### ISSUE TITLE
AeroDyn14 Driver

### ISSUE THREAD

**Issue by sayerhs** [OpenFAST/openfast#1]
AeroDyn14 driver contains `USE AeroDyn_Types` instead of `USE AeroDyn14_Types`. Looks like the code needs to be updated to reflect the changes since introduction of AeroDyn v15.

**Comment by rafmudaf** [comment]
For future reference, I've updated cmake to include aerodyn14_driver in the build and I've updated AD_Driver to use the aerodyn14 types and function calls. However, it looks like updates need to be made to the registry
```
Scanning dependencies of target aerodyn14_driver
[ 95%] Building Fortran object modules-local/aerodyn14/CMakeFiles/aerodyn14_driver.dir/src/AD_Driver.f90.o
/Users/rmudafor/Development/openfast/modules-local/aerodyn14/src/AD_Driver.f90:68:23:

    InitInData%ADOptions%ADFile = 'MyInputFileName.inp'
                       1
Error: 'adoptions' at (1) is not a member of the 'ad14_initinputtype' structure
/Users/rmudafor/Development/openfast/modules-local/aerodyn14/src/AD_Driver.f90:77:67:

    CALL AD14_Init( InitInData, u(1), p,  x, xd, z, OtherState, y, m, TimeInterval, InitOutData, ErrStat, ErrMsg )
                                                                   1
Error: Symbol 'm' at (1) has no IMPLICIT type
/Users/rmudafor/Development/openfast/modules-local/aerodyn14/src/AD_Driver.f90:106:85:

       CALL AD14_CalcOutput( Time, u(1), p, x, xd, z, OtherState, y, ErrStat, ErrMsg )
                                                                                     1
Error: Type mismatch in argument 'm' at (1); passed INTEGER(4) to TYPE(ad14_miscvartype)
/Users/rmudafor/Development/openfast/modules-local/aerodyn14/src/AD_Driver.f90:115:84:

       call AD14_UpdateStates( Time, u(1), p, x, xd, z, OtherState, ErrStat, ErrMsg )
                                                                                    1
Error: Type mismatch in argument 'n' at (1); passed TYPE(ad14_inputtype) to INTEGER(4)
/Users/rmudafor/Development/openfast/modules-local/aerodyn14/src/AD_Driver.f90:127:69:

    CALL AD14_End( u(1), p, x, xd, z, OtherState, y, ErrStat, ErrMsg )
                                                                     1
Error: Type mismatch in argument 'm' at (1); passed INTEGER(4) to TYPE(ad14_miscvartype)
```

This is available at https://github.com/rafmudaf/openfast/tree/bugfix/aerodyn14_driver

**Comment by bjonkman** [comment]
I would be surprised if anyone ever used AD14's driver. I'm pretty sure it was just there to help John compile when he converted AD13 to the FAST modularization framework. It doesn't do anything useful does it? Other than verify that AD14 can compile and possibly run without seg faults? 

ADOptions is probably left over from AD13.

**Comment by rafmudaf** [comment]
@bjonkman no, it doesn't do much. It just calls the AD14 init, calc output and update states over three time steps, and the end method. It doesn't actually read an input file.

In fact, looking at this driver in more detail I'm wondering was it ever actually used to drive a working AD14? It looks if John used it in development he stopped pretty early as the `InitInData` variable which is passed to AD14_Init isn't actually initialized at all.

**Comment by bjonkman** [comment]
I personally would just delete the AD14 driver. AD14 is supposed to be phased out anyway, right?

**Comment by rafmudaf** [comment]
@bjonkman I completely agree.

@michaelasprague @jjonkman @ghaymanNREL any objection to this? I've created a pull request for this at https://github.com/OpenFAST/openfast/pull/92.

On the question of phasing out AD14, I think that deserves its own issue.

**Comment by rafmudaf** [comment]
ps new issue created for ad14 phase out #93
