### ISSUE TITLE
Bug report: Nacelle position set inconsistently by glue code and AeroDyn driver

### ISSUE THREAD

**Issue by hkross** [OpenFAST/openfast#1005]
**Bug description**
Pull request #982 changed the way the AeroDyn nacelle point mesh position was set (from `position = InitInp%HubPosition` to `position = InitInp%NacellePosition`). The nacelle point mesh position is now defined by the tower top (i.e., yaw bearing) location when AeroDyn is driven by OpenFAST. The AeroDyn driver does not output the nacelle position, so it is set to `(0,0,0)` when using the driver. This can be fixed by outputting the nacelle position from the AeroDyn driver (see [this commit](https://github.com/hkross/openfast/commit/2a9507f16f48b4a7dd279c6e9fb1c29e1b998cbe)). However, the driver defines the nacelle position as `(0,0,HubHt+overhang*sin(shftTilt))`, which is not equivalent to the definition that is passed from the glue code. This causes an inconsistent definition of the nacelle mesh position when using the glue code vs driver. This is a problem for the buoyancy calculations (PR #957), since the center of buoyancy of the nacelle is defined by the user relative to the tower top position. 

**Potential solution**
A possible solution is to change the way the nacelle position is set by the AeroDyn driver, but I believe this would require an additional driver input to define the distance between the HubHt and TwrHt.

**Comment by andrew-platt** [comment]
Good catch!  I think the best solution is to add the driver input as suggested and pass that through to AD as the glue-code does.

**Comment by ebranlard** [comment]
(sorry I forgot to answer the comment on the other thread). I agree, I think we would need another input in the AeroDyn driver indeed.
