### ISSUE TITLE
Velocities and Accelerations in AeroDyn Arbitrary Motion CSV file

### ISSUE THREAD

**Issue by lucpavonese** [OpenFAST/openfast#1014]
Dear All,

I am currently working with the Aerodyn driver of openFAST for prescribing motions to a given rotor. I have noticed that the base motion file has 19 columns, which represent the time, position, velocity and acceleration for each degree of freedom. I have then performed a simulation where I was just specifying the motions over each degree of freedom, that is, I set the values for acceleration and velocity as 0. As the simulation ran to completion, then I initially thought that Aerodyn has the capability to perform this sort of calculation internally. 

Nevertheless, I went back to the manual to see whether I could find a better explanation about the point. It is stated in the manual that: 

> The displacements/orientations, velocities, and accelerations are not checked internally for consistency.

 What I understand from this phrase is that Aerodyn takes the values as it is from the base motion input file. So, I imagine that my initial assumption that Aerodyn calculates these accelerations and velocities internally in case they are not specified seems to not really be the case.

Hence, my question is:
- Is there any difference, in terms of the aerodynamic forces calculated by Aerodyn, in setting the base motion file considering only the motions vs specifying the same motions but also adding the velocity and acceleration values for each time interval? 

Thank you in advance.

**Comment by ebranlard** [comment]
Hi @lucpavonese 

The aerodynamic forces will definitely be a function of the relative velocities of the blade, and these relative velocities will not contain the base motion velocities if you don't include these in the base motion file. It is quite important to include them. 
The accelerations could have an impact on some dynamic stall models (if I recall correctly), and would have an important impact if you were simulating a hydrokinetic turbine (in the water). If you are in air, then they would be less important. Nevertheless, if you calculate the velocities using finite differences of the displacement, you might as well compute the accelerations using the velocities. 

We could consider computing them automatically in the future, but currently this is not the case. 

I hope that helps,

Emmanuel

**Comment by fnaos** [comment]
Perfect! Thank you, Emmanuel.

**Comment by lucpavonese** [comment]
Perfect! Thank you very much for the clarification.
