### ISSUE TITLE
How to understand three local wind speed concepts in the Aerodyn OutList.

### ISSUE THREAD

**Issue by ietqlw** [OpenFAST/openfast#1029]
### Discussed in https://github.com/OpenFAST/openfast/discussions/1028

<div type='discussions-op-text'>

<sup>Originally posted by **ietqlw** March  5, 2022</sup>
Hello everyone,

        In the Aerodyn manual, three local wind speed confused me a lot. Would you mind sharing me your views about their differences?
        (1) Undisturbed wind velocity at BαNβ in the local blade coordinate system.
        (2) Disturbed wind velocity at BαNβ in the local blade coordinate system.
        (3) Relative wind speed at BαNβ.
![微信图片_20220305233615](https://user-images.githubusercontent.com/79843558/156890067-e1395cf7-7fb4-4a93-acc4-1e044cef5d2c.png)
 </div>

**Comment by rafmudaf** [comment]
This is a great discussion, but its not an issue. I'm closing here in favor of the discussion #1028.
