### ISSUE TITLE
map_x64.dll is not generated

### ISSUE THREAD

**Issue by abhineet-gupta** [OpenFAST/openfast#1030]
**Bug description**
map_x64.dll is not generated by the visual studio solution.

**To Reproduce*
1. Run Fast.sln with 'Release_Matlab' (x64) solution configuration
2. After successful build (using intel fortran) MAP_x64.pdb and MAP_x64.lib are generated but not MAP_x64.dll

**OpenFAST Version**
OpenFAST 3.1  (hash 3456a645)

**System Information:**
 - OS: Windows 10
 - Compiler: Intel Fortran (Ifort)

**Comment by bjonkman** [comment]
The latest Visual Studio files create MAP as a static library which is then packaged into the final OpenFAST executable, eliminating the need for the MAP DLL file. 

See this pull request: https://github.com/OpenFAST/openfast/pull/763

**Comment by abhineet-gupta** [comment]
Thank you.
