### ISSUE TITLE
Usage question: fixed pitch & rotor speed

### ISSUE THREAD

**Issue by JasonWuTkuTw** [OpenFAST/openfast#1035]
Hi, 

I am wondering if I can fix the blade pitch angle and rotation speed to match my wind tunnel simulation results in FAST? My wind tunnel setup: 1/150 geometrically scaled NREL 5MW wind turbine, 10-deg blade pitch & Tip Speed Ratio = 3.  The upstream condition is generated using TurbSim with Kaimal spectra.  

Thanks

Jason

**Comment by JasonWuTkuTw** [comment]
@jjonkman 

This works.  Thanks a lot. 

Jason

**Comment by redking8000** [comment]
**it is very useful, thanks a lot!**
