### ISSUE TITLE
HydroDyn does not allocate A, B, C matrices, leading to segfault in Jacobian linearization outputs

### ISSUE THREAD

**Issue by ebranlard** [OpenFAST/openfast#1046]
**Bug description**
Setting `LinOutJac=True` and  `LinOutMod=True` in the main fst file will result in a segfault because the A, B ,C matrices of hydrodyn are not allocated when the number of states are 0. 
This issue comes from the statements `if ( p%totalStates == 0 ) return`  present in HydroDyn. 

**Potential options**

1. Make sure the Jacobian functions of HydroDyn always allocate the A, B, C, D matrices. We can simply remove the "if" statements, or for some small performance gains, replace the `if ( p%totalStates == 0 ) return` , with some  `if ( p%totalStates > 0 )  then ...` . This will require a reindentation of the code.  

2. Surround the calls of WrPartialMatrix (in FAST_Lin) with if statement if the matrices are not allocated

3. Change WrPartialMatrix so that it supports unallocated matrices. 

I'd vote for option 1 since I believe other modules like SubDyn always allocate the matrices even if they have a 0 dimension. Let me know your thoughts.

**Comment by ebranlard** [comment]
Removing `if ( p%totalStates == 0 ) return` works fine, should I just do that? That avoids the reindentation of the code.

**Comment by andrew-platt** [comment]
That might work. Looking at the allocation on [line 2588](https://github.com/OpenFAST/openfast/blob/dev/modules/hydrodyn/src/HydroDyn.f90#L2588), the allocation would be `0` by `1` -- we might need to double check that this works with the logic using the `dXdu` array in the glue code.
