### ISSUE TITLE
Cannot run OpenFAST after compiling from source with Microsoft Visual Studio 2019

### ISSUE THREAD

**Issue by hoektc** [OpenFAST/openfast#1052]
**Bug description**
Having built OpenFAST x64 succesfully from source without errors using Visual Studio 2019 on Windows, when I run the generated .exe file, it blinks open a window for a fraction of a second and immediately shuts down. When I run successful x64 debug build in Visual Studio 2019 (F5 while in Visual Studio after building), it does the same and shows the following output:

'openfast_x64.exe' (Win32): Loaded 'D:\openfast\build\bin\openfast_x64.exe'. Module was built without symbols.
'openfast_x64.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'openfast_x64.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'openfast_x64.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'openfast_x64.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. 
'openfast_x64.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'openfast_x64.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'openfast_x64.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
The thread 0x48d8 has exited with code 1 (0x1).
The thread 0x35b8 has exited with code 1 (0x1).
The program '[3504] openfast_x64.exe' has exited with code 1 (0x1).

**To Reproduce**
<Update the following list with your specific information.>
1. Follow the steps here to compile the solution with Microsoft Visual Studio 2019: https://openfast.readthedocs.io/en/main/source/install/install_vs_windows.html
2. Run with F5 in Visual Studio 2019
3. If we have the same issue, you'll see similar output as described above.

**Expected behavior**
I expected the OpenFAST full program GUI to open and function properly

**OpenFAST Version**
FAST v8
git commit: cloned from https://github.com/openfast/openfast.git on 17 march 2022 at 3:25 pm
Fortran compilers / Intel toolkits etc downloaded on that same date as per instructions at https://openfast.readthedocs.io/en/main/source/install/install_vs_windows.html

```
**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.0.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Nov 27 2018
  - Time: 17:19:38
 Execution Info:
  - Date: 11/29/2018
  - Time: 10:52:28-0700
```

**System Information (please complete the following information):**
 - OS: <e.g. Ubuntu 14.04 or macOS 10.12>
 - Compiler: <e.g. GFortran 4.4>
 - Compiler settings: <e.g. CMake flags or other settings>

**Additional context**
<Add any other context about the problem here.>

**Comment by jjonkman** [comment]
Dear @hoektc,

OpenFAST does not currently support a GUI.  So, you cannot run a precompiled OpenFAST executable by pressing F5 or by double clicking on the executable.  Instead, OpenFAST is run from a command prompt.   See, e.g., https://github.com/OpenFAST/openfast/issues/463.

Best regards,
