### ISSUE TITLE
Fast Farm: Bug report

### ISSUE THREAD

**Issue by Tommi1198** [OpenFAST/openfast#1055]
Hi everyone, I have a problem when running fast farm; once I run a simulation succesfully, how can I see the result of the simulation?
I mean, in terms of images of the beahviou of the turbine subjected to the inflow wind?
Thanks a lot!

**Comment by jjonkman** [comment]
Dear @Tommi1198,

FAST.Farm can output time series of various output channels, including wind, wakes, and turbine response.  FAST.Farm can also output visualization data that can be viewed in ParaView or the like.  See the Output Files section of the online FAST.Farm documentation for more information: https://openfast.readthedocs.io/en/main/source/user/fast.farm/OutputFiles.html.

Best regards,

**Comment by Tommi1198** [comment]
I have not the unit D on my computer and I don't know in which file fast farm takes "ReadSetParameters.f90"...where can I found it?

**Comment by jjonkman** [comment]
Dear @Tommi1198,

The source file and variable you refer to are not part of FAST.Farm.  I do see that source file and variable in the ROSCO controller.  I would suggest posting your question on the issues page of the ROSCO github site: https://github.com/NREL/ROSCO/issues.

Best regards,
