### ISSUE TITLE
Where can I get the input and execution's files for openFAST 2.5.0 ? Nothing available on github for this version

### ISSUE THREAD

**Issue by qaa219** [OpenFAST/openfast#1056]
**Is your feature request related to a problem? Please describe.**
<A clear and concise description of the problem.>

**Describe the solution you'd like**
<A clear and concise description of what you want to happen.>

**Describe alternatives you've considered**
<A clear and concise description of any alternative solutions or features youve considered.>

**Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by andrew-platt** [comment]
https://github.com/OpenFAST/openfast/releases/tag/v2.5.0

https://github.com/OpenFAST/r-test/tree/v2.5.0
