### ISSUE TITLE
FAST:Farm

### ISSUE THREAD

**Issue by Tommi1198** [OpenFAST/openfast#1058]
Hi everyone, I encountered this error while running a simulation:

Generator speed:   29.5 RPM, Pitch angle:   0.8 deg, Power:     0.0 kW, Est. wind Speed:  15.6 m/s
Generator speed:   29.5 RPM, Pitch angle:   0.8 deg, Power:     0.0 kW, Est. wind Speed:  15.6 m/s
Generator speed:   29.5 RPM, Pitch angle:   0.8 deg, Power:     0.0 kW, Est. wind Speed:  15.6 m/s
 Time: 18 of 200 seconds.  Estimated final completion at 10:46:12.

T1:FARM_UpdateStates:FWrap_Increment:FAST_Solution:FAST_AdvanceStates:SolveOption2c_Inp2AD_SrvD:In
flowWind_CalcOutput:CalcOutput:IfW_4Dext_CalcOutput [position=(-3.5124, -85.036, 145.7) in
wind-file coordinates]:Interp4D:Outside the grid bounds.
T2:FARM_UpdateStates:FWrap_Increment:FAST_Solution:FAST_AdvanceStates:SolveOption2c_Inp2AD_SrvD:In
flowWind_CalcOutput:CalcOutput:IfW_4Dext_CalcOutput [position=(-3.5124, -85.036, 145.7) in
wind-file coordinates]:Interp4D:Outside the grid bounds.
T3:FARM_UpdateStates:FWrap_Increment:FAST_Solution:FAST_AdvanceStates:SolveOption2c_Inp2AD_SrvD:In
flowWind_CalcOutput:CalcOutput:IfW_4Dext_CalcOutput [position=(-3.5124, -85.036, 145.7) in
wind-file coordinates]:Interp4D:Outside the grid bounds.

 Aborting FAST.Farm.

How is it possible that after 18 seconds the program shows me this type of error? I have never seen it once the simulation has been started...how can I fix it? Thank you very much!

**Comment by jjonkman** [comment]
Dear @Tommi1198,

The error is similar to others you've posted recently, e.g.: https://github.com/OpenFAST/openfast/issues/1044.

If you receive this error at t = 18 s into a simulation rather than right after model initialization (near t = 0 s), this means that the turbine has deflected/displaced enough to trigger the error.  Either your model requires a slightly bigger high-resolution domain to accommodate your turbine deflection/displacement, or the model is experiencing an instability resulting in excessively large deflections/displacements that eventually trigger the error.  I'm not sure what wind turbine(s) you are simulating in FAST.Farm, but given the nodal position = (-3.5124, -85.036, 145.7) m (relative to the tower base at (0,0,0)) and turbine dimensions, is this nodal position expected or a sign that your model has gone unstable?  Plotting the deflections/displacements of the blade and tower (and platform, if relevant) would likely be informative.

Best regards,

**Comment by Tommi1198** [comment]
Dear @jjonkman , how can I plot the deflections of blades and towers if the simulation was interrupted? What kind of file of output I have to use and with which program? (I thought about MATLAB, but I do not have the <filename>.out since the simulation cannot be completed).
Thanks a lot!

**Comment by jjonkman** [comment]
Dear @Tommi1198,

When you select `OutFileFmt` = 1 in the OpenFAST primary (_*.fst_) input file, OpenFAST will generate the _*.out_ output file from model initialization through the time which OpenFAST is terminated.  You can plot the results however you want, including Excel, MATLAB, pyDatView, etc.

Best regards,

**Comment by Tommi1198** [comment]
Dear @jjonkman , I tried to plot the deflections of blades and tower, and I obtain the following results:
- maximum tower-top fore-aft defelction = 0.12 m
- maximum blade out-of-plane tip deflection = 1.2 m
- maximum blade in-plane tip deflection = 0.6 m
The turbine that I'm using is the DTU10MW wind turbine
Are these values acceptable or are they too high for my problem experienced?
Thank you very much!

**Comment by jjonkman** [comment]
Dear @Tommi1198,

These deflections are quite reasonable and do not suggest a problem with your OpenFAST model.  Can you clarify how you've set the extend of the high-resolution domain relative to the turbine size?  Are you leaving enough buffer in the size of the high-resolution domain to accommodate typical turbine deflection?

Best regards,

**Comment by Tommi1198** [comment]
Dear @jjonkman , I have to do a correction...maximum blade in-plane tip deflection = 1 m
Is it still acceptable?

**Comment by jjonkman** [comment]
Dear @Tommi1198,

Yes, 1-m is still a reasonable in-plane blade deflection.

You didn't share the origin and size of the high-resolution domains, which are defined in the WIND TURBINES table, beginning on line 36 of the FAST.Farm (_*.fstf_) input file.

Best regards,

**Comment by Tommi1198** [comment]
Dear @jjonkman , these are the lines requested by you:

 3          NumTurbines   Number of wind turbines (-) [>=1] [last 6 columns below used only for Mod_AmbWind=2 or 3]
 WT_X    WT_Y     WT_Z   WT_FASTInFile                                                                                              X0_High Y0_High  Z0_High dX_High dY_High dZ_High
 (m)     (m)      (m)      (string)                                                                                                   (m)     (m)      (m)     (m)     (m)     (m)
 605.0   1500.0   0.0    "C:\Users\berna\Desktop\ProvaDTU10MW\FAST30\DTU_10MW_RWT_OpenFast_3_0\DTU10MW_Onshore_Ctrl_30.fst"          525.0   1425.0    5.0    10.0    10.0    10.0
 605.0   1500.0   0.0    "C:\Users\berna\Desktop\ProvaDTU10MW\FAST30\DTU_10MW_RWT_OpenFast_3_0\DTU10MW_Onshore_Ctrl_30_Copia.fst"    525.0   1425.0    5.0    10.0    10.0    10.0
 605.0   1500.0   0.0    "C:\Users\berna\Desktop\ProvaDTU10MW\FAST30\DTU_10MW_RWT_OpenFast_3_0\DTU10MW_Onshore_Ctrl_30_Copia2.fst"   525.0   1425.0    5.0    10.0    10.0    10.0

Thank you very much!

**Comment by Tommi1198** [comment]
Dear @jjonkman , these are the lines requested by you:

3          NumTurbines   
WT_X    WT_Y     WT_Z      WT_FASTInFile                                                      
 (m)       (m)       (m)              (string)
605.0   1500.0   0.0            "...\DTU10MW_Onshore_Ctrl_30.fst"
605.0   1500.0   0.0           "...\DTU10MW_Onshore_Ctrl_30_Copia.fst"
605.0   1500.0   0.0           "...\DTU10MW_Onshore_Ctrl_30_Copia2.fst"

X0_High Y0_High  Z0_High dX_High dY_High dZ_High
  (m)            (m)         (m)          (m)        (m)        (m)
525.0        1425.0      5.0         10.0       10.0       10.0
525.0        1425.0      5.0         10.0       10.0       10.0
525.0        1425.0      5.0         10.0       10.0       10.0

Thank you very much!

**Comment by Tommi1198** [comment]
Dear @jjonkman , don't worry, finally I solved the problem! If I will have other issues I will write on the forum.
Thank you very much!

**Comment by Tommi1198** [comment]
Dear @jjonkman , I now tried to run a simulation with the super controller active, but it gave me this error:
FAST.Farm-v3.0.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 1900
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: Jun 23 2021
 - Time: 21:41:28
Execution Info:
 - Date: 03/28/2022
 - Time: 16:48:43+0200

 Heading of the FAST.Farm input file:
    Sample FAST.Farm input file
Running AWAE.
Running InflowWind.
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source

How can I fix it? Thanks a lot

**Comment by jjonkman** [comment]
Dear @Tommi1198,

I'm not sure I understand why you are setting up your FAST.Farm model the way you have.  It appears that you've placed all three wind turbines at the exact same location and all three high-resolution domains are overlapping.  Is this what you intended to do?  Please clarify.

Regarding the super controller, do you only get this error when enabling the super controller?  Or is the problem identical to the one you reported earlier: https://github.com/OpenFAST/openfast/issues/1044?  If the problem only occurs when the super controller is enabled, can you clarify how you are setting up the super controller?  Are you using an example super controller provided by NREL or something you implemented yourself?

Best regards,

**Comment by Tommi1198** [comment]
Dear @jjonkman , regarding the first question you are right, I made a mistake (I will try to run the simulation adjusting the reference grid)
Regarding the second question on the supercontroller, the error is shown only when enabling it, and I'm using the example provided by NREL; what can I do to fix the error?
