### ISSUE TITLE
Help on explanation of the differences between the FAST- and WT-simulated thrust forces

### ISSUE THREAD

**Issue by JasonWuTkuTw** [OpenFAST/openfast#1066]
Hi, 

We have been trying to figure out the reasons causing the difference in the time-averaged thrust coefficients of the NREL 5MW wind turbine obtained from wind tunnel experiments and FAST simulations.  We use the 1/150 geometrically scaled model in the atmospheric boundary layer wind tunnel. Similarities are controlled on: (i) Tip Speed Ratio (TSR), (ii) the blade pitch angle, and (iii) the upstream turbulent wind conditions. For the 10-deg blade pitch angle and TSR = 3.17, the FAST-simulated thrust coefficient (about 0.25) is nearly 3 times the wind tunnel model.  

Is there any comment/reference to explain the difference?  

Thanks 

Jason Wu

**Comment by jjonkman** [comment]
Dear @JasonWuTkuTw,

How does the Reynolds number compare between the FAST simulations and the wind tunnel experiment?  Are you using airfoils in the wind tunnel that are appropriate, considering the likely of a Reynolds number mismatch?

Best regards,

**Comment by JasonWuTkuTw** [comment]
Dear @jjonkman 

Thanks for your comment.  

Yes, I just realize the Reynolds number can play a significant role, and some papers even adjust the model airfoil shapes and/or dimensions to compensate effects of Reynolds number to match the overall forces. If I wish to use FAST to simulate the Low-Reyolds scenario (i.e., the Wind Tunnel simulations), can I just modify the airfoil aerodynamic coefficients accordingly in the *.dat file for AeroDyn (e.g., NACA64_A17.dat)? Or should I do something more? If that's the case, is there any aerodynamic data of the NREL 5MW airfoils measured under low Reynolds numbers, or can I go to some open software, e.g., XFoil, to obtain corresponding data?  

The other thing I found is my misunderstanding of the definition of pitch angle.  We thought it was based on the root sectional pitch angle but in fact, it is based on tip sectional pitch. Just want to confirm this point as well. 

Very appreciate your help, 

Jason

**Comment by jjonkman** [comment]
Dear @JasonWuTkuTw,

Yes, to account for low-Reynold's number in FAST / OpenFAST, you should change the airfoil data (or use airfoil data with Reynolds-number dependence and `AFTapMod` = 2 (2D interpolation on AoA and Re) in AeroDyn v15).  But I'm not familiar with what airfoil data exists at different Reynolds numbers for the DU and NACA airfoils used by the NREL 5-MW baseline wind turbine.  Again, it is common to use airfoils appropriate for low Reynolds number conditions in wind tunnel tests.

The pitch angle in the NREL 5-MW specifications report follows the convention used by OpenFAST: the pitch angle is defined relative to zero twist, such that the angle between the rotor plane and the chordline is the sum of the pitch and twist angles (including any elastic twist).

Best regards,

**Comment by JasonWuTkuTw** [comment]
Dear @jjonkman 

Thank you very much. Your insights are very helpful. 

Jason
