### ISSUE TITLE
Regression test fail

### ISSUE THREAD

**Issue by tolgasarikaya** [OpenFAST/openfast#1070]
Hi everyone,
I am completely new on github and OpenFAST. I am tring to do regression test with visual studio but some of them fails.
I am using windows 10, visual studio 2019 community edition and python v3.9.7(numpy and matplotlib libraries are installed).
I have followed to instructions in the documentation and it came out as follows;

![A1](https://user-images.githubusercontent.com/101410787/160841025-8e7df50b-8851-472e-b7f6-654cd0b4542e.jpg)

What could be the problem? Thank you for your answers.

**Comment by xiaoyangzhan** [comment]
> 

@rafmudaf

**Comment by xiaoyangzhan** [comment]
@rafmudaf

**Comment by ILDENIEL** [comment]
Hi, I'm having the same problems but most of the tests failed, even though I only downloaded the precompiled binaries.
Since I will have to change the code, how can I solve the problem? I also installed bokeh (as said in another issue) but still, there're problems.

**Comment by rafmudaf** [comment]
@ILDENIEL what did you try and what was the result? Please post the commands you used to debug the issue as well as the output. If there are a series of steps you took along the way that would help to describe your story, please include that, as well.

**Comment by ILDENIEL** [comment]
@rafmudaf I tried to explain the issue here
https://github.com/OpenFAST/openfast/issues/1462
