### ISSUE TITLE
Missing outputs using AeroDyn14

### ISSUE THREAD

**Issue by ElioDaka** [OpenFAST/openfast#1076]
Hello everyone,

I am using an AeroDyn v.14 input file to run some simulations in OpenFast v2.4.0. My problem is that the outputs listed in the outlist section in the AeroDyn input file do not appear in the .out file. During the simulation I don't have any error message but those outputs are missing, and I find only the ones coming from ElastoDyn and Inflow. How can I solve this issue? I attach the AeroDyn input file that I am using. Thank you!
Elio

[AeroDyn.txt](https://github.com/OpenFAST/openfast/files/8397457/AeroDyn.txt)

**Comment by jjonkman** [comment]
Dear @ElioDaka,

AeroDyn v14 does not support the `OutList` section of the input file.  The `OutList` section of the AeroDyn input file is only supported by AeroDyn v15.  In AeroDyn v14, outputs are determined by `PrnElm` column of the distributed aerodynamic data table, i.e., by selecting `PRINT` or `NOPRINT`.  In your case, it looks like you've selected `PRINT` for all blade elements.  The corresponding aerodynamic data at each element should be written to a separate output, distinct from the output file containing outputs from ElastoDyn and InflowWind.

Best regards,

**Comment by ElioDaka** [comment]
Thank you @jjonkman! 

I didn't know that the output list was not supported in AerDyn v14. 

Best regards.
