### ISSUE TITLE
Can BeamDyn in FAST V8 meet the requirement for the flutter analysis and control of bending–torsion coupling of wind turbine blade？

### ISSUE THREAD

**Issue by ietqlw** [OpenFAST/openfast#1077]
Dear all，

I plan to carry out the bending–torsion coupling flutter analysis and control of wind turbine blades. I have learnt that BeamDyn included the torsional analysis of blade. 

How about the reliability of using FAST V8 with BeamDyn to analyze bending–torsion coupling flutter? 

And how about the control of using blade pitch or trailing edge flaps to damp bending–torsion coupling flutter?

**Comment by jjonkman** [comment]
Dear @ietqlw,

Yes, when BeamDyn is enabled, you can accurately model blades with bend-torsion coupling, including flutter.  That said, there have been many improvements to BeamDyn and AeroDyn in OpenFAST since FAST v8 (including a recent improvement to BeamDyn here: https://github.com/OpenFAST/openfast/pull/1050), so, I would recommend using the newest version of OpenFAST instead of FAST v8.

BeamDyn can be used with either blade-pitch control considered in ServoDyn or trailing edge flaps considered in AeroDyn and ServoDyn.

Best regards,

**Comment by ietqlw** [comment]
Dear @jonkman,

Thank you for your careful answer.

While employing OC4-DeepCwind semi-submersible 5MW wind turbine, I noticed that all aerodata are measured at Re = 0.75*10^6. Howerer, blade airfoil section might work at higher Reynolds numbers when exposing to higher wind speed. Have Openfast or FAST V8 already considered the effect of Reynolds numbers on the aerodynamics?

Recently, we have carried out a wind tunnel test to measure the aerodynamic parameters CL, CD, CM of NACA64618 airfoil which is equipped with deformable trailing edge flaps. AirfoilPrep was used to extend the aerodynamic parameters. Then we activated the MulTabLoc in AeroDyn and employ the extended aerodynamic parameters from the wind tunnel test. The Reynolds number in our wind tunnel test is 0.62*10^6. 

Would you mind sharing me with your views about how much effect the Reynolds numbers of airfoils in FAST have on the wind turbines?

**Comment by jjonkman** [comment]
Dear @ietqlw,

AeroDyn v14 supports 1D interpolation (AoA only) and 2D interpolation (AoA and Re or control) based on the `MulTabLoc` option.

AeroDyn v15 supports 1D interpolation (AoA only), 2D interpolation (AoA and Re), and 3D interpolation (AoA, Re, and control) through the `AFTabMod` option.  We generally recommend upgrading from AeroDyn v14 to AeroDyn v15 given the superior aerodynamic modeling capability of AeroDyn v15.  We intend to deprecate AeroDyn v14 soon...

Certainly the Re number can change during variable speed operation of a wind turbine; whether these effects are important or not likely depends on the range of Re, the sensitivity of the airfoil to Re, and the desired accuracy of the output, considering the inherent limitations of the aerodynamic models used.

Best regards,

**Comment by zhangtopus** [comment]
Dear  @jonkman,，

I plan to carry out the same work by ietqlw. I have some questions about Beamdyn .

Can BeamDyn in OpenFAST implement eigenvalue analysis of wind turbine blade？

And how to obtain the modal of the blade through OpenFast？

Best regards,

**Comment by zhangtopus** [comment]
Dear  @jjonkman,，

I plan to carry out  same work with ietqlw. I have some questions about Beamdyn .

Can BeamDyn in OpenFAST implement eigenvalue analysis of wind turbine blade？

And how to obtain the modal of the blade through OpenFast？

Best regards,

**Comment by jjonkman** [comment]
Dear @zhangtopus,

Yes, the linearization functionality of OpenFAST can be used when BeamDyn is enabled.  This will allow OpenFAST to generate a linearized state-space representation of the wind turbine, including BeamDyn inputs, outputs, and states amongst other OpenFAST modules.  Eigenvalue analysis of the state matrix "A" can be use d to compute full-system eigensolutions of OpenFAST models with BeamDyn enabled, including full-system mode shapes, natural frequencies, and damping.  The eigenanalysis approach has been discussed many times before, and is documented here: https://github.com/OpenFAST/matlab-toolbox.

As I suggested to @ietqlw, I'd recommend using the updated version of BeamDyn with recent fixes applicable to linearization: https://github.com/OpenFAST/openfast/pull/1050.

Best regards,

**Comment by zhangtopus** [comment]
Dear @jjonkman,

Thanks for your answer.

Best regards,

**Comment by ietqlw** [comment]
Dear @jjonkman,

Sorry for disturbing you again. I have ever implemented trail edge flaps with AeroDyn14 and analyzed their potential of the load redutions on wind turbines. Following your suggestions, I integrate trailing edge flaps to AeroDyn15 through the `AFTabMod` option. 
In order to make the most of AeroDyn15 for analyzing the effects of trailing edge flaps, may I ask what the detailed benefits of AeroDyn15 are with regards to AeroDyn14? 

Best regards

**Comment by jjonkman** [comment]
Dear @ietqlw,

AeroDyn v14 is now quite outdated and will be deprecated from OpenFAST soon.  AeroDyn v15 represents a complete overhaul from earlier version of AeroDyn to (1) fix underlying problems with the original theoretical treatments, (2) introduce improved aerodynamic physics, (3) enable modeling of highly flexible and non-straight blades, and (4) support the unique features of the OpenFAST modularization framework.

Best regards,
