### ISSUE TITLE
"The C++ compiler "/usr/bin/c++.exe" is not able to compile a simple test program" on Windows 10 with Cygwin 64

### ISSUE THREAD

**Issue by pfeja** [OpenFAST/openfast#108]
I tried to compile OpenFAST asper the [documentation](http://openfast.readthedocs.io/en/master/source/install/install_cmake_cygwin.html). I followed all steps one-by-one, but when I try to do the actual compilation, CMake fails with:

```
$ FC=gfortran cmake ../
-- The CXX compiler identification is GNU 6.4.0
-- The C compiler identification is GNU 6.4.0
-- The Fortran compiler identification is GNU 6.4.0
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- broken
CMake Error at /usr/share/cmake-3.6.2/Modules/CMakeTestCXXCompiler.cmake:54 (message):
  The C++ compiler "/usr/bin/c++.exe" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /home/FejPau/code/OpenFAST/build/CMakeFiles/CMakeTmp



  Run Build
  Command:"/cygdrive/c/opal-rt/rt-lab/v11.2.1.100/common/bin/gmake.exe"
  "cmTC_af8f7/fast"

  C:\opal-rt\rt-lab\v11.2.1.100\common\bin\gmake.exe -f
  CMakeFiles/cmTC_af8f7.dir/build.make CMakeFiles/cmTC_af8f7.dir/build

  gmake.exe: command not found: /bin/sh

  gmake.exe: *** [cmTC_af8f7/fast] Error 0x7f





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:18 (project)


-- Configuring incomplete, errors occurred!
See also "/home/FejPau/code/OpenFAST/build/CMakeFiles/CMakeOutput.log".
See also "/home/FejPau/code/OpenFAST/build/CMakeFiles/CMakeError.log".
```

I attached CMakeOutput.log and CMakeError.log.

The strange thing is, when looking at CMakeError.log, it calls gmake.exe from `C:\opal-rt\rt-lab\v11.2.1.100\common\bin\gmake.exe`. I tried to remove this folder from the PATH environment variable, but it still tries to run gmake.exe from there.

I can't uninstall rt-lab because I need this for another project.

What else can I try?

[CMakeError.log](https://github.com/OpenFAST/openfast/files/1890163/CMakeError.log)
[CMakeOutput.log](https://github.com/OpenFAST/openfast/files/1890164/CMakeOutput.log)

**Comment by sayerhs** [comment]
Do you have GNU `gcc` and `g++` compilers installed? If so, you can nudge CMake to use those similar to how you have asked it to use `gfortran`

```
CC=gcc CXX=g++ FC=gfortran cmake ../
```

**Comment by pfeja** [comment]
I just tried this, but I get the same error.

**Comment by rafmudaf** [comment]
@pfeja you can verify the compilers that CMake is using by looking in `CMakeCache.txt`. For example, 
```
mbp@~/Development/openfast/build: grep -ni "cxx" CMakeCache.txt 
86://CXX compiler
87:CMAKE_CXX_COMPILER:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
90:CMAKE_CXX_FLAGS:STRING=
93:CMAKE_CXX_FLAGS_DEBUG:STRING=-g
97:CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
100:CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
103:CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
603://ADVANCED property for variable: CMAKE_CXX_COMPILER
604:CMAKE_CXX_COMPILER-ADVANCED:INTERNAL=1
605://ADVANCED property for variable: CMAKE_CXX_FLAGS
606:CMAKE_CXX_FLAGS-ADVANCED:INTERNAL=1
607://ADVANCED property for variable: CMAKE_CXX_FLAGS_DEBUG
608:CMAKE_CXX_FLAGS_DEBUG-ADVANCED:INTERNAL=1
609://ADVANCED property for variable: CMAKE_CXX_FLAGS_MINSIZEREL
610:CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
611://ADVANCED property for variable: CMAKE_CXX_FLAGS_RELEASE
612:CMAKE_CXX_FLAGS_RELEASE-ADVANCED:INTERNAL=1
613://ADVANCED property for variable: CMAKE_CXX_FLAGS_RELWITHDEBINFO
614:CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
mbp@~/Development/openfast/build: 
```
Could you verify that you are indeed using the c++ compiler you expect?

If CMake did not pick up gcc, try deleting `CMakeCache.txt` and running CMake again.

**Comment by rafmudaf** [comment]
And FYI you can also see the other compilers by searching for `cmake_c_compiler` and `cmake_fortran_compiler`.

**Comment by pfeja** [comment]
After temporarily renaming the opal-rt directory, deleting the `CMakeCache.txt` file and running `cmake` with your recommended settings, and additionally, with `-DCMAKE\_INSTALL\_PREFIX:PATH=$HOME/software`, it compiles and runs when running inside the Cygwin Shell.

But then I added the `C:\cygwin64\lib\lapack` and `C:\cygwin64\home\FejPau\software\bin` to my `PATH` in the Control Panel and tried to run `openfast -h` from Command prompt and it complains about not finding all the Cygwin DLL files like `cygwin1.dll`

![2018-04-12 11_21_42-eingabeaufforderung - openfast -h](https://user-images.githubusercontent.com/38217386/38668557-73c7080a-3e44-11e8-8878-d5885bfe4d04.png)

What am I missing now?

**Comment by pfeja** [comment]
I have created a workaround to run openfast from the Command prompt. I have created a .sh script reading 
``#!/bin/bash`` 
``openfast $@``
and a corresponding .bat file with 
``bash run_openfast.sh myfile.fst``
This helps, but doesn't solve the issue itself. Any ideas on this?

**Comment by rafmudaf** [comment]
@pfeja Am I understanding correctly that you are trying to run the OpenFAST executable which you compiled in CygWin from the Windows Command Prompt?

**Comment by rafmudaf** [comment]
If so, you must run anything compiled by CygWin within the CygWin terminal. This is from the [CygWin website](http://www.cygwin.com):
```
Cygwin is not:

a way to run native Linux apps on Windows. You must rebuild your application from source if you want it to run on Windows.
a way to magically make native Windows apps aware of UNIX® functionality like signals, ptys, etc. Again, you need to build your apps from source if you want to take advantage of Cygwin functionality.
```

I believe this issue is resolved so I'm closing it, but @pfeja feel free to open it again, if necessary.

**Comment by yugoo90** [comment]
Hi, 
I am experiencing same issue as above. I am running a WSL ubuntu distro and using vsCode as my text editor. 
Any help I could get on how to resolve this issue would be very much appreciated.
