### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tommi1198** [OpenFAST/openfast#1080]
Hi everyone, I don't know if anyone can help me, but I have to reproduce the instantaneous flow visualization of XY planes regarding a simulation done in FAST.Farm with 2 wind turbines...I have to replicate, for my application, the following graph on MATLAB, but I don't know how to do it. Can anyone help me please? 
Thank you very much!

![image](https://user-images.githubusercontent.com/100277465/161976599-517873e7-8d28-4b03-b653-3294df0aeb88.png)

**Comment by jjonkman** [comment]
Dear @Tommi1198,

The visualization functionality of FAST.Farm allows FAST.Farm to output visualization data in VTK format, which you can then visualize in ParaView or the like.  This was how the image you share was generated.  See the online FAST.Farm documentation for more information: https://openfast.readthedocs.io/en/main/source/user/fast.farm/InputFiles.html.

Best regards,
