### ISSUE TITLE
Modifying the aerodynamic data of the blade sections 

### ISSUE THREAD

**Issue by JasonWuTkuTw** [OpenFAST/openfast#1084]
Hi, 

We're trying to modify the aerodynamic coefficients of the blade sections in  5MWBaseline/Airfoil/*.dat  files to account for Reynolds number effects in the wind tunnel simulations of our 1/150 geometrically scaled NREL 5 MW turbine model.  However, we think simply replacing the new aerodynamic coefficients may not be enough to tell FAST to correctly reflect the overall thrust coefficient. We tried changing the aerodynamic coefficients to zeros but the resulted time-averaged thrust coefficient increased by 100% instead of reducing to zero.  We're wondering if it is due to the inclusion of unsteady aerodynamic data so we also tried to turn off this option by setting 'InclUAdata'  to  False  in the  blade_shape.dat  files.  However, this leads to a fatal error in running 'AirfoilInfo' at line #17, where the variable "NumAlf" was not found.  

Any suggestions are appreciated. 

Thanks, 

Jason Wu

**Comment by jjonkman** [comment]
Hi @JasonWuTkuTw,

Regarding your error, I'm guessing there is something wrong with the formatting of your airfoil data input file, but you'd have to share your file(s) to comment.

Please note that to disable unsteady airfoil aerodynamic entirely, you should set `AFAeroMod` = 1 in the AeroDyn v15 primary input file.

If the aerodynamic coefficients are zero and unsteady airfoil aerodynamics are disabled, I would expect that you'd have zero aerodynamic thrust (AeroDyn v15 output `RtAeroFxh` = 0).

Best regards,

**Comment by JasonWuTkuTw** [comment]
Dear @jjonkman 

We really appreciate your help. Changing AFAeroMod = 1  in AeroDyn v15 is exactly what we need. 

Here are a few more questions regarding the AeroDyn15 inputs/outputs and wondering if you have any suggesion? 

We're trying to look at the angle of attack and axial induction factors for each section of blade 1. 

- For angles of attack (AOA), we added 'B1N1Alpha', 'B1N2Alpha,' ... , 'B1N9Alpha' in the Output section of AeroDyn15 Input file, for nodes 1, 2, ... & 9, respectively. The time-averaged result of AOAs shows high angles of attack for the nodes 1, 2 and 3 but the zeros for the rest. These results are identical when we change all the blade aerodynamic coefficients to zeros. Just wondering if we're getting the correct values of AOAs? 

- For the axial induction factors (AIF), we added 'B1N1AxInd', 'B1N2AxInd', ..., 'B1N9AxInd' to the Output section of AeroDyn15 Input file, for nodes 1, 2, ..., & 9, respectively.  The time-averaged result of AIFs shows zero values.  Just wondering if we're correct on AIFs? 

- For both AOA and AIF, only up to 9 nodes are available for output.  We are not sure what are radial locations of these nodes. The NREL 5MW blade has 17 radial sections and are inconsistent if only 9 nodes are used.  Just wondering if there is any advice? 

Thanks, 

Jason Wu

**Comment by jjonkman** [comment]
Dear @JasonWuTkuTw,

Regarding your AOA/Alpha and AIF/AxInd results, have you set `NBlOuts` = 9?  Which blade analysis nodes have you selected as output nodes via `BlOutNd`?  (The up-to-nine output nodes are user-selectable via AeroDyn v15 inputs `NBlOuts` and `BlOutNd`.)  See the AeroDyn v15 documentation for more information: https://openfast.readthedocs.io/en/main/source/user/aerodyn/input.html#outputs.

If you want to output airfoil data at more than the the nine nodes available via `NBlOuts` and `BlOutNd`. you can use the nodal outputs option of AeroDyn v15 as documented here: https://openfast.readthedocs.io/en/main/source/user/aerodyn/input.html#nodal-outputs.

Best regards,

**Comment by JasonWuTkuTw** [comment]
Dear @jjonkman 

Modifying  NBlOuts = 9  and  BlOutNd  to the desired node numbering in AeroDyn v15 gives more reasonable results. 

Very appreciated. 

Jason Wu
