### ISSUE TITLE
Feature request-How to close the centrifugal effect on the blade deformation in BeamDyn?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1085]
Hello every one:

I want to conduct a comparison of the blade deflection with and without centrifugal effect by using AeroDyn + BeamDyn, and I am wondering about how to close the centrifugal effect on the blade deformation in BeamDyn?

Thank you for your attention on this issue.

**Comment by jjonkman** [comment]
Dear @ZL6462,

Are you asking about eliminating the centrifugal effect while modeling a rotating rotor, or is the rotor parked?  I'm not sure why you'd want to do the former.

When the rotor is rotating, centrifugal effects (as well as other blade kinematic/kinetic effects) are intrinsic to BeamDyn's formulation of the equation of motion, and so, cannot be readily disabled.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman 

Thank for your answer, I am  asking about eliminating the centrifugal effect while modeling a rotating rotor, and your answer is useful.

Best regards,
