### ISSUE TITLE
Feature request -- How to increase the number of output nodes of BeanDyn, to make it large than 9?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1087]
Dear all,

I want to increase the number of output nodes of BeanDyn to export the all spanwise data with one simulation. Now the maximum output channel is 9, and I am wondering how to increase it? Maybe through the modification of the source codes, but I don't know which codes need to be modified。

Thank you for your attention.

**Comment by jjonkman** [comment]
Dear @ZL6462,

Actually, the functionality you are requesting is already supported by BeamDyn.  See the documentation here: https://openfast.readthedocs.io/en/main/source/user/beamdyn/input_files.html#nodal-outputs.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman ,

Thank you for your reply, I have get all the span data with your instruction.
Best regards,
