### ISSUE TITLE
Feature request --  How to get the blade torsional deflection data after the simulation by using AeroDyn+BeamDyn?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1091]
Dear all,

I want to get the blade torsional deflection data after the simulation by using  AeroDyn+BeamDyn, however the data provided by the BeamDyn output only include the "Wiener-Milenkovic parameter". 

(1) I am wondering that whether it is reliable to convert the Wiener-Milenkovic parameter to rotation angle by the Equations about the "Wiener-Milenkovic parameter" provided by the "BeamDyn Theory" . 

(2) Besides, I also wondering that dose the "Theta" parameter provided by AeroDyn considering the rotational deflection of the blade?

Thank you for you attention.

**Comment by jjonkman** [comment]
Dear @ZL6462,

A similar question was asked and answered on our forum--see: https://forums.nrel.gov/t/extract-blade-tip-torsional-deformation-from-the-wiener-milenkovic-parameters-in-beamdyn/2101/4.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman ,

Actually, thank you for your response, and I have making some comparison, according to the comparison I made, the "Theta" parameter provided by AeroDyn does consider the rotational deflection.

Best regards,
