### ISSUE TITLE
Question about the code concerning Newman's approximation

### ISSUE THREAD

**Issue by Lucas-Carmo** [OpenFAST/openfast#1096]
Hello everyone,

I am trying to run some simulations with Newman's approximation using a WAMIT .8 file, but I get an error saying that the input is too sparse for the interpolation routine.  I found a post dealing with a similar issue on the forum (https://forums.nrel.gov/t/second-order-file-wavedir-boundary-check-issue/1454), but the directions are fully populated in my .8 file and the bug pointed out in that post was already fixed (I am using v3.1.0), so my problem is something else.

After trying to figure out what was wrong with my data, I decided to that a look at the `WAMIT2.f90` file and found something in the the subroutine `SUBROUTINE Read_DataFile3D` that did not make sense to me, so I was hoping that someone could please explain this part to me. It is the code below, which is used to account for the fact that only half of the matrix is given by WAMIT due to symmetry:
```                            
! Check if not filled
DO J=1,Data3D%NumWvDir1
  DO K=J,Data3D%NumWvDir2
!!
!! some stuff
!!
     IF ( .NOT. Data3D%DataMask( I, J, K, L )  ) THEN
    
           ! See if the diagonal mirror one (WvDir2,WvDir1) value is not filled,
           ! and fill it if empty
        IF ( Data3D%DataMask( I, K, J, L )  ) THEN
           Data3D%DataSet ( I, K, J, L ) = Data3D%DataSet( I, J, K, L )
           Data3D%DataMask( I, K, J, L ) = .TRUE.
        ENDIF
!!
!! Lots of ENDs
!!
```
What I don't get is:
1) In the first `IF`, I don't understand why we are checking if the direction pair (J, K) is empty, since we would need this one to fill the (K,J) pair some lines below;
2) In the second `IF`, I would expect a `.NOT.` to check if the element is empty, and I think that in this case we are actually checking if it is filled.

I did some tests replacing these two `IF` statements by:

```
IF ( Data3D%DataMask( I, J, K, L )  ) THEN

     ! See if the diagonal mirror one (WvDir2,WvDir1) value is not filled,
     ! and fill it if empty
  IF ( .NOT. Data3D%DataMask( I, K, J, L )  ) THEN
```

and I got rid of the sparse matrix error, but I am not sure if this modification is correct. 

Thanks in advance for any help!

(I wasn't sure whether I should post it here or on the forum, so I apologize if this is the wrong place)

**Comment by Lucas-Carmo** [comment]
Hello,

I was wondering if I could open a pull request with the code changes shown in my previous comment. Since I couldn't find a test case that uses Newman's approximation in the repo, I thought about doing some tests with a bottom mounted cylinder, which is a problem with analytical solution for the second-order wave diffraction forces. 
BR

**Comment by andrew-platt** [comment]
Dear @Lucas-Carmo,

My apologies for the delay in getting to this.  I did the original implementation of this code about 8 years ago.  Since only one half of the matrix needs to be specified, the intent of this bit of code was to populate the other half using the values read in.  This bit of code is supposed to then populate the other half it is not already populated.  I think you have identified a bug with the implementation of this and have a very good solution for it!

We would really appreciate a pull-request with your fix for this.   In your PR, simply reference this issue number and I will see that it gets merged.

Thank you!
Andy

**Comment by Lucas-Carmo** [comment]
Dear @andrew-platt 

Don't worry, I know you guys have a lot to do and I imagine how hard it is to maintain this repo. 

Great, I will be glad to do it! This might sound silly, but I have been working with OpenFAST/FAST for quite some time now and I have been waiting for the moment to make a contribution, even such a small one :smile:

BR,
Lucas
