### ISSUE TITLE
Feature request -- How to change the position of pitch axis when coupling the BeamDyn and AeroDyn?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1099]
Dear all,

When I make simulations with BeamDyn + AeroDyn, I am wondering that how to change the position of pitch axis. 

Thank you for your attention!

**Comment by jjonkman** [comment]
Dear @ZL6462,

In OpenFAST, the pitch axis is defined in ElastoDyn by the rotor geometry.  That is, the pitch axes of each blade intersect at the rotor apex.  The rotor apex is located by ElastoDyn inputs `OverHang`, `ShftTilt`, etc.  The pitch axes can be preconed away from the rotor plane via ElastoDyn input `PreCone(1-3)`.

The structural and aerodynamic nodes in BeamDyn and AeroDyn are specified relative to this pitch axis.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman  ,

My aim is to change the relative position of the aero center and pitch axis center of each blade element. As you said, I can find the definition of the pitch axis position in the file "NRELOffshrBsline5MW_Blade.dat", which is called by "NRELOffshrBsline5MW_Onshore_ElastoDyn_BDoutputs.dat", but the question is when I use BeamDyn + AeroDyn to calculate the blade deformation, the file "NRELOffshrBsline5MW_Blade.dat" may not been used. Because even I have deleted the "NRELOffshrBsline5MW_Blade.dat" the simulation can still be carried out. So I guess that the position of the pitch axis defined in "NRELOffshrBsline5MW_Blade.dat" is not used by BeamDyn.

Best regards,

**Comment by jjonkman** [comment]
Dear @ZL6462,

I didn't say that you "can find the the definition of the pitch axis position in the file _NRELOffshrBsline5MW_Blade.dat_" file.  Instead, as I mentioned above, the pitch axis is defined by the rotor apex location and precone, which is specified in the ElastoDyn primary input file (which in your case is specified in the _NRELOffshrBsline5MW_Onshore_ElastoDyn_BDoutputs.dat_ file).

The input parameter _PitchAxis_ in the ElastoDyn blade input file (_NRELOffshrBsline5MW_Blade.dat_) is not used when AeroDyn v15 is enabled, and as you said, the ElastoDyn blade input file itself is not used when BeamDyn is enabled.  When AeroDyn v15 is enabled (which is require when BeamDyn is enabled), the aerodynamic center is specified in the AeroDyn blade input file relative to the pitch axis.  For more information on the rarely used _PitchAxis_ input, see the recent discussion on our forum: https://forums.nrel.gov/t/nrel-5mw-rotor-geometry/330/19.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman ,
 
Thank your for your quick answer. 

I have read the discussions on NREL forum, and I have known that the aerodynamic center I mentioned may be the reference point used in FAST manual.

However, I still have one question, what is the relationship between the position of aerodynamic center (or the reference point ) and the PitchAxis? Is it still meet the equation "PitchAxis = 0.5 - AeroCent" as indicated in FAST v8 manual? And how can I do to change the relative position of the aero center and pitch axis center of each blade element?

Thank you for your attention.
Best regards,





change the relative position of the aero center and pitch axis center of each blade element?

**Comment by jjonkman** [comment]
Dear @ZL6462,

I'm not sure I really understand your question.  As I said, ElastoDyn input `PitchAxis` is not used when BeamDyn is enabled and/or when AeroDyn is enabled.  Instead of using the `PitchAxis` input, you can specify the offset of each aerodynamic analysis node (the aerodynamic center) from the pitch axis within the blade input file of AeroDyn v15.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman,

Thank you for you quick reply.
As the instructions you given above, I have read the manual again, and now my question is solved.

Best regards,
