### ISSUE TITLE
Local Sectional Load (Force/Moment) Output Bug in BeamDyn

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#11]
The local sectional load (force/moment) outputs from BeamDyn are not correct.  We'd prefer to implement these load calculations via integration of the applied, gravitational, and inertial loads distributed along the beam from the section to the tip, plus the relevant applied point loads.

More information provided in the following forum topic: https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=1622.

**Comment by WangQi315** [comment]
@jjonkman, I think we corrected this output for the trapezoidal integration.

**Comment by andrew-platt** [comment]
We (Envision) have a fix for this using the _Fc_ and _Fd_ terms (which are already calculated and stored) and the shape functions.  We will give this code to you and hope you can check the validity of our solution.

**Comment by michaelasprague** [comment]
@andrew-platt , it would be great if this could be submitted as a pull request -- please let us know if there's another mechanism you'd prefer. Thanks!

**Comment by rafmudaf** [comment]
This issue was fixed in pull request #114
