### ISSUE TITLE
Compile OpenFAST on Windows as 32bit with open source software

### ISSUE THREAD

**Issue by SimonHH** [OpenFAST/openfast#110]
Dear all,
as I'm new to compiling in general so I hope you can give me a hint which way to try.
Because of limited disk space I can't install Cygwin on my machine. Visual Studio and Intel Fortran are not available to me.
Can you give me some guidance on what software to take and how to do it?
I need a 32bit version of OpenFAST.
Can someone send me an executable or help me creating one by myself.

Attached the error I got with mingw32 when compiling openfast.

Best regards,
Simon

![compile_error_32bit_mingw](https://user-images.githubusercontent.com/38310787/39177253-4751f16e-479e-11e8-9026-c6d7f3490532.JPG)

**Comment by rafmudaf** [comment]
@SimonHH We've attached precompiled binaries to the GitHub release of OpenFAST v1.0.0 at
https://github.com/OpenFAST/openfast/releases/tag/v1.0.0 and will do so for all future releases. In the release, download `windows_openfast_v1.0.0.zip` and you'll find the single precision 32 bit build at `openfast_Win32.exe` to run on Windows.
