### ISSUE TITLE
(FAST.Farm)Some questions about high-res domain precursor files in VTK format of the downstream wind turbine.

### ISSUE THREAD

**Issue by Helloczm** [OpenFAST/openfast#1106]
Dear all:
      We know that the low-res domain in FAST.Farm is primarily responsible for wake meandering and merging; and the high-res wind domain in FAST.Farm is primarily responsible for ambient and waked inflow local to a turbine. Each of these ambient wind data files must follow the simple legacy serial VTK file format. And we can generate inflow vtk files for both domains using SOWFA. 
      However,  if there are two wind turbines in the wind field, the inflow of the downstream turbine is the wake of the upstream one, so how should the high-res domain of the downstream turbine be generated? I think it should contain the wake of the upstream wind turbine, but the wake is calculated by FAST.Farm. So how should I get the high-res domain of the downstream turbine?

@NRELAdmin @jjonkman @bjonkman </div>

**Comment by jjonkman** [comment]
The same question has been asked and answered in discussions: #1105 .
