### ISSUE TITLE
FAST.Farm vtk files

### ISSUE THREAD

**Issue by Tommi1198** [OpenFAST/openfast#1111]
Hello everyone, I would like to know in which order the data of the wind velocity contained in the vtk files coming from a simulation are stored...I mean, which order is followed? 
My opinion is that, since I have 25 points in each of the 3 directions (so, 25 in x, 25 in y and 25 in z) to define the grid and since each 625 lines (that is 25*25) the x-velocity of the wind changes increasing ( I have a steady inflow wind), the first 625 lines are referred to the XY plane at z=0, the next 625 to the XY plane at z=10 (the spacing between eacxh point in the grid is 10 m), and so on...am I correct?
Moreover, I don't know if, in each block of 625 lines, I firstly moved in x (so y fixed) or vice versa.
Thanks a lot!

**Comment by ebranlard** [comment]
Hi @Tommi, 
You can try the following example script to read your VTK plane:
https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/input_output/examples/Example_VTKPlanesGrid.py

**Comment by jjonkman** [comment]
Dear @Tommi1198,

I agree with your interpretation.  

Just to add to what @ebranlard said.  The order is described in the online FAST.Farm User's Guide and Theory Manual here: https://openfast.readthedocs.io/en/main/source/user/fast.farm/InputFiles.html#ambient-wind-precursor-files-in-visualization-toolkit-format.  As stated, the first data point corresponds to the ORIGIN and the remaining points involve looping through X, then Y, and then Z.  For more information on the simple legacy VTK format used by FAST.Farm, see: https://www.vtk.org/wp-content/uploads/2015/04/file-formats.pdf.

Best regards,

**Comment by Tommi1198** [comment]
Perfect, thanks a lot to both of you!
