### ISSUE TITLE
Having Issues with compiling openfast

### ISSUE THREAD

**Issue by OEziuzo** [OpenFAST/openfast#1112]
Hi Everyone,

I'm new to Openfast, I want to build openfast using Microsoft visual studio i followed the guide but im still not getting enough executables in the \openfast\build\bin directory. I'm expecting to get OpenFAST-Simulink_x64.dll” which will assist me in running the two s-function tests attached to the binaries  I would want to know what to do to overcome this. Attached herewith are the pictures from the visual studio as well as the bin directory.
![bin folder](https://user-images.githubus
![visual studio](https://user-images.githubusercontent.com/104716831/166460419-8d5790d3-3f1f-4b86-a36f-f56227ed07f2.JPG)
ercontent.com/104716831/166459926-ccb6f1f9-7705-4f87-bc41-d47d9e662743.JPG)

**Comment by andrew-platt** [comment]
Dear @OEziuzo,

Did you select `Release_MATLAB` and `x64` for the build type?  Unless those are selected, you will not get a dll.  If you have done that, what error messages did you receive during compilation?

Depending on what version of MATLAB you have installed, you may get a linking error.  The VS project is assuming R2019b, but many of us are using newer versions.  For this error, right click on `OpenFAST-Simulink` in the solution explorer, and select `Properties`.  In the properties dialog, select `Linker` -> `Input`, and change the `Additional Dependencies` line to point to the correct location of `libmex.lib`.

Regards,
Andy

**Comment by OEziuzo** [comment]
> 

Dear Andy,

Thanks for the response,

I did not receive an error message during compilation.

I have checked for the linking error but it is in order.

Still the same results persists.

**Comment by bjonkman** [comment]
@OEziuzo , 

Based on the files you show were built, it does not appear that you have selected the correct configuration.

As Andy said, you need to select `Release_Matlab` and `x64` for the build configuration type (see items circled in red):
![image](https://user-images.githubusercontent.com/6108781/166508367-57ce14fe-7108-4b5e-9448-33f3804593d5.png)

After selecting the `Release_Matlab` and `x_64` configuration, please build again.

**Comment by OEziuzo** [comment]
Dear bjonkman and Andy,

It worked! it was an oversight from me, I used to build at 'Release' instead of 'Release_Matlab'. Thank you .

![bin](https://user-images.githubusercontent.com/104716831/166520091-196c7a93-cd66-43f8-8226-60fe37802662.JPG)

**Comment by OEziuzo** [comment]
Dear all,

 Please what could be the cause of this?


![s-function](https://user-images.githubusercontent.com/104716831/166559509-ddf54d2c-6961-46fa-be61-0e41fe789084.JPG)
?

**Comment by bjonkman** [comment]
Likely the path to the `FAST_Library.h` isn't specified properly in create_FAST_SFunc. `FAST_Library.h` should be in one of the include directories in the build statement in `create_FAST_SFunc.m`.

**Comment by OEziuzo** [comment]
Thanks @bjonkman. It worked but its like my bin directory is still incomplete because “MAP_x64.dll” is still missing and I need it to run openfast through simulink.

![bin](https://user-images.githubusercontent.com/104716831/166565825-3202144a-bfc7-45da-9463-2f625c996174.JPG)

**Comment by OEziuzo** [comment]
I have been able to run it.
Thanks all.

**Comment by bjonkman** [comment]
@OEziuzo , OpenFAST was updated so that the code formerly contained in the MAP dll is now contained in the main OpenFAST executable and in the OpenFAST-Simulink dll, eliminating the need for a separate MAP dll.

**Comment by OEziuzo** [comment]
Okay, Thanks for the explanation @bjonkman.
