### ISSUE TITLE
Feature request -- How to calculate the natural frequency of the NREL 5MW blade through BeamDyn

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1115]
Dear all,

I have known that that we can calculate the natural frequency of the NREL 5MW blade through BeamDyn, however I am wondering how to realize that.

Thank you for your attention.
Best regards,

**Comment by jjonkman** [comment]
Dear @ZL6462,

The linearization functionality of OpenFAST, followed by post-processing using MBC3 to perform eigenanalysis, can be used to compute the mode shapes, natural frequencies, and damping of the full wind turbine system (including blades modeled in BeamDyn) in both parked/idling and operating conditions (with the rotor spinning).  The eigenanalysis approach has been discussed many times before, and is documented here: https://github.com/OpenFAST/matlab-toolbox.

Please note that recent improvements to BeamDyn are needed to obtain accurate linearized solutions when BeamDyn is enabled: https://github.com/OpenFAST/openfast/pull/1050.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman ,

Thank you for your quick and useful answer, I will try that as your instruction.
Best regards,
