### ISSUE TITLE
issue with Test01_SIG

### ISSUE THREAD

**Issue by OEziuzo** [OpenFAST/openfast#1138]
Dear all,

I have been trying to run Test01_SIG but I keep having this error.

What am I doing wrong?

![error](https://user-images.githubusercontent.com/104716831/169830562-ea4d63b1-cda5-411f-a7bb-abd8d309ef23.JPG)
![error2](https://user-images.githubusercontent.com/104716831/169831292-2f16e95e-f222-4ca4-92f3-db9ad6c6426c.JPG)

**Comment by bjonkman** [comment]
First, please check that the `LSSGagVxa` variable is requested as an output from the OpenFAST model. The variable does exist in the sample OpenFAST r-test files, so if you haven't changed the input files, it should be okay. However, if the variable isn't one of the OpenFAST output channels, this could cause the error you are seeing. 

Second, this could be a result of not defining `OutList` before the simulation. There is a note on page 52 of the [FAST 8 Readme](https://www.nrel.gov/wind/nwtc/assets/downloads/FAST/FASTv8.16/README_FAST8.pdf) that discusses some differences with different models. It is possible that newer versions of Matlab make this an issue for the sample test, too. 

I took the variable list from the summary file generated from running OpenFAST on that case. If you add this variable to your script before calling `sim('Test01_SIG.mdl',[0,TMax])`, I think that will fix the problem:
```
OutList = {'Time','Wind1VelX','Wind1VelY','Wind1VelZ','LSSGagVxa','LSSGagPxa','TeetDefl',...
           'TipDxb2','TipDyb2','TipALxb2','TipALyb2','Spn2ALxb1','Spn2ALyb1','YawBrRDxt',...
           'YawBrRDyt','YawBrRVxp','YawBrRVyp','YawBrRAxp','YawBrRAyp','RootMyc1','RootMxc1',...
           'RootFxc2','RootFyc2','Spn3MLxb1','Spn3MLyb1','RotTorq','YawBrMzn','TwrBsMzt'};
```

**Comment by OEziuzo** [comment]
Thank you @bjonkman,
I applied the first option and it worked.

**Comment by OEziuzo** [comment]
Hello all,

I need a confirmation on this, w.r.t the 'INVALID' in the out file below, is it because the units of those signals are missing, if yes, how can I correct it?
![s-function_out file](https://user-images.githubusercontent.com/104716831/173662890-356ba3e3-3336-4159-8f9b-5cdbf3e94e77.JPG)

**Comment by jjonkman** [comment]
Dear @OEziuzo,

While you've circled the Azimuth column, the Azimuth column is not actually an INVALID output channel; it is just that the label and unit columns are not aligned (you'll see that Azimuth is the third column with the units of deg).  In this OpenFAST r-test, which makes use of BeamDyn, the blade-tip deflection outputs from ElastoDyn (TipDxc1, etc.) are INVALID outputs because the blade dynamics are modeled in BeamDyn instead of ElastoDyn.  To output the blade response from this r-test example, you should use the related BeamDyn outputs rather than the ElastoDyn outputs.

Best regards,

**Comment by OEziuzo** [comment]
Dear @jjonkman,

Thank you very much for the response. I'll implement it immediately.

**Comment by OEziuzo** [comment]
Dear all,
![outdata](https://user-images.githubusercontent.com/104716831/174106177-43243d17-61d7-4860-b784-4f9717300893.JPG)


I have added these variable to the outlist section of the beamdyn module. I have also tried adding it with the other variables in the matlab script but it is not is still not reflectiing in the OUTDATA. Where am I getting it wron
![outdata](https://user-images.githubusercontent.com/104716831/174106271-6d55f399-69a0-45d2-95aa-cbc75721b17f.JPG)
![outdata2](https://user-images.githubusercontent.com/104716831/174106305-006c1ee7-80e0-441f-9524-f070ebe0620d.JPG)
![outdata3](https://user-images.githubusercontent.com/104716831/174106327-1b581e72-41e6-4323-a65d-9836e46f9e7f.JPG)
g

**Comment by bjonkman** [comment]
Have you tried to run this outside of Matlab (with the OpenFAST executable) and verified that these new outputs are getting listed in the summary file as output channels?

If so, take that list of output channels from the summary file and update the Matlab script that is run before calling `sim()` with the appropriate `OutList = {<list from the summary file>}` (see my comment from May 23 above).

**Comment by OEziuzo** [comment]
Hello @bjonkman,

Thank you for the response. Yes, I've tried it outside of matlab and it still didn't reflect in the '.out file'.
i have also tried the second recomendation and it didn't work either
![outlist4](https://user-images.githubusercontent.com/104716831/174250630-cd9245ef-72bb-4ca1-a936-ab980eb69d8f.JPG)
.

**Comment by bjonkman** [comment]
You have a couple of different models in this thread. Unless you've changed the model, this last one that you are using (5MW_ITIBarge_DLL_WTurb_WavesIrr) doesn't use BeamDyn, so it won't read the BeamDyn input file where you've listed those channels.

**Comment by bjonkman** [comment]
You need to look at the `CompElast` input in your primary OpenFAST file (usually ends in .fst). Even though your files have `BDBldFile` listed, they are used only when `CompElast = 2`.

**Comment by OEziuzo** [comment]
Okay, thank you very much @bjonkman
