### ISSUE TITLE
Feature request -- Is there a theory manual for ElastoDyn?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1146]
Dear all,

I am wondering whether there is a a theory manual for ElastoDyn? Just like that of AeroDyn. Especially for the part of Euler-Bernoulli beam with modal method for balde structure. Just like that of AeroDyn?

Best regards,

**Comment by jjonkman** [comment]
Dear @ZL6462,

The ElastoDyn theory manual has never officially been published, but the derivation of the equations of motion used by ElastoDyn has been shared in what is often called the "Unofficial Theory Manual", which we have uploaded to the OpenFAST readthedocs documentation--see: https://openfast.readthedocs.io/en/main/source/user/elastodyn/index.html.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman ,

Thank you for your reply, I have found the manual according to your direction.

Best regards,
