### ISSUE TITLE
Bug report: Possible corruption in AeroDyn Driver binary output file

### ISSUE THREAD

**Issue by rafmudaf** [OpenFAST/openfast#1155]
**Bug description**
I have found a NaN in the AeroDyn binary output file in the [ad_HelicalWakeInf_OLAF](https://github.com/OpenFAST/r-test/blob/main/modules/aerodyn/ad_HelicalWakeInf_OLAF/ad_driver.outb) regression test case in the `B1N1TnInd` channel when loaded with the [fast_io](https://github.com/rafmudaf/openfast/blob/b/ad_binary_parsing/reg_tests/lib/fast_io.py) Python module used in the regression tests.

A test case for this is available in the `fast_io` module linked above via the `main`:

```python
if __name__=="__main__":
    d, i, p = load_output('/Users/rmudafor/Development/openfast/reg_tests/r-test/modules/aerodyn/ad_HelicalWakeInf_OLAF/ad_driver.outb')

    # print(np.dtype({'names':tuple(i['attribute_names']), 'formats': tuple(types) }))
    # print(np.array(d,dtype=np.dtype({'names':tuple(i['attribute_names']), 'formats': tuple(types) })))

    # print(f"N Channels: { len(i['attribute_names']) }")
    # print(f"Channels Names:")
    # print(i['attribute_names'])

    # print(f"Shape of the data: {np.shape(d)}")

    target_channel = 'B1N1TnInd'
    channel_index = i['attribute_names'].index(target_channel)
    print(f'Values in {target_channel}:')
    print(d[:, channel_index])
```

Tracing back the bug, we can see that the column scale factor is read in as NaN directly from the output file. It is first read at [line 111](https://github.com/rafmudaf/openfast/blob/b/ad_binary_parsing/reg_tests/lib/fast_io.py#L111):
```python
        if FileID != FileFmtID_NoCompressWithoutTime:
            ColScl = fread(fid, NumOutChans, 'float32')  # The channel slopes for scaling, REAL(4)
            print("Parsing ColScl: ", ColScl[38])
            ColOff = fread(fid, NumOutChans, 'float32')  # The channel offsets for scaling, REAL(4)
```

and then used in a division at [line 153](https://github.com/rafmudaf/openfast/blob/b/ad_binary_parsing/reg_tests/lib/fast_io.py#L153) to scale the data:
```python
    if FileID == FileFmtID_NoCompressWithoutTime:
        pack = np.array(PackedData).reshape(NT, NumOutChans)
        data = pack
    else:
        # Scale the packed binary to real data
        pack = np.array(PackedData).reshape(NT, NumOutChans)
        print("ColScl value when scaling binary: ", ColScl[38])
        data = (pack - ColOff) / ColScl
```

@ebranlard verified that [FASTOutputFile](https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/input_output/fast_output_file.py) in the [python-toolbox](https://github.com/OpenFAST/python-toolbox) does correctly load this channel. I also compared with the ascii output version of the file and it is all `0.0`.

**Expected behavior**
I expected all values in the binary output file to load as a decimal number.

**OpenFAST Version**
I've tested this with the AeroDyn output file in the r-test main (v3.1.0) and dev branches.

**System Information (please complete the following information):**
 - OS: macOS 10.15
 - Compiler: GNU Fortran 11
 - Compiler settings: Default CMake settings - double precision, RELWITHDEBINFO

**Additional context**
It is another issue that the current regression tests do not catch this error, and I will open another issue for that.

**Comment by andrew-platt** [comment]
How is this handled in the `ReadFASTBinary.m` file from the Matlab toolbox?  There may be some additional logic in that routine that ignores the denominator if it is zero and reports back only the offset.
