### ISSUE TITLE
MAP linearization operating point output is not computed/reported correctly

### ISSUE THREAD

**Issue by ebranlard** [OpenFAST/openfast#1165]
**Bug description**
MAP linearization operating point output is not computed/reported correctly

**To Reproduce**
1. Linearize a system, where the output forces from MAP can be expected (for instance, in the example attached, the loads at t=0 should be only along x with Fx=4.3e8)
2. Open the lin file, and look at the FairleadLoads in the output vector, they do not correspond to the expected values. (in the example given, a load Fz=-1e6 shows up).

**OpenFAST Version**
Any version before this bug report (July 2022)

**The issue**
The MAP library stores in memory pointers to the nodal forces. Therefore the outputs "y" in the fortran code always need to point to the "y" of MAP. When Jacobians are computed we can't call MAP with a temporary "y_p" (see comment [here](https://github.com/OpenFAST/openfast/blob/dev/modules/map/src/map.f90#L1355). The problem is that at the end of the routine `MAP_Jacobian_PInputs`, the "y" value we return is the one from the last perturbation (typically a displacement of a node along "z"). During the linearization, `MAP_GetOp` is called [here](https://github.com/OpenFAST/openfast/blob/dev/modules/openfast-library/src/FAST_Lin.f90#L1076), after `MAP_Jacobian_PInputs`, therefore, the "y" operating point is wrong. 

**Potential solutions**
1. At the end of JacobianPInput, call `MAP_CalcOutput` at the operating point, to ensure that "y" is correct:
```fortran
   call map_CalcOutput( t, u, p, x, xd, z, OtherState, y, ErrStat2, ErrMsg2 ) 
```
2. Call `MAP_GetOp` before `MAP_Jacobain_PInputs`. 

I prefer solution 1 as it is a true fix, let me know if you think of other solutions. 

[SparNoRNA_MD1HD0SD0_F111111_Mini_NoRef.zip](https://github.com/OpenFAST/openfast/files/9042175/SparNoRNA_MD1HD0SD0_F111111_Mini_NoRef.zip)

**Comment by jjonkman** [comment]
Thanks, @ebranlard, for tracking down this bug!  I agree that solution 1 makes sense.

**Comment by ebranlard** [comment]
Yes, this fixes the issue.
