### ISSUE TITLE
Improve User-Specified Wave-Kinematics File Formatting Requirements for WaveMod = 6

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#118]
The data format of the various user-specified wave-kinematics input files (.Elev, .Vxi, .Vyi, .Vzi, .Axi, .Ayi, .Azi, and .DynP) used with the WaveMod = 6 option in HydroDyn are very finicky, with very specific requirements regarding data format, white space, etc.  This has caused many users trouble.  HydroDyn should be made more robust so that the data format requirements are more user-friendly.  More information can be found in the following forum topic: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1690.

**Comment by ebranlard** [comment]
I've added some checks for this format. For now, the file is allowed to have more lines and more columns than required, but not less (before it could). I can add test to check for strict equality of number of lines and columns if needed.

**Comment by rafmudaf** [comment]
fixed by #239

**Comment by SatishJ013** [comment]
Hi all,

I am facing issue with externally generated wave kinematics WaveMod=6 in OpenFAST-v2.4.0 as I am getting wave elevations of zero in output file. I have attached the relevant input files. Kindly suggest me on this.

Thanks,
Satish J
[TEST_004 (2).zip](https://github.com/OpenFAST/openfast/files/5512368/TEST_004.2.zip)
[TEST_004.zip](https://github.com/OpenFAST/openfast/files/5512370/TEST_004.zip)
