### ISSUE TITLE
In-plane tip deflection

### ISSUE THREAD

**Issue by OEziuzo** [OpenFAST/openfast#1182]
Hello all,

I derived the in-plane speed of the tip of the blades of ‘5MW_Land_DLL_WTurb’ (by finding the derivatives of their respective in-plane tip deflections ’IPDefl1’, ’IPDefl2’, ’IPDefl3’) and it gave me results that are close to zero. Is there what I’m missing in the setup because the one I’m comparing it with has their in-plane speed of the tip of the blades close to the speed of the rotor.
![in-plane_tip_deflection](https://user-images.githubusercontent.com/104716831/179181379-de92053a-da51-41e6-8f0e-19229fd59656.jpg)
![in-plane_tip_deflection2](https://user-images.githubusercontent.com/104716831/179184521-686f7329-2b5f-4f1b-ab5f-e6a1eafc23f2.JPG)

**Comment by OEziuzo** [comment]
Dear @jjonkman,

Thank you very much for this response, absolute accelerations helps.

**Comment by OEziuzo** [comment]
Hello @jjonkman,


Integrating the absolute accelerations to get the absolute velocity gives a strange performance whereas, the absolute accelerations itself gives a good performance as shown below. Would it be correct to use the accelerations as the in-plane speed in this case without any conversion?

![integrating_the acceleration](https://user-images.githubusercontent.com/104716831/182377949-1c97f062-5a29-4241-a8f1-8f21f1b3c8b1.JPG)

**Comment by jjonkman** [comment]
Dear @OEziuzo,

The absolute acceleration of the blade tip is output in a local reference frame that is oriented with the blade tip.  It would not make sense to integrate this acceleration without first expressing the absolute acceleration in a frame of reference that is consistent between time steps, e.g., the global inertial frame.

Best regards,

**Comment by OEziuzo** [comment]
Dear @jjonkman,

Thank you very much for the feedback.
