### ISSUE TITLE
Error when coupling the BeamDyn and ServoDyn

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1189]
Dear all,

I am trying to simulate the aeroelastic performance of NREL-5MW under surge motion condition by using the AeroDyn+BeamDyn of OpenFAST, and everything was going well. However, when I trying to enable the ServoDyn, some errors occured. The error comes from the BeamDyn "Solution does not converge after the maximum number of iterations". The first time, the error occured at the 0.01s, and I guess this is induced by the UA performance of the airfoil, so I turn off the UA model. Then I ran the case for the second time, and the error was occured as after 30s. I guess this is due to the pitch control of ServoDyn, which makes the BeamDyn hard to converge because of the abrupt change of the pitch angle, and I did find an abrupt increase of the pitch angle at 30s form the post process result, just like following figure. By the way, I used the default control strategy of the DISCON.dll.

![untitled](https://user-images.githubusercontent.com/98078424/180341464-8edc6624-fb39-4202-9ef2-9f322e0c3308.jpg)

Thank you for your attention.
Best regards,

**Comment by andrew-platt** [comment]
A couple of questions:

- which version of OpenFAST?
- what size timestep are you using?

**Comment by ZL6462** [comment]
Dear @andrew-platt,

Thank you for your quick reply.
The version I used is 3.10, and time step is 0.0015s.

Best regards,

**Comment by jjonkman** [comment]
Dear @ZL6462,

Are you using the OpenFAST model of the NREL 5-MW baseline wind turbine with BeamDyn enabled from the r-test: https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast/5MW_Land_BD_DLL_WTurb?  How do your input files differ from this OpenFAST model?

Best regards,

**Comment by ZL6462** [comment]
Dear @andrew-platt  and @jjonkman 

Thank you for your reply.

I use the openfast v3.1.0, and the case is from https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast/5MW_Land_BD_DLL_WTurb as mentioned above.

After days of investigation, I gusses this error may come from the extreme operation conditon I used, which lead to large deformation of the blade. I will adjust this and if have other issues, I will report it on github.

Best regards,
