### ISSUE TITLE
Spurious negative damping when running AD15 and BD

### ISSUE THREAD

**Issue by ptrbortolotti** [OpenFAST/openfast#1207]
**Bug description**
When BeamDyn is called, the number of nodes in the AD15 blade input file greatly influences the aeroelastic damping values. There might be an issue in the load mapping between BD and AD15 blade nodes

**To Reproduce**
1. Unzip [BF_align_nodes.zip](https://github.com/OpenFAST/openfast/files/9230541/BF_align_nodes.zip)
2. Run the .fst file with OpenFAST 3.2 switching between bar_urc_stab_13_AeroDyn15_blade.dat and bar_urc_stab_13_AeroDyn15_blade2.dat
3. Compile pyFAST and run the linearization script https://github.com/OpenFAST/python-toolbox/blob/dev/pyFAST/linearization/campbell.py
4. In the case where AD15 and BD nodes aren't matching, you'll obtain negative damping. When nodes match, negative damping disappears

**Expected behavior**
No negative damping is expected in this design at this wind speed.

**Screenshots, if applicable**
I've run longer simulations at multiple wind speeds and I've confirmed the problem.
Here the Campbell with node mismatch (note that I didn’t spend much time identifying the modes correctly)
![Campbell](https://user-images.githubusercontent.com/20641647/182064292-340e1e51-3073-484b-a341-ee07c8f6dab1.png)
And the one with nodes realigned
![Campbell](https://user-images.githubusercontent.com/20641647/182064326-62210563-8fbe-4f03-84b9-994e75244ed6.png)

And the time domain results at wind = 26 m/s. The solutions change slightly, but I suspect that’s only the effect of mesh refinement in AD15 (from 30 to 59 elements).

![TipRDxr](https://user-images.githubusercontent.com/20641647/182064381-df791c90-a5e4-41f3-9704-12d2e97f3347.png)
![TipRDyr](https://user-images.githubusercontent.com/20641647/182064386-cbe3975d-ccab-41aa-a916-dd6120744702.png)
![TipRDzr](https://user-images.githubusercontent.com/20641647/182064387-d34519da-6395-4e13-bbe2-a404143c21b3.png)
![TipTDxr](https://user-images.githubusercontent.com/20641647/182064388-04a956ec-771a-49cb-9ead-b3f0a7d596fc.png)
![TipTDyr](https://user-images.githubusercontent.com/20641647/182064391-030c9245-9fc4-4972-b952-4450624c690a.png)
![TipTDzr](https://user-images.githubusercontent.com/20641647/182064392-9aad7828-6738-455c-808c-5cf896e35976.png)

**OpenFAST Version**
OpenFAST 3.2 compiled on HPC system eagle with Intel compilers

**Comment by andrew-platt** [comment]
This might be fixed in `rc-3.5.3` through PRs #2060, #2063, and #2085.  These tests should be rerun with 3.5.3 to verify this issue is now corrected.

**Comment by andrew-platt** [comment]
@mayankchetan confirmed these issues no longer exist after updates to 3.5.3 (plots coming)

**Comment by mayankchetan** [comment]
The input files provided by @ptrbortolotti does not result in negative damping values when using 3.5.3

# With mismatched AD15 & BD nodes at 26m/s inflow

|Mode| NatFreq_[Hz]| Damp_Ratio_[-]| LogDec._[%] | Mode_content_[-] |
|----|-------------|---------------|-------------|------------------|
|  1 |       0.194|  0.01569       |  9.8575 |  ED 1st tower SS - Bld cos N11 EDGE-DISP - Bld cos |
|  2 |       0.212|  0.13568       | 85.2524 |  ED 1st tower FA - Bld cos N8 FLAP - Bld cos N7 FLA |
|  3 |       0.515|  0.81313       | 510.9026 |  Bld cos N9 FLAP - Bld sin N9 FLAP - Bld sin N8 FLA |
|  4 |       0.602|  0.67929       | 426.8092 |  Bld coll. N9 FLAP - Bld coll. N8 FLAP |
|  5 |       0.674|  0.01994       | 12.5305 |  Bld cos N11 EDGE - Bld sin N11 EDGE - Bld cos N10 |
|  6 |       0.704|  0.60083       | 377.5126 |  NoMax - Bld sin N11 FLAP - Bld cos N11 FLAP - Bld |
|  7 |       0.748|  0.03932       | 24.7037 |  ED 2nd tower SS - Bld coll. N11 EDGE - Bld coll. N |
|  8 |       0.930|  0.01375       |  8.6391 |  NoMax - Bld sin N11 EDGE - Bld sin N10 EDGE - Bld |
|  9 |       1.179|  0.34855       | 219.0029 |  Bld cos N10 FLAP |
| 10 |       1.317|  0.29614       | 186.0701 |  Bld coll. N10 FLAP |
| 11 |       1.426|  0.28739       | 180.5711 |  NoMax - Bld sin N11 FLAP - Bld cos N11 FLAP - Bld |
| 12 |       1.589|  0.02645       | 16.6193 |  NoMax - Bld coll. N11 FLAP - Bld cos N11 FLAP - Bl |
| 13 |       1.618|  0.04935       | 31.0047 |  ED 2nd tower FA |
| 14 |       2.019|  0.02828       | 17.7679 |  NoMax - Bld sin N11 TORS-ROT - Bld sin N10 TORS-RO |
| 15 |       2.265|  0.02349       | 14.7610 |  NoMax - Bld cos N11 TORS-ROT - Bld cos N10 TORS-RO |
| 16 |       2.372|  0.01684       | 10.5819 |  NoMax - Bld coll. N11 TORS-ROT - Bld coll. N10 TOR |
| 17 |       2.427|  0.13986       | 87.8792 |  Bld sin N11 FLAP - Bld sin N10 FLAP |
| 18 |       2.580|  0.13603       | 85.4706 |  Bld coll. N11 FLAP |
| 19 |       2.691|  0.12705       | 79.8284 |  Bld cos N11 FLAP |
| 20 |       3.972|  0.08880       | 55.7932 |  NoMax - Bld sin N11 FLAP - Bld cos N11 FLAP - Bld |


# With aligned AD15 & BD nodes at 26m/s inflow

|Mode| NatFreq_[Hz]| Damp_Ratio_[-]| LogDec._[%]| Mode_content_[-] |
|----|-------------|---------------|------------|------------------|
|  1 |       0.194|  0.01634       | 10.2659|  ED 1st tower SS - Bld cos N11 EDGE-DISP - Bld cos |
|  2 |       0.212|  0.13573       | 85.2798|  ED 1st tower FA - Bld cos N8 FLAP - Bld cos N7 FLA |
|  3 |       0.525|  0.83276       | 523.2360|  Bld cos N9 FLAP - Bld sin N9 FLAP - Bld sin N8 FLA |
|  4 |       0.609|  0.70319       | 441.8261|  Bld coll. N9 FLAP - Bld coll. N8 FLAP |
|  5 |       0.674|  0.02203       | 13.8401|  Bld sin N11 EDGE - Bld cos N10 EDGE - Bld sin N10  |
|  6 |       0.709|  0.62300       | 391.4406|  NoMax - Bld sin N11 FLAP - Bld cos N11 FLAP - Bld  |
|  7 |       0.748|  0.04144       | 26.0391|  ED 2nd tower SS - Bld coll. N11 EDGE - Bld coll. N |
|  8 |       0.930|  0.01528       |  9.6021|  NoMax - Bld sin N11 EDGE - Bld sin N10 EDGE - Bld  |
|  9 |       1.177|  0.38446       | 241.5604|  Bld cos N10 FLAP |
| 10 |       1.316|  0.32874       | 206.5512|  Bld coll. N10 FLAP |
| 11 |       1.422|  0.31776       | 199.6527|  NoMax - Bld sin N11 FLAP - Bld cos N11 FLAP - Bld |
| 12 |       1.588|  0.02785       | 17.5012|  NoMax - Bld cos N11 FLAP - Bld cos N10 FLAP - Bld |
| 13 |       1.614|  0.05206       | 32.7081|  ED 2nd tower FA |
| 14 |       2.032|  0.03508       | 22.0442|  NoMax - Bld sin N11 TORS-ROT - Bld sin N10 TORS-RO |
| 15 |       2.277|  0.02949       | 18.5278|  NoMax - Bld cos N11 TORS-ROT - Bld cos N10 TORS-RO |
| 16 |       2.379|  0.02033       | 12.7751|  NoMax - Bld coll. N11 TORS-ROT - Bld coll. N10 TOR |
| 17 |       2.406|  0.15947       | 100.1958|  Bld sin N11 FLAP - Bld sin N10 FLAP |
| 18 |       2.566|  0.15567       | 97.8079|  Bld coll. N11 FLAP |
| 19 |       2.670|  0.14413       | 90.5612|  Bld cos N11 FLAP |
| 20 |       3.970|  0.11115       | 69.8367|  NoMax - Bld sin N11 FLAP - Bld cos N11 FLAP - Bld  |
