### ISSUE TITLE
Unable to run Simulink with OpenFAST 3.0

### ISSUE THREAD

**Issue by ARussell-IDCORE** [OpenFAST/openfast#1213]
Hi all,

I am having the following issue with trying to run OpenFAST 3.0 with Simulink (PCMode, VSControl = 4 in ServoDyn). I run the command:
 
sim('Simulink_Model.slx') 

to call the Simulink model having defined the .fst input file.

The Simulink model launches but gets stuck saying "Initializing" in the bottom left corner. Additionally, the MATLAB command window returns numerous warnings where it seems to think that none of the Simulink blocks are connected to each other. The program gets stuck there and I have to force close MATLAB and restart.

This is a new issue and I have had no issues with the Simulink interface until now. What might be causing this issue and how may I be able to fix it?

Thank you,

Andrew

**Comment by andrew-platt** [comment]
Hi Andrew,

Which operating system are you on?  Do the example models work (https://github.com/OpenFAST/openfast/tree/v3.0.0/glue-codes/simulink/examples)?

Regards,
Andy

**Comment by ARussell-IDCORE** [comment]
Hi Andy,

I am on Windows 10 and the example models work. Since posting this I have managed to find the cause of the issue. The problem came from including LiDAR measurement within S-Function parameters of the the FAST_SFunc block, where the inputs were set as:

"FAST_InputFileName, TMax, [3 UseLidar, LidRadialV]"

instead of

"FAST_InputFileName, TMax, 0"

Once I reset it to the latter, the simulations were able to run again. I'm guessing that it's because the S-Function I was using couldn't accept LIDAR inputs.

Kind regards,

Andrew
