### ISSUE TITLE
Validity of OpenFAST for very long mooring line

### ISSUE THREAD

**Issue by niuyue321** [OpenFAST/openfast#1218]
Hello Dr. Jason Jonkman,

I have a question regarding the validity of OpenFAST when the morning line is very long. Specifically, in the report "Definition of the Semisubmersible Floating System for Phase II of OC4" page 32, Figure 5-4, if the mooring line is longer than the 186 +DISTANCE, is the simulation still valid?

![Moorling line](https://user-images.githubusercontent.com/77991559/184984572-f807be04-7443-4e28-b16d-615b386d41e2.PNG)

Thank you,
Yue Niu

**Comment by jjonkman** [comment]
Dear @niuyue321,

The quasi-static mooring model in OpenFAST (MAP++) cannot be used to model a mooring line that is longer than the sum of the horizontal and vertical distances between the fairlead and anchor; in this situation, there is no unique quasi-static solution, so, MAP++ would not be able to solve it.  However, the lumped-mass mooring dynamics model in OpenFAST (MoorDyn) has no such limitation.

Best regards,

**Comment by niuyue321** [comment]
Dear Dr. Jason Jonkman,

I see. Thank you for your help!

Best regards,
Yue Niu
