### ISSUE TITLE
HydroDyn WaveStMod=0 Requirement

### ISSUE THREAD

**Issue by Sam-Ramsahoye** [OpenFAST/openfast#1226]
Hi OpenFAST Team,

Are there any plans to re-introduce the WaveStMod >0 options in HydroDyn? If not, are there any recent branches/forks that re-enable this feature? I'm comfortable recompiling bits of source if they're available, but I'd be more comfortable doing this if it didn't involve commits of a very dated fork/branch.

Alternatively,  are there dated versions of OpenFAST/FAST where this is a valid option?

Best,
Sam

**Comment by jjonkman** [comment]
Hi @Sam-Ramsahoye,

See PR https://github.com/OpenFAST/openfast/pull/1008, which is under active development and expected to be released in OpenFAST v4.0.

Best regards,

**Comment by Sam-Ramsahoye** [comment]
Thank you Jason! And Lu Wang for the development.

Sam
