### ISSUE TITLE
WindType=6 User defined

### ISSUE THREAD

**Issue by VanessacNavarroi** [OpenFAST/openfast#1236]
Hello, I am applying a speed controller that approximates the disturbances to the test13.fst in FASTV8, I need to change the wind speed so that the turbine fits the operation specifications of region 2, approximately from 3.5m/s to 11.5m /s with an average of 7.8m/s, I understand that the IfW_UserWind.f90 file exists to modify the wind profile and that the IfW_UserWind_CalcOutput subroutine seen below must be modified
![image](https://user-images.githubusercontent.com/103989402/187569993-f42f323d-bc4d-43b9-a1f7-123272099397.png)
However, I do not have knowledge in fortran, so I would like to know if someone has an example where they have modified the file, I would also like to know what should be done after compiling it in fortran, should the FAST code be compiled in visual basic?

Best regards

**Comment by jjonkman** [comment]
Dear @VanessacNavarroi,

Can you clarify what type of wind you want to specify?  Does the wind you to specify have features that are not supported by one of the standard wind data files supported by InflowWind (including uniform wind and full field turbulence)?

Best regards,

**Comment by VanessacNavarroi** [comment]
Hello, thanks for answering
I want to specify a turbulent wind profile like the one in test 13 which is about 12m/s but is 7.8m/s,
with a minimum of 3.5m/s and a maximum of 11.5m/s, I have not used the InflowWind files, when I use WindType=3 for example I get the following error:
![image](https://user-images.githubusercontent.com/103989402/187777116-563e2c39-42be-4b65-a571-1ec8c43d4e48.png)
The wind data file supported by InflowWind 3=binary TurbSim FF has the turbulence?

Regards

**Comment by jjonkman** [comment]
Dear @VanessacNavarroi,

You don't need to use `WindType` = 6 to simulate with full field turbulence at a different mean wind speed.  `WindType` = 3 and 4 are both full-field turbulent wind data files, but with different file formats, both of which can be generated by TurbSim.  You need to run TurbSim for the conditions you want to simulate.  Have you done that?

FYI: InflowWind and the `WindType`s supported are documented here: https://openfast.readthedocs.io/en/main/_downloads/a231262e7763b4d61759ebe4e0fc30b2/InflowWind_Manual.pdf.

Best regards,

**Comment by VanessacNavarroi** [comment]
Thank you, i found the TurbSim file you shared here in the forum and i ran it, i get the next wind profile,
 
![image](https://user-images.githubusercontent.com/103989402/189437737-aa078b0e-678b-4996-a4ce-6d82fad3eea7.png)

i will kepping working with the TurbSim file

Regards, thank you
