### ISSUE TITLE
The "CoeffData" array was not assigned because the file is too short.

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#1238]
**Bug description**
I tried to transfer the parameters of a balded wind turbine model of another person to the fast software, and the following error occurred when running aerodyn.

>FAST_ InitializeAll:AD_ Init:Init_ AFIparams:AFI_ Init:ReadAFfile:ParseSiAry:
>A fatal error occurred when parsing data.
>The "CoeffData" array was not assigned because the file is too short.

In addition, I would like to ask you, there is a blafid parameter in aerodyn v15.00. * blade definition input file. How can I confirm which airfoil file is related to which nodes?

This is a complete error message(I know I should use the FST file. Here I use a TXT file to input the FST file. I think there is no problem)

C:\Users\13417\Desktop\bladed\LoadCases>TwinRotor_x64 TwinRotor_x64.txt
**************************************************************************************************
OpenFAST

Copyright (C) 2022 National Renewable Energy Laboratory
Copyright (C) 2022 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-Unversioned from 42a5a8196529ae0349eda6d797a79461c2c03ff0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 1910
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: Jul 15 2022
 - Time: 09:42:53
Execution Info:
 - Date: 08/31/2022
 - Time: 16:28:33+0800

OpenFAST input file heading:
    FAST Certification Test #19: IEA 15.0 MW Baseline Wind Turbine with OC3 Monopile RF
    Configuration, for use in offshore analysis

Running ElastoDyn.
Nodal outputs section of ElastoDyn input file not found or improperly formatted.
Running AeroDyn.
AD15 Nodal Outputs: Nodal output section of AeroDyn input file not found or improperly formatted.
Skipping nodal outputs.

FAST_InitializeAll:AD_Init:Init_AFIparams:AFI_Init:ReadAFfile:ParseSiAry:
 >> A fatal error occurred when parsing data.
 >> The "CoeffData" array was not assigned because the file is too short.

OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR
 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.

**Comment by jjonkman** [comment]
Dear @shipors,

From the error message, my guess is your airfoil data input file is not formatted properly.  How does your airfoil data file compare to one of the example airfoil data files provided with OpenFAST (e.g., here: https://openfast.readthedocs.io/en/main/_downloads/5ba9cfc7b0b53c6530f7032f44cb4874/ad_polar_example.dat)?

Regarding `BlAFID`, the list of airfoil data files is given via `AFNames` in the AeroDyn primary input file.  For example, `BlAFID` = 4 corresponds to the fourth file listed in `AFNames`.

Best regards,

**Comment by jjonkman** [comment]
Dear @shipors,

Does adding quotes around the "DEFAULT" keyword solve the problem?

And presumably you have 101 lines in your table of aerodynamic coefficients (you only show 7 lines), from -180 to 180 degrees?

Best regards,

**Comment by shipors** [comment]
Dear @jjonkman 

I checked it again and found that the number of lines in the aerodynamic coefficient table of the first airfoil file I set was wrong. Actually, it should be 101 lines, But I found it was 120 lines. After modification, it can run normally. Thank you for your inspiration!

Best wishes!
