### ISSUE TITLE
The difference between the blade definition of the AeroDyn and BeamDyn?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1242]
Dear all,

I have noticed that there exits blade definition in both the "NRELOffshrBsline5MW_AeroDyn_blade.dat" and "NRELOffshrBsline5MW_BeamDyn.dat". I am windering that what's the difference between these two definitions, namely the differences between BlCrvAC and kp_xr ，as well as BlSwpAC and kp_yr.

Besides, I also noticed that, in "NRELOffshrBsline5MW_AeroDyn_blade.dat" the value of BlCrvAC is NOT zero, however in "NRELOffshrBsline5MW_BeamDyn.dat", the kp_xr is zero.

Thank you for your attention.
Best regards,

**Comment by jjonkman** [comment]
Dear @ZL6462,

The coordinates in the BeamDyn primary input file define the reference axis for the blade structural properties relative to the pitch axis in the blade coordinate system.  The coordinates in the AeroDyn blade input file define the aerodynamic analysis nodes relative to the pitch axis in the blade coordinate system.  The aerodynamic analysis nodes need not be located along the structural reference axis.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman 

Thank you for your reply.

Best regards
