### ISSUE TITLE
A problem about model mapping？

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#1246]
I have encountered the following errors, but I don't know where my problem is. I also saw the content expressed on [this website](https://forums.nrel.gov/t/meshing-error/1527/2). I checked AD and ED and found that the tower height was 60.3m. Maybe there's something missing that I didn't notice?

```
FAST_InitializeAll:InitModuleMappings:ED_2_AD_BladeMotion(1):MeshMapCreate:CreateMotionMap_L2_to_L
2:CreateMapping_ProjectToLine2:Found close value for node 1. (2.80132E-06 m)
CreateMapping_ProjectToLine2:Node 39 does not project onto any line2 element. Closest distance is
1.0815 m.
InitModuleMappings:ED_2_AD_BladeMotion(2):MeshMapCreate:CreateMotionMap_L2_to_L2:CreateMapping_Pro
jectToLine2:Node 39 does not project onto any line2 element. Closest distance is 1.0815 m.
InitModuleMappings:ED_2_AD_BladeMotion(3):MeshMapCreate:CreateMotionMap_L2_to_L2:CreateMapping_Pro
jectToLine2:Node 39 does not project onto any line2 element. Closest distance is 1.0815 m.
```
![image](https://user-images.githubusercontent.com/56157328/189582131-4e8ffc5a-17c4-4bb3-aa62-739600f0ab70.png)
![image](https://user-images.githubusercontent.com/56157328/189582203-09ac8f14-84fa-43fd-87db-b31addbd2fed.png)

**Comment by jjonkman** [comment]
Dear @shipors,

A similar question was answered here: https://github.com/OpenFAST/openfast/discussions/908.  The errors are are related to the mesh-mapping search for ED_2_AD_BladeMotion, which is the mesh-mapping search between ElastoDyn Line2 blade motion output mesh and the AeroDyn Line2 blade motion input mesh. This is pointing towards an incompatibility between how the blade is discretized in ElastoDyn and AeroDyn.

Best regards,
