### ISSUE TITLE
The simulation of floating offshore wind turbines considering substructure hydroelasticity

### ISSUE THREAD

**Issue by JackyzhangHJ** [OpenFAST/openfast#1250]
Dear all
    I recently try to simulate the hydroelastic effect of the substructure of OC4 DeepCwind semisubmersible FOWT. From what I understand from the openfast user guide, it seems to be implemented mainly by modifying the input file of Subdyn. However, when I try to run openfast, it cannot open Subdyn. Do I need to make changes to other input files? And are there any relevant cases in the r-test folder for reference. The main input file and the Subdyn input file are shown below. Looking forward to your answers!

[main input file.txt](https://github.com/OpenFAST/openfast/files/9574824/main.input.file.txt)
[subdyn input file.txt](https://github.com/OpenFAST/openfast/files/9574825/subdyn.input.file.txt)

**Comment by JackyzhangHJ** [comment]
The error reported by openfast is shown in the figure.
![image](https://user-images.githubusercontent.com/113587106/190396517-cc03cf4e-41dc-4af3-9090-d1ba7f9b3c03.png)

**Comment by bjonkman** [comment]
Is this the name of your input file?  `NRELOffshrBsline5MW_OC4DeepCwindSemi_SubDyn` (without any file extension?)

Check that the main input file's value for `SubFile` (line 41) is set properly.

Here are OpenFAST regression test input files for the "Semisubmersible Floating System for Phase II of OC4": https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast/5MW_OC4Semi_WSt_WavesWN

**Comment by JackyzhangHJ** [comment]
Dear @bjonkman
    I have modified the main input file as you suggested. However, the following error occurs when running openfast. Which part of the Subdyn input file should I modify? Looking forward to your answers！

Running SubDyn.
   Floating case detected, Guyan modes will be rigid body modes
   Guyan extra moment and rotated CB-frame will be used (floating case detected)
   Performing Craig-Bampton reduction 1614 DOFs -> 10 modes + 6 DOFs
[INFO] Negative eigenvalue found with small norm (system may contain rigid body mode)
......
FAST_InitializeAll:SD_Init:Craig_Bampton:CraigBamptonReduction:CraigBamptonReduction_FromPartition
:EigenSolveWrap:EigenSolve:Zero eigenvalue found, system may contain rigid body mode

 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.

**Comment by jjonkman** [comment]
Dear @JackyzhangHJ,

I would guess there is a problem with how you’ve set up your SubDyn input file, e.g. the member or joint definitions.  Are all joints that you've specified interconnected by members?

Best regards,

**Comment by JackyzhangHJ** [comment]
Dear @jjonkman
       Thank you for your advice. I tried to do hydroelastic analysis for Spar platform (less number of members and joints than OC4DeepCwind). Openfast works fine with SubDyn. Thanks again for your suggestion.
