### ISSUE TITLE
Feature request--Can we use BeamDyn to calculate the torsional mode of the blade?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1259]
Dear all,

I have noticed that the BeamDyn can not output the torsional deflection, so I am confused whether we can use the BeamDyn to calculate the torsional mode of the blade (for example when we want to conduct flutter analysis)? And how can we realize that, pehaps through MBC3 tool? 

Best regards,

**Comment by jjonkman** [comment]
Dear @ZL6462,

BeamDyn does calculate torsional deformation and can be used to conduct a flutter analysis.  However, the angular/rotation deflections of the blade are output from BeamDyn as Wiener-Milenković rotational parameters.  You'd have to transform these rotational parameters into another form if you want a different parameterization.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman ,

Thank you for your reply, which is useful for me.

Best regards,
