### ISSUE TITLE
NacYaw measures relative to the tower, yaw misalignment in case of floating turbine doesn't consider platform yaw.

### ISSUE THREAD

**Issue by MYMahfouz** [OpenFAST/openfast#1260]
**ServoDyn doesn't see the existence of yaw misalignment in case it is from the platform yaw**
I am trying to use the simple nacelle control using the spring damping model (YawSpr, YawDamp) in ServoDyn to prevent yaw misalignment.

The source of yaw misalignment in this case is the floating platform. So the NacYaw doesn't see any misalignment as it is measured relative to the tower reference frame and not the inertial reference frame.

**What is the best way to apply nacelle yaw control to keep the turbine facing the wind?**
I am trying to keep the turbine facing the wind of all time, what would be the best method to use for this?

**Comment by jjonkman** [comment]
Dear @MYMahfouz,

I'm not sure I fully understand your question.  Am I correct that you want to use nacelle-yaw control to reduce the yaw misalignment brought on by yawing of the floating substructure?  If so, I would suggest using measurements other than the nacelle-yaw angle as input to the yaw controller.

Best regards,

**Comment by MYMahfouz** [comment]
Dear @jjonkman,

First of all thanks for your quick reply.

Yes, this is exactly what I want to do.

I am sorry, but i don't understand what you mean by using measurements? How to implement this in OpenFAST?

I am currently using the  settings below in ServoDyn. I set the YawNeut and NacYaw(in ElastoDyn) to be equal. I was hoping that the nacelle spring and damping will automatically adjust the nacelle yaw.


0                      YCMode      - Yaw control mode {0: none, 3: user-defined from routine UserYawCont, 4: user-defined from Simulink/Labview, 5: user-defined from Bladed-style DLL} (switch)

9999                 TYCOn       - Time to enable active yaw control (s) [unused when YCMode=0]
0.0                    YawNeut     - Neutral yaw position--yaw spring force is zero at this yaw (degrees)
4.6273E+10             YawSpr      - Nacelle-yaw spring constant (N-m/rad)
3.9088E+07             YawDamp     - Nacelle-yaw damping constant (N-m/(rad/s))
9999.9                 TYawManS    - Time to start override yaw maneuver and end standard yaw control (s)
2.0                    YawManRat   - Yaw maneuver rate (in absolute value) (deg/s)
0.0                    NacYawF     - Final yaw angle for override yaw maneuvers (degrees)


Best regards,

**Comment by jjonkman** [comment]
Dear @MYMahfouz,

Well, I would guess you'd want to measure the yaw misalignment (difference between the wind direction and total yaw orientation) and feedback that data into an active yaw controller that aims to minimize the misalignment.  You'll have to enable the active yaw control (`YCMode` > 0, `TYCOn` = 0 s) and use OpenFAST outputs such as `Wind1AngXY` (for the wind direction) from InflowWind and `TwHt1RPzi` (for the yaw orientation) from ElastoDyn within the yaw controller.

Best regards,

**Comment by MYMahfouz** [comment]
Dear @jjonkman,

Yes, I have done this and it works. I thought you meant there is a way for servodyn to read directly "TwHt1RPzi" instead of "NacYaw".

Thanks a lot for the help and the quick replies.

Best regards,
