### ISSUE TITLE
A question about Integrated Hydrodynamic Loads at (0,0,0)

### ISSUE THREAD

**Issue by CharlesYouOUC** [OpenFAST/openfast#1268]
**Bug description**
I  use the Test25 and outpout the  Integrated Hydrodynamic Loads at (0,0,0). The time domain of HydroFzi is shown in figure 1. Why the mean of HydroFzi is 4.55E7N. Because the excitation forces from incoming waves is supposed to be near zero like shown in figure 2. Do you have consider the buoyance of floating structure in the HydroFzi?
![image](https://user-images.githubusercontent.com/114040956/193439792-b5c0c605-361e-4f09-9ec8-fc894712826f.png)
figure 1. The time domain  of HydroFzi 
![image](https://user-images.githubusercontent.com/114040956/193439755-6d80d9ea-a8d0-4f78-b577-9a520dc8b481.png)
figure 2. The time domain  of HydroFzi with change

**Comment by jjonkman** [comment]
Dear @CharlesYouOUC,

Yes, HydroDyn output `HydroFzi` is the total integrated hydrodynamic force in the vertical direction from both the potential flow and strip theory solutions, including hydrostatic (buoyancy) contributions.

Best regards,

**Comment by CharlesYouOUC** [comment]
Dear jjonkman,

Thank you！

Best regards,
