### ISSUE TITLE
The problem of calculating modal coefficients using blade modal shapes  #question#

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#1269]
Hello，

I have calculated the modal shape of the blade using BMODES. Now I need to calculate the modal coefficient. I have an EXCEL file (ModeShapePolyFitting. xls), but its input requires two columns of parameters, X and Y. 

![1664772992370](https://user-images.githubusercontent.com/56157328/193504438-ed456a5e-62f1-45ac-a414-6f7fb28dd4aa.jpg)

There are six columns of parameters in the BODES output file. I already know that X corresponds to the normalized height in the out file. What parameters does Y correspond to in the OUT file?

![image](https://user-images.githubusercontent.com/56157328/193504938-2019a5a3-9fea-42ed-92cb-ff3169de36a5.png)

Best wishes，
shipors.

**Comment by jjonkman** [comment]
Dear @shipors,

Y should be either the flapwise or edgewise displacement, flap disp or lag disp from the BeamDyn output, respectively.

FYI: See the guidance I provide for calculating blade mode shapes for ElastoDyn using BModes in the following topic on our forum: https://forums.nrel.gov/t/nrel-5mw-blade-mode-shape/1092.
 
Best regards,
