### ISSUE TITLE
Whether inflowwind and output power can fit ARMAX model？

### ISSUE THREAD

**Issue by Sunwannasleep** [OpenFAST/openfast#1270]
Hello guys, 
I used FAST （v3.2.1）& Simulink  to simulate the case of 5WM semi submersible wind turbine (5MW_OC4Semi_WST_WavesWN),
I set the inflowwind as a 12 mps turbulent wind, and selected the generator power and torque (GenPwr, GenTq) as the output. 
My questions are as follows：
（1）Whether turbulence wind can be regarded as white noise model？If not, how to generate the inflowwind of the white noise model? Do I need to use Turbosim?
（2）I wonder whether the linear ARMAX model can be fitted between the input wind and the output power/torque. I tried to do it but the result of fitting with MATLAB is not very good, and the fitting degree is only about 20%.

Thanks in advance！

**Comment by jjonkman** [comment]
Dear @Sunwannasleep,

Regarding (1), wind generated by TurbSim includes random phases, with the magnitude of each frequency component derived from a velocity spectrum.  "White noise" typically implies a uniform magnitude across all frequencies.  White noise is not a built-in spectrum within TurbSim, but you can implement your own user-defined spectrum through the `TurbModel = "USERINP"` option.  That said, I'm not sure what you intend to implement for the spatial coherence if want a white noise spectrum.

Regarding (2), I've not tried to fit OpenFAST output to an Autoregressive Moving Average model before, but what are you defining as the "input" in this case?  TurbSim generates full-field turbulence, i.e., with the wind velocity varying in both time and space (spatially varying across the 2D XY plane).  So, the wind "input" is actually multi-dimensional.

Best regards,

**Comment by Sunwannasleep** [comment]
> Thank you for your reply.
About (1),I will learn how to generate white noise spectrum.
About (2), I can understand your concept of multidimensional, define the inputdata as the wind speed in the X direction only, that is, the parameter  "Wind1VelX". And I now believe that there is a nonlinear relationship between input _Wind1VelX_ and output _GenTq/GenPwr_.
Thanks again for your help！

**Comment by clun1** [comment]
Dear jjonkman,

Is this a bug? Why is it a negative number?

Best regards,
<img width="858" alt="image" src="https://github.com/OpenFAST/openfast/assets/93849049/7e8ee2f8-44a5-41ae-95b6-28f5d3132072">

**Comment by jjonkman** [comment]
Dear @clun1,

Please provide a bit more background on what your simulation set up is, e.g., what generator or torque control model have you enabled?

Best regards,
