### ISSUE TITLE
Could you please share the pictures or tables which illustrate the "body" and "point" in ElastoDyn with me ?

### ISSUE THREAD

**Issue by ietqlw** [OpenFAST/openfast#1271]
Dear all,

I have been studying the Fast.farm source code recently. I saw plenty of descriptions including "body M", “body F”, "point P" in ElastoDyn.f90. But I haven't found related introductions about those bodies and points in OpenFast Users' Guide.

Could you please share the pictures or tables which illustrate the "body" and "point" in ElastoDyn with me ?

Kind regards!

Chinese Academy of Sciences
Liangwen Qi

**Comment by jjonkman** [comment]
Dear @ietqlw,

The theory of the ElastoDyn structural dynamics module of OpenFAST is documented here: https://openfast.readthedocs.io/en/main/source/user/elastodyn/index.html#elastodyn-users-guide-and-theory-manual.  But this documentation does not include figures.  That said, there are several relevant figures in my old MS thesis-turned NREL report: https://www.nrel.gov/docs/fy04osti/34755.pdf.  While the latter is not fully up-to-date, between these two links, hopefully you'll find the information you seek.

Best regards,

**Comment by ietqlw** [comment]
Dear @jjonkman,

That's quite helpful to me.
Thanks for your careful answer!

Chinese Academy of Sciences
Liangwen Qi
