### ISSUE TITLE
Openfast with Visualstudio

### ISSUE THREAD

**Issue by SaeedHAMB** [OpenFAST/openfast#1274]
Dear all, 
i hope you would help me
i am trying to compile OpenFast with visual Studio (v2019 11.19) as described in the Instruction. it seems to be, that FAST is incompatible with this Version of Visual studio. however, i don't know which version of VS should be compatible. the instruction says VS2019 is okay. I have installed Openfast v3.2
what should i do to fix it?
![image](https://user-images.githubusercontent.com/115216664/194511385-f0303082-3a92-4590-a286-4802c0f5e028.png)

**Comment by jjonkman** [comment]
Dear @SaeedHAMB,

See a similar question asked and answered in the following issue: https://github.com/OpenFAST/openfast/issues/328#issuecomment-642902611.

Best regards,
