### ISSUE TITLE
PlotFASToutput MATLAB\Simulink

### ISSUE THREAD

**Issue by SaeedHAMB** [OpenFAST/openfast#1278]
Dear all,
i am trying to run OpenFast V3.2 with Matlab\Simulink 2021b. i aa running the "Test01" i have a problem with plotting the results. i dont Know what to do to fix this error, can any body help me? 

may Matlab dont Know where to find the the Data to plot, but i still dont Know what to write in the Command Prompt. 

![image](https://user-images.githubusercontent.com/115216664/194731594-04b3b2a8-31a6-436d-8028-4d204b49f169.png)

![image](https://user-images.githubusercontent.com/115216664/194731608-b4dde5ed-985d-40f7-88b6-d0955de15975.png)

![image](https://user-images.githubusercontent.com/115216664/194731632-b3e6a615-fb41-4201-b095-747aaaa2f09b.png)

**Bug description**
<A clear and concise description of the bug.>

**To Reproduce**
<Update the following list with your specific information.>
1. Compile with 'MATLAB 2021b' as instruction from Kumara Raja E

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots, if applicable**
<Add screenshots to help explain your problem.>

**OpenFAST Version 3.2.0**
<Please provide as much detail as possible including git commit. The best information is a screenshot of the OpenFAST system description that prints when running OpenFAST:>

```
**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.0.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Nov 27 2018
  - Time: 17:19:38
 Execution Info:
  - Date: 11/29/2018
  - Time: 10:52:28-0700
```

**System Information (please complete the following information):**
 - OS: <e.g. Ubuntu 14.04 or macOS 10.12>
 - Compiler: <e.g. GFortran 4.4>
 - Compiler settings: <e.g. CMake flags or other settings>

**Additional context**
<Add any other context about the problem here.>

**Comment by bjonkman** [comment]
The OpenFAST-Simulink simulation appears to have finished running, but it can't find the routine that you are calling to plot the data.

`PlotFASToutput` is a function in the OpenFAST/matlab-toolbox repository: https://github.com/OpenFAST/matlab-toolbox. You will need to download that toolbox/function and make sure that the routine is on your Matlab path.

**Comment by SaeedHAMB** [comment]
thank you for your Response. i think it is done Know. 
I still have one Question: I am preparing myself to write my Bachelor Thesis around the dynamic Response of the Foundation of tow arts of floating Wind turbine. the Simulation musst be with OpenFAST. 

Which modules of OpenFAST should I focussed on? 
Is there any training materials to understand how to work with Openfast? 
Which compiler is the best in my situation to work with? MATLAB, VS, or others?

i would be thankful for any Tip

**Comment by jjonkman** [comment]
Dear @SaeedHAMB,

I don't know what you mean when you say, "foundation of tow arts".  Please clarify.

If you are running Windows, you shouldn't need a compiler unless you need to modify the source code.  NREL has already provided precompiled binaries of the OpenFAST executable and OpenFAST interface to MATLAB/Simulink.

Regarding training material, please see my response to a similar question asked here: https://github.com/OpenFAST/openfast/issues/626.  Moreover, we recently released the presentations and sample models from our most recent workshop held in conjunction with NAWEA / WindTech 2022: https://drive.google.com/drive/folders/1Z6hqCxGP57nZTgyTIMi6AkYd83rJuZmh?usp=sharing.

Best regards,

**Comment by jjonkman** [comment]
Dear @SaeedHAMB,

To model the dynamics of floating offshore wind turbines in OpenFAST, requires the use of ElastoDyn (for structural dynamics), AeroDyn (for aerodynamics), InflowWind (for ambient inflow wind), ServoDyn (for the controller), HydroDyn (for hydrodynamics), and a mooring module (e.g., MAP++ or MoorDyn) for response of the stationkeeping system.   Modules such as BeamDyn can optionally be used for high-fidelity blade structural dynamics modeling and SubDyn can be optionally be used for hydro-elastic effects and internal member-level loads of the substructure, if desired.

Best regards,
