### ISSUE TITLE
Feature request--Can be use MBC3 if we use OLAF+BeamDyn?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1284]
Dear all, 

We have known that the OLAF method doesn't support linearization, so does it mean that we can not use MBC3 if we use OLAF + BeamDyn to make aeroelastic analysis? And are there any methods to realize this function?

Best regards,

**Comment by ebranlard** [comment]
Hi @ZL6462, 

You are correct, you cannot perform linearizations with OLAF on at the moment. Which means you cannot get a linearized model from OpenFAST with OLAF on, and therefore you cannot apply the MBC3 to the linearized model. 
We could implement linearization with OLAF, but we would need to have a funded project for it. 

Currently you'll have to use BEM, with frozen wake or DBEMT_Mod=3, and without unsteady aerodynamics or with UAMod=4 or 6. 



Emmanuel

**Comment by ZL6462** [comment]
Hi @ebranlard ,

Thank you for your reply,

As you mentioned above, we can use linearization with DBEMT_Mod=3, and with UAMod=4 or 6, however, with OpenFAST_v3.2.1, this can not be realized. The screen still warns that: "FAST_InitializeAll:AD_Init:ValidateInputData:DBEMT cannot currently be used for linearization. Set WakeMod=0 or WakeMod=1."

Best regards

**Comment by jjonkman** [comment]
Dear @ZL6462,

The linearization of AeroDyn with dynamic blade-element/momentum theory (DBEMT) and unsteady airfoil aerodynamics enabled was implemented in the following pull request, which has been merged into the dev branch of OpenFAST and is scheduled for release in OpenFAST v3.3: https://github.com/OpenFAST/openfast/pull/1000.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman 
Thank you for your reply, I have found the dev version as your direction.
Best regards,
