### ISSUE TITLE
Openfast can’t converge in idling cases with beamdyn

### ISSUE THREAD

**Issue by zcgzcg50** [OpenFAST/openfast#1300]
I tested several idling cases in openfast  with beamdyn and they can’t converge. I think it’s caused by blade root displacement, shown as follows.
I tried:
Rhoinf=0,
DT=0.0015s/0.0005s(not shown, only diverge later than dt=0.0015s)
Exe: OpenFAST-v3.2.1, double precision
Test turbine: NERL 5MW 
Pitch angle:90deg
Should I increase the stop_tol? But if I conduct a very long-time simulation, this will occur eventually.
![image](https://user-images.githubusercontent.com/97574914/197748003-ddb51302-19a5-4b1a-9e08-2faf449867a8.png)
![image](https://user-images.githubusercontent.com/97574914/197748041-61cd7f70-d7c5-4161-aab7-dee1040f5980.png)

**Comment by jjonkman** [comment]
Dear @zcgzcg50,

The plots you show have a very small y-axis.  Can you clarify more what issue you are facing?  Is the solution diverging more globally, or just locally?  Can you clarify what conditions you are simulating?

Best regards,

**Comment by zcgzcg50** [comment]
hello @jjonkman, please see above, I add some information.
NREL 5 MW model is from the r-test files https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast/5MW_Land_BD_DLL_WTurb.
Idling case conditions:
CompElast=2
steady wind=13m/s, 
Blade 1,2,3 initial pitch=90deg , 
VSMODE=0, PCMODE=0.
Divergence is caused by Beamdyn, it shows at the end of simulation:

> FAST_Solution:FAST_AdvanceStates:B2:BD_GA2:BD_DynamicSolutionGA2:Solution does not converge after
> the maximum number of iterations
> 
>  OpenFAST encountered an error at simulation time 58.371 of 600 seconds.
>  Simulation error level: FATAL ERROR
> 
>  Aborting OpenFAST.

Oscillation only occured at N001 blade station, and N002 and others are smooth in time series. The oscillation is not a blade mode shape.  Divergence is locally.
**IEA 15 MW have the same problem.**
I tried to use a larger stop_tol, it may converge, but maybe not accurate.
I tried a shot time step, it may converge, but increasing simulation time remarkably, especially for large turbine.
Can you give me some suggestions for divergence?

**Comment by ptrbortolotti** [comment]
Hello @zcgzcg50 ,
I've run many simulations using BeamDyn for the IEA15 and I've never observed this issue. 
Note that I'm less familiar with the BD model of the NREL5MW and I tend not to use it since the K and I matrices for the blades of the NREL5MW weren't derived with a cross sectional solver like VABS, but were instead created starting from PreComp, which neglects shear stiffness and cannot populate the full 6x6. 
I've now launched the case that you describe above and I'll check the outputs. In the meanwhile, do you have the input files where the error is generated in the IEA15?
Thanks,
Pietro

**Comment by ptrbortolotti** [comment]
Hello again @zcgzcg50,

I could reproduce the issue and, as you pointed out in your messages, I think it's related to an excessively large time step. @jjonkman can explain things in better detail, but currently BeamDyn and ElastoDyn (and SubDyn) are coupled with a loose-coupling scheme that forces to use tiny time steps across OpenFAST modules. 

I can run the simulations successfully if I adopt a time step DT of 0.0005 s (0.5 ms). We're aware of the excessive computational costs required and we're actively working on a new coupling scheme. The work is funded by the Big Adaptive Rotor project (https://www.nrel.gov/wind/big-adaptive-rotor.html) and we hope to have it implemented by April 2023. For the time being I'm afraid you will need to accept longer simulations.

I hope this helps.

Best regards,
Pietro

**Comment by zcgzcg50** [comment]
Hello @ptrbortolotti 
Please see the link below. It's a monopile wind turbine.
[https://github.com/zcgzcg50/test/blob/main/IEA-15-240-RWT-Monopile-idling-13ms.zip](url)

**Comment by zcgzcg50** [comment]
thanks for your helps.
