### ISSUE TITLE
Feature request--Why blade structural translational velocity (STVx) is always positive?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1312]
Dear all, 

I have conducted aeroelastic simulation of NREL 5MW (fixed bottom) with aerodyn+beamdyn, and I am confused with why the x-component structural translational velocity (STVx) of the blade tip is always positive during a rotation:
![untitled](https://user-images.githubusercontent.com/98078424/200115600-ef7a6c9c-9b9f-4ab0-b985-fa0b34f28416.jpg)

As we know effected by the gravity, the blade will experience reciprocating motion, so the x-velocity of the blade tip should varies between negative and positive values.

Best regards,

**Comment by jjonkman** [comment]
Dear @ZL6462,

Presumably you are referring to the AeroDyn output `BαNβSTVx`.  You haven't stated which output node you are plotting, but I'm guessing this has to do with the orientation of the local blade coordinate system with which this output is reported in.  For example, if the x axis of the local blade coordinate system is directed toward the shaft by a small amount, the rotation of the rotor will result in continuously positive x velocity.  See the following figures in the online AeroDyn documentation for more information:
https://openfast.readthedocs.io/en/main/_images/aerodyn_blade_geom.png
https://openfast.readthedocs.io/en/main/source/user/aerodyn/appendix.html#ad-blade-local-cs

Best regards,
