### ISSUE TITLE
OLAF wake circulation is zero when FreeWakeStart is used

### ISSUE THREAD

**Issue by ebranlard** [OpenFAST/openfast#1313]
**Bug description**
The wake circulation is zero when FreeWakeStart is used. This will result in zero induction, which is not the expected behavior. 

This is likely an easy fix and a minor bug. 

**OpenFAST Version**
This feature used to work at some point. The bug is definitely present in v3.3

**Comment by ebranlard** [comment]
It is likely that you used the input `FullCircStart` instead of using `FreeWakeStart`. 

Don't do that :)

**Comment by andrew-platt** [comment]
![IMG_0929](https://user-images.githubusercontent.com/2745453/203641230-b3255feb-0947-4685-b8bd-d6f17f23e651.jpeg)
