### ISSUE TITLE
Does FAST have filtering function？

### ISSUE THREAD

**Issue by Sunwannasleep** [OpenFAST/openfast#1322]
I noticed that when the wind speed was disturbed, the output power and other physical quantities did not fluctuate significantly. 

Does the air processing module **inflowwind** and **Aerodyn** have filtering function?Whether the wind is filtered？

**Comment by jjonkman** [comment]
Dear @Sunwannasleep,

The InflowWind module of OpenFAST does not have a filter.

The AeroDyn module of OpenFAST can include dynamics in the aerodynamic load calculation that can act like a filter, depending on which functionality is enabled (e.g., the dynamic blade element/momentum theory DBEMT is essentially a low-pass filter on aerodynamic induction).  But the ambient wind is not directly filtered by AeroDyn.

Best regards,

**Comment by Sunwannasleep** [comment]
i got it, thank you very much.

Best regards
