### ISSUE TITLE
Rename OpFM module to ExtInflow

### ISSUE THREAD

**Issue by andrew-platt** [OpenFAST/openfast#1323]
The `OpenFOAM` module interfaces with SOWFA, NALU-Wind, and AMR-Wind.  Renaming this module will reflect that it couples to more than just the OpenFOAM code used in SOWFA.

**Comment by deslaughter** [comment]
@andrew-platt , wasn't this completed in PR #1687?

**Comment by andrew-platt** [comment]
yes. Forgot to close this then.
