### ISSUE TITLE
Use Official pfUnit GitHub repo

### ISSUE THREAD

**Issue by citibeth** [OpenFAST/openfast#134]
@tclune The official `pfUnit` repo has now moved to GitHub, no more Source Forge!  See https://github.com/Goddard-Fortran-Ecosystem/pFUnit

**Comment by rafmudaf** [comment]
@citibeth this is great news!

**Comment by rafmudaf** [comment]
@citibeth currently, the master branch of pfunit does not configure correctly through CMake on NREL's compute system. I'll the develop branch of the official pfunit repo and issue a pull request, if necessary. Until those issue are fixed, however, we'll have to maintain our fork. Thanks for bringing this up.

**Comment by citibeth** [comment]
Tom Clune @tclune is the author of pfUnit.  Maybe he would know why this is?  The PR sounds like a good idea to me, and I'm glad we have this opportunity to merge things back.

**Comment by rafmudaf** [comment]
I opened an issue on @tclune's repo https://github.com/Goddard-Fortran-Ecosystem/pFUnit/issues/12

**Comment by rafmudaf** [comment]
@citibeth I see that you have a fork of `openfast/pfunit`. I've updated `openfast/openfast` to use the official pfunit repository so I'll be deleting the `openfast/pfunit` mirror soon.

**Comment by citibeth** [comment]
Thanks for the heads-up, I deleted it.


On Tue, Jun 5, 2018 at 11:42 AM, Rafael M Mudafort <notifications@github.com
