### ISSUE TITLE
problem about airfoil data

### ISSUE THREAD

**Issue by fpxno1** [OpenFAST/openfast#1350]
could you please If I change the shape of airfoil,how can I get the data about cl cd cm vs alpha?
thank you very much

**Comment by jjonkman** [comment]
Dear @fpxno1,

Airfoil data (Cl, Cd, and Cm versus angle of attack, and perhaps Re number) is typically derived for a given airfoil based on wind tunnel or computational solutions.  For thin airfoils, engineering tools such as XFoil or RFoil (not developed by NREL) can be used to calculate airfoil data up to the stall point.

Best regards,

**Comment by fpxno1** [comment]
Thank you very much !
