### ISSUE TITLE
QUESTION 

### ISSUE THREAD

**Issue by DL-JerkLearner** [OpenFAST/openfast#1352]
Hello everyone! I had problems running IEA15MW unit with ROSCO controller.

I have debugged the operation of 5MW onshore wind turbine, and an error is reported when transferring to 15MW unit:

**Error reported by S-function 'FAST_ SFunc' in 'ROSCO/FAST Nonlinear Wind Turbine/S-Function': FAST_ InitializeAll:FAST_ Init:FAST_ ReadPrimaryFile:Invalid logical input for file

"E:\openfast\openfast_3.0.0_bianyitest\ROSCOtest\ROSCO-main\ROSCO-main\Test_Cases\IEA-15-240-RWT-UMaineSemi\IEA-15-240-RWT-UMaineSemi.fst"

occurred while trying to read SumPrint.**

I suspect that the versions of SFunc and fst files are different.

So, I downloaded different versions of SFunc.

The following errors occurred in V3.2.0:

**Error due to multiple causes.

Caused by:

Error due to multiple causes.

Error in port widths or dimensions. Output port 1 of 'ROSCO/PitchSaturation' is a one dimensional vector with 1 elements.

Incorrect use of runFAST (line 58)

Error in port widths or dimensions. Input port 3 of 'ROSCO/Mux2' is a one dimensional vector with 44 elements.**

The following errors occurred in V3.3.0:

**Error due to multiple causes.

Error reported by S-function 'FAST_ SFunc' in 'ROSCO/FAST Nonlinear Wind Turbine/S-Function':

FAST_ InitializeAll:HydroDyn_ Init:HydroDynInput_ ProcessInitData: A requested output channel is invalid

FAST_ InitializeAll:MD_ Init: Unable to parse Line type 1 on row 7 in input file. Row has wrong number of columns. Must be 10

columns.**

How should these two kinds of mistakes be corrected?

It's OK to change one, as long as it works normally.

**Comment by DL-JerkLearner** [comment]
When I increased the simulated wind speed (steady wind), I also got the following error:

**Error reported by S-function 'FAST_SFunc' in 'ROSCO/FAST Nonlinear Wind Turbine/S-Function':
FAST_Solution:FAST_AdvanceStates:AD_UpdateStates:SetDisturbedInflow:TwrInfl:getLocalTowerProps:Tower strike.**

I don't know how to solve it.

**Comment by jjonkman** [comment]
Dear @DL-JerkLearner,

Regarding the v3.2 errors, your question sounds similar to the one asked and answered here: https://github.com/OpenFAST/openfast/issues/1205.

Regarding the v3.3 error, a similar question was asked and answered here: https://github.com/OpenFAST/openfast/discussions/1339.

Regarding the Tower strike error, did you change the initial rotor speed and initial blade-pitch angle when changing the wind speed?  If not, the controller may not respond properly.

Best regards,
