### ISSUE TITLE
problem when I compile the FAST_SFunc in Matlab 2020rb

### ISSUE THREAD

**Issue by fpxno1** [OpenFAST/openfast#1359]
when I compile the FAST_SFunc in Matlab 2020rb,I have some trouble and need help,Iintend to re compile the FAST_SFunc.mexw64 of fast_v8 in matlab 2020rb
![image](https://user-images.githubusercontent.com/57779494/205042570-7d8561ee-9595-4132-99e5-1b888bf7c6db.png)

**Comment by bjonkman** [comment]
What C compiler are you using in Matlab? It looks like the compiler doesn't have a `min` function, so it's not able to build.

**Comment by fpxno1** [comment]
> 

I used the MinGW-W64 GCC-8.1.0 to compile it ,but I don't know why this doesn't include min function

**Comment by fpxno1** [comment]
I add the "#define min(x,y) ((x) < (y) ? (x) : (y))" in FAST_SFunc.c and solved this problem,thank you very much
