### ISSUE TITLE
MEX compilation fail: warning C4133 + error C2198

### ISSUE THREAD

**Issue by hbasbas** [OpenFAST/openfast#1366]
Dear all, 

I am facing problem with the compilation of the mex file for the interface between OpenFAST 3.3.0 and Matlab2021a. 

I complied the libraries with VS 2019 and the IntelOneAPI Toolkit + HPC. Then I use the VS 2019 C++ compiler for the mex file. However, I have the following errors: 

_**create_FAST_SFunc

----------------------------
Creating ../../../build/bin\FAST_SFunc.mexw64

Building with 'Microsoft Visual C++ 2019 (C)'.
Error using mex
FAST_SFunc.c
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(34): warning C4005: 'min'ÿ: red‚finition de macro
C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\ucrt\stdlib.h(1283): note: voir la d‚finition pr‚c‚dente de 'min'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(182): warning C4244: '='ÿ: conversion de 'double' en 'int', perte possible de donn‚es
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(204): warning C4133: 'fonction'ÿ: types incompatibles - de 'double *' … 'const char *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(204): warning C4133: 'fonction'ÿ: types incompatibles - de 'double [53]' … 'int *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(204): warning C4133: 'fonction'ÿ: types incompatibles - de 'char [1025]' … 'int *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(204): warning C4133: 'fonction'ÿ: types incompatibles - de 'int *' … 'double *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(204): warning C4133: 'fonction'ÿ: types incompatibles - de 'int *' … 'double *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(204): warning C4133: 'fonction'ÿ: types incompatibles - de 'double *' … 'int *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(204): warning C4133: 'fonction'ÿ: types incompatibles - de 'int *' … 'char *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(204): warning C4133: 'fonction'ÿ: types incompatibles - de 'char [80001]' … 'double *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(204): error C2198: 'FAST_Sizes'ÿ: pas assez d'arguments pour un appel
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(427): warning C4133: 'fonction'ÿ: types incompatibles - de 'int *' … 'bool *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(427): warning C4133: 'fonction'ÿ: types incompatibles - de 'char [1025]' … 'int *'
C:\IFAC2022\OpenFAST\glue-codes\simulink\src\FAST_SFunc.c(427): error C2198: 'FAST_Update'ÿ: pas assez d'arguments pour un appel

clÿ: Ligne de commande warning D9025ÿ: substitution de '/MD' par '/MT'

Error in create_FAST_SFunc (line 60)
mex('-largeArrayDims', ...**_

It is quite strange since I have made this process many times and it worked well. I just recently download MLife on NREL website that asks for VS 2019 C++ runtime libraries. I installed them and it makes MLife works but when using OpenFAST with simulink, it makes Matlab crash. So I desinstalled the VS2010 libraries and all the VS 2019 packages with IntelOneAPI compilers and I reinstalled VS 2019 and IntelOneAPI after and get the mentionned errors. If you have any idea....

**Comment by bjonkman** [comment]
Hmmm... this is very strange. I wonder if it would help if you run `mex -setup C++` again? It seems like Matlab has gotten confused about the Microsoft Visual C++ 2019 location. Or maybe your system is missing files after the uninstall/reinstall process? The fact that it's redefining macros makes me wonder if there are multiple versions of that stdlib.h file on your Matlab path.

**Comment by hbasbas** [comment]
Thank you for your reply. 

In fact, very strange. After desinstallation of the Intel OneAPI Basic and HPC toolkits + VS 2019 and reinstallation of them. I still get this error. So, I just remake this process and I downloaded once again openfast. Then, the compilation works again. 
I don't understand why and how, but it finally works again.
