### ISSUE TITLE
OpenFAST aborts with an invalid pointer error

### ISSUE THREAD

**Issue by luethen** [OpenFAST/openfast#138]
OpenFAST aborts with an invalid pointer error when using the `r-test/glue-codes/fast/5MW_Land_DLL_WTurb/`-example with the following modifications:
- using steady InflowWind `../5MW_Baseline/NRELOffshrBsline5MW_InflowWind_Steady8mps.dat`
- `TwrPotent = 0`
- `TwrAero = False`

It works when specifying `NumTwrNds <=6` in `NRELOffshrBsline5MW_Onshore_AeroDyn15.dat` (in particular, `NumTwrNds=0` works).

In the [user guide](http://openfast.readthedocs.io/en/master/source/user/aerodyn/input.html#tower-influence-and-aerodynamics) it says that the tower nodes 

> are only used when `TwrPotent > 0`, `TwrShadow = TRUE`, or `TwrAero = TRUE`

but it doesn't say that they need to be removed when `TwrPotent=0` & `TwrShadow=False` & `TwrAero = False`.

This is the error message:

`*** Error in '../../../../openfast/install/bin/openfast': munmap_chunk(): invalid pointer: 0x0000000002fce280 ***`
[...]
`Program received signal SIGABRT: Process abort signal.`
`Backtrace for this error:`
`#0  0x7FC7E5BB8E08`
`#1  0x7FC7E5BB7F90`
`#2  0x7FC7E50AA4AF`
`#3  0x7FC7E50AA428`
`#4  0x7FC7E50AC029`
`#5  0x7FC7E50EC7E9`
`#6  0x7FC7E50F9697`
`#7  0xA38EC4 in __aerodyn_types_MOD_ad_destroyinitoutput`
`#8  0x54011B in cleanup.31021 at FAST_Subs.f90:?`
`#9  0x65E919 in __fast_subs_MOD_fast_initializeall`
`#10  0x67F738 in __fast_subs_MOD_fast_initializeall_t`
`#11  0x53687D in MAIN__ at FAST_Prog.f90:?`
`Aborted (core dumped)`

**Comment by jjonkman** [comment]
Dear @luethen,

This is not a bug.  As stated in section 4.1.2.3.7 of the AeroDyn documentation (http://openfast.readthedocs.io/en/master/source/user/aerodyn/input.html#aerodyn-primary-input-file), the input parameters in the TOWER INFLUENCE AND AERODYNAMICS section of the AeroDyn primary input file are unused when TwrPotent > 0, TwrShadow = TRUE, or TwrAero = TRUE.  This is equivalent to requiring that NumTwrNds = 0.

Best regards,

**Comment by luethen** [comment]
Dear @jjonkman, 
thank you for the clarification.
