### ISSUE TITLE
Peak-spectral period

### ISSUE THREAD

**Issue by BukalNUS** [OpenFAST/openfast#1380]
Hi may I know how the peak-spectral period of incident waves is determined in the HydroDyn?

Thank you:)

**Comment by jjonkman** [comment]
Dear @BukalNUS,

The peak-spectral period is a user-specified input to HydroDyn (not determined by HydroDyn).  It defines the wave period where the peak of the wave spectrum is concentrated.  HydroDyn uses an analytical equation to define the wave spectrum (the JONSWAP spectrum) based on the peak-spectral wave period (`WaveTp`) and significant wave height (`WaveHs`).  See the online HydroDyn documentation for more information: https://openfast.readthedocs.io/en/main/source/user/hydrodyn/index.html.

Best regards,

**Comment by BukalNUS** [comment]
Ok thank you so much :)
