### ISSUE TITLE
frequency domain

### ISSUE THREAD

**Issue by BukalNUS** [OpenFAST/openfast#1384]
Hi may I know if it is possible to gain a frequency domain in the software?

Thank you :)

**Comment by jjonkman** [comment]
Dear @BukalNUS,

I'm not exactly sure I understand your question, but OpenFAST solves wind turbine dynamics nonlinearly in the time domain, not the frequency domain.  That said, the time-series output data from OpenFAST is often post-processed in the frequency domain (e.g., to calculate the power spectra density).

OpenFAST can also export a linear equivalent state-space model at a given operating point, from which a frequency-domain model can be derived via suitable post-processing of the linear state matrices.

Best regards,

**Comment by BukalNUS** [comment]
Ok i understand. Thank you.
