### ISSUE TITLE
HDF5 1.12

### ISSUE THREAD

**Issue by jrood-nrel** [OpenFAST/openfast#1387]
OpenFAST cannot currently find HDF5 1.12. We would like this to be updated.

**Comment by deslaughter** [comment]
@jrood-nrel, please provide the following additional information:

- How OpenFAST is being built?
- Which platform are you using?
- What is the error message?

**Comment by jrood-nrel** [comment]
First, does OpenFAST with HDF5 1.12 work for you?

**Comment by deslaughter** [comment]
I was able to build OpenFAST (openfast-cpp) with HDF5 1.12.1 on Ubuntu. I don't have a good test case to run against to see if actually creates an HDF5 file.

**Comment by jrood-nrel** [comment]
Did you build HDF5 with CMake or Autotools?

**Comment by deslaughter** [comment]
Autotools. I used the commands in the OpenFAST repository's `share/fast-install.sh` script (`compileHDF5` function).

**Comment by jrood-nrel** [comment]
It's most likely the issue I have with OpenFAST not finding HDF5 1.12 is when it is built with CMake. Unfortunately this totally changes how HDF5 is installed.

**Comment by deslaughter** [comment]
Are you doing the install through CMake? I would expect the files to go to the same places for both build systems.

**Comment by jrood-nrel** [comment]
Ok it was helpful just to know that OpenFAST is able to build somehow with HDF5 1.12. It looks like maybe we can't use this option for newer HDF5 versions https://github.com/spack/spack/blob/521cc41db0b1e294a7e61eea6b0725139044c173/var/spack/repos/builtin/packages/openfast/package.py#L89-L93 which means HDF5 may have fixed some issues in their CMake. As in removing that option, which is necessary for HDF5 1.10, seems to find 1.12 for me. I will close this for now. Thanks for looking into that and sorry I wasn't thorough in my initial attempts.
