### ISSUE TITLE
Two problems encountered when running fast are related to pitch angle

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#1408]
Hello everyone
1. I run fast in a certain model. When the wind speed exceeds a certain value, it is about 23m/s, the pitch angle will not change, and the torque will return to zero
![bb47570b5689970e4ad51d62c46567c](https://user-images.githubusercontent.com/56157328/211989174-f42eb37b-7d10-4925-94cb-ae523c36ad0a.png)

2. When I run fast in a model, the pitch angle will not change and will remain at 0. The torque speed and power output seem to be normal, but they exceed the rated value because there is no pitch change.
![5603971c22b690e0c37964d2f870942](https://user-images.githubusercontent.com/56157328/211989207-a404aa51-61be-4b90-9e3b-b252fc71f892.png)

For the above two problems, I used the same controller for simulation in bladed, and found that it can operate normally in bladed.

**Comment by shipors** [comment]
good everybody
I have resolved the first problem successfully. There are some errors in my controller.

**Comment by jjonkman** [comment]
Dear @shipors,

I presume your second question is also related to your controller...  Are you using a controller provided by NREL such as the baseline controller for the NREL 5-MW wind turbine or ROSCO?

Best regards,

**Comment by shipors** [comment]
Dear jjonkman,


thank you for your reply. I use dll controller witten by myself.&nbsp;


In fact,The two controllers are very similar. I don't know why the first controller works and the second one doesn't.


Is there perhaps a setting in fast that sets the pitch angle output to zero?


best wishes.












邵茂峰
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Jan 12, 2023 21:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OpenFAST/openfast] Two problems encountered when running fastare related to pitch angle (Issue #1408)




 
Dear @shipors,
 
I presume your second question is also related to your controller...  Are you using a controller provided by NREL such as the baseline controller for the NREL 5-MW wind turbine or ROSCO?
 
Best regards,

**Comment by jjonkman** [comment]
Dear @shipors,

You must set `PCMode` to 5 in ServoDyn for OpenFAST to use the blade-pitch commands from a controller DLL.

OpenFAST also supports override pitch manuevers, which take precedent over the commands from the pitch controller when enabled via ServoDyn inputs `TPitManS`, `PitManRat`, and `BlPitchF` for each blade.

Best regards,

**Comment by shipors** [comment]
Dear jjonkman,

Thank you for your ideas! I have solved the problem successfully.

As you said, I modified the parameter of `BlPitchF` and `Ptch_Max `, in ServoDyn, they are both 0 before I changed  numbers. I don't understand this two parameters very much. Could you tell me the difference between the two parameters?

According to my experience in solving this problem, if one of the two parameters is set to zero, the pitch angle output of the external controller will not work.

Best wishes!

**Comment by jjonkman** [comment]
Dear @shipors,

ServoDyn input `BlPitchF` is the final angle after the override pitch maneuver.  The value is only used if `TMax < TPitManS` for any blade.

ServoDyn input `Ptch_Max` is a parameter that will be passed to Bladed-style DLL controllers, representing the maximum pitch angle.  It is only used if `PCMode` = 5 in ServoDyn and if your user-defined controller makes use of the parameter.

Best regards,

**Comment by shipors** [comment]
Dear @jjonkman 

Thanks again for your support!

Best wishes,
