### ISSUE TITLE
Calculation of power coefficient using FAST

### ISSUE THREAD

**Issue by EhsanASL92** [OpenFAST/openfast#1410]
Hi,

In Simulink, I've just implemented a PMSG outside the FAST block. Now to calculate the produced power I need to have the exact value of c_p. However, I found an approximated dynamic of **c_p** in some literature. I wonder if I can get the **c_p** through the OutList. I am new to FAST.

Best regards,
Ehsan ASLMOSTAFA

**Comment by jjonkman** [comment]
Hi @EhsanASL92,

Are you using AeroDyn v15?  You can output the rotor aerodynamic power coefficient from the `OutList` of AeroDyn v15 via output `RtAeroCp`.

Best regards,

**Comment by EhsanASL92** [comment]
Dear @jjonkman ,

Thanks for your reply. I get the **outList** through the **outData** in Fast. It is an 83*1 array which I attached below. I don't know exactly how can I access the OutList of AeroDyn15! since in the 83*1 array I cannot find RtAeroCp?
[matlab.zip](https://github.com/OpenFAST/openfast/files/10428400/matlab.zip)

**Comment by jjonkman** [comment]
Dear @EhsanASL92,

I do see other AeroDyn v15 `OutList` parameters in this area, e.g., `RtArea`.  You can add `RtAeroCp` to the AeroDyn `OutList` within the AeroDyn input file and rerun you simulation.

Best regards,

**Comment by ebranlard** [comment]
Note that these outputs have recently been renamed `RtFld*` (`RtFldCp` for instance)

**Comment by EhsanASL92** [comment]
Thank you so much dear @jjonkman and @ebranlard,
Is it possible to explain how to add **RtAeroCp** to the AeroDyn **OutList**?

Best regards

**Comment by ebranlard** [comment]
Hi @EhsanASL92 , here's an example of AeroDyn input file where you can see different channels added to the OutList: 
https://github.com/OpenFAST/r-test/blob/main/modules/aerodyn/ad_BAR_RNAMotion/OpenFAST_BAR_00_AeroDyn15.dat#L111
(between the line with the keyword OutList and the line with "END")

**Comment by EhsanASL92** [comment]
Thank you so much @ebranlard,
I tried to add **"RtFldCp"** to the outputs, but I get this while I tried to run FAST!
**FAST_InitializeAll:AD_Init:SetParameters:SetOutParam:RtFldCp is not an available output channel.**

Best regards

**Comment by ebranlard** [comment]
You must be using a version prior to 3.4, then you need "RtAeroCp" instead.

**Comment by EhsanASL92** [comment]
Thank you so much @ebranlard,
I am not sure about the version I am using. But I changed "RtAero" to "RtAeroCp" and see no difference in the output!
Is the power coefficient calculated for OC3 5MW NREL before so I can use the values for different pitch angles?

Best regards
