### ISSUE TITLE
The curled wake model cannot give the right wake velocity distribution (kidney shape distribution) as described in the paper

### ISSUE THREAD

**Issue by getChaos22** [OpenFAST/openfast#1436]
[TSinflow_curl.zip](https://github.com/OpenFAST/openfast/files/10661360/TSinflow_curl.zip)
**Description**
Hi dears,

We tried the curled wake model (Mod_Wake=2) in the **FAST.Farm** simulation, but the obtained wake velocity distribution does not show a kidney shape as described in the [paper](https://doi.org/10.1002/we.2785). The obtained distribution looks more like that calculated by the polar model. 

In addition, when the curled wake model is specified , we found that the solution is hard to converge with a relatively large number of wake planes (NumPlanes) .i.e 150. We tried the input recommendations given in this [website](https://openfast.readthedocs.io/en/main/source/user/fast.farm/InputFiles.html), but sometimes it was still not easy to give a  converge solution.

Do you have any ideas about these problems?

Thanks so much!

**To Reproduce**
We basically use the same case file (TSinflow_curled) given in the r-test/glue-codes/fast-farm/ repository. Just a little modifications were made. We put the case file the in the attachment. The non convergence is more likely to happen when the yaw angle is zero.

**Screenshots, if applicable**
The wake velocity distribution we obtained with the curled wake model:(The slice was sampled around 8D downstream)
![image](https://user-images.githubusercontent.com/120010727/216926256-e790444e-b95a-4e90-beb8-0eaa1944fd74.png)

The wake velocity distribution shown in the [paper](https://doi.org/10.1002/we.2785):
![image](https://user-images.githubusercontent.com/120010727/216926904-59c423ab-8c7e-4781-bb13-f1c7535a44aa.png)

The case that failed to converge:
![image](https://user-images.githubusercontent.com/120010727/216927425-b174dcbd-00de-4c00-8cc7-be548326b7a6.png)

**OpenFAST Version**
<Please provide as much detail as possible including git commit. The best information is a screenshot of the OpenFAST system description that prints when running OpenFAST:>

```
1  **************************************************************************************************                                            
2  FAST.Farm                                                                                                                                     
3                                                                                                                                                
4  Copyright (C) 2023 National Renewable Energy Laboratory                                                                                       
5  Copyright (C) 2023 Envision Energy USA LTD                                                                                                    
6                                                                                                                                                
7  This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.                                              
8  See the "LICENSE" file distributed with this software for details.                                                                            
9  **************************************************************************************************                                           
10                                                                                                                                               
11  FAST.Farm-v3.4.0-dirty                                                                                                                       
12  Compile Info:                                                                                                                                
13   - Compiler: GCC version 9.4.0                                                                                                               
14   - Architecture: 64 bit                                                                                                                      
15   - Precision: double                                                                                                                         
16   - OpenMP: No                                                                                                                                
17   - Date: Jan 13 2023                                                                                                                         
18   - Time: 13:54:25                                                                                                                            
19  Execution Info:                                                                                                                              
20   - Date: 02/06/2023                                                                                                                          
21   - Time: 16:45:44+0800
```

**Comment by ebranlard** [comment]
Hi @getChaos22, 

Thank you for posting this. It seems that the default value for k_VortexDecay is too strong in this case. You can try to set it to 0, or to a smaller value like 0.0001. The default is currently 0.01 (somehow the input file says 0, that seems to be an omission on our side). 

I had colleagues lower a bit the value of `f_c` (e.g. divide by 2) compared to the one you would obtain based on the equation given in the input file section for `f_c`. 

When WakeMod=2,3, there is a stability criterion for DT_Low, but this would typically result in quite small values for DT_Low (even the test case do not respect it). If you still have stability issues you can try decreasing DT_Low, or increasing dr. 

I hope that helps a bit...

**Comment by getChaos22** [comment]
Hi @ebranlard,

Thanks for the quick reply!

Your advise on the k_VortexDecay really works. Here is the velocity distribution we got:
![image](https://user-images.githubusercontent.com/120010727/217134218-df414163-a4cf-4610-b4d8-797fd5ad3b0f.png)


The recommended value of DT_Low (DT_Low⪅dr/(2VHub)) is a little expensive for us, because it means more wake planes. We also tried the way of increasing dr. We thought this is a more efficient method than decreasing DT_Low to avoid instability. dr = 8m can basically ensure the convergence for our test case (the default value in the input file is 5m). But we are not sure how much accuracy will lose through this method, because dr affects the gradient calculation and furthermore will affect the eddy viscosity. 

Could you give us some advises?

Thanks.

**Comment by ebranlard** [comment]
Hi @getChaso22, 
I'm glad the setting of k_VortexDecay works. 

I don't really have a good advice for the stability. The time integration scheme for WakeMod=2,3 is not very robust. The stability criterion "rule of thumb" is often hard to reach. You'll have to do a bit of trial an error to find parameters that do no respect the rule of thumb but are still stable. Typically, when the simulation is unstable, it leads to very unrealistic results, which is "spotable". 

Do you still have instabilities with dr=5m? as you mention, you might have to increase dr, but you'll indeed loose in resolution. Maybe dr=5.5m works?

You could potentially increase FilterInit from 1 to 2. This will smoothen the wake gradients, which was proven to also increase the stability. 

That would be my only advices for now...

**Comment by getChaos22** [comment]
Hi @ebranlard,

We test again and tried dr =5.5m, 6m, 7m and 8m, and when dr>=6m the stability can be ensured. We tried to switch FilterInit from 1 to 2, which indeed increases the stability but still cannot ensure convergence throughout the simulation. 
We also believe that a series of numerical trial is really needed. 

Thanks again for all of your advises. I think I can close this issue.
