### ISSUE TITLE
Custom wind turbine (OpenFAST) and wind farm (FAST.Farm) controller in C

### ISSUE THREAD

**Issue by ArnoldTUB** [OpenFAST/openfast#1437]
Hello everyone,

For a research project, I want to code custom controller for individual wind turbine control and for wind farm control. 
If I understand correctly, both controllers can be provided via dynamic libraries. 
Now, I wonder
- Can such libraries be compiled via C code? I saw some examples based on controllers written in Fortran but to my understanding it shouldn't matter, should it?
- What functions (names, inputs, outputs) should custom libraries contain for OpenFAST and FAST.Farm to work with them?
- How would I include my custom libraries into one of the various `CMakeLists`-files for OpenFAST and FAST.Farm to be properly compiled with the custom controllers?

Sorry if answers to these questions are already provided somewhere. I tried my best to find anything myself with no result. I hope you can help me out on this one.

Best
Arnold

**Comment by deslaughter** [comment]
@ArnoldTUB, yes, it would be possible to write the controller in C. The controller would need to satisfy the OpenFAST controller interface and be compiled as a shared library with the control function exported. You can specify the name of the control function to call in the ServoDyn input file. The function prototype would need to be something like (untested):

`void DISCON(float avrSWAP[], int *aviFAIL, char *accINFILE, char *avcOUTNAME, char *avcMSG);`

I recommend taking a look at https://github.com/OpenFAST/r-test/blob/main/glue-codes/openfast/5MW_Baseline/ServoData/DISCON/DISCON.F90 which is a controller used in the OpenFAST regression testing. It provides the location of some of the controller variables that are passed in and out. A more complete listing of the avrSWAP array can be found in https://github.com/OpenFAST/openfast/blob/main/modules/servodyn/src/BladedInterface.f90. 

As for integrating the controller via CMake, I would make an independent file like https://github.com/OpenFAST/r-test/blob/main/glue-codes/openfast/5MW_Baseline/ServoData/DISCON/CMakeLists.txt and then use it via `add_directory` in the main OpenFAST `CMakeLists.txt` similar to how it's done in https://github.com/OpenFAST/r-test/blob/main/CMakeLists.txt.

**Comment by ArnoldTUB** [comment]
Awesome, thank you very much for this detailed answer! I will take a look at everything and see if I can make it work :)

**Comment by deslaughter** [comment]
Feel free to reopen if you have further questions.

**Comment by ArnoldTUB** [comment]
Hello everyone,

I have developed a wind farm controller and implemented it in C. Do you have similar examples as those mentioned by @deslaughter on Mar 7 but for FAST.Farm super controllers?

The wind farm controllers computes yaw angles and axial induction factors. I expect forwarding the yaw values to turbine controllers should work easily but what about the axial induction factors? Can I compute Cp and Ct values and use those? Do I need to compute reference powers? Or something entirely different?

Best
Arnold

**Comment by ArnoldTUB** [comment]
Hello everyone!

I resumed working on this topic and managed to write a wind turbine controller with the aforementioned DISCON function.
Now I want to implement my wind farm super controller via C-code.

From [Table 4.13](https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#ff-tab-sc-dll) I learned which functions, inputs and outputs such a controller library needs to contain. 

Now, I have 3 questions
1. Is there any example for a super controller source file which I could use a template? I tried my best to find something with no success.
2.  I wonder how to specify inputs and outputs in C. Currently, my code is expecting pointers for the output variables such that they are called by reference. Is that the correct approach?
3. In which order do I need to arrange the inputs and outputs, e.g., is
`void sc_init(int nTurbines, int* nInpGlobal, int* NumCtrl2SC, int* NumParamGlobal, int* NumParamTurbine, int* NumStatesGlobal, int* NumStatesTurbine, int* NumSC2CtrlGlob, int* NumSC2Ctrl, int* errStat, char* errMsg)`
fine or should I arrange all variables in another order (I started with the inputs in the order they are mentioned in the link I shared followed by the outputs)?

Best
Arnold

**Comment by jjonkman** [comment]
Dear @ArnoldTUB,

Regarding (1), you can find a sampler (Fotran-based) super controller (sc_dll) in my post dated March 18, 2021 in the following topic on our forum: https://forums.nrel.gov/t/fast-farm/1887.

I'll let others respond regarding the C-related questions.

Best regards,

**Comment by ArnoldTUB** [comment]
Dear @jjonkman,

I was able to resolve all my questions.
Regarding (3), I just ordered all variables similar to the sample controller you referred to.
Regarding (2), I learned that "to a C procedure, a Fortran subroutine or function call looks like a procedure call with all arguments represented by pointers" [[source](https://docs.oracle.com/cd/E19957-01/806-3593/11_cfort.html#:~:text=To%20a%20C%20procedure%2C%20a,from%20a%20CHARACTER*n%20function.)].

Since this issue has already been closed, feel free to ignore it.

Best 
Arnold
