### ISSUE TITLE
Feature request -- Whether the predictor-corrector scheme is used to solve the convection the Lagrangian markers in OLAF?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1443]
Dear all,

I am womdering whether the predictor-corrector scheme is used to solve the convection the Lagrangian markers in OLAF?

In the manual shown in "https://openfast.readthedocs.io/en/dev/source/user/aerodyn-olaf/InputFiles.html", it says that "There are four options: 1) fourth-order Runge-Kutta [1], 2) fourth-order Adams-Bashforth [2], 3) fourth-order Adams-Bashforth-Moulton [3], and 4) first-order forward Euler [5]. The default option is [5]. Currently only options [1] and [5] are implemented. " This means only fourth-order Runge-Kutta or first-order forward Euler are avilable, and predictor-corrector scheme is not used.

However, in the paper “Preliminary Introduction of a Free Vortex Wake Method Into OpenFAST” (https://iopscience.iop.org/article/10.1088/1742-6596/1452/1/012064), it says "At present, a predictor-corrector scheme is used to numerically solve the left-hand side of Equation 2 for the vortex filament location." 

So, whether the predictor-corrector scheme is used to solve the convection the Lagrangian markers in OLAF?

Best wishes,

**Comment by ebranlard** [comment]
Hi @ZL6462 

The predictor-corrector is not implemented in the current version of OLAF. In it's preliminary version, another code base was used. It was since rewritten from scratch, and no predictor-corrector scheme is present. 

Sorry for the confusion...
