### ISSUE TITLE
StC input file for OpenFast v2.1

### ISSUE THREAD

**Issue by relhamoud** [OpenFAST/openfast#1451]
i am trying to do structural control for a spar type floating wind turbine called windcrete. The OpenFast model used is 2.1
I was searching for the StC input file for the 2.1 version of OpenFast. 

where could i find it ?

Thanks

**Comment by jjonkman** [comment]
Dear @relhamoud,

I've now responded to a similar question you posted on our forum--see: https://forums.nrel.gov/t/servodyn-stc-submodule/4495.  I'll close the issue here.

Best regards,
