### ISSUE TITLE
Error running Openfast on Windows

### ISSUE THREAD

**Issue by josujugo** [OpenFAST/openfast#1452]
**FATAL ERROR  running Openfast model on Windows**

I am running the model  from https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/master/OpenFAST/IEA-15-240-RWT-Monopile
and I get the next error:

Z:\Desktop\openfast>openfast_x64.exe Z:\nafarroa\gitlab\openfast\glue-codes\simulink\examples\IEA-15-240-RWT-Monopile\IEA-15-240-RWT-Monopile.fst

**************************************************************************************************
OpenFAST

Copyright (C) 2023 National Renewable Energy Laboratory
Copyright (C) 2023 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v3.4.1
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 2021
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: Feb 11 2023
 - Time: 19:12:02
Execution Info:
 - Date: 02/14/2023
 - Time: 14:15:20+0100

OpenFAST input file heading:
    IEA 15 MW offshore reference model monopile configuration

Running ElastoDyn.

FAST_InitializeAll:ED_Init:ED_ReadInput:ReadBladeInputs:ReadBladeMeshFileAD:Invalid numerical
input for file
"Z:\nafarroa\gitlab\openfast\glue-codes\simulink\examples\IEA-15-240-RWT-Monopile\../IEA-15-240-RW
T/IEA-15-240-RWT_AeroDyn15.dat" occurred while trying to read NumFoil.

 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.

I have test the same Example in Linux and in macOS with good results.

I have tested in Windows using v3.3.0, v3.4.0 v3.4.1 Versions.

**Steps to reproduce the behavior:**
1.  Run openfast_x64.exe PATH\IEA-15-240-RWT-Monopile\IEA-15-240-RWT-Monopile.fst

**System Information):**
 - OS: Windows 10
 - Fast version:  v3.3.0, v3.4.0 v3.4.1 Versions
 - Compiler: Executables from Gihub Release

**Comment by dzalkind** [comment]
I thought it was compatible with OF 3.3, but they tried that one.  Maybe 3.2 or 3.1?  Isn't `NumFoil` an AeroDyn 14 parameter?  Maybe the parameter is re-used.

**Comment by andrew-platt** [comment]
@dzalkind, Good catch.  The `NumFoil` parameter is indeed an AeroDyn 14 input.  However, AeroDyn 15 is being used here.

@josujugo, change `CompAero` to `2` to use AeroDyn 15 with this model.

**Comment by dzalkind** [comment]
And to give a clearer answer than before, the `develop` [branch of that repo](https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/develop/OpenFAST is definitely) is OF v3.4.0.

**Comment by josujugo** [comment]
Ok, thank you very much. I will try your advices. However, it is unclear for me why the Linux and macOs versions are working well.
