### ISSUE TITLE
FAST_InitializeAll: HydroDyn_Init:WAMIT2_Init:DiffQTF_InitCalc: Maximum wave direction required of 30 is not found in the WAMIT data file.

### ISSUE THREAD

**Issue by ietqlw** [OpenFAST/openfast#1457]
Dear all，
![微信截图_20230219154324](https://user-images.githubusercontent.com/79843558/219935580-ba4340e3-600b-4db1-8634-e0f65da9838b.png)

When I conducted a simulation with OpenFAST 3.0.0，the error reported as follow：
FAST_InitializeAll: HydroDyn_Init:WAMIT2_Init:DiffQTF_InitCalc: Maximum wave direction required of 30 is not found in the WAMIT data file.

The simulation case is the OC4 DeepCwind Semi-Submersible floating wind turbines in r-test. The error only occured when I set "WaveDir" in HydroDyn input file as the nonzero value. In addition, when I employed FAST v8 to simulate with the same OC4 wind turbines, no error occured whenever I set "WaveDir"  as a zero or nonzero value.

Hope to get your kind response.

Chinese Academy of Sciences
Liangwen Qi

**Comment by andrew-platt** [comment]
Dear @ietqlw,

The OC4 Semi model does not contain 2nd order hydrodynamic data for a 30 degree wave direction.  This is the reason for the `WAMIT2_Init:DiffQTF` error.

You can run this model with a non-zero wave direction if you disable the second order hydrodynamics.  To disable this, set `DiffQTF` and `SumQTF` to 0.

Regards,
Andy
