### ISSUE TITLE
Wondering if there are some critical setups missing in FAST to better match the wind tunnel results?

### ISSUE THREAD

**Issue by HappyappleTW** [OpenFAST/openfast#1460]
Hi, 
We have been trying to compare the drag forces acting on the tower base of the NREL 5 MW wind turbine using FAST and wind tunnel measurements. The model we have is 1/150 geometrically scaled. We have noticed the effects of Reynolds’s number on blade so we put models of the blade sections (e.g., DU40 … NACA64) in the wind tunnel to just measure the sectional aerodynamic force coefficients (i.e., CD & CL’s) for full range of the angles of attack. Then these aerodynamic coefficients at the ‘correct’ Reynolds’s number (ReC = 20,000) replace the original aerodynamic coefficients at ReC = 750,000 in Aerodyn input files. At pitch angles of around 0 degree and TSR at about 3.1, we found the FAST simulated drag coefficients at tower base are about twice the wind tunnel measurements. We also build our own BEM algorithms based on the book by Manwell and the results of base drags are closer to wind tunnel measurements.  So we’re wondering if we have missing some critical setups in FAST to match better to the wind tunnel results?  Any suggestion is appreciated.  Thanks.

**Comment by jjonkman** [comment]
Dear @HappyappleTW,

Just a few comments/questions:

- An operational condition of 0deg pitch with a TSR = 3.1 is not in the normal operating range of the NREL 5-MW baseline wind turbine.  How do the results compare at more reasonable conditions?
- Have you applied 3D rotational augmentation corrections to the airfoil data or looked at the sensitivity of your results to airfoil data?  I'm guessing there could be large uncertainty in your airfoil data at 1/150 scale, which will greatly impact the results.
- You'll likely need to calibrate the airfoil data to get a good match between OpenFAST and the wind tunnel tests, e.g., as in the following paper: https://www.nrel.gov/docs/fy15osti/63568.pdf.
- I'm not sure I know what is different between the BEM algorithm of Manwell and what is implemented in OpenFAST.  Can you clarify?  Are the results more consistent at more reasonable operating conditions?

Best regards,

**Comment by HappyappleTW** [comment]
Dear @jjonkman

Thank you very much. Your insights are very helpful.

**Comment by HappyappleTW** [comment]
Thanks for your valuable information.  We have read through the paper you mentioned for adjusting the aerodynamic data (https://www.nrel.gov/docs/fy15osti/63568.pdf). In that paper, we noticed that the curve of C_L  versus AOAs are adjusted in several steps during the ‘calibration’ process. In particular, the sharp drop of C_L after the stall angle were raised significantly after the ‘initial setup’ and ‘multi-objective-optimization’ processes. I think that’s the main cause that leads to the differences in the BEM results. So I am wondering if that type of ‘calibration’ process is embedded in Aerydyn (or other FAST) module? If not, is there any software available to adjust the airfoil aerodynamic data to ‘best match’ the wind turbine performance?

**Comment by jjonkman** [comment]
Dear @HappyappleTW,

No, this calibration process is not included as part of OpenFAST/AeroDyn.  Perhaps someone can correct me, but I'm not aware that NREL has developed/shared scripts that automate this calibration process.

I would suggest reaching out to lead author of the referenced paper (Prof. Andy Goupee of the University of Maine) to see if he can share the scripts he used.

Best regards,

**Comment by HappyappleTW** [comment]
Thank you so much for your help, it was incredibly valuable to me. I now have a much better understanding of what I need to do.
