### ISSUE TITLE
Query：About the reading process of the ambient wind with InflowWind Module in FAST.Farm.

### ISSUE THREAD

**Issue by ietqlw** [OpenFAST/openfast#1461]
Dear all，

I used to think that wind gradually propahated into the low-resolution domain defined in FAST.Farm. That is to say, wind reaches the  entrance boundary of the low-resolution domain and wind speeds at all other grid points in low-resolution domain are zero at time = 0. As time marches, wind will gradually fill the whole low-resolution domain.

However, when I use FAST.Farm to conduct a simulation，I found the wind speeds throutht the low-resolution domain are non-zero at time = 0. Hence another guess about the reading process of the ambient wind with InflowWind Module in FAST.Farm occurs. I don't know whether my guess is correct. Hope to get kind response from you.

Here follows my guess:

FAST.Farm defines the low-resolution domain (containing the X-Y-Z space). TurbSim defines the wind data in Y-Z plane at various time steps. At time =0, wind data at time =0 in TurbSim reaches the exit boundary of the low-resolution domain.  As shown in red frame, other wind data at later time steps in TurbSim fill the whole low-resolution domain. Hence at the global time = 0 of FAST.Farm, the wind field of low-resolution domain are filled with wind data with several time steps which are generated by TurbSim. As time marches, the red window is moved to update the ambient wind field from the wind data from TurbSim.

![图片1](https://user-images.githubusercontent.com/79843558/220325246-2118a7a6-71c8-44f2-b796-9a82251d0793.png)

Hope for your patient answer.

Liangwen Qi

**Comment by jjonkman** [comment]
Dear @ietqlw,

The FAST.Farm documentation recommends that the synthetic inflow data from TurbSim be generated periodically.  And I'll assume `PropagationDir` is 0.0 deg (flow propagating along +X) and `Mod_AmbWind` = 2 (a single TurbSim data set is used).  This means the data effectively extends infinitely in time (repeating after time = `AnalysisTime`, which is equivalent to the data extending infinitely in the X direction).  Then, the TurbSim grid (in YZ) at t = 0 s is assumed to be aligned with the FAST.Farm global coordinate system at X = 0, with the YZ coordinates in TurbSim matching the YZ coordinates in FAST.Farm.  And InflowWind propagates the TurbSim domain using Taylor's frozen turbulence assumption, with X = Vmean*t, where Vmean is the mean wind speed (propagation speed) of the YX TurbSim domain.

When `Mod_AmbWind` = 3 (multiple instances of TurbSim data are used), the above statement applies to the TurbSim data associated with the low-res domain.  The only difference is for the TurbSim data associated with each high-res domain, in which case the local TurbSim grid (in YZ) at t = 0 s for each wind turbine is assumed to aligned with the local turbine position at `WT_X`, with the YZ coordinates in TurbSim centered about (`WT_Y`,`WT_Z`) in FAST.Farm.

I hope that helps.

Best regards,

**Comment by ietqlw** [comment]
Dear @jjonkman,

When PropagationDir is 0.0 deg (flow propagating along +X) and Mod_AmbWind = 2 (a single TurbSim data set is used).
The flow propagates along +X, the YZ coordinates in TurbSim then matches the YZ coordinates in FAST.Farm at t = 0 s. I can conclude that flow at t = 0 s only reaches the grid of X=0 in FAST.Farm global frame. The wind speeds in FAST.Farm global frame (X>0) should be zero since the flow has not propagated into those areas. However, when I used the case in the r-test folder, WT2 and WT3 were placed at (1013.0  0.0    0.0) and (2021.0  0.0    0.0), respectively. At t = 0 s, the wind speeds near their hubs are non-zero. I was quite confused about the simulation results.

Hope for your patient answer.

Liangwen Qi

**Comment by jjonkman** [comment]
Dear @ietqlw,

As I said, because the TurbSim data is periodic, this means the data effectively extends infinitely in time, which is equivalent to the data extending infinitely in the X direction.  At t = 0, the wind located at specific distance X downstream can be found by applying Taylor's frozen turbulence assumption.  That is, at t = 0 in FAST.Farm, the wind at X in the FAST.Farm domain is the wind data at time stamp t_TS = -X/Vmean in the TurbSim dataset (if this equation results in a negative value of t_TS because of a positive value of X, this is equivalent to the time stamp AnalysisTime+t_TS due the periodicity of the data.

Best regards,

**Comment by ietqlw** [comment]
Dear @jjonkman，

Thank you for your clear answer. I have understood your meanings.

Liangwen Qi
