### ISSUE TITLE
OpenFAST compiling with  Windows Visual Studio 22

### ISSUE THREAD

**Issue by Chris195513** [OpenFAST/openfast#1481]
Dear all,

Many errors compiling OpenFAST, I use Visual Studio Community 2022, how can I fix this? ,  

![image](https://user-images.githubusercontent.com/127173452/223320440-20642e51-37ca-43a1-acb8-facf4d51ea2e.png)

**Comment by robytian** [comment]
Hi
I think you'd be better off using **Visual Studio2019** installing(https://openfast.readthedocs.io/en/main/source/install/install_vs_windows.html#building-openfast-on-windows-with-visual-studio) **Intel® oneAPI Base Toolkit** after the installation is complete, then installing [**HPCKit**.]([Intel® oneAPI HPC Toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/hpc-toolkit-download.html?operatingsystem=window&distributions=online#collapseCollapsible1668008005862))

**Comment by Chris195513** [comment]
> Hi I think you'd be better off using **Visual Studio2019** installing(https://openfast.readthedocs.io/en/main/source/install/install_vs_windows.html#building-openfast-on-windows-with-visual-studio) **Intel® oneAPI Base Toolkit** after the installation is complete, then installing [**HPCKit**.]([Intel® oneAPI HPC Toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/hpc-toolkit-download.html?operatingsystem=window&distributions=online#collapseCollapsible1668008005862))
![image](https://user-images.githubusercontent.com/127173452/223632993-73c858fd-4395-4fbc-9bf2-7a570497d4e6.png)

same errors with visual studio 2019

**Comment by andrew-platt** [comment]
@Chris195513, have you made any changes to the source code?

**Comment by Chris195513** [comment]
> @Chris195513, have you made any changes to the source code?

I adjust the analysis parameters on " ServoDyn.f90" and "UserSubs.f90".........

**Comment by jjonkman** [comment]
Dear @Chris195513,

It sounds like your compiling issue is similar to the one discussed in the following issue: https://github.com/OpenFAST/openfast/issues/1249.  Following the process outlined that issue should solve your problem.

Best regards,

**Comment by Chris195513** [comment]
Dear @jjonkman 

Thanks for the reply, I finally compiled it without any errors.

**Comment by Tianyao314** [comment]
Dear @Chris195513 

How did you solve these problem? Can you give me some advices?

Best regards,
Yao
