### ISSUE TITLE
FF wind array was exhausted at 62.1 seconds (trying to access data at 72.1 seconds).

### ISSUE THREAD

**Issue by Jamin722** [OpenFAST/openfast#1501]
Dear,all
It is about the modules “5MW_Land_DLL_WTurb” . I did not compile the openfast. I have encountered the following problem
![图片](https://user-images.githubusercontent.com/95916438/226544803-96b6e171-3d81-45f7-a3eb-90543c3550a8.png)

**Comment by jjonkman** [comment]
Dear @Jamin722,

Similar questions have been asked before, e.g., see: https://github.com/OpenFAST/openfast/discussions/1281.

Best regards,
