### ISSUE TITLE
Error when developing bend-twist coupling blade in ED

### ISSUE THREAD

**Issue by AsIlll223** [OpenFAST/openfast#1514]
Hello,everyone

**Background:**

I am trying to modify the ElastoDyn code in Openfast3.4.0 to achieve  the calculation of blade bending and torsion coupling based on the modal method. I add the torsion DOF , corresponding coeff , elastic forces , damping  forces and so on. Then, I compile the code with the Visual Studio 2019 . With the new openfast_x64_bendtwist.exe , I calculate the example: _5MW_Land_DLL_WTurb_ and the error occur. In this example, I just add a torsion DOF flag in the NRELOffshrBsline5MW_Onshore_ElastoDyn.dat.

**Problem:**

   Processed 1442 time steps of 20-Hz full-field data (72.05 seconds). Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows). Using legacy Bladed DLL interface.
 Time:0 of 60 seconds.
The BEM solution is being turned off due to low TSR. (TSR=0). This warning will not be repeated though the condition may persist.(See GeomPhi output channel.)

FAST Solution:CalcOutputs_And_SolveForInputs:SolveOption2:SolveOption2a_Inp2BD:ED_CalcContstateDe
riv:LAPACK_DGETRF:U(             11,               11)=0. Factor U is exactly singular. 
OpenFAST encountered an error during simulation initialization. simulation error level: FATAL ERROR
Aborting OpenFAST.

**Relevant information:**

---------------------- DEGREES OF FREEDOM --------------------------------------
True          FlapDOF1    - First flapwise blade mode DOF (flag)
True          FlapDOF2    - Second flapwise blade mode DOF (flag)
True          EdgeDOF     - First edgewise blade mode DOF (flag)
True          TorDOF      - First torsion blade mode DOF (flag)
False         TeetDOF     - Rotor-teeter DOF (flag) [unused for 3 blades]
True          DrTrDOF     - Drivetrain rotational-flexibility DOF (flag)
True          GenDOF      - Generator DOF (flag)
True          YawDOF      - Yaw DOF (flag)
True          TwFADOF1    - First fore-aft tower bending-mode DOF (flag)
True          TwFADOF2    - Second fore-aft tower bending-mode DOF (flag)
True          TwSSDOF1    - First side-to-side tower bending-mode DOF (flag)
True          TwSSDOF2    - Second side-to-side tower bending-mode DOF (flag)
False         PtfmSgDOF   - Platform horizontal surge translation DOF (flag)
False         PtfmSwDOF   - Platform horizontal sway translation DOF (flag)
False         PtfmHvDOF   - Platform vertical heave translation DOF (flag)
False         PtfmRDOF    - Platform roll tilt rotation DOF (flag)
False         PtfmPDOF    - Platform pitch tilt rotation DOF (flag)
False         PtfmYDOF    - Platform yaw rotation DOF (flag)

the modified NRELOffshrBsline5MW_Onshore_ElastoDyn.dat, openfast_x64_bendtwist.exe and  the error.png are in the zip.

**Question:**

I have no idea about this error.

What could be wrong with the system? How can I identify the main problem and solve it?

Any help would be appreciated.

Best regards
AsIlll223
[bend-twist-error.zip](https://github.com/OpenFAST/openfast/files/11156081/bend-twist-error.zip)

**Comment by jjonkman** [comment]
Dear @AsIlll223,

I'm not familiar with the changes you made to ElastoDyn to introduce a blade-torsion DOF, but this error implies that the mass matrix in ElastoDyn is now ill-conditioned (e.g., with a zero on the diagonal), such that system equations of motion ( F = m a ) cannot be solved for accelerations ( a = m^-1 F ).

FYI: Adding a blade-torsion DOF to ElastoDyn is likely quite involved, as recently discussed on our forum (see the March, 2023 posts in the following forum topic: https://forums.nrel.gov/t/coupled-blade-modes-in-fast/314).

Best regards

**Comment by jjonkman** [comment]
Dear @AsIlll223,

By "separately", do you mean you want to compile and run ElastoDyn standalone, uncoupled from other OpenFAST modules?  I don't believe a standalone driver code has been written for ElastoDyn (yet).

Best regards,

**Comment by AsIlll223** [comment]
Dear @jjonkman 

Yes,  I want to compile and run ElastoDyn standalone, uncoupled from other OpenFAST modules, maybe I can write a _main program.f90_ to use _ElastoDyn module_ ,but I try it and then find there are too many modules files to use, including NWTC and so on.And there are too many f90 files to compile, maybe there is a requirement for the order of these modules.f90 files. 
I'm not very familiar with compiling such multi-module Fortran programs, can you give me some advice？

Best regards

**Comment by deslaughter** [comment]
I would recommend creating your program inside of the OpenFAST repository and adding it as an executable in an existing CMakeLists.txt files. That way you can use `target_link_libraries(your_executable elastodynlib nwtclibs)` to link against ElastoDyn.
