### ISSUE TITLE
Issues when compiling OpenFast under Windwos with Visual Studio

### ISSUE THREAD

**Issue by stafqjcj** [OpenFAST/openfast#152]
Dear all,

I followed the instructions on openfast.readthedocs.io and use Visual Studo Community 2017 and Intel Parallel Studio XE 2018. When I build Fast, I get the followin errors. I am new to Fortran and did not use Visual Studio before... Can anyone point me in the right direction? 

`Severity	Code	Description	Project	File	Line	Suppression State
Error		error #6404: This name does not have a type, and must have an explicit type.   [ERRID_SEVERE]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	121	
Error		Compilation Aborted (code 1)		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	1	
Error		error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FAST_SUBS]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	39	
Error		error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [DBKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	44	
Error		error #6404: This name does not have a type, and must have an explicit type.   [DBKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	44	
Error		error #6592: This symbol must be a defined parameter, an enumerator, or an argument of an inquiry function that evaluates to a compile-time constant.   [DBKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	44	
Error		error #6683: A kind type parameter must be a compile-time constant.   [DBKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	44	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	45	
Error		error #6457: This derived type name has not been declared.   [FAST_TURBINETYPE]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	48	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	50	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	51	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	52	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	58	
Error		error #6404: This name does not have a type, and must have an explicit type.   [PROGNAME]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	64	
Error		error #6632: Keyword arguments are invalid without an explicit interface.   [FLAG]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	67	
Error		error #6404: This name does not have a type, and must have an explicit type.   [TURBINE]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	70	
Error		error #6363: The intrinsic data types of the arguments must be the same.   [MOD]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	117	
Error		error #6404: This name does not have a type, and must have an explicit type.   [NUM2LSTR]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	118	
Error		error #6362: The data types of the argument(s) are invalid.   [TRIM]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	118	
Error		error #6362: The data types of the argument(s) are invalid.   [TRIM]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	118	
Error		error #6404: This name does not have a type, and must have an explicit type.   [ABORTERRLEV]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	121	
Error		error #6363: The intrinsic data types of the arguments must be the same.   [MIN]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	122	
Error		error #6404: This name does not have a type, and must have an explicit type.   [NEWLINE]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	123	
Error		error #6054: A CHARACTER data type is required in this context.   [NEWLINE]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	123	
Error		error #6404: This name does not have a type, and must have an explicit type.   [ERRID_NONE]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	153	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	164	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	169	
Error		error #6054: A CHARACTER data type is required in this context.   [NEWLINE]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	173	
Error		error #6054: A CHARACTER data type is required in this context.   [NEWLINE]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	173	
Error		error #6837: The leftmost part-ref in a data-ref can not be a function reference.   [TURBINE]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	179	
Error		Error running FAST Registry for OpenFOAM.		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\modules-local\openfoam\src\OpenFOAM_Registry.txt	1	
Error		error PRJ0019: A tool returned an error code from "Running Registry for OpenFOAM"		Project		
Warning		warning #8586: Implicit type is given to allow out-of-order declaration. Non-standard extension.   [DBKI]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	44	
Warning		warning #6931: Fortran 2003 does not allow this assignment statement.   ['OpenFAST']		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	64	
Warning		warning #6187: Fortran 2003 requires an INTEGER data type in this context.   [N_TMAX_M1]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	111	
Error	MSB8020	The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	FAST_Registry	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets	57	
Error	MSB8020	The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	MAP_dll	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets	57	
`

**Comment by jjonkman** [comment]
Dear @stafqjcj 

Did you try closing the Visual Studio project, reopening it, and try compiling again?

Best regards,

**Comment by stafqjcj** [comment]
Dear Jason,
I´m new to Visual Studio and hit the "build FAST" instead of "build Solution" button.

However, after "soving" this, there are still 31 error left, of wich the first is
`error #6054: A CHARACTER data type is required in this context.   [NEWLINE]	`
I could solve this by replacing NEWLINE by NEW_LINE('A') but still there are many errors left, e.g.
`Severity	Code	Description	Project	File	Line	Suppression State
Error		error #6362: The data types of the argument(s) are invalid.   [TRIM]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	118	
` and
`Severity	Code	Description	Project	File	Line	Suppression State
Error		error #6363: The intrinsic data types of the arguments must be the same.   [MIN]		C:\Users\wiens\Documents\NREL_DesignCodes\OpenFastGitVS\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	122	
`

I assume that the source code should work without changes but how? Is there a setting in Visual Studio that I have to take care of or should I use an older Visual Studio?

**Comment by jjonkman** [comment]
It looks like your errors are coming from not having FASTlib compiled before FAST. 

You should `build Solution` instead of `build FAST` because the FAST project depends on other projects (like FASTlib) in the solution that need to be built first. If necessary, you could right click on the FASTlib project and select `build` so that FASTlib is built first. 

You should not have to change NEWLINE or any other code.

**Comment by stafqjcj** [comment]
Thanks for coming back to me. Indeed I made the mistake initially but also `buils solution` does not work. I installd older Versions (Visual Studio 2015 community and Intel Fotran Compiler 17.0 Update 1) with no succes.
Building FASTlib first throws the error `error PRJ0019: A tool returned an error code from "Running Registry for InflowWind"`

**Comment by ghaymanNREL** [comment]
Unfortunately I've seen this issue on various Windows boxes.  There is an issue when parsing the RunRegistry.bat file located in the vs-build folder of your repo.  You will need to locate the label :InflowWind and then try removing or adding lines to the file above that label.  You can also try moving the label and the following three lines, higher up in the script file.  Say, above the :ElastoDyn label.  

This would be the group of lines to possibly relocate:

:InflowWind
SET CURR_LOC=%IfW_Loc%
%REGISTRY% "%CURR_LOC%\%ModuleName%.txt" -I "%NWTC_Lib_Loc%" -I "%CURR_LOC%" -O "%Output_Loc%"
GOTO checkError

This issue is not repeatable across boxes, so I'm not sure what the ultimate solution is to this issue.

**Comment by bjonkman** [comment]
@ghaymanNREL: does this have anything to do with line endings? I've seen it where someone checked out the repository on a Mac and then tried to run it on a Windows virtual machine (with the Mac line endings). It complained about missing labels until we converted the line endings to Windows format.

**Comment by evenlund** [comment]
I get similar, but more error messages (167) when trying to compile in VS2015 with trial versions of Intel Fortran (2017.1 and 2017.latest) on a Windows 10 computer. I have followed the docs in detail and also tried ghaymanNRELs advice with no change.

**Comment by bjonkman** [comment]
@evenlund, I think that the problem @stafqjcj reported was resolved by making sure the RunRegistry.bat file contained Windows line endings. (There were some other associated emails regarding the problem.) Run `unix2dos` on the file or save it with DOS line endings using a text editor and try to build again.

**Comment by jjonkman** [comment]
Fixed by #194.

**Comment by abhinaygoga** [comment]
When tried to recompile BeamDyn standalone driver with Visual studio I am also facing the similar error (PRJ0019). The error follwos as this 
''Error Error running FAST Registry for BeamDyn. T:\Software archive\BeamDyn-master\source\Registry_BeamDyn.txt 1
Error error PRJ0019: A tool returned an error code from "Running Registry for BeamDyn" Project'' 
Similar to the comment of Hayman, I tried relocating the label :BeamDyn without any success.  
Both the registry.bat and .txt files are with windows line endings. 
Outside the old NWTC library, is there any source for BeamDyn standalone binaries either direct or for compilation?
Thanks

**Comment by andrew-platt** [comment]
@abhinaygoga, which version of the code are you compiling?

**Comment by abhinaygoga** [comment]
@andrew-platt I took the code from (https://github.com/old-NWTC/BeamDyn). Because I couldn't find any new source codes for standalone beamdyn driver

**Comment by Chris195513** [comment]
can someone explain to me how to fix this?  I get the same errors with visual studio 2019 and 2022
![image](https://user-images.githubusercontent.com/127173452/223633168-ab63b559-860d-40ad-8be7-e2d8381fcd4d.png)

**Comment by jjonkman** [comment]
Dear @Chris195513,

It looks like you've posted your same question twice.  This issue is already closed.  Let's continue the discussion in the other issue you recently opened: https://github.com/OpenFAST/openfast/issues/1481.

Best regards,
