### ISSUE TITLE
ElastoDyn problem - FAST_InitializeAll ED_Init ED_AllocOutput MeshCommit

### ISSUE THREAD

**Issue by ILDENIEL** [OpenFAST/openfast#1524]
Hi everyone, I'm trying to study the aerodynamic performances of a turbine, so I prepared a FST file, an AeroDyn file and of course an ELastoDyn file.
The error encountered after the launch is the following:

Running ElastoDyn.
Nodal outputs section of ElastoDyn input file not found or improperly formatted.

FAST_InitializeAll:ED_Init:ED_AllocOutput:MeshCommit: Line2 element 21 has 0 length.
   n2 = n(1) = (0,0,1.24998E-04)
   n1 = n(22) = (0,0,0)

 OpenFAST encountered an error during module initialization.

I don't understand what is the problem. 
I specify that this is a small 3 bladed Horizontal Axis Wind Turbine, each blade has been split up into 20 blade elements, and since I'm currently not interested in the structural analysis, I prepared the ElastoDyn file only because it is necessary for OpenFAST to be executed.

How can I solve this issue?

**Comment by jjonkman** [comment]
Dear @ILDENIEL,

How small of a wind turbine are you simulating?  From the error message, I would guess your blade or tower discretization results in element lengths that are below an internally defined threshold.  A similar issue was recently in the following OpenFAST discussion: https://github.com/OpenFAST/openfast/discussions/1499.

You say that, you: 
> prepared the ElastoDyn file only because it is necessary for OpenFAST to be executed.

This implies to me that you do not want to consider aero-elasticity and a rigid wind turbine representation would suffice.  Is that correct?  If so, you could likely get by running your simulations with the standalone AeroDyn driver than within OpenFAST.

Best regards,

**Comment by ILDENIEL** [comment]
Dear @jjonkman,
the turbine I'm trying to characterize is very small (blade length lower than 1.5 m), but during the preparation of RNodes and DRNodes I double checked the consistency of the data and everything seems ok.
The smaller element is 0.00025 m (the first one), may it cause the problem?

At this very moment, I would like to characterize the aerodynamics, but later on, I'm also interested in the platform movement and other different features, and for this reason I'm also interested in ElastoDyn and, in general, in OpenFAST.
However, I was not aware of the standalone AeroDyn driver, which I would try to find and use.

Do you have any suggestions for the preparation of AeroDyn and ElastoDyn? Which is the minimum DRNodes value?
Where can I find the ElastoDyn manual?

Thanks in advance
Best regards

**Comment by jjonkman** [comment]
Dear @jjonkman,

Yes, that is likely the problem.  The specific error you are receiving is checking the element length against `PARAMETER  MIN_LINE2_ELEMENT_LENGTH = sqrt(epsilon(1.0_ReKi))`, the size of which depends on the precision.  In single precision, this is about 0.0003 m.  I would not think there is a need for an element smaller than this for a 1.5-m long blade.

For standalone driver AeroDyn documentation, see: https://openfast.readthedocs.io/en/main/source/user/aerodyn/driver.html.  For ElastoDyn documentation, see: https://openfast.readthedocs.io/en/main/source/user/elastodyn/index.html.

Best regards,

**Comment by ILDENIEL** [comment]
Dear @jjonkman,
thanks a lot for these informations, I will try to use fewer nodes.
Where can I find the unofficial FAST theory manual (including ElastoDyn and Hydrodyn)?
Is there a way to run the standalone AeroDyn with the command prompt, the same way as OpenFAST?

Best regards

**Comment by jjonkman** [comment]
Dear @ILDENIEL,

For the theory basis of ElastoDyn, see: https://openfast.readthedocs.io/en/main/source/user/elastodyn/index.html.

For the theory basis of HydroDyn, see: https://openfast.readthedocs.io/en/main/source/user/hydrodyn/index.html.

Yes, the standalone driver for AeroDyn, once compiled, can be used to run AeroDyn via the command prompt, uncoupled from OpenFAST.

Best regards,

**Comment by ILDENIEL** [comment]
Dear @jjonkman,
thanks a lot for your support. I also confirm that after removing the blade element 0.00025m long OpenFAST terminated normally, so thanks to your advise it has been possible to solve the issue.

Best regards
