### ISSUE TITLE
How do I add a new variable to avrSWAP?

### ISSUE THREAD

**Issue by SYZ622** [OpenFAST/openfast#1525]
![image](https://user-images.githubusercontent.com/113154375/231931481-9ce01234-7896-4e84-8bfc-90de42d7ed7a.png)
![image](https://user-images.githubusercontent.com/113154375/231931605-184d8ab7-6172-4db4-9287-3d7f9fdc6976.png)
If I want to add a new variable to avrSWAP, I'm not sure where I should put the new variable in the two images. After adding the new variable is there anything else in the BladedInterface.F90 file that needs to be changed? Thank you very much for your answer!

**Comment by jjonkman** [comment]
Dear @SYZ622,

Can you clarify what variable you want to add to the avrSWAP array?  Will the variable be passed from the DISCON controller to SerovDyn/OpenFAST or will the variable pass from ServoDyn/OpenFAST to the DISCON controller?

Best regards,

**Comment by SYZ622** [comment]
@jjonkman Thanks for your reply. I want this variable to be passed from OpenFAST to DISCON controller.
Best regards！

**Comment by jjonkman** [comment]
Dear @SYZ622,

Can you clarify what variable you want passed from OpenFAST to the DISCON controller?  Does ServoDyn already have access to the variable?

Best regards,

**Comment by SYZ622** [comment]
@jjonkman Thanks for your reply, the variable I want to pass is x%QDT(DOF_P) and I want to call it the speed of the platform movement. I don't think ServoDyn has this variable directly.
Best regards！

**Comment by SYZ622** [comment]
@andrew-platt Thank you for your reply, can you please tell me where this summary file is, I can't seem to find it.

**Comment by andrew-platt** [comment]
You will need to generate the summary file when OpenFAST is run with a controller.  To do this, set `SumPrint` on line 101 of the ServoDyn input file to true, then run an OpenFAST simulation with a controller.  This will produce an output file with the extension `SrvD.sum`.   At the end of this file you should find information about the channels used with the Bladed controller interface.

**Comment by SYZ622** [comment]
@andrew-platt Thank you so much! I've managed to find it, I'd ignored the file until then, thanks again.
Best regards！
