### ISSUE TITLE
Does the computer compilation environment have an impact on external controllers?

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#1539]
Hello everyone,
I encountered the following error message, but: I am sure the path to the DLL is correct; And the DLL can run normally on my computer using OpenFAST-v3.4.0 (which proves that it is indeed 64bit). Once it is copied to a high-performance server next to me, an error will be reported. I am considering whether the reason for the error is that the high-performance server lacks some compilation environment required for the program to run normally.

`
FAST_InitializeAll:SrvD_Init:BladedInterface_Init:The dynamic library .\..\CE1.5MW\ServoData\20230420_fore.dll could not be loaded. Check that the file exists in the specified location and that it is compiled for 64-bit applications.
`

**Comment by shipors** [comment]
Dear @jjonkman ,

That server is indeed running on a Windows system.

I have encountered this situation before, but at that time, I only recompiled the external controller and the error message disappeared. But this solution doesn't work this time (even though I started using the previously compiled controller).

This issue is not fatal because I am running programs on three servers at the same time, and all other servers are functioning normally. (I have enabled parallel computing and this high-performance server can run 160 threads simultaneously, while other servers only have a maximum of 48 threads)

Anyway, thank you for your help.

Best wishes!

**Comment by jjonkman** [comment]
I'm not sure.  Perhaps someone else can comment.

**Comment by deslaughter** [comment]
@shipors , when this has happened to me in the past, it has been due to missing shared libraries on which your DLL depends. Is Visual Studio installed on the server where the DLL doesn't run? I'm guessing that you compiled it using the Intel oneAPI, sometimes the executables and DLLs built with it will link to shared libraries that aren't on all computers. On the computer where you built the DLL, you can run the following command to show all dependencies and then check that they exist on the server (`dumpbin` is part of VS):

`dumpbin /dependents 20230420_fore.dll`

**Comment by shipors** [comment]
Dear @Slaughter,


Thank you for your reply.&nbsp;


I used Visual Studio to generate the DLL on my computer. Then used its copy to run on a high-performance server. Visual studio is not installed on the high- performance server.


As for the solution you mentioned, I will also try it. (I have been busy with other things these two days)&nbsp;


Best Wishes!










邵茂峰
***@***.***


---Original---
From: "Derek ***@***.***&gt;
Date: Sat, Apr 22, 2023 01:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OpenFAST/openfast] Does the computer compilation environmenthave an impact on external controllers? (Issue #1539)




 
@shipors , when this has happened to me in the past, it has been due to missing shared libraries on which your DLL depends. Is Visual Studio installed on the server where the DLL doesn't run? I'm guessing that you compiled it using the Intel oneAPI, sometimes the executables and DLLs built with it will link to shared libraries that aren't on all computers. On the computer where you built the DLL, you can run the following command to show all dependencies and then check that they exist on the server (dumpbin is part of VS):
 
dumpbin /dependents 20230420_fore.dll

**Comment by shipors** [comment]
Dear @deslaughter , @jjonkman 

Thank you for your help. I already know how to solve this problem. As mentioned in @deslaughter , I checked the shared libraries that the DLL relies on and found that these files do not exist on high-performance servers. I downloaded VISUAL STUDIO on the server, and after completing the installation, my DLL can be used normally.

Best Wishes!
