### ISSUE TITLE
compile problem on Ubuntu

### ISSUE THREAD

**Issue by smilke** [OpenFAST/openfast#154]
ex share:
I have installed ubuntu 18 on vmware, and then I try to compile openfast on ubuntu, but when the compilation went to 96%, the gfortran compiler broken,the error message like blow:
` [ 96%]  Building Fortran object modules-local/openfastlibrary/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o`

### `f951: out of memory allocating 65536 bytes after a total of 491261952 bytes gfortran-6: internal compiler error: Killed (program f951)`
`Please submit a full bug report,with preprocessed source if appropriate.`
`See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.`
`modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/build.make:110: recipe for target 'modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o' failed`
`make[2]: *** [modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o] Error 4`
`CMakeFiles/Makefile2:1410: recipe for target 'modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/all' failed`
`make[1]: *** [modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed`
`make: *** [all] Error 2`

so is there somebody had the same quesition with me? and how you resovle it?

**Comment by rafmudaf** [comment]
@smilke could you try compiling with gcc 7? I've compiled on a virtual machine running Ubuntu 14.04 with 2GB of memory without problem. And it looks like gcc 7 is directly available in `apt` on Ubuntu Bionic (18).

**Comment by rafmudaf** [comment]
Ok great to hear that it worked. It sounds like earlier versions of gfortran don't work well `CMAKE_Fortran_COMPILER_VERSION` so that is the issue to fix here.

**Comment by rafmudaf** [comment]
closed by #173
