### ISSUE TITLE
How to modify blade mass in BeamDyn_blade

### ISSUE THREAD

**Issue by Wangzhenyu12** [OpenFAST/openfast#1547]
Hello,everyone.

I want to use OpenFast to simulate the condition of blade mass imbalance. Previously, I set CompElast=1 which means the BeamDyn for blades is ignored. And I modified AdjBlMs in NRELOffshrBsline5MW_Blade.dat to achieve the goal of changing the mass of one blade. Now, I wanna set CompElast=2 which considers the BeamDyn module. But I can not find any parameter like AdjBlMs. 

So my question is how to modify blade mass in BeamDyn module? I know DISTRIBUTED PROPERTIES contain stiffness matrices and mass  matrices of blades. Does it mean I need to modify all the mass density elements in mass matrices?

Thank you all !

**Comment by jjonkman** [comment]
Dear @hangzhouwangyuan,

Yes, BeamDyn does not currently support simple mass scaling, so, you must modify the sectional mass matrices directly.  You can use separate BeamDyn input files for each blade.

Best regards,

**Comment by hangzhouwangyuan** [comment]
Dear  @jjonkman 
Thanks for your quick reply.
