### ISSUE TITLE
Openfast fail to run after changing  the bts file in InflowWind ( FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SolveOption2c_Inp2AD_SrvD:InflowWind_Ca lcOutput:CalcOutput:IfW_FFWind_CalcOutput [position=(0, 0, 15)  in wind-file coordinates]: FF wind array boundaries violated. Grid too small in Z direction (height (Z=15 m) is below the grid and no tower points are defined).)

### ISSUE THREAD

**Issue by HassanYousef12** [OpenFAST/openfast#1552]
Hello!
This my first time requesting help in github so i hope I am asking for the help in the right place.
I used turbSim to regenerate (IEA15MW_IEC_ETM_U50.0_Seed60362647.bts) file available in IEA-15-240-RWT-1.1.3\OpenFAST\IEA-15-240-RWT\Wind. when I tried to run openfast using that, and I got this Fatal error. can you please help me fixing it? 

**************************************************************************************************
OpenFAST

Copyright (C) 2022 National Renewable Energy Laboratory
Copyright (C) 2022 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v3.3.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 1900
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: Nov 02 2022
 - Time: 14:07:06
Execution Info:
 - Date: 04/29/2023
 - Time: 11:49:41+0200

OpenFAST input file heading:
    IEA 15 MW offshore reference model on UMaine VolturnUS-S semi-submersible floating platform

Running ElastoDyn.
Running AeroDyn.
Warning: Turning off Unsteady Aerodynamics because UA parameters are not included in airfoil
(airfoil has likely has constant polars). (node 1, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 5, blade 1)
Warning: Turning off Unsteady Aerodynamics because UA parameters are not included in airfoil
(airfoil has likely has constant polars). (node 1, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 5, blade 2)
Warning: Turning off Unsteady Aerodynamics because UA parameters are not included in airfoil
(airfoil has likely has constant polars). (node 1, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 5, blade 3)
Running InflowWind.

   Reading a 21x21 grid (252 m wide, 24 m to 276 m above ground) with a characteristic wind speed
   of 50 m/s. This full-field file was generated by TurbSim (from OpenFAST-v3.3.0) on 27-Apr-2023
   at 15:12:49.

   Processed 14400 time steps of 20-Hz full-field data (period of 720 seconds).
Running HydroDyn.
  WARNING:  The requested output channel is invalid: -
  WARNING:  The requested output channel is invalid: Wave
  WARNING:  The requested output channel is invalid: elevation
  WARNING:  The requested output channel is invalid: at
  WARNING:  The requested output channel is invalid: the
  WARNING:  The requested output channel is invalid: platform
  WARNING:  The requested output channel is invalid: reference
  WARNING:  The requested output channel is invalid: point
  WARNING:  The requested output channel is invalid: (
  WARNING:  The requested output channel is invalid: 0
  WARNING:  The requested output channel is invalid: 0)
 Generating incident wave kinematics and current time history.
 Calculating second order difference frequency wave kinematics.
 Calculating second order sum frequency wave kinematics.
 Reading in WAMIT output with root name ".\HydroData/IEA-15-240-RWT-UMaineSemi".
 Computing radiation impulse response functions and wave diffraction forces.
 Calculating second order difference-frequency force using the full quadratic transfer function.
Running MoorDyn (v2.a27, 2022-07-20).
   This is an alpha version of MoorDyn-F v2, with significant input file changes from v1.
   Copyright: (C) 2021 National Renewable Energy Laboratory, (C) 2019 Matt Hall
   Parsing MoorDyn input file: .\IEA-15-240-RWT-UMaineSemi_MoorDyn.dat
   Created mooring system:  3 lines, 6 points, 0 rods, 0 bodies.
   Finalizing initial conditions using dynamic relaxation.
   t=60  FairTen 1: 2.43287E+06, 2.44526E+06, 2.43537E+06
   Fairlead tensions did not converge within TMaxIC=60 seconds.
   MoorDyn initialization completed.
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows).
Using legacy Bladed DLL interface.

FAST_InitializeAll:HydroDyn_Init:HydroDynInput_ProcessInitData: A requested output channel is
invalid

 Time: 0 of 720 seconds.
The BEM solution is being turned off due to low TSR.  (TSR = 1.9409). This warning will not be

------------------------------------------------------------------------------
Running ROSCO-v2.6.0
A wind turbine controller framework for public use in the scientific field
Developed in collaboration: National Renewable Energy Laboratory
                            Delft University of Technology, The Netherlands
------------------------------------------------------------------------------
Generator speed:    7.6 RPM, Pitch angle:   1.0 deg, Power:     0.0 kW, Est. wind Speed:  45.3 m/s

FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SolveOption2c_Inp2AD_SrvD:InflowWind_Ca
lcOutput:CalcOutput:IfW_FFWind_CalcOutput [position=(0, 0, 15)  in wind-file coordinates]: FF
wind array boundaries violated. Grid too small in Z direction (height (Z=15 m) is below the grid
and no tower points are defined).

 OpenFAST encountered an error during simulation initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.

**Comment by jjonkman** [comment]
Dear @HassanYousef12,

Similar questions have been asked many times on our forum: https://forums.nrel.gov/. All aerodynamic analysis nodes within the AeroDyn aerodynamics module of OpenFAST (including the tower points) must reside within the wind domain for the full length of the simulation, including taking into account floating platform motion and turbine deflection.

Best regards,
