### ISSUE TITLE
download MCR 7.16 for Mlife

### ISSUE THREAD

**Issue by 1Naruto1** [OpenFAST/openfast#1571]
Dear developer, 

I want to use the tool called 'MLife', but it is necessary to have MCR with version 7.16 for running without matlab. How can I get the MCR with version 7.16, because I did not find it on the matlab website.

Best Regards,

**Comment by jjonkman** [comment]
Dear @1Naruto1,

You can find the MCRInstaller that we previously supplied with the old archives of MCrunch, MLife, and MExtremes on my Google drive: https://drive.google.com/file/d/1PFvU27PxAsJ_IsgxWUHo1elCkfvNUwTq/view?usp=share_link.  I would also suggest reviewing the following topics on our forum:
https://forums.nrel.gov/t/mcrunch-compiled-version/2401
https://forums.nrel.gov/t/mcr-7-16-for-64bit-windows/2595

Best regards,

**Comment by 1Naruto1** [comment]
Dear @jjonkman,

Thanks for your kindness. :)
