### ISSUE TITLE
How OpenFast couples with satr ccm+

### ISSUE THREAD

**Issue by calcin** [OpenFAST/openfast#1582]
Dear all,

The module for calculating aerodynamics in openfast is AeroDyn15 module, I would like to ask if openfast can be coupled with other commercial software (e.g. star ccm+) to do aeroelastic analysis of blades, I would like to use star ccm+ to replace AeroDyn15 module to calculate aerodynamics to achieve higher calculation accuracy. If the two can be coupled together, where should I look for such information to help me to finish coupling openfast and star ccm+?
Any help would be appreciated,

Best regards,

**Comment by jjonkman** [comment]
Dear @calcin,

OpenFAST has been coupled with CFD for aero-elastic analysis where the aerodynamics are calculated in CFD.  An actuator-line  coupling exists to OpenFOAM in SOWFA (https://github.com/NREL/SOWFA) and to AMR-Wind in ExaWind (https://github.com/Exawind/amr-wind).  A blade-resolved coupling exists to Nalu-Wind in ExaWind (https://github.com/Exawind/nalu-wind).  ExaWind is under more active development than SOWFA.  But I'm not aware that coupling between OpenFAST and StarCCM has been developed.

Best regards,

**Comment by calcin** [comment]
Dear @jjonkman,

First of all, thank you for your previous answer.
I know SOWFA before, SOWFA is a good open source project for solving wake flow, but the aerodynamic calculation on wind turbine blade is not better than BEM method in AeroDyn15, I don't know about ExaWind, thank you for giving me such an idea, I don't have to use satr ccm+ for my work now. My purpose is to use CFD method to accurately calculate the blade aerodynamics, it does not matter what kind of CFD software is used, so my question is ExaWind this project is the use of CFD method to calculate the blade aerodynamics of high fidelity? Another question is, is this project only for a specific wind turbine model? Or can the CAD model be used to generate a mesh to calculate any model of wind turbine? The last question is, is this project mature enough to perform a valid aeroelastic analysis?

Best regards,

**Comment by calcin** [comment]
Dear @jjonkman,

First of all, thank you for your previous answer.
I know SOWFA before, SOWFA is a good open source project for solving wake flow, but the aerodynamic calculation on wind turbine blade is not better than BEM method in AeroDyn15, I don't know about ExaWind, thank you for giving me such an idea, I don't have to use satr ccm+ for my work now. My purpose is to use CFD method to accurately calculate the blade aerodynamics, it does not matter what kind of CFD software is used, so my question is ExaWind this project is the use of CFD method to calculate the blade aerodynamics of high fidelity? Another question is, is this project only for a specific wind turbine model? Or can the CAD model be used to generate a mesh to calculate any model of wind turbine? The last question is, is this project mature enough to perform a valid aeroelastic analysis?

Best regards,

**Comment by jjonkman** [comment]
Dear @calcin,

AMR-Wind and SOWFA are similar as they are both actuator-line methods.  Nalu-Wind is higher fidelity because it is surface resolved.  I'm not familiar with the mesh generation methods of Nalu-Wind as I have not used it myself.

Best regards,

**Comment by calcin** [comment]
Dear @jjonkman,

Okay, thank you for your answer and have a nice life!

Best regards,

**Comment by wangfanl** [comment]
> 亲爱的，
> Hello, I would like to ask whether the moordyn of openfast can be coupled with its star ccm + to realize mooring. Is there any information about this?
> 此致敬意

**Comment by luwang00** [comment]
@wangfanl 

We don't have anything readily available on this, but I think it might be easier to couple with the C-version of MoorDyn available here: https://github.com/FloatingArrayDesign/MoorDyn instead of the Fortran version used in OpenFAST. There's also some on going discussion in that repository from people actively working on coupling MoorDyn to other codes that might be helpful.
