### ISSUE TITLE
Feature request--Coupling OpenFAST with AMR-Wind or nalu-wind for floating wind turbine.

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1588]
Dear all,

I am wondering that whether can we couple the OpenFAST with the AMR-Wind or nalu-wind to calculate the performance of the FOWT, namely considering the platform motion.

Thanks for your attention!

**Comment by jjonkman** [comment]
Dear @ZL6462,

I would think these questions would be better asked on the AMR-Wind and Nalu-Wind issues pages: https://github.com/Exawind, but I'll just say that OpenFAST has been coupled to both, as long as the floating platform, hydrodynamics, and moorings are modeled within OpenFAST.  Capability for full two-phase flow (air, water in CFD) coupled to OpenFAST is under development.

Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman 

Thank you for you reply.

Best regards,
