### ISSUE TITLE
Possible small bug with TwrPotent and TwrShadow

### ISSUE THREAD

**Issue by pelljam** [OpenFAST/openfast#1595]
When `TwrPotent == TwrPotent_Bak` the local var `xbar` is modified:

`xbar = xbar + 0.1`

As far as I can tell, that modified value is then later used in the `TwrShadow` calculation. I think this is probably a small bug, i.e. the choice of `TwrPotent` should not have an influence on the `TwrShadow` calculation?

Hope that helps, 

James Pell

**Comment by jjonkman** [comment]
Dear @pelljam,

Thanks for letting us know about this issue.  I agree that it looks incorrect as implemented.  While it may be rare to have both the tower influence and tower shadow enabled at the same time, I agree that this should be fixed.

Best regards,

**Comment by pelljam** [comment]
Thank you for the clarification @jjonkman

I agree: one is really for upwind and the other for downwind. Which makes it a very small issue indeed!

**Comment by jjonkman** [comment]
I'm reopening this issue because while it may be rare, it should still be fixed.

**Comment by pelljam** [comment]
OK, sorry, I was unfamiliar with the process here. I'd assume because it was assigned, the issue was closed as far as I was concerned. I'll not do that with future issues.

**Comment by ebranlard** [comment]
Fixed in #1677 (rc-3.5.1)
