### ISSUE TITLE
The wake experiment of 5MW wind turbine

### ISSUE THREAD

**Issue by robytian** [OpenFAST/openfast#1599]
Dear all

I would like to ask whether NREL or other cooperative institutions have conducted wake experiments related to 5MW wind turbines, such as wind tunnel tests of wind turbines with reduced sizes. Do you have experimental data and papers for reference? I want to test my wake model. thank you.

BR,

Roby

**Comment by robytian** [comment]
Hi @jjonkman @ebranlard 

May I ask whether the openfast file of OLAF model in this [article](https://wes.copernicus.org/preprints/wes-2023-21/) can be provided?And where can the wind tunnel data be found?
Thank you.

BR,

Roby

**Comment by ebranlard** [comment]
@RBergua ran the simulations for this case, he might be able to provide some examples of OLAF input files. You can probably contact the main author of the article regarding the wind tunnel data.

**Comment by RBergua** [comment]
Hi @robytian

The hot-wire and PIV measurements are available here: https://zenodo.org/record/4740006

Attached below you will also find the input file for OLAF that we used for the steady wind condition.
[OLAF_240rpm_LC11.txt](https://github.com/OpenFAST/openfast/files/11668410/OLAF_240rpm_LC11.txt)

Roger

**Comment by robytian** [comment]
Dear Roger and Ebranlard

Thank you very much.

BR,

Roby

**Comment by Junruzhang627** [comment]
Hi~@RBergua, 

Thank you much for your reply. 

I want to test the inflence of different regularization factors as recommanded on the website of openfast docs when number of NW panels is set as 1800. However too much time will spend on the simulations. 

Have you ever tested the different regularization factors under the large number of panels (1800 in your case)? 

Will these different regularization factors greatly influence the convergence, or the results on AEP or Cp, or the result aero force or torque load when the mesh is enough good?

**Comment by robytian** [comment]
Hi @Junruzhang627 

I have tested some cases, and the difference in the number of free or freezing panels greatly affects the results. However, the larger the turbulent vortex viscosity value  , the smoother the wake, and the size of the initial vortex core radius does not have much influence on the results.

If you are interested in this, we can have an in-depth discussion. Besides, are you Chinese? You can contact me at robytian@hrbeu.edu.cn.

**Comment by Junruzhang627** [comment]
Hi @robytian 

Thank you for offering help. I have sent you my questions through email. 

Thanks again.
