### ISSUE TITLE
Issue with VTK output file naming convention

### ISSUE THREAD

**Issue by mchurchf** [OpenFAST/openfast#16]
When you turn on the VTK output, the file naming convention is something like:
Model.AD_Blade1.t0.vtp
Model.AD_Blade1.t1.vtp
...
Model.AD_Blade1.tN.vtp

In order for Paraview to read in and animate the entire time series, the "t" should not be there.  Instead, the filename should look like:
Model.AD_Blade1.0.vtp
Model.AD_Blade1.1.vtp
...
Model.AD_Blade1.N.vtp

**Comment by sayerhs** [comment]
@mchurchf Please see if #17 does what you are looking for. If you and @michaelasprague agree, I'll merge and update `master` and `dev`

**Comment by jjonkman** [comment]
I'm not an expert in ParaView, but I've not seen any problems having the "t" when trying to animate as the *.t#.vtk files get sorted properly.  If this really is a problem, we'll not only have to change the visualization output from FAST, but we've used the same numbering convention for the ambient wind input to FAST.Farm (from ABLSolver) and the disturbed wind visualization output from FAST.Farm, which should be changed as well.

**Comment by gruchalla** [comment]
There are many ways to use ParaView. I think both xxx.t0.vtp and xxx.0.vtp will work in many instances. Although, xxx.0.vtp is a bit more standard and likely to be recognized by a wider range of use cases. 

Also, it is generally a good idea to pad your time steps with 0 to facilitate sorting, e.g., xxx.0000.vtp ... xxx.9999.vtp  vs  xxx.0.vtp ... xxx.9999.vtp

**Comment by ghaymanNREL** [comment]
I'm inclined to only make a change if someone can present a concrete use-case where the current naming convention is causing an issue.

**Comment by mchurchf** [comment]
Yes, my Paraview 5.3.0-RC2 on my Mac won’t open it with the t in the name.

**Comment by mchurchf** [comment]
Yes, I'm running Paraview 5.3.0-RC2 on the Mac, and it won't open the files with the "t" in the name.

**Comment by michaelasprague** [comment]
@ghaymanNREL -- can we make this change along with @gruchalla 's suggestion of padding with zeros, "e.g., xxx.0000.vtp ... xxx.9999.vtp vs xxx.0.vtp ... xxx.9999.vtp"

**Comment by rafmudaf** [comment]
@mschmidt271 and @rafmudaf are currently working on this.

**Comment by rafmudaf** [comment]
Fixed by pull request #126
