### ISSUE TITLE
Possible bug in determining turbine type

### ISSUE THREAD

**Issue by luwang00** [OpenFAST/openfast#1604]
**Bug description**
The section below on determining the type of the turbine looks incorrect. It might be caused by problems with merging. 
* The branches for MHK are duplicated. 
* The use of SubDyn no longer indicates fixed turbines because SubDyn can now be used to model floating substructures. 

https://github.com/OpenFAST/openfast/blob/7e8be526755823fd65c45f9012406e5e24df513b/modules/openfast-library/src/FAST_Subs.f90#L1869-L1890

**OpenFAST Version**
This code section is from the `dev` branch to be released as v4.0.0.

**Additional context**
It is not clear whether this issue has any impact on the results.

**Comment by luwang00** [comment]
Hi @hkross and @bjonkman, please take a look at this if you have time. Thanks!

**Comment by hkross** [comment]
Hi @luwang00, I am not sure why the MHK calls are repeated. Those should only need to be in there once. I think having them at the beginning would work. If MHK=1, it is a fixed MHK turbine, else if MHK=2, it is a floating MHK turbine, else it is a wind turbine. I'm not sure about determining the offshore wind turbine type and will let others comment on that.

**Comment by andrew-platt** [comment]
Completed in 4.0.0 (#2586)
