### ISSUE TITLE
How OpenFast does parallel computing

### ISSUE THREAD

**Issue by calcin** [OpenFAST/openfast#1607]
Dear all,

I recently used the beamdyn module in OpenFast to solve structural deformations, but his calculation speed is very slow, and the CPU usage is not high, I would like to ask if OpenFast can use parallel computing, or what methods can speed up his calculations.
Any help would be appreciated,

Best regards,

**Comment by calcin** [comment]
Dear @jjonkman 

Thank you for your reply, I have a new question I want to ask you, how the blades of openfast are modified to a sweep shape, is it to modify the source code? Or do you just need to modify some .dat files of an existing study? Thanks for the answer.

Best regards,

**Comment by ebranlard** [comment]
Sweep is introduced using the column `BlSwpAC` in the AeroDyn blade input file with the convention given in the figure below. 

![AeroDynCoord2](https://github.com/OpenFAST/openfast/assets/1318316/90f50d9b-93bf-44ca-9494-0028bcece2e0)


Note: if possible, use different issues for different questions.

**Comment by calcin** [comment]
Dear @ebranlard ,

Thank you for your answer, I will definitely correct the precautions you mentioned above next time, and I have another question about your answer this time, that is, when I modify the AeroDyn_bladed.dat file, do I need to modify some parameters in the input file corresponding to the BeamDyn module to correspond to the data size in the AeroDyn_bladed.dat, because I want to use these two modules to couple the solution.

Best regards,

**Comment by ebranlard** [comment]
Hi @calcin, 
Yes you are correct, if you are using BeamDyn, you need to adapt the BeamDyn input files as well. The simplest method is to introduce the sweep in the keypoints of the BeamDyn input file. 
I hope that helps.

**Comment by ebranlard** [comment]
This is indeed the place in the BeamDyn input file where you can modify the meanline of the beam (presweep, prebend). ElastoDyn does not have prebend and presweep implemented. In both cases (ElatoDyn and BeamDyn), you need to modify the AeroDyn file.

**Comment by calcin** [comment]
Dear @ebranlard 
Ok, thanks for the answer and happy work
