### ISSUE TITLE
error in generated power at wind rated speed

### ISSUE THREAD

**Issue by phildsouza** [OpenFAST/openfast#1634]
**error in rated power vs the rated speed**
<I was trying to simulate wind only condition for 5mw wind turbine with OC4 semi-submersible configuration. what I have come across is at the rated wind speed of 11.4m/s the pitch angle is 0 but the rotor speed is 11.93rpm which is below the rated rotor speed. Also, the power generated at 11.4m/s is only 4.6MW. But as I increase the inflow speed above rated wind speed (consider between 14-25m/s) the rotor speed is then constant but there is difference in the pitch angle compared with NREL 5MW wind turbine definition document(Definition of a 5-MW Reference Wind Turbine for Offshore System Development). The error is around 1deg but the power generated by the wind turbine is 5MW.
Also, when I increase the wind speed above the cut-off speed the turbine still generated power. eg. at 26m/s the results show the power generated is 5mw but then when increase to 27m/s it gives a error saying the turbine blade has collided with the tower.

1. switches and flags which i used in .fst file are below
![image](https://github.com/OpenFAST/openfast/assets/123314026/b53c9c1d-92f2-4d40-9bc9-82b5cce62ecb)
2. Screenshot of inflow file
![image](https://github.com/OpenFAST/openfast/assets/123314026/71a3d77f-1138-4d69-aa12-291e9fe968bd)
3. Wavemode is 0 in hydrodyn. but I am simulating the results for 60mtr water depth. for which I have modified the mooring length to 560mtrs and have altered the damping and stiffness matrix as below to meet the required natural period and damping ratio
![image](https://github.com/OpenFAST/openfast/assets/123314026/b3f314ff-334b-412a-8bbe-79846bc8d18d)

**OpenFAST Version**
<OpenFAST-v3.4.1>

**Comment by jjonkman** [comment]
Dear @phildsouza,

It looks like you were able to find the answers to most of your questions.

Regarding operating above the cut-out wind speed, the baseline controller for the NREL 5-MW wind turbine does not automatically shut down and park/idle the rotor for wind speeds above the cut-out wind speed.  The baseline controller only functions in normal operational mode.  You'll have to update the controller or use different OpenFAST settings to simulate the shutdown event or parked/idling condition.

I'm not aware of an updated document showing the response of the baseline NREL 5-MW steady-state response with the newest version of OpenFAST.

Best regards,

**Comment by phildsouza** [comment]
Dear Dr. @jjonkman 

Thank you for the above response it was really helpful. I have another issue with calculating heave natural frequency.

I was trying to analyze natural frequency of OC4 semi-submersible with 5MW wind turbine. the water depth I am simulating is 60mtrs. The damping and stiffness matrix is in Hydrodyn is all 0 and wave mode is set 0, elastodyn has all flags to false with only heave flag being true and initial heave displacement is 6, .fst file and mooring has following inputs. 

![fst](https://github.com/OpenFAST/openfast/assets/123314026/3f314ed8-2414-4e3e-b6b1-082afcce3eee)
![moordyn](https://github.com/OpenFAST/openfast/assets/123314026/7bbb5ad8-2a0e-48fa-84b0-96def2c276a1)

1) when I analyse the heave response using FFT, the calculated natural frequency is 0 but shows a very small damping ratio value. but when I checked for surge and pitch natural frequency it give me a value close to what I would expect. Also, to validate my FFT code I also conduct heave decay at 200m with default mooring the result shown was correct. 
The above mooring dimension is considered from a research paper for 60mtrs(https://www.mdpi.com/2077-1312/9/10/1093 ) ,which also suggests to use clump weight. but for my simulation I haven't use clump weight. even though I understand it should show some value for heave natural frequency without adding clump weight

2)Also, if you could suggest some reference on how I can add clump weight. that would be helpful. if u think thats the main reason why the heave natural frequency is 0

Please help

Thank You,

**Comment by jjonkman** [comment]
Dear @phildsouza,

I'm not understanding your first question because a natural frequency of zero implies a rigid-body mode with no stiffness and undefined damping.

Best regards,
