### ISSUE TITLE
User defined waves in Hydrodyn

### ISSUE THREAD

**Issue by AriaThomas** [OpenFAST/openfast#1636]
Hi all,

I am using OpenFAST V3.0.0. I want to know how to input a user defined wave-elevation time series using WaveMod = 5 in Hydrodyn. 
I have gone through the documentation. In that a text file with .Elev is specified. 

Can you help me to understand this better?  
   As per my understanding, this text file contains a column with time data and a column for wave elevation values.
   I want to know where should I save this file and in what file name?

Kindly help me.

Thanks and regards,

**Comment by jjonkman** [comment]
Dear @AriaThomas,

The user-specified wave-elevation data file required with `WaveMod` = 5 is a simple text-based file.  The file name and location are not critical, as long as they are referenced consistently within `WvKinFile` in the HydroDyn input file.  An example is provided in Test_006 in the standalone HydroDyn CertTest from FAST v8 archive of HydroDyn (https://www.nrel.gov/wind/nwtc/hydrodyn.html).  These original tests have not yet been migrated to module-level r-test of HydroDyn per the following issue that is still open: https://github.com/OpenFAST/openfast/issues/179.  As such, this example would have to be updated to work with OpenFAST, but hopefully it provides you a useful reference nonetheless.  The draft HydroDyn User’s Guide and Theory Manual provides some more information on the user-specified wave-elevation file: https://openfast.readthedocs.io/en/main/source/user/hydrodyn/input_files.html#waves.

Best regards,

**Comment by AriaThomas** [comment]
Thanks a lot. 
I will try the same.

**Comment by AriaThomas** [comment]
Hi Dr. Jonkman,

I have tried the user defined wave input and I am getting an error when I am turning on any of the platform DOFs in Elastodyn.

I am trying to simulate a no wind (aerodyn module OFF) only wave condition for OC3 5MW SPAR.

I am attaching the required files.

Is it something to do with my wave data?

![Error](https://github.com/OpenFAST/openfast/assets/137166533/e37eb646-19bb-40a3-8e48-8f0154acba7e)

[NRELOffshrBsline5MW_OC3Hywind_ElastoDyn.txt](https://github.com/OpenFAST/openfast/files/11878662/NRELOffshrBsline5MW_OC3Hywind_ElastoDyn.txt)
[NRELOffshrBsline5MW_OC3Hywind_HydroDyn.txt](https://github.com/OpenFAST/openfast/files/11878663/NRELOffshrBsline5MW_OC3Hywind_HydroDyn.txt)
[wave.txt](https://github.com/OpenFAST/openfast/files/11878666/wave.txt)
[5MW_OC3Spar_DLL_WTurb_WavesIrr.txt](https://github.com/OpenFAST/openfast/files/11878669/5MW_OC3Spar_DLL_WTurb_WavesIrr.txt)


Please go through it and requesting your suggestions.

Thanks,

**Comment by jjonkman** [comment]
Dear @AriaThomas,

I only looked briefly at your files and didn't run your model myself, but your _Waves.txt_ file does not seem to be formatted properly.  Per the HydroDyn documentation, I would expect the time column to start at 0 s and increment at a time step of `WaveDT`, which in your case is 1.045 s.

Best regards,

**Comment by AriaThomas** [comment]
Hi @jjonkman,

Thanks for the suggestion.

Is it necessary that the wave elevation time series should have a constant time step?

Since I am digitally extracting the wave elevation data, it will not be possible to get a constant time step.

Regards,

**Comment by jjonkman** [comment]
Hi @AriaThomas,

Yes.   The user-defined wave-elevation file provided for `WaveMod` = 5 must use a constant time step equal to `WaveDT`.  If your data is different from this, I suggest you resample or interpolate your data.

Best regards,

**Comment by AriaThomas** [comment]
Okay,
Thanks a lot for the clarification.

Regards,

**Comment by AriaThomas** [comment]
Dear @jjonkman,

I have tried a constant time step wave elevation data with (0,0) as the starting values. But still I am facing similar problems and also I have noticed that in the output file, the wave elevation column is not having the values that I have given as user defined series. 
I am not understanding the error. 
I am trying to simulate the same condition as discussed before, ie.,  only wave and no wind condition (extreme case scenario). I have tried turning off few DOFs, and Rotor, generator switches. But still the simulation is getting aborted.

Please have a look and share your suggestions.

Regards,

![Error_WaveMod=5](https://github.com/OpenFAST/openfast/assets/137166533/6c8ee213-c471-415d-b8f3-0bd51528c914)
[Output_UDF.xlsx](https://github.com/OpenFAST/openfast/files/11933174/Output_UDF.xlsx)
[NRELOffshrBsline5MW_OC3Hywind_ElastoDyn.txt](https://github.com/OpenFAST/openfast/files/11933176/NRELOffshrBsline5MW_OC3Hywind_ElastoDyn.txt)
[NRELOffshrBsline5MW_OC3Hywind_HydroDyn.txt](https://github.com/OpenFAST/openfast/files/11933177/NRELOffshrBsline5MW_OC3Hywind_HydroDyn.txt)
[wave.txt](https://github.com/OpenFAST/openfast/files/11933179/wave.txt)

**Comment by jjonkman** [comment]
Dear @AriaThomas,

I'm not sure I fully understand what is going on here, but HydroDyn does require that the file you are specifying via `WvKinFile` have a _.Elev_ extension when `WaveMod` = 5.  I see that your file is named _wave.txt_ rather than _wave.Elev_.  Moreover, you've specified `WvKinFile` = "wave.txt", and so, HydroDyn is trying to read _wave.txt.Elev_, which it won't be able to find.  I would suggest renaming your file to _wave.Elev_ and specifying `WvKinFile` = "wave" (without the _.Elev_ extension).

Best regards,

**Comment by AriaThomas** [comment]
Dear @jjonkman,

I have tried your suggestion and it worked. It also worked for WvKinFile = "wave.txt". 

Also, my simulation ran successfully when I decreased the time step with expected results.

Is there any readings to study about the effect of timestep  in OpenFAST simulation? 

I am grateful for your guidance.

Regards,

**Comment by AriaThomas** [comment]
Hi @jjonkman,

Now I am trying to run a case with Aerodyn module ON for a parked condition with the user defined wave elevation.

But I am facing the following issues: 

![Aerodyn_error](https://github.com/OpenFAST/openfast/assets/137166533/d2157c3e-f870-48ca-8a8a-9bdac5a071c7)


I have gone through the forum, but I could not find the exact solution for my error.

I am attaching all the required files.

Please have a look and suggest few options.

Thanks,


[NRELOffshrBsline5MW_OC3Hywind_AeroDyn15.txt](https://github.com/OpenFAST/openfast/files/11966652/NRELOffshrBsline5MW_OC3Hywind_AeroDyn15.txt)
[NRELOffshrBsline5MW_OC3Hywind_ElastoDyn.txt](https://github.com/OpenFAST/openfast/files/11966653/NRELOffshrBsline5MW_OC3Hywind_ElastoDyn.txt)
[5MW_OC3Spar_DLL_WTurb_WavesIrr -fst.txt](https://github.com/OpenFAST/openfast/files/11966666/5MW_OC3Spar_DLL_WTurb_WavesIrr.-fst.txt)
[5MW_OC3Spar_DLL_WTurb_WavesIrr.ED - ech.txt](https://github.com/OpenFAST/openfast/files/11966667/5MW_OC3Spar_DLL_WTurb_WavesIrr.ED.-.ech.txt)

**Comment by jjonkman** [comment]
Dear @AriaThomas,

See: https://github.com/OpenFAST/openfast/discussions/1496.

Best regards,
