### ISSUE TITLE
FAST_InitializeAll:HydroDyn_Init: WaveElevSeries arrays for first and second order wave elevations are of different sizes.

### ISSUE THREAD

**Issue by calcin** [OpenFAST/openfast#1637]
Dear all，
The following error occurred when I was running the 15MW wind turbine model:

**************************************************************************************************
OpenFAST

Copyright (C) 2023 National Renewable Energy Laboratory
Copyright (C) 2023 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v3.5.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 2021
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: May 17 2023
 - Time: 13:43:33
Execution Info:
 - Date: 06/20/2023
 - Time: 22:44:40+0800

OpenFAST input file heading:
    IEA 15 MW offshore reference model on UMaine VolturnUS-S semi-submersible floating platform

Running ElastoDyn.
Running AeroDyn.
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 5, blade 1)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 5, blade 2)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 5, blade 3)
Running InflowWind.
Running HydroDyn.
 Generating incident wave kinematics and current time history.
 Calculating second order difference frequency wave kinematics.
 Calculating second order sum frequency wave kinematics.

FAST_InitializeAll:HydroDyn_Init: WaveElevSeries arrays for first and second order wave
elevations are of different sizes.

 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.

This error appeared after I set up the visualization file，My settings are as follows：

---------------------- VISUALIZATION ------------------------------------------
2                      WrVTK       - VTK visualization data output: (switch) {0=none; 1=initialization data only; 2=animation}
1                      VTK_type    - Type of VTK visualization data: (switch) {1=surfaces; 2=basic meshes (lines/points); 3=all meshes (debug)} [unused if WrVTK=0]
False                  VTK_fields  - Write mesh fields to VTK data files? (flag) {true/false} [unused if WrVTK=0]
10                   VTK_fps     - Frame rate for VTK output (frames per second){will use closest integer multiple of DT} [used only if WrVTK=2]

His error report here points to the HydroDyn file, and I'm not sure what went wrong.
I will upload my file to the attachment, any help would be appreciated.

[IEA-15-240-RWT-UMaineSemi.txt](https://github.com/OpenFAST/openfast/files/11801815/IEA-15-240-RWT-UMaineSemi.txt)

[IEA-15-240-RWT-UMaineSemi_HydroDyn.txt](https://github.com/OpenFAST/openfast/files/11801813/IEA-15-240-RWT-UMaineSemi_HydroDyn.txt)

**Comment by andrew-platt** [comment]
Take a look at issue #1484. 

Closing as this is identical to a previous issue.

**Comment by calcin** [comment]
Thank you for your answer, dear @andrew-platt
