### ISSUE TITLE
Considering a self-defined wind turbine in OpenFAST

### ISSUE THREAD

**Issue by LGZDWM** [OpenFAST/openfast#1646]
Dear all,
Is it possible to run simulations on a self-defined wind turbine by OpenFAST, providing I have the necessary geometric parameter. If yes, is there a tutorial about this? Any kinds of guidance are greatly appreciated.
Best regards,
LGZDWM.

**Comment by jjonkman** [comment]
Dear @LGZDWM,

Yes, of course.  OpenFAST is fully parameterized through its input files, with aerodynamic properties defined in AeroDyn, structural properties defined in ElastoDyn (and perhaps BeamDyn and SubDyn), control properties defined in ServoDyn, etc. for other modules.  Of course, there are many input parameters that need to be set.  And I'm not aware of a detailed step-by-step guide for developing your own models.

If you have all of the data, the process is fairly straightforward as long as you understand the definitions of each input parameter (documented here for each module: https://openfast.readthedocs.io/en/main/source/user/index.html#module-documentation).  If you have to estimate or derive the data, the process is more difficult.  Establishing airfoil data for AeroDyn, blade and tower mode shapes for ElastoDyn, and the controller for ServoDyn are inputs that have caused the most confusion among users, but have been discussed on many topics on this OpenFAST GitHub site, as well as our forum: https://forums.nrel.gov/.

It may be useful to review the publications documenting the development of the existing open-source reference models, such as the popular NREL 5-MW baseline wind turbine (https://www.nrel.gov/docs/fy09osti/38060.pdf) or the IEA Wind 15-MW reference wind turbine (https://www.nrel.gov/docs/fy20osti/75698.pdf), which explain how these models were established.

Best regards,
