### ISSUE TITLE
About OLAF error

### ISSUE THREAD

**Issue by xinyulii** [OpenFAST/openfast#1650]
**Bug description**
When I tried to use an OLAF file, there was an error as follows：

Error reported by S-function 'FAST_SFunc' in 'BaseController/FAST Nonlinear Wind Turbine/S-Function':
FAST_InitializeAll:AD_Init:Init_OLAF:FVW_Init:FVW_ReadInputFile:Invalid numerical input for file ".\../5MW_Baseline/OLAF.dat" occurred while trying to read nFWPanels.

May I ask how to resolve this error？

OpenFAST-v3.1.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 1900
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: Mar 08 2022
 - Time: 10:53:02
Execution Info:
 - Date: 06/26/2023
 - Time: 13:33:32+0800
```

**Comment by jjonkman** [comment]
Dear @xinyulii,

My guess is that you are using input files that are not compatible with the version of OpenFAST you are using.  The changes to the input files with each release of OpenFAST are documented here; https://openfast.readthedocs.io/en/main/source/user/api_change.html.  As with any input file processing issue, I would suggest enabling the `Echo` option to debug.

Best regards,

**Comment by xinyulii** [comment]
Dear jjonkman,
Thanks for you response！

Best regards,

xinyulii
