### ISSUE TITLE
reference local system for loads on nodes in elastodyn and beamdyn

### ISSUE THREAD

**Issue by MassimoSirigu** [OpenFAST/openfast#1661]
Hello, I want to perform a structural analysis using openfast. 
I want to evaluate the forces at the nodes in elastodyn and beamdyn and apply them to 2D finite element cross sections of the blade. 
I have some doubts about which kind of reference system I have to use if I want to obtain a moment around the local coordinates of the section, including blade pitch angle and initial twist of the sections.
eventually, i want to have a moment to be applied on the section around the x axis like in the figure.
In beamdyn, I think I have to implement MyL and not MyR; in elastodyn, is it MLy or MlyNT? 
are other transformations necessary before directly applying the moment?
thank you.

![figA02a](https://github.com/OpenFAST/openfast/assets/91613193/143de71d-4527-4259-acb4-6234268e0adb)

**Comment by jjonkman** [comment]
Dear @MassimoSirigu,

I'm not sure I fully understand your question.  I'll just clarify that:

- In ElastoDyn, the local blade loads (Lxb, Lyb, lzb) are in a coordinate system that pitches and deflects with the blade and is aligned with the local structural pretwist.  The nodal loads labled with NT are the same, except in a local coordinate system that does not include the structural pretwist.
- In BeamDyn, the local blade loads in the "l" system are in a coordinate system that pitches and deflects with the blade and is aligned with the local structural pretwist.

Best regards,

**Comment by MassimoSirigu** [comment]
Dear Mr Jonkman,
You answered my question. So I have to use Mly.
thank you
