### ISSUE TITLE
FAST.Farm: Wake meandering effect does NOT show on visualization 

### ISSUE THREAD

**Issue by jujeonW** [OpenFAST/openfast#1662]
Hello everyone,
I am using FAST.Farm to simulate the wake effects on the downstream turbine. It seems like there is something wrong with my setting of the DWM module because the wake meandering effect is not showing when I read the .vtk files. The values that I choose for the DWM module  in the simulations are pretty much just default values. Besides, in FAST.Farm my DT_Low is 2.4 dS_Low is 15 dS_High is 5.  The inflow generated by TurbSim is set to 4% turbulence intensity and 10m/s speed. I changed the turbulence intensity but it doesn't look better either. I can't find a reason for this. Does anybody have an idea?
Thank you kindly
![TI04_480S](https://github.com/OpenFAST/openfast/assets/137092153/39281fe0-64f3-4e07-a68f-c9edaaae56da)
![multi_960s](https://github.com/OpenFAST/openfast/assets/137092153/8b6e4142-697d-4ae7-b6e1-dc79807a702e)
![-0_75D_-20degrees_192s](https://github.com/OpenFAST/openfast/assets/137092153/82429243-2123-411a-8925-e3761ac4e067)

> --- WAKE DYNAMICS ---
> 1                  Mod_Wake           - Switch between wake formulations {1:Polar, 2:Curl, 3:Cartesian} (-) (switch)
> 5.0                dr                 - Radial increment of radial finite-difference grid (m) [>0.0]
> 42                 NumRadii           - Number of radii in the radial finite-difference grid (-) [>=2]
> 86                 NumPlanes          - Number of wake planes (-) [>=2]
> 0.20               f_c                - Cutoff (corner) frequency of the low-pass time-filter for the wake advection, deflection, and meandering model [recommended=1.28*U0/R] (Hz) [>0.0] or DEFAULT [DEFAULT=12.5/R, R estimated from dr and NumRadii, not recommended]
> DEFAULT            C_HWkDfl_O         - Calibrated parameter in the correction for wake deflection defining the horizontal offset at the rotor                                               (m    ) or DEFAULT [DEFAULT= 0.0  ]
> DEFAULT            C_HWkDfl_OY        - Calibrated parameter in the correction for wake deflection defining the horizontal offset at the rotor scaled with                         yaw error (m/deg) or DEFAULT [DEFAULT= 0.0 if Mod_Wake is 2, 0.3 otherwise]
> DEFAULT            C_HWkDfl_x         - Calibrated parameter in the correction for wake deflection defining the horizontal offset              scaled with downstream distance               (-    ) or DEFAULT [DEFAULT= 0.0  ]
> DEFAULT            C_HWkDfl_xY        - Calibrated parameter in the correction for wake deflection defining the horizontal offset              scaled with downstream distance and yaw error (1/deg) or DEFAULT [DEFAULT= 0.0 if Mod_Wake is 2, -0.004 otherwise]
> DEFAULT            C_NearWake         - Calibrated parameter for the near-wake correction (-) [>1.0 and <2.5] or DEFAULT [DEFAULT=1.8]
> DEFAULT            k_vAmb             - Calibrated parameter for the influence of ambient turbulence in the eddy viscosity (-) [>=0.0] or DEFAULT [DEFAULT=0.05 ]
> DEFAULT            k_vShr             - Calibrated parameter for the influence of the shear layer    in the eddy viscosity (-) [>=0.0] or DEFAULT [DEFAULT=0.016]
> DEFAULT            C_vAmb_DMin        - Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the transitional diameter fraction between the minimum and exponential regions (-) [>=0.0          ] or DEFAULT [DEFAULT= 0.0 ]
> DEFAULT            C_vAmb_DMax        - Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the transitional diameter fraction between the exponential and maximum regions (-) [> C_vAmb_DMin  ] or DEFAULT [DEFAULT= 1.0 ]
> DEFAULT            C_vAmb_FMin        - Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the value in the minimum region                                                (-) [>=0.0 and <=1.0] or DEFAULT [DEFAULT= 1.0 ]
> DEFAULT            C_vAmb_Exp         - Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the exponent in the exponential region                                         (-) [> 0.0          ] or DEFAULT [DEFAULT= 0.01]
> DEFAULT            C_vShr_DMin        - Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the transitional diameter fraction between the minimum and exponential regions (-) [>=0.0          ] or DEFAULT [DEFAULT= 3.0 ]
> DEFAULT            C_vShr_DMax        - Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the transitional diameter fraction between the exponential and maximum regions (-) [> C_vShr_DMin  ] or DEFAULT [DEFAULT=25.0 ]
> DEFAULT            C_vShr_FMin        - Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the value in the minimum region                                                (-) [>=0.0 and <=1.0] or DEFAULT [DEFAULT= 0.2 ]
> DEFAULT            C_vShr_Exp         - Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the exponent in the exponential region                                         (-) [> 0.0          ] or DEFAULT [DEFAULT= 0.1 ]
> DEFAULT            Mod_WakeDiam       - Wake diameter calculation model (-) (switch) {1: rotor diameter, 2: velocity based, 3: mass-flux based, 4: momentum-flux based} or DEFAULT [DEFAULT=1]
> DEFAULT            C_WakeDiam         - Calibrated parameter for wake diameter calculation (-) [>0.0 and <0.99] or DEFAULT [DEFAULT=0.95] [unused for Mod_WakeDiam=1]
> DEFAULT            Mod_Meander        - Spatial filter model for wake meandering (-) (switch) {1: uniform, 2: truncated jinc, 3: windowed jinc} or DEFAULT [DEFAULT=3]
> DEFAULT            C_Meander          - Calibrated parameter for wake meandering (-) [>=1.0] or DEFAULT [DEFAULT=1.9]

**Comment by jjonkman** [comment]
Dear @jujeonW,

Can you clarify what settings you are using in TurbSim?  Wake meandering will be driven by the transverse components (v and w) of the turbulent inflow.  Have you enabled spatial coherence in the transverse direction per the FAST.Farm modeling guidance: https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#turbsim?

Best regards,

**Comment by jujeonW** [comment]
Dear @jjonkman,

indead, the settings for v and w components in TurbSim seem to have caused the issue. I am fixing it now. Thank you so much.

Best regards,
