### ISSUE TITLE
beamdyn standalone with gyroscopic and external forces in static analysis

### ISSUE THREAD

**Issue by MassimoSirigu** [OpenFAST/openfast#1668]
Hello, I want to perform a static analysis of the 15 MW wind turbine blade. I was able to use Beadmyn standalone to perform static analysis using external aerodynamic forces that I have implemented on my own in a Matlab code. However, my static analysis does not involve the steady-state gyroscopic and inertial forces (omega is null) and I want to include these forces in my model since I've seen that the centrifugal stiffness around the twist axis is very important (2 degrees of difference at the tip and this affects the aerodynamic loads). 
The problem is that I'm not able to include this kind of force while performing a static analysis with external forces in Beamdyn standalone. I can only perform a static analysis of gyroscopic force with a workaround: enable DynamicSolve and QuasiStaticInit for centripetal forces, but at this point, I have a transient for my external forces. 
Is there a way to include both with a static analysis? 
Alternatively, I was thinking about using OpenFAST and the linearisation module to find steady-state points. from your point of view, is it possible to use the linearisation module to find the steady state point enabling only aerodyn and beamdyn (excluding all the other modules, with zero degrees of freedom, with a constant rotor speed)? the steady state point has as a parameter a constant wind speed, rotor speed and blade pitch and the output will be the static deformation of the blade.

**Comment by jjonkman** [comment]
Dear @MassimoSirigu,

I'm actually not very familiar with the functionality of the static solver available through the BeamDyn driver (`DynamicSolve` = False); perhaps someone else can comment on if rotational effects can be accounted for when that is enabled.

But I agree that you can perform a linearization analysis to find a steady-state solution in OpenFAST with fixed rotor speed and all degrees of freedom of ElastoDyn disabled, and only BeamDyn and AeroDyn functionality enabled.

Best regards,

**Comment by MassimoSirigu** [comment]
Thank you for your comment. My primary goal is to obtain a steady state deformation of the blade using a very quick solver. the standalone version of beamdyn performs the analysis in 0.3 seconds. In these days I was using also a timedomain analysis in openfast with aerodyn+beadmyn, with a fictional damping of 70% and I can obtain a steady state condition within 30 seconds (time I have to wait for the results). 
Do you think that using the linearisation module could lower the computation time for one load case?

**Comment by jjonkman** [comment]
Dear @MassimoSirigu,

Currently, the steady-state calculation in OpenFAST uses a similar time-domain simulation process as typical time-domain OpenFAST simulations without linearization enabled.  So, I would not expect the time-to-solution would be less with linearization enabled.

FYI: NREL is currently working with an industry partner on the introduction of a steady-state solver in OpenFAST that should reduce the time needed to compute a steady-state solution for linearization and to establish better initial conditions for time-domain simulations.  This functionality is not complete yet, but it sounds like the functionality you are seeking.

Best regards,

**Comment by MassimoSirigu** [comment]
Ok, I understand. Today I discovered that four days ago a pull request (Resolve BeamDyn initial strain for rotated blade #1663) solved a convergence issue for beamdyn. I recompiled the code and now my model takes 5 seconds to obtain a satisfactory steady state point, so now the computational time is perfectly acceptable. 
best regards,
Massimo Sirigu
