### ISSUE TITLE
A question about TurbSim parallelism.

### ISSUE THREAD

**Issue by Helloczm** [OpenFAST/openfast#1675]
Dear all
Does TurbSim V2.0 support OpenMP or MPI parallel computing?
@NRELAdmin @jjonkman

**Comment by ebranlard** [comment]
Hi @Helloczm 
TurbSim does not come with any parallelization. Some could be implemented, but we don't have a project to scope that work at the moment.

**Comment by Helloczm** [comment]
Thank you for your reply!
