### ISSUE TITLE
How can I ge OMP or MPI version of FAST.Farm on linux?

### ISSUE THREAD

**Issue by OMGTaylor0814** [OpenFAST/openfast#1688]
Hi guys,
I want to know how to build my parallel version of FAST. Farm on Linux (ubuntu) because I have a large wind farm to run.

Perhaps someone can give me a detailed guidance?

Best Regards,

**Comment by jjonkman** [comment]
Dear @OMGTaylor0814,

FAST.Farm does not support MPI parallelization as of yet, but OpenMP parallelization is available.  Compiling instructions are documented on readthedocs: https://openfast.readthedocs.io/en/main/source/install/index.html#fast-farm.

Best regards,

**Comment by OMGTaylor0814** [comment]
Dear @jjonkman 

Sorry, I am not a professional in this field. I would like to know if I should execute `cmake `in the OpenFAST/build directory with `- DBUILD_ FASTFARM:BOOL=ON - DOPENMP=ON`, and then `make `it?

But I checked the executable programs in the `install/bin` directory, only FAST.FARM.  When I ran a case to view program information, I found that` -  OPENMP: NO`

Have I overlooked any important information?

Can you tell me which specific chapter is in readthedocs?

**Comment by OMGTaylor0814** [comment]
Oh , I think I got it https://openfast.readthedocs.io/en/main/source/user/fast.farm/RunningFFarm.html#running-fast-farm
`To improve the speed of OpenFAST compiled with FAST.Farm enabled, the user may wish to compile in single precision with OpenMP. To do so, add the -DDOUBLE_PRECISION:BOOL=OFF -DOPENMP=ON options with CMake.`

Perhaps someone has done research on the difference between single precision and double precision?

**Comment by OMGTaylor0814** [comment]
Hi
抱歉我还是没有成功得到想要的可执行程序
我尝试了很多次，但openfast和FAST.Farm都不支持 OPENMP，我不清楚是否自己的操作出现了失误
我执行的过程为：
```
mkdir build
cd build
cmake .. -DBUILD_FASTFARM:BOOL=ON -DDOUBLE_PRECISION:BOOL=OFF -DOPENMP=ON
make -j 32
make install
```
运行结果为：
![Fast Farm](https://github.com/OpenFAST/openfast/assets/78580228/05a5b26c-fe33-4f91-a7ac-b704704d48a8)
![openfast](https://github.com/OpenFAST/openfast/assets/78580228/c9f1aec5-f0cc-4b8c-9529-67425fe4f370)

Have I overlooked any important information?

Best Regards,

**Comment by deslaughter** [comment]
@OMGTaylor0814 , there was a bug introduced in the 3.5.0 release where the OpenMP flags were added to the wrong CMake variables. This was fixed in #1647 so please try compiling the `rc-3.5.1` branch and let me know if it resolves your issue.

**Comment by OMGTaylor0814** [comment]
@jjonkman @deslaughter 
Thanks for your help and it work.
And I have two questions:
1. How could I determine the threads I need ? The program used all the threads, which I don't think is necessary. According to the instructions in the document, can I just ensure that there is one more thread than the number of turbines?
2. I met a Error 
` Time: 16 of 10600 seconds.  Estimated final completion at 16:32:45.                              
 FARM_UpdateStates:AWAE_UpdateStates:InflowWind_CalcOutput:CalculateOutput:IfW_FlowField_GetVelAcc:
 Grid3DField_GetCell: Error: GF wind array was exhausted at 18.3 seconds (trying to access data at
 -2.28882E-05 seconds).

  Aborting FAST.Farm.`
which did not show in the non-parallel version of Farm, what should I do for it? I need to mention that I have already adjusted the flag of 'UsableTime' to 'ALL' in the inp file.

Best Regards,

**Comment by deslaughter** [comment]
@OMGTaylor0814 , I don't have a lot of experience with OpenMP and FAST.Farm but I would expect more threads to be better. It looks like AeroDyn can take advantage of OpenMP so having more threads than the number of turbines could be beneficial. For the second issue, see if you pulled down #1684 in the `rc-3.5.1` branch which was a fix for this problem, it was merged in yesterday. If that PR doesn't fix it, please provide the InflowWind input file so I can debug it. Thanks.

**Comment by OMGTaylor0814** [comment]
@deslaughter 
Thanks for your reply
I found that https://github.com/OpenFAST/openfast/pull/1684 The title of [BugFix] change time handling to double precision for G4D timestamp index, but according to the statement I saw earlier, I need to turn on single precision to use OPENMP. So what should I do?

Also, is the InflowWind input file you need a. dat file? Or am I using the bts file generated by turbsim? I have placed all the mentioned files and fstf files in the https://anonfiles.com/rdYaQ92eza/test_7z For your reference, I hope it can be helpful. I am currently using V3.4.1 version of Farm for parallel computing.

**Comment by deslaughter** [comment]
@OMGTaylor0814 , #1684 forces the time handling to be double precision even when compiling in with `-DDOUBLE_PRECISION=OFF`, so you can still see if that PR fixes the issue. It may also be helpful to try compiling with `-DDOUBLE_PRECISION=ON`. Running in single precision and using OpenMP will make FAST.Farm run faster, but both aren't required to for OpenMP to work so you can try one or the other or both.
