### ISSUE TITLE
Errors During OpenFast Build Solution

### ISSUE THREAD

**Issue by KanwarOsama** [OpenFAST/openfast#1692]
Hi,
Hope everyone is doing well. I was trying to Build solution using Visual Studio. There are certain problems that I am facing. Can anyone please tell me what can be a solution to these?
![errors_1](https://github.com/OpenFAST/openfast/assets/139915137/33a49a9b-bff4-4afe-8547-fcdcd4e6dcab)

 Error 1108: Cannot open MKL core
Error   11018: Cannot open mkl_intel_ip64
Error 11018: Cannot open mkl_sequential
Error 11081: : cannot open file 'mkl_intel_lp64.lib'

**Comment by jjonkman** [comment]
Dear @KanwarOsama,

This question has been asked before.  Visual Studio is not finding the MKL libraries for some reason.  Did you install them when you installed the Intel Fortran compiler?

Best regards,

**Comment by KanwarOsama** [comment]
Hi,
Thanks for your response. I don't remember actually if I did it or not. Can I check somehow?

**Comment by jjonkman** [comment]
Dear @KanwarOsama,

See @bjonkman's post dated July 15, 2020 in the following OpenFAST issue: https://github.com/OpenFAST/openfast/issues/322.

Best regards,
