### ISSUE TITLE
Error after implementing TurbSim: GF wind array was exhausted at 0.5 seconds

### ISSUE THREAD

**Issue by lusoalman** [OpenFAST/openfast#1702]
Dear Community!

I am running FASTFarm v3.5 on Windows 10. My model consists of two small wind turbine models (D=1.2m). I wanted to implement TurbSim and did generate the .bts but now I get this error:
![image](https://github.com/OpenFAST/openfast/assets/135970332/b7a139c8-e272-419e-abd9-1bf4a3fed5db)

I have tried some different grid setups but nothing changes. Here is my input file for the TurbSim:
[TurbSim.txt](https://github.com/OpenFAST/openfast/files/12161931/TurbSim.txt)

Also: Where can I set that the full-field wind data files are generated periodically as requested here: https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#inflow-wind-generation ?

Thank you for the help!

All the best, 
Sara

**Comment by jjonkman** [comment]
Dear @lusoalman,

To generate periodic wind data, you should set UsableTime = "ALL" in your TurbSim input file.  Does that solver your issue?

FYI: When generating inflow for use with FAST.Farm, I would recommend using the scripts available through the Python toolbox (https://github.com/OpenFAST/python-toolbox/tree/main/pyFAST/fastfarm).

Best regards,

**Comment by lusoalman** [comment]
Dear @jjonkman,
Thank you for the quick answer! I tried giving "ALL" as an input for the usable time before but I get a numerical error:
Invalid numerical input for file ".\TurbSim.inp".
The error occurred while trying to read the usable output time.


All the best, 
Sara

**Comment by jjonkman** [comment]
Dear @lusoalman,

It appears that you are using an old version of TurbSim (v1.5).  I suggest upgrading to the TurbSim v2.0 (available here: https://www.nrel.gov/wind/nwtc/turbsim.html) or the version of TurbSim available in this OpenFAST GitHub repository (which contains a few small updates relative v2.0).

Best regards,

**Comment by lusoalman** [comment]
Dear @jjonkman,

Ah yes, that worked.  But I need to figure out some other errors I get now when running TurbSim:
![image](https://github.com/OpenFAST/openfast/assets/135970332/a2004dbf-b038-4345-9762-283785024be1)
[TurbSim_UsrSpec.txt](https://github.com/OpenFAST/openfast/files/12170372/TurbSim_UsrSpec.txt)

Thanks a lot and all the best, 
Sara

**Comment by jjonkman** [comment]
Dear @lusoalman,

An error in the Cholesky factorization results from having too high (i.e., unphysical) coherence.  Presumably the issue in your case is that your domain is very small for model scale, so, the coherence parameters may need to be customized for the scale.

I would say that it is more common to keep the simulations at full scale, and scale-up model-scale experimental data to full scale when doing validation (assuming that is what you are doing).

Please also note that the FAST.Farm modeling guidance recommends setting `SCMod2` and `SCMod3` to "IEC" in TurbSim to ensure that you will get transverse coherence in TurbSim and wake meandering in FAST.Farm.

Best regards,

**Comment by lusoalman** [comment]
Dear @jjonkman,

Thank you for your answer. 
I understand the issue but I got confused with the scaling now. Should I increase the grid and hub size and scale it down to my application? Do I do that by setting `ScaleIEC` to 2 and changing the `Coherent Turbulence Scaling Parameters` ?

**Comment by lusoalman** [comment]
Dear @jjonkman,

Okay, thanks a lot! I will try changing the Spatial Coherence Parameters.

All the best, 
Sara

**Comment by majidpoli** [comment]
Dear @jjonkman 
I am trying to simulate the disturbed wind Inflow. I used the matlab code [https://forums.nrel.gov/t/binary-wnd-specification/180/5] to use it for inflow wind (.wnd) for FAST.Farm but I have faced error. 
   Reading a 76x19 grid (1500 m wide, 5 m to 455 m above ground) with a characteristic wind speed
   of 10.347 m/s.

   Processed 334 time steps of 0.33333-Hz full-field data (999 seconds).

Farm_Initialize:AWAE_Init:AWAE_UpdateStates:InflowWind_CalcOutput:CalculateOutput:IfW_FlowField_Ge
tVelAcc:Grid3DField_GetCell: Error: GF wind array was exhausted at 3 seconds (trying to access
data at -2.7985 seconds). IT_Lo=0, IT_HI=1
InflowWind_CalcOutput:InflowWind_GetSpatialAverage:CalculateOutput:IfW_FlowField_GetVelAcc:Grid3DF
ield_GetCell: Error: GF wind array was exhausted at 3 seconds (trying to access data at -247.1
seconds). IT_Lo=-82, IT_HI=-81
InflowWind_CalcOutput:InflowWind_GetHubValues:CalculateOutput:IfW_FlowField_GetVelAcc:Grid3DField_
GetCell: Error: GF wind array was exhausted at 3 seconds (trying to access data at -261.56
seconds). IT_Lo=-87, IT_HI=-86

The data of Inflow wind, I got from .dtk with dt_low = 3s, as the time step, and the dt_low for my new simulation is also 3s, and dt_high = 0.3s. (.sum) file I followed the specification mentioned in the link as below,

T CLOCKWISE 
230.00 HUB HEIGHT

10.347 UBAR 
6.000 TI(u) 
6.000 TI(v) 
6.000 TI(w)

0.000 HEIGHT OFFSET

when I value Height OFFSET =0, the Running Inflow shows " (1500 m wide, 5 m to 455 m above ground)" which is my desire.

**Comment by jjonkman** [comment]
Dear @majidpoli,

My guess is the problem is in your FAST.Farm set up in the X direction (or time).  The script you are using does not generate wind data that is periodic in time (as recommended in the FAST.Farm modeling guidance when using synthetic wind data), so, your wind data will have a finite length of time, which is equivalent to a fixed length in the X direction.  Where have a placed the wind turbines and what are the dimensions and locations of your FAST.Farm low- and high-resolution domains?

Best regards,

**Comment by majidpoli** [comment]
3.0       DT_Low        Time step for low-resolution wind data interpolation; will be used as the global FAST.Farm time step (s) 
 0.3      DT_High       Time step for high-resolution wind data interpolation (s) [>0.0]
 155    NX_Low        Number of low-resolution spatial nodes in X direction for wind data interpolation (-) [>=2]
 76.0    NY_Low        Number of low-resolution spatial nodes in Y direction for wind data interpolation (-) [>=2]
 19.0     NZ_Low        Number of low-resolution spatial nodes in Z direction for wind data interpolation (-) [>=2]
  0.0    X0_Low        Origin of low-resolution spatial nodes in X direction for wind data interpolation (m)
 -750.0    Y0_Low        Origin of low-resolution spatial nodes in Y direction for wind data interpolation (m)
    5.0    Z0_Low        Origin of low-resolution spatial nodes in Z direction for wind data interpolation (m)
45.0       dX_Low        Spacing of low-resolution spatial nodes in X direction for wind data interpolation (m) [>0.0]
20.0       dY_Low        Spacing of low-resolution spatial nodes in Y direction for wind data interpolation (m) [>0.0]
25.0       dZ_Low        Spacing of low-resolution spatial nodes in Z direction for wind data interpolation (m) [>0.0]
57.0       NX_High       Number of high-resolution spatial nodes in X direction for wind data interpolation (-) [>=2]
57.0       NY_High       Number of high-resolution spatial nodes in Y direction for wind data interpolation (-) [>=2]
87         NZ_High       Number of high-resolution spatial nodes in Z direction for wind data interpolation (-) [>=2]

--- WIND TURBINES ---
3         NumTurbines   Number of wind turbines (-) [>=1] [last 6 columns below used only for Mod_AmbWind=2 or 3]
WT_X       WT_Y   WT_Z   WT_FASTInFile   	X0_High    Y0_High   Z0_High   dX_High   dY_High   dZ_High                                                                                                                                                       
(m)        (m)    (m)    (string)     		(m)        (m)       (m)       (m)       (m)       (m)                                                                                                                                                                               
1200.0      0.0    0.0      "fst\WT1.fst"          1060.0     -140.0      5.0       5.0      5.0      5.0
2400.0      0.0    0.0      "fst\cWT2.fst"          2260.0     -140.0      5.0       5.0      5.0      5.0
3600.0      0.0    0.0      "fst\WT3.fst"          3460.0     -140.0      5.0       5.0      5.0      5.0

**Comment by jjonkman** [comment]
Dear @majidpoli,

Indeed, it appears that the flow in the X direction does not encompass your wind farm because your inflow data is not assumed to be periodic by InflowWind.  For wind data that is not periodic, InflowWind will start the wind box 0.5*`MIN`(`GridWidth`, `GridHeight`)  downstream of X =0 (which is X = 225 m for your wind box), and the box of length `UBAR`*`UsableTime` (which equals 10336.6 m for your wind box) will propagate downstream at a speed of `UBAR`.  However, your turbines and domains extend further downstream, and so, do not lie within the wind box at the start of the simulation.  To ensure that the domain lies within the wind box, you'll have to shift the entire domain upwind.

FYI: I notice that your high-resolution domain has a smaller time step and spatial resolution than your wind box, but InflowWind can only interpolate wind data, not add refinement, so, this added resolution will not improving the solution in your case.  This is why we typically recommend using `Mod_AmbWind` = 3 when using synthetic wind data in FAST.Farm, which allows you to use use distinct synthetic wind boxes for the low- and high-resolution domains that have appropriate resolution tailored to each domain.

Best regards,

**Comment by majidpoli** [comment]
Dear @jjonkman,
Thanks for the fast response and your commitment, 
I used the normalized wind speed discussed in "Table C-2: TurbSim tower data binary file grid format"
I respected the wind box in the farm, and mentioned the "PERIODIC" in the .sum file. 
so now FAST.Farm could read the .wnd file.
Thanks
