### ISSUE TITLE
Running cmake with BUILD_OPENFAST_SIMULINK_API=ON fails with cmake error

### ISSUE THREAD

**Issue by reos-rcrozier** [OpenFAST/openfast#1705]
**Bug description**
running cmake on dev branch with BUILD_OPENFAST_SIMULINK_API=ON results in the following cmake error:

```
CMake Error at /usr/share/cmake-3.22/Modules/FindMatlab.cmake:1123 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:foamtypeslib>

  No target "foamtypeslib"
Call Stack (most recent call first):
  glue-codes/simulink/CMakeLists.txt:23 (matlab_add_mex)


CMake Error at /usr/share/cmake-3.22/Modules/FindMatlab.cmake:1123 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:foamfastlib>

  No target "foamfastlib"
Call Stack (most recent call first):
  glue-codes/simulink/CMakeLists.txt:23 (matlab_add_mex)


CMake Error at /usr/share/cmake-3.22/Modules/FindMatlab.cmake:1123 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:foamtypeslib>

  No target "foamtypeslib"
Call Stack (most recent call first):
  glue-codes/simulink/CMakeLists.txt:23 (matlab_add_mex)


CMake Error at /usr/share/cmake-3.22/Modules/FindMatlab.cmake:1123 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:foamfastlib>

  No target "foamfastlib"
Call Stack (most recent call first):
  glue-codes/simulink/CMakeLists.txt:23 (matlab_add_mex)


CMake Error at /usr/share/cmake-3.22/Modules/FindMatlab.cmake:1123 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:foamtypeslib>

  No target "foamtypeslib"
Call Stack (most recent call first):
  glue-codes/simulink/CMakeLists.txt:23 (matlab_add_mex)


CMake Error at /usr/share/cmake-3.22/Modules/FindMatlab.cmake:1123 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:foamfastlib>

  No target "foamfastlib"
Call Stack (most recent call first):
  glue-codes/simulink/CMakeLists.txt:23 (matlab_add_mex)


CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:foamtypeslib>

  No target "foamtypeslib"


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**To Reproduce**
<Update the following list with your specific information.>
1. clone dev branch
2. run
`cmake -LH ~/src/openfast-official-git -DBUILD_FASTFARM=ON -DBUILD_OPENFAST_CPP_API=ON -DBUILD_OPENFAST_SIMULINK_API=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr/local -DDOUBLE_PRECISION=ON -DOPENMP=OFF -DUSE_LOCAL_STATIC_LAPACK=OFF
`4. See the error

**Expected behavior**
cmake to complete without error

**OpenFAST Version**
recent dev branch commit e6052f28744366ed19b89c9b81c7c0f495cffdd1 

**Additional context**
I have a PR with a test with would help prevent such regression in future, see PR #1703 

Currently tests are failing because of this issue.

**Comment by reos-rcrozier** [comment]
@deslaughter sorry hope you don't mind me tagging you here as it seems to be your area.

**Comment by reos-rcrozier** [comment]
Seems to be related to the removal of openfoam and addition of addition of the generic externalinflow module. Seems the simulink interface hasn't been modified to take account of this. Hopefully easy to fix.

**Comment by reos-rcrozier** [comment]
This issue would now be resolved by the PR #1703

**Comment by andrew-platt** [comment]
Thanks for looking into the Simulink build system!  Your expertise in this area is very appreciated!

This was indeed an oversight on my part during the name conversion (it was a bit of a rush due to a deliverable that depended on it).

**Comment by reos-rcrozier** [comment]
It's easily missed, which is why I thought a simulink test would be useful.
