### ISSUE TITLE
SD: concentrated mass with excentricity cannot be fully accounted for in SubDyn

### ISSUE THREAD

**Issue by ebranlard** [OpenFAST/openfast#1710]
Currently, SubDyn users can provide inertial properties of the concentrated mass such that the concentrated mass has an offset compared to the node location, using the three lasts inputs of the [concentrated mass table](https://openfast.readthedocs.io/en/dev/source/user/subdyn/input_files.html#joint-additional-concentrated-masses): `MCGX, MCGY, MCGZ`. 

The main issue is that the FEM model of SubDyn does not keep track of the center of mass offset, and therefore, cannot compute the Guyan load correction ("[extra moment](https://openfast.readthedocs.io/en/dev/source/user/subdyn/theory.html#corrections-to-the-baseline-formulation-guyanloadcorrection)") for this excentric mass. This will lead to inaccuracies in the results.

In the future, we will therefore discontinue this feature. 

The workaround is:
  - introduce a node at the location of the concentrated mass
  - connect this node with a rigid link to the closest node of the structure 

Small note: there is currently a small bug, where the gravity moment due to the excentricity of the concentrated mass is missing. It can be fixed with [this change](https://github.com/ebranlard/openfast/commit/f5abacd2066e177da46a56888dd5bf9e714e3237). But because in the future we will not support the excentricity any longer, there is no immediate need to fix it.

**Comment by andrew-platt** [comment]
Fixed with #2458 and included in the 4.0.0 release.
