### ISSUE TITLE
How to output the curvature of the tower nodes in ED

### ISSUE THREAD

**Issue by YangLeiTH** [OpenFAST/openfast#1712]
Hi @jjonkman 

I wonder how to output the curvature of the tower nodes. From the outListParameters.xlsx, I can only find the displacement and the rotational displacement, but how to output the curvature of the tower nodes?

Best regards,

**Comment by TDmili** [comment]
Hello, I would like to ask, when OpenFAST outputs blade node data, is it limited to a maximum of 9 nodes? If I want to output all nodes, what should I do?

**Comment by jjonkman** [comment]
Dear @TDmili,

While the blade-related outputs specified in the standard `OutList` are limited to 9 nodes, the nodal output functionality of the ElastoDyn, BeamDyn, and AeroDyn modules support outputs at all analysis nodes.  See the related documentation:

https://openfast.readthedocs.io/en/main/source/user/elastodyn/input.html#nodal-outputs
https://openfast.readthedocs.io/en/main/source/user/beamdyn/input_files.html#nodal-outputs
https://openfast.readthedocs.io/en/main/source/user/aerodyn/input.html#nodal-outputs

Best regards,
