### ISSUE TITLE
Issues with VTK naming

### ISSUE THREAD

**Issue by bjonkman** [OpenFAST/openfast#172]
I have noticed a few problems with the VTK file naming merged in https://github.com/OpenFAST/openfast/pull/126:
1. The width of the field used to add zero-padding is based on `DT_out` instead of `vtk_fps`. If you take the 5MW_Land_DLL_WTurb regression test, ask to output vtk files at 15 fps, and set DT_out to 1 or 10, you will change the width of the field and thus the number of vtk files that are generated. In the case DT_out = 10, I get files numbered 0-9 that get overwritten every 10 steps. Using something like `tWidth = log10( (p_FAST%n_TMax_m1+1) / p_FAST%n_VTKTime ) ) + 1` with appropriate type casting would work better.

2. `get_vtkroot_path()` and `get_vtkdir_path()` assume that path names must include the `PathSep` variable to parse where the new `vtk` directory should be created. This is not a valid assumption on Windows. It would be better to call `GetPath()` to determine the directory name instead of the simple logic implemented in those routines.  For example, if I run the command `openfast.exe 5MW_Land_DLL_WTurb/5MW_Land_DLL_WTurb.fst`, it creates a `.\vtk` directory, then tries to write to `.\5MW_Land_DLL_WTurb\vtk`. If that directory doesn't exist, no vtk files get written.

**Comment by rafmudaf** [comment]
Hi Bonnie,

To your first point, good catch. I've updated that locally and will issue a pull request soon.

On your second point, the vtk directory path is based on the output file root, `p_FAST%OutFileRoot`, so in the use case you mentioned the vtk directory should be located in the same directory as `5MW_Land_DLL_WTurb.out`. On Windows, is the `.out` file created in the directory containing the `.fst` file?

Thanks for the feedback and help!

Rafael

**Comment by bjonkman** [comment]
The `.out` file and the `.fst` file are in the same location on Windows, just like other operating systems.
I am just saying the way the `last_separator_index` is currently calculated is not sufficient for Windows systems. 

Windows doesn't care if you use `\` or `/` in a path name, so `p_FAST%OutFileRoot` may contain _either or both_ of those characters to separate directory names. However, the current OpenFAST logic assumes it will only contain `\` when it looks for the last path separator.

Also, if you _do_ pass a path name with a '/' character on Windows, the `mkdir` command will need the path name in quotes. Otherwise, it will give you an error about syntax (though you might not see it because there is no error checking in the OpenFAST MKDIR routine).

**Comment by jjonkman** [comment]
Fixed by #194.
