### ISSUE TITLE
Test case #18 modification - strange behaviour in region 2.5 and 3

### ISSUE THREAD

**Issue by uniqueusername-sahil** [OpenFAST/openfast#1735]
Hello,

I have made a modification of test #18, in which the input wind speed file is turbulent with a mean speed of 12m/s. the simulation completes without error, but I am suspecting that the controller is not transitioning OK between region 2.5 and 3. I have done my best to set the intial rotor speed and blade pitch in the elastodyn such that the initial oscillations are minimised. I have made use on the graphs on page 32 in this doc
https://www.nrel.gov/docs/fy09osti/38060.pdf
(side question: are the csv data for these figures available somewhere?)

Here is the input wind speed, and I have coloured in red the points where I am noticing the problem:-
![image](https://github.com/OpenFAST/openfast/assets/124084990/80b2db9e-40b6-4bfe-856c-b9c5119ec87d)
The grey line above is a wind speed of 11.3 m/s which I think is the boundary between region 2.5 and 3.

I have marked out these points because the blade pitch is zero, where I believe it should not be the case. I believe that the pitch controller should be trimming to keep the rotor speed up. Here is the blade pitch:-
![image](https://github.com/OpenFAST/openfast/assets/124084990/ed2fcb8d-04ca-4fb6-95b8-ab24a70daee2)

and rotor speed:-
![image](https://github.com/OpenFAST/openfast/assets/124084990/844a0a49-557a-4e4b-bd69-fea1d1663603)

and active power:-
![image](https://github.com/OpenFAST/openfast/assets/124084990/25eb256f-fec6-4b80-871f-2b707dd7fc76)

I am trying to plot the power curve (from simulated data, not the specification), and this weird behaviour especially around the 20 second mark is not easy for me to understand. The first ten seconds could be down to my initial conditions not being OK, but the turbine seems to stabilise, and then do this weird dip around 20 seconds.

Am I doing something wrong in the setup? Or is it just a bad idea to try and simulate turbulence near to a region boundary (2.5 to 3)?

Thanks,
Sahil

**Comment by uniqueusername-sahil** [comment]
Hi @jjonkman ,

Thanks very much for sharing the data, and recommendation.

The situation is broadly the same. See below figures re-plotted after applying the recommended initial conditions:-
![image](https://github.com/OpenFAST/openfast/assets/124084990/48aa29d2-79b5-48b4-ad51-69afa452b70e)
Above we see that the pitch controller quickly puts the pitch down to zero anyway, and around the 20 second mark the behaviour is the same as in the original plot.

Rotor speed also does not have much different to say.
![image](https://github.com/OpenFAST/openfast/assets/124084990/42861aba-aef7-4175-962c-de14f6694611)

Nor the active power.
![image](https://github.com/OpenFAST/openfast/assets/124084990/d20c6676-b9c6-44a9-b4b5-800f75fe19bf)

Thank you so much for your help and guidance. Let me know if you wish me to attach the simulation input files, or see any specific exerpt.

Thanks,
Sahil

**Comment by jjonkman** [comment]
I don't see anything out of the ordinary in your results once the start-up transient is passed.  I'll go ahead and close this issue.

Best regards,

**Comment by uniqueusername-sahil** [comment]
Can you please help me to understand why around the 20 second mark the active power drops to around 3500kW, despite the fact that the wind speed in the same time is around 13 m/s? Refer to the original figures for the input wind speed.

Thanks,

**Comment by jjonkman** [comment]
The baseline controller for the NREL 5-MW turbine does not have direct knowledge of the wind speed; rather, it uses rotor speed as an input.  The rotor speed and blade-pitch have dropped, so, the controller believes the wind turbine is in Region 2 (below rated), hence power has dropped accordingly.

**Comment by uniqueusername-sahil** [comment]
That makes sense, I think I saw something similar in the ROSCO paper. My next question is since the controller manages the blade pitch, why would it reduce the pitch? And isn't the reducing rotor speed a function of the reducing pitch?

**Comment by jjonkman** [comment]
Blades are pitched to feather to reduce aerodynamic torque, so, increasing pitch should lead to reduced speed when the generator torque is constant. But the generator torque is also varying with rotor speed.

**Comment by uniqueusername-sahil** [comment]
Thanks @jjonkman  for your time and effort. I have plotted the gen torque below
![image](https://github.com/OpenFAST/openfast/assets/124084990/d489abfb-ac12-452b-816e-c67ed437e6ae)

here we can see the gen torque is increasing as you expected. If I understood well, then that is what is causing the pitch controller to feather down to zero, at which point the control region changes and the torque controller reduces the torque and consequently active power.

In fact we can also see the same situation is starting to come around the 60 second mark where the simulation has terminated.
