### ISSUE TITLE
FATAL ERROR 

### ISSUE THREAD

**Issue by Chen1995SYSU** [OpenFAST/openfast#1736]
Dear Jason，

I received the following error when trying to use the FAST.Farm. File Settings and errors are as follows, I have checked, but did not find what went wrong.  Can you give me some advice?

------- FAST.Farm for OpenFAST INPUT FILE -------------------------------------------------
FAST.Farm input file, using two turbines separated by 3D downstream and an offset of 30m, turbulent inflow, yaw maneuver for WT1
--- SIMULATION CONTROL ---
False              Echo               - Echo input data to <RootName>.ech? (flag)
FATAL              AbortLevel         - Error level when simulation should abort (string) {"WARNING", "SEVERE", "FATAL"}
2000.0             TMax               - Total run time (s) [>=0.0]
False              UseSC              - Use a super controller? (flag)
2                  Mod_AmbWind        - Ambient wind model (-) (switch) {1: high-fidelity precursor in VTK format, 2: one InflowWind module, 3: multiple instances of InflowWind module}
2                  Mod_WaveField      - Wave field handling (-) (switch) {1: use individual HydroDyn inputs without adjustment, 2: adjust wave phases based on turbine offsets from farm origin}
0                  Mod_SharedMooring  - Shared mooring system model (switch) {0: None, 3=MoorDyn}}
--- SUPER CONTROLLER --- [used only for UseSC=True]
"unused"           SC_FileName        - Name/location of the dynamic library {.dll [Windows] or .so [Linux]} containing the Super Controller algorithms (quoated string)
--- SHARED MOORING SYSTEM --- [used only for Mod_SharedMoor>0]
""                 SharedMoorFile     - Name of file containing shared mooring system input parameters (quoted string) [used only when Mod_SharedMooring > 0]
0.04	           DT_Mooring         - Time step for farm-level mooring coupling with each turbine (s) [used only when Mod_SharedMooring > 0]
--- AMBIENT WIND: PRECURSOR IN VTK FORMAT --- [used only for Mod_AmbWind=1]
1.0                DT_Low-VTK         - Time step for low -resolution wind data input files; will be used as the global FAST.Farm time step (s) [>0.0]
0.1                DT_High-VTK        - Time step for high-resolution wind data input files (s) [>0.0]
"unused"           WindFilePath       - Path name to VTK wind data files from precursor (string)
False              ChkWndFiles        - Check all the ambient wind files for data consistency? (flag)
--- AMBIENT WIND: INFLOWWIND MODULE --- [used only for Mod_AmbWind=2 or 3]
0.8                DT_Low             - Time step for low -resolution wind data interpolation; will be used as the global FAST.Farm time step (s) [>0.0]
0.1                DT_High            - Time step for high-resolution wind data interpolation (s) [>0.0]
400                NX_Low             - Number  of low -resolution spatial nodes in X direction for wind data interpolation (-) [>=2]
100                NY_Low             - Number  of low -resolution spatial nodes in Y direction for wind data interpolation (-) [>=2]
35                 NZ_Low             - Number  of low -resolution spatial nodes in Z direction for wind data interpolation (-) [>=2]
-126               X0_Low             - Origin  of low -resolution spatial nodes in X direction for wind data interpolation (m)
-500.0             Y0_Low             - Origin  of low -resolution spatial nodes in Y direction for wind data interpolation (m)
5.0                Z0_Low             - Origin  of low -resolution spatial nodes in Z direction for wind data interpolation (m)
15                 dX_Low             - Spacing of low -resolution spatial nodes in X direction for wind data interpolation (m) [>0.0]
10.0               dY_Low             - Spacing of low -resolution spatial nodes in Y direction for wind data interpolation (m) [>0.0]
10.0               dZ_Low             - Spacing of low -resolution spatial nodes in Z direction for wind data interpolation (m) [>0.0]
36                 NX_High            - Number  of high-resolution spatial nodes in X direction for wind data interpolation (-) [>=2]
34                 NY_High            - Number  of high-resolution spatial nodes in Y direction for wind data interpolation (-) [>=2]
34                 NZ_High            - Number  of high-resolution spatial nodes in Z direction for wind data interpolation (-) [>=2]
"NRELOffshrBsline5MW_InflowWind_Steady8mps.dat"           InflowFile         - Name of file containing InflowWind module input parameters (quoted string)
--- WIND TURBINES ---
3                  NumTurbines        - Number of wind turbines (-) [>=1]                         [last 6 columns below used only for Mod_AmbWind=2 or 3]
WT_X    WT_Y   WT_Z   WT_FASTInFile     X0_High  Y0_High  Z0_High  dX_High  dY_High  dZ_High
(m)     (m)    (m)    (string)          (m)      (m)      (m)      (m)      (m)      (m)
  0.0   0.0    0.0    "5MW_OC4Semi_WSt_WavesWN1.fst"   -63   -85.0   5.0      5    5     5
630.0   0.0    0.0    "5MW_OC4Semi_WSt_WavesWN2.fst"   567   -85.0   5.0      5    5     5
1260.0  0.0    0.0    "5MW_OC4Semi_WSt_WavesWN3.fst"   1197   -85.0   5.0      5    5     5
--- WAKE DYNAMICS ---
1                  Mod_Wake           - Switch between wake formulations {1:Polar, 2:Curl, 3:Cartesian} (-) (switch)
5.0                dr                 - Radial increment of radial finite-difference grid (m) [>0.0]
40                 NumRadii           - Number of radii in the radial finite-difference grid (-) [>=2]
1200               NumPlanes          - Number of wake planes (-) [>=2]
0.08               f_c                - Cutoff (corner) frequency of the low-pass time-filter for the wake advection, deflection, and meandering model [recommended=1.28*U0/R] (Hz) [>0.0]

ERROR：
T2:FARM_UpdateStates:FWrap_Increment:FAST_Solution:CalcOutputs_And_SolveForInputs:SolveOption2:AD_
CalcOutput:RotCalcOutput:BEMT_CalcOutput(node 5, blade
3):UA_CalcOutput:UA_BlendSteady:Temporarily turning off UA due to high angle of attack or low
relative velocity. This warning will not be repeated though the condition may persist.
 Time: 51 of 2000 seconds.  Estimated final completion at 17:07:47.
The BEM solution is being turned off due to low TSR.  (TSR = 1.9982). This warning will not be
 Time: 87 of 2000 seconds.  Estimated final completion at 18:16:34.

T2:FARM_UpdateStates:FWrap_Increment:FAST_Solution:FAST_AdvanceStates:AD_UpdateStates:BEMT_UpdateS
tates:UpdatePhi(node 9, blade 2):BEMT_UnCoupledSolve:There is no valid value of phi for these
operating conditions: Vx = 3.7991, Vy = -28.02, rlocal = 28.125, theta = 0.13605, geometric phi =
3.0068. This warning will not be repeated though the condition may persist. (See GeomPhi output
channel.)
 Time: 121 of 2000 seconds.  Estimated final completion at 18:06:55.

T2:FARM_UpdateStates:FWrap_Increment:FAST_Solution:CalcOutputs_And_SolveForInputs:SolveOption2:AD_
CalcOutput:RotCalcOutput:BEMT_CalcOutput(node 19, blade 3):UA_CalcOutput:Mach number exceeds 0.3.
Theory is invalid. This warning will not be repeated though the condition may persist.
T3:FARM_UpdateStates:FWrap_Increment:FAST_Solution:CalcOutputs_And_SolveForInputs:SolveOption2:AD_
CalcOutput:RotCalcOutput:BEMT_CalcOutput(node 5, blade
1):UA_CalcOutput:UA_BlendSteady:Temporarily turning off UA due to high angle of attack or low
relative velocity. This warning will not be repeated though the condition may persist.
 Time: 126 of 2000 seconds.  Estimated final completion at 18:09:31.
The BEM solution is being turned off due to low TSR.  (TSR = 1.998). This warning will not be
 Time: 175 of 2000 seconds.  Estimated final completion at 19:56:46.

T3:FARM_UpdateStates:FWrap_Increment:FAST_Solution:FAST_AdvanceStates:AD_UpdateStates:BEMT_UpdateS
tates:UpdatePhi(node 9, blade 3):BEMT_UnCoupledSolve:There is no valid value of phi for these
operating conditions: Vx = 5.3311, Vy = -38.062, rlocal = 28.125, theta = 0.13605, geometric phi
= 3.0024. This warning will not be repeated though the condition may persist. (See GeomPhi output
channel.)
 Time: 194 of 2000 seconds.  Estimated final completion at 19:25:46.

T3:FARM_UpdateStates:FWrap_Increment:FAST_Solution:CalcOutputs_And_SolveForInputs:SolveOption2:AD_
CalcOutput:RotCalcOutput:BEMT_CalcOutput(node 19, blade 1):UA_CalcOutput:Mach number exceeds 0.3.
Theory is invalid. This warning will not be repeated though the condition may persist.
 Time: 204 of 2000 seconds.  Estimated final completion at 19:34:03.

T2:FARM_UpdateStates:NearWakeCorrection:Wake model is not valid in the propeller-brake region,
i.e., Ct > 2.0.

 Aborting FAST.Farm.

**Comment by clun1** [comment]
I'd like to know how you solved this problem?

**Comment by jjonkman** [comment]
Dear @clun1,

Are you receiving a similar error running FAST.Farm?  If so, what are you FAST.Farm input file settings?

Best regards,

**Comment by hhh850** [comment]
Dear  @jjonkman 
         I am using FAST. FARM to calculate three fans in series.  The operation works correctly when the yaw angle of the first fan is set to 0°, 10°, and 15°.  However, I encounter issues when the yaw angle is set to 20°.  I cannot identify the problem.  Could you please provide some suggestions?
         
------------------------------------------------------------------------------------------------------------------------------------
     FAST.Farm v1.00.* INPUT FILE
Sample FAST.Farm input file
--- SIMULATION CONTROL ---
False              Echo               Echo input data to <RootName>.ech? (flag)
FATAL              AbortLevel         Error level when simulation should abort (string) {"WARNING", "SEVERE", "FATAL"}
2000.0               TMax               Total run time (s) [>=0.0]
False              UseSC              Use a super controller? (flag)
2                  Mod_AmbWind        Ambient wind model (-) (switch) {1: high-fidelity precursor in VTK format, 2: one InflowWind module, 3: multiple instances of InflowWind module}
--- SUPER CONTROLLER --- [used only for UseSC=True]
"SC_DLL.dll"       SC_FileName        Name/location of the dynamic library {.dll [Windows] or .so [Linux]} containing the Super Controller algorithms (quoated string)
--- AMBIENT WIND: PRECURSOR IN VTK FORMAT --- [used only for Mod_AmbWind=1]
3.0                DT_Low-VTK         Time step for low -resolution wind data input files  ; will be used as the global FAST.Farm time step (s) [>0.0]
0.1                DT_High-VTK        Time step for high-resolution wind data input files   (s) [>0.0]
"unused"           WindFilePath       Path name to VTK wind data files from precursor (string)
False              ChkWndFiles        Check all the ambient wind files for data consistency? (flag)
--- AMBIENT WIND: INFLOWWIND MODULE --- [used only for Mod_AmbWind=2 or 3]
3.0                DT_Low             Time step for low -resolution wind data interpolation; will be used as the global FAST.Farm time step (s) [>0.0]
0.1                DT_High            Time step for high-resolution wind data interpolation (s) [>0.0]
301                NX_Low             Number  of low -resolution spatial nodes in X direction for wind data interpolation (-) [>=2]
101                NY_Low             Number  of low -resolution spatial nodes in Y direction for wind data interpolation (-) [>=2]
35                 NZ_Low             Number  of low -resolution spatial nodes in Z direction for wind data interpolation (-) [>=2]
-315.0             X0_Low             Origin  of low -resolution spatial nodes in X direction for wind data interpolation (m)
-500.0             Y0_Low             Origin  of low -resolution spatial nodes in Y direction for wind data interpolation (m)
5.0                Z0_Low             Origin  of low -resolution spatial nodes in Z direction for wind data interpolation (m)
10.0               dX_Low             Spacing of low -resolution spatial nodes in X direction for wind data interpolation (m) [>0.0]
10.0               dY_Low             Spacing of low -resolution spatial nodes in Y direction for wind data interpolation (m) [>0.0]
10.0               dZ_Low             Spacing of low -resolution spatial nodes in Z direction for wind data interpolation (m) [>0.0]
17                 NX_High            Number  of high-resolution spatial nodes in X direction for wind data interpolation (-) [>=2]
16                 NY_High            Number  of high-resolution spatial nodes in Y direction for wind data interpolation (-) [>=2]
16                 NZ_High            Number  of high-resolution spatial nodes in Z direction for wind data interpolation (-) [>=2]
"InflowWind.dat"   InflowFile         Name of file containing InflowWind module input parameters (quoted string)
--- WIND TURBINES ---
3                  NumTurbines        Number of wind turbines (-) [>=1]                          [last 6 columns below used only for Mod_AmbWind=2 or 3]
WT_X    WT_Y   WT_Z   WT_FASTInFile     X0_High  Y0_High  Z0_High  dX_High  dY_High  dZ_High
(m)     (m)    (m)    (string)          (m)      (m)      (m)      (m)      (m)      (m)
0.0     0.0    0.0    "FFTest_WT1.fst"   -85     -85.0    5.0     10.63    10.67     10.67
630.0   0.0    0.0    "FFTest_WT2.fst"   545     -85.0    5.0     10.63    10.67     10.67
1260.0  0.0    0.0    "FFTest_WT3.fst"  1175     -85.0    5.0     10.63    10.67     10.67
--- WAKE DYNAMICS ---
5.0                dr                 Radial increment of radial finite-difference grid (m) [>0.0]
40                 NumRadii           Number of radii in the radial finite-difference grid (-) [>=2]
136                NumPlanes          Number of wake planes (-) [>=2]
DEFAULT            f_c                Cutoff (corner) frequency of the low-pass time-filter for the wake advection, deflection, and meandering model (Hz) [>0.0] or DEFAULT [DEFAULT=0.0007]
DEFAULT            C_HWkDfl_O         Calibrated parameter in the correction for wake deflection defining the horizontal offset at the rotor                                               (m    ) or DEFAULT [DEFAULT= 0.0  ]
DEFAULT            C_HWkDfl_OY        Calibrated parameter in the correction for wake deflection defining the horizontal offset at the rotor scaled with                         yaw error (m/deg) or DEFAULT [DEFAULT= 0.3  ]
DEFAULT            C_HWkDfl_x         Calibrated parameter in the correction for wake deflection defining the horizontal offset              scaled with downstream distance               (-    ) or DEFAULT [DEFAULT= 0.0  ]
DEFAULT            C_HWkDfl_xY        Calibrated parameter in the correction for wake deflection defining the horizontal offset              scaled with downstream distance and yaw error (1/deg) or DEFAULT [DEFAULT=-0.004]
DEFAULT            C_NearWake         Calibrated parameter for the near-wake correction (-) [>1.0 and <2.5] or DEFAULT [DEFAULT=1.8]
DEFAULT            k_vAmb             Calibrated parameter for the influence of ambient turbulence in the eddy viscosity (-) [>=0.0] or DEFAULT [DEFAULT=0.05 ]
DEFAULT            k_vShr             Calibrated parameter for the influence of the shear layer    in the eddy viscosity (-) [>=0.0] or DEFAULT [DEFAULT=0.016]
DEFAULT            C_vAmb_DMin        Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the transitional diameter fraction between the minimum and exponential regions (-) [>=0.0          ] or DEFAULT [DEFAULT= 0.0 ]
DEFAULT            C_vAmb_DMax        Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the transitional diameter fraction between the exponential and maximum regions (-) [> C_vAmb_DMin  ] or DEFAULT [DEFAULT= 1.0 ]
DEFAULT            C_vAmb_FMin        Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the value in the minimum region                                                (-) [>=0.0 and <=1.0] or DEFAULT [DEFAULT= 1.0 ]
DEFAULT            C_vAmb_Exp         Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the exponent in the exponential region                                         (-) [> 0.0          ] or DEFAULT [DEFAULT= 0.01]
DEFAULT            C_vShr_DMin        Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the transitional diameter fraction between the minimum and exponential regions (-) [>=0.0          ] or DEFAULT [DEFAULT= 3.0 ]
DEFAULT            C_vShr_DMax        Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the transitional diameter fraction between the exponential and maximum regions (-) [> C_vShr_DMin  ] or DEFAULT [DEFAULT=25.0 ]
DEFAULT            C_vShr_FMin        Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the value in the minimum region                                                (-) [>=0.0 and <=1.0] or DEFAULT [DEFAULT= 0.2 ]
DEFAULT            C_vShr_Exp         Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the exponent in the exponential region                                         (-) [> 0.0          ] or DEFAULT [DEFAULT= 0.1 ]
DEFAULT            Mod_WakeDiam       Wake diameter calculation model (-) (switch) {1: rotor diameter, 2: velocity based, 3: mass-flux based, 4: momentum-flux based} or DEFAULT [DEFAULT=1]
DEFAULT            C_WakeDiam         Calibrated parameter for wake diameter calculation (-) [>0.0 and <0.99] or DEFAULT [DEFAULT=0.95] [unused for Mod_WakeDiam=1]
DEFAULT            Mod_Meander        Spatial filter model for wake meandering (-) (switch) {1: uniform, 2: truncated jinc, 3: windowed jinc} or DEFAULT [DEFAULT=3]
DEFAULT            C_Meander          Calibrated parameter for wake meandering (-) [>=1.0] or DEFAULT [DEFAULT=1.9]


-----------------------------------------------------------------------------------------------------------------------------

Time: 504 of 2000 seconds.  Estimated final completion at 16:24:17.                              
 FARM_CalcOutput:AWAE_CalcOutput:LowResGridCalcOutput:The center of wake plane #125 for turbine #1
 has passed the upper-most X boundary of the low-resolution domain.
 LowResGridCalcOutput:The center of wake plane #126 for turbine #1 has passed the upper-most X
 boundary of the low-resolution domain.
 LowResGridCalcOutput:The center of wake plane #127 for turbine #1 has passed the upper-most X
 boundary of the low-resolution domain.
 LowResGridCalcOutput:The center of wake plane #128 for turbine #1 has passed the upper-most X
 boundary of the low-resolution domain.
 LowResGridCalcOutput:The center of wake plane #129 for turbine #1 has passed the upper-most X
 boundary of the low-resolution domain.
 LowResGridCalcOutput:The center of wake plane #130 for turbine #1 has passed the upper-most X
 boundary of the low-resolution domain.
 LowResGridCalcOutput:The center of wake plane #131 for turbine #1 has passed the upper-most X
 boundary of the low-resolution domain.
 LowResGridCalcOutput:The center of wake plane #132 for turbin

  Time: 507 of 2000 seconds.  Estimated final completion at 16:23:33.                              
 T3:FARM_UpdateStates:NearWakeCorrection:Wake model is not valid in the propeller-brake region,
 i.e., Ct > 2.0.


  Aborting FAST.Farm.

**Comment by jjonkman** [comment]
Dear @hhh850 ,

This error is stating that the disk-averaged rotor thrust coefficient is greater than 2, where the near-wake correction in FAST.Farm is invalid. A rotor thrust coefficient greater than 2 is quite unexpected. I would guess the wind turbines are not operating as expected based on an incorrect setting in the FAST.Farm or OpenFAST input files. How do the wind speed, rotor speed, and blade pitch angles look for each turbine as output from OpenFAST up until the simulation failure?

Best regards,
