### ISSUE TITLE
Calculation of relative wind speed and angle of attack on blades

### ISSUE THREAD

**Issue by Zheng-Haojie** [OpenFAST/openfast#1739]
Hello everyone！
Using AeroDyn, we can calculate the relative wind speed and angle of attack of the determined nodes on the blades of a 5MW reference wind turbine. But if I want to know the relative wind speed and angle of attack between two nodes, how should I calculate it? Can I take the average value between two nodes?For example, calculating the relative velocity and angle of attack at the midpoint of nodes 8 and 9（A）.
![image](https://github.com/OpenFAST/openfast/assets/110016796/af7c2d7e-46b9-45e8-a771-b643e1fe273f)
In addition, in the operation of wind farms, in order to cope with extreme weather, people sometimes actively reduce the TSR of wind turbine blades. How will the pitch angle, relative wind speed at each node, and angle of attack change in this situation? How should I set it in Openfast?
![image](https://github.com/OpenFAST/openfast/assets/110016796/18031572-d478-40d3-9139-1c986a5cfacb)
Thank you very much.

**Comment by jjonkman** [comment]
Dear @Zheng-Haojie,

Depending on the aerodynamic discretization of the blade, linear interpolation between nodes could be satisfactory.  Of course, you can always define analysis nodes in AeroDyn wherever you want, so, such interpolation is not needed if you place the analysis nodes appropriate to your needs apriori.

I'm not sure I understand your second question.

Best regards,

**Comment by Zheng-Haojie** [comment]
Thank you very much for your answer. Sorry I didn't make the second question clear.
The second question I mainly want to know is whether TSR or rotational speed can be manually assigned a fixed value in FAST. I would also like to know how FFAST achieves this fixation, by giving a change in pitch angle?
Thank you for your wonderful answers on the forum!

**Comment by jjonkman** [comment]
Dear @Zheng-Haojie,

If you want to simulate with steady-state conditions, you can force a fixed TSR in OpenFAST by disabling the generator degree of freedom (`GenDOF` = FALSE in ElastoDyn) and using steady wind (`WindType `= 1) with a user-specified rotor speed (`RotSpeed` in ElastoDyn) and wind speed (`HWindSpeed` in InflowWind).

If you want to simulate dynamic conditions with turbulent inflow and want a given TSR, you must specify a controller (in ServoDyn), but the TSR will have some level of variation depending on the aggressiveness of the controller you are using.

Best regards,

**Comment by Zheng-Haojie** [comment]
Thank you for your answer! Simulation in steady state is just what I need.
