### ISSUE TITLE
Using OpenFAST on Simulink

### ISSUE THREAD

**Issue by Mojallizadeh** [OpenFAST/openfast#1740]
Hello everyone,

I would like to use OpenFAST on Simulink but I have the following problems. I just want to run the example OpenLoop available in the repository. Note that I don't have any problem on Windows and the problem is just on Linux Ubuntu.

I tried it with Ubuntu using my own compilation on GCC however I get the following error:

> Error using Run_OpenLoop
> Error while obtaining sizes from MEX S-function 'FAST_SFunc' in 'OpenLoop/FAST Nonlinear Wind
> Turbine/S-Function'. Note that I tried different versions of OpenFAST including the current, 3 and 2.6 however, I always got the same error.
> 
> Error in run (line 91)
> evalin('caller', strcat(script, ';')); - Show complete stack trace
> Caused by:
>     Error using Run_OpenLoop
>     Invalid MEX-file '/media/sf_Shared/git_projects/Ver 2.6/openfast/install/lib/FAST_SFunc.mexa64':
>     /media/sf_Shared/git_projects/Ver 2.6/openfast/install/lib/FAST_SFunc.mexa64: undefined symbol:
>     __openfoam_types_MOD_opfm_packinitoutput - Show complete stack trace

I read all the instructions online and spent two weeks but I couldn't solve the problem.
MATLAB 2023a
GCC latest

**Comment by deslaughter** [comment]
@Mojallizadeh Please try with https://github.com/OpenFAST/openfast/tree/rc-3.5.1 until version 3.5.1 is released. There were several changes made in that branch to get the Simulink build working on Linux. Note that you do not need to use the `create_FAST_SFunc.m` to build the mex file, it will be generated in `build/glue-codes/simulink` when building with CMake.

**Comment by deslaughter** [comment]
Closing due to lack of response, feel free to reopen if the rc-3.5.1 didn't resolve your issue.
