### ISSUE TITLE
How to run r-test-module-aerodyn test

### ISSUE THREAD

**Issue by YangLeiTH** [OpenFAST/openfast#1741]
Dear @jjonkman,

I found the input driver file in the r-test-module-aerodyn folder is different from the driver file downloaded from the NREL Aerodyn15 CertTest. I failed to run the driver file in the r-test-module-aerodyn folder with AeroDyn_Driver_x64.exe. What executable file I should use to run the driver file in the r-test-module-aerodyn folder?

Best regards,

**Comment by jjonkman** [comment]
A similar question was recently asked and answered on our forum: https://forums.nrel.gov/t/error-running-standalone-aerodyn-driver-for-dynamic-bemt/5524.

**Comment by YangLeiTH** [comment]
Hi @jjonkman,

Following your answering, I have got a new version of AeroDyn driver executable file compiling from the source code, then the problem is solved. Thank you!

Best regards,
