### ISSUE TITLE
Wind turbines do not stop at cut-out speeds.

### ISSUE THREAD

**Issue by calcin** [OpenFAST/openfast#1742]
Dear all,
I have a problem when using a 5mw wind turbine, when I increase the wind speed to 29m/s, I see that the RPM is not 0 in the simulation results, under normal circumstances, when the wind turbine is in the cut out wind speed, shouldn't the wind turbine be undergoing a pitch stop condition? Here are my result graphs for 29m/s 40m/s 50m/s I only set their wind speed and initial pitch angle, other parameters are defaulted and the initial pitch angle is 90 degrees.
![1](https://github.com/OpenFAST/openfast/assets/111359446/b844e6b8-19cb-4d09-ac8f-3af3b03dcf4d)
![2](https://github.com/OpenFAST/openfast/assets/111359446/966d766a-298b-4713-bd3f-2e5cbc66b2ce)
![3](https://github.com/OpenFAST/openfast/assets/111359446/7ee7fe18-7f57-4d72-9fd1-59f8247af3c4)
If I missed some settings. Please help point out the mistakes, thank you very much. By the way, the math I'm using is 5MW_Land_DLL_WTurb

**Comment by jjonkman** [comment]
Dear @calcin,

The baseline controller for the OpenFAST model of the NREL 5-MW baseline wind turbine available in the OpenFAST r-test (https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast/5MW_Land_DLL_WTurb) only includes logic for normal operation.  This controller will not initiate a shut down of the rotor at high wind speeds.  You'll have to implement your own shutdown control logic or switch to a different reference controller (such as ROSCO: https://github.com/NREL/ROSCO) if you need to simulate shutdown transient events.

Best regards

**Comment by calcin** [comment]
Dear @jjonkman 
Thank you for your reply, another query solved for me, much appreciated, have a nice life.
