### ISSUE TITLE
Mass and stiffness information from ANSYS

### ISSUE THREAD

**Issue by YangLeiTH** [OpenFAST/openfast#1751]
Hi @jjonkman 

I recently came across the official manual for OC4 and inferred that you obtained the mass and stiffness information for the OC4 blades, hub, nacelle, tower, and platform through ANSYS modeling. I am writing to inquire if it would be possible for you to share this ANSYS model with me.

Best regards,
Lei Yang

**Comment by jjonkman** [comment]
Dear @YangLeiTH,

Are you referring to the OC4-DeepCwind semisubmersible?  I'm aware that an ANSYS model of this semisubmersible (not the including the supported NREL 5-MW baseline wind turbine) was developed at some point, but I'm not aware of its availability.

Best regards,

**Comment by YangLeiTH** [comment]
Thank you!
