### ISSUE TITLE
Design question regarding Fast.farm offshore wind turbines

### ISSUE THREAD

**Issue by DingZL1207** [OpenFAST/openfast#1753]
I would like to design a wind turbine model myself. Does the user manual contain tutorials on this topic, such as designing blade length, size, and other related parameters?Can relevant software, such as Turbsim, be used to generate blade and wind turbine tower files similar to generating turbulent wind field files?
I am a beginner, and I sincerely appreciate your assistance!

**Comment by jjonkman** [comment]
Dear @DingZL1207,

This OpenFAST repository is useful if you have a given wind turbine of known properties that you want to simulate across a range of load cases.  There is nothing in the OpenFAST repository that directly supports wind turbine sizing and design optimization.  For the latter, I would refer you to NREL's wind turbine design optimization and sizing software such as WISDEM and WEIS: https://github.com/WISDEM.  Of course, these software make use of OpenFAST for load-case simulations, so, the tools are interrelated.

TurbSim can be used to generate full-field turbulent inflow for use in OpenFAST, but does not support defining the aerodynamic or structural properties of blades and towers.

Best regards,

**Comment by DingZL1207** [comment]
Thank you so much！

---- Replied Message ----
| From | ***@***.***> |
| Date | 08/31/2023 02:58 |
| To | OpenFAST/openfast ***@***.***> |
| Cc | DingZL1207 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [OpenFAST/openfast] Design question regarding Fast.farm offshore wind turbines (Issue #1753) |

Dear @DingZL1207,

This OpenFAST repository is useful if you have a given wind turbine of known properties that you want to simulate across a range of load cases. There is nothing in the OpenFAST repository that directly supports wind turbine sizing and design optimization. For the latter, I would refer you to NREL's wind turbine design optimization and sizing software such as WISDEM and WEIS: https://github.com/WISDEM. Of course, these software make use of OpenFAST for load-case simulations, so, the tools are interrelated.

TurbSim can be used to generate full-field turbulent inflow for use in OpenFAST, but does not support defining the aerodynamic or structural properties of blades and towers.

Best regards,
