### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by anishas26** [OpenFAST/openfast#1754]
**Bug description**
I am trying to install OpenFAST through conda-forge. I created a new environment and activated it. Then ran the install command and it says

BEGINNING OF ERROR
PackagesNotFoundError: the following packages are not available from current channels: -openfast

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
END OF ERROR

**To Reproduce**
conda create -n openfast_env
conda activate openfast_env
conda install -c conda-forge openfast #this is where the error above happens

Windows 10 pro OS
Using anaconda prompt

**Comment by deslaughter** [comment]
@anishas26 OpenFAST is not currently available for Windows from conda-forge. We hope to provide this in the future. Until we can get OpenFAST working with conda-forge, please download the Windows version from [Releases](https://github.com/OpenFAST/openfast/releases).

**Comment by deslaughter** [comment]
Closing due to lack of response, feel free to reopen.
