### ISSUE TITLE
Questions about Turbsim

### ISSUE THREAD

**Issue by sffgd** [OpenFAST/openfast#1770]
Hello, there is a question I would like to ask: Can Turbsim be used to simulate the generation of typhoon files? If you know, please let me know, thank you very much!

**Comment by jjonkman** [comment]
Dear @sffgd,

I guess that depends on what you mean.  If by "typhoon", you mean IEC load cases based on V_ref,T--that is, the reference wind speed specified in the IEC 61400-1 design standard for areas subject to tropical cyclones (typhoons/hurricanes), then the answer is "yes"; TurbSim can be used to generate wind data files that match the conditions called out in this standard.

TurbSim is also quite customizable by the user in that the user can specify their own wind profile (shear, veer), turbulence spectra (in U,V,W), and spatial coherence.  So, if you know what these should be for a given tropical cyclone (typhoon/hurricane) condition, you can use TurbSim to generate synthetic turbulence that matches those user-specified conditions.

But TurbSim does not have internal models that directly model the physics of tropical cyclone (typhoon/hurricane) conditions.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman，
Thank you very much for your answer, I am very grateful, your answer is very comprehensive and clear, as a newcomer to OpenFast, there are some doubts:
Question 1.I'm sorry I didn't understand what "V_ref,T" stands for, can you explain it for me if it's convenient for you?

Question 2.I am currently using the "IECKAI" turbulence model and want to know how different the generated wind file is from the real typhoon?

Question 3.If I use Turbsim to simulate a real typhoon, and then use openfast to study the aero-hydrodynamic-mooring fully coupled dynamic characteristics analysis of offshore wind turbines under the action of a typhoon, I don't know if this idea is feasible, if you can give some suggestions, I would be very grateful!

Question 4.As far as I know, we can now use WRF to simulate the typhoon path, if I use WRF to simulate the typhoon time history file will be very difficult for me, in question 3 mentioned that the acquisition of the measured typhoon file is very important, if there is an open source real typhoon time history wind file, please tell me, thank you very much!

Best regards,

**Comment by jjonkman** [comment]
Dear @sffgd,

Here are my responses:
1) I refer you to the IEC 61400-1 design standard for a clear definition of this variable and how it is used in design load case simulations.
2) I would say that there are likely differences between the synthetic wind generated by the Kaimal turbulence model and a real typhoon, but that probably depends on the specific situation.  I would suggest comparing the wind in terms of profile, spectra, coherence, etc.
3) OpenFAST can certainly be used to simulate the full system dynamic response of offshore wind turbines subject to wind inflow generated by TurbSim.
4) Julie Lundquist of CU-Boulder gave a really nice presentation yesterday regarding WRF-LES simulations of tropical cyclone events and their use to drive wind turbine structural loads (e.g., as announced here: https://www.linkedin.com/in/jakob-mann-b25a9345?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAmXu40BoZBxRXOdJjRpHQHZdWCIsc7BGnA&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_content%3BnIlafZIAQnaf61Gf0%2FjJPw%3D%3D).  I understand from Julie's presentation that the output from the WRF simulations are available, but I'm not familiar with the details.  I would suggest reaching out to her.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman,

Okay,Thanks for the answer， thanks a lot! 
According to your proposal, I will study further deeper

Best regards,
