### ISSUE TITLE
openfast/simulink

### ISSUE THREAD

**Issue by Viper19103** [OpenFAST/openfast#1772]
When running create FAST SFunc file, there is an error using mex, MEX can't find the library openfastlib_mex specified with the -l option, please verify that the name of the library is correct, and if the library doesn't exist on an existing path, please specify the path with the -L option.What's the solution?
![屏幕截图 2023-09-15 154415](https://github.com/OpenFAST/openfast/assets/145104308/07af1332-73bc-4297-9bd6-058d10a4652b)

**Comment by deslaughter** [comment]
Which platform (Windows, MacOS, or Linux) and compiler are you using?

**Comment by Viper19103** [comment]
Windows，visual studio2019,matlabR2021b

**Comment by deslaughter** [comment]
Did you set `built_with_visualStudio = true` in `create_FAST_SFunc.m` before running it? `libName` gets set to `openfastlib_mex` when the script thinks the library was built using CMake.

**Comment by Viper19103** [comment]
ok，i will try，thank you

**Comment by deslaughter** [comment]
Closing issue. Please reopen if you need additional help.

**Comment by TorbenKnudsen** [comment]
I have a similar problem but using ubuntu 22.04.
Below you what I tried and finally the error

cmake .. -DBUILD_OPENFAST_SIMULINK_API=off -DBUILD_SHARED_LIBS=on
make openfastlib
make install
This did give a file libopenfastlib.so in
/home/tk/OpenFAST/build/modules/openfast-library/
This did not give a file libopenfastlib.so in
/home/tk/OpenFAST/modules/openfast-library/

Running the create_FAST_SFunc I still get
----------------------------
Creating ./FAST_SFunc.mexa64

Building with 'gcc'.
Error using mex
/usr/bin/ld: cannot find -lopenfastlib_mex: No such file or directory
collect2: error: ld returned 1 exit status

Let me know if you need more information to help
