### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Tianyao314** [OpenFAST/openfast#1773]
**Bug description**

the program can be compiled under debug, but failed under release.

![image](https://github.com/OpenFAST/openfast/assets/55082013/2f196969-7aba-4eb9-bd9a-e9669f4d2d40)

I saw many users met this error, but there is not a certain method to sovle this.
error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FAST_SUBS]

**Comment by jjonkman** [comment]
Can you share the full text from your "output window" instead of the "error list"?

**Comment by andrew-platt** [comment]
Which branch are you trying to compile?

**Comment by Tianyao314** [comment]
> Can you share the full text from your "output window" instead of the "error list"?

Dear jjonkman

I successful compiled the program without any change of the code today, and I didn't meet the errors again. 

Although I don't know the reason, my problem has been solved. Thank you for your help.

Best regards,
Yao

**Comment by Tianyao314** [comment]
> Which branch are you trying to compile?

Dear andrew-platt

I compiled branch of rc-3.5.1, and I compiled it successfully.

thanks for your help.

Kind regards,
Yao
