### ISSUE TITLE
Bug report-Error when running the case "ad_QuadRotor_OLAF".

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1781]
Dear all, 

When I try to run the case "ad_QuadRotor_OLAF" from "https://github.com/OpenFAST/r-test/tree/main/modules/aerodyn/ad_QuadRotor_OLAF", an error occur:
![image](https://github.com/OpenFAST/openfast/assets/98078424/b94dcdf5-dcbc-4d41-9bb6-b4bf7dd34f07)
The version of the aerodyn.exe is 3.5.0, and I have also try some other version such as v3.3.0 and v3.1.0 with their corresponding r-test version, and all filed.

Thank you for your attention.

**Comment by andrew-platt** [comment]
How did you compile `aerodyn.exe`?  We didn't provide an executable in the 3.5.0 release, so I want to verify I can reproduce this issue with the same compilation method you used.

**Comment by andrew-platt** [comment]
I can confirm this issue exists in 3.5.0 and in the rc-3.5.1 branch.  Fixed in PR #1811.

@ZL6462, thanks for lettings us know about this issue!
