### ISSUE TITLE
Questions about the operation of ad_VerticalAxis_OLAF and Turbsim

### ISSUE THREAD

**Issue by engineerYuXN** [OpenFAST/openfast#1787]
Dear all
         I have built a vertical axis wind turbine with multiple rotors in ad_VerticalAxis_OLAF, and I want to use the turbulent wind generated by turbsim to do the calculations, but no matter how I change the size of the wind field (increase the area of the wind field or decrease the area of the wind field), I always get an error and stop the calculations around the middle of the calculations, and the specific error is reported as follows.
![aerodyn报错](https://github.com/OpenFAST/openfast/assets/87838413/3029e519-3b53-46a3-b716-7c088ac09f57)
The following diagram shows the relevant settings about the model
![22](https://github.com/OpenFAST/openfast/assets/87838413/d41e639b-33f1-4c64-b3a6-5d1f8873dce1)
The following diagram shows the relevant settings about the ad_driver.dvr
![33](https://github.com/OpenFAST/openfast/assets/87838413/8c033802-25a5-4712-b210-fba5093c4962)
![44](https://github.com/OpenFAST/openfast/assets/87838413/5d1e797d-6c24-446f-bca1-9c072708526c)
![55](https://github.com/OpenFAST/openfast/assets/87838413/21eafa25-8944-4ae0-8fb7-6ba6d89df97c)
![66](https://github.com/OpenFAST/openfast/assets/87838413/8faa24e3-61f0-49d3-927b-8893d1b514c2)
The following diagram shows the relevant settings about the Turbsim.inp
![77](https://github.com/OpenFAST/openfast/assets/87838413/be079dbf-905f-41ca-ba31-cfefbaa9bb09)
![88](https://github.com/OpenFAST/openfast/assets/87838413/ad75664a-ce0a-4dc3-9af5-8c4ca8c2eff5)
I hope you can give me some suggestions for improvement based on my input file and explain the reason for the error.

Thank your for your attention.
Best regards,

**Comment by engineerYuXN** [comment]
@jjonkman @ebranlard

**Comment by ebranlard** [comment]
Hi @engineerYuXN 

There has been a couple of bugs in InflowWind lately. I can see that you are using 3.4.1. If you can, try to compile the version for 3.5.1, which is in the branch rc-3.5.1 of this repository. 

You can also try to increase you TurbSim height, so that the box starts right above the gound (say 0.05m above the ground instead of 5m) . 
Let us know if that helps,

Emmanuel

**Comment by engineerYuXN** [comment]
Hi @ebranlard 
I used version 3.5.0 of turbsim to generate turbulence winds as you suggested, and I still get the following error
![111](https://github.com/OpenFAST/openfast/assets/87838413/8dce3c25-9e74-4163-a9b5-c8b3764b7ffd)
![222](https://github.com/OpenFAST/openfast/assets/87838413/2b9dd6c8-9ccf-4d58-95bc-13b3ad837d43)
I have made the following changes based on the relevant reported errors, but all of them result in errors
1. Add GridHeight and GridWidth.
2. Define HasTower, HubOrigin_n and TwrOrigin_t for the impeller.

Currently I still have the following problems
1. I'm not sure if I'm using the rc3.5.1 version as you said
2、I don't know how to modify it next, hope you can give me some suggestions!

Thank your for your attention.
Best regards

**Comment by ebranlard** [comment]
Hi, 
Indeed, you need to use the branch of OpenFAST called `rc3.5.1` and compile OpenFAST yourself. If you don't know how to do it, you can refer to the documentation, or wait one month or so until we officially release the version. Then binaries wil be available for donwload.

**Comment by engineerYuXN** [comment]
Hi @ebranlard
     But I'm using aerodyn, do I also need to use openfast version 3.5.1?

**Comment by jjonkman** [comment]
Dear @engineerYuXN,

I believe @ebranlard means that you should recompile the standalone AeroDyn driver using the source code from the rc-3.5.1 branch of the OpenFAST repository, available here: https://github.com/OpenFAST/openfast/tree/rc-3.5.1.

Best regards,

**Comment by engineerYuXN** [comment]
Dear @jjonkman 
       I have compiled aerodyn and turbsim in rc3.5.1 as you intended, below screenshot shows the version shown at runtime.
![微信截图_20230930233218](https://github.com/OpenFAST/openfast/assets/87838413/d9aefa93-9ea9-46c3-9478-42ab5f593ba7)
![微信截图_20230930233311](https://github.com/OpenFAST/openfast/assets/87838413/8f6e4634-18a1-461e-a917-10e112f16b46)
      However, with version 3.5.1, I still get a corresponding error, and when I adjust GridHeight and GridWidth to 2000m, I still get the Grid too small in Z or Y direction error
     
![微信截图_20230930233424](https://github.com/OpenFAST/openfast/assets/87838413/e1332bda-0107-4b35-ac73-61932c36b762)
    I hope you can give me some more help
Thank your for your attention.
Best regards

**Comment by engineerYuXN** [comment]
After I adjust the GridHeight and GridWidth to 4000m, I can calculate 9s in full, but there is no guarantee that I can calculate longer, and after outputting the VTK file I found a lot of vortex grids that flew far away, and I don't know if it's these flying scattering vortex grids that caused aerodyn to report the error.

<img width="1274" alt="屏幕截图 2023-10-01 162031" src="https://github.com/OpenFAST/openfast/assets/87838413/4278d3b5-12e3-4719-9a3b-0e86bd57d94b">

**Comment by ebranlard** [comment]
My guess is that your regularization parameters needs updating. You can try to follow the guidelines indicated here:
https://openfast.readthedocs.io/en/dev/source/user/aerodyn-olaf/RunningOLAF.html#guidelines
You likely need to increase them by a significatn factor.

**Comment by engineerYuXN** [comment]
Dear @ebranlard
I would like to ask you if there is any correlation between the settings of nNWPanels, nNWPanelsFree, nFWPanels, nFWPanelsFree in OLAF and GridHeight, GridWidth, NumGrid_Z, NumGrid_Y in Turbsim.

**Comment by engineerYuXN** [comment]
Dear @ebranlard
       Thank you very much for your reply to my question, it helps me a lot. I have another question at the moment, I do the calculations based on CFD software for the same environmental conditions and the same size model, and the RtAeroMxh, RtAeroMyh, RtAeroMzh outputs from the OLAF module are much larger than the CFD software (probably about 3 times), and I'd like to know the parameters affecting the torque and the RtAeroPwr values of the aerodynamic power, in addition to the model size, the number of panels, the simulation time step and so on, and what are the other parameters affecting the results in a big way.
       Thank your for your attention.
Best regards

**Comment by ebranlard** [comment]
Hi, 
The regularization and wake length are the most critical parameters. The guidelines should ensure that you are in the right range of values.  For VAWT the unsteady airfoil aerodynamics model (AFAeroMod=2) can also have a significant influence on the results (see e.g., this [article](https://wes.copernicus.org/articles/7/455/2022/)).  

A three fold factor seems excessive and there is likely something off with the model. I cannot give much more guidance than trying to follow the guidelines and adjust the parameters mentioned above (regularization and wake length). In the above mentioned article, we had fairly satisfactory results compared to the measurements.
