### ISSUE TITLE
using OpenFAST to study the effects of the prescribed platform motions on the performance of turbine rotors

### ISSUE THREAD

**Issue by ietqlw** [OpenFAST/openfast#1789]
Dear @jjonkman ,

I plan to use OpenFAST to study the effects of the prescribed platform motions on the performance of turbine rotors. The platform motions are expected to be decoupled from the tower and rotor. A prescribed manner such as sine wave requires to be exerted. 

Taking a prescribed sine-wave platform-pitching angle as a example (pitch angle= 5 + 3*cos(2*pi*0.0373*time) deg), I have several possible methods for this target:
(1) At the end of `SUBROUTINE ED_CalcContStateDeriv( t, u, p, x, xd, z, OtherState, m, dxdt, ErrStat, ErrMsg )`, I try to exert a prescribed angular acceleration for platform-pitching DOF： `dxdt%QDT(DOF_P)=-3.14159/60.0 * 4 * 3.14159 * 3.14159 * 0.0373 * 0.0373 * cos(2 * 3.14159 * 0.0373 * t)*2`
The acceleration was calculated by the expected prescribed sine-wave platform-pitching angle via double derivation. The initial value of platform pitch angle defined in ED input file was assign 5 deg.
(2) At the end of `SUBROUTINE ED_RK4( t, n, u, utimes, p, x, xd, z, OtherState, m, ErrStat, ErrMsg )`, I try the exert a prescribed angular  velocity and displacement for platform-pitching DOF
```
x%qt = 5.0 * 3.14159/180.0 + 3.14159/60.0 * cos(2 * 3.14159 * 0.0373 * t)*2
x%qdt = 3.14159/60.0 * 2 * 3.14159 * 0.0373 * cos(2 * 3.14159 * 0.0373 * t)*2
```

I am not sure which method is correct. My main concern is whether those methods removes the contributions of the platform (as a body) to the general inertia forces.

Please help me evaluate them. Moreover, if the platform motion was defined using the above methods, should the platform-pitching DOF be turned off in the ED input file? Is it reasonable to disable hydrodyn and moordyn in the .fst primary file? 

Best regards,

**Comment by jjonkman** [comment]
Dear @ietqlw,

I would not recommend changing ElastoDyn as you are proposing, which will result in the desired coupling between the platform motions and other DOFs of ElastoDyn.  Instead, I recommend applying external loads to the platform to achieve the desired motion.  This topic has been discussed previously, e.g., see: https://github.com/OpenFAST/openfast/issues/617.

Best regards,

**Comment by ietqlw** [comment]
Dear @jjonkman,

Thank you very much for your valuable suggestion.

Best regards,
