### ISSUE TITLE
A Question about Blade Torsion Shape Fitting in BModes

### ISSUE THREAD

**Issue by AsIlll223** [OpenFAST/openfast#1798]
Dear everyone,

When I use **ModeShapePolyFitting.xls** in BModes to **fit the torsional shape function** of the DTU10MW wind turbine blade，I do not know how to fill the **Tangent Line** column, because I just found the blade twist angle column without its slope in the _BModes.out_ . Could anyone give me some advice ? Thanks kindly.

-------- Mode No.   8  (freq = 0.63338E+01 Hz)

 span_loc   flap disp     flap slope      lag disp       lag slope      twist

  0.0000    0.000000       0.000000       0.000000       0.000000       0.000000
  0.0345   -0.000079      -0.004570       0.000033       0.001897       0.000509
  0.0690   -0.000296      -0.008303       0.000123       0.003472       0.001034
  0.1034   -0.000631      -0.011629       0.000263       0.004814       0.001675
  0.1379   -0.001079      -0.014954       0.000441       0.005800       0.002617
  0.1724   -0.001634      -0.017977       0.000648       0.006517       0.004170
  0.2069   -0.002273      -0.019919       0.000872       0.006809       0.006494
  0.2414   -0.002944      -0.019782       0.001097       0.006565       0.009656
  0.2759   -0.003560      -0.016683       0.001304       0.005731       0.013506
  0.3103   -0.004011      -0.010027       0.001473       0.004326       0.017583
  0.3448   -0.004175       0.000416       0.001589       0.002549       0.021021
  0.3793   -0.003936       0.013883       0.001637       0.000256       0.022904
  0.4138   -0.003212       0.029057       0.001597      -0.002636       0.022640
  0.4483   -0.001979       0.043955       0.001453      -0.005996       0.019850
  0.4828   -0.000291       0.055839       0.001188      -0.009814       0.014465
  0.5172    0.001687       0.061319       0.000792      -0.013861       0.007222
  0.5517    0.003692       0.056967       0.000259      -0.017871      -0.000756
  0.5862    0.005340       0.040117      -0.000397      -0.021079      -0.007339
  0.6207    0.006194       0.010113      -0.001136      -0.022695      -0.010353
  0.6552    0.005854      -0.030173      -0.001886      -0.021707      -0.007524
  0.6897    0.004076      -0.074187      -0.002543      -0.017158       0.002562
  0.7241    0.000926      -0.111116      -0.002973      -0.008337       0.019624
  0.7586   -0.003161      -0.128052      -0.003031       0.004952       0.041724
  0.7931   -0.007248      -0.110614      -0.002575       0.022048       0.065099
  0.8276   -0.009968      -0.047683      -0.001496       0.041659       0.083911
  0.8621   -0.009722       0.062790       0.000248       0.061306       0.092232
  0.8966   -0.005023       0.211487       0.002606       0.078023       0.086206
  0.9310    0.004919       0.368911       0.005418       0.088965       0.065932
  0.9655    0.020046       0.508282       0.008502       0.094265       0.035383
  1.0000    0.039546       0.609596       0.011667       0.094802      -0.000577

Thank you for your attention.

**Comment by jjonkman** [comment]
Dear @AsIlll223,

Typically when modeling a blade in BModes, you'd use `hub_conn` = 1 (cantilevered), in which case the displacement and slope is zero at the root for all modes.

Best regards,

**Comment by AsIlll223** [comment]
Dear @jjonkman,Thank for your reply. I have known the twist mode slope at root is zero. For the twist mode, I fill mode 8 twist angle in ModeShapeFitting.xls y column. But I also need to know the twist mode angle slope of every Span_loc to fill the Tangent Line in ModeShapeFitting.xls . Can I set all twist mode slopes as zero ? Could you give me some advice ?Best regards,发自我的手机-------- 原始邮件 --------发件人： jjonkman ***@***.***>日期： 2023年10月10日周二 半夜12:49收件人： OpenFAST/openfast ***@***.***>抄送： AsIlll223 ***@***.***>, Mention ***@***.***>主    题： Re: [OpenFAST/openfast] A Question about Blade Torsion Shape Fitting in BModes (Issue #1798)
Dear @AsIlll223,
Typically when modeling a blade in BModes, you'd use hub_conn = 1 (cantilevered), in which case the displacement and slope is zero at the root for all modes.
Best regards,

**Comment by jjonkman** [comment]
Dear @AsIlll223,

Can you clarify what you need this torsion mode shape for?  _ModeShapeFitting.xls_ was developed to support the calculation of polynomial mode shape coefficients for use in ElastoDyn, but ElastoDyn currently only considers mode shapes for bending of the blades and tower and requires that the offset and slope at the root be zero when specifying these mode shape polynomial coefficients.  Are you trying to do something similar for the blade torsion with the same requirements in terms of polynomial coefficients?

Best regards,

**Comment by AsIlll223** [comment]
***@***.***,Of course I know, I develop a wind turbine simulation program considering blade bend-twist coupling effects based on current Openfast ElastoDyn code. So I need the blade twist mode shape cofficients.发自我的手机-------- 原始邮件 --------发件人： jjonkman ***@***.***>日期： 2023年10月10日周二 凌晨1:52收件人： OpenFAST/openfast ***@***.***>抄送： AsIlll223 ***@***.***>, Mention ***@***.***>主    题： Re: [OpenFAST/openfast] A Question about Blade Torsion Shape Fitting in BModes (Issue #1798)
Dear @AsIlll223,
Can you clarify what you need this torsion mode shape for?  ModeShapeFitting.xls was developed to support the calculation of polynomial mode shape coefficients for use in ElastoDyn, but ElastoDyn currently only considers mode shapes for bending of the blades and tower and requires that the offset and slope at the root be zero when specifying these mode shape polynomial coefficients.  Are you trying to do something similar for the blade torsion with the same requirements in terms of polynomial coefficients?
Best regards,

**Comment by AsIlll223** [comment]
Dear @jjonkman 

Thank you for your reply. Of course I know, I develop a wind turbine simulation program considering blade bend-twist coupling effects based on current Openfast ElastoDyn code. So I need the blade twist mode shape cofficients. 

Best regards,

**Comment by jjonkman** [comment]
Dear @AsIlll223,

What requirements does your new program have in terms of polynomial coefficients for the torsion mode?  It is natural for the lateral deflection of a cantilevered beam to have zero slope at its root, but the same can't be said for the torsion mode.  For example, if a uniform torque is applied to a circular shaft, the twist will change linearly along the beam, so, the slope of this twist mode will be constant from root to tip (i.e., not zero at the root).

Best regards,

**Comment by AsIlll223** [comment]
Dear @jjonkman 

Thank you for your reply.

I made the new program mainly referring to these articles: _Nonlinear equations of motion for the elastic bending and torsion of twisted nonuniform rotor blades (Hodges,1974)_ and _STABILITY OF ELASTIC BENDING AND TORSION OF UNIFORM CANTILEVER ROTOR BLADES IN HOVER WITH VARIABLE STRUCTURAL COUPLING (Hodges,1976)_. 

I calculated the modal mass and stiffness of the blade torsional mode with the torsional shape function coefficient in _Subroutine Coeff( )_. The operation here is similar to calculating the flapwise and edgewise modal mass and stiffness in ElastoDyn, and then in _Subroutine FillAugMat( )_ I Added the blade 1st torsion DOF and calculated generalized force and other terms to solve the mass matrix and so on.

Best regards,

**Comment by jjonkman** [comment]
Dear @AsIlll223,

Regarding adding a blade-torsion degrees of freedom to ElastoDyn, see the following related discussion on our forum: https://forums.nrel.gov/t/coupled-blade-modes-in-fast/314/39?u=jason.jonkman.

Best regards,

**Comment by Fandier** [comment]
Dear @jjonkman
I seem to be generating incorrect natural frequencies for the tower of the OC3-Spar when using Bmode. I used the default parameters to calculate the natural frequencies of the tower, but the natural frequencies of the first six orders of the platform are different from the natural frequencies calculated by FAST.
Bmode:
![image](https://github.com/OpenFAST/openfast/assets/73537352/a9e9aad4-dced-4986-acdd-cd4e73bc40cf)
FAST:
![image](https://github.com/OpenFAST/openfast/assets/73537352/c33640c9-d2d9-4ed7-ad0c-c54948a03783)
I would like to know if my Bmode settings are correct?
![image](https://github.com/OpenFAST/openfast/assets/73537352/f5eea0d2-c74f-4137-abbc-55874066b5fb)
![image](https://github.com/OpenFAST/openfast/assets/73537352/ceb64d8e-6ac8-46e7-8424-a937f814a33e)
![image](https://github.com/OpenFAST/openfast/assets/73537352/5660346e-c54a-42b9-a869-3a07006f8ef5)
![image](https://github.com/OpenFAST/openfast/assets/73537352/deb66b2e-1d4d-4c38-8bab-a6c87a50e456)

**Comment by jjonkman** [comment]
Dear @Fandier,

You haven't shared your complete set of BModes inputs, but the inputs you have shared look correct.

Are you using the recommended version of BModes (called BModes_JJ on our forum: https://forums.nrel.gov/)?  This version is available here: https://drive.google.com/file/d/14TNXJvtmFLYn5cn4A-_5cMfUwXFD6oB6/view?usp=drive_link.

Best regards,

**Comment by Fandier** [comment]
Dear @jjonkman
I apologise that I chose the wrong parameters for the mooring stiffness leading to incorrect results. I have another question, if I want to get the torsional mode shape of the tower for OC4 semisubmersible, do I just use the column "twist" and fit it to a polynomial form?
![image](https://github.com/OpenFAST/openfast/assets/73537352/743d069a-ef6d-4cbf-b86b-0efc769d7e40)

![image](https://github.com/OpenFAST/openfast/assets/73537352/2cdffc21-b5d3-4361-a408-d1bddeb45b5c)

**Comment by jjonkman** [comment]
Dear @Fandier,

Good point; I see the incorrect mooring stiffness in your BModes input now.

Regarding torsion, I agree, with the caveats discussed earlier in this discussion.

Best regards,

**Comment by AsIlll223** [comment]
Dear @jjonkman 

When I was learning Blade_coord.docx about ElastoDyn, I had doubts about the following content. Could you give me some reference interpretation?
![image](https://github.com/OpenFAST/openfast/assets/56946664/94777456-cc2b-4820-bf3b-d7241b016eae)
 Why the _theta_x_ and the _theta_y_ calculate as this formula ? I don not understand the angle transformation relation in this formula, especially the _theta_op directly dot the cos(theta_s)_ term.

Best regards,

**Comment by jjonkman** [comment]
Dear @AsIlll223,

In these equations, _theta_OoP_ and _theta_IP_ are the slopes of the elastic deflection in the blade coordinate system (which are aligned with out-of-plane (OoP) and in-plane (IP) when the blade-pitch angle is zero).  The _COS()_ and _SIN()_ terms involving the structural pretwist (_theta_S_) rotate these slopes so that they are aligned with the structural twist (because coordinate system _Lj_ is aligned with the structural pretwist).

I hope that helps.

Best regards,

**Comment by AsIlll223** [comment]
Dear @jjonkman 

Thank you . That helps a lot.

Best regards,
