### ISSUE TITLE
Some outliers of BeamDyn node B1N3TAXl

### ISSUE THREAD

**Issue by Wangzhenyu12** [OpenFAST/openfast#1800]
Hello, everyone. I want to research the acceleration of blade node near the root of 5MW onshore wind turbine. The output variable name is B1N3TAXl. The kp_zr of N3 is 1.1998650E+00m.I simulated a few sets of 10-minutes with different mean wind speed and different RandSeed1. And I find there are outliers in some time series. The probability of outliers presence increases with the mean wind speed. Please explain this phenomenon and whether I should ignore these outliers？
Thanks!
<img width="744" alt="ed53abe3cbf1662197a0262589290e3" src="https://github.com/OpenFAST/openfast/assets/74004322/ebab5f9e-3c53-4627-9068-d470670fc86e">
<img width="812" alt="548a741c90836f6ab110944aeeb15f4" src="https://github.com/OpenFAST/openfast/assets/74004322/d09f5ccb-bd4b-4745-880d-d9861f197551">

**Comment by jjonkman** [comment]
Dear @Wangzhenyu12,

Can you clarify which version of OpenFAST with BeamDyn you are running?  There have been many improvements and bug fixes made to BeamDyn recently, including in the pending release of OpenFAST v3.5.1.  I'd like to make sure that these "spikes' are not the result of issues that we have previously addressed.  If you are not running v3.5.1, could you see if they persist in this version: https://github.com/OpenFAST/openfast/tree/rc-3.5.1.

Best regards,

**Comment by Wangzhenyu12** [comment]
Dear @jjonkman 
Thanks for your quick reply. I used OpenFAST v3.4.1 to calculate these results. Today, I try v3.5.0 to calculate again and get similar spikes in same time series. As a beginner, I am not able to compile. Next time when you release OpenFAST v3.5.1 official version , I will try it again and tell you the whether these spikes persist.
Best regards,

**Comment by Wangzhenyu12** [comment]
Dear @jjonkman
I have tried to use OpenFAST v3.5.1 to recalculate same 8 sets of 10-minutes, the spikes still exist in the same position. So could you please tell me how to process these spikes？

Best regards,

**Comment by jjonkman** [comment]
Dear @Wangzhenyu12,

Do you also see jumps in velocity associated with the acceleration spikes, or is the effect isolated to the acceleration outputs?

Best regards,

**Comment by Wangzhenyu12** [comment]
Dear @jjonkman
I only find an output type name 'N1TVXg' can be output which is associated with 'N1TAXl', though they are in different coordinate systems. And I draw two time series figures of these two outputs.  There is no any significant jump in 'N1TVXg'.
<img width="876" alt="image" src="https://github.com/OpenFAST/openfast/assets/74004322/4a5892d3-60d9-4f2e-bce3-d7c5e79f4964">



<img width="773" alt="image" src="https://github.com/OpenFAST/openfast/assets/74004322/f661eb68-2d69-4239-a3d5-b2185616cf49">

Best regards,

**Comment by jjonkman** [comment]
Dear @Wangzhenyu12,

I would guess the spikes that are isolated to acceleration are an artifact of the numerics in the generalized alpha solve used by BeamDyn.  Considering that these spikes do not propagate to velocity or displacement, I would not be too concerned.

Best regards,

**Comment by Wangzhenyu12** [comment]
Dear @jjonkman
Thanks for your reasonable answer！
