### ISSUE TITLE
The output of the platform motion using OLAF

### ISSUE THREAD

**Issue by HelenLeeeeee** [OpenFAST/openfast#1813]
I want to use BEM and OLAF to simulate IEA15MW-Umaines， but when the inflow wind and other modules except erodyn are the same, the output platform motion of the two is very different, but the aerodynamic characteristics are similar. I wonder which module in OLAF this might be caused by a setup error.
the surge movement of OLAF output is small and seems unrealistic
![image](https://github.com/OpenFAST/openfast/assets/145997196/d2699b46-6488-4ef6-9969-d61eca5ecf11)

**Comment by ebranlard** [comment]
Hi, 
I'm not sure how you setup your OLAF simulation, but OLAF requires tuning of the inputs before running a given simulation. You can try to apply the guidelines here to setup the OLAF inputs: 
https://openfast.readthedocs.io/en/dev/source/user/aerodyn-olaf/RunningOLAF.html#guidelines 
My guess is that currently your inputs are not physical. Hopefully the guidelines will help provide results that are more realistic.

**Comment by HelenLeeeeee** [comment]
> Hi, I'm not sure how you setup your OLAF simulation, but OLAF requires tuning of the inputs before running a given simulation. You can try to apply the guidelines here to setup the OLAF inputs: https://openfast.readthedocs.io/en/dev/source/user/aerodyn-olaf/RunningOLAF.html#guidelines My guess is that currently your inputs are not physical. Hopefully the guidelines will help provide results that are more realistic.

I used python files to generate nNWPanels, nNWPanelsFree, and DTFVW based on my wind speed and rotor speed. Regularization parameters are also set according to the requirements of the document. Are there any other parameters I haven't noticed?Here is my OLAF input, Would you please check it for me？I would appreciate your help.
https://github.com/HelenLeeeeee/practice-issue/blob/main/olaf.png?raw=true

**Comment by ebranlard** [comment]
Your input file looks reasonable. One thing to note is that OLAF needs an initialization period (typically 100s or more, the python script should tell you) before the wake is fully developped and the induced velocities at the rotor are realistic. I'm afraid that becasue of this, you'll have issues comparing BEM and OLAF time series, or you'll have to run very long simulations and only compare them in the statistical sense. 

First, I would try to verify that BEM and OLAF provide similar results for a fixed platform simulation. You'll also see how OLAF indeed needs a transient period. 

To slightly circumvent the transient issue, you could try starting your system at a very low wind speed and RPM and progressively ramp up the wind speed to the desired value (using a deterministic wind or by manipulating your turbulence box).   

I hope that helps.

**Comment by HelenLeeeeee** [comment]
> Your input file looks reasonable. One thing to note is that OLAF needs an initialization period (typically 100s or more, the python script should tell you) before the wake is fully developped and the induced velocities at the rotor are realistic. I'm afraid that becasue of this, you'll have issues comparing BEM and OLAF time series, or you'll have to run very long simulations and only compare them in the statistical sense.
> 
> First, I would try to verify that BEM and OLAF provide similar results for a fixed platform simulation. You'll also see how OLAF indeed needs a transient period.
> 
> To slightly circumvent the transient issue, you could try starting your system at a very low wind speed and RPM and progressively ramp up the wind speed to the desired value (using a deterministic wind or by manipulating your turbulence box).
> 
> I hope that helps.

I set the initial rotor speed in ElastoDyn to 2rpm, and set WindType to 2 to make the wind speed from 0 to rated wind speed (10.59m/s), OLAF's prediction of platform turbulence is still much lower than BEM's.
Moreover, OLAF's prediction of platform aerodynamic performance, such as wind turbine thrust, torque and power, is similar to BEM method. Does this prove that OLAF wake is fully developed? Are there any other reasons why the prediction of platform movement might be problematic?
Thank you for your prompt reply.

**Comment by ebranlard** [comment]
Hi @HelenLeeeeee 
I'm not fully sure as to what is happening, the message you see are likely Moordyn warnings. 

I would recommend doing a simulation with a stiff platform (ElastoDyn platform degrees of freedom off), and compare the two solutions (BEM/OLAF) and look for big differences. Then you con progressively introduce degrees of freedom one by one to further investigate where the difference comes from.

**Comment by HelenLeeeeee** [comment]
> Hi @HelenLeeeeee I'm not fully sure as to what is happening, the message you see are likely Moordyn warnings.
> 
> I would recommend doing a simulation with a stiff platform (ElastoDyn platform degrees of freedom off), and compare the two solutions (BEM/OLAF) and look for big differences. Then you con progressively introduce degrees of freedom one by one to further investigate where the difference comes from.

I made a mistake in the settings of the main file, this problem has been fixed. 
Thank you for your reply!
