### ISSUE TITLE
Error in ReadWrite_FAST function

### ISSUE THREAD

**Issue by EhsanASL92** [OpenFAST/openfast#1814]
Hi,
I am trying to run ROSCO on Simulink. First, I added the ROSCO_toolbox to set the path in Matlab.
Then, I changed the directory name for the SFunction and FAST directory.
fast.FAST_SFuncDir = 'D:\OpenFASTbyEhsan\openfast-3.1.0\glue-codes\simulink\src'; %%%% NEED FOR SIMULINK
fast.FAST_InputFile = '5MW_Land_BD_DLL_WTurb.fst'; % FAST input file (ext=.fst)
fast.FAST_directory = 'D:\OpenFASTbyEhsan\openfast-3.1.0\reg_tests\r-test\glue-codes\openfast\5MW_Land_BD_DLL_WTurb'; % Path to fst directory files
I tested it with both FAST v8 and OpenFAST v3.1.0
But I see this error :
Error in ReadWrite_FAST (line 14)
FP = FAST2Matlab(fullfile(fast.FAST_directory,fast.FAST_InputFile),2); %FP are Fast Parameters, specify 2 lines of header (FAST 8)
Can you help me run ROSCO on Matlab/Simulink?

I run OpenFAST examples and they all run properly!
I also check the ReadWrite_FAST function, seem that cannot be called with proper arguments!

Best regards,
Ehsan

**Comment by ebranlard** [comment]
This seems to be a matlab-toolbox issue, can you repost it on the matlab toolbox repository?

Thank you
