### ISSUE TITLE
OpenFAST simulation of 15MW Floater: IEA-15-240-RWT-UMaineSemi 

### ISSUE THREAD

**Issue by mariachristinadiam** [OpenFAST/openfast#1817]
Hello! I am new to OpenFAST and I am trying to run a simulation of the UMaine VolturnUS-S (FOWT) semi-submersible supporting the IEA-15-240-RWT wind turbine: 
https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/master/OpenFAST/IEA-15-240-RWT-UMaineSemi

When I run the IEA-15-240-RWT-UMaineSemi.fst via openfast_x64.exe I get the following result:
**************************************************************************************************
OpenFAST

Copyright (C) 2023 National Renewable Energy Laboratory
Copyright (C) 2023 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v3.5.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 2021
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: May 17 2023
 - Time: 13:43:33
Execution Info:
 - Date: 10/18/2023
 - Time: 23:51:45+0300

OpenFAST input file heading:
    IEA 15 MW offshore reference model on UMaine VolturnUS-S semi-submersible floating platform

Running ElastoDyn.
Running AeroDyn.
Running InflowWind.
Running HydroDyn.
  WARNING:  The requested output channel is invalid: WavesF1xi
  WARNING:  The requested output channel is invalid: WavesF1zi
  WARNING:  The requested output channel is invalid: WavesM1yi
  WARNING:  The requested output channel is invalid: WavesF2xi
  WARNING:  The requested output channel is invalid: WavesF2zi
  WARNING:  The requested output channel is invalid: WavesM2yi
  WARNING:  The requested output channel is invalid: WavesF2xi
  WARNING:  The requested output channel is invalid: WavesF2yi
  WARNING:  The requested output channel is invalid: WavesF2zi
  WARNING:  The requested output channel is invalid: WavesM2xi
  WARNING:  The requested output channel is invalid: WavesM2yi
  WARNING:  The requested output channel is invalid: WavesM2zi
 Generating incident wave kinematics and current time history.
 Calculating second order difference frequency wave kinematics.
 Calculating second order sum frequency wave kinematics.
 Reading in WAMIT output with root name
 "D:\Desktop\openfast-3.5.0\openfast-3.5.0\IEA-15-240-RWT-master\OpenFAST\IEA-15-240-RWT-UMaineSem
 i\HydroData/IEA-15-240-RWT-UMaineSemi".
 Computing radiation impulse response functions and wave diffraction forces.
 Calculating second order difference-frequency force using the full quadratic transfer function.
Running MoorDyn (v2.0.0, 2022-12-08).
   This is MoorDyn v2, with significant input file changes from v1.
   Copyright: (C) 2022 National Renewable Energy Laboratory, (C) 2019 Matt Hall
   Parsing MoorDyn input file:
   D:\Desktop\openfast-3.5.0\openfast-3.5.0\IEA-15-240-RWT-master\OpenFAST\IEA-15-240-RWT-UMaineSe
   mi\IEA-15-240-RWT-UMaineSemi_MoorDyn.dat
Warning: invalid output specifier FX.  Must start with L, C, R, or B
Warning: invalid output specifier FY.  Must start with L, C, R, or B
Warning: invalid output specifier FZ.  Must start with L, C, R, or B
   Created mooring system:  3 lines, 6 points, 0 rods, 0 bodies.
   Finalizing initial conditions using dynamic relaxation.
   t=60  FairTen 1: 2.43287E+06, 2.44526E+06, 2.43537E+06
   Fairlead tensions did not converge within TMaxIC=60 seconds.
   MoorDyn initialization completed.
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows).

FAST_InitializeAll:HydroDyn_Init:HydroDynInput_ProcessInitData: A requested output channel is
invalid
FAST_InitializeAll:SrvD_Init:BladedInterface_Init:The dynamic library
/usr/share/miniconda3/envs/test/lib/libdiscon.dll could not be loaded. Check that the file exists
in the specified location and that it is compiled for 64-bit applications.

 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.

I have installed ROSCO and I do not understand what the error message indicates.

**Comment by mariachristinadiam** [comment]
[Thank you very much! It terminated normally.
However, using the MATLAB Toolbox functions ReadFASTtext.m to read the files, the channels' values are empty, as seen below:]
![1](https://github.com/OpenFAST/openfast/assets/148391339/1170da63-e6c1-4693-8f15-92b67c45eaf9)
Τhank you again.

**Comment by jjonkman** [comment]
Does your `.out` file have columns of numerical data in it?  The MATLAB workspace you shared seems to imply that the _.out_ file you are using only has a header (including channel names and units), but no actual numerical results.

**Comment by mariachristinadiam** [comment]
Νο, there are no actual numerical results in the .out file.
![Καταγραφή 2](https://github.com/OpenFAST/openfast/assets/148391339/bfbd317b-d315-472b-85c3-a37985307645)

**Comment by jjonkman** [comment]
So, the issue is not with the MATLAB post-processing, but with your OpenFAST simulation.  It appears the OpenFAST simulation ended after the output file header was created, but before any time-series data was written to the file.  What information did OpenFAST share when you ran the simulation?

**Comment by mariachristinadiam** [comment]
I found my mistake, once I updated DISCON to version 2.8.0 of ROSCO, it worked. 
Thank you!
