### ISSUE TITLE
OpenFast regression test: 4 out of 40 fail

### ISSUE THREAD

**Issue by MuhammadSharjil** [OpenFAST/openfast#1826]
Hi
I am a PhD student and have recently started working on OpenFast. I have followed the details on https://openfast.readthedocs.io/en/main/source/testing/regression_test_windows.html#regression-test-windows
I have windows 10 with visual studio 2019 and python 3.11.
The regression test results are:
pass 36, fail 4
I couldnt figure out as if I should take this as normal and move forward or debug this.
Thanks
![Capture](https://github.com/OpenFAST/openfast/assets/114649993/c734e0f5-8ccd-460b-86fe-c881851afdc3)

**Comment by deslaughter** [comment]
Please provide which version/branch of OpenFAST you're compiling and the Intel Fortran compiler version.

**Comment by MuhammadSharjil** [comment]
I have cloned it using 
git clone https://github.com/openfast/openfast

![dev branch](https://github.com/OpenFAST/openfast/assets/114649993/ebec8960-8f97-41e3-b037-eb5a321df7fd)
.git

**Comment by MuhammadSharjil** [comment]
![plots](https://github.com/OpenFAST/openfast/assets/114649993/fb9df07a-1764-4715-9ea5-cc47c36cb97d)
![plots_continued](https://github.com/OpenFAST/openfast/assets/114649993/ca31e1e5-bed9-4d48-bece-3599935e3c21)

These are plots for the case SWRT_YFREE_VS_WTurb_Summary
I have used this command to execute the regression tests
python .\manualRegressionTest.py ..\build\bin\openfast_x64_Double.exe 2.0 1.9

**Comment by deslaughter** [comment]
@MuhammadSharjil Thank you for the additional information. I'll need some more time to look into this. It's not uncommon for different compilers to produce slightly different results. The regression test reference files are tuned for the GFortran compiler and the GitHub Actions servers. However, I wouldn't expect the level of differences that you're showing in the plots. I will attempt to reproduce this on my system and let you know what I find out. In the meantime, I wouldn't let this hold you up.

**Comment by bjonkman** [comment]
The SWRT models have instabilities (as shown in the baseline results), so I wouldn't worry so much about those differences. The SWRT models make difficult regression tests because almost every recompile can change the time histories around that instability at ~20 seconds.

If other models have results this different, I would be more concerned.

**Comment by MuhammadSharjil** [comment]
Thanks for the reply @bjonkman.
I actually had 4 failed cases.
![failed_cases1](https://github.com/OpenFAST/openfast/assets/114649993/f9f8cca9-3037-44a1-978d-5f8494148d60)

![failed_cases](https://github.com/OpenFAST/openfast/assets/114649993/5a354a61-eb58-4168-a891-49271247aefe)


> The SWRT models have instabilities (as shown in the baseline results), so I wouldn't worry so much about those differences. The SWRT models make difficult regression tests because almost every recompile can change the time histories around that instability at ~20 seconds.
> 
> If other models have results this different, I would be more concerned.

**Comment by bjonkman** [comment]
> Thanks for the reply @bjonkman. I actually had 4 failed cases. ![failed_cases1](https://user-images.githubusercontent.com/114649993/279067669-f9f8cca9-3037-44a1-978d-5f8494148d60.PNG)
> 
> ![failed_cases](https://user-images.githubusercontent.com/114649993/279067632-5a354a61-eb58-4168-a891-49271247aefe.PNG)
Without plots of the failing channels in the other 3 cases, I can't comment on if they are important. I was just indicating that the SWRT model failure isn't a concern to me.

**Comment by MuhammadSharjil** [comment]
> > Thanks for the reply @bjonkman. I actually had 4 failed cases. ![failed_cases1](https://user-images.githubusercontent.com/114649993/279067669-f9f8cca9-3037-44a1-978d-5f8494148d60.PNG)
> > ![failed_cases](https://user-images.githubusercontent.com/114649993/279067632-5a354a61-eb58-4168-a891-49271247aefe.PNG)
> 
> Without plots of the failing channels in the other 3 cases, I can't comment on if they are important. I was just indicating that the SWRT model failure isn't a concern to me.

@bjonkman , here are the three failed cases results
[5MW_ITIBarge_DLL_WTurb_WavesIrr Summary.pdf](https://github.com/OpenFAST/openfast/files/13210012/5MW_ITIBarge_DLL_WTurb_WavesIrr.Summary.pdf)
[5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth Summary.pdf](https://github.com/OpenFAST/openfast/files/13210014/5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth.Summary.pdf)
[UAE_Dnwind_YRamp_WST Summary.pdf](https://github.com/OpenFAST/openfast/files/13210015/UAE_Dnwind_YRamp_WST.Summary.pdf)

**Comment by bjonkman** [comment]
It looks like your wave elevations on these two 5MW offshore cases don't match. It is possible that those models aren't using the same random number generator (RNG). If those cases aren't using RANLUX as the RNG, that would probably explain the differences you are seeing, but you will have to check what it is using.

The UAE failure looks like it is caused by very small differences in accelerations, which tend to be noisy. I wouldn't be too concerned with those differences.

**Comment by MuhammadSharjil** [comment]
![Capture](https://github.com/OpenFAST/openfast/assets/114649993/683b2faf-69c9-4db7-aecf-21b476168914)
You are referring to SeaState.dat for 5MW_ITIBarge_DLL_WTurb_WavesIrr?
I have gone through the seastate.dat file in "5MW_ITIBarge_DLL_WTurb_WavesIrr" in both "build/reg_tests" and "openfast/reg_tests" folders.

Wavemode is set to 2
WaveSeed(1) is 123456789
WaveSeed(2) is RANLUX 


> It looks like your wave elevations on these two 5MW offshore cases don't match. It is possible that those models aren't using the same random number generator (RNG). If those cases aren't using RANLUX as the RNG, that would probably explain the differences you are seeing, but you will have to check what it is using.
> 
> The UAE failure looks like it is caused by very small differences in accelerations, which tend to be noisy. I wouldn't be too concerned with those differences.

**Comment by MuhammadSharjil** [comment]
> ![Capture](https://user-images.githubusercontent.com/114649993/279659121-683b2faf-69c9-4db7-aecf-21b476168914.PNG) You are referring to SeaState.dat for 5MW_ITIBarge_DLL_WTurb_WavesIrr? I have gone through the seastate.dat file in "5MW_ITIBarge_DLL_WTurb_WavesIrr" in both "build/reg_tests" and "openfast/reg_tests" folders.
> 
> Wavemode is set to 2 WaveSeed(1) is 123456789 WaveSeed(2) is RANLUX
> 
> > It looks like your wave elevations on these two 5MW offshore cases don't match. It is possible that those models aren't using the same random number generator (RNG). If those cases aren't using RANLUX as the RNG, that would probably explain the differences you are seeing, but you will have to check what it is using.
> > The UAE failure looks like it is caused by very small differences in accelerations, which tend to be noisy. I wouldn't be too concerned with those differences.

Hi
It would be nice to get an updated response on this. This will help me in getting started with this version.
Thanks

**Comment by MuhammadSharjil** [comment]
> I'm not sure I can comment on why your wave elevations would be different from the baseline regressions. For NREL help, it would be good if you could tell them which version of OpenFAST you are using. A git hash would be very useful--this is generally written to the screen when you first run OpenFAST and should also be written inside the .log file that is generated in the regression tests.

Thanks a lot for the looking into it.
I will post this on NREL forum for onwards assistance :)

**Comment by jjonkman** [comment]
Dear @MuhammadSharjil,

I briefly skimmed your PDF files and nothing stands out as incorrect (the wave elevation time series even agree).  There are small differences that I would guess are due to differences in operating system or compiler settings between your results and the baselines, but nothing stands out as significant (at least that I saw in my quick skim).  Is there something specifically concerning to you?

Best regards,

**Comment by MuhammadSharjil** [comment]
> Dear @MuhammadSharjil,
> 
> I briefly skimmed your PDF files and nothing stands out as incorrect (the wave elevation time series even agree). There are small differences that I would guess are due to differences in operating system or compiler settings between your results and the baselines, but nothing stands out as significant (at least that I saw in my quick skim). Is there something specifically concerning to you?
> 
> Best regards,

Hi @jjonkman 
Thanks for going through the files. I also found the difference to be not that large, but  I wanted the expert opinion.
Thanks a lot.
