### ISSUE TITLE
A Question on How to Generate 3D Turbulent Wind

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#1830]
Hello everyone,

I am trying to generate a turbulent wind using turbsim, and I want the wind speeds in all three directions(x, y, z) of this wind to be roughly the same (such as maintaining fluctuations around 7m/s).

The turbulent wind I generated before, often meets the requirements in the x direction, but the wind speed in the y or z direction is always close to zero.

In other words, I want to accurately control the wind speed in all directions. How can I set up the INP file?

Best wishes!

**Comment by jjonkman** [comment]
Dear @shipors,

Can you clarify how you are currently setting up your TurbSim simulation?  Presumably you are using one of the standard turbulence models, like `TurbModel` = "IECKAI"?  Each of these standard turbulence has default scaling between the standard deviations in the u-, v-, and w- components of turbulence.

If you have your own scalings in mind, you could select different turbulence models.  For example, `TurbModel` = "USRINP" allows you to specify you own scalings and spectra in the u-, v-, and w- directions.  And when using `TurbModel` = "IECVKM" along with a user-defined velocity profile (`WindProfileType` = "USR"), you can set your own scaling factors for the standard deviations of the u-, v-, and w-components.  See the TurbSim documentation for more information: https://openfast.readthedocs.io/en/main/_downloads/cb14d3e2d3533d76e405d730fea19846/TurbSim_v2.00.pdf.

Best regards,

**Comment by bjonkman** [comment]
TurbSim always generates winds aligned with the mean wind direction (noted by lower case u, v, w). By that definition, v and w should have mean velocities of 0. After generating those winds, it rotates to the global coordinate system (aligned with global X, Y, Z and noted by U, V, W).  If you want the mean wind speeds around global X, Y, and Z to be the same, you'd have to adjust the rotation angles `VFlowAng` and `HFlowAng`
