### ISSUE TITLE
Fast.farm control problem.

### ISSUE THREAD

**Issue by DingZL1207** [OpenFAST/openfast#1831]
How can I develop a control strategy to manage the wind tuebine during the runtime of the Fast.farm program?Thank you very much!

**Comment by jjonkman** [comment]
Dear @DingZL1207,

I'm not sure I fully understand what you are asking.

FAST.Farm uses OpenFAST to model the individual wind turbines of a wind farm.  OpenFAST itself supports several control options.  See the ServoDyn documentation for information on the control options available in OpenFAST.

FAST.Farm also supports functionality of a user-specified super controller that can coordinate control actions between each turbine in the wind farm.  See the FAST.Farm documentation for information on the super controller functionality of FAST.Farm.

Best regards,

**Comment by DingZL1207** [comment]
Sorry I didn't explain it clearly. What I mean is that when the Fast.farm program runs the calculation, the wind turbine should be adjusted and controlled according to the strategy set by me, such as adjusting the yaw Angle (for example, adjusting the yaw Angle of wind turbine No.1 to 10 degrees at the 10th second of the total time, and adjusting the yaw Angle of wind turbine No.2 to 20 degrees at the 20th second). Rather than a set policy of entering the relevant file before the program runs .

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/24/2023 23:52 |
| To | OpenFAST/openfast ***@***.***> |
| Cc | DingZL1207 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [OpenFAST/openfast] Fast.farm control problem. (Issue #1831) |

Dear @DingZL1207,

I'm not sure I fully understand what you are asking.

FAST.Farm uses OpenFAST to model the individual wind turbines of a wind farm. OpenFAST itself supports several control options. See the ServoDyn documentation for information on the control options available in OpenFAST.

FAST.Farm also supports functionality of a user-specified super controller that can coordinate control actions between each turbine in the wind farm. See the FAST.Farm documentation for information on the super controller functionality of FAST.Farm.

Best regards,

**Comment by jjonkman** [comment]
The control options available in OpenFAST and FAST.Farm are flexible enough to do what you propose.

If you have predefined nacelle-yaw commands in mind (to force yaw motion to specific angles at specific times), these can be set directly with the ServoDyn input file of each OpenFAST model using the override yaw maneuver inputs of ServoDyn.  However, if you want to control nacelle yaw based on specific measurements available at runtime, you'll have to implement your own user-defined yaw controller.

Best regards,

**Comment by DingZL1207** [comment]
> The control options available in OpenFAST and FAST.Farm are flexible enough to do what you propose.
> 
> If you have predefined nacelle-yaw commands in mind (to force yaw motion to specific angles at specific times), these can be set directly with the ServoDyn input file of each OpenFAST model using the override yaw maneuver inputs of ServoDyn. However, if you want to control nacelle yaw based on specific measurements available at runtime, you'll have to implement your own user-defined yaw controller.
> 
> Best regards,



> The control options available in OpenFAST and FAST.Farm are flexible enough to do what you propose.
> 
> If you have predefined nacelle-yaw commands in mind (to force yaw motion to specific angles at specific times), these can be set directly with the ServoDyn input file of each OpenFAST model using the override yaw maneuver inputs of ServoDyn. However, if you want to control nacelle yaw based on specific measurements available at runtime, you'll have to implement your own user-defined yaw controller.
> 
> Best regards,

Dear jjonkamn,

Thank you so much!Sorry I am a first year graduate student who just started to learn open fast, so there are so many questions. If possible, could you please tell me what knowledge is needed for these related operations (such as how to use super controller), so that I can better find specific resources to learn (although the user manual is very detailed, it is still difficult for me). Thanks again!

Best regards,

**Comment by jjonkman** [comment]
Dear @DingZL1207,

I would recommend that you:

1. Review the supercontroller documentation available on readthedocs: https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#super-controller and https://openfast.readthedocs.io/en/main/source/user/fast.farm/FFarmTheory.html#super-controller-sc-module.
2. Begin with the supercontroller example that makes use of the sample _DISCON_SC.f90_ and _sc_dll.f90_ source files discussed in the following OpenFAST discussion: https://github.com/OpenFAST/openfast/discussions/1511.

Best regards,

**Comment by DingZL1207** [comment]
> Dear @DingZL1207,
> 
> I would recommend that you:
> 
> 1. Review the supercontroller documentation available on readthedocs: https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#super-controller and https://openfast.readthedocs.io/en/main/source/user/fast.farm/FFarmTheory.html#super-controller-sc-module.
> 2. Begin with the supercontroller example that makes use of the sample _DISCON_SC.f90_ and _sc_dll.f90_ source files discussed in the following OpenFAST discussion: [Violation error when running FAST.Farm with supercontroller #1511](https://github.com/OpenFAST/openfast/discussions/1511).
> 
> Best regards,

Thank you very much!
