### ISSUE TITLE
Bug report--The difference between the number of output nodes and the number of definition nodes of BeamDyn.

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#1832]
Dear all,

I use the OpenFAST v3.5.0 simulate the aeroelastic performance of the IEA-15MW (download from "https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/master"). 

The aerodynamic model is DBEM and the structural model is BeamDyn. The number of total blade nodes defined in the BeamDyn.dat is 50, while the number of output nodes in ".out" file is 51.  I am confused what results in this issue.
![image](https://github.com/OpenFAST/openfast/assets/98078424/6bf32a00-bca4-4567-8d9f-e944511e47ec)

Thank you for your attention.

**Comment by winder365** [comment]
Dear @jjonkman 

Sorry for delay. 
As you mentioned above, This IEA-15MW model uses station_total = 26 with refine = 2, which means that there is a node added between each station. My question is that whether the node is added by linear interpolation. For example, whether the new node between r/R=0.1 and r/R=0.2 is added at the r/R =0.15 position.

Thank for your attention.

**Comment by ZL6462** [comment]
Dear @jjonkman 

As you mentioned above, This IEA-15MW model uses station_total = 26 with refine = 2, which means that there is a node added between each station. My question is that whether the node is added by linear interpolation. For example, whether the new node between r/R=0.1 and r/R=0.2 is added at the r/R =0.15 position.

Thank for your attention.

**Comment by jjonkman** [comment]
Dear @ZL6462,

Yes, your understanding is correct.

Best regards,
