### ISSUE TITLE
where the Blade-type control interface can be found

### ISSUE THREAD

**Issue by Tomedssa** [OpenFAST/openfast#1839]
Hi,
I just started to contact OpenFAST, some questions may not be professional, please don't mind. The article "A Reference Open Source Controller for Stationary and floating offshore wind Turbines" mentions that OpenFAST uses a Blade-type control interface to communicate with ROSCO. But I'm not sure where the Blade-type control interface can be found. Can you help me find it?
Thank you very much for your time in advance.
Tomedssa

**Comment by jjonkman** [comment]
Dear @Tomedssa,

I believe you mean that you are asking about the "Bladed-style control interface"; is that correct?  the ROSCO controller is implemented as a Bladed-style dynamic library.  The ServoDyn module of OpenFAST supports an interface to controllers implemented Bladed-style dynamic library format.

ROSCO is available here: https://github.com/NREL/ROSCO.

Best regards,

**Comment by Tomedssa** [comment]
Hello jjonkman，
Thanks for your reply;
I opened a ServoDyn module for OpenFAST. I found the blade interface section in this ServoDyn module,is this the Bladed-style control interface？In other words, am I correct in understanding that OpenFast interacts with ROSCO through blade interface module?
Thanks a lot.

**Comment by jjonkman** [comment]
Dear @Tomedssa,

Correct.  OpenFAST will use the Bladed DLL interface when `PCMode` =5 (for pitch control), `VSContrl` = 5 (for torque control), `HSSBrMode` = 5 (for control of the brake), `YCMode` = 5 (for yaw control), `AfCmode` = 5 (for airfoil control), and/or `CCmode` = 5 (for cable control).

Best regards,

**Comment by Tomedssa** [comment]
Dear @jjonkman
I have benefited greatly from your answer. Thank you very much.
