### ISSUE TITLE
MCrunch cannot run in MATLAB R2022a version

### ISSUE THREAD

**Issue by 1codecopyer** [OpenFAST/openfast#1843]
Hi
**MCrunch can't run with  CertTest.m**
<A clear and concise description of the bug.>

**System environment and software version information**
<Update the following list with your specific information.>
1. Windows system
2. MATLAB R2022a version
3. Run CertTest. m under the CertTest folder
4. MATLAB cannot run script file
5. See the error

**Error prompt**

>CertTest
=======
Test_ 01
=======
Running MCrunch (v1.000.00y-mlb, 04-May-2009)
Reading "DLC2.3_1. out" (1.409390 MB)
**Rows=1201, Cols=135
Unable to Resolve Name 'FileInfo. Time'.**
Error ReadManyFiles>@ (Chan) eval (CalcChan (Chan). Eqn) (**Line 245**)
FileInfo. Time (:, NumIC+(CC))=cell2mat (arrayfun (@ (Chan) eval (CalcChan (Chan). Eqn), CC, 'UniformOutput', false));
Error ReadManyFiles (line 245)
FileInfo. Time (:, NumIC+(CC))=cell2mat (arrayfun (@ (Chan) eval (CalcChan (Chan). Eqn), CC, 'UniformOutput', false));
Error MCrunch (**line 22**)
ReadManyFiles (FileList, TitleLine, NamesLine, UnitsLine, FirstDataLine, CalcChan);
Error CertTest (**line 32**)
**MCrunch'Test_ 01. mcru '**

The MATLAB running files have not been modified and are consistent with the official downloaded files.
![image](https://github.com/OpenFAST/openfast/assets/115353218/f5d980b8-c30a-480c-95c2-941ea67215d9)

Can you tell me how to run the CertTest. m script file in the CertTest folder normally in MATLAB?
Thank you very much for your time in advance.
Best regards

**Comment by jjonkman** [comment]
Dear @1codecopyer.

Regarding the MCrunch error you are receiving, a similar question was asked and answered in the following topic on our forum: [MCrunch - #10 by Mark.Byers](https://forums.nrel.gov/t/mcrunch/2178/10) (see my post dated Feb 25, '21).

Best regards,

**Comment by 1codecopyer** [comment]
Thank you very much for your reply. Following the comments on the m file, the CertTest. m script program can run normally and generate images.
