### ISSUE TITLE
Is YawBrRDyt included in YawBrTDxt?

### ISSUE THREAD

**Issue by AssiduousAsule** [OpenFAST/openfast#1847]
Hello, I have a question to ask. When only considering the deflection of the tower, is the TTDspFA calculated in Openfast strictly the displacement along xt in six degrees of freedom? What I mean is whether it includes the displacement of the tower top caused by the pitch motion of the tower top around the tower base. Because when I thought about it, I realized that if I only looked at the structure, does the tower top surge in strict six degrees of freedom not exist.
As shown in the following figure：
![vvv](https://github.com/OpenFAST/openfast/assets/103891371/9a22e5e5-f241-4356-a201-9a5a57c7b1e3)
When I wanted to obtain the superposition effect of six degrees of freedom motion on wind speed, I found four parameters: YawBrTDxt, YawBrRDyt, PtfmTDxi, and PtfmRDyi. Can I convert the calculation results of these four parameters into velocity and add them to the wind speed?

**Comment by jjonkman** [comment]
Dear @AssiduousAsule,

I'm not sure I fully understand your question.  Certainly the tower-top velocity computed by OpenFAST includes the contributions of platform surge, platform pitch, and tower deflection from tower bending.  But I'm not sure how you are differentiating between tower surge and tower pitch.  In reality, the tower bends, which causes both translation and rotation of the tower top.

ElastoDyn output `TTDspFA` is the translation of the tower-top only associated with tower bending (not including platform surge and pitch).

ElastoDyn can output the absolute translational velocity of the tower top via outputs YawBrTVxp, etc., but those outputs are in expressed in the tower-top (p) coordinate system.

Best regards,

**Comment by AssiduousAsule** [comment]
Dear @jjonkman ,
Your answer is very useful. Then I will simplify my question: if I want to obtain the displacement of the tower tube bending in the x-axis direction based on the tower base as the coordinate system, can I directly use YawBrTDxt data. Or YawBrTDxt+sin (YawBrRDyt) * Lt, where Lt refers to the height from the tower top to the tower base. Because I found that the YawBrTDxt and sin (YawBrRDyt) * Lt data in ElastoDyn are very similar. Sorry, I am mainly unable to determine if there is a simple xt direction displacement of the tower like a semi floating foundation.
![11](https://github.com/OpenFAST/openfast/assets/103891371/ce52af4d-87a5-4fb4-819b-c51206758dda)

Best regards,

**Comment by jjonkman** [comment]
Dear @AssiduousAsule,

`YawBrTDxt` is the elastic displacement of the tower-top in the xt (nominally surge) direction.  `YawBrRDyt` is the elastic rotation of the tower top.  If the elastic mode shape was a linear function, I would expect `YawBrTDxt` = SIN(`YawBrRDyt`)*Lt, but the mode shape is not likely a linear function.

I don't fully agree with either of your images, but the first one is closer to what I would expect.  I would say that for small rotations, the surge velocity of the tower top would equal the surge velocity of the platform, plus the pitch velocity of the platform multipled by the moment arm (Lt) plus the elastic velocity of the tower in the x direction (`YawBrTVxp`).

Best regards,

**Comment by AssiduousAsule** [comment]
I have received your reply and understand the meaning. Thank you very much for your answer.
