### ISSUE TITLE
MoorDyn v2: echo file missing

### ISSUE THREAD

**Issue by RBergua** [OpenFAST/openfast#1849]
**Bug description**
It seems that MoorDyn v2 is not producing an Echo file despite the flag being defined as True.  

**To Reproduce**
Any model from the r-test repository (https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast) that uses MoorDyn. 

**Expected behavior**
An output Echo file (*.ech).

**OpenFAST Version**
This issue has been observed in OpenFAST v3.5.1 and OpenFAST dev.

**Comment by andrew-platt** [comment]
@RyanDavies19 and @mattEhall, can you address this?

**Comment by RyanDavies19** [comment]
@RBergua the echo file capability was removed when MoorDyn was upgraded to v2 (#1086). Good point noticing that the flags are still in place. I will work on removing them with some other work I am doing.

**Comment by RyanDavies19** [comment]
@andrew-platt MoorDyn creates a log summary file that includes most all of the inputs. There are a couple things that still could be added though.

**Comment by RBergua** [comment]
@RyanDavies19 Is there a specific flag to enable this log summary? I'm only getting result files (*.out) from MoorDyn at the moment.

**Comment by andrew-platt** [comment]
If the log file only gets written when MoorDyn successfully initializes, then we will need to add the echo back in.  We will need some way to troubleshoot the input files in that case.

**Comment by RyanDavies19** [comment]
The flag is '1       writeLog' in the options section and a higher integer triggers more detailed output (at least in the C code it does). I talked with Matt about this today and am planning to finish getting all the details outputted to the log after I get pinned bodies completed.

**Comment by RyanDavies19** [comment]
@RBergua this can be closed, my PR removed echo file flags from things and updated the log file to include everything from the inputs
