### ISSUE TITLE
Yaw control and tilt control problems in Fast.farm

### ISSUE THREAD

**Issue by May0048** [OpenFAST/openfast#1858]
Dear,
I am a first year graduate student who just started to learn open fast, I would like to ask how to set the yaw and tilt Angle of the turbine in the upper and middle reaches of FAST.Farm? ServoDyn or Super Controller? 
Thanks!

**Comment by jjonkman** [comment]
Dear @May0048,

I'm not sure I fully understand your question, but static tilt and and yaw angles can be set within the ElastoDyn input file of each OpenFAST model within FAST.Farm.

If you are referring to active control at the turbine level, this is available for active control of yaw through the ServoDyn module of OpenFAST, but active tilt control is not currently supported by OpenFAST.

The super controller of FAST.Farm can be used to coordinate control across wind turbines within the wind farm.

Best regards,

**Comment by May0048** [comment]
> Dear @May0048,
> 
> I'm not sure I fully understand your question, but static tilt and and yaw angles can be set within the ElastoDyn input file of each OpenFAST model within FAST.Farm.
> 
> If you are referring to active control at the turbine level, this is available for active control of yaw through the ServoDyn module of OpenFAST, but active tilt control is not currently supported by OpenFAST.
> 
> The super controller of FAST.Farm can be used to coordinate control across wind turbines within the wind farm.
> 
> Best regards,

Dear @jjonkman 
Sorry, I didn't make the question clear. What I want to express is this situation.
![1699517075551](https://github.com/OpenFAST/openfast/assets/150214223/af905bb3-3f86-4cc6-b7a5-e6e8085886a5)
Is this your first case (set ElastoDyn input file)?

Best regards,

**Comment by jjonkman** [comment]
Dear @May0048,

Yes.  The example you show only involves static yaw and tilt angles that can be set within the ElastoDyn input.

Best regards,
