### ISSUE TITLE
How to determine the simulation time and time step?

### ISSUE THREAD

**Issue by neilasir** [OpenFAST/openfast#1859]
Dear @NRELAdmin 
May I ask how to determine the total run time and time step in the fst file when analyzing floating wind turbines using Openfast? Is there any relevant literature available for explanation?
![QQ图片20231108144115](https://github.com/OpenFAST/openfast/assets/128685265/fe41703a-2c0e-4ef5-a55d-576ba15e6b9e)

**Comment by jjonkman** [comment]
Dear @neilasir,

Guidance for selecting time steps has been discussed in many topics on our forum, e.g., see: [PTDM implementation - #16 by Jason.Jonkman](https://forums.nrel.gov/t/ptdm-implementation/4543/16).

The simulation length should be set to obtain good statistical reliability of the results (assuming you are exciting the floating turbine via turbulent inflow and/or irregular waves).  There is typically a trade-off between running many seeds of shorter simulations versus fewer seeds of longer simulations.  If you are applying IEC design standards for performing loads analyses, these standards recommend specific simulation lengths and numbers of seeds for specific load-case simulations.

Best regards

**Comment by neilasir** [comment]
Thank u so much!

Best regards
