### ISSUE TITLE
An error occurred while running MCrunch

### ISSUE THREAD

**Issue by May0048** [OpenFAST/openfast#1860]
![1699442804589](https://github.com/OpenFAST/openfast/assets/150214223/230f4c78-e9e8-4331-ae75-dc4273262910)
How to solve the missing.COMP file

**Comment by jjonkman** [comment]
Dear @May0048,

 _DelFile.m_ containing `function DelFile()` is source file of MCrunch.  Do you have the Source directory of MCrunch in your MATLAB search path?

Best regards

**Comment by May0048** [comment]
> Dear @May0048,
> 
> _DelFile.m_ containing `function DelFile()` is a source file of MCrunch. Do you have the _Source_ directory of MCrunch in your MATLAB search path?
> 
> Best regards

Dear @jjonkman 
Thanks for your reply, I have solved the above problem.

Best regards
