### ISSUE TITLE
Out-of-bounds errors in some arrays

### ISSUE THREAD

**Issue by jrood-nrel** [OpenFAST/openfast#187]
I've posted this on Slack, but I just realized I haven't made this an official issue yet, so I'm creating this to keep track of this problem and link it to Nalu-Wind.

We have OpenFAST coupled to Nalu-Wind and we have a regression test for this called `nrel5MWactuatorLine`. This test segfaults on all systems we test on due to errors in OpenFAST. Before the segfault existed we also had an out-of-bounds situation that didn't segfault. To be more specific, here are the errors I see:
OpenFAST commit `5f3e24a01f82cc878255695b7e04b33c10d1be8c` (July 18) has the old out of bounds problem that does not segfault, but nonetheless is going out of bounds:
```
At line 1157 of file /.../openfast/modules-local/openfoam/src/OpenFOAM.f90
68: Fortran runtime error: Index '8' of dimension 1 of array 'initout_ad%bladeprops%blspn' above upper bound of 7
```
OpenFAST commit `b7fb8017898aeb6b1578f7df5f0aa9a2e02dce06` (July 25) has the new out of bounds problem that does segfault:
```
At line 494 of file /..../openfast/modules-local/openfast-library/src/FAST_Library.f90
68: Fortran runtime error: Index '1' of dimension 1 of array 'turbine%ad%input%blademotion' above upper bound of 0
```
I am not an expert in the OpenFAST coupling we are employing so I don't know if Nalu-Wind is doing something it shouldn't, but I think @sayerhs is aware of the root causes of these errors and some fixes might already exist.

**Comment by rafmudaf** [comment]
@jrood-nrelcan you confirm that pull request #243 fixes this problem?

**Comment by jrood-nrel** [comment]
Yes, the OpenFAST coupling to Nalu-Wind appears to pass all tests with #243

**Comment by rafmudaf** [comment]
great, thanks.
