### ISSUE TITLE
plot_directivity.py included in aeroacoustics, subpackage of python-toolbox , can't run properly

### ISSUE THREAD

**Issue by 1codecopyer** [OpenFAST/openfast#1871]
Hello, everyone.
When I used Git to clone python- toolbox from OpenFAST repository and run the plot _ directivity.py , an official example under  subpackage called aeroacoustics. Although it can run, I am puzzled by the running results, as shown in the figure:
![image](https://github.com/OpenFAST/openfast/assets/115353218/7afc65b0-3af2-4a41-8c39-301c7ec89f2d)

Viewing input file IEA_ LB_ RWT AeroAcoustics_ 1. out, where the parameter Number of observers and the number of data columns obs are 2
![image](https://github.com/OpenFAST/openfast/assets/115353218/e175e7f3-6bfd-47f3-8b60-c3a8a4d6180c)

The condition num_ obs<3 is true, run the 'print ("Error: Need at least 3 observers to generate contour.")' code (i.e. the tricontourf function has not been executed)

The  important parameter num_ obs is affected by ` AA_ 1. Shape [1] ` .  I debug found AA_ 1. shape [1]==3, AA_ 1. shape [1] -1<3

![image](https://github.com/OpenFAST/openfast/assets/115353218/510f3a1e-bdf8-4df2-b963-962f250871c9)
![image](https://github.com/OpenFAST/openfast/assets/115353218/7c71557f-debe-48a9-95f9-5306c378523a)

Later, I tried other input files such as IEA_ LB_ RWT AeroAcoustics_ i. out (i=1 2 3 4), found that Number of observers: 2, all satisfy  num_ obs<3

**Summary**：
This code can only run under conditions that meet num_obs < 3 .The code  has an output result of `print ("Error: Need at least 3 observers to generate source.")`, which does not allow for the normal implementation of the source plot of SPL for each location function. Is  plot_ directivity.py needs to modify , If so, how can I modify it?

**Comment by 1codecopyer** [comment]
I modify the parameters in the code (such as num_obs=AA_1. shape [1], or modify if num_obs<2) to ensure that the else condition is true, with the aim of running the code after` else`. However, the code still reported an error, and the error prompt is:
![image](https://github.com/OpenFAST/openfast/assets/115353218/56ccb61e-bf31-4d50-a01c-08cc7b74d104)

**Comment by andrew-platt** [comment]
This should be posted to the python-toolbox repository, not here.  https://github.com/OpenFAST/python-toolbox/issues
