### ISSUE TITLE
Openfast problem running Hydrodyn

### ISSUE THREAD

**Issue by Americandream123** [OpenFAST/openfast#1875]
Hi, I'm using open fast to calculate the 5MW example for OC4 and I'm having the following problem when I change the platform model data to one of my own set model data: modeling
Partially submerged/spherical rods requires that the first/bottom-most element of the rod must
be completely submerged. This is not the case for MemberID 5. Thank you all for your help!
![f6221d0803801f8eb5e5f59d20e41ef](https://github.com/OpenFAST/openfast/assets/146064115/03c8016e-c530-468b-b3b2-9885b650c420)
![6cee201ea1dfc661e02b13b287260df](https://github.com/OpenFAST/openfast/assets/146064115/2c5e245c-3549-456c-9541-e8a883681057)
![b65494ac2bf3a07eb840a9ac28334aa](https://github.com/OpenFAST/openfast/assets/146064115/ef623d55-8ded-4a0c-9d0b-f88150b26ea8)
![4d0ccc0f8f5d9e249dee622e7ce151a](https://github.com/OpenFAST/openfast/assets/146064115/f2428ccc-592c-4097-af59-ee4d305f6503)

**Comment by Americandream123** [comment]
![d318a26343b55fdfbbbc3409a507d90](https://github.com/OpenFAST/openfast/assets/146064115/8ed558a4-b5f1-49fc-b29c-48fae40bd511)
![1ef5cb106b186afafced448b04b71cf](https://github.com/OpenFAST/openfast/assets/146064115/0b7a29ef-7eae-4a53-9c43-5b96cf11f277)


I'm building a 10MW model with open fast and the bottom three trusses are always cylindrical how do I build it into the rectangular shape shown below thanks for the help!

**Comment by Americandream123** [comment]
![e60065371e52ab33513b52d940c5c17](https://github.com/OpenFAST/openfast/assets/146064115/096e8e72-56f7-4f4e-b29a-54cc961694ea)
Here's the 10MW model drawing, with the draped swings below as prisms

**Comment by RBergua** [comment]
In the first message, OpenFAST complains that the flooded/ballasted part defined does not cover the bottom element within that member. This happens for the MemberID = 5 that is defined between JointID = 7 and JointID = 8. The z-coordinates for these joints are -15 m and -4 m, respectively. Since you are using a discretization of 1 m for that member (MDivSize), this means that the region between -15 m and -14 m was not completely flooded. However, looking at the second message, it seems that your input file has been changed since the filled members section is empty (NFillGroups = 0). Accordingly, you should not receive a message about filled/flooded members anymore. Can you confirm?

**Comment by RBergua** [comment]
For the rectangular members, HydroDyn only allows to include circular (tapered or straight) members. Therefore, you can only define isotropic hydrodynamic coefficients (i.e., the same hydrodynamic coefficients in the transversal direction). To account for two different hydrodynamic coefficients in two different directions (e.g., vertical and horizontal in your pontoons), you could combine cylindrical members with heave plates. See below for reference:
![image](https://github.com/OpenFAST/openfast/assets/33709140/426272b2-1b8e-4a8c-9616-5839e6b06181)

**Comment by jjonkman** [comment]
I would just add that we have plans to add direct support for modeling hydrodynamic members with rectangular cross sections in the strip-theory solution in a future release of HydroDyn.

Best regards,

**Comment by Americandream123** [comment]
Thank you for your answer to my query. One more small question for you I have the following problem when I do openfast modeling again, but I have checked each point carefully and there is no overlap resulting in zero length. Thank you for your help.
![3b9cd8e96e1e714c2b10d6679fa158e](https://github.com/OpenFAST/openfast/assets/146064115/a5273912-9c7d-4245-8ce0-962220fca62c)
![c3925caae6207a6302954c40e3f842b](https://github.com/OpenFAST/openfast/assets/146064115/e8578248-3cb1-40b0-90e4-881dfa62c34e)
![334569de27fca9fb5ca34e0f1b78907](https://github.com/OpenFAST/openfast/assets/146064115/971985ef-21f4-4fa3-b321-c92d9a4f038c)

**Comment by jjonkman** [comment]
It is not obvious to me why this error is showing up for your model.  I suggest trying to isolate the issue by eliminating members.  It may help to run the model in debug mode to identify the issue.

**Comment by luwang00** [comment]
In the MEMBERS section in your screenshot above, the two end joints of member 3 are identical, which would lead to a member of zero length.

**Comment by Americandream123** [comment]
Thank you for your answer, my problem is solved!
