### ISSUE TITLE
Simulation error level: FATAL ERROR.When i run the openfast_x64 5MW_OC4Semi_WSt_WavesWN.fst,there is an error i can't solve.

### ISSUE THREAD

**Issue by Bq2181** [OpenFAST/openfast#1885]
OpenFAST-v3.5.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 2021
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: May 17 2023
 - Time: 13:43:33
Execution Info:
 - Date: 11/19/2023
 - Time: 15:30:30+0800

OpenFAST input file heading:
    FAST Certification Test #25: NREL 5.0 MW Baseline Wind Turbine with OC4-DeepCwind semi
    configuration, for use in offshore analysis

Running ElastoDyn.
Nodal outputs section of ElastoDyn input file not found or improperly formatted.
Running AeroDyn.
AD15 Nodal Outputs: Nodal output section of AeroDyn input file not found or improperly formatted.
Skipping nodal outputs.
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 1)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 2, blade 1)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 3, blade 1)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 4, blade 1)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 2)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 2, blade 2)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 3, blade 2)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 4, blade 2)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 1, blade 3)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 2, blade 3)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 3, blade 3)
Warning: Turning off Unsteady Aerodynamics because polar has constant data. (node 4, blade 3)
Running InflowWind.
Running HydroDyn.
 Generating incident wave kinematics and current time history.
 Reading in WAMIT output with root name ".\../5MW_Baseline/HydroData/marin_semi".
 Computing radiation impulse response functions and wave diffraction forces.
 Calculating second order difference-frequency force using the full quadratic transfer function.
 Calculating second order sum-frequency force using the full quadratic transfer function.
Running MoorDyn (v2.0.0, 2022-12-08).
   This is MoorDyn v2, with significant input file changes from v1.
   Copyright: (C) 2022 National Renewable Energy Laboratory, (C) 2019 Matt Hall
   Parsing MoorDyn input file: .\NRELOffshrBsline5MW_OC4DeepCwindSemi_MoorDyn.dat
   Created mooring system:  3 lines, 6 points, 0 rods, 0 bodies.
   Finalizing initial conditions using dynamic relaxation.
   t=52  FairTen 1: 9.99020E+05, 1.00376E+06, 9.96932E+05
   Fairlead tensions converged to 1% after 52 seconds.
   MoorDyn initialization completed.
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows).

FAST_InitializeAll:SrvD_Init:BladedInterface_Init:The dynamic library
.\../5MW_Baseline/ServoData/DISCON_OC3Hywind.dll could not be loaded. Check that the file exists
in the specified location and that it is compiled for 64-bit applications.

 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.

D:\app\OpenFast\r-test-main\glue-codes\openfast\5MW_OC4Semi_WSt_WavesWN>

**Comment by Bq2181** [comment]
Now that this has been solved, I am missing a file.Thank you

**Comment by jjonkman** [comment]
Dear @Bq2181  ,

See a similar question asked and answered here: https://github.com/OpenFAST/openfast/discussions/1114.

Best regards,

**Comment by syhpiner** [comment]
Please bear with me
I met the same question, do you remember which file you miss?
Best regards
