### ISSUE TITLE
A question on turbulent wind speed generation

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#1890]
Hello, everyone.
I have a question on turbulent wind speed generation. The hub height of my turbine is 61.83 meters, and I want to generate a set of BTS files so that the average Wind1VelX in the output out file is 23 m/s, but in reality the average Wind1VelX is often greater than that, how do I do that? Here is my INP file,  I changed the suffix to txt for easier uploading.

[23m.txt](https://github.com/OpenFAST/openfast/files/13446865/23m.txt)

**Comment by jjonkman** [comment]
Dear @shipors,

Just a few comments/questions:
* I would generally expect that TurbSim will add turbulent fluctuations with zero mean atop the mean wind profile.  So, given that your TurbSim simulation is 600 s, I would expect that you'd get the correct mean wind speed if you process 600 s of simulation output.  Have you processed 600 s of simulation output?
* You mention a hub height of 61.83 m, but I see `HubHt` = `RefHt` set to 61.8 m in your TurbSim file; is there a reason you are not using 61.83 m exactly?
* I'm not too familiar with the `TurbModel` = "SMOOTH" turbulence model; is there a reason you are using that over more common turbulence models such as "IECKAI".

Best regards,

**Comment by shipors** [comment]
Thank you for your reply. I have resolved this problem. As you mentioned, after setting the TurbSim simulation to 200s, I obtained the desired average wind speed.
