### ISSUE TITLE
Error when compiling OpenFAST v3.5.1

### ISSUE THREAD

**Issue by relhamoud** [OpenFAST/openfast#1894]
Hello everyone,

I have started to compile OpenFAST recently more specifically OpenFAST v3.5.1
I use Visual Studio 2019. I downloaded Intel one API HPC toolkit and Intel one API Base toolkit. The latter contains MKL (Math Kernel Library)
I applied the steps from here: 
https://openfast.readthedocs.io/en/main/source/install/install_vs_windows.html

Then i obtain this error:

![Annotation 2023-11-27 181003](https://github.com/OpenFAST/openfast/assets/106849956/913c2bf9-5dbb-4b26-9c2f-e72f6ca94685)

I searched a lot between issues related to compiling OpenFAST with Visual Studio but i did not find anyone encountering this error.

Could you please help me ?

Best Regards,

Riad

**Comment by andrew-platt** [comment]
Hi Riad,

I have not seen that error before.  You may need to reinstall VS, then the Intel toolkits.  I can't think of any other ideas of what could cause this issue.

Regards,

**Comment by relhamoud** [comment]
In fact, i just click ok and click on Build solution and it works !!!! OpenFAST is compiled successfully :)

**Comment by AsIlll223** [comment]
Hi @andrew-platt 
I try to compile openfast v3.5.1 in double precision, and I follow the [https://openfast.readthedocs.io/en/main/source/install/index.html#vs-windows](url) on windows VS Studio 2019 with cmake. 
But I obtain this error:

![image](https://github.com/OpenFAST/openfast/assets/56946664/ea596fb3-6bc8-4a95-b5e1-dcd82d6ca378)

Could you please help me ?

Best Regards,
