### ISSUE TITLE
How does OpenFast calculate blade loads

### ISSUE THREAD

**Issue by Tomedssa** [OpenFAST/openfast#1916]
Hello everyone!Through reading some literature, I have seen the calculation formula of blade load, and the parameter blade load exists in the output data of OpenFast, so I want to know how to calculate blade load in OpenFast and where can I find the relative code?

**Comment by jjonkman** [comment]
Dear @Tomedssa,

Are you asking about the ElastoDyn module of OpenFAST?  ElastoDyn uses the load summation method. That is, the blade-root bending moments are calculated in ElastoDyn by integrating along the blade the applied aerodynamic pitching moments + ( radial vector ) x ( applied aerodynamic forces + gravitation forces - inertia forces ).  All of these forces, moments, and distances are vectors and are oriented with the blade as the blade deflects.

Best regards,

**Comment by Tomedssa** [comment]
Dear @jjonkman,
Thank you for your reply.The calculation you describe is exactly what I want to know，but when I read the ElastoDyn module,  I did not find the detailed calculation process for calculating blade root loads.Is this calculation process shown elsewhere?

**Comment by Tomedssa** [comment]
Your answer is very helpful to me. Thank you very much.
