### ISSUE TITLE
Compiling with MinGW

### ISSUE THREAD

**Issue by diegoscmo** [OpenFAST/openfast#192]
Hello,

I am trying to compile openfast-dev version with MinGW, but I have stumbled in a couple of problems.

For CMAKE, I used the suggested in https://github.com/OpenFAST/openfast/pull/68 :

```
cmake ^
   -DCMAKE_INSTALL_PREFIX=%install_folder% ^
   -DBUILD_SHARED_LIBS=ON ^
   -G "MinGW Makefiles" ^
   -DBLAS_LIBRARIES:FILEPATH="-lblas -L%folder_of_blas%" ^
   -DLAPACK_LIBRARIES:FILEPATH="-lblas -llapack -L%folder_of_lapack%" ^
   -DCMAKE_BUILD_TYPE=RELEASE ^
../
```

When compiling FAST_Subs.f90.obj, I get the same error reported in https://github.com/OpenFAST/openfast/issues/110, f951.exe: out of memory allocating 65536 bytes:

![image](https://user-images.githubusercontent.com/13876911/47102913-59a58a00-d214-11e8-8604-bf1e1a05c897.png)

To avoid this issue, I've changed my compiler from gfortran GNU 6.3.0 to an older 4.6.2. Now I get another error when Linking Fortran executable openfast.exe:

![image](https://user-images.githubusercontent.com/13876911/47102781-fca9d400-d213-11e8-9266-c2f99d6db40c.png)

Before this last error, another similar error already made me compile and have the minpack package, but now it looks like the functions are implicit in the code and having the package is not enough. I don't have enough experience with .c to make changes into numeric.c.

Any help is appreciated. Thanks!

**Comment by diegoscmo** [comment]
Update:
Redid everything with the newest version of lapack, msys2 and mingw-w64-x86_64-toolchain. Switching to 64 bits solved the f951.exe problem (I did retry with the latest 32bits mingw and got the same error).

What I got this time was slightly different. First I get a an error for conflicting types of fopen_s:
![image](https://user-images.githubusercontent.com/13876911/47456133-13b76b80-d7aa-11e8-8e6d-b97641f58e7d.png)
This was fixed by changing the pre-defined type that comes with mingw-toolchain, not a great solution, but allowed the compilation to proceed.

Then I got the same cminpack error:
![image](https://user-images.githubusercontent.com/13876911/47456196-3b0e3880-d7aa-11e8-8c7a-42bef9288cf5.png)
This was fixed by adding the following flag to CMAKE:
`-DCMAKE_C_FLAGS:STRING="-DCMINPACK_NO_DLL"`

It does compile, but I get a Segmentation Fault when I run it:
![image](https://user-images.githubusercontent.com/13876911/47456355-a821ce00-d7aa-11e8-9c69-cd43d26c1730.png)

Feels like I am close, but I ran out of ideas. Would really appreciate support of someone who already has compiled it with MinGW. Just for reference, this is what the dependency walker output looks like:
![image](https://user-images.githubusercontent.com/13876911/47456593-59c0ff00-d7ab-11e8-80fe-6695c711b404.png)

Thanks!

**Comment by rafmudaf** [comment]
@diegoscmo Could you try rerunning this from the [dev branch](https://github.com/openfast/openfast/tree/dev)? This bug was recently fixed in #201.

**Comment by bjonkman** [comment]
Regarding point #2: MAP++ defines `fopen_s` if it is not using Microsoft C. You could probably just change `#if !defined(_MSC_VER)` to `#if !defined(_MSC_VER) && !defined(_MINGW)` at the end of `outputstream.c` and the matching header definition in `outputstream.h`. There may be some compatibility issues with older versions of MinGW, though.

**Comment by diegoscmo** [comment]
@rafmudaf 

I've downloaded and tried to compile with your branch. In the end of compilation process the following error occured:

```
[100%] Linking Fortran executable openfast.exe
../../modules-ext/map/libmapcpplib.a(numeric.c.obj):numeric.c:(.text+0xffe): undefined reference to `__imp_lmder'
../../modules-ext/map/libmapcpplib.a(numeric.c.obj):numeric.c:(.text+0x1014): undefined reference to `__imp_enorm_'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [glue-codes\openfast\CMakeFiles\openfast.dir\build.make:111: glue-codes/openfast/openfast.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:2003: glue-codes/openfast/CMakeFiles/openfast.dir/all] Error 2
mingw32-make: *** [Makefile:129: all] Error 2
```

The error is different from before. Using `-DCMINPACK_NO_DLL` allowed for the compilation to finish.

(3) works on your branch: The "Estimated time for completion" message output was as expected, only one visible changing output. Using both the dev branch and yours, Sys*.f90 pointed by cmake is the same:

`-- Setting system file as: src/SysGnuWin.f90`

Diego

**Comment by rafmudaf** [comment]
@diegoscmo 

I hadn't included `MINGW` in the CMake configuration to automatically add the `CMINPACK_NO_DLL` flag. However, I've just pushed a new commit which should fix that.

Thanks
Rafael

**Comment by rafmudaf** [comment]
@diegoscmo, regarding @bjonkman's comment above, there's an open pull request which adds the specific line she mentioned and others: #68. Does that resolve the map build problems for MinGW?

**Comment by diegoscmo** [comment]
@rafmudaf, that fixes it, no modifications in both cmake and MinGW files were needed to compile and run with #68.

Thanks a bunch!
Diego

**Comment by rafmudaf** [comment]
Thanks for your help @diegoscmo
