### ISSUE TITLE
Pitch Control-Mechanical Loads

### ISSUE THREAD

**Issue by vicemora** [OpenFAST/openfast#1930]
Hello,
I'm trying to see how different pitch controllers deal with mechanical loads in a WT. I'm trying to propose a first approach to it.
So I'm looking for recommendations: Which OpenFAST outputs (from the output list) should I focus on in order to see how a pitch controller influences mechanical loads in a WT? I'm not looking for loads in a specific component; I'm just starting my approach from scratch. I'm just looking for recommendations to get the first step into my project with OpenFAST.

**Comment by jjonkman** [comment]
Dear @vicemora,

Pitch controllers are often used to reduce structural loads in the blades, drivetrain, or tower.  Common output load metrics include blade-root bending moments, shaft bending moments at the main bearing, and tower-top and tower-base bending and yaw moments.

Best regards,
