### ISSUE TITLE
openfast（the tower shadow effect）

### ISSUE THREAD

**Issue by sffgd** [OpenFAST/openfast#1933]
Dear author：     
There is a literature that says that "the tower shadow effect in fast is fixed and is regarded as in the average position", is the average position the azimuth corresponding to the average value of the tower shadow effect?

best regards！

**Comment by jjonkman** [comment]
Dear @sffgd,

I'm not exactly sure what that sentence is referring to.  Can you provide the citation and further background?

FYI: A brief overview of the tower shadow models available in AeroDyn are provided here: https://openfast.readthedocs.io/en/main/source/user/aerodyn/theory.html#tower-shadow-models.

Best regards,

**Comment by sffgd** [comment]
Dear jjonkman，
Thank you for your reply, and I'm going to read the FAST document carefully.
This is what I saw in the article, "Modeling aspects of a floating wind turbine for coupled wave-wind-induced dynamic analyses”In the 3.2 Aero-servo-elastic modeling section, it is mentioned that "For example, the HAWC2 considers moving tower."
shadows which attached to the tower while in FAST the tower shadow is fixed and is considered at the mean position", so first ask you what the average position means?
Literature links：https://doi.org/10.1016/j.renene.2012.12.006
Best regards,

**Comment by jjonkman** [comment]
Dear @sffgd,

That article is referring to an old limitation of AeroDyn in FAST whereby the tower shadow model assumed that the tower did not move.  So, this implementation was not valid for the modeling of floating offshore wind turbines.  However, the implementation of tower shadow was modified to support the motion of the tower many years ago and is available now if you enable tower shadow within the AeroDyn v15 module of OpenFAST.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman ，
Thank you so much, I found General Options in AeroDyn v15 and there are two models in it, Powles model and Eames model, but I was thinking about which model should I choose for the calculation? (If the floating wind turbine is in the open ocean and the wind and waves are combined on the wind turbine).

Best regards,

**Comment by jjonkman** [comment]
Dear @sffgd,

Both the Powles and Eames tower-shadow models are quite simply quasi-steady velocity deficit models.  The Eames model has some turbulence intensity (TI) dependence that the Powles model doesn't have.  But the shape of the velocity deficit can be tailored a bit in either model by calibrating the coefficients to known solutions (e.g., CFD or measurements).

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman ，
Thanks for the answer！

Best regards,
