### ISSUE TITLE
Doubts about wind turbines in TEST 11-14

### ISSUE THREAD

**Issue by AzureJi** [OpenFAST/openfast#1934]
Dear  @jjonkman 

I have read your Definition of a 5MW Reference Wind Turbine for Offshore System Development before, and now I would like to use the 1.5MW wind turbine from TEST 11. Is there a file similar to the 5MW wind turbine instruction?

Best regards,

**Comment by jjonkman** [comment]
Dear @AzureJi,

The OpenFAST model of the 1.5-MW wind turbine from the r-test is that of the WindPACT 1.5-MW baseline turbine, which is documented here: http://www.nrel.gov/docs/fy06osti/32495.pdf.

Best regards,

**Comment by AzureJi** [comment]
Dear @jjonkman 

I have benefited greatly. Thank you for your guidance. Thank you very much.

Best regards,
