### ISSUE TITLE
A question about generating modal shapes using linearization

### ISSUE THREAD

**Issue by ccccsdcc** [OpenFAST/openfast#1939]
Dear all,

I tried to employ the linearization functionality within OpenFAST to acquire the natural frequencies and normalised mode shapes of the support structure of an IEA 10MW monopile supported offshore wind turbine during a shutdown state.

To this end, I have utilized the 'AnalyzeModeShapes.m' to generate a set of .vtp files.

Which file should I generate the modal shapes from?  

Should my focus be on displacements, velocities, or another parameter in these .vtp files? 

I found that the velocity normalized in the "input.Mode2.LinTime1.ED_TowerLn2Mesh_motion.001.vtp" file seems to be closer to the mode shapes in this reference (OC6 Phase 2: Integration and validation of a novel soil-structure interaction model for offshore wind power design)

Thank you in advance for your help!

Best regards,

![1](https://github.com/OpenFAST/openfast/assets/69953140/6fa44069-2496-4d36-8d59-f6e8245b3211)
![2](https://github.com/OpenFAST/openfast/assets/69953140/a6c52088-7503-4e69-9dfe-cb5f614d1b4b)

**Comment by jjonkman** [comment]
Dear @ccccsdcc,

The VTP files generated in the mode shape visualization process are meant for visualization within VTK-based post-processing tools such as ParaView.  I would expect that you'd want to animate the system oscillating about a given mode shape.  In this context, the displacements are most useful.  I don't normally open up the VTP files to look at the raw data directly.

Best regards,

**Comment by ccccsdcc** [comment]
Dear jjonkman，

Thank you for your reply.
The nrel1_m4 and nrel2_m4 models in oc6 project ll appeared to use three methods to obtain the mode shapes of the structure.
![1](https://github.com/OpenFAST/openfast/assets/69953140/51937b58-47c0-440b-948b-36d88e8cf449)
![2](https://github.com/OpenFAST/openfast/assets/69953140/881b7a4e-4c98-460d-ad25-0359ad837177)
![3](https://github.com/OpenFAST/openfast/assets/69953140/79fd8b4b-5bb4-4014-a5c7-36bd8d38655d)
https://a2e.energy.gov/ds/oc6/oc6.phase2
![5](https://github.com/OpenFAST/openfast/assets/69953140/edea4945-3361-48de-b4e8-c423466ebe88)
https://www.nrel.gov/docs/fy21osti/79938.pdf
![4](https://github.com/OpenFAST/openfast/assets/69953140/1d95dcb3-0bb0-48e1-ab25-161ca2b7fa0e)
https://doi.org/10.1002/we.2698
I would like to use Openfast to obtain the modal shapes of the structure, as in the OC6 project ll.
For the second and third methods, do I need to perform free decay tests or apply white noise excitation in Openfast to identify modes based on the structural response?
How should I use Openfast for the first linearisation method?

Best regards,

**Comment by RBergua** [comment]
Dear @ccccsdcc,

The mode shapes in OC6 phase II were obtained by means BModes (making the necessary modifications to the inputs so the beams included were representative of the ElastoDyn and SubDyn modules) and checked by means of a FEM code in MATLAB. See below for reference:
![image](https://github.com/OpenFAST/openfast/assets/33709140/445e75ab-abf3-40fd-940d-1fa4abcc85fd)

Some tools (e.g., OpenFAST) have a linearization capability that provides information about the eigenfrequency and damping. While other tools may not have this capability. In those cases, alternative methods like a free-decay or broad-band excitations can be used to characterize the eigenfrequency and damping.

I hope that helps.

**Comment by ccccsdcc** [comment]
Dear @RBergua,
Thank you for your reply.
Best regards,
