### ISSUE TITLE
Damping ratios for U-Maine VolturnUS-S FOWT

### ISSUE THREAD

**Issue by andreowhite** [OpenFAST/openfast#1942]
Hi everyone:
Does anyone know where I can find the damping ratios for UMaine VolturnUS-S FOWT?

Thank you.

Regards,
AOAW

**Comment by jjonkman** [comment]
Dear @andreowhite,

 This is probably a better question for the IEA Wind 15-MW reference wind turbine repository: [https://github.com/IEAWindTask37/IEA-15-240-RWT/issues](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIEAWindTask37%2FIEA-15-240-RWT%2Fissues&data=05%7C02%7Cjason.jonkman%40nrel.gov%7C6fc78dbcf3b24c9f3e1e08dbfd7e6cac%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C638382491673678025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iWZotLSyNkiWcVt5bfVAsKxObzH629ZYsMrpyBZFc0c%3D&reserved=0).

Best regards,
