### ISSUE TITLE
About buoy in mooring line

### ISSUE THREAD

**Issue by axxyyyyyyyy378** [OpenFAST/openfast#1944]
Hello,

Does anyone know how to model a buoy in the mooring line (Moordyn v 2) ? Should I add “Body” to model the buoy? Could you give me some advice

<img width="824" alt="1702782363179" src="https://github.com/OpenFAST/openfast/assets/150985396/2508aa68-54af-44e4-a59f-f540c6d643b9">

Best regrads，

**Comment by RyanDavies19** [comment]
@axxyyyyyyyy378 for a surface piercing buoy, you will need to construct it from cylinders (rod objects in MoorDyn). If you are just modeling a simple cylinder then you don't need to use the body object. However if you want to use multiple cylinders then a body can be used to attach rods. When using rods attached to a body, the rods positions need to be defined relative to the body's reference frame. You can read more in the MoorDyn [documentation](https://moordyn.readthedocs.io/en/master/index.html).

**Comment by axxyyyyyyyy378** [comment]
@RyanDavies19 Long time no see. Thanks for your help, I have successfully realized the idea
