### ISSUE TITLE
Simulate wind turbine shutdown status

### ISSUE THREAD

**Issue by sffgd** [OpenFAST/openfast#1957]
hello，
     I want to simulate the motion response of a 15mw wind turbine under extreme shutdown conditions. How should I modify the file parameters？
 
Best regards，

**Comment by jjonkman** [comment]
Dear @sffgd,

By "extreme shutdown condition", are you referring to IEC design load case 5.1 involving an emergency stop?

Best regards,

**Comment by sffgd** [comment]
Dear@jjonkman 
More specifically, I would like to simulate the motion response of a 15MW-UMaineSemi wind turbine under typhoon passage. In my opinion, it can be discussed in two scenarios:

1.When a typhoon occurs, the wind turbine remains in a normal shutdown state (IEC design load case 6), and then I simulate the results in Openfast.
2. When a typhoon appears, it moves from far to near, and the wind speed also increases from small to large. At this time, the wind turbine state is referred to IEC design load case 5.1 involving an emergency stop
The above is my personal opinion. If there is anything wrong, please correct it!

Furthermore, I would like to simulate the first scenario in Openfast. Here are the steps for me to set the normal shutdown state

Step 1: In the ElastoDyn module, I set gendof (false), rotspeed (0), and BlPitch (1)~(3) to 90 degrees
Step 2: In the Servodyn module, I set PCMode to 0, HIGH-SPEED SHAFT BRAKE (HSSBrMode changed to 1, THSSBrDp and HSSBrDT changed from 9999.9 to 0), and GENERATOR AND TORQUE CONTROL (TimGenOf changed from 9999.9 to 0)
If there are any errors or shortcomings, please point them out!

Best regards,

**Comment by jjonkman** [comment]
Dear @sffgd,

Normal survival through storm events (including typhoon) are simulated with IEC load cases 6.X.  The passage of a typhoon eye wall is not a specific IEC load case, so, you'll have to apply your own assumptions to model this event.  I would not expect IEC load case 5.1 to apply to this event as 5.1 is about activation of the emergency stop button.

Normal storm event conditions are typically simulated without the brake applied to park the rotor; rather, the rotor should be simulated in an idling state (free to spin, without reaction torque applied).  The proper input-file settings in ElastoDyn, AeroDyn, and ServoDyn to simulating idling conditions are discussed in the following topic on our forum: https://forums.nrel.gov/t/parked-turbine-simulation/2007.

Best regards,

**Comment by sffgd** [comment]
Dear@jjonkman，

Thanks for your reply.
According to the above forum，I would prefer to model ain idling rotor，the significant parametres could be changed as follows:
AeroDynv15
WakeMod = 0
AFAerMod = 1
TwrAero=Ture

ServoDyn
GenTiStr = TRUE, TimGenOn > TMax
PCMode=0，VSControl=0，GenModel=1

ElastoDyn
GenDOF = ture
RotSpeed = 0
BlPitch(1,2,3)) = 90°

For this I have changed the aerodyn、servodyn and elastodyn， I have attached these files, please advice me on whether it is correct or not to setup parked condition.
Thanks,
[IEA-15-240-RWT-UMaineSemi_AeroDyn15.txt](https://github.com/OpenFAST/openfast/files/13808133/IEA-15-240-RWT-UMaineSemi_AeroDyn15.txt)
[IEA-15-240-RWT-UMaineSemi_ServoDyn.txt](https://github.com/OpenFAST/openfast/files/13808134/IEA-15-240-RWT-UMaineSemi_ServoDyn.txt)
[IEA-15-240-RWT-UMaineSemi_ElastoDyn.txt](https://github.com/OpenFAST/openfast/files/13808137/IEA-15-240-RWT-UMaineSemi_ElastoDyn.txt)

**Comment by jjonkman** [comment]
Dear @sffgd,

Yes, these settings look good to me for an idling rotor.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman,

 If I want to simulate a fixed blade, rather than an idling rotor state, would it be OK to set it up as follows? And is it correct to control the fixed position of the blades by changing Azimuth (0° to 120°)?

AeroDynv15
WakeMod = 0
AFAerMod = 1
TwrAero=Ture

ServoDyn
GenTiStr = TRUE, TimGenOn > TMax
PCMode=0，VSControl=0，GenModel=1

ElastoDyn
GenDOF = false
RotSpeed = 0
BlPitch(1,2,3)) = 90°

**Comment by jjonkman** [comment]
Dear @sffgd,

I agree with your settings for a parked (fixed) rotor.  Please note that technically the torque-related settings in ServoDyn are not strictly necessary because ElastoDyn will not use the generator torque coming from ServoDyn when `GenDOF` = FALSE, but the ServoDyn settings wont hurt anything either.

Best regards,

**Comment by sffgd** [comment]
Dear @sffgd，

Thank you for your reply！

 Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman，

Thank you for your reply！

Best regards,
