### ISSUE TITLE
Some problems about python-toolbox

### ISSUE THREAD

**Issue by May0048** [OpenFAST/openfast#1958]
In the running situation of Ex3 in FAST., what is the binary file represented by FFbin？Also, what is the reason that Ex3 does not report an error but does not output？

**Comment by jjonkman** [comment]
Dear @May0048,

I'm not sure I understand your question.  What do you mean by "Ex3"?  If this is a question about the Python Toolbox, I would suggest posting your question in that repository: https://github.com/OpenFAST/python-toolbox/issues.

Best regards,
