### ISSUE TITLE
Wind turbine blade input parameter problem

### ISSUE THREAD

**Issue by lingajiang** [OpenFAST/openfast#1976]
**Bug description**
Error in airfoil input data during calculation with aerodyn module

**To Reproduce**
Airfoil input data：
         12   NumBlNds           - Number of blade nodes used in the analysis (-)
  BlSpn        BlCrvAC        BlSwpAC        BlCrvAng       BlTwist        BlChord          BlAFID    BlCb    BlCenBn    BlCenBt
   (m)           (m)            (m)            (deg)         (deg)           (m)              (-)     (-)     (m)        (m)
 0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  2.00000e-02  1    0.0      0.0       0.0
 1.000000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  2.00000e-02  2    0.0      0.0       0.0
 2.000000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  3.60000e-02  3    0.0      0.0       0.0
 3.550000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  3.29000e-02  4    0.0      0.0       0.0
 5.100000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  2.94000e-02  5    0.0      0.0       0.0
 6.650000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  2.59000e-02  6    0.0      0.0       0.0
 8.200000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  2.24000e-02  7    0.0      0.0       0.0
 9.750000000000000e-01  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  1.88000e-02  7    0.0      0.0       0.0
 1.130000000000000e-01  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  1.53000e-02  8    0.0      0.0       0.0
 1.285000000000000e-01  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  1.18000e-02  8    0.0      0.0       0.0
 1.440000000000000e-01  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  8.30000e-03  9    0.0      0.0       0.0
 1.499000000000000e-01  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  6.75000e-03  9    0.0      0.0       0.0

**Expected behavior**
I plan to build a small-power wind turbine model (about 3w) through openfast. Currently, I am using aerodyn module to calculate the aerodynamic characteristics. The following errors appear in the output of the airfoil node. My data input sequence is indeed incremental, I do not understand the problem, could you please answer it.

**Screenshots, if applicable**
I plan to build a small-power wind turbine model (about 3w) through openfast. Currently, I am using aerodyn module to calculate the aerodynamic characteristics. The following errors appear in the output of the airfoil node. My data input sequence is indeed incremental, I do not understand the problem, could you please answer it.

**OpenFAST Version**
Running analysis type 1: one simulation
 Nodes positions for turbine 1, (at t=0, without base or RNA motion)
 Bse:   0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
 Twr:   0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
 Nac:   0.000000000000000E+000  0.000000000000000E+000  0.449999988079071
 Hub:   0.000000000000000E+000  0.000000000000000E+000  0.449999988079071
 Bld:   0.000000000000000E+000  0.000000000000000E+000  0.449999988079071
 Bld:   0.000000000000000E+000  0.000000000000000E+000  0.449999988079071
 Bld:   0.000000000000000E+000  0.000000000000000E+000  0.449999988079071
Running ADI.
Running AeroDyn.
AD15 Nodal Outputs: Nodal output section of AeroDyn input file not found or improperly formatted.
Skipping nodal outputs.
Dvr_InitCase:ADI_Init:AD_Init:ValidateInputData:Blade 1 nodes must be entered in increasing
elevation.
ValidateInputData:Blade 2 nodes must be entered in increasing elevation.
ValidateInputData:Blade 3 nodes must be entered in increasing elevation.

 AeroDyn Driver encountered simulation error level: FATAL ERROR

 Aborting AeroDyn_driver.

```
**************************************************************************************************
AeroDyn_driver

Copyright (C) 2023 National Renewable Energy Laboratory
Copyright (C) 2023 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

AeroDyn_driver-Unversioned from 18704086dad861ab13daf804825da7c4b8d59428
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 2021
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: Yes, number of threads: 24/24
 - Date: Mar 07 2023
 - Time: 15:42:58
Execution Info:
 - Date: 01/12/2024
 - Time: 20:45:15+0800

**System Information (please complete the following information):**
winds environment

**Additional context**
In the small wind turbine, how do you think the two parameters of BlCrvAC BlSwpAC are calculated accurately

**Comment by jjonkman** [comment]
Dear @lingajiang,

I suspect you are receiving the errors about "nodes must be entered in increasing elevation" because your 8th node is located out of sequence.  I believe you meant to use `BlSpn` = 9.750000000000000e-02, rather than the value of 9.750000000000000e-01 that you have used.

Best regards,

**Comment by lingajiang** [comment]
Hello, I have changed the parameter blspn
  BlSpn        BlCrvAC        BlSwpAC        BlCrvAng       BlTwist        BlChord          BlAFID    BlCb    BlCenBn    BlCenBt
   (m)           (m)            (m)            (deg)         (deg)           (m)              (-)     (-)     (m)        (m)
 0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  2.89500e+01  2.00000e-02  1    0.0      0.0       0.0
 1.000000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  2.89500e+01  2.00000e-02  2    0.0      0.0       0.0
 2.000000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  2.89500e+01  3.60000e-02  3    0.0      0.0       0.0
 3.550000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  2.01000e+01  3.29000e-02  4    0.0      0.0       0.0
 5.100000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  1.40000e+01  2.94000e-02  5    0.0      0.0       0.0
 6.650000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  1.00700e+01  2.59000e-02  6    0.0      0.0       0.0
 8.200000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  7.69000e+00  2.24000e-02  7    0.0      0.0       0.0
 9.750000000000000e-02  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  6.29000e+00  1.88000e-02  7    0.0      0.0       0.0
 1.130000000000000e-01  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  5.19000e+00  1.53000e-02  8    0.0      0.0       0.0
 1.285000000000000e-01  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  3.89000e+00  1.18000e-02  8    0.0      0.0       0.0
 1.440000000000000e-01  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  1.71000e+00  8.30000e-03  9    0.0      0.0       0.0
 1.499000000000000e-01  0.000000000000000e+00  0.000000000000000e+00  0.000000000000000e+00  1.20000e+00  6.75000e-03  9    0.0      0.0       0.0
But the same error still occurs. May I ask whether this error has anything to do with the parameter BlCrvAC BlSwpAC I set to 0?

**Comment by jjonkman** [comment]
Dear @lingajiang,

This error is only tied to BlSpn.  AeroDyn can certainly use `BlCrvAC` = `BlSwpAC` = 0.

I would suggest enabling `Echo` and seeing if the Echo file shows that the AeroDyn data is being read in properly.

Best regards,

**Comment by lingajiang** [comment]
Dear jjonkman
Combined with your guidance and suggestions, I have done the following three steps：
1.True         Echo               - Echo the input to "<rootname>.AD.ech"?  (flag)
2.Learn how to read echo files from the aerodyn module manual：The contents of an echo file will be truncated if AeroDyn encounters an error while parsing an input file. The error usually corresponds to the line after the last successfully echoed line.
3.======  General Options  ============================================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 True            = Echo                
 default         = DTAero              
 3               = WakeMod             
 1               = AFAeroMod           
 0               = TwrPotent           
 0               = TwrShadow           
 False           = TwrAero             
 False           = FrozenWake          
 False           = CavitCheck          
 False           = Buoyancy            
 False           = CompAA              
 unused          = AA_InputFile        
======  Environmental Conditions  ===================================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 1.225           = AirDens             
 1.225           = AirDens             
 1.464E-05       = KinVisc             
 1.464E-05       = KinVisc             
 335             = SpdSound            
 335             = SpdSound            
 103500          = Patm                
 103500          = Patm                
 1700            = Pvap                
 1700            = Pvap                
======  Blade-Element/Momentum Theory Options  ====================================================== [unused when WakeMod=0 or 3]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 1               = SkewMod             
 1.4726215563702 = SkewModFactor       
 1.4726215563702 = SkewModFactor       
 True            = TipLoss             
 True            = HubLoss             
 True            = TanInd              
 True            = AIDrag              
 True            = TIDrag              
 Default         = IndToler            
 500             = MaxIter             
======  Dynamic Blade-Element/Momentum Theory Options  ============================================== [used only when WakeMod=2]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 2               = DBEMT_Mod           
 4               = tau1_const          
======  OLAF -- cOnvecting LAgrangian Filaments (Free Vortex Wake) Theory Options  ================== [used only when WakeMod=3]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 OLAF.dat        = OLAFInputFileName   
======  Beddoes-Leishman Unsteady Airfoil Aerodynamics Options  ===================================== [used only when AFAeroMod=2]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 3               = UAMod               
 True            = FLookup             
======  Airfoil Information =========================================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 1               = AFTabMod            
 1               = InCol_Alfa          
 2               = InCol_Cl            
 3               = InCol_Cd            
 4               = InCol_Cm            
 0               = InCol_Cpmin         
 9               = NumAFfiles          
 Airfoils/Modell = AFNames             
 Airfoils/Modell =                     
 Airfoils/Modell =                     
 Airfoils/Modell =                     
 Airfoils/Modell =                     
 Airfoils/Modell =                     
 Airfoils/Modell =                     
 Airfoils/Modell =                     
 Airfoils/Modell =                     
======  Rotor/Blade Properties  =====================================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 True            = UseBlCm             
 NRELOffshrBslin = ADBlFile(1)         
 NRELOffshrBslin = ADBlFile(2)         
 NRELOffshrBslin = ADBlFile(3)         
======  Hub Properties ============================================================================== [used only when Buoyancy=True]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 0.0             = VolHub              
 0.0             = HubCenBx            
======  Nacelle Properties ========================================================================== [used only when Buoyancy=True]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 0.0             = VolNac              
0,0,0 NacCenB            - Position of nacelle center of buoyancy from yaw bearing in nacelle coordinates (m)
======  Tail fin Aerodynamics ========================================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 False           = TFinAero            
 unused          = TFinFile            
======  Tower Influence and Aerodynamics ============================================================ [used only when TwrPotent/=0, TwrShadow/=0, TwrAero=True, or Buoyancy=True]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 10              = NumTwrNds           
Tower Table Header: TwrElev        TwrDiam        TwrCd          TwrTI          TwrCb                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
Tower Table Header: (m)              (m)           (-)            (-)           (-)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
6.050000000000000e-02  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
1.210000000000000e-01  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
1.815000000000000e-01  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
2.420000000000000e-01  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
3.025000000000000e-01  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
3.630000000000000e-01  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
4.235000000000000e-01  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
4.840000000000000e-01  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
5.445000000000000e-01  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
6.050000000000000e-01  3.330000000000000e-02  8.000000000000000e-01  1.000000000000000e-01  0.0
======  Outputs  ====================================================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 False           = SumPrint            
 9               = NBlOuts             
1, 2, 3, 4, 5, 6, 7, 8, 9    BlOutNd             - Blade nodes whose values will be output  (-)
 0               = NTwOuts             
0    TwOutNd             - Tower nodes whose values will be output  (-)
OutList             - The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels, (-)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
"RtAeroCp"
"RtAeroCq"
"RtAeroCt"
"RtAeroPwr"
"RtSpeed"
			
END of input file (the word "END" must appear in the first 3 columns of this last OutList line)



           12  NumBlNds       - Number of blade nodes used in the analysis (-)
  BlSpn        BlCrvAC        BlSwpAC        BlCrvAng       BlTwist        BlChord          BlAFID    BlCb    BlCenBn    BlCenBt

   0.0000    0.0000    0.0000    0.0000   18.9500    0.0200         1   0.0000    0.0000    0.0000
   1.0000    0.0000    0.0000    0.0000   18.9500    0.0200         2   0.0000    0.0000    0.0000
   0.0200    0.0000    0.0000    0.0000   28.9500    0.0360         3   0.0000    0.0000    0.0000
   0.0355    0.0000    0.0000    0.0000   20.1000    0.0329         4   0.0000    0.0000    0.0000
   0.0510    0.0000    0.0000    0.0000   14.0000    0.0294         5   0.0000    0.0000    0.0000
   0.0665    0.0000    0.0000    0.0000   10.0700    0.0259         6   0.0000    0.0000    0.0000
   0.0820    0.0000    0.0000    0.0000    7.6900    0.0224         7   0.0000    0.0000    0.0000
   0.9750    0.0000    0.0000    0.0000    6.2900    0.0188         7   0.0000    0.0000    0.0000
   0.1130    0.0000    0.0000    0.0000    5.1900    0.0153         8   0.0000    0.0000    0.0000
   0.1285    0.0000    0.0000    0.0000    3.8900    0.0118         8   0.0000    0.0000    0.0000
   0.1440    0.0000    0.0000    0.0000    1.7100    0.0083         9   0.0000    0.0000    0.0000
   0.1499    0.0000    0.0000    0.0000    0.1200    0.0068         9   0.0000    0.0000    0.0000



           12  NumBlNds       - Number of blade nodes used in the analysis (-)
  BlSpn        BlCrvAC        BlSwpAC        BlCrvAng       BlTwist        BlChord          BlAFID    BlCb    BlCenBn    BlCenBt

   0.0000    0.0000    0.0000    0.0000   18.9500    0.0200         1   0.0000    0.0000    0.0000
   1.0000    0.0000    0.0000    0.0000   18.9500    0.0200         2   0.0000    0.0000    0.0000
   0.0200    0.0000    0.0000    0.0000   28.9500    0.0360         3   0.0000    0.0000    0.0000
   0.0355    0.0000    0.0000    0.0000   20.1000    0.0329         4   0.0000    0.0000    0.0000
   0.0510    0.0000    0.0000    0.0000   14.0000    0.0294         5   0.0000    0.0000    0.0000
   0.0665    0.0000    0.0000    0.0000   10.0700    0.0259         6   0.0000    0.0000    0.0000
   0.0820    0.0000    0.0000    0.0000    7.6900    0.0224         7   0.0000    0.0000    0.0000
   0.9750    0.0000    0.0000    0.0000    6.2900    0.0188         7   0.0000    0.0000    0.0000
   0.1130    0.0000    0.0000    0.0000    5.1900    0.0153         8   0.0000    0.0000    0.0000
   0.1285    0.0000    0.0000    0.0000    3.8900    0.0118         8   0.0000    0.0000    0.0000
   0.1440    0.0000    0.0000    0.0000    1.7100    0.0083         9   0.0000    0.0000    0.0000
   0.1499    0.0000    0.0000    0.0000    0.1200    0.0068         9   0.0000    0.0000    0.0000



           12  NumBlNds       - Number of blade nodes used in the analysis (-)
  BlSpn        BlCrvAC        BlSwpAC        BlCrvAng       BlTwist        BlChord          BlAFID    BlCb    BlCenBn    BlCenBt

   0.0000    0.0000    0.0000    0.0000   18.9500    0.0200         1   0.0000    0.0000    0.0000
   1.0000    0.0000    0.0000    0.0000   18.9500    0.0200         2   0.0000    0.0000    0.0000
   0.0200    0.0000    0.0000    0.0000   28.9500    0.0360         3   0.0000    0.0000    0.0000
   0.0355    0.0000    0.0000    0.0000   20.1000    0.0329         4   0.0000    0.0000    0.0000
   0.0510    0.0000    0.0000    0.0000   14.0000    0.0294         5   0.0000    0.0000    0.0000
   0.0665    0.0000    0.0000    0.0000   10.0700    0.0259         6   0.0000    0.0000    0.0000
   0.0820    0.0000    0.0000    0.0000    7.6900    0.0224         7   0.0000    0.0000    0.0000
   0.9750    0.0000    0.0000    0.0000    6.2900    0.0188         7   0.0000    0.0000    0.0000
   0.1130    0.0000    0.0000    0.0000    5.1900    0.0153         8   0.0000    0.0000    0.0000
   0.1285    0.0000    0.0000    0.0000    3.8900    0.0118         8   0.0000    0.0000    0.0000
   0.1440    0.0000    0.0000    0.0000    1.7100    0.0083         9   0.0000    0.0000    0.0000
   0.1499    0.0000    0.0000    0.0000    0.1200    0.0068         9   0.0000    0.0000    0.0000
   I noticed that in the output node, the output of the second node is 1.000, but I input 1.0000e-02. As a student who just comes into contact with openfast learning modeling, I don't understand why it reads and outputs in this way. I am very glad to hear your opinion

**Comment by lingajiang** [comment]
I think I have found a solution to the problem. Thank you for your answer. I wish you success in your work.
