### ISSUE TITLE
MoorDyn: unexpected behavior at initialization

### ISSUE THREAD

**Issue by RBergua** [OpenFAST/openfast#1978]
**Bug description**
I'm modeling a system in OpenFAST with buoyant cans as follows:
![image](https://github.com/OpenFAST/openfast/assets/33709140/1a5a51dd-12b0-4b32-95a7-4b163c344ff6)

The cans are modeled in MoorDyn by means of rods and I'm using the CoupledPinned attachment available in OpenFAST dev (4fafe68) to allow the 3 rotational DOFs at the connection with the legs (like a ball joint).

For these tests, I consider still water conditions and no inflow wind (i.e., it's a gravity-only condition). I run these tests with a rigid system. I only account for the rotation of the cans (CoupledPinned attachment in MoorDyn) and the 6 rigid DOFs of the platform.

When I use TmaxIC = 0 s (no initial computation in MoorDyn), I can observe that the platform pitch oscillates around -1.9 deg and the cans experience rotation amplitudes smaller than 1.5 deg. This behavior is the expected one.
![image](https://github.com/OpenFAST/openfast/assets/33709140/8aaf9916-c278-4031-8cd4-c71be23002d1)

However, if I define a given time to compute the initial condition (e.g., TmaxIC = 100), I get converged magnitudes for the fairlead tensions:
![image](https://github.com/OpenFAST/openfast/assets/33709140/5c25d965-979f-48a2-a802-efecbf400b38)

But the cans are all over the place (in the below image you can see that the cans are tilted around 85 deg at t = 0 s in OpenFAST, so the cans are almost horizontal instead of vertical) and the platform pitch behavior is erratic due to the very large motion of the cans:
![image](https://github.com/OpenFAST/openfast/assets/33709140/9657eb27-4077-4291-b4b7-12289e1934cf)

Summarizing: Using TmaxIC different than 0 seconds in MoorDyn results in unexpected responses when using rods and CoupledPinned attachments.

Additional note: Maybe this large initial transient is related to the crashes experienced in MoorDyn when using Coupled attachments ("Warning: extreme pitch moment from body-attached Rod") that we commented offline.

**Comment by RyanDavies19** [comment]
@RBergua Have you tried with CdScaleIC = 1? Maybe the larger drag in initialization is causing issues. Also, the way that the IC generation is set up is based on line tension convergence, so while the line tensions converge that doesn't necessarily mean the bodies positions converge.

**Comment by RBergua** [comment]
Note that the rods in MoorDyn (buoyant cans) are defined in the upright position (i.e., vertical). So, the cans should maintain that vertical or almost vertical position if MoorDyn is properly accounting for the hydrostatics during the initialization. The only reason that would explain the cans tilting to almost 90 deg is the mean sea level not being properly accounted with regarding to the cans position or the hydrostatics not being considered properly. 

For reference, below yo can see the results when CdScaleIC = 1. In the above results, CdScaleIC used was 2. In this case, the cans are tilted around 77 deg (before they were tilted around 85 deg).

![image](https://github.com/OpenFAST/openfast/assets/33709140/df8543b4-ff53-421a-af77-d8cfdb648419)

**Comment by andrew-platt** [comment]
@RBergua, what does the platform heave look like?  Is it possible the initial heave is set incorrectly allowing the cans rest at a large angle during initialization, but stabilize to near vertical after the heave settles?

**Comment by RBergua** [comment]
The OpenFAST model is defined very close to the heave equilibrium position. The rods (buoyant cans) are 18 m long and half of the can (9 m) is submerged. The cans would become hydrostatically unstable (i.e, they would tip over) when the platform moves upwards around 7 m. This condition is never met in my simulations (OpenFAST and analytical).

Below you can see the evolution of platform pitch, platform heave and the can rotation when the initial conditions are not considered in MoorDyn. Like before, the platform pitch oscillates around -1.9 deg and the cans experience rotation amplitudes smaller than 1.5 deg. The platform heave oscillates around 0.2 m. This is the expected behavior.
![image](https://github.com/OpenFAST/openfast/assets/33709140/838aa3f1-16f1-4561-80c6-61ad2bba0b4b)

Below you can see the same outputs when considering the initial conditions in MoorDyn. In this case, all magnitudes are very erratic. This results in a large initial transient. This behavior is not expected.
![image](https://github.com/OpenFAST/openfast/assets/33709140/d6ecfccf-7d10-402f-be1b-1854cc565e64)
 
Below you can see the tilt orientation of the 6 bodies representative of the angle described by the can bundles per leg (the system has 6 legs):
![image](https://github.com/OpenFAST/openfast/assets/33709140/ad8098e1-2733-4c3e-aed3-890f75017f2a)

Below you can also see the submergence of the cans (i.e., can length percentage that is wet):
![image](https://github.com/OpenFAST/openfast/assets/33709140/72689013-6cdb-4e3d-b8d0-b6032c3cb5c3)

As it can be observed, the cans move from a completely submerged condition to a completely dry condition. This non-physical behavior only appears when the initial computation in MoorDyn is considered.

**Comment by andrew-platt** [comment]
Good findings!  It sort of looks like MD is not considering the entire can buoyancy during the initialization.  Maybe just part of the can is considered, or perhaps the still water level is miscalculated?

If there is an issue with the water level, it may have been fixed in the `dev-unstable-pointers` with https://github.com/OpenFAST/openfast/pull/1804.  This has not been merged into the `dev` branch yet.

**Comment by RBergua** [comment]
Thanks for the feedback, @andrew-platt. For reference, I'm defining MSL2SWL = 0. So, I guess the mean sea level is properly considered. But I agree that there seems to be a hydrostatic calculation issue.

**Comment by RyanDavies19** [comment]
@RBergua Are you still running the cans as rods with 36 segments?

**Comment by RyanDavies19** [comment]
I will look into this more then. That submergence does look strange to me. I have run USFLOWT in MD standalone as a free bodies and a coupled pinned bodies (with the translational positions fixed at their starting values for coupled pinned bodies). In both cases the submergence begins as 0.5 regardless of whether I use initial conditions or not.

**Comment by mattEhall** [comment]
We have a fix in the works  https://github.com/mattEhall/openfast/commit/3a7c63e266c2ee97b1b51d819f5ca5fbff8cc890

**Comment by RyanDavies19** [comment]
See #2005 for the PR with the bug fix for this.

**Comment by RBergua** [comment]
I confirm that this bug has been solved with commit [e39453a](https://github.com/OpenFAST/openfast/commit/e39453af79726c5cb23dd6e2b2389da6b6dc2960) in OpenFAST dev. 
![image](https://github.com/OpenFAST/openfast/assets/33709140/12ed3fbd-4dbc-481a-8988-183e11ae6fda)
![image](https://github.com/OpenFAST/openfast/assets/33709140/f3d64e79-516a-4d4f-bd28-56e2281edad9)
Thanks for the support! 👍
