### ISSUE TITLE
Modal analysis

### ISSUE THREAD

**Issue by 3sdb** [OpenFAST/openfast#1984]
Everyone
I have a question.
Can openfast perform modal analysis? How to do it?

**Comment by jjonkman** [comment]
Dear @3sdb,

Yes.  The use of the linearization functionality of OpenFAST, followed by Eigenanalysis, to derive the full-system natural frequencies, damping, and mode shapes--including generation of Campbell diagrams--has been discussed many times here in OpenFAST issues/discussions and on our forum (https://forums.nrel.gov/).

Best regards,
