### ISSUE TITLE
How to calculation the MASS MATRIX in the Cummins Equation?

### ISSUE THREAD

**Issue by Melancho7ee** [OpenFAST/openfast#1991]
Dear All,

I have been working on modeling a floating offshore wind turbine (FOWT) following "ss-fitting-manual", and the Cummins Euqation is shown in the figure below.

![image](https://github.com/OpenFAST/openfast/assets/116873649/702d2718-e905-4155-8f61-9557f02a9ec9)

My question is that how can I obtain the **mass matrix M**? **Especially for the SURGE and SWAY DOF.** 
As far as I am concerned: 
1) The mass of heave DOF is somewhat related to the total mass of the FOWT;
2) The mass (more specifically, moment of Inertia) of pitch, roll and yaw DOF can be calculated by Parallel Axis Theorem, which I found on the NREL Forum [(https://forums.nrel.gov/t/rotor-and-nacelle-mass-moment-of-inertia-tensors/2015)].

So My Question Is: how to calculate the mass of SURGE and SWAY DOF. Intuitively, it seems that these two translational  should not have the so-called mass. Am I right? If not, how can I obtain these values?

Thanks

**Comment by Melancho7ee** [comment]
It suddenly occurs to me that the Mass of Surge, sway and heave should be the total mass of a FOWT.....
Take the NREL 5MW ITI Barge for example, the Total mass is:
HubMass=56780; NacMass=240000; PtfmMass=5.452E+06; TwrMass=347460; BldMass=17740;
I_Mass_Surge = HubMass + NacMass + PtfmMass + TwrMass + 3*BldMass;
                         = 56780   + 240000  + 5.452E+06 + 347460 + 3*17740;
                         = 6.14946E+06 KG;

**Comment by jjonkman** [comment]
Dear @Melancho7ee,

The 6x6 rigid-body mass matrix from the documentation you refer to should should have the following form:

![image](https://github.com/OpenFAST/openfast/assets/6108256/fecae2a1-7e86-4d93-9874-1e65d69174ea)

where
m = full-system mass, including ballast
(x_g,y_g,z_g) = center of mass relative to the platform reference point
(I_11,I_12,…I_33) = inertias relative to the platform reference point

Best regards,
