### ISSUE TITLE
[FOWT][HydroDyn]How to tune the damping matrix and drag coefficients through a series of free decay test? 

### ISSUE THREAD

**Issue by getChaos22** [OpenFAST/openfast#2006]
Hello everyone,

Recently, I am trying to figure out how to tune the damping matrix and Morison drag coefficients through a series of free decay tests. I took the DeepCwind semi-submarine platform and NREL 5MW wind turbine as an example case, and used the damping ratio given by the [MARIN-2011](https://doi.org/10.1115/OMAE2014-24172) test (as shown in the following picture) to tune the linear damping matrix and drag coefficient. 

![image](https://github.com/OpenFAST/openfast/assets/120010727/525240ff-d622-4c16-84c8-14d9e3dd9f7b)
Damping ratio of surge from MARIN-2011 and MARIN-2013 tests

I have tried three sets of damping coefficients, but the damping ratios I obtained is largely different from those of MARIN-2011 test (as shown in the following picture).

![image](https://github.com/OpenFAST/openfast/assets/120010727/7e30d6a1-6ac6-4975-9236-5e5366a450ac)

The damping coefficients that I have used are: (I have put the following three cases in the attachment)
 **Damping1**: Base column: Cd=0.68, upper column: Cd=0.61, main coumn: Cd=0.56, axial Cd of heave plate: 9.6, and a blank damping matrix. (The coefficients are taken from the semi-submarine case in [r-test](https://github.com/OpenFAST/r-test/blob/dev/glue-codes/openfast/5MW_OC4Semi_WSt_WavesWN/NRELOffshrBsline5MW_OC4DeepCwindSemi_HydroDyn.dat))

**Damping2**: Base column: Cd=1.6, main and upper column: Cd=0.4, axial Cd of heave plate: 8.2, damping matrix: B11=7.5E4, B55=3.1E7. (The coefficients are taken from the NREL's setting in the [OC6 project](https://iopscience.iop.org/article/10.1088/1742-6596/1618/3/032033/meta)  )

**Damping3**: Base column: Cd= 2.0, main and upper column: Cd=0.4, axial Cd of heave plate: 8.2, damping matrix: B11=35.5E4, B55=3.1E7. (This one is tuned by myself basing on the damping ratio around the initial amplitude of 8.5 m)

The results of the above damping coefficients are much lower or higher than the test data. Further more, it seems like tuning the damping coefficients cannot change the tendency of the damping ratio curves, but only has an effect of translation. 

So I came across with a problem on how to calibrate these damping coefficients and drag coefficients basing on the test data. Is there anything wrong with my tuning method. Or what is the correct way to calibrate these coefficients? 

Do you have any idea about this problem?  

Best Regards

Chao Li

Attachment: 
[free_decay.zip](https://github.com/OpenFAST/openfast/files/14045701/free_decay.zip)

**Comment by luwang00** [comment]
Hi @getChaos22 

Thanks for sharing your results. Tuning the damping coefficients and drag coefficients can be a very challenging exercise.

There are a couple of factors to consider here. First, when comparing to free-decay experiments, we typically need to remove the first one or two cycles from the experimental measurements. This is because the first few cycles can be heavily influenced by start-up flow effects that cannot be replicated in mid-fidelity models like OpenFAST that essentially relies on sources of linear and/or quadratic damping. 

Second, the hydrodynamic damping and drag coefficients are highly sensitive to flow conditions. Coefficients tuned to free-decay experiments, even if matching perfectly, might not be applicable to wave conditions. In fact, the coefficients can also be sensitive to the sea state. The coefficients you referenced from r-tests and OC6 were not necessarily tuned to free decay. In many cases, they are simply chosen based on experience.

Lastly, it is correct that adjusting the linear damping coefficients will only cause a vertical shift in your damping ratio curve. The variation of damping ratio as a function of motion amplitude can only be influenced by the drag coefficients or the quadratic damping coefficients in OpenFAST. You can potentially adjust those to better match the free-decay experiment. However, going back to the first point, matching the experiment with, for example, very high drag coefficients might not result in a valid model.

**Comment by getChaos22** [comment]
Hi @luwang00 

Thanks for your fast reply. The information is really helpful.

Now I am trying to adjust the drag coefficients and quadratic damping coefficients rather than only the linear damping coefficients. 

But there is still one thing that confused me. You mentioned that the damping coefficients tuned by the free-decay test may not be suitable to other wave conditions. This is very clear to me because I have read your 2022's paper published in Renewable Energy. As I understand it, the paper proposed a couple of methods to improve the prediction of the platform's motion in irregular waves. These methods are more reasonable to account for the viscosity effect than the original model in OpenFAST. The drag coefficients of the new methods originated from the ones that calibrated by the free-decay test data, but some modifications had been made. Therefore, with these methods, OpenFAST can not only retain the correct behavior in free-decay but also give good predictions of platform motions in irregular waves. But in your last comment, you mentioned that the coefficients from OC6 were not necessarily tuned to free decay.  It is this contradiction that confused me. 

What I want to do is to follow your work: calibrate the damping coefficients by free-decay at first, then correct the model of OpenFAST by the methods you proposed, so that a model and coefficients that can satisfy both free-decay and low-frequency motion can be obtained. Have I understood correctly?

Best regards

Chao Li

**Comment by luwang00** [comment]
@getChaos22

Regarding the hydrodynamic coefficients from OC6, I didn't realize you are referring specifically to the paper you linked. I was thinking about the main OC6 collaboration paper that discussed many models and different tuning.

For the paper you linked, I do believe the model should give reasonable agreement with the free-decay experiments in term of the overall level of damping, at least over the portion of the time series we looked at at the time. I think you figure also confirms showing comparable level of damping between the experiment and Damping 2 over the middle portion of the decay time series. However, I don't think the model would match the experimental damping ratio exactly on a cycle-to-cycle basis.

I agree that you can start with tuning to free decay. That can give you a reasonable starting point, but some modification is needed afterwards to match wave response as you pointed out.

**Comment by getChaos22** [comment]
Hi @luwang00,

Thank you for your reply and guidance. I think I almost understand. There are just two things that I want to confirm with you. 

You mentioned that Damping 2 in my figure shows a comparable level of damping with the experiment over the **middle portion of the time series**. Do you mean the range of initial amplitude around 1 m ~ 2.5 m (As I marked in the following figure)? 
![image](https://github.com/OpenFAST/openfast/assets/120010727/5821cdaf-79ab-4aef-b557-252dd8608c2f)

The cycle-to-cycle basis means the whole initial amplitude range that the test implemented (around 0.5 m ~ 8 m ). Is that right?

Thanks again.

Chao Li

**Comment by luwang00** [comment]
Hi @getChaos22,

Yes, the region you highlighted is the "middle portion" I was referring to. With mid-fidelity modeling, we usually drop the first few cycles from the experiment and run/tune the models from the second or third cycle.

By cycle-to-cycle, I meant how the damping ratio changes from one period to the next, even within the "middle portion." This can also be difficult to replicate exactly, but as shown in your figure, the damping ratio is approximately 4% in the box. This is more or less consistent between the model and the experiment.

**Comment by getChaos22** [comment]
Hi @luwang00,

Thank you for the explanation. 

Sorry for keeping bothering you. But just one more question to consult, which is how to conduct free-decay test (basin test or numerical test) to obtain the damping ratio curve? Do we need to conduct several free-decay tests with different initial amplitudes? Or just carry on one free-decay test with a large amplitude, then calculate the damping ratios at different peaks？

Best regards.

Chao Li

**Comment by luwang00** [comment]
Hi @getChaos22,

I don't have a definitive answer to your question. Certainly, you'd get more information by conducting several free-decay tests/simulations with different initial amplitudes. However, if the different tests give different damping ratios, it's not clear how to integrate that into the model. I would say, as a start, perform one free-decay test/simulation with an initial offset approximately equal to the largest excursion you'd expect from a deployed system. This way, the decay test is at least representative of the level of motion in waves. Of course, the expected motion is not known beforehand, so you might need to just start from somewhere and iterate a few times.

**Comment by getChaos22** [comment]
Hi @luwang00,

Many thanks for your ongoing assistance!

Best regards

Chao Li
