### ISSUE TITLE
turbsim Generate experimental wind conditions

### ISSUE THREAD

**Issue by lingajiang** [OpenFAST/openfast#2007]
**Is your feature request related to a problem? Please describe.**
Dear engineers:
I have built my own model in the aerodyn module, and then I want to build my own wind field with the turbsim module.
**Describe the solution you'd like**
I have built my own model in the aerodyn module, and then I want to build my own wind field with the turbsim module. I have the sequential wind speed data measured by my own wind tunnel (the data is composed of the sequential wind speed of 1024*1024 measurement points). When I learn the turbsim module, I want to use the TurbSim_User.timeSeriesInput file. However, I found that this file can only input one point in each Z direction and then form the wind speed data of the entire inlet surface through interpolation. I have my own data of the entire inlet surface, and I want to import all of them to form my own experimental wind conditions. In this case, what should I do? What do you suggest?
In addition, if you import in order, the order of the points is the understanding of the index?
![微信截图_20240125102814](https://github.com/OpenFAST/openfast/assets/140866891/6cd42696-e773-44f2-a2ff-dfc9fb44935b)

**Describe alternatives you've considered**
<A clear and concise description of any alternative solutions or features youve considered.>

**Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by jjonkman** [comment]
Dear @lingajiang,

I agree that the `TIMESR` feature of TurbSim can only be used to derive full-field turbulent wind fields by time-matching the wind velocity time series measured at one point.  The ability to time-match from multiple point measurements is a reasonable enhancement of TurbSim to propose.

That said, DTU has released their PyConTurb code, which is similar to the `TIMESR` feature of TurbSim, but does support time-matching from multiple point measurements.  We have used PyConTurb at NREL when we want to do that.

In your case, however, it sounds like you have data at a very fine spatial resolution of point measurements (considering that we typically recommend using a spatial discretization equal to the maximum chordlength of a blade), so, I'm not sure why you would need to add finer resolution of turbulence at all.  (Perhaps you need finer discretization in time?)  Instead, I would suggest that you simply convert your data into TurbSim format for use within OpenFAST.  While I have not used this script myself, there is a Python script in the OpenFAST Toolbox that can read and write TurbSim binary formatted output files: https://github.com/OpenFAST/openfast_toolbox/blob/main/openfast_toolbox/io/turbsim_file.py.  This file format is described in Annex D of the TurbSim User's Guide: https://openfast.readthedocs.io/en/main/_downloads/cb14d3e2d3533d76e405d730fea19846/TurbSim_v2.00.pdf.

Best regards,

**Comment by bjonkman** [comment]
Just to clarify, the `TimeSR` feature of TurbSim can already match **more than one** time history: 
![image](https://github.com/OpenFAST/openfast/assets/6108781/31b895d5-0b80-42dc-ba15-36cc11ca4464)
See an example input file here: https://github.com/OpenFAST/openfast/blob/main/docs/source/user/turbsim/examples/TurbSim_User.timeSeriesInput

But, as Jason said, if you already have measurements at all the (regularly spaced) points and don't need interpolation, you could just transform your measurements to the .wnd or .bts format that InflowWind can read, or you could read your own data format by modifying the InflowWind `UserWind` module.

**Comment by lingajiang** [comment]
Dear Jonkman
Please forgive me for not having enough ability to write code before, so combined with your suggestion: I wrote my data into a new.bts file through turbsim_file.py for FAST operation. I used visual studion2019 to compile and then run the fast program, do I still need to compile in python according to your suggestion? In addition, I found that you have written the file readfile_bts.m before, if you use readfile_bts.m to add the data to form a new.bts file, is it OK?

Thank you for your reply

**Comment by jjonkman** [comment]
Dear @lingajiang,

You don't need to compile Python.  It sounds like you already successfully wrote a TurbSim binary file that can be used by OpenFAST.

From the MATLAB Toolbox, I did not personally develop _readfile_BTS.m_, but this script will **read** a TurbSim binary file into the MATLAB workspace.  I'm not aware that an equivalent MATLAB-based script to **write** a TurbSim binary file has been developed, but I'm sure that would be possible using _readfile_BTS.m_ as a starting point.

Best regards,

**Comment by lingajiang** [comment]
Dear Jonkman
Thank you for your reply
best wish for you.
