### ISSUE TITLE
Encountered Issues When Enabling TMD in IEA-15MW

### ISSUE THREAD

**Issue by zrxstar** [OpenFAST/openfast#2019]
Hello, respected teachers.

 I am attempting to activate the Tuned Mass Damper (TMD) in the OpenFAST calculation of the IEA-15MW. However, regardless of the parameters I modify, the response of the wind turbine blades or tower remains unchanged after enabling TMD.

 I am really confused and don't know where the error is. 

I have also tried it in the NREL 5.0 MW case, and the effect of TMD is more obvious. 

I hope you can give me some reminders and help. Thank you all.

![屏幕截图 2024-02-01 103839](https://github.com/OpenFAST/openfast/assets/145632235/4936990b-0468-4820-8243-85fea75c75c0)
![屏幕截图 2024-02-01 103923](https://github.com/OpenFAST/openfast/assets/145632235/1f5b34af-af9b-4c54-b46b-97ba2f3a46c8)
![屏幕截图 2024-02-01 103944](https://github.com/OpenFAST/openfast/assets/145632235/3873a3d1-3f1d-482c-8e53-3e7a367ed28b)

**Comment by jjonkman** [comment]
Dear @zrxstar,

It sounds like the TMD is working well for your NREL 5-MW model, but not for your IEA Wind 15-MW model; is that correct?  What TMD-related settings are different between these two models?

In your IEA Wind model, do you see any effect of the nacelle-based TMD, e.g., does the axial reaction force transferred through the nacelle-yaw bearing (ElastoDyn output `YawBrFzn`) contain the extra weight of the TMD?

Best regards,

**Comment by zrxstar** [comment]
Dear @jjonkman,

Thank you very much for your response! 

Following your advice, I compared the YawBrFzn of 15MW and 5MW wind turbines under different TMD settings. It can be seen that the YawBrFzn of the 5MW wind turbine can clearly reflect the differences:
![image](https://github.com/OpenFAST/openfast/assets/145632235/4d22cf7c-976a-4349-adfc-4d4998613cf8)

Differences can also be observed on the 15MW wind turbine below, although the variations are relatively small.
![image](https://github.com/OpenFAST/openfast/assets/145632235/15f585ee-3a4c-4659-8fbf-f13cc4c19051)

Therefore, can I understand it this way: TMD does play a role in the simulation of the 15MW wind turbine, but due to the turbine's large size and its floating nature, the effect of setting the TMD in the nacelle is not particularly pronounced. Alternatively, there might be an issue with my TMD parameter settings, such as a relatively small mass or a significant difference from the natural frequency of the wind turbine.

Thank you in any case for your response. This is my first time communicating with a top scientist like you. Wishing you all the best!

**Comment by jjonkman** [comment]
Dear @zrxstar,

I fully agree with your assessment.

Best regards,
