### ISSUE TITLE
ElastoDyn vs SubDyn: Different behavior in floating systems

### ISSUE THREAD

**Issue by RBergua** [OpenFAST/openfast#2021]
**Bug description**
I commented this issue in the past offline, but I leave it here for traceability.

When modeling a rigid platform in SubDyn (e.g., defining a rigid link and one lumped mass and inertia), the response is different than when a rigid platform in ElastoDyn is defined. This difference seems to show up when there is a modulation in the system response (e.g., two natural frequencies that are relatively close between them).

To illustrate this issue, the system has been simplified significantly:
![image](https://github.com/OpenFAST/openfast/assets/33709140/bb39d4ee-5ff6-4acf-8522-5acf9cc593d6)

Only three OpenFAST modules are used in this comparison: ElastoDyn, SubDyn and HydroDyn. HydroDyn is used to include the vertical force (equivalent to the buoyancy force) and a stiffness matrix (equivalent to the hydrostatic restoring). Below you can find the comparison between the platform being modeled in ElastoDyn vs the platform modeled in SubDyn vs the system simulated in HOTINT (EXUDYN).
![image](https://github.com/OpenFAST/openfast/assets/33709140/efe31153-943b-4a0c-8572-6eb93887fdb7)

As it can be observed, the agreement between ElastoDyn and HOTINT is excellent and SubDyn behaves differently.

The tests have been performed with the current OpenFAST dev branch ([e39453a](https://github.com/OpenFAST/openfast/commit/e39453af79726c5cb23dd6e2b2389da6b6dc2960)). 

This may be a good test case to run with the tight coupling ([#PR1850](https://github.com/OpenFAST/openfast/pull/1850/)) and check if the SubDyn response improves.

**Comment by luwang00** [comment]
The discrepancy observed between the ElastoDyn model and the rigid SubDyn model is a consequence of the linearized equations of motion of the Guyan modes (rigid-body motion for floating) in SubDyn. This issue will be resolved as part of PR #2203.
