### ISSUE TITLE
Method to project mooring line tension along the axes of inertial frame

### ISSUE THREAD

**Issue by niuyue321** [OpenFAST/openfast#2032]
Dear @jjonkman,

For MoorDyn, we are able to get "FairTen1", "FairTen2", and "FairTen3" as outputs. I am wondering whether there is a way to project those mooring line tensions along the x and y axes of the inertial frame? Thank you!

Best wishes,
Yue

**Comment by jjonkman** [comment]
Dear @niuyue321,

See the full list of available MoorDyn v2 outputs in the online MooDyn documentation: https://moordyn.readthedocs.io/en/latest/inputs.html#id5.

Best regards,

**Comment by niuyue321** [comment]
Dear @jjonkman,

Yes. Thank you so much for your help!

Best regards,
Yue
