### ISSUE TITLE
New BeamDyn Stand Alone Driver file

### ISSUE THREAD

**Issue by ecamare** [OpenFAST/openfast#2037]
I have been trying to run BeamDyn in stand-alone mode. I found that my old models I had working no longer work with OpenFAST 3.5. I went back to

4.2.4.8. Appendix in the OpenFAST manual to get sample BeamDyn input files:

bd_primary_nrel_5mw.inp
nrel_5mw_blade.inp
bd_driver_dynamic_nrel_5mw.inp

Then, in a terminal I type: 

>>beamdyn_driver bd_driver_dynamic_nrel_5mw.inp

were beamdyn_driver an executable on on my local path (openfast/install/bin)

The output is: 
  >>Running BeamDyn Driver a part of OpenFAST - v3.5.0
  linked with NWTC Subroutine Library

 >>BD_ReadDvrFile:Premature EOF for file "bd_driver_dynamic_nrel_5mw.inp" occurred while trying to
 read WrVTK.
 BeamDyn Driver encountered simulation error level: FATAL ERROR

  >>Aborting program.

Am I running beamDyn stand-alone incorrectly or is there new input that is needed in the driver input file?

Best, 
Ernesto

**Comment by andrew-platt** [comment]
You will need to update your driver input file for BeamDyn.  We added visualization of BeamDyn driver simulations with version 3.5.0.

See here for compatible input files: https://github.com/OpenFAST/r-test/tree/v3.5.2/modules/beamdyn

**Comment by ecamare** [comment]
Thanks a lot, that did the trick. I appreciate the quick help!
Ernesto
