### ISSUE TITLE
TIP MOTION - question

### ISSUE THREAD

**Issue by ILDENIEL** [OpenFAST/openfast#2044]
Hello all,
I'm running OpenFAST v3.5.2 to study the tip motion of a Baseline-like turbine with neither tilt, coning nor yaw angles, so I enabled the flapwise and edgewise degrees of freedom of the blades.
I assume that all the tip displacements, translational and rotational, are related to each other: the azimuthal trend describing the rotation of a blade element about the Yb,1-axis should be somehow similar to the translational displacements along the Xb,1- and Zb,1- axes, but it comes out that there's a shift in these azimuthal trends. How can it be possible?

![image](https://github.com/OpenFAST/openfast/assets/125210312/b994bd84-b184-4e6a-90ed-181e9aa5b4b4)
![image](https://github.com/OpenFAST/openfast/assets/125210312/ef038143-84f1-4e95-a89f-1bb0b5ace76c)
![image](https://github.com/OpenFAST/openfast/assets/125210312/230fb8e6-2642-4c55-b886-bc43f629b1b8)

Under my assumptions, the translational displacement about the blade x-axis is also related to the rotational displacement along the blade z-axis, which is considered null by ElastoDyn, thus the azimuthal trend of the rotation about Yb,1 should have the exact same trend of the translational one along Xb,1.

Thanks in advance.

**Comment by jjonkman** [comment]
Dear @ILDENIEL,

I would guess the phase shift you are showing has something to do with the blade structural pretwist, which couples flapwise and edgeise bending.  Are the Y rotations in phase with the X translations when the structural pretwist (input `StrcTwst` in the ElastoDyn blade input file) is zeroed?

Best regards,

**Comment by ILDENIEL** [comment]
Dear @jjonkman,
your help and your tips are always paramount and incredibly appreciated.
![image](https://github.com/OpenFAST/openfast/assets/125210312/eaa790a3-9ec1-4216-8319-9c136897eb6c)
![image](https://github.com/OpenFAST/openfast/assets/125210312/d3bb2b13-5c0d-4e54-8b1e-9588ef84a5c2)
with a structural pretwist constant equal to 0 for all the ED nodes, the phase shift is 0.
Thank you so much for your availability and your courtesy.

**Comment by jjonkman** [comment]
Dear @ILDENIEL,

I'm glad your results make sense to you know.

The structural twist in ElastoDyn defines the orientation of the principal axes of bending, which effects the coupling between flapwise and edgewise motions.

The aerodynamic twist in AeroDyn defines the orientation of the chordline, which primarily effects the local angle of attack.

Both twist values are often similar, but need not be identical.

Best regards,

**Comment by ILDENIEL** [comment]
Dear @jjonkman,
I thought that these two concepts were tied together, since the angle of attack changes (also) because of the blade bending itself and the following change of the local wind velocity.
Among the papers and documentation, unfortunately, I haven't been able to find such a distinction or explanation. 
Where can I find these definitions? Is there a particular document focusing on this topic?

Thanks in advance,
Best regards

**Comment by ILDENIEL** [comment]
Dear @jjonkman, 
I understood the difference between structural and aerodynamic twist because of your clear explanation, I just wanted to know if there was a specific document clearly pointing out this difference, in order to eventually cite it.
I'll go through with the documentation that you kindly shared.
Thanks again for your help.

Best regards.
