### ISSUE TITLE
I'm having problems calculating the 15MW turbine case beyond the wind farm grid

### ISSUE THREAD

**Issue by lin990316** [OpenFAST/openfast#2047]
I'm having problems calculating the 15MW turbine case beyond the wind farm grid,The error shows that the model exceeds the wind field boundary in the Z direction in the calculations, however the hub height for the case is 150 metres so the wind field height setting in Turbsim is set to a maximum of 300 metres and "Z=305" always exceeds the wind field boundary. May I ask what is the reason for this? Is it because I have incorrectly set the operating conditions that the motion response of the wind turbine is too large? How should I modify it to continue the calculation.
Thank you for your guidance!

" Time: 0 of 4000 seconds.

FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:AD_CalcOutput:RotCalcOutput:BEMT_CalcOu
tput(node 2, blade 1):UA_CalcOutput:UA_BlendSteady:Temporarily turning off UA due to high angle
of attack or low relative velocity. This warning will not be repeated though the condition may
persist.
 Time: 10 of 4000 seconds.  Estimated final completion at 01:10:51.

FAST_Solution:FAST_AdvanceStates:ED_ABM4:ED_CalcContStateDeriv:SetCoordSy:Small angle assumption
violated in SUBROUTINE SmllRotTrans() due to a large blade deflection (ElastoDyn SetCoordSy). The
solution may be inaccurate. Simulation continuing, but future warnings from SmllRotTrans() will
be suppressed.
 Additional debugging message from SUBROUTINE SmllRotTrans(): 11.03 s
 Time: 30 of 4000 seconds.  Estimated final completion at 01:11:28.

FAST_Solution:FAST_AdvanceStates:SolveOption2c_Inp2AD_SrvD:InflowWind_CalcOutput:CalcOutput:IfW_FF
Wind_CalcOutput [position=(91.819, -7.5301, 305.13)  in wind-file coordinates]: FF wind array
boundaries violated. Grid too small in Z direction (Z=305.13 m is above the grid).

 OpenFAST encountered an error at simulation time 34.09 of 4000 seconds.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST."

**Comment by jjonkman** [comment]
Dear @lin990316,

I would guess your model is numerically unstable, resulting in excessive turbine deflection.  The large blade deflection warning from ElastoDyn just before the FF wind array boundaries violated error from InflowWind is the clue.

Presumably you are using an OpenFAST model of the IEA Wind 15-MW reference wind turbine.  Can you clarify what you changed relative to the model set-up provided in the repository?

Best regards,

**Comment by lin990316** [comment]
Dear @jjonkman 
Thank you for your reply, in this case I didn't change the 15MW turbine model, I generated a 17m/s turbulent wind field by Turbsim modification, the turbulence is set to A, the wave height is 6.6m, the period is 13.5 seconds, the current speed is 1.6m/s, I don't seem to have changed any other settings, is it because of the unreasonable setting of the working condition that leads to this situation?

In addition, regarding this issue, I saw your reply in another discussion post, I seem to notice that I may not have set the initial pitch angle and rotor speed of the turbine correctly, is it possible that this may be the cause of this error? During the correction process, I changed the initial pitch angle from 6 to 12 and the rotor speed from 6 to 12, the situation seems to have improved, is it reasonable to do it this way? I saw a link in that paragraph of your reply about the initial settings for a 5MW turbine at different wind speeds, is there any relevant information available for a 15MW turbine, I really didn't look for this on the web.
Best regards,

**Comment by lin990316** [comment]
Dear @jjonkman 
I'm sorry I overlooked this image earlier when reading this document, a million thanks for the guidance! I will readjust the settings to continue with the calculations as per your instructions.
Thanks again for your guidance!
Best regards,
