### ISSUE TITLE
set OLAF

### ISSUE THREAD

**Issue by lingajiang** [OpenFAST/openfast#2056]
Dear engineers
When I use OLAF for calculation, the problem of calculation time and calculated wake length has been bothering me, and I have been adjusting the four parameters of Tmax, DT, nNWPanels and nNWPanelsFree in the calculation process. The first time I calculated the four parameters required by the case through the py code.
change code：if __name__ == '__main__':
    OLAFParams(omega_rpm = 545.7, U0=8, R=0.7, deltaPsiDeg=3, verbose=True)
    result：   5.47 Transient time   ( 49.7 rot)
           2972 nAWPanels        ( 24.9 rot,  10.0D)

OLAF INPUT FILE:
----------------------- GENERAL OPTIONS ---------------------
       0.000920 DTFVW        (delta psi =   3.0deg)
--------------- WAKE EXTENT AND DISCRETIZATION --------------
           2972 nNWPanels     ( 24.9 rot,  10.0D)
           1040 nNWPanelsFree (  8.7 rot,   3.5D   1.0)
              0 nFWPanels     (  0.0 rot,   0.0D)
              0 nFWPanelsFree (  0.0 rot,   0.0D)
  But when I'm running in the aerodyn module：
  result：AeroDyn_driver-Unversioned from 18704086dad861ab13daf804825da7c4b8d59428
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 2021
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: Yes, number of threads: 24/24
 - Date: Mar 07 2023
 - Time: 15:42:58
Execution Info:
 - Date: 02/27/2024
 - Time: 16:55:18+0800

------------------------------------------------------------------------------
Running combined case 1/1
 Nodes positions for turbine 1, (at t=0, without base or RNA motion)
 Bse:   0.300000011920929       0.000000000000000E+000  0.000000000000000E+000
 Twr:   0.300000011920929       0.000000000000000E+000  0.000000000000000E+000
 Nac:   0.300000011920929       0.000000000000000E+000   1.77386784553528
 Hub:   5.136953294277191E-002  0.000000000000000E+000   1.79999995231628
 Bld:   5.346350371837616E-002  0.000000000000000E+000   1.85996341705322
 Bld:   4.407885670661926E-002 -5.183494836091995E-002   1.77067446708679
 Bld:   4.407885670661926E-002  5.183495208621025E-002   1.77067446708679
Running ADI.
Running AeroDyn.
AD15 Nodal Outputs: Nodal output section of AeroDyn input file not found or improperly formatted.
Skipping nodal outputs.
Running OLAF.
 - Directory:         G:\openfast_anli\11\x300w_aero
 - RootName:          ad_driver.1.
 - Reading advanced options for OLAF:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
nNWPanelsFree < nNWPanels is a beta feature for simulation speed up.
The frozen near-wake convection might slightly change in the future.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 - OLAF regularization parameters (for wing 1):
    WingReg (min/max) :   0.0210  0.0421
    WakeReg (min/max) :   0.0210  0.0421
    k = alpha delta nu:   0.0184

[INFO] OLAF free near wake is at full extent at time: 0.95864
Its calculation time is too short, may I ask how a small wind turbine pneumatic model like mine can accurately match its calculation time and wake length (for example, I want to calculate the near wake as 3.5D and the far wake as 9D)? Do you have any suggestions.
My fast is version 3.5.0, and my zipped files：
[123.zip]
I would be glad to receive your reply

**Comment by ebranlard** [comment]
Hi 
I'm not sure I fully understand your question with the computational time. Your parameters seems fine. Make sure you ajust the dt of openfast or the aerodyn driver as well. You can ajust tmax to get a longer simulations.  You can look at the guidelines and the documentation for the input parameters. 
https://openfast.readthedocs.io/en/dev/source/user/aerodyn-olaf/RunningOLAF.html#guidelines 
You can visualize the wake with WrVTK to make sure the wake is long enough. 

I hope that helps!
