### ISSUE TITLE
Wrong argument passed to `FAST_InitializeAll_T`

### ISSUE THREAD

**Issue by marchdf** [OpenFAST/openfast#2064]
**Bug description**

The definition of the function [FAST_InitializeAll_T]( https://github.com/OpenFAST/openfast/blob/main/modules/openfast-library/src/FAST_Subs.f90#L37) has `TurbId` as it's second argument. The call sites: https://github.com/OpenFAST/openfast/blob/main/modules/openfast-library/src/FAST_Library.f90#L144 and https://github.com/OpenFAST/openfast/blob/main/modules/openfast-library/src/FAST_Library.f90#L148 pass in `iTurb` to that argument and not `TurbId`.

**To Reproduce**
I am calling openfast from amr-wind but this isn't specific to that and I don't build stand-alone openfast so I am not sure what the steps are to reproduce.

**Expected behavior**
I would expect `TurbId` to be passed to `FAST_InitializeAll_T` and not `iTurb` since that is what it expects in the argument list.

**OpenFAST Version**
3.5.2

**System Information (please complete the following information):**
 - OS: NAME="Rocky Linux" VERSION="8.9 (Green Obsidian)" ID="rocky" ID_LIKE="rhel centos fedora" VERSION_ID="8.9"
 - Compiler: GNU Fortran (Spack GCC) 10.4.0

**Comment by andrew-platt** [comment]
The problem appears to be due to a discrepency in how the `TurbId` is used in _FAST.Farm_ vs with AMR-Wind.  When used with _FAST.Farm_, the turbine id ranges from `1:NumTurbines`, but when coupled to a C code, the turbine id ranges from `0:NumTurbines-1`.

**Comment by andrew-platt** [comment]
Looking at the code, the `FAST_Sizes` routine does not have a variable `TurbID`.  Are you referring to another call to `FAST_InitializeAll_T` from the `FAST_OpFM_Init` routine (https://github.com/OpenFAST/openfast/blob/main/modules/openfast-library/src/FAST_Library.f90#L589)?

For reasons completely unknown to me, the `FAST_OpFM_Init`routine contains both `TurbID` and `iTurb` in its input argument list.  I don't actually know why both arguments are there, or if they would ever be different.  However the use of `iTurb` appears to be consistent in this routine -- it must match the index of the `Turbine` data structure getting passed to `FAST_InitializeAll_T` and all uses of the `Turbine` data structure that follows.  So I propose we remove either `TurbID` or `iTurb` from the argument list in `FAST_OpFM_Init` as those appear redundant.

**Comment by marchdf** [comment]
I am referring to this `FAST_InitializeAll_T`: https://github.com/OpenFAST/openfast/blob/main/modules/openfast-library/src/FAST_Subs.f90#L37. It uses `TurbId` in the argument list. 

I don't know why there are 2 IDs being passed into `FAST_OpFM_Init`. In AMR-Wind we seem to pass a `local` and a `global` ID to those arguments: https://github.com/Exawind/amr-wind/blob/main/amr-wind/wind_energy/actuator/turbine/fast/FastIface.cpp#L224. I don't know why. Maybe @gantech or @psakievich have a historical perspective on this?

**Comment by bjonkman** [comment]
Originally, `Turbine` was not an array, but there was a `TurbID` for file naming purposes. The `iTurb` variable was introduced in https://github.com/OpenFAST/openfast/pull/20

**Comment by andrew-platt** [comment]
I'm going to close this issue in deference to the underlying issue outlined in #2096.
