### ISSUE TITLE
Hydrodyn and Hydrostatics

### ISSUE THREAD

**Issue by HANloading** [OpenFAST/openfast#2070]
Dear everyone：
I wrote my own model and my model reference point is the platform center of gravity（13.46m below horizontal）, so I would like to derive the hydrostatic recovery matrix based on openfast where the reference point is the platform center of gravity, or is there any other way to derive this recovery matrix?
Looking forward to replying！！

**Comment by HANloading** [comment]
Thank you for your reply.
[1]Definition of the Semisubmersible Floating System for Phase II of OC4
By "hydrostatic recovery" matrix, I meant a 6x6 hydrostatic recovery matrix, which is correct, forgive my carelessness.
 I am considering a 14 degree of freedom model of a semi-submersible wind turbine, including 6 degrees of freedom for the platform, two first order bending degrees of freedom for the tower, and flapwise and edgewise for the blades.
But the reference point for my model is chosen to be the center of gravity of the platform (-13.46) . If I directly quote the anchor chain loads and hydrostatic loads inside the paper [1]. ### **_When I don't give any initial value for the state, the heave degree of freedom in my model oscillates with equal amplitude between 0-0.45. And the rest of the degrees of freedom vary to different degrees._** So is this situation related to the selection of the modeling reference point, which leads to the variation of hydrostatic and anchor chain loads. If yes, how should I modify it?

I tried to modify the **rho*g*V0*Z_b** in Addlin but the simulation results didn't change, please help me out is this the right way to do it and also do I need to modify the anchor chain loads?

![Heave](https://github.com/OpenFAST/openfast/assets/146436066/8a4bc2f0-d724-4898-b409-138152769d24)



Looking forward to your reply

**Comment by jjonkman** [comment]
Dear @HANloading,

For the NREL 5-MW baseline wind turbine atop the OC4-DeepCwind semisusmersible, the platform heave-mode is more or less uncoupled from pitch and roll.  Thus, I would think the choice of platform reference point would impact the hydrostatic and mooring restoring matrices in pitch and roll, but not in heave.

If your model oscillates in heave in the absence of wind or wave excitation, that tells me that in your model the full system weight does not balance with the undisplaced buoyancy and vertical mooring pretension.  We generally recommend that you set up floating wind turbine models such that these three terms balance, as discussed in our online HydroDyn documentation: https://openfast.readthedocs.io/en/main/source/user/hydrodyn/modeling_considerations.html#undisplaced-position-for-floating-systems.

Best regards,

**Comment by HANloading** [comment]
Dear @jjonkman 
Thanks for your answer.
In order to balance the weight and buoyancy of the whole system (nacelle, blades, tower, platform) and the pre-tensioning of the mooring system, how should I modify it in my M matrix?
Also, I see in the manual of the semi-submersible wind turbine thatoverall tower mass = 249718kg; Platform mass, including ballast = 1.3473e+7 kg; nacelle = 240000kg; overall balde mass = 17740kg; hub = 56780kg;T_Mooring = -1839000;rho*g*V0 = 1.3989e+8.
Then I calculated based on rho*g*V0-m_Total*g-T_Mooring = 0,m_total is still 88030.06632268064kg short of equilibrium, which part of the mass is this? And does nacelle need to be accounted for?
Looking forward to your reply again

**Comment by jjonkman** [comment]
Dear @HANloading,

I'm not following how you get 88030 kg, even though I agree with your component masses.  Note that the combined hub + 3 blade mass is 110000 kg for the NREL 5-MW baseline wind turbine.  And note that T_Mooring is already negative, which means it should be added instead of subtracted in your vertical force balance.

Best regards,

**Comment by HANloading** [comment]
> Dear @HANloading,
> 
> I'm not following how you get 88030 kg, even though I agree with your component masses. Note that the combined hub + 3 blade mass is 110000 kg for the NREL 5-MW baseline wind turbine. And note that T_Mooring is already negative, which means it should be added instead of subtracted in your vertical force balance.
> 
> Best regards,

Thank you very much, the above problem has been solved. But another problem has been encountered.
I constructed a model of a semi-submersible offshore wind turbine (FOWT) using the Euler-Lagrange equations. I chose 14 degrees of freedom (DOFs) to describe the motions of the FOWT, including flap and edge motions for the 3 blades, fore-aft and side-to-side motions for the top of the tower, and 6 motions for the floating platform. All motions are defined based on the platform centre of mass. Finally, by introducing the small deformation assumption and neglecting higher order terms, I linearise the Euler-Lagrange equations to obtain the M_sym, C_sym, and K_sym matrices.
1 I consider the intrinsic frequency in the case of no wind and no waves, and the K and M matrix expressions are as follows:
K = K_sym + K_moor + K_Hydrostatic;
M = M_sym;
Platform: 0.7163 0.4995 0.0113 0.0509 0.6933 0.6933
Tower: 1.1039 1.087
Blade: 0.5049 0.0113 0.0509 1.0896 0.0833 0.0155
OpenFAST using Morrison's formula (Potmod=0 in HydroDyn.dat and without any waves and wind)
Platform: 0.009 0.009 0.0580 0.0380 0.0380 0.0130
Tower: 0.440 0.4420
Blade: 0.6940 0.703 0.706 1.0878 1.089 1.145
As you can see there is a very large difference in the intrinsic frequencies, do I need to additionally consider the rest of the M and K matrices? For example the add mass matrix?

**Comment by jjonkman** [comment]
Dear @HANloading,

I agree that you should include the hydrodynamic added mass matrix.  For the K_Hydrostatic, are you including the effects of both buoyancy and weight of the body (pendulum effect)?

Best regards,

**Comment by HANloading** [comment]
[1]Definition of the Semisubmersible Floating System for Phase II of OC4
Forgive me if I don't quite understand what you're saying.
1. isn't buoyancy already taken into account in the external forces section, as the paper [1] states
2. i don't understand how body of weight should be taken into account in K_hydrostatic. is there any reference please?
3. when i add the additional mass matrix, there is almost no difference in the intrinsic frequency of the platform, but there is still a slight difference in the intrinsic frequency of the tower and the blades. does the  body of weight affect the intrinsic frequency of these two parts?
![image](https://github.com/OpenFAST/openfast/assets/146436066/add12864-1e19-4766-8812-b51717f07914)

**Comment by jjonkman** [comment]
Dear @HANloading,

Here are my responses:

1. Yes, I agree.
2. The weight of the body will influence the (4,4) and (5,5) (and perhaps the (4,6) and (5,6), depending on the system symmetry) of the hydrostatic stiffness matrix.  See the HydroDyn documentation found here for a general description: https://openfast.readthedocs.io/en/main/source/user/hydrodyn/modeling_considerations.html#hydrostatic-restoring-for-strip-theory-members-of-floating-systems.
3. The body weight will impact the restoring in pitch and roll, and the associated natural frequencies.  But this is different from the hydrodynamic added mass, which I would think would impact the natural frequencies of all floater modes (more or less, depending on the displaced volume of the floater).
4. Yes, I would say the coupling is generally important, especially in surge-pitch-heave and in sway-roll-heave.

Best regards,

**Comment by FowtDyn** [comment]
> Dear everyone： I wrote my own model and my model reference point is the platform center of gravity（13.46m below horizontal）, so I would like to derive the hydrostatic recovery matrix based on openfast where the reference point is the platform center of gravity, or is there any other way to derive this recovery matrix? Looking forward to replying！！

I have also established a 14-degree-of-freedom dynamic model for a semi-submersible wind turbine, using the same method as you, and encountered an initial oscillation in the Heave direction as well. I suspect it is due to an imbalance between the hydrostatic buoyancy, the pre-tension of the mooring system, and the system's weight. Additionally, the natural frequencies of the 6 degrees of freedom for the platform in my model are also incorrect. However, after adjusting the mooring and hydrostatic restoration matrices, I was able to tune them to the correct frequencies. How did you correct these issues? I look forward to your reply, thank you.

**Comment by Zhao-Yu-Lg** [comment]
@HANloading Hello, your question is very useful to me. Have you solved it? Can we talk about it

**Comment by FowtDyn** [comment]
Hello, sorry I just saw your email. Regarding the full-system modeling of the floating wind turbine, I have basically resolved the issue, but there are some imperfections. I believe this is within an acceptable margin of error. If you have any questions, we can discuss them.


| |
ncepu_yxm
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/21/2024 16:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [OpenFAST/openfast] Hydrodyn and Hydrostatics (Issue #2070) |

@HANloading Hello, your question is very useful to me. Have you solved it? Can we talk about it

**Comment by Zhao-Yu-Lg** [comment]
@FowtDyn 
Hello, I am also working on a 14-DOF semi-submersible floating wind turbine. I have some problems in calculating the hydrodynamics of the platform, and I am eager to get your help. At first, I wanted to use the hydrodynamic load output of FAST as my hydrodynamic load, but I couldn't get the result I wanted. I don't know if you did this. However, I used the formula to model, and found that it was not consistent with the response of FAST's surge and pitch. I would like to ask for your help. Thank you very much

**Comment by FowtDyn** [comment]
Did you take added mass and added damping into account in your modeling? If you did, the basic response should be consistent, though it may not fully match the OpenFAST simulation results. Also, which software did you use for the modeling? Was it Mathematics or Matlab? I would like to know if you have any other contact methods similar to WeChat to facilitate our communication. I also hope to improve through exchanging ideas with you.


| |
ncepu_yxm
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/17/2024 11:20 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [OpenFAST/openfast] Hydrodyn and Hydrostatics (Issue #2070) |

@FowtDyn
Hello, I am also working on a 14-DOF semi-submersible floating wind turbine. I have some problems in calculating the hydrodynamics of the platform, and I am eager to get your help. At first, I wanted to use the hydrodynamic load output of FAST as my hydrodynamic load, but I couldn't get the result I wanted. I don't know if you did this. However, I used the formula to model, and found that it was not consistent with the response of FAST's surge and pitch. I would like to ask for your help. Thank you very much

**Comment by Zhao-Yu-Lg** [comment]
@FowtDyn 
Thank you very much. My wechat number is my name， I hope I can get your guidance.
Best，

**Comment by Zhao-Yu-Lg** [comment]
Hello, my wechat ID is Zhao-Yu-Lg. I hope I can get your guidance.



发自我的iPhone


------------------ Original ------------------
From: FowtDyn ***@***.***&gt;
Date: Tue,Dec 17,2024 7:18 PM
To: OpenFAST/openfast ***@***.***&gt;
Cc: Zhao-Yu-Lg ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [OpenFAST/openfast] Hydrodyn and Hydrostatics (Issue #2070)





 Did you take added mass and added damping into account in your modeling? If you did, the basic response should be consistent, though it may not fully match the OpenFAST simulation results. Also, which software did you use for the modeling? Was it Mathematics or Matlab? I would like to know if you have any other contact methods similar to WeChat to facilitate our communication. I also hope to improve through exchanging ideas with you.
 
 
 | |
 ncepu_yxm
 |
 |
 ***@***.***
 |
 ---- Replied Message ----
 | From | ***@***.***&gt; |
 | Date | 12/17/2024 11:20 |
 | To | ***@***.***&gt; |
 | Cc | ***@***.***&gt; ,
 ***@***.***&gt; |
 | Subject | Re: [OpenFAST/openfast] Hydrodyn and Hydrostatics (Issue #2070) |
 
 @FowtDyn
 Hello, I am also working on a 14-DOF semi-submersible floating wind turbine. I have some problems in calculating the hydrodynamics of the platform, and I am eager to get your help. At first, I wanted to use the hydrodynamic load output of FAST as my hydrodynamic load, but I couldn't get the result I wanted. I don't know if you did this. However, I used the formula to model, and found that it was not consistent with the response of FAST's surge and pitch. I would like to ask for your help. Thank you very much

**Comment by FowtDyn** [comment]
Hello,I have added your wechat


| |
ncepu_yxm
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/18/2024 14:07 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [OpenFAST/openfast] Hydrodyn and Hydrostatics (Issue #2070) |

Hello, my wechat ID is Zhao-Yu-Lg. I hope I can get your guidance.



发自我的iPhone


------------------ Original ------------------
From: FowtDyn ***@***.***&gt;
Date: Tue,Dec 17,2024 7:18 PM
To: OpenFAST/openfast ***@***.***&gt;
Cc: Zhao-Yu-Lg ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [OpenFAST/openfast] Hydrodyn and Hydrostatics (Issue #2070)





Did you take added mass and added damping into account in your modeling? If you did, the basic response should be consistent, though it may not fully match the OpenFAST simulation results. Also, which software did you use for the modeling? Was it Mathematics or Matlab? I would like to know if you have any other contact methods similar to WeChat to facilitate our communication. I also hope to improve through exchanging ideas with you.


| |
ncepu_yxm
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***&gt; |
| Date | 12/17/2024 11:20 |
| To | ***@***.***&gt; |
| Cc | ***@***.***&gt; ,
***@***.***&gt; |
| Subject | Re: [OpenFAST/openfast] Hydrodyn and Hydrostatics (Issue #2070) |

@FowtDyn
Hello, I am also working on a 14-DOF semi-submersible floating wind turbine. I have some problems in calculating the hydrodynamics of the platform, and I am eager to get your help. At first, I wanted to use the hydrodynamic load output of FAST as my hydrodynamic load, but I couldn't get the result I wanted. I don't know if you did this. However, I used the formula to model, and found that it was not consistent with the response of FAST's surge and pitch. I would like to ask for your help. Thank you very much
