### ISSUE TITLE
About the aerodynamic characteristics of the test file

### ISSUE THREAD

**Issue by Zheng-Haojie** [OpenFAST/openfast#2084]
I would like to use Fluent to verify the aerodynamic parameters in the test file of fast, however, the document does not seem to state that the lift coefficient, drag coefficient, etc. are the results of what the Reynolds number is. Where can I find protocol descriptions for these tests?
Looking forward to your answers!

**Comment by jjonkman** [comment]
Dear @Zheng-Haojie,

Which airfoil data of which OpenFAST r-test are you specifically asking about?

Best regards,

**Comment by Zheng-Haojie** [comment]
Thank you for such a prompt reply！The airfoil aerodynamic test instructions I need are:
S826, S82, S818 airfoils of WindPack1.5MW wind turbines
Best regards！

**Comment by jjonkman** [comment]
Dear @Zheng-Haojie,

The Reynolds numbers of these airfoils are reported in their respective airfoil data files (and are Re = 3M, 3M, and 4M, respectively, for S826, S825, and S818)--see: https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast/WP_Baseline/Airfoils.

Please note, however, that these airfoil data include 3D corrections, including for rotational augmentation and deep stall.  Keep that it mind when you are comparing to Fluent.

Best regards,

**Comment by Zheng-Haojie** [comment]
Thank you for your answer！Your reply solved my confusion.
