### ISSUE TITLE
how to improve the simulation speed for beamdyn

### ISSUE THREAD

**Issue by WANGSUYU0809** [OpenFAST/openfast#2106]
**Is your feature request related to a problem? Please describe.**
I have used beamdyn to model a 16MW wind turbine, with around 250m rotor diameter and around 65 beam sections for one blade, and found that I have to use a time step as small as 0.0001 to have converge result at the start of the simulation, which makes the simulation speed very slow, need around 2hours for 100s simulation. 

**Describe the solution you'd like**
How could I increase the time step to speed up the simulation and not get diverge result? What is worthy for me to have a try?

**Describe alternatives you've considered**
<A clear and concise description of any alternative solutions or features youve considered.>

**Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by andrew-platt** [comment]
Dear @WANGSUYU0809 ,

Similar questions about speeding up _BeamDyn_ simulations have been asked before.  See #1605, #1496.

In #1605, we @jjonkman mentioned that we are working on a new tight coupling scheme that will dramatically improve the calculation time for simulations involving _BeamDyn_.  Development of the new solver has been difficult and a slow process, so we are behind schedule from what we stated in that issue.  We now expect this will be ready for the v5.0.0 release in the June-July 2024 timeframe. 

Regards,

**Comment by WANGSUYU0809** [comment]
Hi Andy,

Thanks for your reply!  I have further questions. 

When I build the aerodynamic model of the blade, I use the aerodynamic reference center (normally 25% of the chord length from leading edge) as the reference line, which is represented by BlCrvAC and BlSwpAC in the aerodyn file, and I specify the aerodynamic twist angle in BlTwist. 

My first question is how to define BlCrvAng, and why I need to define this value?

Besides, should I also use this aerodynamic reference line as the axis to define beam  in Beamdyn, which is represented by kp_xr, and kp_yr?  And how should I define initial_twist in beamdyn? Should I follow aerodynamic twist? Are there any suggestions for modeling long and flexible blade in Beamdyn which helps converge?

Best Regards,

**Comment by jjonkman** [comment]
Dear @WANGSUYU0809,

Regarding `BlCrvAng`, see a similar question asked and answered in the following OpenFAST issue: https://github.com/OpenFAST/openfast/issues/451.

In most cases, the aerodynamic reference line in AeroDyn and the structural reference line in BeamDyn would differ.  In BeamDyn, the structural reference line (defined via `kp_xr`, `kp_yr`, `kp_zr`, and `initial_twist`) should locate the origin and orientation of the sectional mass and stiffness matrices specified in the BeamDyn blade file.  In general, we recommend that you define the structural reference line in BeamDyn to be a smooth curve without much curvature.  (There is no equivalent restriction for the aerodynamic reference line.)

Best regards,

**Comment by WANGSUYU0809** [comment]
Thanks for your answers, it helps me solve my question.
