### ISSUE TITLE
Visual Studio 2022 Build Issue

### ISSUE THREAD

**Issue by DavidChen0429** [OpenFAST/openfast#2110]
Hi, I am new to both Visual Studio and Openfast, and I ran into an issue regarding compiling openfast in Visual Studio.

I followed the documentation and installed all the dependencies, but when I tried to build the openfast in Visual Studio, here is what happened:
![error](https://github.com/OpenFAST/openfast/assets/81453154/bee816d5-5ed6-4a91-a9cc-f8c0bc6b2e6e)

The corresponding output is like below:
![output](https://github.com/OpenFAST/openfast/assets/81453154/32fc4b96-2e55-471b-878a-beb33cff56da)

It seems like I have an issue opening the input file "opencv_world401d.lib". Does anyone know how to solve it? Appreciate it.

**Comment by andrew-platt** [comment]
Which version or git hash of OpenFAST?

**Comment by DavidChen0429** [comment]
I think that's the latest version of OpenFAST v3.5.2, I just cloned all the code from "https://github.com/OpenFAST/openfast".

**Comment by andrew-platt** [comment]
This is a really strange error that I haven't seen before.  If you compile for 64 bit, do you get the same errors?

The link error about `opencv_world401d.lib` is puzzling.  This isn't a library that is used directly in _OpenFAST_.  I suspect it a backend library the compiler is using, and is either not available for 32 bit compiles, or there is something wrong with the compiler install.

Tagging @deslaughter  in case he has seen this before.

**Comment by bjonkman** [comment]
Which C/C++ compiler are you using? You could try to use a different one: for example, right-click on the 'FAST_Registry` project, click `Properties`, then `Configuration Properties->General->Platform Toolset`. 

![image](https://github.com/OpenFAST/openfast/assets/6108781/b6adc315-ad8a-4e2b-9d90-dc38e38fe0de)
Note: I have old versions of Visual Studio and Intel installed, so you will have different options.

**Comment by deslaughter** [comment]
@andrew-platt I agree that it's a very strange issue. I haven't seen it before. It seems like something in Visual Studio has changed and is being applied to the OpenFAST projects. 

@DavidChen0429 is this a fresh install of Visual Studio? Is it on a shared computer when the configuration may have been modified?

**Comment by andrew-platt** [comment]
@DavidChen0429, which version of Windows are you running?

@deslaughter, at some point when I have free time, I'll upgrade VS on my Win10 VM and see what chaos that presents.

**Comment by DavidChen0429** [comment]
> @andrew-platt I agree that it's a very strange issue. I haven't seen it before. It seems like something in Visual Studio has changed and is being applied to the OpenFAST projects.
> 
> @DavidChen0429 is this a fresh install of Visual Studio? Is it on a shared computer when the configuration may have been modified?

Yep. I'm using the latest version of Visual Studio that I downloaded a few days ago.

**Comment by DavidChen0429** [comment]
> @DavidChen0429, which version of Windows are you running?
> 
> @deslaughter, at some point when I have free time, I'll upgrade VS on my Win10 VM and see what chaos that presents.

I'm using Windows 11 (x64). Is it possible that OpenFAST doesn't support Windows 11?

**Comment by DavidChen0429** [comment]
> This is a really strange error that I haven't seen before. If you compile for 64 bit, do you get the same errors?
> 
> The link error about `opencv_world401d.lib` is puzzling. This isn't a library that is used directly in _OpenFAST_. I suspect it a backend library the compiler is using, and is either not available for 32 bit compiles, or there is something wrong with the compiler install.
> 
> Tagging @deslaughter in case he has seen this before.

That's the strange part, I selected "release" and "x64", but still the compiler worked as "Realse Win32" which you can see from the output. Is there a way to change that?

**Comment by bjonkman** [comment]
> That's the strange part, I selected "release" and "x64", but still the compiler worked as "Realse Win32" which you can see from the output. Is there a way to change that?

You can change that from the `Build->Configuration Manager` window:
![image](https://github.com/OpenFAST/openfast/assets/6108781/f431a56a-7d68-47e1-8325-d0bff2ac545f)

![image](https://github.com/OpenFAST/openfast/assets/6108781/2c56850e-c1f0-4d8f-9c4a-13fd752fcaa7)

Change the `Win32` to `x64` for the FAST_Registry project. It was originally set so that we didn't have to keep rebuilding the registry for different configurations when we would normally build for Win32, but it shouldn't matter.

**Comment by DavidChen0429** [comment]
Hey guys, thanks for the tips, and the problem is solved by compiling for 64 bit as @andrew-platt suggested. 

To be specific, I changed the platform of the FAST_Registry project from `Win32` to `x64` as the previous post from @bjonkman 
 showed. After doing so, I successfully built the solution by using the default compiler from the VS2022.

**Comment by andrew-platt** [comment]
Thanks for the update!

For our next release, I think we should change the FAST_Registry to build only `x64` as the necessary `Win32` libraries are probably no longer installed by default.
