### ISSUE TITLE
Turbsim

### ISSUE THREAD

**Issue by sffgd** [OpenFAST/openfast#2114]
Hello everyone，
    If I want to use user-defined wind spectra and spatial correlation functions in Turbsim to generate wind files, do I need to change the source code? Or just modify the parameters in the.inp file, such as Meteorological Boundary Conditions (TurbModel="USRINP", UserFile inputs for user-defined spectra).
    Best wishes

**Comment by sffgd** [comment]
I would like to add a custom spatial coherence function (attachment)
![相干函数图片](https://github.com/OpenFAST/openfast/assets/144923930/430aaeb7-5c4d-4184-bddb-976ef20e4400)

**Comment by sffgd** [comment]
I would like to add custom wind spectra and spatial coherence functions (attachment)
![自定义风谱](https://github.com/OpenFAST/openfast/assets/144923930/649f284d-68c9-4ab6-8373-cee6255efc72)
![相干函数图片](https://github.com/OpenFAST/openfast/assets/144923930/5dbf368b-4120-4310-bd24-7b842015e95d)

**Comment by jjonkman** [comment]
Dear @sffgd,

If you want to specify your own wind turbulence spectra, you can do that through input files.  Set `TurbModel` =  "USRINP" and define your own spectra via the `UserFile`.

If you want to change the formulation of the spatial coherence model to be different than the "GENERAL" formulation implemented in TurbSim involving the coherence decrement (a), offset parameter (b), and coherence exponent (`CohExp`), you'd have to modify the TurbSim source code.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman， 

Thank you for your reply！I want to specify my own wind turbulence spectra, and  do that through input files. Set TurbModel= "USRINP" and define your own spectra UserFile. But I have a problem with the generation of the diagram below (Inputfile for User User-Defined Time Series)
![333](https://github.com/OpenFAST/openfast/assets/144923930/9287414a-a898-469a-ba4c-5ad7072392b3)
![444](https://github.com/OpenFAST/openfast/assets/144923930/dc689e95-f306-4a52-bec1-62c707049513)

Therefore, I would appreciate asking for detailed help.

**Comment by sffgd** [comment]
Dear @jjonkman，

Is it feasible to change only the user-defined wind spectrum without changing the spatial correlation function?

**Comment by jjonkman** [comment]
Dear @sffgd,

Yes.  You can set `TurbModel` = "USRINP" to define your own velocity spectrum together with one of the built-in spatial coherence functions such as `SCMod1` = `SCMod2` = `SCMod3` = "IEC", "GENERAL", or "NONE".

Best regards,

**Comment by sffgd** [comment]
![Uploading 444.png…]()

**Comment by jjonkman** [comment]
Dear @sffgd,

I'm not sure I fully understand your equations (e.g., I'm not sure what z is; n and f seem to refer to the same variable, and I would think S_u would be a function of f, not u).  Regardless, presumably S_u(f) is the one-sided velocity spectrum (PSD) that needs to be specified within TurbSim's user-defined spectra input file.  That is, you should multiply the right-hand side of the spectra equations by sigma^2/f to get S_u(f).  Likewise for v and w, if you have equations for those spectra.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman，
 Yes，I agree with “That is, you should multiply the right-hand side of the spectra equations by sigma^2/f to get S_u(f). Likewise for v and w, if you have equations for those spectra.”, and successfully generated the wind field, thank you very much for your answer!
