### ISSUE TITLE
OpenMP not actually required?

### ISSUE THREAD

**Issue by marchdf** [OpenFAST/openfast#2117]
**Bug description**
If building for C++ (BUILD_OPENFAST_CPP_API), then `FIND_PACKAGE` requires that it finds OpenMP (https://github.com/OpenFAST/openfast/blob/main/CMakeLists.txt#L114). That will fail if openmp is not found but strictly speaking openmp should not be required when building the API. Further checks, check that it actually found OpenMP but the `REQUIRED` keyword does not actually let the code get to them.

**To Reproduce**
Build the CPP API on machine that does not have openmp and with the default `option(OPENMP "Enable OpenMP support" off)`.

**Expected behavior**
Described above

**Screenshots, if applicable**
NA
**OpenFAST Version**
3.5.2

**System Information (please complete the following information):**
 - OS: OSX
 - Compiler: GCC 13

**Comment by andrew-platt** [comment]
Thanks for letting us know! I'll take a look at this.

**Comment by andrew-platt** [comment]
See #2120 for proposed fix.

**Comment by andrew-platt** [comment]
Fixed with #2120.  This will be included in v3.5.3 later this week.
