### ISSUE TITLE
Misnamed NWTC_Library Registry files in Visual Studio project files in dev-unstable-branch 

### ISSUE THREAD

**Issue by bjonkman** [OpenFAST/openfast#2119]
The Visual Studio project files that contain NWTC_Library need to be updated with the new names of the Registry input files in the `dev-unstable-pointers` branch. They currently reference `..\..\modules\nwtc-library\src\Registry_NWTC_Library_typedef_nomesh.txt` and `..\..\modules\nwtc-library\src\Registry_NWTC_Library.txt`, but these files have been renamed in the recent history. When doing a rebuild, where it deletes the `*_Types.f90` files, it fails because the registry is trying to recreate `NWTC_Library_Types.f90` from one of these missing files.

See for example: https://github.com/OpenFAST/openfast/blob/3e49c6797be33526f6414018d4fd22841047aa5c/vs-build/FASTlib/FASTlib.vfproj#L2038

**Comment by andrew-platt** [comment]
I believe this was fixed with #2189
