### ISSUE TITLE
A Question About Inflow Wind

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#2137]
hello everyone，

I want to set the input wind speed position of wind turbine to 100 meters in front of the machine, can I set the WindVxiList parameter in the InflowWind INPUT FILE to -100 to achieve it? 

In addition, when turbsim generates the BTS file, can I set the parameter Z0 to achieve different surface roughness?

thanks.

**Comment by jjonkman** [comment]
Dear @shipors,

InflowWind input `WindVxiList` sets the location of the sensors used by InflowWind to output ambient wind through the `OutList`.  InflowWind doesn't allow you to specify the x-location of the wind field coming from TurbSim, if that is what you are asking about.

Regarding TurbSim input `Z0`, this input defines the surface roughness length if you've selected the logarithmic vertical wind profile (`WindProfileType` = "LOG").

Best regards,

**Comment by shipors** [comment]
dear @jjonkman 

I wonder if it is possible to set the X-direction position of the input wind when generating a wind speed file using TurbSim, meaning I would like to shift the generated wind from the hub location to 100 meters ahead of the turbine. Is this achievable?

Best wishes.

**Comment by jjonkman** [comment]
Dear @shipors,

InflowWind input `XOffset` is supported for HAWC-formatted wind data files to shift the wind data along the X axis, but I don't recall why this feature was not added for TurbSim-formatted wind data files when `XOffset` was implemented. My guess is the implementation would not be too difficult, but would require a source code change.

Best regards

**Comment by shipors** [comment]
Dear @jjonkman,

Ok thanks for your reply. I have two more queries that I would like to seek help.

First, I noticed that when selecting WindType as HAWC format in the InflowWind INPUT FILE, I need to enter u, v, w-component fluctuating wind. If all wind speeds in the v and w directions are set to 0m/s, will it affect the wind speed input in the X direction?

Secondly, I would like to know if the wind speed and turbulence intensity changes between the positions (100, 0, 0) and (200, 0, 0)? The above question assumes that there is no wind turbine drawing kinetic energy from the turbulent wind, and is not affected by other conditions, and that the wind speed starts at (0, 0, 0).

Best wishes.

**Comment by jjonkman** [comment]
Dear @shipors,

Regarding (1), the u, v, and w components are specified independently, so, zeroing v and w will not change u.

Regarding (2), the Mann box is a rectangular box in 3D containing frozen turbulence (that does not change in time).  In InflowWind, this box is made 4D (3D space + 1D time) by propagating the box along the mean wind direction at the hub-height wind speed.  So at a fixed (Y,Z) point at different X locations (assuming X is along the mean wind direction), the wind speed will change in time and the TI will remain constant.  The TI may change between different (Y,Z) points.

Best regards,

**Comment by shipors** [comment]
***@***.***,


In FAST.FARM, no matter where the turbine is located in the wind field, it is always subject to wind speeds consistent with the incoming wind until it is affected by the wake of some upstream turbine. (Assuming a steady state wind of 8m/s is input, the wind direction is constant, and the wind speed in front of the turbines in the wind farm starts at 8m/s at the same time)


In fact, I would like to set the input wind speed 100 meters in front of the wind turbine (assuming its a turbulent wind with an average wind speed of 15m/s, which I call WIND one, and the wind direction does not change), and after some time, the wind speed propagates to the hub of the wind turbine or to the wind turbine swept surface ( wind speed at this point is WIND two), and the WIND two is evolved from the WIND one by some kind of regularity, can this be Can this be realized?


Best Wishes!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenFAST/openfast"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月5日(星期五) 凌晨0:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFAST/openfast] A Question About Inflow Wind (Issue #2137)





 
Dear @shipors,
 
Regarding (1), the u, v, and w components are specified independently, so, zeroing v and w will not change u.
 
Regarding (2), the Mann box is a rectangular box in 3D containing frozen turbulence (that does not change in time).  In InflowWind, this box is made 4D (3D space + 1D time) by propagating the box along the mean wind direction at the hub-height wind speed.  So at a fixed (Y,Z) point at different X locations (assuming X is along the mean wind direction), the wind speed will change in time and the TI will remain constant.  The TI may change between different (Y,Z) points.
 
Best regards,

**Comment by jjonkman** [comment]
Dear @shipors,

I'm not sure I fully understand your question.  Just a couple comments:

If you use `Mod_AmbWind` = 2 or 3 in FAST.Farm, using InflowWind to set the wind data, and are using `WindType` = 1 or 2, the wind will be spatially uniform throughout the farm.  If you use `WindType` = 3, 4, 5, or 7, the wind will propagate based on Taylor's frozen turbulence assumption.  If you use `WindType` = 6 (user defined), you can define your own wind function (requiring a recompile of FAST.Farm).

If you use `Mod_AmbWind` = 1 in FAST.Farm, the wind inflow is expected to be four dimensional (u, v, and w defined in 3D space + time).

Best regards,
