### ISSUE TITLE
Testing OpenFAST

### ISSUE THREAD

**Issue by aleram06** [OpenFAST/openfast#215]
[Error running r-test.txt](https://github.com/OpenFAST/openfast/files/2660875/Error.running.r-test.txt)
Hi,

I'm new with OpenFAST and I'm getting troubles with the unit and regression tests.

I managed to install OpenFAST with Visual Studio using Windows 10. Then I´ve been trying to compile the unit tests following the section 5.2.1.2 of the OpenFast documentation, but when I make the target to test with make beamdyn_utest, I´m getting this error message: 

```
_C:\Users\ave\code\openfast\unit_tests>make beamdyn_utest
'make' is not recognized as an internal or external command,
operable program or batch file._
```

I added the path of the cmake´s executable to the environment variables, but it didn't fix the problem. I'm using Intel compiler 19.

On the other hand, I´ve followed the steps described in section 5.2.3 to execute the OpenFAST regression tests. However, all the tests fail with the following error:

```
(base) C:\Users\ave\code\openfast\reg_tests>python manualRegressionTest.py ..\build\bin\openfast_x64_Double.exe Windows Intel 1e-5
executing AWT_YFix_WSt                           'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
FAIL
```

I´m using Anaconda prompt.

Can someone help me with these issues?

Any help would be appreciated.

**Comment by aleram06** [comment]
Thank you for your reply.

See here the executable path:
```
>>> import os
>>> os.chdir(r'C:\Users\ave\code\openfast\reg_tests')
>>> import sys
>>> print(sys.executable)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe
```

and here lines from 73 to 79 in manualRegressionTest.py:

```
for case in casenames:
    print(strFormat(prefix).format(prefix), strFormat(longestName+" ").format(case), end="", flush=True)
    command = "{} executeOpenfastRegressionCase.py {} {} {} {} {} {} {} {} {}".format(pythonCommand, case, openfast_executable, sourceDirectory, buildDirectory, tolerance, machine, compiler, plotFlag, noExecFlag)
    returnCode = subprocess.call(command, stdout=outstd, shell=True)
    resultString = passString if returnCode == 0 else failString
    results.append((case, resultString))
    print(resultString)
```
Do you have any suggestion to fix the problem with the unit tests?

**Comment by aleram06** [comment]
Thank you @rafmudaf for your reply.
See here the executable path:
```
>>> import os
>>> os.chdir(r'C:\Users\ave\code\openfast\reg_tests')
>>> import sys
>>> print(sys.executable)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe
```
For value of `command` after line 75, please see attached document.
Do you have any suggestion to fix the problem with the unit tests?

**Comment by rafmudaf** [comment]
ok @aleram06 I've found the bug. Since your python interpreter has spaces in the path, I needed to wrap the execution command in quotes in `manualRegressionTest.py`. I've tested that this fixes things on my side, but you can verify that it works for you by implementing the change in the last commit of [this branch](https://github.com/rafmudaf/openfast/tree/bugfix/python_executable) on your local machine.

I've created a pull request for this fix.

**Comment by manmathan299** [comment]
Hi, after with unsuccessful attempt of openfast install in windows with cmake and cygwin
64

I managed to install OpenFAST with Visual Studio using Windows 10. Then I´ve been trying to compile the regression test following the  OpenFast documentation, but when I make the target to  regression test I´m getting this error message:
![regression](https://user-images.githubusercontent.com/37687398/65632123-90744a80-dff6-11e9-896d-982dd1c04bdc.JPG)
...could you please rectify the error

**Comment by rafmudaf** [comment]
@manmathan299 Be sure that you have the required dependencies installed as listed here:
https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#dependencies
