### ISSUE TITLE
openfast Simulink model Time step output

### ISSUE THREAD

**Issue by yinghanguan** [OpenFAST/openfast#2150]
Hello, in the openfast Simulink model, I want to build a reinforcement learning environment to control the pitch angle and obtain maximum power output. During this process, I hope that each time step can output current data, excluding historical data. How can I proceed?

**Comment by jjonkman** [comment]
Dear @yinghanguan,

OpenFAST can output the current data at each time step, but I'm not sure what you mean when you refer to "excluding historical data".

Best regards,

**Comment by yinghanguan** [comment]
![002533](https://github.com/OpenFAST/openfast/assets/62784838/03bfb5ed-9b4d-4f39-b737-67ccdb542d52)
When I run two time steps in the way shown in the above figure, the output of out. timeout is shown in the following figure,I hope to obtain the last column, which means that the output for each time step is [1,30]
![image](https://github.com/OpenFAST/openfast/assets/62784838/3097b661-90c6-47e0-bf41-b05782bd1b3c)

**Comment by jjonkman** [comment]
Dear @yinghanguan,

I'm not sure I really understand your question, but normally the `OutData` output from the OpenFAST S-Function block is a one-dimensional array containing the values of the OpenFAST outputs at the current time step.

Best regards,

**Comment by yinghanguan** [comment]
In my simulation results, it is obvious that the output is a two-dimensional array, and the output contains data for both the current and historical time steps, which is different from what I wanted. I only need data for the current time step

**Comment by jjonkman** [comment]
It doesn't look like you are using the `OutData` output from the OpenFAST S-Function block, but rather, you are looking at the output of a bock you added.  What does `OutData` look like directly?
