### ISSUE TITLE
Request for torque of intermediate shaft

### ISSUE THREAD

**Issue by AzureJi** [OpenFAST/openfast#2160]
In TEST18, is there a way to directly obtain the torque of the intermediate shaft? And if you need to calculate it, how do you calculate it with those quantities？

**Comment by jjonkman** [comment]
Dear @AzureJi,

You've asked a similar question in the OpenFAST discussion at: https://github.com/OpenFAST/openfast/discussions/2159.  I've responded there and will close this duplicate issue.

Best regards,
