### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jagdeeps90** [OpenFAST/openfast#2166]
Hello,

I have LES data which I am saving as time series of planar inflow data in vtk format at sampling frequency of 2Hz. So, I have number of vtk files which U V W.

How can introduce this vtk files and do analysis of bending moments, pitch and generator speed fluctuations.

P.S. I am able to input a time series at a single spatial point which will be uniform across the rotor region.

**Comment by jjonkman** [comment]
Dear @jagdeeps90,

Are you trying to input your LES inflow data in VTK format into OpenFAST or FAST.Farm?

FAST.Farm already supports the use of inflow data in VTK format (via `Mod_AmbWind` = 1).

If you mean OpenFAST, the InflowWind module of OpenFAST cannot currently make use of VTK format directly, so, you'd either have to convert the VTK data to a format that is supported by InflowWind (e.g., TurbSim's BTS format), or to change the InflowWind source code to make use of your VTK data directly (e.g., through the user-defined wind option, `WindType` = 6).

Best regards,

**Comment by jagdeeps90** [comment]
Yes, I am trying to input LES data into OpenFast for the Analysis of an individual wind turbine. Thanks for the information. Now, I think I am getting into something.

**Comment by jagdeeps90** [comment]
Dear @jjonkman ,

I would like to know which component in the out list is the out of plane bending moment which acts perpendicular to the plane of the rotation. There are 70 or so output channels. I am not sure which one represents MoOp. 

Thanks 
Jagdeep

**Comment by jjonkman** [comment]
Dear @jagdeeps90,

There are far more than 70 outputs available through the various `OutList` of OpenFAST modules.  For a complete list, see: https://openfast.readthedocs.io/en/main/_downloads/3f19498a5dc774461e022b671ff01ec6/OutListParameters.xlsx.  From ElastoDyn, the output-of-plane bending moment is `RootMyc1` (or `RootMOoP1`) for blade 1 (likewise for blades 2 and 3).

Best regards,

**Comment by jagdeeps90** [comment]
Dear @jjonkman,

Thanks for the information; it helps me a lot.

Thanks
Jagdeep
