### ISSUE TITLE
A question about generator model in MATLAB simulation model

### ISSUE THREAD

**Issue by Tomedssa** [OpenFAST/openfast#2170]
Hello everyone，

In the process of using the MATLAB simulation model provided by openfast (i.e. Test01_SIG.mdl), I am a little confused about the generator model. May I ask how the generator model is built? Is this generator model an asynchronous generator model, a doubly-fed generator model, or some other type of generator model?

Thanks.

**Comment by jjonkman** [comment]
Dear @Tomedssa,

The simple induction generator (SIG) model of _Test01_SIG.mdl_ is a model of the same SIG model available within ServoDyn via `VSContrl` = 0, `GenModel` = 1.  The SIG model is a very simple representation of an induction (asynchronous) generator.  See the old FAST v6 User's Guide for more information: https://openfast.readthedocs.io/en/main/_downloads/d8bd014121d6505cb25cf49bee5eaa80/Old_FAST6_UsersGuide.pdf.

Best regards,

**Comment by Tomedssa** [comment]
Dear @jjonkman，

Thank you for your reply.When running the Test01_SIG.mdl model, I also encountered another problem, that is, when the pitch angle is changed, the electromagnetic torque and generator power generated  by the Test01_SIG.mdl model is negative.Do you know what caused it?The result is shown in the file.
[picture.docx](https://github.com/OpenFAST/openfast/files/15051279/picture.docx)

Thanks.

**Comment by jjonkman** [comment]
Dear @Tomedssa,

It looks like your pitch controller has driven the rotor to near synchronous speed, where the power is close to zero.

FYI: The AWT-27CR2 wind turbine you are simulating by default has fixed pitch.

Best regards,

**Comment by Tomedssa** [comment]
Dear @jjonkman，

Thank you for your reply.The type of wind turbine I use is 5MW_OC4Semi_WSt_WavesWN.
![image](https://github.com/OpenFAST/openfast/assets/149127552/a217ba0d-a174-461c-93dd-469d71a5f3e7)
When I used the simple induction generator that came with Test01_SIG.mdl, I could not solve the problem of negative torque, so I used the torque control of the PI-controlled progressive generator, but the power was stable at about 4 MW.I think it may be caused by the random value of my PI parameter. So I would like to ask, when the torque control adopts PI control, is the determination of PI parameters obtained by progressive linearization near a certain operating point?

Thanks.

**Comment by jjonkman** [comment]
Dear @Tomedssa,

It sounds like you posted a similar question about PI parameters on the ROSCO GitHub site: https://github.com/NREL/ROSCO/issues/340.  I'll go ahead and close this issue and you can continue the discussion there.

Best regards,
