### ISSUE TITLE
After compiling OpenFAST and running it in MATLAB, it crashes!

### ISSUE THREAD

**Issue by WS991106** [OpenFAST/openfast#2172]
Dear @jjonkman ,
        
I've been learning about OpenFAST compilation recently, and after I compile it according to the guidebook on the official website, I open Run_OpenLoop inside Simulink, and then after writing the address of the .fst file and clicking OK, MATLAB just flashes and crashes straight away to the point that I can't see what's wrong, so I thought I'd come and ask you about it. The compiled file is attached. 

Best regards,
Wangshuai
![1713878539749](https://github.com/OpenFAST/openfast/assets/143490138/cf77e787-c960-4ae0-a0da-45d913793d37)
![1713878548886](https://github.com/OpenFAST/openfast/assets/143490138/fe7b6ded-cef7-4ad4-9b4b-79898a0a9486)

**Comment by jjonkman** [comment]
Dear @WS991106,

I don't see the _FAST_SFunc.mex64_ file in your list (perhaps it is cut-off)?  Have you compiled this yourself too?

Does the OpenFAST-Simulink interface work for you if you use the `precompiled FAST_SFunc.mex64` and `OpenFAST-Simulink_x64.dll` binaries available through the NREL release of OpenFAST: https://github.com/OpenFAST/openfast/releases?

Best regards,

**Comment by WS991106** [comment]
Dear @jjonkman ,

On my side it shows that it is inside the image, maybe it is cut-off, this thing is compiled by myself with create_FAST_SFunc.m. However, it is working fine for me with the pre-compiled file provided on the official website, so I don't know what the problem is.
Then I also want to ask if the compilation process needs to recompile FAST_SFunc.mex64 and OpenFAST-Simulink_x64.dll if I want to do active mooring control to modify the underlying code?

Best regards,
Wangshuai
![1713930533003](https://github.com/OpenFAST/openfast/assets/143490138/ac0c4940-3601-4e94-8b9e-c6944896194e)

**Comment by jjonkman** [comment]
Dear @WS991106,

I'm not sure what the issue is with the versions of the _FAST_SFunc.mex64_ and _OpenFAST-Simulink_x64.dll_ binaries that you compiled yourself.  Did you change the source code in any way before compiling?

OpenFAST does not currently support a active mooring control though the Simulink interface (active mooring control through the controller DLL is standard), so, if you want that functionality, you'd have to modify the source code and recompile.

Best regards,

**Comment by WS991106** [comment]
Dear @jjonkman ，

Before I compiled it there was no modification of the source code, it was all compiled and installed according to the files on Github, because after running Matlab is crashing directly without reporting errors, so it has been bothering me to know what the problem is.

I know OpenFAST doesn't know about active mooring control, I mean if I want to modify the source code when recompiling the FAST.sln file, do I have to build all the following five solutions or do I not need to rebuild OpenFAST-Simulink? If I don't need to rebuild OpenFAST-Simulink, I would like to use the github pre-compiled OpenFAST-Simulink_x64.dll file.
![1714273321214(1)](https://github.com/OpenFAST/openfast/assets/143490138/d81a3b9a-30c4-4c83-b9eb-5e6b404539d0)


Best regards，

**Comment by bjonkman** [comment]
If you modify any source files in the `FASTlib` or `OpenFAST-Simulink` projects, you will need to build the .dll file again (instead of using the file distributed with OpenFAST). There are a few different ways you can build the files for Simulink. Can you describe your process here, and include which versions of compilers and Matlab you are using?

**Comment by WS991106** [comment]
Dear @bjonkman ，

Sorry for not replying to your message in time, what do I need to recompile if I want to change the code in the MoorDyn.f90 file? The compiler I am using is VS2019 and Matlab is 2022a.

Best regards，

**Comment by WS991106** [comment]
Dear @bjonkman ,

My compilation process is as follows, could you please take a look to see if there is any error? I have set up the five solutions in the configuration manager as follows.
![1715155087900](https://github.com/OpenFAST/openfast/assets/143490138/0ce8fb19-0c07-4b63-a83f-f0102bb104cf)

After that the solution is generated and it will show 5 successes, then I use Matlab to generate the FAST_SFunc.mex64 file. After success run Run_OpenLoop.m, it will just crash.

**Comment by WS991106** [comment]
Dear @bjonkman 

Thank you so much for your help, the Matlab crash problem has been solved, thank you very much indeed!

Best regards，
