### ISSUE TITLE
making fault 

### ISSUE THREAD

**Issue by dorsamgh** [OpenFAST/openfast#2177]
Hello, I hope you are doing well. I want to create several faults, including blade and mooring faults, by modifying the source code of OpenFAST version 3.3.0. I would like to know if there is any resource or structure available for this task? If possible, please guide me.
Also, I have read these [conversation](https://forums.nrel.gov/t/making-fault/1260), but I need some guidance on how to start from scratch.

**Comment by jjonkman** [comment]
Dear @dorsamgh,

I don't think I can provide much guidance on blade and mooring faults beyond on blade and mooring faults what is already discussed in the forum post you cross-referenced.  Do you have a specific question as to what is discussed in that forum post?

If you question is how to change the source code and recompile OpenFAST, I refer you to the OpenFAST documentation: https://openfast.readthedocs.io/en/main/source/install/index.html#compile-from-source.

Best regards,

**Comment by dorsamgh** [comment]
Dear @jjonkman,

Thank you for your response. Actually, I want to create some faults on  IEA-15-240-RWT-UMaineSemi using OpenFAST. I know how to compile the .exe file from the source code and have been able to compile a normal .exe file. Now, my question might seem simple, To simulate a specific fault such as a seized blade, should I modify the files related to the OpenFAST source code or the modules related to the 15 MW wind turbine such as servodyn ?
thanks again.

**Comment by jjonkman** [comment]
Dear @dorsamgh,

For a fault related to blade seizure (the blade pitch actuator not responding to the pitch controller), you can use the override pitch maneuver settings available directly through the ServoDyn input file, with no source code change or recompile required.  This topic has also been discussed on our forum, e.g., see: https://forums.nrel.gov/t/how-to-create-a-actuator-and-sensor-fault-in-open-fast/5577.

Best regards,

**Comment by dorsamgh** [comment]
Dear @jjonkman,

Hello. Thank you for your response and I apologize for the late reply to this message. Based on the parameters of the ServoDyn module, I created a fault related to blade seizure. Additionally, using the same method, I created a fault related to yaw angle change by altering NacYawF at the desired time. Now, my question is how can I create this fault in an intermittent manner? Is it possible to do this by changing the module parameters, or do I need to modify the source code?

---

**Comment by jjonkman** [comment]
Dear @dorsamgh,

If by "intermittent" you mean the fault coming and going, that is not possible through the simple override maneuvers available in ServoDyn.  You would need to modify the source code for such a condition.

Best regards,

**Comment by dorsamgh** [comment]
Dear @jjonkman 
thank you for your response, to modify the source code of ServoDyn, should i continue along to the "openfast-3.3.0\modules\servodyn\src\ServoDyn.f90" path and apply my changes in the .dat file and then compile the FAST ("openfast-3.3.0\vs-build\FAST\FAST.sln")?

**Comment by jjonkman** [comment]
Yes, that sounds correct.

**Comment by dorsamgh** [comment]
Thank you. I have two more questions. To modifying the source code of ServoDyn, should the yaw angle be defined in radians or degrees? And finally, after obtaining the exe file, should I set the YCMode value to 3? The function I defined in the source code is as follows:
![image](https://github.com/OpenFAST/openfast/assets/60191807/118a8003-a6f2-4b5d-a0c5-2faf09ef8ef2)
![image](https://github.com/OpenFAST/openfast/assets/60191807/6081b5ef-4398-4a28-9af1-3533e2362ba5)
![image](https://github.com/OpenFAST/openfast/assets/60191807/f127835e-856b-4d83-bc04-8a7a46b0b3cd)

**Comment by jjonkman** [comment]
Dear @dorsamgh,

The internal unit for yaw angle within OpenFAST is radians.

It doesn't look like you've edited the placeholder `SUBROUTINEUserYawCont()`, but you should select `YCMode` = 3 if you place your user-defined yaw-control logic in this routine.

Best regards,

**Comment by dorsamgh** [comment]
Dear @jjonkman 

I created a subroutine called `CustomUserYawCont()`, and as shown in the images, I called it in the (ControlMode_USER) state. Should I name the function `UserYawCont()` and define this subroutine?

**Comment by jjonkman** [comment]
Dear @dorsamgh,

By setting `TYawManS` to 0, the yaw maneuver will override the yaw controller already at the beginning of the simulation.  If you want to use your `UserYawCont()` logic throughout the simulation, set `TYawManS` > `TMax`.

Best regards,

**Comment by dorsamgh** [comment]
Dear @jjonkman 
thank you, that was exactly the problem. and now by adjusting this parameter, i have achieved the desired result. thank you for your response and guidance.
