### ISSUE TITLE
Unit testing OpenFAST on ubuntu 22.04

### ISSUE THREAD

**Issue by TorbenKnudsen** [OpenFAST/openfast#2184]
I have installed OpenFAST and can run it as shown below

~/OpenFAST/build $ ~/OpenFAST/install/bin/openfast -v

 **************************************************************************************************
 OpenFAST

 Copyright (C) 2024 National Renewable Energy Laboratory
 Copyright (C) 2024 Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v3.5.3
 Compile Info:
  - Compiler: GCC version 11.4.0
  - Architecture: 64 bit
  - Precision: double
  - OpenMP: No
  - Date: May  3 2024
  - Time: 14:11:20
 Execution Info:
  - Date: 05/06/2024
  - Time: 10:56:15+0200

  OpenFAST terminated normally.

I then like to do some more test e.g. unit test but that is not successful.
Any help on what I am doing wrong is appreciated

~/OpenFAST/build $ cmake .. -DBUILD_TESTING=ON 
-- Enabling Fortran 2008 features
-- Setting system file as: src/SysGnuLinux.f90
CMake Error at reg_tests/CMakeLists.txt:79 (add_subdirectory):
  The source directory

    /home/tk/OpenFAST/reg_tests/r-test

  does not contain a CMakeLists.txt file.

CMake Error at reg_tests/CMakeLists.txt:89 (file):
  file COPY cannot find
  "/home/tk/OpenFAST/reg_tests/r-test/glue-codes/openfast/5MW_Baseline": No
  such file or directory.

CMake Error at reg_tests/CMakeLists.txt:89 (file):
  file COPY cannot find
  "/home/tk/OpenFAST/reg_tests/r-test/glue-codes/openfast/AOC": No such file
  or directory.

CMake Error at reg_tests/CMakeLists.txt:89 (file):
  file COPY cannot find
  "/home/tk/OpenFAST/reg_tests/r-test/glue-codes/openfast/AWT27": No such
  file or directory.

CMake Error at reg_tests/CMakeLists.txt:89 (file):
  file COPY cannot find
  "/home/tk/OpenFAST/reg_tests/r-test/glue-codes/openfast/SWRT": No such file
  or directory.

CMake Error at reg_tests/CMakeLists.txt:89 (file):
  file COPY cannot find
  "/home/tk/OpenFAST/reg_tests/r-test/glue-codes/openfast/UAE_VI": No such
  file or directory.

CMake Error at reg_tests/CMakeLists.txt:89 (file):
  file COPY cannot find
  "/home/tk/OpenFAST/reg_tests/r-test/glue-codes/openfast/WP_Baseline": No
  such file or directory.

CMake Error at reg_tests/CMakeLists.txt:94 (file):
  file COPY cannot find
  "/home/tk/OpenFAST/reg_tests/r-test/glue-codes/openfast/5MW_Baseline": No
  such file or directory.

CMake Error at reg_tests/CMakeLists.txt:100 (file):
  file COPY cannot find
  "/home/tk/OpenFAST/reg_tests/r-test/glue-codes/fast-farm/5MW_Baseline": No
  such file or directory.

CMake Error at /usr/share/cmake-3.22/Modules/ExternalProject.cmake:2882 (message):
  No download info given for 'pfunit' and its source directory:

   /home/tk/OpenFAST/unit_tests/pfunit

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/ExternalProject.cmake:3716 (_ep_add_download_command)
  unit_tests/CMakeLists.txt:44 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/tk/OpenFAST/build/CMakeFiles/CMakeOutput.log".
See also "/home/tk/OpenFAST/build/CMakeFiles/CMakeError.log".
~/OpenFAST/build $

**Comment by deslaughter** [comment]
The regression tests are in a git submodule which is not automatically initialized when cloning OpenFAST. Please run `git submodule update --init --recursive` to download the regression tests.

**Comment by TorbenKnudsen** [comment]
Derek, thanks for the response. I will try this later. Now I will fight some errors that is not due to OpenFAST.
