### ISSUE TITLE
OpenFAST test input files

### ISSUE THREAD

**Issue by gilcastroh** [OpenFAST/openfast#219]
Much like the CertTest folder on FAST v7 and v8, does OpenFAST provide a sample library of input test files?
I'm new to OpenFAST and I have been fiddling with it and FAST v7 and v8, and while these two have sample files OpenFAST does not, so I tried copying the ones from v8. For Test01, there was an output, but running OpenFAST for Test02 and 03 gave me a message saying:

Invalid logical input for file
".\AWT27/Test02_AD15.ipt" occurred while trying to read CavitCheck.

Was it wrong to even try to get v8 files to work? Should I modify the v8 files somehow? Is there a library of sample input files somewhere? I tried searching but didn't find one.

Thanks in advance.

**Comment by jjonkman** [comment]
Dear @gilcastroh,

What used to be the CertTest in FAST v7 and FAST v8 has become the regression test (r-test) in OpenFAST: https://github.com/OpenFAST/r-test. All of FAST v8 CertTest models (Test01 through Test26) have been migrated to the OpenFAST r-test, and a few additional tests have been added.  The module-level BeamDyn CertTests have also been migrated to the OpenFAST r-test, but the other module-level CertTests still need to get moved per OpenFAST issue https://github.com/OpenFAST/openfast/issues/178, https://github.com/OpenFAST/openfast/issues/179, and https://github.com/OpenFAST/openfast/issues/181.

Best regards,

**Comment by gilcastroh** [comment]
Thank you,

I've found and downloaded that folder. Still, not all of them work, but that may have been (my clumsiness) because I had not built OpenFAST (oddly it still does something).
I tried building OpenFAST with Visual Studio on Windows but could not. Maybe I'll make a new issue but not yet. I followed the guide and got these errors. I've seen fixes for this but they have all been marked as merged already. Why isn't building working? Also, dumb question, do I need to build it to run analysis (if not, why did it work before, even if not often)?

Apologies for what's probably just my clumsiness,

'''
Severity	Code	Description	Project	File	Line	Suppression State
Error		Compilation Aborted (code 1)		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	1	
Error		error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FAST_SUBS]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	35	
Error		error #6404: This name does not have a type, and must have an explicit type.   [DBKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	40	
Error		error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [DBKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	40	
Error		error #6592: This symbol must be a defined parameter, an enumerator, or an argument of an inquiry function that evaluates to a compile-time constant.   [DBKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	40	
Error		error #6683: A kind type parameter must be a compile-time constant.   [DBKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	40	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	41	
Error		error #6457: This derived type name has not been declared.   [FAST_TURBINETYPE]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	44	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	46	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	47	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	48	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	54	
Error		error #6404: This name does not have a type, and must have an explicit type.   [PROGNAME]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	60	
Error		error #6632: Keyword arguments are invalid without an explicit interface.   [FLAG]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	63	
Error		error #6404: This name does not have a type, and must have an explicit type.   [TURBINE]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	66	
Error		error #6363: The intrinsic data types of the arguments must be the same.   [MOD]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	113	
Error		error #6362: The data types of the argument(s) are invalid.   [TRIM]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	114	
Error		error #6404: This name does not have a type, and must have an explicit type.   [NUM2LSTR]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	114	
Error		error #6362: The data types of the argument(s) are invalid.   [TRIM]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	114	
Error		error #6404: This name does not have a type, and must have an explicit type.   [ERRID_SEVERE]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	117	
Error		error #6404: This name does not have a type, and must have an explicit type.   [ABORTERRLEV]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	117	
Error		error #6363: The intrinsic data types of the arguments must be the same.   [MIN]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	118	
Error		error #6054: A CHARACTER data type is required in this context.   [NEWLINE]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	119	
Error		error #6404: This name does not have a type, and must have an explicit type.   [NEWLINE]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	119	
Error		error #6404: This name does not have a type, and must have an explicit type.   [ERRID_NONE]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	149	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	160	
Error		error #6683: A kind type parameter must be a compile-time constant.   [INTKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	165	
Error		error #6054: A CHARACTER data type is required in this context.   [NEWLINE]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	169	
Error		error #6054: A CHARACTER data type is required in this context.   [NEWLINE]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	169	
Error		error #6837: The leftmost part-ref in a data-ref can not be a function reference.   [TURBINE]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	175	
Error		Error running FAST Registry for Lidar.		C:\code\openfast\modules-local\inflowwind\src\Lidar.txt	1	
Error		error PRJ0019: A tool returned an error code from "Running Registry for Lidar"		Project		
Warning		warning #8586: Implicit type is given to allow out-of-order declaration. Non-standard extension.   [DBKI]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	40	
Warning		warning #6931: Fortran 2003 does not allow this assignment statement.   ['OpenFAST']		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	60	
Warning		warning #6187: Fortran 2003 requires an INTEGER data type in this context.   [N_TMAX_M1]		C:\code\openfast\glue-codes\openfast\src\FAST_Prog.f90	107	
'''

**Comment by rafmudaf** [comment]
@gilcastroh try closing and reopening Visual Studio. Can you post specific steps you used to compile? Also, see [issue#152](https://github.com/OpenFAST/openfast/issues/152).

**Comment by gilcastroh** [comment]
I'll try going through that issue. In the mean time, here's what I have done.
- I have installed Intel® Parallel Studio XE 2019 Cluster, Git and Python 3.7 (32 bit)
- Used the files from https://github.com/openfast/openfast.git
- Opened FAST.sln
- Accepted to upgrade VC++ Compiler and Libraries
- Chose Release and Win32, then Build Solution (not Build FAST)
- Got 33 errors and 3 warnings, closed and opened FAST.sln again, Build it again
- This time I got 32 errors and 3 warnings
- There was nothing in the bin folder

**Comment by gilcastroh** [comment]
Following the issue, I tried the following:
- Built FASTlib before FAST. Got 32 errors and 3 warnings. Closed and opened, repeat, same number of errors
- Opened RunRegistry.bat on FASTlib\Resource Files and tried to change its line endings to Windows line endings. I found none. There was supposed to be no need for this, since this issue has already been fixed, but I still used Visual Studio and Notepad+ to look for \r or \n. I also went to Edit-EOL Conversion-Windows, but the file was already on Windows format

**Comment by bjonkman** [comment]
I see in your error list that there was a problem with running the FAST Registry, and since there was nothing in the bin folder, I assume the FAST_Registry project didn't build. 

Can you open the FAST.sln file, right-click on the FAST_Registry, then click on `Project Only->Build Only FAST_Registry`. I assume this will fail... and if it does, can you attach/paste the build log here?

**Comment by gilcastroh** [comment]
However, it still doesn't work. I tried running the AWT_YFree_WSt test file by moving the openfast_Win32 application and MAP_Win32.dll into the folder with AWT_YFree_WSt.fst. Running it gave me this:
```
C:\OpenFAST\r-test-master\glue-codes\openfast\AWT_YFree_WSt>openfast_win32 AWT_YFree_WSt_AD.fst

**************************************************************************************************
OpenFAST

Copyright (C)  National Renewable Energy Laboratory
Copyright (C)  Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v2.0.0-dirty
Compile Info:
 - Architecture: 32 bit
 - Precision: single
 - Date: Dec 21 2018
 - Time: 10:14:16
Execution Info:
 - Date: 12/21/2018
 - Time: 13:30:14-0000


FAST_InitializeAll:FAST_Init:FAST_ReadPrimaryFile:OpenFInpFile:The input file,
"AWT_YFree_WSt_AD.fst", was not found.

 FAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.
```
Anything wrong with my compilation? Thanks in advance

**Comment by gilcastroh** [comment]
I believe it is working now. Before I consider it done, can you confirm that the annexed image show the correct output of the AWT_YFree_WSt.out file? I got it by copying the openfast_Win32 application and MAP_Win32.dll into the folder with AWT_YFree_WSt.fst. On the command prompt, I ran this:
> C:\OpenFAST\r-test-master\glue-codes\openfast\AWT_YFree_WSt>openfast_win32 AWT_YFree_WSt.fst
and got this:
```
C:\OpenFAST\r-test-master\glue-codes\openfast\AWT_YFree_WSt>openfast_win32 AWT_YFree_WSt.fst

**************************************************************************************************
OpenFAST

Copyright (C)  National Renewable Energy Laboratory
Copyright (C)  Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v2.0.0-dirty
Compile Info:
 - Architecture: 32 bit
 - Precision: single
 - Date: Dec 21 2018
 - Time: 10:14:16
Execution Info:
 - Date: 12/21/2018
 - Time: 13:41:23-0000

OpenFAST input file heading:
    FAST Certification Test #03: AWT-27CR2 with many DOFs with free yaw and steady wind.

Running ElastoDyn.
Running AeroDyn.
Running AirfoilInfo.
Running BEM.
Running UnsteadyAero.
Running InflowWind.
Running ServoDyn.
 Time: 0 of 20 seconds.
Warning: Turning off Unsteady Aerodynamics due to high angle-of-attack. BladeNode = 1, Blade = 1,
A0A = 66.423 deg
Warning: Turning off Unsteady Aerodynamics due to high angle-of-attack. BladeNode = 2, Blade = 1,
A0A = 52.04 deg
Warning: Turning off Unsteady Aerodynamics due to high angle-of-attack. BladeNode = 1, Blade = 2,
A0A = 45.114 deg
Warning: Turning off Unsteady Aerodynamics due to high angle-of-attack. BladeNode = 2, Blade = 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

 Total Real Time:       9.304 seconds
 Total CPU Time:        9.2031 seconds
 Simulation CPU Time:   9.125 seconds
 Simulated Time:        20 seconds
 Time Ratio (Sim/CPU):  2.1918

 OpenFAST terminated normally.
```
Thanks in advance if it's wrong, thank you so much for this Christmas present if it's right
 
![awt_yfree_wst out](https://user-images.githubusercontent.com/45944124/50345346-98aecf00-0526-11e9-8dde-cb6aefc00cff.PNG)

**Comment by jjonkman** [comment]
Yes, it looks like you compiled OpenFAST v2 properly and the results are correct.  You can compare your results with the NREL-generated baseline by comparing your outputs to those from the windows-intel subdirectory.  The results will differ slightly because you are compiling in single precision whereas the NREL baselines were generated with double precision.  (But I would recommend compiling in single for general engineering use where time-to-solution is important.)

**Comment by gilcastroh** [comment]
Oh… good to know I have files to compare, and awesome to know I've got this sorted! Thanks again for your time!
