### ISSUE TITLE
Where can I find the TMD corresponding input file of 15MW wind turbine, such as NRELOffshrBsline5MW_ServoDyn_StC.dat in 5MW wind turbine

### ISSUE THREAD

**Issue by Bq2181** [OpenFAST/openfast#2197]

**Comment by jjonkman** [comment]
Dear @Bq2181,

NREL has not developed an OpenFAST model of the IEA Wind 15-MW RWT with a TMD as far as I know, but if you have specific TMD parameters in mind, you can always develop this OpenFAST model yourself using the NREL 5-MW example as a template.

Best regards,

**Comment by Bq2181** [comment]
> Dear @Bq2181,
> 
> NREL has not developed an OpenFAST model of the IEA Wind 15-MW RWT with a TMD as far as I know, but if you have specific TMD parameters in mind, you can always develop this OpenFAST model yourself using the NREL 5-MW example as a template.
> 
> Best regards,

Ok, thank you very much for your answer.
