### ISSUE TITLE
Apple clang v 15.0.0 cannot build registry

### ISSUE THREAD

**Issue by andrew-platt** [OpenFAST/openfast#2204]
**Bug description**
On a Mac using the default _c_ compiler _clang_ from Apple, the following error occurs while building the registry (`dev` branch at commit a98f8bce6):

![Screenshot 2024-05-10 at 3 41 59 PM](https://github.com/OpenFAST/openfast/assets/2745453/bc09d374-aea6-43ff-871a-93b1a7f7a34e)

Compiler specifics: 

```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

The alternative is to use the _gcc_ compiler. However, we are likely to get questions on this if we don't address it.

**Comment by deslaughter** [comment]
The `openfast_registry` CMakeLists.txt file has the wrong version for the C++ standard. `std::quoted` is part of the C++14 standard, whereas the current version is listed as C++11. Most compilers in use should support C++14 so I'll summit a PR to change the required C++ standard version.

**Comment by andrew-platt** [comment]
Fixed with 2210
