### ISSUE TITLE
FASTFarm simulation floating wind farm

### ISSUE THREAD

**Issue by cjwan12589** [OpenFAST/openfast#2206]
Dear Professor jjonkman,
I have some questions about FASTFarm simulation floating wind farm, after I set all the input files, the operation error was reported. The screenshot of the error is as follows, but I don't understand what it means. Could you please take a look and give me some guidance? The following is my FASTFarm main input file, please also take a look, is there a problem with the grid Settings?
![报错截图](https://github.com/OpenFAST/openfast/assets/155708766/87aa1632-9ed4-40b0-9128-e380204bc7be)
[FASTFarm.txt](https://github.com/OpenFAST/openfast/files/15282901/FASTFarm.txt)

**Comment by jjonkman** [comment]
Dear @cjwan12589,

Similar questions were asked and answered in the following OpenFAST issues: #2027, #1613, and #1044.

Best regards,
