### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BAbaka626** [OpenFAST/openfast#2207]
Dear@jjonkman 

I am a master's student and am currently doing research on wind field optimization. I need your article after making data. (Validation of FAST.Farm Against Large-Eddy Simulations To cite this article: JJonkman et al 2018 J. Phys.: Conf.Ser.1037062005) Regarding the data of SOWFA simulation results, could you please provide me with relevant simulation result data for reference? Thank you very much for your help.

GLORIA

**Comment by jjonkman** [comment]
Dear @BAbaka626,

Unfortunately, due to the large size of the SOWFA dataset, I'm quite sure that the SOWFA simulation results from that paper have since been deleted.

Best regards,
