### ISSUE TITLE
some questions when fixing pitch angle

### ISSUE THREAD

**Issue by Wangzhenyu12** [OpenFAST/openfast#2218]
I am studying the aerodynamic imbalance caused by the presence of pitch angle error in a single blade. 
      My OpenFAST version is v3.4.1.  The model is 5MW onshore wind turbine and I use Beamdyn.
      I use the method of modifying the parameters in #1035,  make PCMode = 0 in ServoDyn and BlPitch(1)=3   BlPitch(2)=0    BlPitch(3)=0   in ElastoDyn.
      Since I don't control rotor speed , GenDOF is still True and CompServo =1.
![image](https://github.com/OpenFAST/openfast/assets/74004322/cb80e036-eace-4789-80b4-28222b8689b6)
![image](https://github.com/OpenFAST/openfast/assets/74004322/ec611964-b681-41d9-be29-81422eb6f22d)
      The wind speed time-series is a turbulent wind with an average wind speed of 9 m/s. The blades do not pitch in normal operating condition at this wind speed.
      And the calculations give strange results like these two figures. 
![image](https://github.com/OpenFAST/openfast/assets/74004322/feebfc7c-c297-4e55-9359-dfad8c5874b7)
![image](https://github.com/OpenFAST/openfast/assets/74004322/ea984e8b-907a-43d9-aeac-a1dd2bec62ec)
      I also decrease pitch angle error, when BlPitch(1)=0.5, the results seem reliable.
      But when I make BlPitch(1)=BlPitch(2)=BlPitch(3)=3, there is no pitch angle error ,the results are still strange and similar to these two figures.
     Please tell me what's wrong and how to deal with it.  Thanks!

**Comment by Wangzhenyu12** [comment]
Dear [jjonkman](https://github.com/jjonkman)

Thanks for your quick reply. According to your advice, I make VSContrl = 1 and set simple variable-speed torque control parameters based on 《Definition of a 5MW Reference Wind Turbine for Offshore System Development》, then I get reasonable simulation results.

And I have another question, if I want to simulate a condition that the pitch angle of blade 1 is always larger than the other two  blades by a fixed value during the pitching process, what should I do?

Best regards,

**Comment by jjonkman** [comment]
Dear @Wangzhenyu12,

To simulate a fixed blade-pitch angle offset error, you have a few options:

- You can define the pitch offset by adding a fixed offset to the aerodynamic and structural twist in the AeroDyn blade input files  and the ElastoDyn (or BeamDyn) blade input files (using different files for each blade), respectively;
- if active pitch control is disabled, you can define the offset via the fixed pitch angles set in ElastoDyn (through inputs `BlPitch`(1-3)); or
- If active pitch control is enabled, you can define the pitch offset directly within the controller.

Best regards,

**Comment by xiaolan0195** [comment]
> 亲爱的 [jjonkman](https://github.com/jjonkman)
> 
> 感谢您的快速回复。根据您的建议，我根据《海上系统开发用 5MW 参考风力涡轮机的定义》制作 VSContrl = 1 并设置简单的变速转矩控制参数，然后我得到了合理的仿真结果。
> 
> 我还有一个问题，如果我想模拟一个情况，即在俯仰过程中，叶片 1 的俯仰角总是比其他两个叶片大一个固定值，我该怎么办？
> 
> 此致敬意

Hello!
I encountered the same problem. I conducted research on two wind farms with wind turbines. The upstream wind turbines were subjected to pitch control, with a uniform pitch of 2 °, to examine the impact on downstream wind turbine power and the overall wind farm. The power output value of the upstream fan shows negative values and oscillations, but when the pitch is uniformly adjusted by 1 °, the results are more reasonable. May I ask how you modified the torque control module to achieve a more reasonable output with a larger pitch angle?

![Image](https://github.com/user-attachments/assets/a0a10793-9e68-483f-94af-044251068777)

![Image](https://github.com/user-attachments/assets/f3ae0b74-fbd2-4aa7-ad70-5380b150815d)

![Image](https://github.com/user-attachments/assets/8bfa74ad-21da-4121-85c8-f78f885e7974)

best wishes！

**Comment by Wangzhenyu12** [comment]
@xiaolan0195  一年了，原始文件找不到了。我记得就让 VSContrl = 1，然后把下面的 SIMPLE VARIABLE-SPEED TORQUE CONTROL 的四个数改掉。取值在《Definition of a 5MW Reference Wind Turbine for Offshore System Development》的7.2节里有给。

**Comment by davidricarteSP** [comment]
Dear  @jjonkman 
I am simulating pitch failure cases in which I fix one blade at an angle of 10º, for example, (at a mean wind speed of 14 m/s) and leave the other blades operating normally under the control of the controller during the entire simulation time. I am having difficulty setting the input parameters of the Servodyn and Elastodyn modules and the DISCON.IN file. Could you please help me by indicating which parameters I should change and in what way so that this simulation produces the results I am looking for?

**Comment by jjonkman** [comment]
Dear @davidricarteSP,

You can use the override pitch maneuver inputs in ServoDyn to prescribe a fault where one blade fails to responds to the pitch controller and gets stuck at a given angle.  All you have to do is set the start-time of the fault (`TipManS`), the final pitch where the blade will be stuck at (`BlPitchF`) and the rate at which the pitch angle will move to `BlPitchF` after initiation of the fault (`PitManRat`).  You can set the override pitch maneuver for any or all blades independently.

Best regards,

**Comment by shipors** [comment]
> Dear @Wangzhenyu12,
> 
> To simulate a fixed blade-pitch angle offset error, you have a few options:
> 
> - You can define the pitch offset by adding a fixed offset to the aerodynamic and structural twist in the AeroDyn blade input files  and the ElastoDyn (or BeamDyn) blade input files (using different files for each blade), respectively;
> - if active pitch control is disabled, you can define the offset via the fixed pitch angles set in ElastoDyn (through inputs `BlPitch`(1-3)); or
> - If active pitch control is enabled, you can define the pitch offset directly within the controller.
> 
> Best regards,

Hi,

excuse me,BITwist Parameters in aerodynamics of the blade model , StrcTwst parameters in structural dynamics blade models .
Do you mean  these two parameters?
The former with 19 nodes and the latter with 49 nodes,if all the nodes on the blade of these two parameters are increased by a certain angle (e.g. 3deg), will the final simulation result show that the pitch angle of blade 1 is greater than that of the other two blades?

best wishes,

**Comment by jjonkman** [comment]
Dear @shipors,

Yes, I was referring to the `BlTwist` for the aerodynamic twist in AeorDyn and `StrcTwst` for the structural twist in ElastoDyn.

The blade-pitch angle does not account for twist, so, changing the aerodynamic and structural twist will not directly impact the blade-pitch angle measurement, although it may impact how the pitch control reacts, which would indirectly impact the blade-pitch angles.  Blade-pitch is defined in OpenFAST such that the orientation of the local chordline from the rotor plane is the blade pitch angle plus the local twist angle.

Best regards,

**Comment by xiaolan0195** [comment]
> [@xiaolan0195](https://github.com/xiaolan0195) 一年了，原始文件找不到了。我记得就让 VSContrl = 1，然后把下面的 SIMPLE VARIABLE-SPEED TORQUE CONTROL 的四个数改掉。取值在《Definition of a 5MW Reference Wind Turbine for Offshore System Development》的7.2节里有给。
 I conducted research on two wind farms equipped with wind turbines. The upstream wind turbine is subjected to pitch control, and the pitch angle value is specified to evaluate the impact on downstream wind turbines and the overall wind farm. When the pitch is fixed at 2 ° below the rated wind speed, the output is normal according to the parameter settings of this method. However, when I tried to fix the upstream fan at 4 ° at a wind speed of 12m/s, under the same settings, the power output curve displayed does not conform to theory and will exceed the rated power. How to solve this problem when facing wind speeds above the rated speed?

<img width="2932" height="1202" alt="Image" src="https://github.com/user-attachments/assets/d7418f0e-3d03-48a7-9bd7-d12b17ecfd1e" />

<img width="1912" height="1464" alt="Image" src="https://github.com/user-attachments/assets/72d65aa1-2e5e-42d3-9207-bc7bba2f35f5" />

<img width="1117" height="991" alt="Image" src="https://github.com/user-attachments/assets/1cf596bb-977d-4945-9faa-a6e568d69ca7" />

Best！

**Comment by jjonkman** [comment]
Dear @xiaolan0195,

I'm not sure I fully understand your question, but I'm not surprised that disabling pitch control will result in power that exceeds rated when the wind speed exceeds rated, given that above rated, pitch control is used to regulate rotor speed and power.

Best regards,
