### ISSUE TITLE
Simulate the problems of a 15MW semi-submersible wind turbine with Fastfarm

### ISSUE THREAD

**Issue by 3sdb** [OpenFAST/openfast#2221]
Dear everyone
The following error message is displayed：
This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

FAST.Farm-v3.5.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 2021
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: May 17 2023
 - Time: 13:43:33
Execution Info:
 - Date: 05/16/2024
 - Time: 15:41:54+0800

 Heading of the FAST.Farm input file:
   FAST.Farm input file, using two turbines separated by 3D downstream and an offset of 30m,
   turbulent inflow, yaw maneuver for WT1
Running AWAE.
Running InflowWind.

   Reading a 101x39 grid (600 m wide, 2 m to 298 m above ground) with a characteristic wind speed
   of 12 m/s. This full-field file was generated by TurbSim (from OpenFAST-v3.4.1) on 16-May-2024
   at 13:38:15.

   Processed 20000 time steps of 20-Hz grid-field data (period of 1000 seconds).
Running WakeDynamics.
Running FASTWrapper.
Running OpenFAST.
OpenFAST input file heading:
    IEA 15 MW offshore reference model on UMaine VolturnUS-S semi-submersible floating platform

Running ElastoDyn.
Running AeroDyn.
Running InflowWind.
Running HydroDyn.
  WARNING:  The requested output channel is invalid: WavesF1xi
  WARNING:  The requested output channel is invalid: WavesF1zi
  WARNING:  The requested output channel is invalid: WavesM1yi
  WARNING:  The requested output channel is invalid: WavesF2xi
  WARNING:  The requested output channel is invalid: WavesF2zi
  WARNING:  The requested output channel is invalid: WavesM2yi
  WARNING:  The requested output channel is invalid: WavesF2xi
  WARNING:  The requested output channel is invalid: WavesF2yi
  WARNING:  The requested output channel is invalid: WavesF2zi
  WARNING:  The requested output channel is invalid: WavesM2xi
  WARNING:  The requested output channel is invalid: WavesM2yi
  WARNING:  The requested output channel is invalid: WavesM2zi
 Generating incident wave kinematics and current time history.
 Adjusting incident wave kinematics for turbine offset from array origin.
 Calculating second order difference frequency wave kinematics.
 Calculating second order sum frequency wave kinematics.
 Reading in WAMIT output with root name ".\HydroData/IEA-15-240-RWT-UMaineSemi".
 Computing radiation impulse response functions and wave diffraction forces.
 Calculating second order difference-frequency force using the full quadratic transfer function.
Running MoorDyn (v2.0.0, 2022-12-08).
   This is MoorDyn v2, with significant input file changes from v1.
   Copyright: (C) 2022 National Renewable Energy Laboratory, (C) 2019 Matt Hall
   Parsing MoorDyn input file: .\IEA-15-240-RWT-UMaineSemi_MoorDyn.dat
Warning: invalid output specifier FX.  Must start with L, C, R, or B
Warning: invalid output specifier FY.  Must start with L, C, R, or B
Warning: invalid output specifier FZ.  Must start with L, C, R, or B
   Created mooring system:  3 lines, 6 points, 0 rods, 0 bodies.
   Finalizing initial conditions using dynamic relaxation.
   t=60  FairTen 1: 2.43287E+06, 2.44526E+06, 2.43537E+06
   Fairlead tensions did not converge within TMaxIC=60 seconds.
   MoorDyn initialization completed.
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows).
Using legacy Bladed DLL interface.

FAST_InitializeAll:HydroDyn_Init:HydroDynInput_ProcessInitData: A requested output channel is
invalid

Running OpenFAST.
OpenFAST input file heading:
    IEA 15 MW offshore reference model on UMaine VolturnUS-S semi-submersible floating platform

Running ElastoDyn.
Running AeroDyn.
Running InflowWind.
Running HydroDyn.
  WARNING:  The requested output channel is invalid: WavesF1xi
  WARNING:  The requested output channel is invalid: WavesF1zi
  WARNING:  The requested output channel is invalid: WavesM1yi
  WARNING:  The requested output channel is invalid: WavesF2xi
  WARNING:  The requested output channel is invalid: WavesF2zi
  WARNING:  The requested output channel is invalid: WavesM2yi
  WARNING:  The requested output channel is invalid: WavesF2xi
  WARNING:  The requested output channel is invalid: WavesF2yi
  WARNING:  The requested output channel is invalid: WavesF2zi
  WARNING:  The requested output channel is invalid: WavesM2xi
  WARNING:  The requested output channel is invalid: WavesM2yi
  WARNING:  The requested output channel is invalid: WavesM2zi
 Generating incident wave kinematics and current time history.
 Adjusting incident wave kinematics for turbine offset from array origin.
 Calculating second order difference frequency wave kinematics.
 Calculating second order sum frequency wave kinematics.
 Reading in WAMIT output with root name ".\HydroData/IEA-15-240-RWT-UMaineSemi".
 Computing radiation impulse response functions and wave diffraction forces.
 Calculating second order difference-frequency force using the full quadratic transfer function.
Running MoorDyn (v2.0.0, 2022-12-08).
   This is MoorDyn v2, with significant input file changes from v1.
   Copyright: (C) 2022 National Renewable Energy Laboratory, (C) 2019 Matt Hall
   Parsing MoorDyn input file: .\IEA-15-240-RWT-UMaineSemi_MoorDyn2.dat
Warning: invalid output specifier FX.  Must start with L, C, R, or B
Warning: invalid output specifier FY.  Must start with L, C, R, or B
Warning: invalid output specifier FZ.  Must start with L, C, R, or B
   Created mooring system:  3 lines, 6 points, 0 rods, 0 bodies.
   Finalizing initial conditions using dynamic relaxation.
   t=60  FairTen 1: 2.43287E+06, 2.44526E+06, 2.43537E+06
   Fairlead tensions did not converge within TMaxIC=60 seconds.
   MoorDyn initialization completed.
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows).
Using legacy Bladed DLL interface.

FAST_InitializeAll:HydroDyn_Init:HydroDynInput_ProcessInitData: A requested output channel is
invalid

Farm_Initialize:Farm_ValidateInput:OutFmt produces a column width of 10 instead of 20 characters.

------------------------------------------------------------------------------
Running ROSCO-v2.8.0
A wind turbine controller framework for public use in the scientific field
Developed in collaboration: National Renewable Energy Laboratory
                            Delft University of Technology, The Netherlands
------------------------------------------------------------------------------
Generator speed:    7.5 RPM, Pitch angle:   0.0 deg, Power:     0.0 kW, Est. wind Speed:  14.5 m/s

------------------------------------------------------------------------------
Running ROSCO-v2.8.0
A wind turbine controller framework for public use in the scientific field
Developed in collaboration: National Renewable Energy Laboratory
                            Delft University of Technology, The Netherlands
------------------------------------------------------------------------------
Generator speed:    7.5 RPM, Pitch angle:   0.0 deg, Power:     0.0 kW, Est. wind Speed:  10.7 m/s

T1:FARM_InitialCO:FWrap_t0:FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SolveOption2
c_Inp2AD_SrvD:InflowWind_CalcOutput:CalculateOutput:IfW_FlowField_GetVelAcc:Grid4DField_GetVel:Out
side the grid bounds.
InflowWind_CalcOutput:InflowWind_GetSpatialAverage:CalculateOutput:IfW_FlowField_GetVelAcc:Grid4DF
ield_GetVel:Outside the grid bounds.
T2:FARM_InitialCO:FWrap_t0:FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SolveOption2
c_Inp2AD_SrvD:InflowWind_CalcOutput:CalculateOutput:IfW_FlowField_GetVelAcc:Grid4DField_GetVel:Out
side the grid bounds.
InflowWind_CalcOutput:InflowWind_GetSpatialAverage:CalculateOutput:IfW_FlowField_GetVelAcc:Grid4DF
ield_GetVel:Outside the grid bounds.

 Aborting FAST.Farm.

FAST.Farm for OpenFAST INPUT FILE -------------------------------------------------
FAST.Farm input file, using two turbines separated by 3D downstream and an offset of 30m, turbulent inflow, yaw maneuver for WT1
--- SIMULATION CONTROL ---
False              Echo               - Echo input data to <RootName>.ech? (flag)
FATAL              AbortLevel         - Error level when simulation should abort (string) {"WARNING", "SEVERE", "FATAL"}
300.0              TMax               - Total run time (s) [>=0.0]
False              UseSC              - Use a super controller? (flag)
2                  Mod_AmbWind        - Ambient wind model (-) (switch) {1: high-fidelity precursor in VTK format, 2: one InflowWind module, 3: multiple instances of InflowWind module}
2                  Mod_WaveField      - Wave field handling (-) (switch) {1: use individual HydroDyn inputs without adjustment, 2: adjust wave phases based on turbine offsets from farm origin}
0                  Mod_SharedMooring  - Shared mooring system model (switch) {0: None, 3=MoorDyn}}
--- SUPER CONTROLLER --- [used only for UseSC=True]
"unused"           SC_FileName        - Name/location of the dynamic library {.dll [Windows] or .so [Linux]} containing the Super Controller algorithms (quoated string)
--- SHARED MOORING SYSTEM --- [used only for Mod_SharedMoor>0]
""                 SharedMoorFile     - Name of file containing shared mooring system input parameters (quoted string) [used only when Mod_SharedMooring > 0]
0.04	           DT_Mooring         - Time step for farm-level mooring coupling with each turbine (s) [used only when Mod_SharedMooring > 0]
--- AMBIENT WIND: PRECURSOR IN VTK FORMAT --- [used only for Mod_AmbWind=1]
1.0                DT_Low-VTK         - Time step for low -resolution wind data input files; will be used as the global FAST.Farm time step (s) [>0.0]
0.1                DT_High-VTK        - Time step for high-resolution wind data input files (s) [>0.0]
"unused"           WindFilePath       - Path name to VTK wind data files from precursor (string)
False              ChkWndFiles        - Check all the ambient wind files for data consistency? (flag)
--- AMBIENT WIND: INFLOWWIND MODULE --- [used only for Mod_AmbWind=2 or 3]
1.0                DT_Low             - Time step for low -resolution wind data interpolation; will be used as the global FAST.Farm time step (s) [>0.0]
0.1                DT_High            - Time step for high-resolution wind data interpolation (s) [>0.0]
150                NX_Low             - Number  of low -resolution spatial nodes in X direction for wind data interpolation (-) [>=2]
40                 NY_Low             - Number  of low -resolution spatial nodes in Y direction for wind data interpolation (-) [>=2]
29               NZ_Low             - Number  of low -resolution spatial nodes in Z direction for wind data interpolation (-) [>=2]
-100               X0_Low             - Origin  of low -resolution spatial nodes in X direction for wind data interpolation (m)
-200             Y0_Low             - Origin  of low -resolution spatial nodes in Y direction for wind data interpolation (m)
5.0                Z0_Low             - Origin  of low -resolution spatial nodes in Z direction for wind data interpolation (m)
5.0                 dX_Low             - Spacing of low -resolution spatial nodes in X direction for wind data interpolation (m) [>0.0]
10.0               dY_Low             - Spacing of low -resolution spatial nodes in Y direction for wind data interpolation (m) [>0.0]
10.0               dZ_Low             - Spacing of low -resolution spatial nodes in Z direction for wind data interpolation (m) [>0.0]
10                 NX_High            - Number  of high-resolution spatial nodes in X direction for wind data interpolation (-) [>=2]
30                 NY_High            - Number  of high-resolution spatial nodes in Y direction for wind data interpolation (-) [>=2]
57                 NZ_High            - Number  of high-resolution spatial nodes in Z direction for wind data interpolation (-) [>=2]
"IEA-15-240-RWT_InflowFile.dat"           InflowFile         - Name of file containing InflowWind module input parameters (quoted string)
--- WIND TURBINES ---
2                  NumTurbines        - Number of wind turbines (-) [>=1]                         [last 6 columns below used only for Mod_AmbWind=2 or 3]
WT_X    WT_Y   WT_Z   WT_FASTInFile                      X0_High  Y0_High  Z0_High  dX_High  dY_High  dZ_High
(m)     (m)    (m)    (string)                             (m)      (m)      (m)      (m)      (m)      (m)
  5.0  0.0    0.0    "IEA-15-240-RWT-UMaineSemi-wt1.fst"   -70     -50.0     10.0      10.0    10.0     5.0
 400.0  0.0    0.0    "IEA-15-240-RWT-UMaineSemi-wt2.fst"  370     -50.0     10.0      10.0    10.0     5.0
--- WAKE DYNAMICS ---
2                  Mod_Wake           - Switch between wake formulations {1:Polar, 2:Curl, 3:Cartesian} (-) (switch)
5.0                dr                 - Radial increment of radial finite-difference grid (m) [>0.0]
80                 NumRadii           - Number of radii in the radial finite-difference grid (-) [>=2]
60                 NumPlanes          - Number of wake planes (-) [>=2]
0.02               f_c                - Cutoff (corner) frequency of the low-pass time-filter for the wake advection, deflection, and meandering model [recommended=1.28*U0/R] (Hz) [>0.0]
DEFAULT            C_HWkDfl_O         - Calibrated parameter in the correction for wake deflection defining the horizontal offset at the rotor                                               (m    ) or DEFAULT [DEFAULT= 0.0  ]
DEFAULT            C_HWkDfl_OY        - Calibrated parameter in the correction for wake deflection defining the horizontal offset at the rotor scaled with                         yaw error (m/deg) or DEFAULT [DEFAULT= 0.0 if Mod_Wake is 2, 0.3 otherwise]
DEFAULT            C_HWkDfl_x         - Calibrated parameter in the correction for wake deflection defining the horizontal offset              scaled with downstream distance               (-    ) or DEFAULT [DEFAULT= 0.0  ]
DEFAULT            C_HWkDfl_xY        - Calibrated parameter in the correction for wake deflection defining the horizontal offset              scaled with downstream distance and yaw error (1/deg) or DEFAULT [DEFAULT= 0.0 if Mod_Wake is 2, -0.004 otherwise]
DEFAULT            C_NearWake         - Calibrated parameter for the near-wake correction (-) [>1.0 and <2.5] or DEFAULT [DEFAULT=1.8]
DEFAULT            k_vAmb             - Calibrated parameter for the influence of ambient turbulence in the eddy viscosity (-) [>=0.0] or DEFAULT [DEFAULT=0.05 ]
DEFAULT            k_vShr             - Calibrated parameter for the influence of the shear layer    in the eddy viscosity (-) [>=0.0] or DEFAULT [DEFAULT=0.016]
DEFAULT            C_vAmb_DMin        - Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the transitional diameter fraction between the minimum and exponential regions (-) [>=0.0          ] or DEFAULT [DEFAULT= 0.0 ]
DEFAULT            C_vAmb_DMax        - Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the transitional diameter fraction between the exponential and maximum regions (-) [> C_vAmb_DMin  ] or DEFAULT [DEFAULT= 1.0 ]
DEFAULT            C_vAmb_FMin        - Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the value in the minimum region                                                (-) [>=0.0 and <=1.0] or DEFAULT [DEFAULT= 1.0 ]
DEFAULT            C_vAmb_Exp         - Calibrated parameter in the eddy viscosity filter function for ambient turbulence defining the exponent in the exponential region                                         (-) [> 0.0          ] or DEFAULT [DEFAULT= 0.01]
DEFAULT            C_vShr_DMin        - Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the transitional diameter fraction between the minimum and exponential regions (-) [>=0.0          ] or DEFAULT [DEFAULT= 3.0 ]
DEFAULT            C_vShr_DMax        - Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the transitional diameter fraction between the exponential and maximum regions (-) [> C_vShr_DMin  ] or DEFAULT [DEFAULT=25.0 ]
DEFAULT            C_vShr_FMin        - Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the value in the minimum region                                                (-) [>=0.0 and <=1.0] or DEFAULT [DEFAULT= 0.2 ]
DEFAULT            C_vShr_Exp         - Calibrated parameter in the eddy viscosity filter function for the shear layer    defining the exponent in the exponential region                                         (-) [> 0.0          ] or DEFAULT [DEFAULT= 0.1 ]
DEFAULT            Mod_WakeDiam       - Wake diameter calculation model (-) (switch) {1: rotor diameter, 2: velocity based, 3: mass-flux based, 4: momentum-flux based} or DEFAULT [DEFAULT=1]
DEFAULT            C_WakeDiam         - Calibrated parameter for wake diameter calculation (-) [>0.0 and <0.99] or DEFAULT [DEFAULT=0.95] [unused for Mod_WakeDiam=1]
DEFAULT            Mod_Meander        - Spatial filter model for wake meandering (-) (switch) {1: uniform, 2: truncated jinc, 3: windowed jinc} or DEFAULT [DEFAULT=3]
DEFAULT            C_Meander          - Calibrated parameter for wake meandering (-) [>=1.0] or DEFAULT [DEFAULT=1.9]
--- CURLED-WAKE PARAMETERS [only used if Mod_Wake=2 or 3] ---
DEFAULT            Swirl              - Switch to include swirl velocities in wake (-) (switch) [DEFAULT=TRUE]
DEFAULT            k_VortexDecay      - Vortex decay constant for curl (-) [DEFAULT=0]
DEFAULT            NumVortices        - The number of vortices in the curled wake model (-) [DEFAULT=100]
DEFAULT            sigma_D            - The width of the vortices in the curled wake model non-dimesionalized by rotor diameter (-) [DEFAULT=0.2]
DEFAULT            FilterInit         - Switch to filter the initial wake plane deficit and select the number of grid points for the filter {0: no filter, 1: filter of size 1} or DEFAULT [DEFAULT=1] (switch)
DEFAULT            k_vCurl            - Calibrated parameter for scaling the eddy viscosity in the curled-wake model (-) [>=0] or DEFAULT [DEFAULT=2.0 ]
DEFAULT            Mod_Projection     - Switch to select how the wake plane velocity is projected in AWAE {1: keep all components, 2: project against plane normal} or DEFAULT [DEFAULT=1: if Mod_Wake is 1 or 3, or DEFAULT=2: if Mod_Wake is 2] (switch)
--- VISUALIZATION ---
False              WrDisWind          - Write low- and high-resolution disturbed wind data to <RootName>.Low.Dis.t<n>.vtk etc.? (flag)
0                  NOutDisWindXY      - Number of XY planes for output of disturbed wind data across the low-resolution domain to <RootName>.Low.DisXY<n_out>.t<n>.vtk (-) [0 to 99]
150.0               OutDisWindZ        - Z coordinates of XY planes for output of disturbed wind data across the low-resolution domain (m) [1 to NOutDisWindXY] [unused for NOutDisWindXY=0]
0                  NOutDisWindYZ      - Number of YZ planes for output of disturbed wind data across the low-resolution domain to <RootName>/Low.DisYZ<n_out>.t<n>.vtk (-) [0 to 99]
315.0, 441         OutDisWindX        - X coordinates of YZ planes for output of disturbed wind data across the low-resolution domain (m) [1 to NOutDisWindYZ] [unused for NOutDisWindYZ=0]
0                  NOutDisWindXZ      - Number of XZ planes for output of disturbed wind data across the low-resolution domain to <RootName>/Low.DisXZ<n_out>.t<n>.vtk (-) [0 to 99]
0.0                OutDisWindY        - Y coordinates of XZ planes for output of disturbed wind data across the low-resolution domain (m) [1 to NOutDisWindXZ] [unused for NOutDisWindXZ=0]
2.0                WrDisDT            - Time step for disturbed wind visualization output (s) [>0.0] or DEFAULT [DEFAULT=DT_Low or DT_Low-VTK] [unused for WrDisWind=False and NOutDisWindXY=NOutDisWindYZ=NOutDisWindXZ=0]
--- OUTPUT ---
False              SumPrint           - Print summary data to <RootName>.sum? (flag)
99999.9            ChkptTime          - Amount of time between creating checkpoint files for potential restart (s) [>0.0]
0.0                TStart             - Time to begin tabular output (s) [>=0.0]
1                  OutFileFmt         - Format for tabular (time-marching) output file (switch) {1: text file [<RootName>.out], 2: binary file [<RootName>.outb], 3: both}
True               TabDelim           - Use tab delimiters in text tabular output file? (flag) {uses spaces if False}
"ES10.3E2"         OutFmt             - Format used for text tabular output, excluding the time channel.  Resulting field should be 10 characters. (quoted string)
DEFAULT            OutAllPlanes       - Output all wake planes at all time steps. [DEFAULT=False]
7                  NOutRadii          - Number of radial nodes         for wake output for an individual rotor (-) [0 to 20]
0, 2, 5, 11, 17, 21, 39  OutRadii     - List of radial nodes         for wake output for an individual rotor (-) [1 to NOutRadii] [unused for NOutRadii=0]
1                  NOutDist           - Number of downstream distances for wake output for an individual rotor (-) [0 to 9 ]
63.0               OutDist            - List of downstream distances for wake output for an individual rotor (m) [1 to NOutDist ] [unused for NOutDist =0]
0                  NWindVel           - Number of points for wind output (-) [0 to 9]
0.0                WindVelX           - List of coordinates in the X direction for wind output (m) [1 to NWindVel] [unused for NWindVel=0]
0.0                WindVelY           - List of coordinates in the Y direction for wind output (m) [1 to NWindVel] [unused for NWindVel=0]
150.0               WindVelZ           - List of coordinates in the Z direction for wind output (m) [1 to NWindVel] [unused for NWindVel=0]
                   OutList            - The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels (quoted string)

InflowWind v3.01.* INPUT FILE -------------------------------------------------------------------------
IEA 15 MW Offshore Reference Turbine
---------------------------------------------------------------------------------------------------------------
False                  Echo        - Echo input data to <RootName>.ech (flag)
3                   WindType    - switch for wind file type (1=steady; 2=uniform; 3=binary TurbSim FF; 4=binary Bladed-style FF; 5=HAWC format; 6=User defined; 7=native Bladed FF)
0.0                    PropagationDir - Direction of wind propagation (meteoroligical rotation from aligned with X (positive rotates towards -Y) -- degrees)
0.0                    VFlowAng    - Upflow angle (degrees) (not used for native Bladed format WindType=7)
False                  VelInterpCubic - Use cubic interpolation for velocity in time (false=linear, true=cubic) [Used with WindType=2,3,4,5,7]
1                      NWindVel    - Number of points to output the wind velocity    (0 to 9)
0.0                    WindVxiList - List of coordinates in the inertial X direction (m)
0.0                    WindVyiList - List of coordinates in the inertial Y direction (m)
150.0                  WindVziList - List of coordinates in the inertial Z direction (m)
================== Parameters for Steady Wind Conditions [used only for WindType = 1] =========================
10.0                   HWindSpeed  - Horizontal windspeed                            (m/s)
150.0                  RefHt       - Reference height for horizontal wind speed      (m)
0.12                   PLexp       - Power law exponent                              (-)
================== Parameters for Uniform wind file   [used only for WindType = 2] ============================
"none"                 Filename_Uni - Filename of time series data for uniform wind field.      (-)
150.0                  RefHt_Uni   - Reference height for horizontal wind speed                (m)
240.0                  RefLength   - Reference length for linear horizontal and vertical sheer (-)
================== Parameters for Binary TurbSim Full-Field files   [used only for WindType = 3] ==============
"13C.bts"                 FileName_BTS - Name of the Full field wind file to use (.bts)
================== Parameters for Binary Bladed-style Full-Field files   [used only for WindType = 4] =========
"none"                 FilenameRoot - Rootname of the full-field wind file to use (.wnd, .sum)
False                  TowerFile   - Have tower file (.twr) (flag)
================== Parameters for HAWC-format binary files  [Only used with WindType = 5] =====================
"none"                 FileName_u  - name of the file containing the u-component fluctuating wind (.bin)
"none"                 FileName_v  - name of the file containing the v-component fluctuating wind (.bin)
"none"                 FileName_w  - name of the file containing the w-component fluctuating wind (.bin)
64                     nx          - number of grids in the x direction (in the 3 files above) (-)
32                     ny          - number of grids in the y direction (in the 3 files above) (-)
32                     nz          - number of grids in the z direction (in the 3 files above) (-)
16.0                   dx          - distance (in meters) between points in the x direction    (m)
3.0                    dy          - distance (in meters) between points in the y direction    (m)
3.0                    dz          - distance (in meters) between points in the z direction    (m)
150.0                  RefHt_Hawc  - reference height; the height (in meters) of the vertical center of the grid (m)
-------------   Scaling parameters for turbulence   ---------------------------------------------------------
2                      ScaleMethod - Turbulence scaling method   [0 = none, 1 = direct scaling, 2 = calculate scaling factor based on a desired standard deviation]
1.0                    SFx         - Turbulence scaling factor for the x direction (-)   [ScaleMethod=1]
1.0                    SFy         - Turbulence scaling factor for the y direction (-)   [ScaleMethod=1]
1.0                    SFz         - Turbulence scaling factor for the z direction (-)   [ScaleMethod=1]
1.2                    SigmaFx     - Turbulence standard deviation to calculate scaling from in x direction (m/s)    [ScaleMethod=2]
0.8                    SigmaFy     - Turbulence standard deviation to calculate scaling from in y direction (m/s)    [ScaleMethod=2]
0.2                    SigmaFz     - Turbulence standard deviation to calculate scaling from in z direction (m/s)    [ScaleMethod=2]
-------------   Mean wind profile parameters (added to HAWC-format files)   ---------------------------------
10.0                   URef        - Mean u-component wind speed at the reference height (m/s)
2                      WindProfile - Wind profile type (0=constant;1=logarithmic,2=power law)
0.2                    PLExp_Hawc  - Power law exponent (-) (used for PL wind profile type only)
0.03                   Z0          - Surface roughness length (m) (used for LG wind profile type only)
0                      XOffset     - Initial offset in +x direction (shift of wind box) (-)
================== LIDAR Parameters ===========================================================================
0                      SensorType          - Switch for lidar configuration (0 = None, 1 = Single Point Beam(s), 2 = Continuous, 3 = Pulsed)
0                      NumPulseGate        - Number of lidar measurement gates (used when SensorType = 3)
30                     PulseSpacing        - Distance between range gates (m) (used when SensorType = 3)
0                      NumBeam             - Number of lidar measurement beams (0-5)(used when SensorType = 1)
-200                   FocalDistanceX      - Focal distance co-ordinates of the lidar beam in the x direction (relative to hub height) (only first coordinate used for SensorType 2 and 3) (m)
0                      FocalDistanceY      - Focal distance co-ordinates of the lidar beam in the y direction (relative to hub height) (only first coordinate used for SensorType 2 and 3) (m)
0                      FocalDistanceZ      - Focal distance co-ordinates of the lidar beam in the z direction (relative to hub height) (only first coordinate used for SensorType 2 and 3) (m)
0.0 0.0 0.0            RotorApexOffsetPos  - Offset of the lidar from hub height (m)
17                     URefLid             - Reference average wind speed for the lidar[m/s]
0.25                   MeasurementInterval - Time between each measurement [s]
False                  LidRadialVel        - TRUE => return radial component, FALSE => return 'x' direction estimate
1                      ConsiderHubMotion   - Flag whether to consider the hub motion's impact on Lidar measurements
====================== OUTPUT ==================================================
False                  SumPrint    - Print summary data to <RootName>.IfW.sum (flag)
OutList      - The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels, (-)
Wind1VelX
Wind1VelY
Wind1VelZ
END of input file (the word "END" must appear in the first 3 columns of this last OutList line)

TurbSim v2.* Input File------------------------
Example file that can be used with simulations for the NREL 5MW Baseline Turbine; note that UsableTime has been decreased in this file so that the file distributed with the FAST CertTest isn't as large
---------Runtime Options-----------------------------------
False         Echo            - Echo input data to <RootName>.ech (flag)
    789012    RandSeed1       - First random seed  (-2147483648 to 2147483647)
"RanLux"      RandSeed2       - Second random seed (-2147483648 to 2147483647) for intrinsic pRNG, or an alternative pRNG: "RanLux" or "RNSNLW"
False         WrBHHTP         - Output hub-height turbulence parameters in binary form?  (Generates RootName.bin)
False         WrFHHTP         - Output hub-height turbulence parameters in formatted form?  (Generates RootName.dat)
False         WrADHH          - Output hub-height time-series data in AeroDyn form?  (Generates RootName.hh)
True          WrADFF          - Output full-field time-series data in TurbSim/AeroDyn form? (Generates RootName.bts)
False         WrBLFF          - Output full-field time-series data in BLADED/AeroDyn form?  (Generates RootName.wnd)
True          WrADTWR         - Output tower time-series data? (Generates RootName.twr)
False         WrHAWCFF        - Output full-field time-series data in HAWC form?  (Generates RootName-u.bin, RootName-v.bin, RootName-w.bin, RootName.hawc)
False         WrFMTFF         - Output full-field time-series data in formatted (readable) form?  (Generates RootName.u, RootName.v, RootName.w)
False         WrACT           - Output coherent turbulence time steps in AeroDyn form? (Generates RootName.cts)
          0   ScaleIEC        - Scale IEC turbulence models to exact target standard deviation? [0=no additional scaling; 1=use hub scale uniformly; 2=use individual scales]

--------Turbine/Model Specifications-----------------------
        39   NumGrid_Z       - Vertical grid-point matrix dimension
         101   NumGrid_Y       - Horizontal grid-point matrix dimension
       0.05   TimeStep        - Time step [seconds]
       1000   AnalysisTime    - Length of analysis time series [seconds] (program will add time if necessary: AnalysisTime = MAX(AnalysisTime, UsableTime+GridWidth/MeanHHWS) )
       "ALL"   UsableTime      - Usable length of output time series [seconds] (program will add GridWidth/MeanHHWS seconds unless UsableTime is "ALL")
        150   HubHt           - Hub height [m] (should be > 0.5*GridHeight)
        296   GridHeight      - Grid height [m]
        600   GridWidth       - Grid width [m] (should be >= 2*(RotorRadius+ShaftLength))
          0   VFlowAng        - Vertical mean flow (uptilt) angle [degrees]
          0   HFlowAng        - Horizontal mean flow (skew) angle [degrees]

--------Meteorological Boundary Conditions-------------------
"IECKAI"      TurbModel       - Turbulence model ("IECKAI","IECVKM","GP_LLJ","NWTCUP","SMOOTH","WF_UPW","WF_07D","WF_14D","TIDAL","API","USRINP","TIMESR", or "NONE")
"TurbSim_User.spectra"    UserFile        - Name of the file that contains inputs for user-defined spectra or time series inputs (used only for "USRINP" and "TIMESR" models)
"1-ed3"       IECstandard     - Number of IEC 61400-x standard (x=1,2, or 3 with optional 61400-1 edition number (i.e. "1-Ed2") )
"C"           IECturbc        - IEC turbulence characteristic ("A", "B", "C" or the turbulence intensity in percent) ("KHTEST" option with NWTCUP model, not used for other models)
"NTM"         IEC_WindType    - IEC turbulence type ("NTM"=normal, "xETM"=extreme turbulence, "xEWM1"=extreme 1-year wind, "xEWM50"=extreme 50-year wind, where x=wind turbine class 1, 2, or 3)
"default"     ETMc            - IEC Extreme Turbulence Model "c" parameter [m/s]
"PL"          WindProfileType - Velocity profile type ("LOG";"PL"=power law;"JET";"H2L"=Log law for TIDAL model;"API";"USR";"TS";"IEC"=PL on rotor disk, LOG elsewhere; or "default")
"TurbSim_User.profiles"    ProfileFile     - Name of the file that contains input profiles for WindProfileType="USR" and/or TurbModel="USRVKM" [-]
        150   RefHt           - Height of the reference velocity (URef) [m]
          12   URef            - Mean (total) velocity at the reference height [m/s] (or "default" for JET velocity profile) [must be 1-hr mean for API model; otherwise is the mean over AnalysisTime seconds]
"default"     ZJetMax         - Jet height [m] (used only for JET velocity profile, valid 70-490 m)
0.14          PLExp           - Power law exponent [-] (or "default")
"default"     Z0              - Surface roughness length [m] (or "default")

--------Non-IEC Meteorological Boundary Conditions------------
"default"     Latitude        - Site latitude [degrees] (or "default")
       0.05   RICH_NO         - Gradient Richardson number [-]
"default"     UStar           - Friction or shear velocity [m/s] (or "default")
"default"     ZI              - Mixing layer depth [m] (or "default")
"default"     PC_UW           - Hub mean u'w' Reynolds stress [m^2/s^2] (or "default" or "none")
"default"     PC_UV           - Hub mean u'v' Reynolds stress [m^2/s^2] (or "default" or "none")
"default"     PC_VW           - Hub mean v'w' Reynolds stress [m^2/s^2] (or "default" or "none")

--------Spatial Coherence Parameters----------------------------
"default"     SCMod1          - u-component coherence model ("GENERAL","IEC","API","NONE", or "default")
"default"     SCMod2          - v-component coherence model ("GENERAL","IEC","NONE", or "default")
"default"     SCMod3          - w-component coherence model ("GENERAL","IEC","NONE", or "default")
"default"     InCDec1         - u-component coherence parameters for general or IEC models [-, m^-1] (e.g. "10.0  0.3e-3" in quotes) (or "default")
"default"     InCDec2         - v-component coherence parameters for general or IEC models [-, m^-1] (e.g. "10.0  0.3e-3" in quotes) (or "default")
"default"     InCDec3         - w-component coherence parameters for general or IEC models [-, m^-1] (e.g. "10.0  0.3e-3" in quotes) (or "default")
"default"     CohExp          - Coherence exponent for general model [-] (or "default")

--------Coherent Turbulence Scaling Parameters-------------------
"M:\coh_events\eventdata"    CTEventPath     - Name of the path where event data files are located
"Random"      CTEventFile     - Type of event files ("LES", "DNS", or "RANDOM")
true          Randomize       - Randomize the disturbance scale and locations? (true/false)
          1   DistScl         - Disturbance scale [-] (ratio of event dataset height to rotor disk). (Ignored when Randomize = true.)
        0.5   CTLy            - Fractional location of tower centerline from right [-] (looking downwind) to left side of the dataset. (Ignored when Randomize = true.)
        0.5   CTLz            - Fractional location of hub height from the bottom of the dataset. [-] (Ignored when Randomize = true.)
         30   CTStartTime     - Minimum start time for coherent structures in RootName.cts [seconds]

**Comment by jjonkman** [comment]
Dear @3sdb,

It doesn't look like your FAST.Farm model is set up properly.   All aerodynamic nodes of each OpenFAST model must remain in the bounds of their respective high-resolution domain for the entire simulation.  There may be others, but one obvious error I see is that you've set `Y0_High` = -50, but the IEA Wind 15-MW reference wind turbine blades are much longer than 50 m.

We generally recommend using the OpenFAST toolbox (https://github.com/OpenFAST/openfast_toolbox/tree/main/openfast_toolbox/fastfarm) when generating inflow and setting up FAST.Farm input files to ensure that you are following the FAST.Farm modeling guidance: https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html.

Best regards,
