### ISSUE TITLE
Low CPU Usage!

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#2222]
Hi ,everyone!

My FAST-FARM often stays at a low CPU usage when running in parallel, and then it doesn't update its progress for a long time unless I hit enter many times on the command line, has anyone else experienced something similar?

PS:
my CPU: Intel Core i9-13900
my computer memory：64GB
my GPU: RTX 4090

Best wishes!

**Comment by shipors** [comment]
![image](https://github.com/OpenFAST/openfast/assets/56157328/d96ed56e-9def-4eae-8b1a-af440422e130)
I simulate a farm with 50 turbines for 140s, it costs 4.8178 hours, meanwhile , I run the program in parallel!

**Comment by jjonkman** [comment]
Dear @shipors,

Can you share the full message written to the command prompt when you run FAST.Farm?  I want to see what it says about OpenMP.

You can also find in the source code commented-out sections that make use of calls to `omp_get_wtime()`, which can be used to report information on how each thread is used in the parallelization of FAST.Farm based on compiler directives including `printthreads` and `_OPENMP`.  I would suggest including these sections of code, recompiling FAST.Farm, and rerunning the case to see the thread usage throughout the simulation.

Best regards,

**Comment by shipors** [comment]
![image](https://github.com/OpenFAST/openfast/assets/56157328/2633ceef-1d1d-4981-9ea2-3bc9643bffb2)
@jjonkman

**Comment by jjonkman** [comment]
Thanks.

Now try enabling the `omp_get_wtime()` calls as I described above.

Best regards,

**Comment by shipors** [comment]
dear @jjonkman 

I have made the changes you mentioned and recompiled FF, the command line status at run time I will put in the attachment, please focus on the status at run time up to 132 seconds, it seems to have some problems.

thanks!
[calls.txt](https://github.com/OpenFAST/openfast/files/15374794/calls.txt)

**Comment by jjonkman** [comment]
Dear @shipors,

I'm only seeing part of the story (there are more `omp_get_wtime()` calls you could enable), but from what I do see, most of the time consumed in the simulation seems to come from reading of the ambient wind data into FAST.Farm (which is not parallelized).  What type of ambient wind data are you using (`Mod_AmbWind` = ?) and is the data stored locally or over a network?

Best regards,

**Comment by shipors** [comment]
Dear @jjonkman 

I will enable more calls.

I use steady wind,  WindType=1. There are 50 turbines in my farm, so I set a big field.
 low-resolution spatial: 17,000 meters long, 16,000 meters wide, 250 meters high. Maybe that's why.

Best wishes!
