### ISSUE TITLE
Layer parameters of NREL5MW wind turbine blades

### ISSUE THREAD

**Issue by EVElove444** [OpenFAST/openfast#2227]
Hello, I would like to ask if you have the Layer parameters of the 5MW wind turbine blades. I need to recalculate the parameters of ElastoDyn.Thank you very much.

**Comment by EVElove444** [comment]
Hello, I have checked the 5MW layup information in detail in the forum. Can you send SNL's Brian Resor's report describing the reverse-engineered composite layup of the NREL 5-MW baseline blade to my email address 279521147@qq .com, I would be grateful

**Comment by jjonkman** [comment]
Dear @EVElove444,

I've sent you Brian Resor's report via e-mail.

Best regards,

**Comment by huaxin934** [comment]
Dear Jason,  
        Recently, our team has been using Precomp to simulate  NREL 5MW  wind turbine blades. Would you kindly provide me the basic structural layup to go along with the basic 61.5m blade design defined by NREL’s 5MW reference model for my research work? It will be highly helpful. Could you please send me the file to my email address [panhx25@mail2.sysu.edu.cn].Thank you very much for your help.
@jjonkman

**Comment by jjonkman** [comment]
Dear @huaxin934 ,

I've sent you Brian Resor's report via e-mail.

Best regards,

**Comment by huaxin934** [comment]
Thank you for taking the time to respond despite your busy schedule.

**Comment by huaxin934** [comment]
Dear Jason,
      I would like to consult you on a matter. I aim to simulate damage to the leading edge of the NREL 5MW blade at the 88.13% chord position. I used Precomp to reference the file you sent me for layering the NREL 5MW blade. The damage level was simulated by reducing the thickness of the leading edge layering material, yielding stiffness coefficients for damage levels ranging from 0% to 90%. However, the section stiffness data obtained at 0% damage shows some discrepancy compared to the section stiffness data in the NREL 5MW source file within OpenFAST. Is it reasonable to directly substitute the stiffness coefficients from my simulation into OpenFAST to obtain the bending moment data for the damaged blade? Subsequently, I primarily intend to use this bending moment data to establish a damage identification model for the blade.
    Thank you in advance for your assistance amidst your busy schedule.

**Comment by jjonkman** [comment]
Dear @huaxin934,

Can you clarify the level of discrepancy you are seeing for the case with 0% damage?

Perhaps a workaround would be to identify the change in stiffness associated with the damage as a ratio of the undamaged case and then apply that ratio to the original stiffness?

Best regards,

**Comment by luxiao-666** [comment]
Dear Jason,
Recently, our team has been using Precomp to simulate NREL 5MW wind turbine blades. Would you kindly provide me the basic structural layup to go along with the basic 61.5m blade design defined by NREL’s 5MW reference model for my research work? It will be highly helpful. Could you please send me the file to my email address[3059798423@qq.com].Thank you very much for your help.

**Comment by jjonkman** [comment]
Dear @luxiao-666  ,

I've sent you Brian Resor's report via e-mail.

Best regards,

**Comment by Ch-scorpio** [comment]
Dear Jason,
I am also working on the NREL 5-MW wind turbine blade for my graduate research. Could you kindly share the basic structural layup to go along with the basic 61.5 m blade design defined by NREL’s 5-MW reference model, if available?
If possible, I would greatly appreciate it if you could send the file to my email: 3573615080@qq.com.
Thank you very much for your help!
@jjonkman

**Comment by EVElove444** [comment]
What data do you need about NREL5MW blades? Design aerodynamic data?

**Comment by Ch-scorpio** [comment]
@EVElove444 
I am mainly looking for the composite layup report of the NREL 5-MW baseline wind turbine blade reverse-engineered by Brian Resor of SNL, as mentioned in the forum discussion.
This report would be very helpful for my graduate research on the structural and dynamic analysis of the NREL 5-MW blade.
Thank you very much for your help!

**Comment by EVElove444** [comment]
Already sent to you via email

**Comment by Ch-scorpio** [comment]
@EVElove444 Thank you very much! I have received the report. I really appreciate your help.
