### ISSUE TITLE
OpenFast - ServoDyn drivers for Linux

### ISSUE THREAD

**Issue by lucunnin** [OpenFAST/openfast#224]
Hi,

I have recently compiled openfast for my linux system. I am looking to run Test Case 24 and so need the OC3Hywind Discon Driver. I cannot seem to find this file amongst those that have compiled. I also compiled the r-test suite which appears to contain the .dll files but not the .so files. Is it necessary to compile this independently of the rest? Do any cmake or make files exist for this purpose?

Thanks and kind regards,
Luke Cunningham

**Comment by rafmudaf** [comment]
Hi @lucunnin ,

The ".dll" suffix is simply for compatibility with the regression test input files. On linux, that library is actually a shared object, but its renamed after it is compiled. You can see this step in the [CMake config](https://github.com/OpenFAST/r-test/blob/master/glue-codes/openfast/5MW_Baseline/ServoData/DISCON/CMakeLists.txt#L48) for the DISCON libraries. Without this, we would have to maintain a set of input files for each system.

The controllers are included as targets in the cmake configuration. You can verify this by running "make help" and looking for "DISCON_OC3Hywind". If those don't show up, verify that the BUILD_TESTING cmake flag is on and that the contents of "openfast/reg_tests/r-test" exist (in other words, that the r-test git submodule is initialized and updated). If that looks ok, you should compile and install these drivers with the "make install" command. See the OpenFAST [regression test documentation](https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#ctest-configuration) for more details.

**Comment by kala-j-prasad** [comment]
Dear @jjonkman  Jonkman,

I am running the OpenFAST 5 MW OC4 semi-submersible on Linux (RHEL 9, GCC 11.5.0). The simulation fails in AeroDyn with a LAPACK DGELS error:


  Running ElastoDyn.
  Running InflowWind.
  Running SeaState.
   WaveTMax is less then the simulation time.  Wave data will repeat every WaveTMax seconds.
  Generating incident wave kinematics and current time history.
  Running AeroDyn.
 [INFO] Using the input file input `BEM_Mod` to match BEM coordinate system outputs
 ** On entry to DGELS parameter number  6 had an illegal value
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO IEEE_UNDERFLOW_FLAG IEEE_DENORMAL


All other modules (ElastoDyn, InflowWind, SeaState) initialize successfully
The error occurs during AeroDyn initialization, before time stepping
Linux GCC 11.5.0, OpenFAST compiled from source
Even with Wake_Mod=0 (no BEMT), DGELS is called and fails
The simulation runs successfully on Windows with identical input files, suggesting a Linux compilation or numerical stability issue.

**Comment by andrew-platt** [comment]
Dear @kala-j-prasad,

Which version of OpenFAST are you compiling?  What `cmake` options did you use during compile, and which `LAPACK` library are you using?

**Comment by kala-j-prasad** [comment]
Thankyou Andrew for the response.
I have resolved it
