### ISSUE TITLE
Can Moordyn be used to simulate taut mooring or semi-taut mooring systems?

### ISSUE THREAD

**Issue by WANGSUYU0809** [OpenFAST/openfast#2244]
Hellow,

Can Moordyn be used to simulate taut mooring or semi-taut mooring system, or is it only capable of simulating catenary mooring? Thank you.

Best Regards,
Suyu Wang

**Comment by RyanDavies19** [comment]
Hi @WANGSUYU0809,

MoorDyn can be used for taut and semi-taut systems as well as simulating dynamic power cables. Users can provide line stiffness, non-linear line stiffness, internal damping, bending stiffness, and more. Check out the documentation here for more information on it's capabilities: https://moordyn.readthedocs.io/en/latest/index.html
