### ISSUE TITLE
 Question regarding compilation of DISCON (.so) files

### ISSUE THREAD

**Issue by lucunnin** [OpenFAST/openfast#225]
Hi all,

I have compiled OpenFAST on a Linux system and am slightly confused about the variation of the use of the DISCON controller files compared to FAST v8. With FAST V8, these files were compiled as part of the compilation of FAST and easily available. With OpenFAST, I cannot seem to find the files. In particular, I need the HywindOC3 shared library. The tests cannot run without the files in place, as specified in the ServoDyn.dat file. Are there any instructions for the compilation of these shared libraries? Or are they even needed in OpenFAST? Thank you in advance for your help, and my apologies if I am missing something obvious.

Kind regards,
Luke Cunningham

**Comment by rafmudaf** [comment]
Hi @lucunnin ,

I've posted this comment on issue #224 and added it here as well for future reference.

The ".dll" suffix is simply for compatibility with the regression test input files. On linux, that library is actually a shared object, but its renamed after it is compiled. You can see this step in the CMake config for the DISCON libraries. Without this, we would have to maintain a set of input files for each system.

The controllers are included as targets in the cmake configuration. You can verify this by running "make help" and looking for "DISCON_OC3Hywind". If those don't show up, verify that the BUILD_TESTING cmake flag is on and that the contents of "openfast/reg_tests/r-test" exist (in other words, that the r-test git submodule is initialized and updated). If that looks ok, you should compile and install these drivers with the "make install" command. See the OpenFAST regression test documentation for more details.
