### ISSUE TITLE
Cable control

### ISSUE THREAD

**Issue by WS991106** [OpenFAST/openfast#2251]
Dear @jjonkman ，

Where can I find the relevant documents on cable control?

**Comment by jjonkman** [comment]
Dear @WS991106,

Identifying cables with active control in the SubDyn substructure is documented here: https://openfast.readthedocs.io/en/main/source/user/subdyn/input_files.html#cable-properties.

Identifying tendons with active control in the MoorDyn stationkeeping system is documented here: https://moordyn.readthedocs.io/en/latest/inputs.html#control-moordyn-f-only.

Active control should be implemented in a Bladed-style DLL controller enabled through ServoDyn, such as ROSCO: https://github.com/NREL/ROSCO.  But as far as I know, ROSCO does not provide built-in cable control options; rather, you should implement your own cable control logic.  Arguments related to cable control passed to/from the Bladed-style DLL controller are available through the extended Bladed interface, documented here: https://openfast.readthedocs.io/en/main/source/user/servodyn/ExtendedBladedInterface.html.

Best regards,

**Comment by WS991106** [comment]
Dear @jjonkman ，

Thank you for your answer, I would also like to ask if it is possible to realize an active mooring with a cable control？

Best regards，

**Comment by jjonkman** [comment]
Dear @WS991106,

Yes.  You can use the cable control functionality of OpenFAST to actively control the length of tendons or mooring lines in MoorDyn.

Best regards,

**Comment by WS991106** [comment]
Dear @jjonkman ，

Thank you for your answer. I would like to know where I can download the latest MoorDyn
.data file, because the file I downloaded inside https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast does not have a control channel!
![1717496102080](https://github.com/OpenFAST/openfast/assets/143490138/267f9f3e-d501-4839-9403-bad09e87b142)

**Comment by jjonkman** [comment]
Dear @WS991106,

I don't believe we have an r-test that tests active cable control.  The cable control section of the MoorDyn input file does not need to be in the input file if it is not used.  Simply add the CONTROL section after the LINES section within your MoorDyn input file.

Best regards,

**Comment by WS991106** [comment]
Dear @jjonkman ，

I added the CONTROL section after the LINES section within my MoorDyn input file,but still an error, seems to be not allowed to add an extra column of content.
![1717497118894](https://github.com/OpenFAST/openfast/assets/143490138/3454eb5b-96e7-4125-bd96-dbd9eeed1917)

Best regards,

**Comment by jjonkman** [comment]
You can't add columns as you've done.  As far as I know, the CONTROL section should be a new section added below the LINES section.  See the documentation I referenced earlier: https://moordyn.readthedocs.io/en/latest/inputs.html#control-moordyn-f-only.

**Comment by WS991106** [comment]
Dear @jjonkman ，



> Dear @WS991106,
> 
> Identifying cables with active control in the SubDyn substructure is documented here: https://openfast.readthedocs.io/en/main/source/user/subdyn/input_files.html#cable-properties.
> 
> Identifying tendons with active control in the MoorDyn stationkeeping system is documented here: https://moordyn.readthedocs.io/en/latest/inputs.html#control-moordyn-f-only.
> 
> Active control should be implemented in a Bladed-style DLL controller enabled through ServoDyn, such as ROSCO: https://github.com/NREL/ROSCO. But as far as I know, ROSCO does not provide built-in cable control options; rather, you should implement your own cable control logic. Arguments related to cable control passed to/from the Bladed-style DLL controller are available through the extended Bladed interface, documented here: https://openfast.readthedocs.io/en/main/source/user/servodyn/ExtendedBladedInterface.html.
> 
> Best regards,

Thank you for your answer, you said above that active control requires the use of Bladed, I would like to ask if it is possible to use Simulink for active control, because the CCmode 4 of Cable control is possible to use Simulink.

**Comment by andrew-platt** [comment]
Dear @WS991106,

It is possible to use cable controls in `ServoDyn` through the _Simulink_ interface.  The example _Simulink_ cases provide placeholders for where the cable controls would be used -- it is up to you to program the _Simulink_ model to pass the correct signals for cable control.

In the fixed inputs to the _OpenFAST_ library, cable controls are at indices 12-31 for `DeltaL` and 32-51 for `DeltaLDot` (see the bottom of `modules/openfast-library/src/FAST_Library.h` for index information).  In the _Simulink_ exampe for the OpenLoop, the placeholders for the cable controls are shown as follows:
<img width="571" alt="Screenshot 2024-06-10 at 2 06 58 PM" src="https://github.com/OpenFAST/openfast/assets/2745453/fc2df3f8-5a89-4bfa-8dd9-ab3e29d86986"> (these are arrays of zeros in the example case).

Regards,

**Comment by WS991106** [comment]
Dear @andrew-platt ，

Ok, I understand, thank you very much for your answer!
