### ISSUE TITLE
Generator model and Drive train model

### ISSUE THREAD

**Issue by Tomedssa** [OpenFAST/openfast#2257]
Dear @jjonkman
There is a line of code in the ServoDyn.dat of OpenFast:
2   GenModel     - Generator model {1: simple, 2: Thevenin, 3: user-defined from routine UserGen} (switch) [used only when VSContrl=0]
This selects the generator model to be used.But I wonder where I can see the generator model building process in OpenFast.
For drive train model model, if I use one-lumped mass model (no gearbox), then how should I calculate the equivalent rotational inertia of the generator？ In other words, how is the generator and rotor rotational inertia calculated in OpenFast？
Thanks.

**Comment by jjonkman** [comment]
Dear @Tomedssa,

I'm not sure I fully understand your question.  Regardless, the generator inertia (`GenIner`) is an input to ElastoDyn, and represents the rotational inertia of the generator, expressed relative to the high-speed shaft.  The rotor inertia (`RotIner`) is computed internally within ElastoDyn by integrating the distributed blade mass along the blade to calculate the blade inertia about the low-speed shaft and summing across blades and with the hub inertia (`HubIner`).  The total rotational inertia of the drivetrain is `RotIner` + `GenIner` * `GBRatio`^2, so, `HubIner` should include the rotational inertia of the low-speed shaft and part of the gearbox and `GenIner` should include the rotational inertia of high-speed shaft and part of the gearbox such that this summation of total drivetrain inertia is correct.  If you have a one-mass drivetrain model without a gearbox (with `DrTrDOF` = FALSE and `GBRatio` = 1) and are not interested in computing torque loads within the drivetrain, then it doesn't really matter how you distribute the inertia between `HubIner` and `GenIner` as long as the total drivetrain inertia is correct.

Best regards,

**Comment by Tomedssa** [comment]
Dear @jjonkman,
I want to build a 5MW wind turbine model of a direct-drive permanent magnet synchronous generator. Because it is direct-drive, it does not need a gearbox. But for drive train model in this model, I need to know the generator inertia and the rotor inertia used to calculate the equivalent moment of inertia of the generator. As shown in the formula in the picture.
![QQ截图20240610210452](https://github.com/OpenFAST/openfast/assets/149127552/e208114a-d41c-4e38-b413-6dd902b6b160)
where Jg and Jw are the generator and the rotor rotationalinertias respectively, ng is the gear ratio, which is equal to I, because no gearbox is utilized.
In ElastoDyn, I found two parameters, HubIner and GenIner. But I haven't found the parameter RotIner, can you tell me where I can find the value of this parameter?
Thanks.

**Comment by jjonkman** [comment]
Dear @Tomedssa,

`RotIner` is not an input to OpenFAST.  Rather, if you are using ElastoDyn to model the blade structural dynamics, `RotIner` is computed internally within ElastoDyn by integrating the distributed blade mass along the blade to calculate the blade inertia about the low-speed shaft and summing across blades and with `HubIner`.  The value of `RotIner` calculated by ElastoDyn is reported in the ElastoDyn summary (_.ED.sum_) file.

Best regards,

**Comment by Tomedssa** [comment]
Your answer helped me a lot. Thank you very much!

**Comment by Tomedssa** [comment]
Dear @jjonkman,
I have another question, is there a parameter of rotation damping coefficient in OpenFAST?
Thanks.

**Comment by jjonkman** [comment]
Dear @Tomedssa,

The rotational damping of the drivetrain torsional mode is user-specified via `DTTorDmp` in ElastoDyn.  The rotational damping of the rigid-body rotation is accounted for via the generator torque (from ServoDyn) and aerodynamic torque (from AeroDyn), which are rotational-speed dependent.

Best regards,

**Comment by Tomedssa** [comment]
Thank you for your patience in answering my questions.

**Comment by Tomedssa** [comment]
Dear @vicemora,

I'm sorry that I failed to model the generator due to various problems I encountered in the modeling process. The final generator control part is based on NREL's control strategy, which uses a simple proportional integral controller to complete the control of the generator torque and power.

Best regards,
