### ISSUE TITLE
Matlab

### ISSUE THREAD

**Issue by WS991106** [OpenFAST/openfast#2260]
Dear @jjonkman，

Is it possible to implement active mooring control using Cable control in Simulink?

Best regards，

**Comment by andrew-platt** [comment]
Answering this question in #2251

**Comment by WS991106** [comment]
Dear @andrew-platt ，

Does this mean is it necessary to use a Bladed-style DLL controller to implement active moorings, which won't work inside Simulink?

Best regards，

**Comment by WS991106** [comment]
Dear @andrew-platt ，

Thank you for your answer.
