### ISSUE TITLE
Questions related to moordyn

### ISSUE THREAD

**Issue by WANGSUYU0809** [OpenFAST/openfast#2265]
Hello, may I ask if it is possible to force the floating body to follow a prescribed 6-DOF motion time series while using Moordyn to calculate the mooring response based on the motion of the fairlead points? This would be instead of simultaneously solving for the floating body motion response and mooring line tension response under the influence of waves and mooring forces. The objective is to verify Moordyn based on the measured floater motion response and mooring line tension.  Thanks a lot!

Best Regards,
Suyu Wang

**Comment by jjonkman** [comment]
Dear @WANGSUYU0809,

I recommend applying external loads to the platform in ElastoDyn to achieve the desired motion. This topic has been discussed previously, e.g., see: https://github.com/OpenFAST/openfast/issues/617.

Best regards,

**Comment by RyanDavies19** [comment]
@WANGSUYU0809 Jason's linked example above is a nice fully explained way of doing this. I will also add that it is possible do what you ask using the [MoorDyn driver](https://moordyn.readthedocs.io/en/latest/inputs.html#moordyn-f-driver-input-file) with a body object in MoorDyn. An older example of this can be seen in the regression tests, where 3 coupled points are given platform motions: [modules/moordyn/md_5MW_OC4Semi ](https://github.com/OpenFAST/r-test/tree/main/modules/moordyn/md_5MW_OC4Semi)

**Comment by RyanDavies19** [comment]
@WANGSUYU0809 if you are on windows you can run the precompiled windows binaries from the [3.5.3 release](https://github.com/OpenFAST/openfast/releases/tag/v3.5.3). If you are on a different OS, you will need to [compile the driver from source](https://openfast.readthedocs.io/en/main/source/install/index.html#compile-from-source).

Once you have the driver execute the driver and the driver input file from the command line the same way you start an OpenFAST simulation: `moordyn_driver md_driver.inp`

Note that MoorDyn is not picky about the driver input file name/extension as long as its a text file. You may also see `.dvr` used as an extension.

**Comment by WANGSUYU0809** [comment]
Thanks for all your answers!  It solved my question!
