### ISSUE TITLE
Turbsim excecutables and version numbering

### ISSUE THREAD

**Issue by stiansorum** [OpenFAST/openfast#2271]
Hi,

I was wondering if the executables for the updated versions of TurbSim are available from the GitHub repository (or somewhere else)? We are about to launch the latest release of our software SIMA (which includes wind turbines), where TurbSim-type wind files can be used as input. We would, therefore, like to provide a link to your software, but the latest compiled version I could find was on the legacy TurbSim page (v2.0, https://www.nrel.gov/wind/nwtc/turbsim.html)

**Comment by andrew-platt** [comment]
Dear @stiansorum,

I forgot to add the TurbSim to the latest release.  It will be available here in a few hours: https://github.com/OpenFAST/openfast/releases/tag/v3.5.3.

Regards,

**Comment by andrew-platt** [comment]
The latest windows executable is now available in the asset download for version 3.5.3.
