### ISSUE TITLE
Difference between "RtAeroMyg" and "RtAeroMyh"

### ISSUE THREAD

**Issue by winder365** [OpenFAST/openfast#2277]
Dear all,

I am confused about the difference between "RtAeroMyg" and "RtAeroMyg" these days. Even though I have know that these two parameters are defined in the global coordinate and hub coordinate respectively.

There are several specific issues：
1）Can these two parameters can be seen as the tilt moment of the rotor?
2) Does the RtAeroMyg is calculated relative to the origin of the global coordinate,  and whether the  origin of the global coordinate is located at the bottom of the tower, just like the X-Y-Z frame (namely coordinate ①) in the picture?
![image](https://github.com/OpenFAST/openfast/assets/155932750/20a06422-eb32-4c25-893c-3949f3541e97)
3）Does the RtAeroMyh is calculated relative to the center of the bub?

Thank you for your attention.

**Comment by jjonkman** [comment]
Dear @winder365,

Presumably you are asking about the difference between AeroDyn outputs `RtAeroMyg` and `RtAeroMyh`.  A similar question was asked and answered on our forum--see: https://forums.nrel.gov/t/aerodyn-output-channels-coordinate-system/7142.

Best regards,

**Comment by winder365** [comment]
Dear @jjonkman ,

Thank you for your reply. It is more clear now!

Best regards,
