### ISSUE TITLE
Inquiry on System Requirements for Running OpenFASTFeature request

### ISSUE THREAD

**Issue by Myprojectjoy** [OpenFAST/openfast#2291]
Dear OpenFAST Team,

Firstly, I would like to express my sincere gratitude to the entire team for the incredible work on developing OpenFAST and FAST.Farm. 

I am interested in utilizing OpenFAST for my research and would like to know the system requirements needed to run the software efficiently. Could you please provide detailed information on the recommended hardware and software specifications?

Thank you once again for your outstanding contributions to the field. I look forward to your response.

**Comment by jjonkman** [comment]
Dear @Myprojectjoy.

See similar questions asked and answered in the following topics here on GitHub and on our forum:
https://github.com/OpenFAST/openfast/issues/2255
https://forums.nrel.gov/t/hardware-requirements-for-openfast/3961

Best regards,

**Comment by Myprojectjoy** [comment]
Dear [@Jason.Jonkman](https://forums.nrel.gov/u/jason.jonkman)

Thanks a lot for your kind reply. This helps me to understand the system requirements for OpenFast for full fledged simulations and to plan the hardware requirements.

Best regards,
Subhajit
