### ISSUE TITLE
Bug report: Link to minimal example doesn't work

### ISSUE THREAD

**Issue by cortadocodes** [OpenFAST/openfast#2295]
**Bug description**
The link to the github directory mentioned in [this section](https://ebranlard-openfast.readthedocs.io/en/doc/source/working.html#run-your-first-openfast-simulation) doesn't work: https://github.com/OpenFAST/r-test/blob/main/glue-codes/openfast/MinimalExample/

**Comment by andrew-platt** [comment]
Note that the ReadTheDocs you are referring to is on @ebranlard's personal branch.  That set of docs is rendered from his fork which has not been merged in yet.

**Comment by cortadocodes** [comment]
My mistake!

**Comment by cortadocodes** [comment]
My mistake! Thanks
