### ISSUE TITLE
About the usage of https://github.com/OpenFAST/openfast/tree/main/glue-codes/python

### ISSUE THREAD

**Issue by yinghanguan** [OpenFAST/openfast#2304]
I want to build a reinforcement learning environment using the code from https://github.com/nach96/openfast-gym, but I am not clear where in self.inp_array is the pitch angle and the motor torque, and what is the data structure in self.output_values? Is there any documentation for this?

**Comment by jjonkman** [comment]
Dear @yinghanguan,

I'm not familiar with the repository you are referencing, but this sounds like a question better suited for that repository.  I'll close this issue here.

Best regards,
