### ISSUE TITLE
[OLAF] Twist Not Computed in OLAF cases when Polar Projection is used, resulting in wrong Fn, Ft outputs

### ISSUE THREAD

**Issue by ebranlard** [OpenFAST/openfast#2348]
**Bug description**
The output variable `PitchAndTwist` is used to compute `Fn`, `Ft`, `Cn`, `Ct`, and `Theta`.  
It's taken from `thetaBladeNds`, but `thetaBladeNds` is not defined when we use the polar BEM projection. 

Below the following line, we should compute the twist. 
(https://github.com/OpenFAST/openfast/blob/dev/modules/aerodyn/src/AeroDyn.f90#L3570)

I'll submit a pull request shortly. 

**OpenFAST Version**
Current dev

**Comment by andrew-platt** [comment]
Fixed with #2349
