### ISSUE TITLE
building problems on Linux fedora 26

### ISSUE THREAD

**Issue by ShenghaiLiao** [OpenFAST/openfast#235]
I'm having trouble in installing OpenFAST.
i'm using Linux fedroa26 ,with gcc-4.9.3,openmpi-1.8.5,make-3.81,cmake-2.8.12.
I'm trying to usr SOWFA so I make it with "cmake .. -DBUILD_OPENFAST_CPP_API:BOOL=ON"
(I had successfully build OpenFAST with this switch off)
[navy@localhost build]$ cmake ../
-- The CXX compiler identification is GNU 4.9.3
-- The C compiler identification is GNU 4.9.3
-- The Fortran compiler identification is GNU
-- Check for working CXX compiler: /usr/local/gcc-4.9.3/bin/c++
-- Check for working CXX compiler: /usr/local/gcc-4.9.3/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/local/gcc-4.9.3/bin/gcc
-- Check for working C compiler: /usr/local/gcc-4.9.3/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working Fortran compiler: /usr/local/gcc-4.9.3/bin/gfortran
-- Check for working Fortran compiler: /usr/local/gcc-4.9.3/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/gcc-4.9.3/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/gcc-4.9.3/bin/gfortran supports Fortran 90 -- yes
CMake Warning at cmake/OpenfastFortranOptions.cmake:53 (message):
  A version of GNU GFortran greater than 4.6.0 is required but CMake could
  not detect your GFortran version.
Call Stack (most recent call first):
  CMakeLists.txt:45 (set_fast_fortran)

-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Setting system file as: src/SysGnuLinux.f90
-- Found MPI_C: /usr/local/openmpi-1.8.5/lib/libmpi.so  
-- Found MPI_CXX: /usr/local/openmpi-1.8.5/lib/libmpi_cxx.so;/usr/local/openmpi-1.8.5/lib/libmpi.so  
-- Found MPI_Fortran: /usr/local/openmpi-1.8.5/lib/libmpi_usempif08.so;/usr/local/openmpi-1.8.5/lib/libmpi_usempi_ignore_tkr.so;/usr/local/openmpi-1.8.5/lib/libmpi_mpifh.so;/usr/local/openmpi-1.8.5/lib/libmpi.so  
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.7") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found HDF5: /usr/lib64/libhdf5.so;/usr/lib64/libhdf5_hl.so;/usr/lib64/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/usr/lib64/libhdf5_hl.so;/usr/lib64/libhdf5.so  
-- Found YAMLCPP: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/navy/OpenFOAM/openfast-dev/build

errors come out when the next command "make" had done to 99%
P.S.错误=error,警告=warning,‘to_string’不是‘std’的成员=to_string' is not a member of 'std'

Linking Fortran executable openfast
/usr/bin/ld: warning: libgfortran.so.4, needed by /usr/lib64/liblapack.so, may conflict with libgfortran.so.3
[ 99%] Built target openfast
Scanning dependencies of target openfastcpplib
[ 99%] Building CXX object glue-codes/openfast-cpp/CMakeFiles/openfastcpplib.dir/src/OpenFAST.cpp.o
In file included from /home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:20:0,
                 from /home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:1:
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/SC.h:22:16: 警告：non-static data member initializers only available with -std=c++11 or -std=gnu++11
   double d2R = 0.01745329251 ; //Degrees to Radians
                ^
In file included from /home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:1:0:
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:33:23: 警告：non-static data member initializers only available with -std=c++11 or -std=gnu++11
   float nacelle_cd{0.0};
                       ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:34:25: 警告：non-static data member initializers only available with -std=c++11 or -std=gnu++11
   float nacelle_area{0.0};
                         ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:35:24: 警告：non-static data member initializers only available with -std=c++11 or -std=gnu++11
   float air_density{0.0};
                        ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:33:19: 警告：extended initializer lists only available with -std=c++11 or -std=gnu++11
   float nacelle_cd{0.0};
                   ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:33:23: 警告：extended initializer lists only available with -std=c++11 or -std=gnu++11
   float nacelle_cd{0.0};
                       ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:34:21: 警告：extended initializer lists only available with -std=c++11 or -std=gnu++11
   float nacelle_area{0.0};
                     ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:34:25: 警告：extended initializer lists only available with -std=c++11 or -std=gnu++11
   float nacelle_area{0.0};
                         ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:35:20: 警告：extended initializer lists only available with -std=c++11 or -std=gnu++11
   float air_density{0.0};
                    ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.H:35:24: 警告：extended initializer lists only available with -std=c++11 or -std=gnu++11
   float air_density{0.0};
                        ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp: 在成员函数‘void fast::OpenFAST::allocateMemory()’中:
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:722:47: 错误：‘to_string’不是‘std’的成员
       turbineAllocFile.open("turbineAlloc." + std::to_string(worldMPIRank) + ".txt") ;
                                               ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp: 在成员函数‘void fast::OpenFAST::readVelocityData(int)’中:
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:831:49: 错误：‘to_string’不是‘std’的成员
   hid_t velDataFile = H5Fopen(("velDatafile." + std::to_string(worldMPIRank) + ".h5").c_str(), H5F_ACC_RDWR, H5P_DEFAULT);
                                                 ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:845:57: 错误：‘to_string’不是‘std’的成员
     hid_t dset_id = H5Dopen2(velDataFile, ("/turbine" + std::to_string(iTurb)).c_str(), H5P_DEFAULT);
                                                         ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp: 在成员函数‘hid_t fast::OpenFAST::openVelocityDataFile(bool)’中:
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:869:47: 错误：‘to_string’不是‘std’的成员
     velDataFile = H5Fcreate(("velDatafile." + std::to_string(worldMPIRank) + ".h5").c_str(), H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
                                               ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:899:60: 错误：‘to_string’不是‘std’的成员
       hid_t dataSet = H5Dcreate(velDataFile, ("/turbine" + std::to_string(iTurb)).c_str(), H5T_NATIVE_DOUBLE, dataSpace, H5P_DEFAULT, dcpl_id, H5P_DEFAULT);    
                                                            ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:908:45: 错误：‘to_string’不是‘std’的成员
     velDataFile = H5Fopen(("velDatafile." + std::to_string(worldMPIRank) + ".h5").c_str(), H5F_ACC_RDWR, H5P_DEFAULT);
                                             ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp: 在成员函数‘void fast::OpenFAST::backupVelocityDataFile(int, hid_t&)’中:
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:926:43: 错误：‘to_string’不是‘std’的成员
     std::ifstream source("velDatafile." + std::to_string(worldMPIRank) + ".h5", std::ios::binary);
                                           ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:927:41: 错误：‘to_string’不是‘std’的成员
     std::ofstream dest("velDatafile." + std::to_string(worldMPIRank) + ".h5." + std::to_string(curTimeStep) + ".bak", std::ios::binary);
                                         ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:927:81: 错误：‘to_string’不是‘std’的成员
     std::ofstream dest("velDatafile." + std::to_string(worldMPIRank) + ".h5." + std::to_string(curTimeStep) + ".bak", std::ios::binary);
                                                                                 ^
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp: 在成员函数‘void fast::OpenFAST::writeVelocityData(hid_t, int, int, OpFM_InputType_t, OpFM_OutputType_t)’中:
/home/navy/OpenFOAM/openfast-dev/glue-codes/openfast-cpp/src/OpenFAST.cpp:954:50: 错误：‘to_string’不是‘std’的成员
   hid_t dset_id = H5Dopen2(h5File, ("/turbine" + std::to_string(iTurb)).c_str(), H5P_DEFAULT);
                                                  ^
make[2]: *** [glue-codes/openfast-cpp/CMakeFiles/openfastcpplib.dir/src/OpenFAST.cpp.o] 错误 1
make[1]: *** [glue-codes/openfast-cpp/CMakeFiles/openfastcpplib.dir/all] 错误 2
make: *** [all] 错误 2

P.S.错误=error,警告=warning,‘to_string’不是‘std’的成员=to_string' is not a member of 'std',

someone got the same problem?
please help
by the way ,I would be appreciated if anyone tell me his own environment as a reference.such as the versions of gcc gnu make cmake c++ compiler

**Comment by ShenghaiLiao** [comment]
As I know ,"to_string" has already been add to C++11,which has been support by gcc since version 4.8.0
my gcc version was 7.3.1,but when I built openfast with 7.3.1:
gfortran: 编译器内部错误：Killed(程序 f951)
make[2]: *** [modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/build.make:111：modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o] 错误 4
make[1]: *** [CMakeFiles/Makefile2:1412：modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/all] 错误 2
make: *** [Makefile:128：all] 错误 2
=_=  the gfortran collapsed it self.
so I compiled gcc-4.9.3 myself,and came the error above

**Comment by rafmudaf** [comment]
@ShenghaiLiao `=_= the gfortran collapsed it self.` <- thats a new one!

Have you found the issue and/or solution? I have not used Fedora, but I have compiled successfully on recent versions of Ubuntu, Debian, and CentOS. I generally use GCC 7.3 or newer. The default cmake typically work for me. Did you use any custom settings aside from turning on the c++ api?

**Comment by rafmudaf** [comment]
@ShenghaiLiao I'm closing this issue as I haven't heard back from you. However, if you continue to have this problem please comment on here again and I'll reopen the issue.
