### ISSUE TITLE
mach number exceeds 1.0

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#2355]
Dear everyone,

I am conducting a simulation of a set of direct drive wind turbines (without gearbox, rated speed of approximately 10RPM), so I set the Gearbox ratio of a set of non direct drive wind turbines (rated speed of approximately 400RPM) to 1. I want to simulate a direct drive wind turbine using this method (still using the DLL controller of the non direct drive wind turbine), and the following error occurs
![1722494128441](https://github.com/user-attachments/assets/8c4bbbf5-1032-477a-b5c9-307afc533cd1)
Perhaps I should modify the controller?
[error message.txt](https://github.com/user-attachments/files/16451370/error.message.txt)

Best Wishes!

**Comment by jjonkman** [comment]
Dear @shipors,

You could be running into one or more of several issues:

- When dropping `GBRatio` to unity, you have not increased `GenIner` accordingly. resulting in an unrealistically low inertia for the direct-drive turbine
- When dropping `GBRatio` to unity, you have not changed `DTTorSpr` according or have not disabled `DrTrDOF`, resulting in unrealistically high drivetrain stiffness for the direct-drive turbine
- When dropping `GBRatio` to unity, you have not changed the  generator torque set by the controller, resulting in too low of torque for the direct-drive turbine

Best regards,

**Comment by shipors** [comment]
Dear @jjonkman ，

Thank you for your reply.

I noticed that the drivetrain model used by FAST is a two-mass model. （Perhaps my understanding is incorrect?）

Could I change it to a one-mass model by modifying the configuration file?

Best Wishes!

**Comment by jjonkman** [comment]
Dear @shipors,

Disabling the drivetrain degree of freedom (`DrTrDOF` = FALSE) will change the two-mass model into a one-mass model by eliminating the rotational-flexibility with spring-damper DOF.

Best regards,
