### ISSUE TITLE
Last value of WaveDirArr not set

### ISSUE THREAD

**Issue by ebranlard** [OpenFAST/openfast#236]
**Bug description**

The last value of WaveDirArr is not set.  Affects the HydroDyn module

**To Reproduce**

Set `WaveDirMod` to 1 in an HydroDyn file. Print the `InitOut%WaveDirArr` from `Waves.f90` 

**OpenFAST Version**

Present in OpenFAST 2.1, but at least there since HydroDyn v2.01.01.c  (2013)

**References**

See #191

**Comment by ebranlard** [comment]
As mentioned in #191 

The issue is that the last value of WaveDirArr is never set in the loop over WvSpreadFreqPerDir.

The last value of `WaveDirArr` should not be set to zero but set to a random value of WvTheta.

I'll send a pull request to fix this

**Comment by ebranlard** [comment]
This issue can be closed once #237 is merged.

**Comment by rafmudaf** [comment]
closed by pr #237
