### ISSUE TITLE
Mooring system Fault

### ISSUE THREAD

**Issue by dorsamgh** [OpenFAST/openfast#2379]
Hello, I hope you are doing well. 
I want to make a fault in the mooring line system in such a way that the upper part of one of the lines (fairlead) detaches after a certain period of time, 400 seconds into the operation, leaving the wind turbine connected to the seabed with only two lines. I have reviewed previous conversations like [this](https://forums.nrel.gov/t/tendon-failure-in-fast-modeling/934/12), where it was mentioned that to create this fault, the tension of one of the lines in MAP should be set to zero. My question is, if I want this to happen at a specific time, can I still make this change using the MAP source code, or do we need to modify the MoorDyn source code instead? 
Thank you in advance for your response.

**Comment by jjonkman** [comment]
Dear @dorsamgh,

MoorDyn was recently upgraded so that you can trigger the loss of a mooring line through the input file.  See the pull request here for more information: https://github.com/OpenFAST/openfast/pull/2214.  This improvement will be included in the upcoming release of OpenFAST v4.0, so you can either wait for that release (soon), or compile this branch yourself.

Best regards,

**Comment by dorsamgh** [comment]
Dear @jjonkman 
Thank you for your response. I have reviewed this section ([link](https://moordyn.readthedocs.io/en/latest/inputs.html)); however, I am unable to simulate this change and create the failure. The version of the OpenFAST that I'm using is 3.3.0, and I'm performing the simulation on the IEA-15-240-RWT-UMaineSemi. Do I need to make any changes to the source code of OpenFAST itself to enable this feature in the MoorDyn module for the simulation to work? The simulation errors are as follows:
![image](https://github.com/user-attachments/assets/4996bcbe-b085-4e08-a8a0-bcff02e4b04a)
![image](https://github.com/user-attachments/assets/f4b98dc3-df36-418b-b59c-6ca27cf6817e)

**Comment by jjonkman** [comment]
Dear @dorsamgh,

This MoorDyn functionality for mooring line fault is not included in OpenFAST v3.3; it will be first released in OpenFAST v4.0, expected soon.  If you don't want to wait, you can compile the branch of OpenFAST yourself.

Best regards,

**Comment by dorsamgh** [comment]
Dear @jjonkman 
Thank you for your response and kindness.
From what I understand, it is not possible to directly implement this fault in the current version of OpenFAST in the MoorDyn module.
Now, I have two questions:

1. When will OpenFAST version 4.0 be released?
2. If I want to implement this fault myself, do I need to modify the source code related to MoorDyn? (Similar to how I modified the source code related to nacelle yaw faults and compiled a version of OpenFAST with the fault included.)

**Comment by andrew-platt** [comment]
Dear @dorsamgh,

We expect to release OpenFAST v4.0.0 within a few weeks.  There are a couple of pull requests that we are finishing up, then following some QA/QC, we will post the release.  Look for this sometime in September.

**Comment by jjonkman** [comment]
Dear @dorsamgh,

Regarding (2), if you don't want to wait for the release of OpenFAST v4.0, you could merge the changes from the PR mentioned above (https://github.com/OpenFAST/openfast/pull/2214) into the version of OpenFAST you are using now and recompile OpenFAST.

Best regards,

**Comment by dorsamgh** [comment]
Dear @jjonkman ,
Thank you for your constant guidance and kindness. I created the desired fault in Fairlead by modifying the values of tension and tension damping in the Line_GetStateDeriv subroutine.
