### ISSUE TITLE
Map++: log_initialization_information function is always calling write_summary_file()

### ISSUE THREAD

**Issue by sanguinariojoe** [OpenFAST/openfast#2396]
**Bug description**
Look [here](https://github.com/OpenFAST/openfast/blob/dev/modules/map/src/mapinit.c#L2680). If a summary file is specified then `write_summary_file()` is called twice. Otherwise just once.

I am pretty sure line 2684 should be dropped

**OpenFAST Version**
OpenFAST dev branch, commit e204587c4aa9e81f0d47a92c13ab9c7d7cc7aaf5

**System Information (please complete the following information):**
 - OS: Arch Linux
 - Compiler: gcc version 14.2.1 20240805 (GCC)
 - Compiler settings: --target mappplib

**Comment by bjonkman** [comment]
I agree. It looks like the additional line was added in commit c6bc9d18 (in March 2015), which was a merge of a couple of branches in svn.

**Comment by andrew-platt** [comment]
Corrected with #2405.  Thanks @sanguinariojoe for reporting this!
