### ISSUE TITLE
Fluctuation in LSS speed for steady wind 

### ISSUE THREAD

**Issue by PaulKSmith** [OpenFAST/openfast#2398]
Hello,

I am observing the LSS speed fluctuation even at steady wind of 8m/s, which leads to 1P for DTU10MW. Wondering if anyone can help me understand if this is numerical or physical or point me in right direction. 

Regards,

**Comment by jjonkman** [comment]
Dear @PaulKSmith,

Just a few questions in response:

- Is this the output from an OpenFAST model?
- Where did you obtain this model and have you changed it in any way?
- Does your model include imbalances such as structural (e.g., differing blade masses) and/or aerodynamic (e.g., differing blade-pitch angles)?

Best regards,
