### ISSUE TITLE
How to realize data interface between OpenFAST and Matlab/Simulink?

### ISSUE THREAD

**Issue by huang-wei1996** [OpenFAST/openfast#2409]
Hello
I am a beginner for OpenFAST. I want to transfer some output parameters from Elastodyn module in OpenFAST to a Simulink model, as shown in figure. I learned that the guidance on OpenFAST’s data interaction with Simulink mainly includes generator torque control, nacelle yaw control, and pitch control. However, these methods can’t solve my problem. Can you give me some suggestions or guidance？
![图片](https://github.com/user-attachments/assets/bb32e077-b6b2-4b08-98b8-435515edc43b)

**Comment by jjonkman** [comment]
Dear @huang-wei1996,

Can you clarify what type of OpenFAST outputs you want to send to Simulink and what type of inputs you want Simulink to send OpenFAST?

Best regards,

**Comment by huang-wei1996** [comment]
Dear jjonkman

I am sorry. I am not sure what type of data OpenFAST supports. I want to regard the load applied at the tower-top as OpenFAST outputs, and they are sent to Simulink model in the form of time domain signals. Meanwhile, Simulink outputs are fedback to OpenFAST in the form of time domain signals. 

Best regards

**Comment by huang-wei1996** [comment]
Dear jjonkman,

Thanks for your guidence. I will try OpenFAST S-Function to solve my problem. 

Yes, the Simulink outputs should be the top-tower reation displacement, velocity or acceleration or something else, and they should be sent to AeroDyn module or Nacelle dynamic part in OpenFAST.

Best regards.

**Comment by jjonkman** [comment]
Dear @huang-wei1996,

The OpenFAST-Simulink interface is not set up to allow Simulink to output the tower-top motion as an input to OpenFAST.  Rather, OpenFAST will calculate the tower-top motion in response to the applied loads through its internal equations of motion.  Changing that would require (a quite large) source code change.

Again, providing clarification on what you are trying to do would help.

Best regards,

**Comment by huang-wei1996** [comment]
Thank you very much for your advice!

**Comment by Weixingye** [comment]
Dear jjonkman,

I would like to further ask a question, if you don't mind. I am considering adding a damper of my own design to the tower body. Is it possible to use an S-function to output the node displacements, velocities, and accelerations of the wind turbine tower at each time step. Then, based on the motion information, my designed damper would calculate the reaction load and apply it to the tower through an S-function. Can I use an existing S-function for this purpose, or would I need to write one myself to implement this specific functionality? If the latter is the case, could you please provide me with some guidance?

Thank you!

**Comment by Weixingye** [comment]
@jjonkman

**Comment by jjonkman** [comment]
Dear @Weixingye ,

The existing interface between OpenFAST and MATLAB/Simulink does not currently support active control of Structural Controllers (StC) or the ability to prescribe user-defined point loads through Simulink. See the following OpenFAST issues for a related discussion: https://github.com/OpenFAST/openfast/issues/2323 and https://github.com/OpenFAST/openfast/issues/761.

The OpenFAST S-Function can certainly output tower motions (displacement, velocity, acceleration) through the typical ElastoDyn outputs, but one challenge I can potentially see is that if the force you are calculating depends on acceleration, there is an implicit coupling between ElastoDyn and your force, which may not be numerically stable through the Simlulink interface, given that OpenFAST is called through an S-Function that acts as a discrete-time block in Simulink (meaning that the outputs are one time-step delayed relative to the inputs).

Best regards,

**Comment by Weixingye** [comment]
Thank you very much for your reply, I will reconsider my idea.
