### ISSUE TITLE
Does OpenFAST allow negative fine pitch angle?

### ISSUE THREAD

**Issue by GBA217** [OpenFAST/openfast#2411]
Hi,
I'm trying to run a Ramp simulation with negative fine pitch angle (-0.017453300000      ! PC_FinePit) but, the pitch angle doesn't seem to go below zero. I have set minimum physical pitch (PC_MinPit) allowed to -0.34906000000 rad but it doesnt seem to help. Does OpenFAST allow negative fine pitch angle?
![image](https://github.com/user-attachments/assets/f2087e85-e5c8-45fe-a3ed-c4e8e4e9794e)

**Comment by dzalkind** [comment]
Hi, this is probably more of a ROSCO issue.  You may also need to set `PS_Mode` to 0.

**Comment by GBA217** [comment]
Seting PS_Mode to 0 works. Thanks
