### ISSUE TITLE
Lidar module array not fully initialized

### ISSUE THREAD

**Issue by bjonkman** [OpenFAST/openfast#2413]
Is there a reason that the `ParseAry` routine called for  variable `RotorApexOffsetPos` is reading only one element in the array instead of all 3?
https://github.com/OpenFAST/openfast/blob/2246befaacf88a9657deb0606e08b33fc7338a11/modules/inflowwind/src/InflowWind_Subs.f90#L543

https://github.com/OpenFAST/openfast/blob/2246befaacf88a9657deb0606e08b33fc7338a11/modules/inflowwind/src/InflowWind.txt#L71

All elements of the array are used, so it seems like the y- and z- components of this position are uninitialized.
https://github.com/OpenFAST/openfast/blob/2246befaacf88a9657deb0606e08b33fc7338a11/modules/inflowwind/src/Lidar.f90#L371

**Comment by andrew-platt** [comment]
That's a qood question.  I checked the history and it looks like it may have been written that way.

This should be corrected.

**Comment by bjonkman** [comment]
I have a fix in my `f/Envision_updates` branch. I need to update some input files in the r-test so they don't fail with this new requirement, though. 

Just wanted to make sure it wasn't supposed to be an offset in only the X direction. Thanks.

**Comment by andrew-platt** [comment]
Thanks!

I suspect the intent was for all three directions, but probably never got tested for that.

**Comment by andrew-platt** [comment]
Corrected with #2415
