### ISSUE TITLE
FAST.Farm running errors

### ISSUE THREAD

**Issue by Pinkyutdmech** [OpenFAST/openfast#2423]
I am running FAST.FARM for NREL 5MW turbine using the input files in r-test in github. I am creating my FAST.The FARM input file is based on my requirement of 3 turbines in a staggered position separated by 7D. No partial offset is given. I generated 1 turbulent inflow wind file, hence the Mod_Ambwind = 2. I am getting the following error:

T1:FARM_InitialCO:FWrap_t0:FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SolveOption2
c_Inp2AD_SrvD:InflowWind_CalcOutput:CalculateOutput:IfW_FlowField_GetVelAcc:Grid4DField_GetVel:Out
side the grid bounds.
T2:FARM_InitialCO:FWrap_t0:FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SolveOption2
c_Inp2AD_SrvD:InflowWind_CalcOutput:CalculateOutput:IfW_FlowField_GetVelAcc:Grid4DField_GetVel:Out
side the grid bounds.
T3:FARM_InitialCO:FWrap_t0:FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SolveOption2
c_Inp2AD_SrvD:InflowWind_CalcOutput:CalculateOutput:IfW_FlowField_GetVelAcc:Grid4DField_GetVel:Out
side the grid bounds.

I looked at the Modeling Guidance in the FAST.Farm documentation but did not get a clue to resolve it.

Could you help me figure out which parameters to adjust?
Here are my primary FAST. Farm input file and my InflowWind file

FAST.FARM Input file
[FAST.Farm.zip](https://github.com/user-attachments/files/17003686/FAST.Farm.zip)

Inflow wind File
[IW.zip](https://github.com/user-attachments/files/17003696/IW.zip)

**Comment by jjonkman** [comment]
Dear @Pinkyutdmech,

I see that the error is triggered at model initialization (t=0).  Are you perhaps specifying large initial displacements of the turbine in the OpenFAST models?  Can you also share the TurbSim input file you are using?

Best regards,

**Comment by Pinkyutdmech** [comment]
Hi Dr. Jason,

The turbulent wind file is generated for 10m/s with TI 6% and shear exponent 0.12. The TurbSim input file is attached.
[90m_10mps_seed1.zip](https://github.com/user-attachments/files/17018312/90m_10mps_seed1.zip)

**Comment by Pinkyutdmech** [comment]
I just resolved the error. I found the high-resolution domain size, especially Z-axis, is not sufficient large than the NREL 5MW reference wind turbine with a hub height of 90 m and a 126 m rotor diameter. I increase the bounds and FAST.Farm terminated normally.
However, please let me know if the TurbSim input file is correct?

**Comment by jjonkman** [comment]
I'm glad you solved the issue.

I wouldn't say that you are following the FAST.Farm modeling guidance in terms of aligning the discretization of the low- and high-resolution domains in FAST.Farm with the TurbSim domain, but otherwise your TurbSim file looks fine.

Best regards,

**Comment by Pinkyutdmech** [comment]
I have followed the FAST.Farm modeling guidance. However, the NumGrid_Z and NumGrid_Y value I Have taken a bit higher than the calculated value. Secondly, the HubHt for TurbSim is also chosen slightly higher value than calculated value in the documentation. However, the FAST.Farm input file follows the modeling guidance equations. Please specify if I need to do any changes to improve the outputs of FAST.Farm.



 that I have calculated

**Comment by jjonkman** [comment]
I'm not questioning the domain size and `HubHt` you are using in TurbSim.  My concern is that the grid points aren't aligned (because the spatial-temporal discretization is not the same or integer multiples of each other), as such, the TurbSim wind data will be interpolated by FAST.Farm to populate the low- and high-resolution domain, which is not recommended.

**Comment by Pinkyutdmech** [comment]
Hello Dr. Jason
If I have understood correctly, in the FAST.Farm input file which I shared, the temporal discretization DT_High (0.1 s) is an integer multiple of DT_Low (2.2 s). But the spatial discretization DS_High (4.65 m) is not an integer multiple of DS_Low (10 m). I used the value what I obtained from the equations given in the model guidance. 

Do I need to approximate the values of spatial and temporal discretization everytime in such a way that the high resolution spatial or temporal discretization will be either same or integer multiple of low-resolution spatial or temporal discretization. Please clarify.

**Comment by Pinkyutdmech** [comment]
Will this interpolation affect the overall power production?

**Comment by jjonkman** [comment]
Dear @Pinkyutdmech,

The FAST.Farm modeling guidance encourages you to align the discretization of the low- and high-resolution domains in FAST.Farm with the TurbSim descretization to avoid excessive interpolation.  This means that `DT`, `DX`, `DY`, `DZ`, `X0`, `Y0`, and `Z0` of the low- and high-resolution domains in FAST.Farm should be integer multiples of `TimeStep`, DX = Vhub*`TimeStep`, DY = `GridWidth`/(`NumGrid_Y`-1), DZ = `GridHeight`/(`NumGrid_Z`-1) in TurbSim (as well as taking into consideration how the TurbSim grid is centered around `HubHt`).  Not doing so will lead to excessive interpolation, which will smooth out the turbulence a bit.  This would not have too much effect on the means of the turbine response in FAST.Farm, but it will reduce the variations of the turbine response (including power fluctuations and fatigue loads).

Best regards,

**Comment by Pinkyutdmech** [comment]
Thank you so much Dr. Jason for clarification. I understood very well now. 
I have few more questions: 
1. When you mentioned "low- and high-resolution domains in FAST.Farm should be integer multiples of TimeStep", which Time step. Is it DT_Low or DT_High?
2. When I am running for Mod_AmbWind =2, I need to create 1 inflow wind input file using TurbSim. This wind file should have turbine specification matching the TimeStep, NumGrid_Z, NumGrid_Y of high resolution or low-resolution domain?

I am always confused when I create TurbSim input file for ModAmbWind =2. Please clarify.

**Comment by jjonkman** [comment]
Here are my responses:

1. Both `DT_Low` and `DT_High` in FAST.Farm should be integer multiples of `TimeStep` in TurbSim (or more precisely, `DT_High` should equal `TimeStep` and `DT_Low` should be an integer multiple of that).
2. The grid points in both the low- and high-resolution domains in FAST.Farm should be aligned with grid points in TurbSim.

Best regards,

**Comment by Pinkyutdmech** [comment]
Thanks for clarifying Point 1. 

For point 2, still I did not understand.  In the FAST.Farm, the low-res and high-res domain has different values of the grid points, which is derived from the equations in the modeling guidance document. Even the GridHeight and GridWidth are calculated based on these number of grid points and DY, DZ. 
Thus, please tell me in the TurbSim file, which grid-points (NY_Low, NZ_Low or NY_High, NZ_High to be consider for NumGrid
_Y and NumGrid_Z in case of ModAmbWind =2?

I apologize to throw up so many questions. Please excuse me. Thank you for all your patience.

**Comment by jjonkman** [comment]
The grid points in both the low- and high-resolution domains in FAST.Farm should be aligned with grid points in TurbSim, but are both likely a subset of the TurbSim grid points.  That is, the TurbSim domain must fully encompass the low- and high-resolution domains of FAST.Farm, but the low- and high-resolute domains should be subsets of the full set of TurbSim grid points, with the high-resolution domains using grid points that centered around each wind turbine and the low-resolution domain encompassing the full wind farm (but likely using a coarsened set of grid points).

**Comment by Pinkyutdmech** [comment]
Thank you so much for the clarification, Sir. I appreciate you for creating such an invaluable tool and for providing support to all the users who utilize it for wind energy applications.

Best regards
