### ISSUE TITLE
A compile error in Ubuntu about FAST_Prog.c

### ISSUE THREAD

**Issue by smilke** [OpenFAST/openfast#244]
**There are some error when I build FAST executable using FAST_Prog.c but not FAST_Prog.f90**

When I wanted to learn more about FAST, I recompiled FAST under Linux. When I used FAST_Prog.f90 and adopted the default settings, there was no problem. But when I modify CMakeLists.txt and point the compiled object to FAST_Prog.c, the first thing is that the OpenFOAM_Types.h file can't be found automatically during the compilation process. When I manually copy them to the compiled folder, the compilation process still reports an error. I can't solve it myself, I hope to learn more about the compilation aspect.

**To Reproduce**

1. Compile with 'gfortran'
//2. Run '...' case with '...' settings
3. Open '...' output
4. See the error
Cause there are too many errors, so I picked out a few typical mistakes  as below：
`FAST_Prog.c:56:59: warning: passing argument 3 of ‘FAST_OpFM_Restart’ from incompatible pointer type`
`FAST_Library.h:16:23: note: expected ‘int *’ but argument is of type ‘OpFM_InputType_t *`
`FAST_Library.h:16:23: note: expected ‘SC_InputType_t * {aka struct SC_InputType *}’ but argument is of type ‘char *’`
`FAST_Prog.c:134:4: error: too few arguments to function ‘FAST_End’`

**Expected behavior**

I want to know how to use this c language program to make glue code, which involves my control of FAST in the future. In addition, I would like to know more about FAST compilation and programming, because I may need to modify FAST in the future.

**V2.0.0**

Please provide as much detail as possible including git commit. The best information is a screenshot of the OpenFAST system description that prints when running OpenFAST:

```
**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.0.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Nov 27 2018
  - Time: 17:19:38
 Execution Info:
  - Date: 11/29/2018
  - Time: 10:52:28-0700
```

**System Information (please complete the following information):**
 
 - OS: Ubuntu 18
 - Compiler: GFortran 
 - Compiler settings: CMake flags

**Additional context**

**Comment by rafmudaf** [comment]
@smilke What is your compiler version? Also, could you provide more details on the steps you took which led you to this problem? Specifically, please modify the description above expanding on the "To reproduce" section. Something like this but as applicable to your case:
```
Steps to reproduce the behavior:

1. run this command: export FC=/usr/bin/gfortran
2. run this command: "cmake .."
3. Change this line in openfast/CMakeLists.txt:
CMAKE_MATH_LIBRARY=/lib/mkl/libmkl
to 
CMAKE_MATH_LIBRARY=/lib/accelerate/libaccelerate
4. copy OpenFAST.h into /some/directory
5. Errors:
   Cause there are too many errors, so I picked out a few typical mistakes  as below：
   `FAST_Prog.c:56:59: warning: passing argument 3 of ‘FAST_OpFM_Restart’ from incompatible pointer type`
   `FAST_Library.h:16:23: note: expected ‘int *’ but argument is of type ‘OpFM_InputType_t *`
   `FAST_Library.h:16:23: note: expected ‘SC_InputType_t * {aka struct SC_InputType *}’ but argument is of type ‘char *’`
   `FAST_Prog.c:134:4: error: too few arguments to function ‘FAST_End’`
```

**Comment by rafmudaf** [comment]
Without more information, this issue is difficult to work out so I'm closing it. @smilke please comment again here if you're still facing this problem.
