### ISSUE TITLE
SubDyn: Lumped mass issues

### ISSUE THREAD

**Issue by RBergua** [OpenFAST/openfast#2451]
**Bug description**
SubDyn behaves in an unexpected way when accounting for lumped masses.

**To Reproduce**
The unexpected behavior is not fully understood.

We have one model in SubDyn with beams and lumped masses. The model looks as follows:
![image](https://github.com/user-attachments/assets/69274cac-cd21-491e-a06e-b4fe083da90a)

The information about the mass, center of mass and moments of inertia was used to create an equivalent rigid floater in ElastoDyn.
![image](https://github.com/user-attachments/assets/803c321e-9156-487c-9bfc-4233641e2eb3)

The results of these 2 models (ElastoDyn rigid and SubDyn defined as rigid by means of SttcSolve = False and Nmodes = 0) was consistent in time domain for still water conditions:
![image](https://github.com/user-attachments/assets/df15f9fe-a2d7-471d-ab32-282a87cc51bd)

The agreement is very good between models specially considering that the ElastoDyn model includes 1 potential flow body in HydroDyn and the SubDyn model includes 6 potential flow bodies in HydroDyn (discretized system). 

The above SubDyn model used lumped masses with eccentricities. However, it is known that the lumped masses should not include eccentricities in SubDyn (see for reference: https://github.com/OpenFAST/openfast/issues/1710#issue-1826821882).

Accordingly, new joints were created in the SubDyn and linked to existing joints through rigid links. The model studied accounts for 22 lumped masses, so 22 rigid links were used. When doing this, the properties (e.g., mass, center of mass and moments of inertia) of the 2 SubDyn models (lumped mass with eccentricity vs lumped mass with rigid link) were consistent:
![image](https://github.com/user-attachments/assets/d17b30c5-3e25-43b4-9bad-fc93500b587b)

However, when comparing the results in time domain, there was a large difference in the behavior between models:
![image](https://github.com/user-attachments/assets/1530bc1f-10ef-4eec-a1cd-23fb34f16e63)

In order to try to better understand this behavior, the 22 lumped masses with 22 rigid links were removed from the SubDyn model and only 1 lumped mass with 1 rigid link was included. This unique lumped mass is equivalent to the 22 lumped masses in terms of mass, center of mass and moments of inertia. Since the structural model in SubDyn in this case is rigid, the response should be the same:
![image](https://github.com/user-attachments/assets/7bf17af7-10f0-42e8-97c9-cf99e0b7ba03)
 
This indicates that the issue is not related to the number of rigid links used in SubDyn.

So, for some reason that we don't understand, including a lumped mass with a rigid link has a very different behavior than expected.

**OpenFAST Version**
Current OpenFAST dev.

**Comment by andrew-platt** [comment]
@luwang00, is this something you can address?

**Comment by RBergua** [comment]
I have been looking at this problem in detail with @luwang00. Somehow, it seems that these numerical models (i.e., ElastoDyn vs SubDyn models) were tuned in terms of hydrostatics to achieve the same equilibrium condition. However, because lumped masses with eccentricities were used in SubDyn, the changes introduced in hydrostatics were unrealistic. Once the SubDyn with lumped masses attached by rigid links was used, a large difference was observed. This large difference is actually not due to the use of the lumped masses with rigid links (proper approach) but rather tuning the hydrostatics using the SubDyn model with lumped masses that included eccentricities (wrong approach).

**Comment by andrew-platt** [comment]
Closing this as a model setup issue.
