### ISSUE TITLE
Enquiring about coordinate transformation 

### ISSUE THREAD

**Issue by PaulKSmith** [OpenFAST/openfast#2454]
Hello everyone,

I am trying to understand the coordinate system in OpenFAST. So, made an attempt to transform the LSS forces from rotating frame of reference (`LSShftFya`) to fixed frame . Then compare with  `LSShftFys`. For the transformation I am using simple rotational matrix as my simulation does not have any yaw dof and subjected to only steady wind. 

```
      theta = RtSpeed % [rad/s]
      % Rotation matrix for rotation about the x-axis
        R_x = [1, 0, 0;
               0, cos(theta_i), -sin(theta_i);
               0, sin(theta_i), cos(theta_i)];

        % Forces in body-fixed frame at time t(i)
        F_BF = [RotThrust(i); LSShftFya(i); LSShftFza(i)];

        % Transform forces to fixed frame
        F_FF = R_x * F_BF; 
```

However, I am not able to match the calculated forces after transformation with `LSShftFys, LSShftFzs`. I wanted to make sure if LSShftFya,LSShftFza can be transformed this way.

![image](https://github.com/user-attachments/assets/a630a331-46ad-4a86-ab4a-4bfb152c3787)

Appreciate any help!

**Comment by jjonkman** [comment]
Dear @PaulKSmith,

I agree with all of your math except that you are using `RtSpeed` for the angle in rad/s rather than `Azimuth` in radians.

Best regards,

**Comment by PaulKSmith** [comment]
Thanks!
 Somehow misinterpreted. It matches perfectly now.
