### ISSUE TITLE
Morrison's theory and Hydrodyn

### ISSUE THREAD

**Issue by HANloading** [OpenFAST/openfast#2462]
Dear All:
I'm at https://openfast.readthedocs.io/en/main/source/user/hydrodyn/modeling_considerations.html#floating-platforms
Check out
1: There are some modifications that can be made in the hydrodyn input file to make it so that only Morrison's theory is utilised in the calculation of wave loads and not the potential flow theory.
2: But when I make the corresponding changes in the 15MW file, it only results in an unsuccessful run.
So I would like to know if it is possible in openfast to use only Morrison's theory for load calculations for a 15MW turbine and be able to output the loads and motions for the corresponding platform slices?
3: If it is possible to implement #2, can you give an example file? Because I'm looking at https://openfast.readthedocs.io/en/main/source/user/hydrodyn/appendix.html#appendix-a-oc4-semi-submersible-input-file
I only see the file for OC4.
Thanks.

**Comment by jjonkman** [comment]
Dear @HANloading,

Are you referring to the IEA Wind 15-MW RWT atop the VolturnUS semisubmersible?  The OpenFAST model of this turbine provided on the IEA Wind repository uses a potential-flow only model with a rigid floater: https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/master/OpenFAST/IEA-15-240-RWT-UMaineSemi.

I gather you want to change this model to be a strip-theory- (extended Morison-) only model with a structural flexible floater.  This is certainly possible, but I'm not aware of anyone that has developed such a model to share.

Best regards,

**Comment by HANloading** [comment]
Dear @jjonkman 
So, please, is there any introduction to the internal calculations of potential flow theory? I'm trying to figure out what input parameters are related to the potential flow theory, and in addition, is it possible to output and potential flow theory related parameters in openfast? For example, is the potential flow theory related to inputs such as platform acceleration, platform velocity, fluid velocity, etc.?

**Comment by jjonkman** [comment]
Dear @HANloading,

A basic overview of the first-order potential flow solution implemented in HydroDyn is given in chapter 2 of my Ph.D. Thesis-turned NREL report: https://www.nrel.gov/docs/fy08osti/41958.pdf.  There have been many extensions since then, as outlined in a series of papers over the years.  The online HydroDyn documentation on readthedocs also contains a series of implementation plans that outline the theory implemented across improvements made to HydroDyn over the years: https://openfast.readthedocs.io/en/main/source/user/hydrodyn/index.html.  Yes, the hydrodynamic loads associated with the potential-flow solution are dependent on the floating platform displacement, velocity, and acceleration.

In terms of the HydroDyn input file, the "FLOATING PLATFORM", "2ND-ORDER FLOATING PLATFORM FORCES" and "PLATFORM ADDITIONAL STIFFNESS AND DAMPING" sections pertain to the potential-flow solution.

Best regards,

**Comment by HANloading** [comment]
@jjonkman 
I'm sorry, but I'm not sure what parameters PRP Body Kinematics, WAMIT Body Kinematics, WAMIT Body Forces in Hydrodyn in the outlistparameters correspond to in the potential flow theory calculations? In your PhD thesis, you said ‘The two most 
common alternatives are the frequency-domain representation and Morison's representation.’ I would like to know the frequency-domain I would like to know that frequency-domain representation is included in the potential flow theory? In addition, I want to output some values in openfast, I want the values of inputs that are needed when calculating hydrodynamic loads using the potential flow theory. So I am not sure if the parameters in PRP Body Kinematics, WAMIT Body Kinematics, WAMIT Body Forces are some of the data I want?
![image](https://github.com/user-attachments/assets/2cc406dc-984a-4c30-8a73-94c5f8c548eb)
![image](https://github.com/user-attachments/assets/b4ab5a7e-fc68-4d82-b8eb-9584a77524f8)

**Comment by jjonkman** [comment]
Dear @HANloading,

Here are my responses:
-  The potential-flow solution implemented in HydroDyn makes use of the hydrostatic and frequency-dependent radiation and diffraction solutions from a freqeuncy-domain wave-body interaction solver (such as WAMIT) and solves the potential-flow solution in the time-domain based on frequency-to-time-domain transforms.
- The HydroDyn outputs listed under WAMIT Body Kinematics in the HydroDyn `OutList` are the values HydroDyn needs from the structural solver (the displacements, velocities, accelerations of each potential-flow body) for its potential-flow solution. 
- The HydroDyn outputs listed under WAMIT Body Forces in the HydroDyn `OutList` are the values HydroDyn calculates from its potential-flow solution.

Best regards,

**Comment by Javeria503** [comment]
Hello i am also working on diffraction theory using eigen function matching technique. I write matlab code for an article on which i am working wave loads on a floating stationary  bottomless cylindrical structures. But my results have some minor issue and i do not know how to correct it. so can anyone help me in it?

**Comment by jjonkman** [comment]
Dear @Javeria503,

I'm not sure enough about what you are doing to comment.

Best regards,

**Comment by Javeria503** [comment]
@jjonkman                                                                                                                                                                                                            Hello I write a MATLAB code for an article to reproduce their results but my code has some bugs which i could not resolve. I attached the article if you can provide help i will share my code.                                                                                                              Thanks
[bottomless cylinder.pdf](https://github.com/user-attachments/files/17797596/bottomless.cylinder.pdf)

**Comment by jjonkman** [comment]
Dear @Javeria503,

I'm not familiar with the article you share.  Given that your question is unrelated to OpenFAST, I'm not in a position to offer help.

Best regards,

**Comment by Javeria503** [comment]
Okay Thanks, I know it is not related to openFAST what it is related to marine hydrodynamics so i did not find any other platform where i can seek help so that's why i post it here. Thanks for your response.
