### ISSUE TITLE
User-defined Profiles

### ISSUE THREAD

**Issue by sffgd** [OpenFAST/openfast#2466]
Hello，everyone：
I would like to ask about user-defined profiles in turbsim (figure below), there are some doubts as follows：
![微信图片_20241015174948](https://github.com/user-attachments/assets/aa6f56e3-9d25-408a-8e1f-f83789181484)

1.firstly，I would like to know if the default values of StdScale1, StdScale2, and StdScale3 in the table will also work for Typhoon (2008 Typhoon Hagupit)?
2.If it is assumed that the incoming flow from the wind field is directed at the wind turbine, can the wind direction be set to zero?
3.I would like to know the exact calculation of standard deviation and length scale.
If you know some calculations, I'd appreciate it.

best regard！

**Comment by jjonkman** [comment]
Dear @sffgd,

The inputs (`StdScale1`, `StdScale2`, `StdScale3`, Standard deviation, Length scale) in TurbSim's user-defined profile input file are only used when you set `TurbModel` = `USRVKM` to select the von Karman model with user-defined scaling.  This model, including these parameters, are well documented in the TurbSim User's Guide: https://openfast.readthedocs.io/en/main/_downloads/cb14d3e2d3533d76e405d730fea19846/TurbSim_v2.00.pdf.

But I can't say whether this model is appropriate for the specific typhoon you mention.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman,

 Based on your description above，I think I have understood what you mean, Figure A-4. Sample input file for User-Defined Profiles in Turbsim User Guide is for von Karman model, but I set TurbModel=‘USRINP’ and WindProfileType=‘USR’, and got the power spectrum of ‘USRINP’, if I can derive the inputs (StdScale1, 2, 3, Standard deviation, Length scale) from the power spectrum, can I use Figure A-4 instead of the ProfileFile?

Best regards,

**Comment by jjonkman** [comment]
Dear @sffgd,

You can use a user-defined profile file with any turbulence model in TurbSim.  But for other turbulence models besides `USRVKM`, the user-defined profile inputs `StdScale1`, `StdScale2`, `StdScale3`, Standard deviation, and Length scale are ignored.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman,
 
Thank you for your answer, are there any other user-defined wind profile example files for turbulence models other than USRVKM? This would make it easier for me to import into turbsim and use them.

Best regards,

**Comment by jjonkman** [comment]
Dear @sffgd,

The _UsrShear.inp_ example in the TurbSim CertTest makes use of the _UsrShear.profiles_ user-defined profile file while making use of `TurbModel` = `IECKAI`.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman,
 
I found it in Turbsim User's Guide： "The ProfileFile parameter tells TurbSim the name of the input file that contains user-defined profiles for wind speed and direction“, then I set parameter cases 1 and 2, but when generating the wind file I get error 3

case 1:
--------Meteorological Boundary Conditions-------------------
"USRINP"  TurbModel       - Turbulence model ("IECKAI","IECVKM","GP_LLJ","NWTCUP","SMOOTH","WF_UPW","WF_07D","WF_14D","TIDAL","API","USRINP","TIMESR", or "NONE")
"FOS.dat" UserFile        - Name of the file that contains inputs for user-defined spectra or time series inputs (used only for "USRINP" and "TIMESR" models)
"1-Ed3"   IECstandard     - Number of IEC 61400-x standard (x=1,2, or 3 with optional 61400-1 edition number (i.e. "1-Ed2") )
"10.5"    IECturbc        - IEC turbulence characteristic ("A", "B", "C" or the turbulence intensity in percent) ("KHTEST" option with NWTCUP model, not used for other models)
"NTM"     IEC_WindType    - IEC turbulence type ("NTM"=normal, "xETM"=extreme turbulence, "xEWM1"=extreme 1-year wind, "xEWM50"=extreme 50-year wind, where x=wind turbine class 1, 2, or 3)
default   ETMc            - IEC Extreme Turbulence Model "c" parameter [m/s]
"USR"     WindProfileType - Velocity profile type ("LOG";"PL"=power law;"JET";"H2L"=Log law for TIDAL model;"API";"USR";"TS";"IEC"=PL on rotor disk, LOG elsewhere; or "default")
"User-Defined Profiles-FOVS.dat" ProfileFile     - Name of the file that contains input profiles for WindProfileType="USR" and/or TurbModel="USRVKM" [-]
150       RefHt           - Height of the reference velocity (URef) [m]
25.58     URef            - Mean (total) velocity at the reference height [m/s] (or "default" for JET velocity profile) [must be 1-hr mean for API model; otherwise is the mean over AnalysisTime seconds]
default   ZJetMax         - Jet height [m] (used only for JET velocity profile, valid 70-490 m)
default   PLExp           - Power law exponent [-] (or "default")
default   Z0              - Surface roughness length [m] (or "default")
 
case 2:
![图片7](https://github.com/user-attachments/assets/9a69e06d-2146-4c4b-bafa-7baaf3da3be2)

error 3:
![图片6](https://github.com/user-attachments/assets/c8d1db03-fc51-4334-b67a-1ce393f0e30e)

How should I fix this error?

Best regards,

**Comment by jjonkman** [comment]
Dear @sffgd,

It looks like you set `NumUSRz` heights to 30, but have only set 4 rows of height values; could that be the problem?  (Or did you only share part of the file?)

Does TurbSim run without error if you use `TurbModel` = "IECKAI" instead of a "USRINP"?

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman,

yes, I only set 4 rows of height values (share part of the file)
I tried TurbModel=‘IECKAI’/‘IECVKM’/‘USRINP’, with ‘USR’ WindProfileType, and I get an ‘access violation’ error. But when I don't use ‘USR’ WindProfileType, it runs successfully.
So I'm wondering if there is something wrong with the ‘USR’ WindProfileType file format?

additions：‘USR’ WindProfileType as follow：
---------Turbsim v2.00.* Profile Input File------------------------------------
Example file using completely made up profiles 
-------- User-Defined Profiles (Used only with USR wind profile or USRVKM spectral model) -------------
30              NumUSRz        - Number of Heights 
1.490           StdScale1      - u-component scaling factor for the input standard deviation
1.0             StdScale2      - v-component scaling factor for the input standard deviation
0.534           StdScale3      - w-component scaling factor for the input standard deviation
---------------------------------------------------------------------------------------------
Height    Wind Speed       Wind Direction          Standard Deviation    Length Scale
 (m)        (m/s)        (deg,cntr-clockwisre)            (m/s)              (m)
--------------------------------------------------------------------------------------------------------- 
10.0           20.55560            0                      13.94               14.63
20.0           21.89116            0                       9.86               29.26
30.0    	   22.64820            0                       8.05               43.89
40.0           23.18993            0                       6.97               58.51
50.0           23.59091            0                       6.24               73.14
60.0           23.92463            0                       5.69               87.77
70.0           24.23711            0                       5.27              102.40
80.0           24.46805            0                       4.93              117.03
90.0           24.69058            0                       4.65              131.66
100.0          24.90619            0                       4.41              146.28
110.0          25.07672            0                       4.20              160.91
120.0          25.19271            0                       4.02              175.54
130.0          25.33895            0                       3.87              190.17
140.0          25.47313            0                       3.73              204.80
150.0          25.88000            0                       3.60              219.43
160.0          25.67630            0                       3.49              234.05
170.0          25.77895            0                       3.38              248.68
180.0          25.85078            0                       3.29              263.31
190.0          25.92411            0                       3.20              277.94
200.0          25.99701            0                       3.12              292.57
210.0          26.05566            0                       3.04              307.20
220.0          26.14074            0                       2.97              321.82
230.0          26.23415            0                       2.91              336.45
240.0          26.29443            0                       2.85              351.08
250.0          26.34902            0                       2.79              365.71
260.0          26.39187            0                       2.73              380.34
270.0          26.42528            0                       2.68              394.97
280.0          26.46899            0                       2.63              409.59
290.0          26.50180            0                       2.59              424.22
300.0          26.52905            0                       2.55              438.85

Best regards,

**Comment by jjonkman** [comment]
Dear @sffgd,

I wouldn't think this would cause an "access violation" error, but I do see that you've included extra columns of data in your user-defined profile.  There should only be 3 columns of data (Height, Wind Speed, Wind Direction) in your user-defined profile file unless you are using TurbModel = "USRVKM", which you are not.  I would suggest starting with the _UsrShear.profiles_ example and include your 30-rows of data in that file.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman,

After some testing I found that only the grid size causes the change error. When I set NumGrid_Z=NumGrid_Y=31, GridHeight=GridWidth=280m, I get an access violation error, but when I set NumGrid_Z=NumGrid_Y=31, GridHeight=GridWidth=80m it works! But with NumGrid_Z=NumGrid_Y=31 and GridHeight=GridWidth=80m, it will run successfully.
But I need a grid of about 280*280m，Is there a way out of this?

**Comment by jjonkman** [comment]
Dear @sffgd,

Is the vertical extent of your TurbSim domain (determined by TurbSim inputs `HubHt` and `GridHeight`) compatible with the user-defined profile you've specified, which extends from 10 to 300 m?

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman,

Thank you for your reply, after checking this was indeed the problem and it is now running successfully.
In addition, I would like to ask
1. whether openfast can use the wind file generated by matlab (binary ‘.bts’ wind file);
2. whether TimeStep (Time step [seconds]) in Turbsim file must be equal to DT (Integration time step (s)) in openfast's ‘.fst’?
I have noticed that for TimeStep is the sampling time step, it is recommended to take a value in the range of 0.05 s~0.1 s, for DT=1 / (10 * highest natural frequency in Hz of coupling between modules)

 Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman，

I would also like to ask how the yaw angle of the elastodyn module is set (nacyaw - initial or fixed nacelle-yaw angle degrees), e.g. what is the direction of rotation of the wind turbine corresponding to -30° and 30°? Is the yaw angle nacyaw = 30° shown below correct?

![微信图片_20241028220340](https://github.com/user-attachments/assets/21ec8a28-2e5e-44a2-8fce-e68e51cd24d8)

Best regards,

**Comment by jjonkman** [comment]
Dear @sffgd,

Nacelle yaw in ElastoDyn is defined as a positive rotation of the nacelle about the z axis that points upwards, opposite gravity, along the tower centerline.  So, a positive nacelle yaw is counterclockwise when viewed from above.  In your image, you've shown a negative yaw angle.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman，

Thank you for your reply, I have understood!

 Best regards,
