### ISSUE TITLE
Error when using turbulence wind files

### ISSUE THREAD

**Issue by Winxinn** [OpenFAST/openfast#2472]
Hello, everyone!
I'm having some problems with wind farm simulation using openfest:
When I change the wind type to 3 (3=binary TurbSim FF) in the inflowwind file, I get the following error.

![image](https://github.com/user-attachments/assets/f03b8d01-1163-48c3-aad9-8dfa58a22504)

Your help is very much needed and I will be very grateful!

**Comment by jjonkman** [comment]
Dear @news87,

Are you trying to use the LIDAR functionality of InflowWind?  I would only expect that you'd get this error if you are using the LIDAR functionality. 

Regardless, it sounds like your InflowWind input file is not formatted properly.  As with any input file formatting issue, I would enable the `Echo` option in your InflowWind input file to debug issues with input file formatting.

Best regards,

**Comment by news87** [comment]
Dear @jjonkman 

Thank you for your reply. Yes, I am trying to use the lidar module in a turbulent environment, using the inflowwind file which is the original file in the example without any modifications, but it still reports an error, do you have any idea what could be causing this?

Sincere thanks

**Comment by news87** [comment]
Dear@jjonkman,

Thank you very much for your reply, I changed the parameters in Inflowwind and it works successfully. But I have a new question, how can I output the wind speed measured by the lidar module, currently the measurements of wind speed are as follows, or can this represent the wind speed measured by the lidar module?
![image](https://github.com/user-attachments/assets/add49d41-abe9-4615-a6b7-e141a3f5e026)
Thank you again !

**Comment by jjonkman** [comment]
Dear @news87,

If you are using the LIDAR functionality of InflowWind, the LIDAR sensor outputs are available via InflowWind `OutList` parameters `WindMeas1` - `WindMeas5`.  See the _OutListParameters.xlsx_ spreadsheet for more information: https://openfast.readthedocs.io/en/main/_downloads/3f19498a5dc774461e022b671ff01ec6/OutListParameters.xlsx.

Best regards

**Comment by Winxinn** [comment]
Dear @jjonkman，

Thank you very much for your help! I'll give try it.

Best regards.

**Comment by Winxinn** [comment]
Dear @jjonkman

I'm very sorry to bother you again, when I use turbulent winds as input, Rotspeed outputs an increasing trend, and I get the same result using steady state winds（12m/s/).
![image](https://github.com/user-attachments/assets/c5213b39-c0f3-485c-89cc-58522bc4578e)

May I ask what is the cause of this?
