### ISSUE TITLE
How to compile OpenFAST into a dynamic library？

### ISSUE THREAD

**Issue by tclblby** [OpenFAST/openfast#2475]
Hi all,
        I want to learn to use some of the Openfast's module in another fortran program so i want to compile them into  dynamic library. I found some similar issues but i didn't get the answer from them. Could tell me in detail how to strat this?

Kind regards

**Comment by deslaughter** [comment]
To use functions from OpenFAST's modules in a dynamic library, you'll need to export them with a C interface. Some examples would be `HydroDyn_C_Binding.f90`, `AeroDyn_Inflow_C_Binding.f90`, and `IfW_C_Binding.f90`. Once you compile those modules as shared libraries, you can access them from other Fortran programs after loading the shared library. However, it is much simpler to link against the static libraries so you can use the Fortran subroutines directly. This can be done by installing OpenFAST, adding the path to the installation directory to `CMAKE_PREFIX_PATH`, and then adding `find_package(OpenFAST)` to your CMake file. You should then have access to all modules and routines in OpenFAST. `Nalu-Wind` uses this method to call OpenFAST functions, example at https://github.com/Exawind/nalu-wind/blob/e0e9f0f8a5f0fcc771bcc8b4bfe7e46125f3e64e/CMakeLists.txt#L182.

**Comment by tclblby** [comment]
@deslaughter 
Thanks a lot, your reply is really helpful.
