### ISSUE TITLE
FAST_Solution:FAST_AdvanceStates:AD_UpdateStates:SetDisturbedInflow:TwrInfl:Tower strike.

### ISSUE THREAD

**Issue by 250079395** [OpenFAST/openfast#2503]
Dear @jjonkman
    When I attempted to simulate a 15 MW wind turbine using an open-loop model similar to a 5MW wind turbine, the following error occurred: FASD_Solution: FASD_AdvanceStates: AD-UupdateStates: SetDisturbedInflow: TwrInfl: Tower Strike. May I ask what caused it? Looking forward to your reply.

**Comment by jjonkman** [comment]
Dear @250079395,

Presumably when you refer to "open loop" you mean that you disabled the controller and are simulating a condition that would normally require control or at least a given rotor speed and pitch angle to avoid overly excessive thrust.  That is, my guess is your simulation considers a condition that the IEA Wind 15-MW RWT was not designed for.

Best regards,

**Comment by 250079395** [comment]
Dear @jjonkman
  I am very honored to receive your reply. Just now, I conducted a simulation of the Rosco controller for the IEA-15-240-RWT-UmineSemii wind turbine. When I set the steady-state wind speed to 15, it can run, and when I set it to 18, it can also run. However, when I set the steady-state wind speed to 16, runFAST. m encountered the following error: The S-Function 'FASTSFunc' in 'ROSCO/FAST Nonlinear Wind Turbine/S-Function' reported an error: 
FASTA_Solution: FASTAdvanceStates: NaN state detected. (My simulation duration is 3600; PCMode and VSContrl are set to 4). This is bothering me a lot. Do you have any good suggestions? We look forward to your reply.
   Looking forward to your reply.At the same time, I wish you a smooth work.

**Comment by jjonkman** [comment]
Dear @250079395,

I'm not exactly sure what you are doing, considering that you mention OpenLoop, ROSCO, and Simulink.  If you are referring to some Simulink implementation of the ROSCO controller, see a related discussion on our forum: https://forums.nrel.gov/t/cause-of-difference-between-simulation-results-using-libdiscon-dll-and-simulink/7685.

Also, as has been discussed in many topics, if you change the mean hub-height wind speed, make sure that you are also change the initial rotor speed and blade-pitch angles in ElastoDyn (based on their expected (mean) values conditioned on the mean hub-height wind speed) to avoid problems initializing the controller.

Best regards,

**Comment by 250079395** [comment]
Dear @jjonkman
  Thank you for your reply. I did not further study the open-loop situation. As you guessed, I am working on the Simulink implementation of Rosco. You may have misunderstood my previous question. However, thank you for providing me with the discussion address regarding the Rosco issue. I will carefully study the specific content. Sincerely thank you for your response amidst your busy schedule, and wish you a smooth work.
