### ISSUE TITLE
Numerical Instability in SubDyn Module with Retained DOFs for Monopile Offshore Wind Turbine

### ISSUE THREAD

**Issue by ccccsdcc** [OpenFAST/openfast#2512]
Hello everyone,

I'm running a numerical simulation of a monopile-based offshore wind turbine in OpenFAST. In the SubDyn module, I’ve configured the model to retain all degrees of freedom (DOFs) for the foundation by setting CBMod to False. However, I’m encountering numerical instability at the start of the simulation. The only way I’ve found to achieve stability is to significantly reduce the time step, which unfortunately slows down the simulation considerably.

Could anyone help me understand why retaining all DOFs for the foundation in SubDyn leads to this initial instability? Additionally, are there best practices or alternative approaches to stabilize the simulation without having to use such a small time step?

Thank you for your assistance!

![page1](https://github.com/user-attachments/assets/f64d5b8c-15b3-4715-88c9-07de8c807c3b)

**Comment by ccccsdcc** [comment]
Dear @jjonkman ,

Thank you for the detailed explanation!  I understand now the challenges with retaining all finite-element DOFs in SubDyn.

Could you please clarify the theoretical basis for the coupling method currently used in the latest version of OpenFAST to integrate structural modules like BeamDyn, ElastoDyn, and SubDyn? Specifically, I’m interested in understanding the theory or principles behind the time integration and stability management approach in the current version, before the generalized alpha method is introduced in v5.

Thank you again for your insights!

Best regards,

**Comment by jjonkman** [comment]
Dear @ccccsdcc,

There are few documents under "Modularization Framework" and "Glue Code and Mesh Mapping" on readthedocs that describe how the current coupling scheme in the OpenFAST glue code works: https://openfast.readthedocs.io/en/main/source/user/index.html#modularization-framework and https://openfast.readthedocs.io/en/main/source/user/index.html#glue-code-and-mesh-mapping.  A high-level description is also provided in various OpenFAST overview presentations, such as what was presented at our recent OpenFAST workshop held in conjunction with NAWEA / WindTech: https://openfast.readthedocs.io/en/main/source/user/index.html#glue-code-and-mesh-mapping.

As part of the development of tight coupling, we've also drafted a journal article that we intend to submit in conjunction with the release of OpenFAST v5 (which is due out soon (in the next month or two)) that explains the coupling procedure of the original OpenFAST glue code as well as its extension to tight coupling.

Best regards,

**Comment by ccccsdcc** [comment]
Dear @jjonkman ,

Thank you so much for your detailed response and for sharing the references on the coupling scheme in the OpenFAST glue code.  

Best regards,
