### ISSUE TITLE
Nacelle anemometer signal

### ISSUE THREAD

**Issue by TorbenKnudsen** [OpenFAST/openfast#2540]
I am using OpenFAST with NREL5MW to analyze MPC control which also involves Kalman filters. Generally, I like to only use signals which would be available in a real turbine.  For a wind speed measurement I like something similar to a nacelle anemometer.  I have been considering using Wind1VelX but suspect it is a signal directly from turbsim which is not realistic.  I could ad some (white) noise to it.  My questions are:
1. What exactly is Wind1VelX?
2. Can I use it for a nacelle anemometer?
3. Is is there a better option?
4. Is there a signal for this
5. Is there also rotor averages wind speed signal?

**Comment by jjonkman** [comment]
Dear @TorbenKnudsen,

Here are my responses:

1. InflowWind output `Wind1VelX` is the X-component of the undisturbed wind velocity in global coordinates at the 1st coordinate in the list (at X,Y,Z = `WindVxiList`,`WindVyiList`,`WindVziList`).  If you are using TurbSim wind data within InflowWind, I agree that this output will simply extract the wind data from the TurbSim output file (including interpolation, if the coordinate is not at a TurbSim grid point).
2. Using the InflowWind wind outputs could be used to approximate a nacelle anemometer, but you'd certainly miss the influence of the nacelle aerodynamics, rotor wake, and relative motion association with structural dynamics.
3. Certainly the rotor wake and relative motion effects are accounted for in AeroDyn, but the velocity field at specific points in the wake is not tracked by AeroDyn unless you are using the free vortex wake model OLAF, and even then, the nacelle aerodynamics are not considered by AeroDyn.
4. No; see 3.
5. The rotor-disk-averaged relative wind speed is an output from AeroDyn (`RtVAvgxh`,`RtVAvgyh`,`RtVAvgzh`), which includes the contribution of tower influence and structural dynamics, but does not consider the wake effect or nacelle aerodynamics.

Best regards,

**Comment by TorbenKnudsen** [comment]
Dear Jason

Thanks for your response.  I have two clarifying questions.
1. Is it correct understood that global coordinates used for Wind1VelX can be interpreted as earth fixed coordinates?

2. and that the rotor-disk-averaged relative wind speed is in the rotor disc coordinate system or similar but not the earth fixed?

**Comment by jjonkman** [comment]
Dear @TorbenKnudsen,

Regarding (1), the InflowWind outputs (`Wind1VelX`, etc.) are expressed in OpenFAST's global coordinate system, which is earth fixed with X directed along the nominal (zero degree) wind direction, Z directed vertical upward (opposite gravity) and Y directed to the left when looking nominally downwind (along the zero-degree wind direction).

Regarding (2), the rotor-disk-averaged relative wind speed (`RtVAvgxh`) is output from AeroDyn in the hub coordinate system, which moves and rotates with the hub.

Best regards,

**Comment by TorbenKnudsen** [comment]
Dear Jason

Thanks for your response.  I will perhaps have more questions later. For now I wish you a Merry Christmas
