### ISSUE TITLE
AeroDyn_Driver_x64.exe Function

### ISSUE THREAD

**Issue by wkdanqu1** [OpenFAST/openfast#2555]
Hello, Professor, 
Is there a method to achieve co-simulation for real-time interaction between AeroDyn_Driver_x64.exe and other software?

**Comment by jjonkman** [comment]
Dear @wkdanqu1,

The AeroDyn module can be called by other software (such as OpenFAST).  AeroDyn is not typically the computational bottleneck in the aero-elastic solve if your goal is real-time simulation, unless you are using the free-vortex wake OLAF.  Whether real-time simulation is available depends on the capabilities of the calling software.

FYI: The standalone AeroDyn driver is a simple wrapper to call AeroDyn in the absence of other software that would drive the solution.  So, if AeroDyn is called by other software (such as OpenFAST), the standalone AeroDyn driver is not used in that case.

Best regards,

**Comment by wkdanqu1** [comment]
Hello, Professors,

This has been very helpful for me. I will proceed with further real-time simulation development following your method! 
Thank you again for your assistance!
Best regards,
Jesse

**Comment by wkdanqu1** [comment]
Hello  Professors @andrew-platt @jjonkman,

I hope this message find you well !

In the code for calculating Output in the aerodyn_inflow_library.py, it requires motion parameters for the Hub, Nacelle, root, and mesh. The example folder vtkRef also provides parameters stored in .vtp files.
However, my hydrodynamic calculation software can only provide motion parameters for the floating platform! Is there a way to obtain the motion parameters for the Hub, Nacelle, root, and mesh using the floating platform's motion parameters? Or is there a method that only requires the input of the floating platform's motion parameters?

Best regards,
Jesse

**Comment by jjonkman** [comment]
Dear @wkdanqu1,

The mesh-mapping utility of OpenFAST supports disparate meshes, including use of rigid-body kinematics that could be used to map a mesh point in the floater to a mesh point in the nacelle, assuming rigid-body motion between these bodies.  But if the rotor is operational (spinning), the rotor would not be rigidly connected to the nacelle, so, you'd have to model the rotor rotation or assume a given rotational motion if you want to couple your software with AeroDyn.  You could also expand your software to support structural flexibility.  

Best regards,
