### ISSUE TITLE
The issue of yaw control for a single turbine and for a wind farm

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#2570]
Hi everyone!

I am considering using FAST and FARM to conduct yaw testing. I understand that for a single turbine, if you want to set a fixed yaw angle, you only need to change the value in the "NACELLE-YAW CONTROL" section of the SERVODYN.dat file. 

However, this method only allows setting a constant value, meaning the yaw angle will not adjust according to the actual changing wind direction.

If you want to achieve the functionality where the yaw angle changes based on the actual varying wind direction, you would need to develop your own yaw controller, am I right? 

I plan to use a DLL-mode controller, but after reading APPENDIX A Communication Between Bladed And External Controllers in the Bladed User Manual, I found that for yaw control, there isn't an ideal control input for the desired yaw angle (like the Demanded pitch angle), and adjustments to the yaw angle can only be made by controlling the yaw rate or torque. Is this correct?

best wishes!

**Comment by jjonkman** [comment]
Dear @shipors,

Within the ServoDyn input file directly, you can set a fixed yaw angle command or simple yaw maneuver (linear ramp from start to end).  If you want active yaw control to changing wind direction, you must select a user-defined yaw-control option in ServoDyn (`YCMode` = 3, 4, or 5).

Regarding your description of the Bladed-style controller dynamic library interface, I agree.

If you are using the ROSCO dynamic library (https://github.com/NREL/ROSCO) for your wind turbine control (which is in Bladed dynamic library format), you can use the active yaw control logic available in ROSCO by setting `YCMode` = 5 in ServoDyn, plus the yaw-control settings in ROSCO.  You could use ROSCO in place of developing your own control logic.

Best regards,

**Comment by shipors** [comment]
thank you very much for your reply.

**Comment by shipors** [comment]
I am conducting a simple test where I set Elastodyn-NacYaw to -10, Servodyn YCMode to 5, YawNeut to -10, and other yaw parameters as shown in the following figure
I compiled the DLL and set the yaw related content to:
avrSwap[27] = 0;
avrSwap[47] = 1 * 0.017;
But the simulation results are like this, it's obvious that my DLL didn't work. 

![Image](https://github.com/user-attachments/assets/c9fe26af-2f82-4776-8101-b98b28cc32e4)



![Image](https://github.com/user-attachments/assets/7c1e7d10-f0d6-4cd7-965d-7bbccd334839)
In fact, I need to set TYCOn=0, TYawManS=9999， So my DLL can run normally

**Comment by jjonkman** [comment]
Dear @shipors,

I agree that you must set `TYCOn` to when you want to start active yaw control through a DLL (presumably, you'd want `TYCOn` = 0).  As of now, only your override yaw maneuver is engaged.

FYI: the nacelle-yaw rate should be specified through `avrSWAP`(48), not (47).

Best regards,

**Comment by shipors** [comment]
> Dear @shipors,
> 
> I agree that you must set `TYCOn` to when you want to start active yaw control through a DLL (presumably, you'd want `TYCOn` = 0).  As of now, only your override yaw maneuver is engaged.
> 
> FYI: the nacelle-yaw rate should be specified through `avrSWAP`(48), not (47).
> 
> Best regards, 

dear@jjonkman 

Thank you for your attention to my question.That's how it should be set up.

Yaw rate is indeed the 48th data of avrswap, but given that the C/C + + array starts at 0, I set it to 47 of the array, which you call avrswap (48)

Thank you very much.

best wishes!
