### ISSUE TITLE
About OC4 wind turbine

### ISSUE THREAD

**Issue by axxyyyyyyyy378** [OpenFAST/openfast#2576]
Dear @jjonkman ,

I found that in the "5MW_OC4Semi_WSt_WavesWN" case of the current version of OpenFAST, the default wave direction is set to 0° (aligned with the X-axis), and it is not possible to modify the wave direction. This limitation is due to the lack of information about other wave directions in the hydrodynamic parameter file for the OC4 wind turbine (e.g., in .12d format). 

The missing data can be supplemented by performing frequency-domain analyses using software such as WAMIT or AQWA. However, during the calculation process, it is necessary to provide the wind turbine's geometric model (e.g., OC4) along with its density and material properties. While I have some basic geometric parameters, I am still missing more detailed data, such as the mass distribution. 

Could you advise where I might find more detailed public parameters for the OC4 wind turbine?

Thanks very much.

**Comment by jjonkman** [comment]
Dear @axxyyyyyyyy378

I’m not the one who developed these, but the WAMIT input files that NREL used to generate the 2nd-order WAMIT solution for the OC4-DeepCwind semisubmersible are available in my Aug 21, 2018 post in the following topic on our forum: https://forums.nrel.gov/t/hydrodynamic-analysis-of-oc3-hywind-spar-buoy/1103.

Best regards,

**Comment by axxyyyyyyyy378** [comment]
Dear @jjonkman ,

Thank you for your patient response. My issue has been resolved.

Best regards,
