### ISSUE TITLE
GENERATOR AND TORQUE CONTROL and TMD

### ISSUE THREAD

**Issue by hishamtariq19** [OpenFAST/openfast#2585]
I ma trying to study the effectiveness of TMD (optimally tuned) installed on the top of the tower of IEA-15MW-RWT.

I observed significantly different findings when I switch Variable-speed control mode (VSContrl) from 1 to 5.

At wind speed = 5 m/s (DLC 1.2):

For VSContrl = 1; TMD (with 3 % mass ratio) reduces RMS value of tower top displacement in fore-aft direction as compared to uncontrolled OWT (with no TMD)

For VSContrl = 1; TMD (with 3 % mass ratio) does not have any notable effect on the RMS value of tower top displacement in fore-aft direction as compared to uncontrolled OWT (with no TMD)

I am attaching picture of time histories of fluctuating component of tower top displacement in fore-aft direction with two different controller types.

![VSContrl _1](https://github.com/user-attachments/assets/0f70cb42-53f7-4495-870f-954749d81227)
![VSContrl _5](https://github.com/user-attachments/assets/c0546d14-60d7-458d-91ca-0e1d69c2f3c5)

Which of these two Variable-speed control modes is more suitable if I am interested in studying the effect of TMD on tower top motion of IEA-15MW-RWT.

**Comment by jjonkman** [comment]
Dear @hishamtariq19,

Can you clarify what simple variable-speed control settings you are using with `VSContrl` = 1 and what you are doing with pitch control (`PCMode`)?  The OpenFAST model of the IEA Wind 15-MW reference wind turbine is released with `PCMode` = `VSContrl` = 5, whereby the combined pitch + torque control is provided by the reference open-source controller (ROSCO).  By switching to `VSContrl` = 1, you are overriding the torque control from ROSCO, which may adversely effect the pitch controller if you have that enabled.

Comparing your two sets of results, it looks like ROSCO is already providing much more fore-aft damping than `VSContrl` = 1, so, it appears to me that the TMD is less influential when ROSCO is enabled.

Best regards,

**Comment by hishamtariq19** [comment]
Dear @jjonkman,

Thanks for the explanation.

Here are the simple variable-speed control settings (default from IEA-15MW-RWT input files)


---------------------- GENERATOR AND TORQUE CONTROL ----------------------------
5                      VSContrl    - Variable-speed control mode {0: none, 1: simple VS, 3: user-defined from routine UserVSCont, 4: user-defined from Simulink/Labview, 5: user-defined from Bladed-style DLL} (switch)
1                      GenModel    - Generator model {1: simple, 2: Thevenin, 3: user-defined from routine UserGen} (switch) [used only when VSContrl=0]
95.756                 GenEff      - Generator efficiency [ignored by the Thevenin and user-defined generator models] (%)
True                   GenTiStr    - Method to start the generator {T: timed using TimGenOn, F: generator speed using SpdGenOn} (flag)
True                   GenTiStp    - Method to stop the generator {T: timed using TimGenOf, F: when generator power = 0} (flag)
9999.9                 SpdGenOn    - Generator speed to turn on the generator for a startup (HSS speed) (rpm) [used only when GenTiStr=False]
0.0                    TimGenOn    - Time to turn on the generator for a startup (s) [used only when GenTiStr=True]
9999.9                 TimGenOf    - Time to turn off the generator (s) [used only when GenTiStp=True]
---------------------- SIMPLE VARIABLE-SPEED TORQUE CONTROL --------------------
7.559987120819503      VS_RtGnSp   - Rated generator speed for simple variable-speed generator control (HSS side) (rpm) [used only when VSContrl=1]
19624046.66639         VS_RtTq     - Rated generator torque/constant generator torque in Region 3 for simple variable-speed generator control (HSS side) (N-m) [used only when VSContrl=1]
343357.4355671095      VS_Rgn2K    - Generator torque constant in Region 2 for simple variable-speed generator control (HSS side) (N-m/rpm^2) [used only when VSContrl=1]
2.                     VS_SlPc     - Rated generator slip percentage in Region 2 1/2 for simple variable-speed generator control (%) [used only when VSContrl=1]


For Pitch control, I used PCMode =5

Setting VSContrl = 1, while having Pitch control enabled may have affected the pitch controller, as explained by you.

Yes, TMD is less effective suppressing fore-aft motion when ROSCO is enabled, at other wind speeds as well (8,14, 20 m/s).

**Comment by jjonkman** [comment]
Dear @hishamtariq19,

Thanks for clarifying.  I don't think I have anything to add--it appears that ROSCO is providing enough fore-aft damping that the TMD is less influential when ROSCO is enabled.  And I would recommend not mixing `VSContrl` = 1 with `PCMode` = 5 when using ROSCO that combines the pitch and torque control logic within one controller.

Best regards,
