### ISSUE TITLE
Regarding the questions about fastfarm wake simulation

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#2592]
Merry Christmas!

Can I turn off the high-resolution VTK output and maintain only the low-resolution output when focusing on the wake impact relationships between turbines?

I've noticed that after setting up a simulation for a certain period, the wake visuals do not gradually extend to downstream turbines but instead remain at a certain position behind the upstream turbines. What should I do to address this issue?

Is there a way to determine which upstream turbines' wakes are affecting a particular turbine when simulating dozens of turbines simultaneously?

I have observed that downstream turbines only experience wake effects once the upstream turbines' wakes have propagated to their positions. Are there any methods to speed up this process?

Best wishes, god bless you

**Comment by jjonkman** [comment]
Dear @shipors,

Here are my responses:.

I'm not sure I understand your first question, but I would say that the VTK output should only be used when you want to visualize the wake behavior.  If you are running many (hundreds to thousands) of simulations, generating VTK output will slow down FAST.Farm and require a lot of storage.  I would suggest disabling VTK output if you are running many cases, and rerun the cases that you want to visualize with VTK output enabled.

Regarding wakes ending prematurely (without the wake deficit gradually decaying away), this implies that `NumPlanes` may need to be increased.  It _may_ be that you are not following the recommended FAST.Farm modeling guidance for other spatial-temporal descritization settings (https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html), which results in an incorrect setting for `NumPlanes`.

While FAST.Farm internally superimposes wakes from upwind turbines to impact the inflow of downwind turbines, there is currently no convenient way of writing which turbines impact others in an output file.  But this should be reasonably clear through the farm-wide wake visualization output.

FAST.Farm does have a sizeable start-up transient as it takes time for the wakes to propagate after model initialization.  There is not currently a way to speed up or eliminate this start-up transient.  It is currently recommend to estimate what this start-up transient time is (see the modeling guidance) and ignore that time period when post-processing FAST.Farm outputs.

Best regards,
