### ISSUE TITLE
The simulation is running too slowly

### ISSUE THREAD

**Issue by smilke** [OpenFAST/openfast#261]
**Bug description**

When I run the OpenFAST using input file 5MW_Land_DLL_WTurb and WP_VSP_WTurb, I got an unbelievable "Total Real Time". The test for 5MW_Land_DLL_WTurb toke total run time about 120 seconds for 60 seconds' simulation, and the WP_VSP_WTurb toke total run time about 59 seconds for 40 seconds' simulation. Is this situation normal? I am new to OpenFAST, but according to my previous experience with FASTv8, this is unbelievable.

**To Reproduce**

1. Compile with 'gnu'
2. Run '5MW_Land_DLL_WTurb' case with 'DLL unused' settings, and run 'WP_VSP_WTurb' case with raw settings.
3. The problem is that I don't know if this is normal?

**Expected behavior**

I expect that this simulation can take less time, at least lower than the simulation time.

**OpenFAST-v2.0.0-dirty**
```
**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.0.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Mar  6 2019
  - Time: 17:19:38
 Execution Info:
  - Date: 11/29/2018
  - Time: 09:28:55
```

**System Information (please complete the following information):**
 
 - OS: Ubuntu 16.04 
 - Compiler:  GFortran 5.4
 - Compiler settings: Release version and static library and any other things is follow raw setting

**Comment by ashesh2512** [comment]
@smilke 120 seconds wall time for a 60 second simulation does seem a bit long, but this could depend on multiple factors. OpenFAST has been configured to run nightly tests on one of NREL’s clusters. Last night the test reported a run time of about 72 seconds as can be seen here. 

https://my.cdash.org/viewTest.php?buildid=1622580

**Comment by rafmudaf** [comment]
Also keep in mind that double precision is much slower than single precision. Are you comparing the same numerical precision in fast 8 vs openfast?

**Comment by smilke** [comment]
In fact, I did compile OpenFAST into double precision, and I don't know if FASTv8 is single-precision or double-precision, because I used to use the archive version under Windows, I will check it out. I currently need to run OpenFAST in real time, so I must ask his actual execution time to be less than the simulation time. Do you have any suggestions?

Also, I need to use a 5MW model or a 1.5MW model. In fact, I can reduce the computational accuracy requirements, as long as it can run fast enough.

**Comment by smilke** [comment]
I have solved  the problem by changing double precision to single precision. Thanks for your advise. But I am still confused about how to improve the running speed of FAST as much as possible

**Comment by jjonkman** [comment]
Dear @smilke,

Yes, I would encourage you to compile in single precision when running many simulations.  Single precision should be sufficiently accurate and much faster than double.

We've also had a discussion on our forum about how to reduce the time necessary to run FAST / OpenFAST simulations--see: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1416&p=12380.

Best regards,

**Comment by smilke** [comment]
Dear @jjonkman 
Thank you so much, the link you gave is very helpful.

**Comment by rafmudaf** [comment]
Thanks for the added info, @jjonkman

**Comment by hbasbas** [comment]
> Dear @Smilke,
> 
> Yes, I would encourage you to compile in single precision when running many simulations. Single precision should be sufficiently accurate and much faster than double.
> 
> We've also had a discussion on our forum about how to reduce the time necessary to run FAST / OpenFAST simulations--see: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1416&p=12380.
> 
> Best regards,

Dear @jjonkman and @rafmudaf,

When clicking on the link, I cannot find the issue directly. Is it possible to give me this link again ? Maybe due to possible website update, the link is not working well.

Best regards,

**Comment by jjonkman** [comment]
Dear @hbasbas,

Unfortunately the deep links changed when switching from the old to new forum, so, while the forum posts/topics still exist, many of these cross-references are broken.  However, here is one forum topic that is relevant and is likely the one I had previously linked to: https://forums.nrel.gov/t/fast-computation-time-and-improvement/1235.

Best regards,

**Comment by hbasbas** [comment]
Dear @jjonkman 

Thank you for this link. Useful !
