### ISSUE TITLE
Suggestion for changing build dependencies

### ISSUE THREAD

**Issue by bjonkman** [OpenFAST/openfast#267]
**Is your feature request related to a problem? Please describe.**
Every time the git hash changes, the NWTC Library is (or at least should be) rebuilt. Since almost all code depends on this library, this results in a lot of unnecessary rebuilding/linking.

**Describe the solution you'd like**
I suggest moving the the `QueryGitVersion` subroutine in the NWTC Library to a separate stand-alone module that only the glue codes and drivers depend on.

**Comment by ebranlard** [comment]
Yes! That's the way forward in my opinion. I've been discussing this with @rafmudaf  and I believe he is working on a solution.

**Comment by ebranlard** [comment]
I believe `VersionInfo.f90` is not recompiled in Visual studio if the git version changes. I don't know how to force a dependency between this file and the git header file. 
An alternative, is to force a timestamp change of VersionInfo.f90. https://stackoverflow.com/a/35498399/627911

@bjonkman do you confirm this is indeed an issue?

**Comment by bjonkman** [comment]
@ebranlard I've played around with a few things in the OpenFAST Visual Studio files, but it looks like Visual Studio does not notice that changing the header file should rebuild the VersionInfo.f90 file. When I generate the dependency list for that file, it does show there is a dependency on the header file (though not on the file specified in the intermediate directory), so I think that would be something to ask Intel.

You can change the timestamp using a pre-Build step like that example you've linked to. HOWEVER, it still won't build that file on that particular build step because it seems to look at the timestamp _before_ pressing build. It will build it the _next_ time you build. If you delete the versioninfo.obj and versioninfo.mod files instead of changing the VersionInfo.f90 time stamp, it would force you to build the second time. **I'd probably change the timestamp or delete the intermediate files on the post-build step instead**. Then you would force it to recompile VersionInfo.f90 every time without having to hit build twice.

**Comment by bjonkman** [comment]
Note: After #428, the VersionInfo module is now used in NWTC_IO.f90, which reverts the dependency changes discussed here.
