### ISSUE TITLE
Issues when compiling OpenFAST on Windows under Cygwin

### ISSUE THREAD

**Issue by traft1966** [OpenFAST/openfast#273]
Hi, everyone

I have issue when building OpenFAST under Cygwin

I attach error message and compile environment

・Installing OpenFAST
I followed Open FAST Docs [https://openfast.readthedocs.io/en/master/source/install/install_cmake_cygwin.html](url)

・error message example

> Warning:__builtin_memset’: specified size 18446744073709551598 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]

Please, give me some advice 

thank you
Ryota

![error1](https://user-images.githubusercontent.com/49219711/56110411-586cd400-5f8f-11e9-8f79-bdf0ac4df821.PNG)
![error2](https://user-images.githubusercontent.com/49219711/56110412-59056a80-5f8f-11e9-8894-3e163986bcf5.PNG)
![error3](https://user-images.githubusercontent.com/49219711/56110413-59056a80-5f8f-11e9-9bc1-a3dc72cc67b4.PNG)
![error4](https://user-images.githubusercontent.com/49219711/56110414-59056a80-5f8f-11e9-8e5a-010a3d7f1b6e.PNG)

**Comment by lenhou** [comment]
Hi Ryota,

I remember I had the similar warnings when I was compiling openfast, but I ignored the warnings. In the end, I still successfully completed the whole compilation process, and got the executable (openfast.exe).

I don't know if the warnings affect in any aspect of the calculation results though.

Regards,
Len

**Comment by rafmudaf** [comment]
Thats right, those are warnings and don't affect the code execution. I believe its related to this bug in gfortran: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79929. Nevertheless, this is fixed in gfortran 8+.
