### ISSUE TITLE
Regression test fails

### ISSUE THREAD

**Issue by lenhou** [OpenFAST/openfast#274]
Hi everyone,

I have the same issue as closed issue #197, but I don't know what I can do to correct it.
![test result](https://user-images.githubusercontent.com/49435712/56116464-6bd06d00-5f98-11e9-98f5-b15070b715f8.jpeg)

I use ubuntu 14.04 as my dell laptop's OS and run the regression tests with CTest following the instruction in the documentation.

From the closed issue #197, I have learned to check that DISCON controllers are required to be in the designated folders.

I followed the instruction of the documentation and also checked that the DISCON controllers are located in the following folders as the NOTE of README.md for r-test reminded:
`openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoData/DISCON.dll`
`openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoData/DISCON_ITIBarge.dll`
`openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoData/DISCON_OC3Hywind.dll`

By the way, I've found that there is maybe an inconsistent description of the location of DISCON controllers in the documentation.

In section 5.2.2.3 of the online OpenFast documentation (https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#ctest-configuration), which says that the DISCON controllers must exist in the following location:
`openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoDyn/DISCON.dll`
`openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoDyn/DISCON_ITIBarge.dll`
`openfast/build/reg_tests/glue-codes/openfast/5MW_Baseline/ServoDyn/DISCON_OC3Hywind.dll`

But it is different from the location (../ServoData instead of ../ServoDyn) indicated in the README.md for r-test, which may cause confusion.

Does anyone have the same issue here? Any hints or possible solutions for this situation?

Thank you.

Regards,
Len

**Comment by rafmudaf** [comment]
@lenhou can you run a single case in verbose mode with this command:
```
ctest -VV -R AOC_YFix_WSt
```
and show the results here? It should be something like this: 

```
>>mbp@~/Development/openfast/build (docs/fast8readme $)$ ctest -VV -R AOC_YFix_WSt
UpdateCTestConfiguration  from :/Users/rmudafor/Development/openfast/build/DartConfiguration.tcl
Parse Config file:/Users/rmudafor/Development/openfast/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/rmudafor/Development/openfast/build/DartConfiguration.tcl
Parse Config file:/Users/rmudafor/Development/openfast/build/DartConfiguration.tcl
Test project /Users/rmudafor/Development/openfast/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 8
    Start 8: AOC_YFix_WSt

8: Test command: /Users/rmudafor/.virtualenvs/openfast/bin/python3 "/Users/rmudafor/Development/openfast/reg_tests/executeOpenfastRegressionCase.py" "AOC_YFix_WSt" "/Users/rmudafor/Development/openfast/build/glue-codes/openfast/openfast" "/Users/rmudafor/Development/openfast/reg_tests/.." "/Users/rmudafor/Development/openfast/build/reg_tests/glue-codes/openfast" "0.00001" "Darwin" "GNU"
8: Test timeout computed to be: 5400
```

The **Test command** line towards the bottom will show you the location of the log file for this case. It would be helpful if you include that as well.

**Comment by lenhou** [comment]
Hi  @rafmudaf,

Thank you for your help. It helps me to learn more about CTest function.
 
The result of the single case shows as follows: 

![test_result_2](https://user-images.githubusercontent.com/49435712/56187825-6c2f3d80-6056-11e9-9300-011827304c49.jpeg)

The log file is attached here: [AOC_YFix_WSt.log](https://github.com/OpenFAST/openfast/files/3083369/AOC_YFix_WSt.log)

I have also executed the other case (AWT_YFree_WSt) which failed in the regression test before.

Below is the result and the log file is attached here: [AWT_YFree_WSt.log](https://github.com/OpenFAST/openfast/files/3083409/AWT_YFree_WSt.log).

![test_result_3](https://user-images.githubusercontent.com/49435712/56188638-a0a3f900-6058-11e9-97a1-7001f72c5f6f.jpeg)

To compare both log files, it seems like there is a same warning: 

`Warning: Turning off Unsteady Aerodynamics due to high angle-of-attack.`

I don't know if it's related to the fails.

Could you give me advice to solve the issue?

Thank you again.

Regards,
Len

**Comment by rafmudaf** [comment]
Thanks for providing this extra info @lenhou. It looks like your cases completed successfully, but it is surprising that so many failed. The linux-gnu baselines were generated on CentOS with gfortran 7, so any differences in your system may cause some failures. I have an Ubuntu machine where I can also run the regression test so I'll set that up and let you know if I see the same thing.

Your next step from here should be to plot the results and visually inspect the differences. You can do that in cmake by turning on the `CTEST_PLOT_ERRORS` flag, but this would require rerunning all of the tests. An alternative is the use the included python script in `openfast/reg_tests/` for running the test cases with this command:

```
python3 manualRegressionTest.py ../build/glue-codes/openfast/openfast linux gnu 1e-5 -n -p
```

Here, the `-n` flag tells the script to avoid actually running the case and the `-p` flag turns on plotting. When this is finished you'll see a `.html` file at `openfast/build/reg_tests/`.

**Comment by rafmudaf** [comment]
I've finished recompiling and running the regression test suite on Ubuntu 18.04 with gfortran 7.3 and have 16 failing tests. After looking at the plots, everything is very close to the baselines. So, I suggest you go through this same process and verify that everything looks fine on your side.

**Comment by lenhou** [comment]
Thank you @rafmudaf ,

After I checked the plots, there are actually many results aren't matched with their baseline solutions.
I made a summary of the testing results via manual Regression Test with python3 as below:
![summary](https://user-images.githubusercontent.com/49435712/56259390-6f353700-6105-11e9-9336-a22df315cd83.jpeg)
For example, the "PtfmHeave", "PtfmSurge" and "RotSpeed" of the "5MW_OC4Semi_WSt_WavesWN" are obviously unmatched to the baseline:
![PtfmHeave](https://user-images.githubusercontent.com/49435712/56259565-0f8b5b80-6106-11e9-822d-36c04cbca434.png)
![PtfmSurge](https://user-images.githubusercontent.com/49435712/56259572-17e39680-6106-11e9-9adc-40025003a9f3.png)
![RotSpeed](https://user-images.githubusercontent.com/49435712/56259501-d7841880-6105-11e9-9359-8ced6fd20c14.png)
Mentioning about the differences of systems, I previously used Ubuntu 18.04 but I failed to compile openfast with the problem similar with closed issue #154. I then successfully compiled openfast when I switched to Ubuntu 14.04 following your comment on the closed issue. Thank you for that one. :)
I also checked that the version of gcc and gfortran on my laptop is 4.8.4. Maybe that is also the possible factor for causing the fails.  
The next step I will try is to update my gcc and gfortran and rebuild openfast, also to rerun the whole test. I hope it's a correct option to make.
Do you have any suggestions to my situation here? 

Thank you as always.

Regards,
Len

**Comment by rafmudaf** [comment]
Wow thats much more of a difference than I would expect. I think upgrading your compiler version is a good move. In case you're having trouble finding gcc 7+ for ubuntu trusty, this PPA gives you a few versions: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test. You can use it with
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gfortran-7
```

**Comment by rafmudaf** [comment]
Please comment on how that turns out.

**Comment by lenhou** [comment]
Hi @rafmudaf and everyone,

I have reinstalled Ubuntu 18.04 with gfortran 7.3. Sadly, I have found similar compilation error as before, although the issue is irrelevant to testing. 

To completely document the issue, my system information is listed as below for reference:
-  Ubuntu: version 18.04
-  GCC: version 7.3.0 (already installed with Ubuntu)
-  GNU Fortran: version 7.3.0
-  Python: version 3.6.7 (already installed with Ubuntu)
-  GNU Make: version 4.1 (already installed with Ubuntu)
-  CMake: version 3.10.2

After I reinstalled Ubuntu 18.04, I did commands at the terminal as the following:
- Update the system first:
`$ sudo apt-get update` 
`$ sudo apt-get upgrade`
- Install dependencies and download openfast source code:
`$ sudo apt install git`
`$ git clone --recursive https://github.com/openfast/openfast.git`
`$ sudo apt-get install gfortran`
`$ sudo apt-get install cmake`
`$ sudo apt-get install build-essential`
`$ sudo apt-get install libblas-dev liblapack-dev`
-  Start regression test:
`~/openfast$ mkdir build install && cd build`
`~/openfast/build$ cmake .. -DBUILD_TESTING=ON`
`~/openfast/build$ make install`

CMake has no problems. The error happened during the compilation process when it went to 85%. Below is the error message.
![result](https://user-images.githubusercontent.com/49435712/56401608-5905b300-628c-11e9-8def-39b8b34fdadf.jpeg)
Blindly, I did make once again. The error message is the same.
![image](https://user-images.githubusercontent.com/49435712/56401747-07a9f380-628d-11e9-980e-1a7802e0eb95.png)

Both are pointing to the same issue:

`modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/build.make:110 recipe for target 'modules-local/openfast-library/CMakeFiles/opendast_postlib.dir/src/FAST_Subs.f90.o' failed`

So I checked the build.make file, line 110, which reads:

`@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/len/openfast/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building Fortran object modules-local/openfast-library/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o"`

and line 111 is:

`cd /home/len/openfast/build/modules-local/openfast-library && /usr/bin/gfortran $(Fortran_DEFINES) $(Fortran_INCLUDES) $(Fortran_FLAGS) -c /home/len/openfast/modules-local/openfast-library/src/FAST_Subs.f90 -o CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o`

Based on the aforementioned information, I still can't figure out what I should do to solve the issue.

Does anybody have the same issue as me? Or any suggestions for this situation?

Thank you.

Regards,
Len

**Comment by rafmudaf** [comment]
Can you retry compiling in debug mode? Change CMAKE_BUILD_TYPE to “Debug”

**Comment by rafmudaf** [comment]
In more detail, you can do this by rerunning the cmake command with this:
```
cmake .. -DBUILD_TESTING=ON -D CMAKE_BUILD_TYPE=Debug
# and then just rerun make
make install
```

**Comment by lenhou** [comment]
Hi @rafmudaf,  
Thank you. I have completed the compilation in debug mode. I am curious about the reason though...
But all cases failed in ctest.
Regards,
Len

**Comment by lenhou** [comment]
Hi @rafmudaf, 
The testing failure is because I didn't install python3-numpy.
Now it's actually running the tests.
I will share my findings on the test results.
Thank you for your help.
Regards,
Len

**Comment by lenhou** [comment]
Hi @rafmudaf,

Thank you for your help.

After I rerun the test, except 5MW_Land_BD_DLL_WTurb appears to unmatch the baseline, every test results are fine.

Below are some parameters which I found inconsistencies:

![B2RootFxr](https://user-images.githubusercontent.com/49435712/56481304-fc570200-64f0-11e9-8e60-ab681b9c93d0.png)
![B2RootFyr](https://user-images.githubusercontent.com/49435712/56481305-fc570200-64f0-11e9-9df1-3a5d6fb2350a.png)
![B2RootFzr](https://user-images.githubusercontent.com/49435712/56481306-fcef9880-64f0-11e9-97fd-759af361f1de.png)

Besides, parameters (e.g. RootF, RootM, and TipRD) of blade 1 and blade 2 in the same test also seem inconsistent to the baseline.

This case maybe only happens on me which makes it difficult to identify the possible issue.

Any suggestions?  I will try to look into the code and have a better understanding to the whole testing procedure.

Thank you.

Regards,
Len

**Comment by andrew-platt** [comment]
This almost looks like the quasi-static initialization is used in BeamDyn for the local, but the reference has that turned off.  With the quasi-static initialization, all the centrifugal forces are presolved, which results in all the initial high frequency content in the blade `B#RootFzr` terms to vanish. @rafmudaf, was there a change in the test case with this initializaton without the baseline getting updated?

**Comment by rafmudaf** [comment]
The baselines should have been updated and the nightly test is [passing](https://my.cdash.org/viewTest.php?onlypassed&buildid=1666049). I wonder if @lenhou switched from the `master` branch to the `dev` branch while building and testing? If the regression test was first run on the master branch, the old baselines would have been copied into the build directory. Then, if the repo was switched to dev, the new solution without the startup transients would be generated locally and compared to the old baselines. If this is the case, delete `build/reg_tests` and rerun cmake and the regression test.

**Comment by rafmudaf** [comment]
It sounds like these issues are solved and there may have been a misconfigured regression test. @lenhou please comment if you still have issues here.

**Comment by lenhou** [comment]
Hi @rafmudaf ,
Thank you for your answer.
I am sorry that I was not able to follow up this issue.
While building and testing, what I did was to follow the instruction on the documentation. 
I didn't switch from the master branch to the dev branch. 
At least I was not aware that I can do so.
To make sure my openfast is the current one on this github, I removed the whole openfast folder on my machine and cloned it recently, but I still found the same issue.
I don't know if regression test is misconfigured or other setup issues.
Could you give me some advice?
Thank you again.
Regards,
Len

**Comment by rafmudaf** [comment]
Hi Len

I have a couple of suggestions:
1. Use the `dev` branch
2. Use RelWithDebInfo as your compile type

To get onto the dev branch, first clone the repository as you have done with
```
git clone https://github.com/openfast/openfast
```

Then, move into the openfast directory and run this command to get onto the `dev` branch and update the submodules
```
git checkout dev && git submodule update
```
You can verify this worked by checking your git-status
```
git status
```

FInally, continue through the build process by creating and `build` directory and running cmake. You CMake command should be this:
```
cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
make install
```
This will use more aggressive optimizations than `Debug` so it should be closer to the r-test baselines. I'm hoping that it was also avoid the compiler bug you ran into earlier when you compiled in `Release` mode.

**Comment by lenhou** [comment]
Hi @rafmudaf ,

Thank you for your prompt reply.

Firstly, I cloned the repo with `--recursive` flag.
Then I followed your suggestions by using `dev` branch and `RelWithDebInfo` as build type.

I found it takes more time to build and test then the original settings, but sadly, the result shows the same. 
I randomly pick some unmatched test results from `5MW_Land_BD_DLL_WTurb` shown as below:
![image](https://user-images.githubusercontent.com/49435712/62992223-34f65f00-be85-11e9-81ff-00be592d8787.png)
![image](https://user-images.githubusercontent.com/49435712/62992242-48a1c580-be85-11e9-99ff-f7d6c858605f.png)
![image](https://user-images.githubusercontent.com/49435712/62992255-56efe180-be85-11e9-939d-fc8f8d9e489e.png)

I am wondering why only `5MW_Land_BD_DLL_WTurb` has unmatched results, while the others show no or little deviations.

What I am trying to do afterwards is to generate S-function and to use MATLAB for my later applications, I don't know if this issue affects the correctness of my simulation. 

If that's the case, I will have to stick to this issue, and make it work, otherwise, I prefer to move on to the next step. 

By the way, is there any guidance for OpenFAST and MATLAB/Simulink simulation?

Thank you as always.

Regards,
Len

**Comment by lenhou** [comment]
@rafmudaf 
Thank you. 
I am not sure what I did is right or wrong. 
I did `git pull` on my original folder, then I continued build process with 
```
cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
make install
```
followed by `ctest` and executed manualRegressionTest.py again, but test result is the same. 
Should I remove the whole folder and clone the latest repository on dev branch again? Or is there any step I missed?
Thank you as always.
Regards,
Len

**Comment by rafmudaf** [comment]
@lenhou be sure to update the submodule with ```git submodule update```.

**Comment by lenhou** [comment]
@rafmudaf 
Thank you.
I deleted my local folder and cloned it again, and followed your suggestions. Finally, there are only two test cases failed.
<img width="407" alt="11" src="https://user-images.githubusercontent.com/49435712/63991736-80626b80-cb1b-11e9-9155-86fd5311cab9.png">
After I checked these cases from the drawing, I found there aren't major discrepancies. 
Thank you as always.
Regards,
Len
