### ISSUE TITLE
SysGnuWin issues introduced in #271

### ISSUE THREAD

**Issue by bjonkman** [OpenFAST/openfast#278]
In reviewing pull request #271, which was merged over the weekend, I found a few issues in changes that were made to SysGnuWin.f90:

1. gfortran's `FSTAT` [documentation](https://gcc.gnu.org/onlinedocs//gfortran/FSTAT.html#FSTAT) says its arguments need to be `INTEGER(4)`, but they were changed to default integers using `INTEGER` (see lines 80-81). This means that the size of the integer now depends on compiling options. Is there a reason this was changed?

2. The `make_command` on line 223 now creates a directory called `-p` and will have issues if windows path names include '/' in their path names. I had fixed this syntax in a previous pull request (#194), but it's been overwritten with linux syntax again.

**Comment by rafmudaf** [comment]
I made these changes to that sys file in order to fix some bugs with CygWin, but the eventual fix was to use the linux file for CygWin. I'll look again at all the changes that were made to `SysGnuWin.f90` as much of that might actually have been unnecessary.

**Comment by bjonkman** [comment]
It looks like the SysGunLin.f90 file should also use `INTEGER(4)` for `FSTAT`. The Intel version(s) of the function can take default integers.

**Comment by rafmudaf** [comment]
In wondering why this didn't cause a problem sooner, I found that this function (`FileSize`) is only used in the nwtclib tests. Am I missing it somewhere?

In any case, does this line handle the integer size issues you pointed out?
```
   Status = FSTAT( INT( Unit, B4Ki ), StatArray )
```

**Comment by bjonkman** [comment]
No, that doesn't fix the issue. The `StatArray` needs to be `INTEGER(4)` in gfortran: https://gcc.gnu.org/onlinedocs//gfortran/FSTAT.html#FSTAT. That documentation also says `Unit` is a default integer, so I am not sure why `Unit` would be converted to `INTEGER(4)` in the SysGnuLin version of the routine.

I think this routine was called in some of the other NWTC code that that Marshall wrote that isn't in the OpenFAST repository. NWTC_Library was part of a lot of different codes.

You would only notice a problem if you were building with default integers set to be INTEGER(8), which you would probably never do. But if you're going to be changing the data types in a routine, it should follow the documentation.

**Comment by rafmudaf** [comment]
closed by #279
