### ISSUE TITLE
SubDyn and MKL

### ISSUE THREAD

**Issue by sinolonghai** [OpenFAST/openfast#29]
I compiled openfast using intel compiler with MKL math library. For Test21, I found that when I set OMP_NUM_THREADS parameter to a larger number, the MKL can run in parallel, which can speed-up the calculation. However, when OMP_NUM_THREADS is set to different values, the generated Test21.SD.sum files are different, and then obviously the final calculation results are different. Any reason for this to happen?

Thanks!

Hai

**Comment by michaelasprague** [comment]
@sinolonghai, is the only parallelization embodied in the MKL library? (and no where else in FAST)?

**Comment by jrood-nrel** [comment]
I would expect differences with threaded MKL. It just depends on how different. https://software.intel.com/en-us/articles/getting-reproducible-results-with-intel-mkl/

**Comment by jrood-nrel** [comment]
Also you can try turning on CNR and see if that gives you the same answer.
https://software.intel.com/en-us/node/528730

**Comment by sinolonghai** [comment]
Yes Mike and Jon. This is an MKL problem. By setting both OMP_NUM_THREADS and MKL_NUM_THREADS, if MKL_NUM_THREADS uses the same value, no matter what OMP_NUM_THREADS value will be, the final result will remain identical.
