### ISSUE TITLE
DLLEXPORT directives in FAST_Library

### ISSUE THREAD

**Issue by sayerhs** [OpenFAST/openfast#3]
The `DLLEXPORT` directives in `FAST_Library.f90` for Intel Fortran Compiler generates warnings when compiling on Unix-y architectures. Replace snippets as below to quell this warning

```
!DEC$ ATTRIBUTES DLLEXPORT::FAST_Sizes
#ifndef IMPLICIT_DLLEXPORT
!GCC$ ATTRIBUTES DLLEXPORT :: FAST_Sizes
#endif
```

with 

```
#ifndef IMPLICIT_DLLEXPORT
!DEC$ ATTRIBUTES DLLEXPORT::FAST_Sizes
!GCC$ ATTRIBUTES DLLEXPORT :: FAST_Sizes
#endif
```

CMake is already set up to handle addition of `-DIMPLICIT_DLLEXPORT` on Unix-y architectures.

**Comment by rafmudaf** [comment]
fixed in pull request #70
