### ISSUE TITLE
Applying Sinusoidal Force at the Tip in BeamDyn

### ISSUE THREAD

**Issue by Pouria-AZD** [OpenFAST/openfast#300]
Hi all,

Considering dynamic analysis of BeamDyn, there is a force at the tip of the blade and I want to have it in sinusoidal mode not to stop at a time step and being constant until the end of it, as I have in my result that shows from a specific time step to the end that the force and displacement do not change. 
Also, I was wondering if there is any way to see the tip displacement for each node along the blade.

Thank you in advance.

**Comment by andrew-platt** [comment]
Hi Pouria,

I am not sure I entirely understand your question.  At present, the BeamDyn driver can only apply constant forces. There is no method currently to apply a timeseries force to the blade (there were discussions a long time ago about adding this, but we have not done anything further with it).

For the solve, the driver allows you to specify either a static solve, or dynamic solve.  In the static solve, each 'timestep' output is actually an iteration step output and not really time.

In the main input file, there is an option for `QuasiStaticInit` initialization option.  This initializes a dynamic case in the deflected position. If you apply a tip load with the `QuasiStaticInit` set to `false`, the beam should oscillate and eventually reach equilibrium (depending on what damping is applied). If the `QuasiStaticInit` set to true, the beam will start in the deflected position and show no oscillations.

As far as seeing displacements at each node, you can see the displacements of up to 9 nodes using the outputs `N#TDxr` etc. (where # is the 1 digit node number).  We have plans to simplify getting all nodes outputs more easily (more than 9 nodes), but do not have a timeline for when that feature will be added.

**Comment by Pouria-AZD** [comment]
Hi Andrew,

As I have got from your explanation, in BeamDyn in fact the dynamic solve does not have a dynamic force, but in the output file from the first time increment(equal to 2e-4) there are different forces applying (in N1Fxl), also more than my input force in the driver input file just until around 1s and after that to the end(total time step is 4s) the force would be constant and the displacement is reached to its maximum deflection and it is constant from the first second to the end as well.
I have this question that how is it possible when the force is constant then we get the result that shows the force is changing by time and suddenly stops at your input force value then it is constant until the end as a straight line? therefore the maximum deflection in both solving(static and dynamic) should be the same because we can not say that we got dynamic result! 

Regards,

**Comment by andrew-platt** [comment]
To clarify, the outputs for `N#Fxl` (etc.) are the _internal forces within the blade_, not an applied force.  So at time 0 when a tip load is applied, the blade must deflect before that internal force exists (the internal forces within an undeflected beam with no load is zero).

I think you are looking at results from a *static solve*.  During the static solve, each output timestep is a solve iteration.  It takes a couple of iterations before the final solution is converged (no more than 4).  Note that the *static solve* does not include any dynamic effects.

If you run the same simulation as a *dynamic solve*, it could take upwards of a hundred seconds for the beam to reach a steady state solution.  This will depend on the stiffness and mass matrices, applied load, length of beam, and damping ratios used.  Once it reaches steady state, it will be converged to the same displacements and internal loads as seen in the static solve.

**Comment by Pouria-AZD** [comment]
Dear @andrew-platt ,

First let me thank you for your helpful explanations.

In my case I have considered 4 members with 9 key points while I have 6 nodes for each element which makes it 21 nodes for node total. now I am wondering how it is possible to apply concentrated force at the final node of each of the 4 members(not only at the tip of the beam but also by applying an external force for the internal nodes to have their displacement results).

Regards,

**Comment by andrew-platt** [comment]
The driver input file allows for adding point loads at specific locations along the blade span. For example, you could apply a point load at 0.9101 of the blade span as follows:

```
          1   NumPointLoads - Number of point loads along blade
Non-dim blade-span eta   Fx          Fy            Fz           Mx           My           Mz
(-)                      (N)         (N)           (N)          (N-m)        (N-m)        (N-m)
0.9101    0  0  0  0  25 0
---------------------- PRIMARY INPUT FILE --------------------------------------
```

These point loads are mapped over to the corresponding quadrature points.
