### ISSUE TITLE
Using a different AeroDyn module

### ISSUE THREAD

**Issue by reich-martin** [OpenFAST/openfast#301]
Hi, 

I am looking into switching from the BEMT to a different method for the calculation of the aerodynamic loads. Therefore, I would like to know how closely the different modules are linked together. 

- Can I just take the input variables and calculate the same output variables (which are those?) as AeroDyn does but with the new method? 
- Do other modules need more data besides the output information?
- Are the calculations and functions calling the calculations spread all over the source code or do I just need to look in specific locations, i.e. FAST_Subs.F90?
- Is the data between the AeroDyn module and the other modules linked by using the mesh map system?

How easily can the AeroDyn module be exchanged?

Thanks
Martin

**Comment by jjonkman** [comment]
Dear Martin,

OpenFAST is modular and data is encapsulated.  This means OpenFAST only communicates with modules through predefined interfaces (SUBROUTINES) and data is only transferred through these interfaces (as SUBROUTINE arguments).  The modularization framework is well documented here: https://nwtc.nrel.gov/FAST-Developers.  Here are my answers to your specific questions:

- Yes.

- No, but there are two sets of outputs: 1) outputs computed by the *_CalcOutput() routine every time step and 2) initialization outputs computed only once at initialization by the *_Init() routine.

- Calculations for a given module are limited to that module's source code, e.g. the interface routines for AeroDyn are in AeroDyn.f90.

- Yes.  All data passed across spatial boundaries in OpenFAST use the mesh-mapping system.

The ease of changing e.g. AeroDyn depends on the nature / sophistication of the state update and output calculations and your experience with programming / Fortran and the modularization framework.

Best regards,

**Comment by andrew-platt** [comment]
Closing this issue as it is a development question rather than issue or feature request in the code.
