### ISSUE TITLE
Is the openfast-registry dependency necessary?

### ISSUE THREAD

**Issue by rafmudaf** [OpenFAST/openfast#303]
**Is your feature request related to a problem? Please describe.**
The OpenFAST Registry is currently used to generate fortran code for the module types files. It is the first executable compiled any time OpenFAST is compiled as every module needs to have its types module generated before it can compile. The dependency on source code that isn't included in the repository has been causing headaches in CMake and Visual Studio.

*Is there still a good reason to generate the module types files on every compile instead of including them in git directly?*

I'm *not* proposing to get rid of the registry, but rather remove it from the OpenFAST build and remove the autogeneration of types files for every build. Whenever a change is made to the module registries, the `.txt` files would still be modified and run through the registry executable but the output of that would be committed to the repo.

**Describe the solution you'd like**
- Remove the registry as a dependency of OpenFAST
- Commit the module types files
- Include documentation for when to use the registry, how to compile it, and how to use it; specifically document the process for updating the module types
  - update the Module_Registry.txt
  - run registry
  - commit x,y,z

**Describe alternatives you've considered**
- Adding type-file targets which the modules depend on - down side is this almost doubles the number of targets so theres a lot of noise in `make help` or the Visual Studio project tree
- Adding a single registry target which contains all types - down side is that then every module contains all of the types in OpenFAST. This increases build time for small targets like `beamdyn_driver`.

**Additional context**
This would also enable optimizing the module types files for performance without having to modify the registry source code.

**Seeking input from**
@bjonkman 
@michaelasprague 
@sayerhs

**Comment by rafmudaf** [comment]
also @andrew-platt

**Comment by andrew-platt** [comment]
In almost every code development effort I am involved in within OpenFAST, modifications of registry files are required and frequent.  So for my workflow, it is much better to keep the registry as a dependency rather than impose another process that I would need to keep track of and manually trigger.

In my experience, generating the types files is not a large bottleneck, but compilation step is very time consuming.

**Comment by ebranlard** [comment]
I think it makes sense to have them auto-generated, but I personally prefer having those backed up in git.  Unless they really are build dependent (OS, architecture, compiler), which I don't think the types should be.

**Comment by andrew-platt** [comment]
I don't think there is anything build dependent in the types files.

From what I remember, getting the dependency order correct with CMake + VS was what led to keeping a separate VS build process (`vs-build`).  The CMake generated VS environment was rather difficult to work within for debugging.  So perhaps if we did add additional type-file targets to simplify the CMake + VS build, it wouldn't matter too much if debugging is done in the other VS environment (though that means we continue to maintain two completely separate build environments).

**Comment by rafmudaf** [comment]
Both systems have the same types-module dependency problem, so thats not exactly the need for maintaining both. The `vs-build` project has been maintained alongside the CMake build system due to the heavier lift required to use CMake, especially for anyone wanting to simply compile once and run many times, and the gap in functionalities of the CMake VS project. One example of this gap is that debugging with a CMake-generated Visual Studio project is difficult because any settings you configure to run a test case are overwritten the next time CMake is executed. This is improving with more modern versions of CMake and Visual Studio, but its certainly not well supported yet.

I like the idea of a switch for autogenerating the types. However, I'd suggest doing the opposite of @andrew-platt's suggestion: exclude the types autogeneration by default but have a switch to turn it on when needed. This would solve the problem in both `vs-build` and CMake and possibly serve the majority of users better. As listed below, changes to the registry files are relatively infrequent. Further, exporting the autogenerated types files to the module `src` directories rather than the `build` directory would track the differences in git.

```
#   LAST COMMIT                          FILENAME
Wed Oct 3 16:58:41 2018 -0600 ./modules-local/beamdyn/src/Registry_BeamDyn.txt
Wed Jul 25 17:35:05 2018 -0600 ./modules-local/openfast-library/src/FAST_Registry.txt
Wed Jul 25 17:35:05 2018 -0600 ./modules-local/openfoam/src/OpenFOAM_Registry.txt
Wed Jul 25 17:35:05 2018 -0600 ./modules-local/elastodyn/src/ElastoDyn_Registry.txt
Sun May 13 20:38:40 2018 -0600 ./modules-local/aerodyn/src/AeroDyn_Driver_Registry.txt
Sun May 13 21:03:33 2018 -0600 ./modules-local/aerodyn/src/AeroDyn_Registry.txt
Sun May 13 21:01:02 2018 -0600 ./modules-local/aerodyn/src/BEMT_Registry.txt
Sun May 13 21:14:33 2018 -0600 ./modules-local/aerodyn/src/DBEMT_Registry.txt
Tue Apr 10 11:23:02 2018 -0600 ./modules-local/nwtc-library/src/Registry_NWTC_Library.txt
Tue Apr 10 11:23:02 2018 -0600 ./modules-local/nwtc-library/src/Registry_NWTC_Library_typedef_mesh.txt
Tue Apr 10 11:23:02 2018 -0600 ./modules-local/nwtc-library/src/Registry_NWTC_Library_typedef_nomesh.txt
Tue Apr 10 11:23:02 2018 -0600 ./modules-local/servodyn/src/ServoDyn_Registry.txt
Sun Jul 16 00:17:02 2017 -0600 ./modules-local/subdyn/src/SubDyn_Registry.txt
Sun Jul 16 00:17:02 2017 -0600 ./modules-local/supercontroller/src/SuperController_Registry.txt
Sat Jul 15 23:46:51 2017 -0600 ./modules-local/aerodyn/src/AirfoilInfo_Registry.txt
Sat Jul 15 23:21:56 2017 -0600 ./modules-local/aerodyn/src/UnsteadyAero_Registry.txt
Mon Apr 10 12:55:09 2017 -0600 ./utilities/template-module/src/ModuleName_Registry.txt
Mon Jul 25 23:36:09 2016 -0600 ./modules-local/aerodyn14/src/Registry-AD14.txt
Sun Aug 28 22:36:01 2016 -0600 ./modules-local/extptfm/src/ExtPtfm_MCKF_Registry.txt
Fri Mar 11 14:12:34 2016 -0700 ./modules-local/servodyn/src/TMD_Registry.txt
Wed Jan 27 19:19:35 2016 +0000 ./modules-ext/map/src/MAP_Registry.txt
Mon Jan 11 20:50:00 2016 +0000 ./modules-ext/moordyn/src/MoorDyn_Registry.txt
Fri Jan 8 02:44:37 2016 +0000 ./modules-ext/feamooring/src/FEAM_Registry.txt
Fri Jan 8 18:40:28 2016 +0000 ./modules-ext/icedyn/src/Registry_IceDyn.txt
Tue Jan 5 21:55:27 2016 +0000 ./modules-local/aerodyn14/src/Registry-DWM.txt
```
The commits listed above are from the `master` branch. All registry files changed in the `dev` branch when the `modules-ext` and `modules-local` directories were merged.

**Comment by andrew-platt** [comment]
I like the idea of the CMake switch defaulted to off.  This gives those of us needing to regularly update the types files a convenient way to auto-generate them with little inconvenience while still serving the majority of users.  It also keeps a copy of the types files in git as @ebranlard suggested.

Maybe in our test builds before allowing merges, could we test both with auto-generating and with the provided types files?  That way we can catch the rare cases where a manual Types file edit was done without the corresponding registry file edit.

**Comment by bjonkman** [comment]
I like @rafmudaf's suggestion, too. Having the Types.f90 files tracked in git would fix the biggest issue with the `vs-build` solution right now (where it can't figure out the dependencies until the types files are generated the first time).
