### ISSUE TITLE
AeroDyn standalone driver output options

### ISSUE THREAD

**Issue by whophil** [OpenFAST/openfast#304]
Hi all, two questions related to the AeroDyn standalone driver output.

1. Is it possible in the OpenFAST version of the AeroDyn driver to have more than 9 blade station outputs?
2. Is it possible to concatenate the output in "combined-case analysis" into a single file instead of bursting it into one file per case?

These may sound familiar to @andrew-platt and @bjonkman.

If these features are currently not available, I'm happy to contribute but I thought I'd check first.

**Comment by andrew-platt** [comment]
Hi Phil,

At present neither of these features that we are used to are in the OpenFAST version of the AeroDyn driver.

1.  @bjonkman  and I have discussed bringing the nodal outputs into OpenFAST for BeamDyn. We may be able to do that with AeroDyn as well.
2. At present the AD15 driver only handles single cases at a time.  Perhaps this is code Envision would be willing to share with the community?

Do you have a timeline for when you would like to see this happen?

**Comment by whophil** [comment]
Thanks @andrew-platt. I don't have any particular timeline in mind.

Feature 1 (nodal outputs) would higher priority for me. Feature 2 would be nice to have but isn't critical for my use case.

Somewhat related - is the interface for `libaerodyn` exposed or documented anywhere?

**Comment by whophil** [comment]
Hey @andrew-platt and @bjonkman , any word on if nodal outputs will be coming to NREL's AD driver?

**Comment by bjonkman** [comment]
Hey @whophil , yes, I think nodal outputs will be coming .... sometime. I'm planning to give NREL some code related to our joint linearization project in a month or so, and that will probably be part of the code dump.

**Comment by whophil** [comment]
Great news @bjonkman and @andrew-platt ! Let me know if there's anything I can do to help.

**Comment by bjonkman** [comment]
Item 1 in this issue was addressed and merged into dev with #373. 
Item 2 is part of a not-yet-ready-to-merge branch here: https://github.com/bjonkman/openfast/tree/f/LinearAero. I expect to make a pull request with that code base sometime this fall.
