### ISSUE TITLE
Question about using OpenFAST with f2py

### ISSUE THREAD

**Issue by Raiszo** [OpenFAST/openfast#307]
As suggested here #60 I used the `-DBUILD_SHARED_LIBS` options, the files are in `<install_loc>/lib` but after that I don't know how to use these files to build an interface for python using f2py similar to the MATLAB interface that appears in the docs.
Any reply is very grateful.

**Comment by Lucas-Mc** [comment]
We are currently experimenting with f2py to develop more efficient tests than the ones we have now with pFUnit. We came close to getting this to work, but ran into issues with f2py [not being compatible with derived types](https://www.numfys.net/howto/F2PY/) of which we had many which could not be avoided currently. To attempt to resolve this, we have looked into the [f90wrap](https://github.com/jameskermode/f90wrap) adaption, yet have not made any significant developments to report on so far.  Thanks for the inquiry!
