### ISSUE TITLE
Feature Request - Ability to Apply Time-Dependent Point Loads at Various Points on the Wind Turbine Structure

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#317]
**Is your feature request related to a problem? Please describe.**
When modeling laboratory-based tests (e.g., forced oscillation of a blade in a test stand, forced oscillation of the tower-base on a seismic shake table, or forced oscillation of a floating platform in a wave tank), there is often a need to apply time-varying point loads (forces, and moments) in an OpenFAST model at one or more locations on the wind turbine structure (e.g., blade tip, tower-top, platform) to mimic the experimental set-up.  It would be great to enhance OpenFAST to support this feature.

**Describe the solution you'd like**
Introduce a new module in OpenFAST that allows the user to specify user time series of 6-component loads (3 forces, 3 moments, dependent on time) at one or more user-specified locations (X,Y,Z).  The module need not have inputs or states.  The module outputs would be the lumped time-dependent loads on a point mesh that the OpenFAST glue / driver code will use mesh mapping to transfer as input to the various structural modules (e.g., ElastoDyn, BeamDyn, SubDyn) as applied loads.

**Comment by andrew-platt** [comment]
In the case of a blade in a test stand, would that be best served through the BeamDyn driver code?

**Comment by jjonkman** [comment]
@andrew-platt -- I agree if you have a BeamDyn model cantilevered to a test stand that the BeamDyn driver would function well.  The feature I am requesting above can be used if you want to excite an ElastoDyn blade model (ElastoDyn does not currently have a driver), a BeamDyn model with free-free boundary conditions (the otherwise cantilevered end in BeamDyn can be modeled as free through the ElastoDyn platform degrees of freedom when BeamDyn is coupled to OpenFAST), a full wind turbine, etc..

**Comment by andrew-platt** [comment]
Thanks for the clarification.  I'll add that the ability to apply time-dependent loads in the BeamDyn driver is also a feature that would be nice to have.

**Comment by andrew-platt** [comment]
This is now possible from the Structural Control module in ServoDyn.  This was merged in with PR #607.  An example test case is given in the OpenFAST glue-code regression test `StC_test_OC4Semi`.  In this case, a time dependent loads applied to all 3 blades simultaneously using the `BStC` option in ServoDyn.

Four options exist in ServoDyn for applying loads:
- `BStC` -- can apply prescribed loads at any point along the blades (either BeamDyn or ElastoDyn)
- `NStC` -- can apply prescribed loads at the nacelle
- `TStC` -- can apply prescribed loads at any location along the tower
- `SStC` -- can apply loads at any SubDyn node (floating flexible or fixed bottom), or the platform reference point (ElastoDyn rigid floating)
