### ISSUE TITLE
FAST 8 compile issue after changing source

### ISSUE THREAD

**Issue by muyang3121** [OpenFAST/openfast#325]
Dear Professors:
   I've been learning about smart blade and I want to add additional flap angle,I modified  some source code FAST_Library、FAST_types、FAST_Subs、FAST_Solver,there are many syntax errors, but they've been modified, and now the following error has occurred, I don't know how to fix it. Can someone help me? 

Warning	1	 warning #11010: file format not recognized for C:\Users\wangning\Desktop\FAST_v8.16.00a-bjj testing 6\bin\MAP_Win32.dll	ipo	
Error	2	 fatal error LNK1107: invalid or corrupt file: cannot read at 0x2E0	C:\Users\wangning\Desktop\FAST_v8.16.00a-bjj testing 6\bin\MAP_Win32.dll	1

**Comment by muyang3121** [comment]
Dear Professors:
  This is the problem that occurred before,Iand the library file for map should be missing for later analysis, so the FAST_v8.16.00a-bjj \bin\MAP_Win32.dll"  was added to the  additional dependencies. The following problems has been solved,but the problem occurred above.

C:\Users\wangning\Desktop\FAST_v8.16.00a-bjj testing3\Source\dependencies\NWTC_Library\SysIVF.f90 : warning: Module 'Debug\syssubs.mod' is created by both 'C:\Users\wangning\Desktop\FAST_v8.16.00a-bjj testing3\Source\dependencies\NWTC_Library\SysIVF.f90' and 'C:\Users\wangning\Desktop\FAST_v8.16.00a-bjj testing3\Source\dependencies\NWTC_Library\SysMatlab.f90'.
1>------ Build started: Project: FAST_Library, Configuration: Debug Win32 ------
1>Linking...
1>   Creating library C:\Users\wangning\Desktop\FAST_v8.16.00a-bjj testing3\bin\FAST_Library_debug_Win32.lib and object C:\Users\wangning\Desktop\FAST_v8.16.00a-bjj testing3\bin\FAST_Library_debug_Win32.exp
1>FAST_Library.obj : error LNK2019: unresolved external symbol _FAST_INITIALIZEALL_T referenced in function _FAST_Sizes
1>FAST_Library.obj : error LNK2019: unresolved external symbol _FAST_SOLUTION0_T referenced in function _FAST_Start
1>FAST_Library.obj : error LNK2019: unresolved external symbol _FILLOUTPUTARY_T referenced in function _FAST_Start
1>FAST_Library.obj : error LNK2019: unresolved external symbol _FAST_LINEARIZE_T referenced in function _FAST_Start
1>FAST_Library.obj : error LNK2019: unresolved external symbol _FAST_SOLUTION_T referenced in function _FAST_Update
1>FAST_Library.obj : error LNK2019: unresolved external symbol _EXITTHISPROGRAM_T referenced in function _FAST_End
1>FAST_Library.obj : error LNK2019: unresolved external symbol _FAST_CREATECHECKPOINT_T referenced in function _FAST_CreateCheckpoint
1>FAST_Library.obj : error LNK2019: unresolved external symbol _FAST_RESTOREFROMCHECKPOINT_T referenced in function _FAST_Restart
1>..\..\bin\FAST_Library_debug_Win32.dll : fatal error LNK1120: 8 unresolved externals
1>
1>Build log written to  "file://C:\Users\wangning\Desktop\FAST_v8.16.00a-bjj testing3\Simulink\VisualStudio\Debug\BuildLog.htm"
1>FAST_Library - 9 error(s), 0 warning(s)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by muyang3121** [comment]
Dear@jjonkman @bjonkman：
   Could you help me,please!Thank you very much!

**Comment by muyang3121** [comment]
@jjonkman

**Comment by muyang3121** [comment]
Dear@bjonkman：
   I tried to run it under release, and then it automatically generated the additional dependencies, and then copied it to debug. The compilation was successful. I'll generate the new fast_library_debug_win32.dll, the fast_library_debug_win32.exp, the fast_library_debug_win32.lib and the path in matlab and run with the  simulink, but the output pattern is obviously not working. The main thing I do now is to build a model with a flap, adjust the flap according to the blade root load change, accept the external three flap signals to reduce vibration.
   Professor, I'd like to ask if you have any good advice, thank you.

**Comment by muyang3121** [comment]
Dear@bjonkman:
     I ran the simulink example in the fastv8.16 package, the openloop example, and the closed-loop example. I picked up the oscilloscope at the pitch angle and found that when I set the wind speed to 15m/s, the values were all 0. where do I need to adjust this place?

**Comment by muyang3121** [comment]
@bjonkman

**Comment by rafmudaf** [comment]
Like @bjonkman mentioned, if there's no compelling reason to use FAST 8, you may be better served moving to OpenFAST so that everyone is on the same page with the build systems and feature sets.

In any case, the initial bug here was "solved" so I'm closing this issue. @muyang3121 reopen another one for your specific question about the pitch angle.
