### ISSUE TITLE
Rename Binary Output File Extension Used in the Regression Tests

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#331]
Currently, the OpenFAST regression tests (r-tests) use an undocumented binary file format by specifying OutFileFmt=0 in the OpenFAST primary input file.  The format of this file is different from the standard binary output format available by selecting OutFileFmt=2 or 3. But both output files are given the same output file extension (*.outb).  Because the two binary output formats are different, the binary output produced via OutFileFmt=0 should be given a different file extension so as to not be confused with the standard format produced via OutFileFmt=2.  Using the same same file extension has caused confusion because the readFASTbinary script in the MATLAB Toolbox can only read *.outb files from OutFileFmt=2.

**Comment by bjonkman** [comment]
In the matlab-toolbox pull request listed above, I have updated the Matlab reader to handle both types of files. The Python reader in the regression tests had already been updated to handle both, so I don't think it is necessary to change the extension.
