### ISSUE TITLE
TurbSim Bladed-Style-Wind(.wnd)

### ISSUE THREAD

**Issue by RuiliangWang** [OpenFAST/openfast#334]
Hello Everyone,
  When I read the TurbSim code below ,I found some question.

> `SUBROUTINE WrBinBLADED(p, V, USig, VSig, WSig, ErrStat, ErrMsg)

> WRITE (UBFFW)   INT(  -99                                   , B2Ki )     ! -99 = New Bladed format
>       WRITE (UBFFW)   INT(    4                                   , B2Ki )     ! 4 = improved von karman (but needed for next 7 inputs)
>       WRITE (UBFFW)   INT(    3                                   , B4Ki )     ! 3 = number of wind components
>       WRITE (UBFFW)  REAL( p%met%Latitude                         , SiKi )     ! Latitude (degrees)
>       WRITE (UBFFW)  REAL( p%met%Z0                               , SiKi )     ! Roughness length (m)
>       WRITE (UBFFW)  REAL( p%grid%Zbottom + p%grid%GridHeight/2.0 , SiKi )     ! Reference Height (m) ( Z(1) + GridHeight / 2.0 ) !This is the vertical center of the grid
>       WRITE (UBFFW)  REAL( 100.0*TI(1)                            , SiKi )     ! Longitudinal turbulence intensity (%)
>       WRITE (UBFFW)  REAL( 100.0*TI(2)                            , SiKi )     ! Lateral turbulence intensity (%)
>       WRITE (UBFFW)  REAL( 100.0*TI(3)                            , SiKi )     ! Vertical turbulence intensity (%)

The code always produce the Blade-Style file (.wnd) with the improved von karman model(4).  if I use the Kaiman Model, In the Bladed, the the second parameter need to be changed  to 7 and not 4,and the header description will be different. 
And I have no help document of  the Bladed-Style Wind flie(.wnd) about the data format. Can you share that with me ? I mean that If I use the 7(KaimanModel),the code may need to be changed  for  perfect Bladed interface. 

Ruiliang.Wang

**Comment by bjonkman** [comment]
The header information in the Bladed-style .wnd files is informational only. The model information stored there cannot completely reflect what was used in TurbSim (because it allows different models that Bladed does), and I chose to always use the improved von Karman model identifier in the files so that I could store the turbulence intensity information in the binary files. This header information DOES NOT affect the values stored in the file, which are what matter when importing the wind files into Bladed.

**Comment by RuiliangWang** [comment]
I get your point. but I have a question , if I use the  Turbsim to get the Bladed-Style wind file, In the Bladed show below
![image](https://user-images.githubusercontent.com/37888164/65474187-7bd86b00-dead-11e9-9d4b-37cecf558ec2.png)
If I use the 4 ( improved von kaiman)，In the Bladed ,I can not change the turbulence value. I want to recompile the file to get the kaimal model(7 maybe), the header information maybe changed.But I do not know the header information format with kaiman,I think kaimal is different with the von kaiman in header information.
Could you provide the header information format with Kaimal model?

**Comment by bjonkman** [comment]
I'm not sure I understand the problem. It looks like you _have_ changed the turbulence value from what was generated in TurbSim. The red text is just warning you that it isn't using the value it was generated with (which is always something you should keep in mind!). _It's not actually preventing you from changing the values_. The reason that the improved von Karman model is the only one that gives this warning is that Bladed doesn't store the turbulence values for the other generated wind.

Here's a copy of the wind file format, but you don't need to modify TurbSim. In fact, this document tells you that the turbulence data is informational only: [Bladed wind file format.pdf](https://github.com/OpenFAST/openfast/files/3644874/Bladed.wind.file.format_with_Mann.pdf)

Also, I really don't recommend changing the mean wind speed on the files generated from TurbSim. The standard deviation (turbulence intensity) can be scaled after generating the wind file while keeping the integrity of the underlying mathematical equations, but changing the mean wind speed affects the coherence equations in a completely different, non-linear way.

**Comment by RuiliangWang** [comment]
I do not change the mean wind ,I just want to make the Ti(U), Ti(V), Ti(W)  to be free and I can change the value freely without warnning.

**Comment by bjonkman** [comment]
Okay. The screen shot you show has the mean wind speed changed from 3 m/s (what was simulated) to 11.96 m/s (what it is being used in Bladed). And please keep in mind that just because you don't have a warning message does not make the modifications any more valid. It just means that Bladed doesn't have enough information to warn you about it.

**Comment by RuiliangWang** [comment]
Thank you very much.
