### ISSUE TITLE
Regression Test with Visual Studio

### ISSUE THREAD

**Issue by 1fr9** [OpenFAST/openfast#335]
Hi everyone,

first of all I am complete new on github, so please forgive me if I make some mistakes. 

Windows x64
Visual Studio 2015 Community
Intel Parallel Studio XE 2017
Python 3.7

I try to run the regression test with Visual Studio 2015 using the documentation (https://openfast.readthedocs.io/en/dev/source/testing/regression_test_windows.html) but some tests fail.
![image](https://user-images.githubusercontent.com/55579768/65314261-432b4f80-db96-11e9-8f39-fac078b0e658.png)
After some research I tried to plot the results according to #260 but none of them passed. 

Any hints or possible solutions for my problem?

Thank you.

**Comment by rafmudaf** [comment]
If none of the tests pass when you try to plot, its likely you don't have `numpy` or `matplotlib` installed. As for the failing cases without plotting, the manual regression test script does not execute the linearization cases (any with `Linear` in the name) so they are marked as failing.

This is a documentation bug but it has been updated in my fork and will be included in the main OpenFAST repo soon.

**Comment by manmathan299** [comment]
Hi, I am complete new on github so please ignore mistakes 
after with unsuccessful attempt of openfast install in windows with cmake and cygwin
64

I managed to install OpenFAST with Visual Studio using Windows 10. Then I´ve been trying to compile the regression test following the OpenFast documentation, but when I make the target to regression test I´m getting this error message:
![regression](https://user-images.githubusercontent.com/37687398/65632285-e943e300-dff6-11e9-8c66-a5ebd9fb8d6d.JPG)
how can i rectify this

**Comment by rafmudaf** [comment]
As mentioned in the comment above, make sure that you have the proper dependencies. In this case, you don't have `numpy` installed. The required packages are listed in the docs here: https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#dependencies.

**Comment by manmathan299** [comment]
how can i install numpy...as of now

**Comment by manmathan299** [comment]
hai i have fixed the issue (installed numpy)....the regression test shows the following results
![regtest](https://user-images.githubusercontent.com/37687398/65638236-4e053a80-e003-11e9-8499-0d1abb4a3071.JPG)
how can i make the other tests to pass....but i am using ITI Barge (test22) got passed so i can proceed further

**Comment by manmathan299** [comment]
However, When I try to generate plots using the command you provided  

> python3 manualRegressionTest.py ..\build\openfast_x64_Double.exe Windows Intel 1e-5 -n -p

 FOR ISSUE 260# simply fails and I Got the following errors
![plotfail](https://user-images.githubusercontent.com/37687398/65639179-3af36a00-e005-11e9-835c-08ba4b697d98.JPG)


 no plots are generated. i am using python 3.7 with installed matplotlib

**Comment by manmathan299** [comment]
how can i rectify this,,,,kindly help me

**Comment by rafmudaf** [comment]
@manmathan299 run a single case with the verbose flag on to try to get some more information regarding your error. This is all driven through Python so you should get a descriptive error message to guide you in searching the internet for a solution.

Here's the command to run a single test case with the verbose flag:
```
python3 manualRegressionTest.py ..\build\openfast_x64_Double.exe Windows Intel 1e-5 -n -p -v -case AWT_YFix_WSt
```
