### ISSUE TITLE
Compiling issue - libopenfastcpplib.so: undefined reference to `H5P_CLS_DATASET_CREATE_ID_g'

### ISSUE THREAD

**Issue by rachaelesmith** [OpenFAST/openfast#340]
Hi there,

I hope someone can help. I am receiving the following error compiling OpenFAST (with CPP_API on) on a Unix after executing the 'make' command.

[ 99%] Built target openfast
[ 99%] Built target openfastcpplib
Linking CXX executable openfastcpp
CMakeFiles/openfastcpp.dir/src/FAST_Prog.cpp.o: In function `readInputFile(fast::fastInputs&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double*)':
FAST_Prog.cpp:(.text+0x252d): undefined reference to `YAML::LoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/openfastcpp.dir/src/FAST_Prog.cpp.o: In function `YAML::Node::Scalar[abi:cxx11]() const':
FAST_Prog.cpp:(.text._ZNK4YAML4Node6ScalarB5cxx11Ev[_ZNK4YAML4Node6ScalarB5cxx11Ev]+0x31): undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]()'
CMakeFiles/openfastcpp.dir/src/FAST_Prog.cpp.o: In function `YAML::Node YAML::Node::operator[]<char [8]>(char const (&) [8])':
FAST_Prog.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x6b0): undefined reference to `YAML::detail::node_data::set_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/openfastcpp.dir/src/FAST_Prog.cpp.o: In function `YAML::Node YAML::Node::operator[]<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
FAST_Prog.cpp:(.text._ZN4YAML4NodeixINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEES0_RKT_[_ZN4YAML4NodeixINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEES0_RKT_]+0x630): undefined reference to `YAML::detail::node_data::set_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libopenfastcpplib.so: undefined reference to `H5P_CLS_DATASET_CREATE_ID_g'
collect2: error: ld returned 1 exit status
make[2]: *** [glue-codes/openfast-cpp/openfastcpp] Error 1
make[1]: *** [glue-codes/openfast-cpp/CMakeFiles/openfastcpp.dir/all] Error 2
make: *** [all] Error 2

Any advice? I am using cmake 2.8.12.2, gcc 7.2.0 and gmake 3.82, and I installed hdf5, yaml-cpp and lapack according to the script fast-install.sh

Thanks,
Rachael

**Comment by gantech** [comment]
Which HDF5 library are you using? Can you paste the output from your cmake command?

**Comment by rachaelesmith** [comment]
Please see below. I tried to set HDF5_ROOT:PATH=$openfastdir/install as in the fast-build-cpp.sh script but it ignored it for some reason.

-- The CXX compiler identification is GNU 7.2.0
-- The C compiler identification is GNU 7.2.0
-- The Fortran compiler identification is GNU
-- Check for working CXX compiler: /usr/local/gcc/7.2.0/bin/c++
-- Check for working CXX compiler: /usr/local/gcc/7.2.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/local/gcc/7.2.0/bin/gcc
-- Check for working C compiler: /usr/local/gcc/7.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working Fortran compiler: /usr/local/gcc/7.2.0/bin/gfortran
-- Check for working Fortran compiler: /usr/local/gcc/7.2.0/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/gcc/7.2.0/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/gcc/7.2.0/bin/gfortran supports Fortran 90 -- yes
CMake Warning at cmake/OpenfastFortranOptions.cmake:53 (message):
  A version of GNU GFortran greater than 4.6.0 is required but CMake could
  not detect your GFortran version.
Call Stack (most recent call first):
  CMakeLists.txt:45 (set_fast_fortran)


-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Setting system file as: src/SysGnuLinux.f90
-- Found MPI_C: /usr/lib64/openmpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/lib64/openmpi/lib/libmpi_cxx.so;/usr/lib64/openmpi/lib/libmpi.so  
-- Found MPI_Fortran: /usr/lib64/openmpi/lib/libmpi_usempi.so;/usr/lib64/openmpi/lib/libmpi_mpifh.so;/usr/lib64/openmpi/lib/libmpi.so  
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.1") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found HDF5: /usr/lib64/libhdf5.so;/usr/lib64/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/usr/lib64/libhdf5_hl.so;/usr/lib64/libhdf5.so  
-- Found YAMLCPP: /home/links/rs495/OpenFAST/install/include  
-- Configuring done
CMake Warning at glue-codes/openfast-cpp/CMakeLists.txt:47 (add_executable):
  Cannot generate a safe runtime search path for target openfastcpp because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libhdf5.so.8] in /usr/lib64 may be hidden by files in:
      /usr/lib64/openmpi/lib
    runtime library [libhdf5_hl.so.8] in /usr/lib64 may be hidden by files in:
      /usr/lib64/openmpi/lib

  Some of these libraries may not be found correctly.


-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    HDF5_ROOT


-- Build files have been written to: /home/links/rs495/OpenFAST/build

**Comment by rafmudaf** [comment]
I think your given `HDF5_ROOT` is incorrect, but it looks like CMake did find HDF5:
```
-- Found HDF5: /usr/lib64/libhdf5.so;/usr/lib64/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/usr/lib64/libhdf5_hl.so;/usr/lib64/libhdf5.so
```
The `HDF5_ROOT` variable should point to the installation location for that library, probably `/usr/lib64/`. But like I said, CMake is able to find it any way.

@gantech do you think there's a difference in hdf5 api in the library included with openmpi?

**Comment by gantech** [comment]
@rachaelesmith  Can you do `echo $openfastdir/install` before you run `cmake`.

@rafmudaf Yes. The version of HDF5 does matter.

**Comment by andrew-platt** [comment]
Closing this issue since there hasn't been any further discussion.  @rachaelesmith, please reopen if you run into further issues.
