### ISSUE TITLE
No CMAKE_Fortran_COMPILER could be found.

### ISSUE THREAD

**Issue by gbhn100** [OpenFAST/openfast#343]
Hi there.

I am trying to use openfast on mac for my university dissertation but I have no experience at all trying to set anything like this up. I have followed the instructions as best I can and installed the relevant software but I have ran into an error. When in Cmake and I hit configure it comes up with the error:

 The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:18 (project):
  No CMAKE_Fortran_COMPILER could be found.

Configuring incomplete, errors occurred!
See also "/Users/ethan/Desktop/openfast-master/build/CMakeFiles/CMakeOutput.log".
See also "/Users/ethan/Desktop/openfast-master/build/CMakeFiles/CMakeError.log".

Any help/ advice would be greatly appreciated, Thanks.

**Comment by rafmudaf** [comment]
Can you verify that you have a Fortran compiler installed?

**Comment by gbhn100** [comment]
I believe I initially installed gFortran but when that didn't work I installed intel parallel studio Fortran

**Comment by rafmudaf** [comment]
On a Mac, you can install gfortran easily with [Homebrew](https://brew.sh).

In any case, you need to figure out which Fortran compiler you have installed. You can try these bash commands:
```
# Intel Fortran
which ifort

# Gfortran version 9 from homebrew
which gfortran

# Gfortran version 8 from homebrew
which gfortran-8

# Gfortran version 7 from homebrew
which gfortran-7
```

If any of those return a path to a compiler, choose one and then do this:
```
export FC=<path to a Fortran compiler>

# Then in the same terminal window move into the OpenFAST build directory
cmake ..
```

If those `which` commands don't point to a compiler, you either don't have one installed or its not on your path.

**Comment by rafmudaf** [comment]
Take the brackets out...

```
ethans-MBP:~ ethan$ export FC=/usr/local/bin/ifort
```

**Comment by gbhn100** [comment]
When I enter that nothing happens. Also I don't really understand what you said to do after that. sorry I'm very new to doing anything like this

**Comment by rafmudaf** [comment]
Ah ok. You shouldn't see anything happen after the line above, but it sets an environment variable which will be used by CMake. A nuance here is that you're setting the environment variable for your current terminal instance, so if you close the terminal window you lose that environment variable.

Do these commands in a freshly opened terminal:
```
# set the FC variable - nothing will show after this
export FC=/usr/local/bin/ifort

# make sure its set - the command should return the path you've set above
echo $FC

# move into your openfast folder
cd ~/Desktop/openfast-master/build/

# Run CMake
rm CMakeCache.txt
cmake ..
# in the command above, CMake does lots of things including searching for your Fortran compiler. Since you've set the environment variable FC, you've hinted to CMake where to find the compiler. FC means Fortran Compiler. For C projects, you would set CC. For C++, you would set CXX.

# Compile and install
make -j8 install
```

**Comment by gbhn100** [comment]
When I type in those commands this is what comes up:

Last login: Tue Oct  8 22:59:55 on ttys000
ethans-MBP:~ ethan$ export FC=/usr/local/bin/ifort
ethans-MBP:~ ethan$ echo $FC
/usr/local/bin/ifort
ethans-MBP:~ ethan$ cd ~/Desktop/openfast-master/build/
ethans-MBP:build ethan$ rm CMakeCache.txt
ethans-MBP:build ethan$ make -j8 install
make: *** No rule to make target `install'.  Stop.

**Comment by rafmudaf** [comment]
You left out `cmake ..`! :) Its subtle

**Comment by rafmudaf** [comment]
@gbhn100 let me know if you have any more trouble with this.

**Comment by gbhn100** [comment]
when i add the cmake . . this happens:

oa-edu-172-153:~ ethan$ export FC=/usr/local/bin/ifort
oa-edu-172-153:~ ethan$ echo $FC
/usr/local/bin/ifort
oa-edu-172-153:~ ethan$ cd ~/Desktop/openfast-master/build/
oa-edu-172-153:build ethan$ rm CMakeCache.txt
oa-edu-172-153:build ethan$ cmake ..
-bash: cmake: command not found
oa-edu-172-153:build ethan$ make -j8 install
make: *** No rule to make target `install'.  Stop.

**Comment by rafmudaf** [comment]
@gbhn100 Are you on the same computer? Your command line prompt changed from `ethans-MBP:~ ethan$` to `oa-edu-172-153:~ ethan$`, so just be sure you are on the computer you expect to be on.

In any case, the error message bash gave you is letting you know that it can't find the `cmake` command. How did you work with CMake the first time?

**Comment by gbhn100** [comment]
yes, I am still on the computer. I was at the uni before and connected to their wifi if that would have changed it. I'm home now and it has changed back but I still get the same message:

ethans-MBP:~ ethan$ export FC=/usr/local/bin/ifort
ethans-MBP:~ ethan$ cd ~/Desktop/openfast-master/build/
ethans-MBP:build ethan$ rm CMakeCache.txt
ethans-MBP:build ethan$ cmake ..
-bash: cmake: command not found
ethans-MBP:build ethan$ make -j8 install
make: *** No rule to make target `install'.  Stop.

I have been opening the application, clicking browse source and selecting the openfast folder then clicking configure

**Comment by rafmudaf** [comment]
Are you running the CMake GUI? If so, you can install the command line version with ```brew install cmake``` and then run the commands as I listed above.

Otherwise, you'll have to understand better what the source directory is and what configure means. If you do, then you can absolutely substitute `cmake ..` with the corresponding commands in the CMake GUI.

**Comment by gbhn100** [comment]
ah, thank you. I went and installed cmake through homebrew then when I ran it everything worked. my only problem now is I can't figure out how to open openfast

**Comment by gbhn100** [comment]
so I found the openfast executable but I don't understand what you mean by in a terminal, go into your case directory where you have a .fst file

**Comment by rafmudaf** [comment]
Sounds like using a command line environment may be new to you so here's an intro article on that: https://www.makeuseof.com/tag/beginners-guide-mac-terminal/. I hope that answers some of your questions and gives you some background into using a computer this way.
