### ISSUE TITLE
Can't Compile Discon.sln

### ISSUE THREAD

**Issue by unverozkol** [OpenFAST/openfast#345]
**Bug description**
I am using a Windows-10 based PC with MSVS-19.  I am newbee in both OpenFast and Git.  
So Following every thing step by step stated in the openfast Doc's, I have come so far upto 5.2.3.
But I can't not build Discon.sln 

It seems like not finding some of the files necessary, but I am assuming that I cloned the entire openfast project folder from GITHUB.  Obviously I am missing a very fundamental  key piece of information which I am not aware of.  

Followings are some info on my Microsoft Visual Studio-19 setup, and my output.
Thanks for the suggestions that may come up in advance.
Regards
Unver Ozkol

**MSVS-19 info**
**********************************************
Microsoft Visual Studio Community 2019
Version 16.2.5
VisualStudio.16.Release/16.2.5+29306.81
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA310
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.2.292.25104
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.2.292.25104
Azure App Service Tools v3.0.0

C# Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.2.19178.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Intel® Advisor 2019 Update 5   602216
Intel® Advisor 2019 Update 5, (build 602216), Copyright © 2009-2019 Intel Corporation. All rights reserved.

Intel® Inspector 2019 Update 5   602103
Intel® Inspector 2019 Update 5, (build 602103), Copyright © 2009-2019 Intel Corporation. All rights reserved.

Intel® Parallel Studio XE 2019 Update 5 Composer Edition for C++ Windows*   Package ID: w_comp_lib_2019.5.281
Intel® Parallel Studio XE 2019 Update 5 Composer Edition for C++ Windows* Integration for Microsoft* Visual Studio* 2019, Version 19.0.6.16, Copyright © 2002-2019 Intel Corporation. All rights reserved.
* Other names and brands may be claimed as the property of others.

Intel® Parallel Studio XE 2019 Update 5 Composer Edition for Fortran Windows*   Package ID: w_comp_lib_2019.5.281
Intel® Parallel Studio XE 2019 Update 5 Composer Edition for Fortran Windows* Integration for Microsoft Visual Studio* 2019, Version 19.0.0052.16, Copyright © 2002-2019 Intel Corporation. All rights reserved.
* Other names and brands may be claimed as the property of others.

Intel® VTune™ Amplifier 2019 Update 6   602217
Intel® VTune™ Amplifier 2019 Update 6, (build 602217),  Copyright © 2009-2019 Intel Corporation. All rights reserved.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20626.2

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.2.19178.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.2.19178.1
Conda support for Python projects.

Python - Django support   16.2.19178.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.2.19178.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.2.19178.1
Profiling support for Python projects.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.10627.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Output of the "Discon.sln" building process is as follows:**
********************************************
1>------ Rebuild All started: Project: Discon, Configuration: Release x64 ------
2>------ Rebuild All started: Project: Discon_ITIBarge, Configuration: Release x64 ------
3>------ Rebuild All started: Project: Discon_OC3Hywind, Configuration: Release x64 ------
1>Deleting intermediate files and output files for project 'Discon', configuration 'Release|x64'.
2>Deleting intermediate files and output files for project 'Discon_ITIBarge', configuration 'Release|x64'.
3>Deleting intermediate files and output files for project 'Discon_OC3Hywind', configuration 'Release|x64'.
1>Compiling with Intel(R) Visual Fortran Compiler 19.0.5.281 [Intel(R) 64]...
2>Compiling with Intel(R) Visual Fortran Compiler 19.0.5.281 [Intel(R) 64]...
2>DISCON_ITIBarge.F90
1>DISCON.F90
3>Compiling with Intel(R) Visual Fortran Compiler 19.0.5.281 [Intel(R) 64]...
3>DISCON_OC3Hywind.F90
1>fpp: fatal: can't fopen file: C:\FAST\OpenFAST\reg_tests\r-test\glue-codes\openfast\5MW_Baseline\ServoData\DISCON\DISCON.F90
3>fpp: fatal: can't fopen file: C:\FAST\OpenFAST\reg_tests\r-test\glue-codes\openfast\5MW_Baseline\ServoData\DISCON_OC3\DISCON_OC3Hywind.F90
3>Discon_OC3Hywind : error PRJ0019: A tool returned an error code1>Discon : error PRJ0019: A tool returned an error code

1>Build log written to  "file://C:\FAST\OpenFAST\vs-build\Discon\Discon\x64\Release\BuildLog.htm"
3>Build log written to  "file://C:\FAST\OpenFAST\vs-build\Discon\Discon_OC3Hywind\x64\Release\BuildLog.htm"
3>Discon_OC3Hywind - 1 error(s), 0 warning(s)
1>Discon - 1 error(s), 0 warning(s)
2>fpp: fatal: can't fopen file: C:\FAST\OpenFAST\reg_tests\r-test\glue-codes\openfast\5MW_Baseline\ServoData\DISCON_ITI\DISCON_ITIBarge.F90
2>Discon_ITIBarge : error PRJ0019: A tool returned an error code
2>Build log written to  "file://C:\FAST\OpenFAST\vs-build\Discon\Discon_ITIBarge\x64\Release\BuildLog.htm"
2>Discon_ITIBarge - 1 error(s), 0 warning(s)
========== Rebuild All: 0 succeeded, 3 failed, 0 skipped ==========

**OpenFAST Version**
** This is How I build FAST.sln**
******************************************
1>------ Rebuild All started: Project: FAST_Registry, Configuration: Release x64 ------
1>data.c
1>gen_c_types.c
1>gen_module_files.c
1>C:\FAST\OpenFAST\modules-local\openfast-registry\src\gen_module_files.c(2370,19): warning C4267:  '=': conversion from 'size_t' to 'int', possible loss of data
1>misc.c
1>my_strtok.c
1>registry.c
1>reg_parse.c
1>C:\FAST\OpenFAST\modules-local\openfast-registry\src\gen_module_files.c(2382,24): warning C4267:  '=': conversion from 'size_t' to 'int', possible loss of data
1>sym.c
1>symtab_gen.c
1>type.c
1>C:\FAST\OpenFAST\modules-local\openfast-registry\src\reg_parse.c(272,7): warning C4102:  'normal': unreferenced label
1>C:\FAST\OpenFAST\modules-local\openfast-registry\src\type.c(187,1): warning C4267:  'initializing': conversion from 'size_t' to 'int', possible loss of data
1>Generating code
1>Previous IPDB not found, fall back to full compilation.
1>All 74 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>FAST_Registry.vcxproj -> C:\FAST\OpenFAST\vs-build\Registry\..\..\build\bin\Registry.exe
1>Done building project "FAST_Registry.vcxproj".
2>------ Rebuild All started: Project: MAP_dll, Configuration: Release x64 ------
2>Performing Custom Build Tools
2>======================================================================
2>
2>----- FAST Registry --------------
2>----------------------------------------------------------
2>input file: ..\..\modules-ext\map\src\MAP_Registry.txt
2>opening ..\..\modules-local\nwtc-library\src/Registry_NWTC_Library.txt
2>generating ..\..\build\types-files/MAP_Types.f90
2>CUSTOMBUILD : Registry warning : derived data type Ver of type progdesc is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type PtFairDisplacement of type meshtype is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type ptFairleadLoad of type meshtype is not passed through C interface
2>
2>Registry for MAP completed.
2> 
2>======================================================================
2>bstraux.c
2>C:\FAST\OpenFAST\modules-ext\map\src\bstring\bstraux.c(1004,26): warning C4267:  'function': conversion from 'size_t' to 'int', possible loss of data
2>bstrlib.c
2>C:\FAST\OpenFAST\modules-ext\map\src\bstring\bstraux.c(1017,13): warning C4267:  '=': conversion from 'size_t' to 'int', possible loss of data
2>dpmpar.c
2>enorm.c
2>enorm_u.c
2>lmder.c
2>lmpar.c
2>qrfac.c
2>qrsolv.c
2>freedata.c
2>jacobian.c
2>lineroutines.c
2>mapapi.c
2>maperror.c
2>mapinit.c
2>numeric.c
2>outputstream.c
2>residual.c
2>simclist.c
2>C:\FAST\OpenFAST\modules-ext\map\src\bstring\bstrlib.c(367,32): warning C4267:  'function': conversion from 'size_t' to 'int', possible loss of data
2>lmroutines.cc
2>   Creating library ..\..\build\bin\MAP_x64.lib and object ..\..\build\bin\MAP_x64.exp
2>Generating code
2>Previous IPDB not found, fall back to full compilation.
2>All 293 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
2>Finished generating code
2>MAP_dll.vcxproj -> C:\FAST\OpenFAST\vs-build\MAPlib\..\..\build\bin\MAP_x64.dll
2>Done building project "MAP_dll.vcxproj".
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========
**************************************************************************************************

**OpenFAST Version**
Cloned on October 2 2019 from Git repository as described in online OpenFAST Doc. chapter 4.1.
*****************************************************
**System Information **
 
 - OS: Windows-10-Enterprise
- 64 bit OS.

**Comment by rafmudaf** [comment]
In the output you've included above, this line is the important one:
```
3>fpp: fatal: can't fopen file: C:\FAST\OpenFAST\reg_tests\r-test\glue-codes\openfast\5MW_Baseline\ServoData\DISCON_OC3\DISCON_OC3Hywind.F90
```

Does that file exist?

**Comment by unverozkol** [comment]
That was my hunch as well.  No it does not exist.  And I don't know how to make it exist, since I assumed I downloaded everthing by cloning.

**Comment by rafmudaf** [comment]
This is really a lack of proper documentation, but I've been working on improving that. There's a subtle note [here](https://openfast.readthedocs.io/en/master/source/testing/index.html#configuring-the-test-suite).

In any case, you should move into your OpenFAST directory and run this command:
```
git submodule update --init
```

**Comment by unverozkol** [comment]
Dear Rafael;
When I run that command, I get fatal errors as follows.  Should I erase the stuff in the "reg_tests" folder first?

unverozkol@unverozkol-A1 MINGW64 /c/fast/openfast (master)
$ git submodule update --init
fatal: destination path 'C:/FAST/OpenFAST/reg_tests/r-test' already exists and is not an empty directory.
fatal: clone of 'https://github.com/openfast/r-test.git' into submodule path 'C:/FAST/OpenFAST/reg_tests/r-test' failed
Failed to clone 'reg_tests/r-test'. Retry scheduled
fatal: destination path 'C:/FAST/OpenFAST/reg_tests/r-test' already exists and is not an empty directory.
fatal: clone of 'https://github.com/openfast/r-test.git' into submodule path 'C:/FAST/OpenFAST/reg_tests/r-test' failed
Failed to clone 'reg_tests/r-test' a second time, aborting

**Comment by rafmudaf** [comment]
Yes, that's right. Though I wonder what's in that folder.

To reset the submodule, do this:
```
git submodule deinit reg_tests/r-test
git submodule init reg_tests/r-test
git submodule update
```

**Comment by unverozkol** [comment]
Dear Rafael;
The "ServoData" folder whose location is shown below is empty .
C:\FAST\OpenFAST\reg_tests\r-test\glue-codes\openfast\5MW_Baseline\ServoData

I applied these three commands and the last one has ended as;
**
unverozkol@unverozkol-A1 MINGW64 /c/fast/openfast (master)
$ git submodule update
Cloning into 'C:/FAST/OpenFAST/reg_tests/r-test'...
Submodule path 'reg_tests/r-test': checked out '63491ff684f79886e4cd16a5ee15f5fff803de55'
Submodule path 'unit_tests/pfunit': checked out 'a192e82246b44e701446811a9792a530e4f250c7'
**
And NOW "Discon.sln" compiles and the "ServoData" folder is populated . 
Thanks four your support.

**Comment by rafmudaf** [comment]
Great! Maybe you lost internet connection or otherwise interrupted the download when the submodule was cloned the first time? I don't know why the ServoData directory would exist but be empty. In any case, good to hear you've gotten past it.
