### ISSUE TITLE
Can't generate openfast_x64.exe

### ISSUE THREAD

**Issue by unverozkol** [OpenFAST/openfast#346]
**Bug description**
Having successfully building "discon.sln" as described in online document 5.2.3->(2)
I tried to build "fast.sln" as described in online document 5.2.3->(3).  It builds with no errors, only some warnings.  But there is no "openfast_x64.exe" file is produced in the "..build/bin" folder or anywhere else.  I have repeated this couple of times by closing/opening MSVS-19.  But no avail.

**My system**
Windows 10 Enterprise, 64bit
running MSVS-19 with INTEL parallel studio XE 2019

**Here is the output of Fast.sln building process **
1>------ Build started: Project: FAST_Registry, Configuration: Release_Double x64 ------
1>data.c
1>gen_c_types.c
1>gen_module_files.c
1>C:\FAST\OpenFAST\modules-local\openfast-registry\src\gen_module_files.c(2370,19): warning C4267:  '=': conversion from 'size_t' to 'int', possible loss of data
1>misc.c
1>my_strtok.c
1>registry.c
1>reg_parse.c
1>C:\FAST\OpenFAST\modules-local\openfast-registry\src\gen_module_files.c(2382,24): warning C4267:  '=': conversion from 'size_t' to 'int', possible loss of data
1>sym.c
1>symtab_gen.c
1>type.c
1>C:\FAST\OpenFAST\modules-local\openfast-registry\src\reg_parse.c(272,7): warning C4102:  'normal': unreferenced label
1>C:\FAST\OpenFAST\modules-local\openfast-registry\src\type.c(187,1): warning C4267:  'initializing': conversion from 'size_t' to 'int', possible loss of data
1>Generating code
1>Previous IPDB not found, fall back to full compilation.
1>All 74 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>FAST_Registry.vcxproj -> C:\FAST\OpenFAST\vs-build\Registry\..\..\build\bin\Registry.exe
1>Done building project "FAST_Registry.vcxproj".
2>------ Build started: Project: MAP_dll, Configuration: Release_Double x64 ------
2>Performing Custom Build Tools
2>======================================================================
2>
2>----- FAST Registry --------------
2>----------------------------------------------------------
2>input file: ..\..\modules-ext\map\src\MAP_Registry.txt
2>opening ..\..\modules-local\nwtc-library\src/Registry_NWTC_Library.txt
2>generating ..\..\build\types-files/MAP_Types.f90
2>CUSTOMBUILD : Registry warning : derived data type Ver of type progdesc is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type PtFairDisplacement of type meshtype is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type ptFairleadLoad of type meshtype is not passed through C interface
2>
2>Registry for MAP completed.
2> 
2>======================================================================
2>bstraux.c
2>C:\FAST\OpenFAST\modules-ext\map\src\bstring\bstraux.c(1004,26): warning C4267:  'function': conversion from 'size_t' to 'int', possible loss of data
2>bstrlib.c
2>C:\FAST\OpenFAST\modules-ext\map\src\bstring\bstraux.c(1017,13): warning C4267:  '=': conversion from 'size_t' to 'int', possible loss of data
2>dpmpar.c
2>enorm.c
2>enorm_u.c
2>lmder.c
2>lmpar.c
2>qrfac.c
2>qrsolv.c
2>freedata.c
2>jacobian.c
2>lineroutines.c
2>mapapi.c
2>maperror.c
2>mapinit.c
2>numeric.c
2>outputstream.c
2>residual.c
2>simclist.c
2>C:\FAST\OpenFAST\modules-ext\map\src\bstring\bstrlib.c(367,32): warning C4267:  'function': conversion from 'size_t' to 'int', possible loss of data
2>lmroutines.cc
2>   Creating library ..\..\build\bin\MAP_x64.lib and object ..\..\build\bin\MAP_x64.exp
2>Generating code
2>Previous IPDB not found, fall back to full compilation.
2>All 293 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
2>Finished generating code
2>MAP_dll.vcxproj -> C:\FAST\OpenFAST\vs-build\MAPlib\..\..\build\bin\MAP_x64.dll
2>Done building project "MAP_dll.vcxproj".
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Here is what is inside of BUILD/BIN directory**
![build_bin](https://user-images.githubusercontent.com/44326944/66425487-78e68a00-ea18-11e9-8a8b-d29b613db026.png)

As seen there is no "openfast_x64.exe".  Any clues, why?

 **OpenFAST Version**
OpenFAST is cloned from GIT at the end of sept 2019

**Comment by bjonkman** [comment]
It looks like you maybe told it to build only the "MAP_dll" project with its dependencies and not the entire solution file (which contains several more projects). Try selecting `Build -> Build Solution` instead.

**Comment by unverozkol** [comment]
Dear Bonnie;
This is how I exactly done it.  Build --> Build Solution.
if it helps, here is how my project configuration looks like:  there is FAST_Registry and MAP_dll
Am I missing some files in my project?  If so, How could I get them from git?

![config_man](https://user-images.githubusercontent.com/44326944/66431567-df71a500-ea24-11e9-81b9-8e3da8c25bfd.png)

**Comment by bjonkman** [comment]
Your solution file should also show `FAST` and `FAST_Lib` projects. 
- Do the `<openfast>\vs-build\FAST\FAST.vfproj` and `<openfast>\vs-build\FASTlib\FASTlib.vfproj` files exist?
- Does it show that Fortran is available in Visual Studio? There should be some indication of the version of Intel Fortran you've installed in the `Help->About Microsoft Visual Studio` window. If not, try to install Intel Fortran _after_ installing Visual Studio.
- Are the project files showing that they are unavailable (like `FAST_Lib` in the screenshot below)? If so, right click on the project file in the Solution Explorer window and select `Reload project`. 

`FAST` and `FAST_Lib` should appear in the Solution Explorer window with source files the way `FAST` appears in the screen shot below. (You probably won't have "Advisor Results" in your solution file like I do, but that is fine.)

![image](https://user-images.githubusercontent.com/6108781/66448737-c3afd400-ea0f-11e9-8ef5-8ec7bd1eaacc.png)

**Comment by unverozkol** [comment]
Dear Bonnie, 
Your third suggestion does the trick.  When I open Fast.sln, for some reason Source files were not loaded.  When I Reload Project, they appeared now.  Thanks alot.

**Comment by kumaraeedara** [comment]
In the configuration manager Platform of "FAST_Registry" always remain as Win32 even when x64 is chosen for Active Solution Platform. Allows to change manually though. Any particular reason?

![ConfigurationManager](https://user-images.githubusercontent.com/20492734/77245567-7f269680-6c45-11ea-988e-d31b1a6027ef.jpg)

**Comment by andrew-platt** [comment]
The `FAST_Registy` is used to generate the `_Types.f90` files which are then compiled into OpenFAST.  The code created by the `FAST_Registry.exe` is the same regardless of which memory addressing is used.  So for simplicity we set it to 32 bit.

**Comment by kumaraeedara** [comment]
Ok.. Thanks.
