### ISSUE TITLE
Seg fault with GFortran 9

### ISSUE THREAD

**Issue by pjstanle** [OpenFAST/openfast#347]
Hello!

I'm trying to get OpenFAST running. I have cloned, installed, and tested with the following code from the documentation:

![image](https://user-images.githubusercontent.com/15972217/66687949-d578bd80-ec41-11e9-89a8-d932cdef5f17.png)

However, I get the following failures when performing the regression tests:

![image](https://user-images.githubusercontent.com/15972217/66692109-838f6200-ec58-11e9-9735-20dad0f48d27.png)
![image](https://user-images.githubusercontent.com/15972217/66692120-943fd800-ec58-11e9-83f6-3ce4dd079c4f.png)

When I run a verbose test, I find that the issue (I think) is a segmentation fault regarding a .log file. 

![image](https://user-images.githubusercontent.com/15972217/66688080-4fa94200-ec42-11e9-8e5f-40896948e77b.png)

I have checked, and the .log file exists at the indicated path, but it is blank (not sure if this is a problem). I tried updated my gcc compiler, and have experienced the same issue. Are there any thoughts on how to solve this problem? 

Thanks in advance for any solutions

**Comment by rafmudaf** [comment]
What is your system information?

**System Information (please complete the following information):**
 
 - OS: [e.g. Ubuntu 14.04 or macOS 10.12]
 - Compiler: [e.g. GFortran 4.4]
 - Compiler settings: [e.g. CMake flags or other settings]

**Comment by pjstanle** [comment]
OS: macOS 10.11.6
Compiler: GNU Fortran (Homebrew GCC 9.2.0_1) 9.2.0
Compiler settings: -DBUILD_TESTING=ON

**Comment by rafmudaf** [comment]
@pjstanle this is indeed a bug! However, its only a problem with the highest level of compiler optimization (`-O3`) on the GNU Fortran compiler versions 8+. I've made a fix and pushed it to my fork: [the fix](https://github.com/rafmudaf/openfast/tree/bugfix/ad14_optimization_segfault). After more testing, I'll issue a pull request to bring this to the `dev` branch.

In the meantime, you could take my changes and incorporate them into your repository or compiler with a lower optimization level. To do that, use CMake:
```
cmake .. -DCMAKE_BUILD_TYPE=RELWITHDEBINFO
make install
```

**Comment by rafmudaf** [comment]
This CMake build type uses `-O2` optimization rather than `-O3`.

**Comment by rafmudaf** [comment]
@pjstanle the fix for this has been merged into the `dev` branch. Comment again here if you still run into problems.
