### ISSUE TITLE
Problem with visual studio 2015 and Openfast installing

### ISSUE THREAD

**Issue by salicto** [OpenFAST/openfast#354]
Hello,

I apologize in advance if my question seems pointless or repetitive. I am new in the use of visual studio and openFast. I followed the OpenFast doc of 4.6.1 and 4.6.2. .However, next to the two directories Fastlib and Fast, the mention "incompatible" is mentioned with the phrase "This project is incompatible with the current edition ..." I have read many reports on GitHub masi I can not find the solution. Thank you for your help
![76612155_504303180297690_2039252447825756160_n](https://user-images.githubusercontent.com/57439956/68292765-d52ae100-008c-11ea-947a-63e181fddef3.png)

**Comment by bjonkman** [comment]
It looks like you do not have the Intel Fortran compiler installed. It needs to be installed _after_ you install Visual Studio.

**Comment by salicto** [comment]
I'm sorry a little late but thank you for your answer. I had the same feeling about compiling fortran but I was not sure.
