### ISSUE TITLE
OpenFAST exe files

### ISSUE THREAD

**Issue by PeterV310** [OpenFAST/openfast#361]
Downloaded OpenFAST v2.2.0 from github but cannot locate the OpenFAST x64 exe file.
Where can I find this please since for now I only need to run the tests .. no compiling.

Thanks

**Comment by rafmudaf** [comment]
They aren't available yet, but should be ready within the next few days. In the meantime, the v2.1.0 binaries are available.

**Comment by PeterV310** [comment]
Downloaded the v2.1.0 zip file .. How can I access the exe files now please .. I'm new to the use of OpenFAST ..

**Comment by PeterV310** [comment]
Sorted that one .. But when runnign oen of the tests .. now I am recieveing an error libifcoremd.dll not found ..

**Comment by jjonkman** [comment]
Dear @PeterV310,

The question on how to resolve an error regarding libifcoremd.dll has been answered here: https://github.com/OpenFAST/openfast/issues/352.

Best regards,

**Comment by PeterV310** [comment]
Thanks. Copied DLL files to the loc of the executable file/s and works now.
