### ISSUE TITLE
BeamDyn does not work

### ISSUE THREAD

**Issue by kkartal88** [OpenFAST/openfast#362]
Hi, I am trying to run OpenFast with BeamDyn, but it does not work. I tried different values for "Order of interpolation", change the calculation time steps, removed the prebend, but nothing helped. With ElastoDyn the system is running. I hope someone can help me.

I attached some files and the error.

![bug1](https://user-images.githubusercontent.com/57793057/68937776-52e1a180-079d-11ea-8312-40d288ae5b49.png)
![bug2](https://user-images.githubusercontent.com/57793057/68937804-5ffe9080-079d-11ea-841a-4a04d81aa3d4.png)
[WT004_AeroDyn15.txt](https://github.com/OpenFAST/openfast/files/3851075/WT004_AeroDyn15.txt)
[WT004_AeroDyn15_blade.txt](https://github.com/OpenFAST/openfast/files/3851076/WT004_AeroDyn15_blade.txt)
[WT004_BeamDyn.txt](https://github.com/OpenFAST/openfast/files/3851084/WT004_BeamDyn.txt)

Info:
OpenFAST-v2.1.0-130-g2d9230df-dirty
Compile Info:
 - Architecture: 64 bit
 - Precision: double
- OS: Windows 10

**Comment by andrew-platt** [comment]
Hi @kkartal88 ,

Sorry to hear you are having difficulties with BeamDyn.  To help with troubleshooting, could you attach the BeamDyn blade properties file (`WT004_BeamDyn_Blade2.dat` listed in your `WT004_BeamDyn.dat` file)?

Also, we released a new version of OpenFAST last week that includes some bug fixes.  Could you try with that version?

**Comment by kkartal88** [comment]
Hi thank you for your help. I changed some values and it is running, see attached. Is my understanding right, the local center of mass is defined as the distance from the local point (kp_xr, kp_yr)

After 24 hours it has only simulated 50 seconds. Is this normal? Is there no way to reduce it to one or two hours for 600 seconds? 
PS, it is only running when i set DT to minimal 0.0001s. 

[WT004.zip](https://github.com/OpenFAST/openfast/files/3855382/WT004.zip)

**Comment by andrew-platt** [comment]
In the input file, the keypoint line is used to describe the overall shape of the blade, not the elastic or mass centers.  The keypoint line must be a smooth function, preferably a 3rd order polynomial for BeamDyn to work well.  The keypoint line in your input file is not a third order polynomial, so BeamDyn cannot adequately match it using the shape functions used in the calculations.  The result of this is a distortion of the blade compared to what you are expecting, and this can introduce high frequency content that must be resolved using very small timesteps.

![WT004_BeamDyn-KP](https://user-images.githubusercontent.com/2745453/69069320-8281eb00-09e3-11ea-9e89-06e777483041.png)

The offset of the mass and stiffness centers from the keypoint line is done within the 6x6 matrices (see documentation here: https://openfast.readthedocs.io/en/dev/source/user/beamdyn/input_files.html).

**BeamDyn calculations**
When BeamDyn reads in the keypoint line, it fits it with a cubic spline curve.  This curve is then used to set the locations of the GLL nodes used in the FE calculations.  The shape functions are then set by the GLL nodes and used for all calculations.

**Comment by JelmerPolman** [comment]
Hi Andrew,

just to clarify my understanding, is the 'attempted shape function' reconstructed with the langranian interpolants based on the GLL nodes?

Best regards,
Jelmer Polman

**Comment by andrew-platt** [comment]
Hi Jelmer,

- 'attempted shape function' was a poor choice of wording on my part.  This is the lagrangian shape functions reconstructed from the GLL nodes.
- The 'cubic spline fit' is a piecewise cubic spline with intervals between keypoints.  At the keypoints, the value, first and second derivatives are continuous.  The current implementation of the cubic spline sets the second derivative at the first and last segments to zero (we are changing this to the not-a-knot condition as is used in MATLAB's spline function as it yields a better result for most blade curvatures I've seen).

Regards,
Andy

**Comment by JelmerPolman** [comment]
Hi Andrew,


Thank yo for the quick response. 

I too had a lot of problems with the "BD_DynamicSolutionGA2:Solution does not converge after
 the maximum number of iterations" error, but didn't find the spline fit to be the source of the problem. I will open an seperate topic with my simulations and trouble shooting. 


Best regards,
Jelmer Polman
