### ISSUE TITLE
Input file error for the WP Tests

### ISSUE THREAD

**Issue by PeterV310** [OpenFAST/openfast#364]
Need to update the path for the WP tests due to error: OpenFInpFile:The input file, "pitch.ipt", was not found.

Trying to locate the call for this input file but cannot find it. In which file is it please?

**Comment by jjonkman** [comment]
Dear @PeterV310 ,

The Pitch.ipt file is called directly from Craig Hansen's old pitch controller, PitchCntrl_ACH.f90, which is used in the WindPACT 1.5-MW baseline turbine r-test simulations, but PitchCntrl_ACH.f90 is more of an example than an officially supported NREL-supplied routine.

FYI: It is difficult to support questions on PitchCntrl_ACH.f90 now that Craig Hansen has retired. The only documentation of PitchCntrl_ACH.f90 that I'm aware of is in Appendix E of the WindPACT Rotor Design Study Report: http://www.nrel.gov/docs/fy06osti/32495.pdf.

Best regards,

**Comment by PeterV310** [comment]
Cannot find the file PitchCntrl_ACH.f90 file in my openFAST directories ..

Or should I comment out the ref to this file? and if so how?

**Comment by PeterV310** [comment]
Tried to update the f90 code but did not manage .. will try later .. Thanks

**Comment by jjonkman** [comment]
Dear @PeterV310,

The PitchCntrl_ACH.f90 source file is located in the ServoDyn directory.  You can find it here: https://github.com/OpenFAST/openfast/tree/master/modules/servodyn/src.

 You can prevent OpenFAST from calling this routine by changing PCMode in ServoDyn different from PCMode = 3.  Of course, if you do that, you should then introduce an alternative pitch controller for this turbine.

Best regards,

**Comment by bjonkman** [comment]
You can find the `pitch.ipt` input file here: https://github.com/OpenFAST/r-test/blob/master/glue-codes/openfast/WP_VSP_ECD/pitch.ipt

**Comment by PeterV310** [comment]
Thanks Bonnie. We can close this one.
