### ISSUE TITLE
Semi-Submersible 8 MW WT

### ISSUE THREAD

**Issue by PeterV310** [OpenFAST/openfast#365]
I need to simulate an offshore semi-submersible 8 MW (LEANWIND project WT) as a base case  (aerodynamic and hydrodynamic) following which I would then need to load the platform with turbomachinary equipment and run the simulations again to compare.

What would be a typical workflow for this? Do I start working on the "5MW_OC4Semi_WSt_WavesWN" input file?

Thanks

**Comment by jjonkman** [comment]
Dear @PeterV310,

If you don't already have an OpenFAST model that matches the configuration you need to simulate, then yes, I would recommend starting with a model from the r-test that best matches your configuration.  For a floating semisubmersible, the r-test you identified is the closest.  You'll need to update the aerodynamic, hydrodynamic, control, and structural properties to match that of your 8-MW LEANWIND turbine.  Of course, this will likely take some effort.

As you're assembling the model, I would run verification cases to ensure that the model is set up properly, e.g., checking that the mass and center of masses are what you expect, verifying that the natural frequencies are what you expect, ensuring that the power curve is what you expect, ensuring the floating platform is in equilibrium in the absence of wind and wave forcing, ensuring that the floating platform is hydrostatically stable, etc.

Best regards,

**Comment by PeterV310** [comment]
Thanks for the guidance. Will work on it. Probabbly I would need some assistance on individual areas as I move forward.

**Comment by rafmudaf** [comment]
@PeterV310 Comment here again if you'd like to reopen this issue.
