### ISSUE TITLE
ManualRegressionTest python script does not produce plots on Windows

### ISSUE THREAD

**Issue by bjonkman** [OpenFAST/openfast#369]
**Bug Description**
Python gives a traceback error when attempting to generate plots.

**To Reproduce**
1. Clear the `build/reg_tests` folder
2. Run `reg_tests/ManualRegressionTest.py` with the `-p` flag
3. Python produces this error:
```
Traceback (most recent call last):
  File "executeOpenfastRegressionCase.py", line 181, in <module>
    finalizePlotDirectory(localOutFile, testInfo["attribute_names"], caseName)
  File ".\lib\errorPlotting.py", line 184, in finalizePlotDirectory
    with open(_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '..\\build\\reg_tests\\glue-codes\\openfast\\<CASE>\\plots\\Time_div.txt'
```
and no plots are generated (even though all the cases failed)

**Screenshots, if applicable**
![image](https://user-images.githubusercontent.com/6108781/70638699-9261a900-1bf6-11ea-84bd-93b6e5affb97.png)

**OpenFAST Version**
This problem was introduced in https://github.com/OpenFAST/openfast/pull/330

**System Information (please complete the following information):**
 - OS: Windows 
 - Python: v3.8 and 3.7.1

**Comment by rafmudaf** [comment]
@rhammond2

**Comment by rafmudaf** [comment]
@bjonkman can you verify that the cases finished without error here? As in, did they generate a `.outb`?

**Comment by rafmudaf** [comment]
and also you have to additionally install the Python package Bokeh 1.4.0

**Comment by bjonkman** [comment]
Thanks, @rafmudaf. It appears the missing Bokeh package was causing the issue. It now generates plots. 

In future versions, it would be nice not to have this warning printed hundreds of times ;-) 
```
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
```
