### ISSUE TITLE
Regression Test, some cases always FAILS

### ISSUE THREAD

**Issue by thufuxu** [OpenFAST/openfast#375]
generally following the instructions @ https://openfast.readthedocs.io/en/master/source/testing/regression_test_windows.html#regression-test-windows and also git the latest "dev" branch

good to do the compiling of the DLLs, but when running the “Regression Test”, there were always "FAILS" to some cases, anyone can provide a clue to fix them? Can a tool list with the versions used to be shared to build a same environment? Thanks. 

![Picture1](https://user-images.githubusercontent.com/57276683/71145610-3a2b3800-21f0-11ea-85a0-5e9a01f3c923.png)

**Comment by rafmudaf** [comment]
Hello @thufuxu - the libraries and compilers along with their versions are documented in the r-test repo: https://github.com/OpenFAST/r-test/tree/master#baselines. However, hardware differences can also cause the tests to fail. I suggest that you generate the plots with the Python reg test driver as documented here: https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#executing-with-python-driver. Use the `-p -n` flags to avoid running the cases but generating the plots. This will create a html file at `openfast/build/reg_tests/glue-codes/openfast/regression_tests_summary.html`.

Also be sure to install the dependencies with `pip`:
```
pip install numpy bokeh
```

**Comment by thufuxu** [comment]
thanks @rafmudaf 

I tried couple more times and strictly following the software tool requirement, except hardware... unfortunately, can't get all the cases "PASS".

**Comment by rafmudaf** [comment]
It will be very difficult to align your system and hardware with the ones used at NREL so that all of your test cases pass. Instead, plot the errors and verify that there's nothing significantly different.
