### ISSUE TITLE
compile problem on Ubuntu 

### ISSUE THREAD

**Issue by hjoke** [OpenFAST/openfast#376]
f951: out of memory allocating 59323336 bytes after a total of 167628800 bytes
glue-codes/openfast/CMakeFiles/openfast.dir/build.make:62: recipe for target 'glue-codes/openfast/CMakeFiles/openfast.dir/src/FAST_Prog.f90.o' failed
make[2]: *** [glue-codes/openfast/CMakeFiles/openfast.dir/src/FAST_Prog.f90.o] Error 1
CMakeFiles/Makefile2:2064: recipe for target 'glue-codes/openfast/CMakeFiles/openfast.dir/all' failed
make[1]: *** [glue-codes/openfast/CMakeFiles/openfast.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rafmudaf** [comment]
Please include the information requested in the issue template:

```
**Bug description**
<A clear and concise description of the bug.>

**To Reproduce**
<Update the following list with your specific information.>
Steps to reproduce the behavior:
1. Compile with '...'
2. Run '...' case with '...' settings
3. Open '...' output
4. See the error

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots, if applicable**
<Add screenshots to help explain your problem.>

**OpenFAST Version**
<Please provide as much detail as possible including git commit. The best information is a screenshot of the OpenFAST system description that prints when running OpenFAST:>

**System Information (please complete the following information):**
 - OS: <e.g. Ubuntu 14.04 or macOS 10.12>
 - Compiler: <e.g. GFortran 4.4>
 - Compiler settings: <e.g. CMake flags or other settings>

**Additional context**
<Add any other context about the problem here.>
```
