### ISSUE TITLE
Questions regarding C++ API

### ISSUE THREAD

**Issue by Leifheitstandard** [OpenFAST/openfast#380]
Hi,

I am currently trying to find an open source beam program in order to realize a coupling with a CFD code developed at my university. I was therefore hoping to use the C++ API to couple our CFD code and FAST / the Beamdyn module.

Looking at the example given in "FAST_Prog.cpp" and trying to understand the related source code has left me with the following:
 
- an object of type fast::OpenFAST is created, which reads in an input file, starts the simulation, makes certain data from the FAST simulation accessible, enables specification of certain data from "outside", enables to some extent control of the simulation from "outside"

Looking at cDriver_Input_from_FAST and cDriver_Output_to_FAST and the underlying structs, it seems that the current implementation only allows to specify Velocities in the FAST simulation, while Forces, Coordinates, etc can be extracted.

Is this true ?

For the intended coupling, it would be necessary to extract node positions from FAST and input forces from outside; the coupled code is supposed to calculate the forces on the blade of the turbine while FAST / Beamdyn delivers the resulting deformations.

I hope this is the right place for such questions, if not feel free to delete / close the issue!

Best Regards

**Comment by gantech** [comment]
@Leifheitstandard You are correct. The current C++ API only allows coupling to a CFD in actuator mode to provide inflow conditions and extract forces and positions from OpenFAST.

We are currently developing an interface in OpenFAST to couple to a blade-resolved CFD code. However, it might be a while before that is merged into the OpenFAST code base.
