### ISSUE TITLE
No explicit error message when VTK surfaces are requested without airfoil coordinates

### ISSUE THREAD

**Issue by ebranlard** [OpenFAST/openfast#382]
**Bug description**
OpenFAST aborts with no explicit error message when VTK surfaces are requested without airfoil coordinates being provided in airfoil files. 

**To Reproduce**
Set `VTK_type=1` and `WrVTK=1` for a simulation where no airfoil coordinates are provided in all or one of the airfoil files. 

**Expected behavior**
Explicit error message provided.

**Comment by bjonkman** [comment]
Hmmm... I get the error message "Cannot do surface visualization without airfoil coordinates defined in AeroDyn" (this is running the code from #373) :
![image](https://user-images.githubusercontent.com/6108781/72541691-37981e80-3840-11ea-98fc-3869d964cad5.png)

**Comment by ebranlard** [comment]
It might be due to some warning message that took priority or filled the error message buffer. Here's what I get:


![image](https://user-images.githubusercontent.com/1318316/72546457-07547e00-3848-11ea-9167-37e7a8fc3325.png)

**Comment by bjonkman** [comment]
Yes, it looks like the error message just got too large for this model with all those mesh-mapping messages. I put a little work-around in my linearization pull request to print informational messages a bit early so that error messages after the mesh-mapping informational messages get printed, too.

**Comment by ebranlard** [comment]
Thanks that does the trick!
