### ISSUE TITLE
Issue with building OpenFast on Ubuntu 18.04 using CMake

### ISSUE THREAD

**Issue by rhaghi** [OpenFAST/openfast#383]
Hello,

I am new to compiling Fortran and C on my machine. I followed the same steps that you explained [here](https://openfast.readthedocs.io/en/master/source/install/#cmake-with-make-for-linux-macos). However, while building OpenFast, I faced with some errors. All the errors seem to say the same: `Warning: __builtin_memset: specified size 18446744073709551598 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]`, but the `ErrMsg` is different. I uploaded screenshots from my terminal. My machine OS is Ubuntu 18.04 running on IntelCore i7-2600 CPU with 16GB ram. The `cmake` version on my machine is 3.10.2, `gcc` version is  7.4.0, and `make` version is 4.1.

I am not sure if you can reproduce the error as it might be my machine specific. However, to reproduce the error run the following on a Linux machine terminal (this is mainly a copy-paste from the installation instruction page):

1. git clone https://github.com/OpenFAST/OpenFAST.git
2. cd OpenFAST
3. mkdir build
4. cd build
5. cmake ..
6. make

Thanks a lot for the help. 
![Screenshot from 2020-01-21 14-46-07](https://user-images.githubusercontent.com/46800756/72850004-eb444880-3c5c-11ea-9b12-24aac330cde7.png)
![Screenshot from 2020-01-21 14-44-34](https://user-images.githubusercontent.com/46800756/72850032-fdbe8200-3c5c-11ea-970e-e75ee0df2fc9.png)
![Screenshot from 2020-01-21 14-45-03](https://user-images.githubusercontent.com/46800756/72850044-031bcc80-3c5d-11ea-98af-14168512363b.png)
![Screenshot from 2020-01-21 14-45-33](https://user-images.githubusercontent.com/46800756/72850066-1038bb80-3c5d-11ea-89c6-742134c36bdf.png)

**Comment by andrew-platt** [comment]
Thanks for the bug report.  This is a known error that can be safely ignored.

You will notice that this only occurs on string manipulations involving `ErrMsg`.  In these cases, we are truncating a string and prepending a few characters or words.  The newly created string can't actually exceed the allocated size, so it isn't actually an issue to worry about.  We simply haven't gotten around to modifying the logic to make that cleaner.

**Comment by rhaghi** [comment]
Thanks a lot @andrew-platt :)

**Comment by rafmudaf** [comment]
Its also only a thing on GCC 7  ¯\_(ツ)_/¯
