### ISSUE TITLE
Installation and testing Question

### ISSUE THREAD

**Issue by CallumG-Ed** [OpenFAST/openfast#384]
Hi users and developers,

I'm new to Linux and OpenFAST and I'm experiencing some issues with installation and testing. I require OpenFAST for my PhD research to couple with SOWFA. At present I'm trying to install on my HPC running ubuntu 18.04.

From a clean install of ubuntu 18.04 the steps I have followed are:

1) sudo apt update

2) sudo apt upgrade

3) sudo apt install gcc gfortran cmake libblas-dev liblapack-dev libxml2-dev libhdf5-serial-dev libyaml-cpp-dev

4) mkdir OpenFAST && cd OpenFAST

5) git clone --recursive https://github.com/OpenFAST/openfast.git

6) cd openfast/

7) git checkout dev

8) git submodule update

9) mkdir build install && cd build

10) cmake .. -DBUILD_TESTING=ON

11) make install

12) ctest

The results of ctest are:

Test project /home/<user>/OpenFAST/openfast/build
      Start  1: AWT_YFix_WSt
 1/37 Test  #1: AWT_YFix_WSt .............................***Failed    0.07 sec
      Start  2: AWT_WSt_StartUp_HighSpShutDown
 2/37 Test  #2: AWT_WSt_StartUp_HighSpShutDown ...........***Failed    0.07 sec
      Start  3: AWT_YFree_WSt
 3/37 Test  #3: AWT_YFree_WSt ............................***Failed    0.07 sec
      Start  4: AWT_YFree_WTurb
 4/37 Test  #4: AWT_YFree_WTurb ..........................***Failed    0.07 sec
      Start  5: AWT_WSt_StartUpShutDown
 5/37 Test  #5: AWT_WSt_StartUpShutDown ..................***Failed    0.07 sec
      Start  6: AOC_WSt
 6/37 Test  #6: AOC_WSt ..................................***Failed    0.07 sec
      Start  7: AOC_YFree_WTurb
 7/37 Test  #7: AOC_YFree_WTurb ..........................***Failed    0.07 sec
      Start  8: AOC_YFix_WSt
 8/37 Test  #8: AOC_YFix_WSt .............................***Failed    0.07 sec
      Start  9: UAE_Dnwind_YRamp_WSt
 9/37 Test  #9: UAE_Dnwind_YRamp_WSt .....................***Failed    0.07 sec
      Start 10: UAE_Upwind_Rigid_WRamp_PwrCurve
10/37 Test #10: UAE_Upwind_Rigid_WRamp_PwrCurve ..........***Failed    0.07 sec
      Start 11: WP_VSP_WTurb_PitchFail
11/37 Test #11: WP_VSP_WTurb_PitchFail ...................***Failed    0.07 sec
      Start 12: WP_VSP_ECD
12/37 Test #12: WP_VSP_ECD ...............................***Failed    0.08 sec
      Start 13: WP_VSP_WTurb
13/37 Test #13: WP_VSP_WTurb .............................***Failed    0.07 sec
      Start 14: SWRT_YFree_VS_EDG01
14/37 Test #14: SWRT_YFree_VS_EDG01 ......................***Failed    0.07 sec
      Start 15: SWRT_YFree_VS_EDC01
15/37 Test #15: SWRT_YFree_VS_EDC01 ......................***Failed    0.08 sec
      Start 16: SWRT_YFree_VS_WTurb
16/37 Test #16: SWRT_YFree_VS_WTurb ......................***Failed    0.08 sec
      Start 17: 5MW_Land_DLL_WTurb
17/37 Test #17: 5MW_Land_DLL_WTurb .......................***Failed    0.08 sec
      Start 18: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr
18/37 Test #18: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr ...........***Failed    0.07 sec
      Start 19: 5MW_OC3Trpd_DLL_WSt_WavesReg
19/37 Test #19: 5MW_OC3Trpd_DLL_WSt_WavesReg .............***Failed    0.08 sec
      Start 20: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth
20/37 Test #20: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth ...***Failed    0.08 sec
      Start 21: 5MW_ITIBarge_DLL_WTurb_WavesIrr
21/37 Test #21: 5MW_ITIBarge_DLL_WTurb_WavesIrr ..........***Failed    0.07 sec
      Start 22: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti
22/37 Test #22: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti ....***Failed    0.07 sec
      Start 23: 5MW_OC3Spar_DLL_WTurb_WavesIrr
23/37 Test #23: 5MW_OC3Spar_DLL_WTurb_WavesIrr ...........***Failed    0.07 sec
      Start 24: 5MW_OC4Semi_WSt_WavesWN
24/37 Test #24: 5MW_OC4Semi_WSt_WavesWN ..................***Failed    0.07 sec
      Start 25: 5MW_Land_BD_DLL_WTurb
25/37 Test #25: 5MW_Land_BD_DLL_WTurb ....................***Failed    0.07 sec
      Start 26: WP_Stationary_Linear
26/37 Test #26: WP_Stationary_Linear .....................***Failed    0.07 sec
      Start 27: Ideal_Beam_Fixed_Free_Linear
27/37 Test #27: Ideal_Beam_Fixed_Free_Linear .............***Failed    0.08 sec
      Start 28: Ideal_Beam_Free_Free_Linear
28/37 Test #28: Ideal_Beam_Free_Free_Linear ..............***Failed    0.08 sec
      Start 29: 5MW_Land_BD_Linear
29/37 Test #29: 5MW_Land_BD_Linear .......................***Failed    0.08 sec
      Start 30: bd_5MW_dynamic
30/37 Test #30: bd_5MW_dynamic ...........................***Failed    0.07 sec
      Start 31: bd_5MW_dynamic_gravity_Az00
31/37 Test #31: bd_5MW_dynamic_gravity_Az00 ..............***Failed    0.07 sec
      Start 32: bd_5MW_dynamic_gravity_Az90
32/37 Test #32: bd_5MW_dynamic_gravity_Az90 ..............***Failed    0.07 sec
      Start 33: bd_curved_beam
33/37 Test #33: bd_curved_beam ...........................***Failed    0.07 sec
      Start 34: bd_isotropic_rollup
34/37 Test #34: bd_isotropic_rollup ......................***Failed    0.08 sec
      Start 35: bd_static_cantilever_beam
35/37 Test #35: bd_static_cantilever_beam ................***Failed    0.07 sec
      Start 36: bd_static_twisted_with_k1
36/37 Test #36: bd_static_twisted_with_k1 ................***Failed    0.07 sec
      Start 37: beamdyn_utest
37/37 Test #37: beamdyn_utest ............................   Passed    0.00 sec

3% tests passed, 36 tests failed out of 37

Label Time Summary:
aerodyn14    =   0.51 sec*proc (7 tests)
aerodyn15    =   1.41 sec*proc (19 tests)
beamdyn      =   0.84 sec*proc (11 tests)
dynamic      =   0.22 sec*proc (3 tests)
elastodyn    =   1.85 sec*proc (25 tests)
hydrodyn     =   0.52 sec*proc (7 tests)
linear       =   0.31 sec*proc (4 tests)
map          =   0.22 sec*proc (3 tests)
moordyn      =   0.07 sec*proc (1 test)
openfast     =   2.16 sec*proc (29 tests)
servodyn     =   1.93 sec*proc (26 tests)
static       =   0.30 sec*proc (4 tests)
subdyn       =   0.23 sec*proc (3 tests)

Total Test time (real) =   2.70 sec

The following tests FAILED:
	  1 - AWT_YFix_WSt (Failed)
	  2 - AWT_WSt_StartUp_HighSpShutDown (Failed)
	  3 - AWT_YFree_WSt (Failed)
	  4 - AWT_YFree_WTurb (Failed)
	  5 - AWT_WSt_StartUpShutDown (Failed)
	  6 - AOC_WSt (Failed)
	  7 - AOC_YFree_WTurb (Failed)
	  8 - AOC_YFix_WSt (Failed)
	  9 - UAE_Dnwind_YRamp_WSt (Failed)
	 10 - UAE_Upwind_Rigid_WRamp_PwrCurve (Failed)
	 11 - WP_VSP_WTurb_PitchFail (Failed)
	 12 - WP_VSP_ECD (Failed)
	 13 - WP_VSP_WTurb (Failed)
	 14 - SWRT_YFree_VS_EDG01 (Failed)
	 15 - SWRT_YFree_VS_EDC01 (Failed)
	 16 - SWRT_YFree_VS_WTurb (Failed)
	 17 - 5MW_Land_DLL_WTurb (Failed)
	 18 - 5MW_OC3Mnpl_DLL_WTurb_WavesIrr (Failed)
	 19 - 5MW_OC3Trpd_DLL_WSt_WavesReg (Failed)
	 20 - 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth (Failed)
	 21 - 5MW_ITIBarge_DLL_WTurb_WavesIrr (Failed)
	 22 - 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti (Failed)
	 23 - 5MW_OC3Spar_DLL_WTurb_WavesIrr (Failed)
	 24 - 5MW_OC4Semi_WSt_WavesWN (Failed)
	 25 - 5MW_Land_BD_DLL_WTurb (Failed)
	 26 - WP_Stationary_Linear (Failed)
	 27 - Ideal_Beam_Fixed_Free_Linear (Failed)
	 28 - Ideal_Beam_Free_Free_Linear (Failed)
	 29 - 5MW_Land_BD_Linear (Failed)
	 30 - bd_5MW_dynamic (Failed)
	 31 - bd_5MW_dynamic_gravity_Az00 (Failed)
	 32 - bd_5MW_dynamic_gravity_Az90 (Failed)
	 33 - bd_curved_beam (Failed)
	 34 - bd_isotropic_rollup (Failed)
	 35 - bd_static_cantilever_beam (Failed)
	 36 - bd_static_twisted_with_k1 (Failed)
Errors while running CTest

I'd appreciate some support on the reason for the failed tests?

Cheers,
Callum

**Comment by rafmudaf** [comment]
Failing with such a short execution time, its likely that these cases didn't run. Possible reasons for that are that the executable isn't compiled correctly or permissions are incorrect.

I recommend you do a couple of things to get more information:
1. Look at the log file from a test case; for example, at ```openfast/build/reg_tests/glue-codes/openfast/AWT_YFix_WSt/AWT_YFix_WSt.log```
2. Run a single test case in verbose mode: ```ctest -VV -R AWT_YFix_WSt```

Also, what happens when you try to run the executable manually?

**Comment by CallumG-Ed** [comment]
Hi rafmudaf,

thanks very much for getting back to me.

1) the file (openfast/build/reg_tests/glue-codes/openfast/AWT_YFix_WSt/AWT_YFix_WSt.log) doesn't exist.
2) this command returned:

ctest -VV -R AWT_YFix_WSt

UpdateCTestConfiguration  from :/home/callum/OpenFAST/openfast/build/DartConfiguration.tcl
Parse Config file:/home/callum/OpenFAST/openfast/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/callum/OpenFAST/openfast/build/DartConfiguration.tcl
Parse Config file:/home/callum/OpenFAST/openfast/build/DartConfiguration.tcl
Test project /home/callum/OpenFAST/openfast/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: AWT_YFix_WSt

1: Test command: /usr/bin/python3 "/home/callum/OpenFAST/openfast/reg_tests/executeOpenfastRegressionCase.py" "AWT_YFix_WSt" "/home/callum/OpenFAST/openfast/build/glue-codes/openfast/openfast" "/home/callum/OpenFAST/openfast/reg_tests/.." "/home/callum/OpenFAST/openfast/build/reg_tests/glue-codes/openfast" "0.00001" "Linux" "GNU"
1: Test timeout computed to be: 5400
1: Traceback (most recent call last):
1:   File "/home/callum/OpenFAST/openfast/reg_tests/executeOpenfastRegressionCase.py", line 34, in <module>
1:     import pass_fail
1:   File "/home/callum/OpenFAST/openfast/reg_tests/lib/pass_fail.py", line 22, in <module>
1:     import numpy as np
1: ModuleNotFoundError: No module named 'numpy'
1/1 Test #1: AWT_YFix_WSt .....................***Failed    0.07 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
aerodyn14    =   0.07 sec*proc (1 test)
elastodyn    =   0.07 sec*proc (1 test)
openfast     =   0.07 sec*proc (1 test)
servodyn     =   0.07 sec*proc (1 test)

Total Test time (real) =   0.07 sec

The following tests FAILED:
	  1 - AWT_YFix_WSt (Failed)
Errors while running CTest

Thanks again for any help.
Callum

**Comment by andrew-platt** [comment]
It looks like you are missing a prerequisite for the regressions tests with python: `ModuleNotFoundError: No module named 'numpy'`.

From the command line, try installing the missing package with `pip3 install numpy matplotlib`.  You may need to install `pip3` first (`sudo apt-get install pip3`).

**Comment by CallumG-Ed** [comment]
Hi Andrew,

thanks very much for the comment, that seems to have sorted it. I'm only getting 4 failed tests now:

ctest -j8
Test project /home/callum/OpenFAST/openfast/build
      Start  1: AWT_YFix_WSt
      Start  2: AWT_WSt_StartUp_HighSpShutDown
      Start  3: AWT_YFree_WSt
      Start  4: AWT_YFree_WTurb
      Start  5: AWT_WSt_StartUpShutDown
      Start  6: AOC_WSt
      Start  7: AOC_YFree_WTurb
      Start  8: AOC_YFix_WSt
 1/37 Test  #1: AWT_YFix_WSt .............................   Passed   16.23 sec
      Start  9: UAE_Dnwind_YRamp_WSt
 2/37 Test  #6: AOC_WSt ..................................   Passed   22.03 sec
      Start 10: UAE_Upwind_Rigid_WRamp_PwrCurve
 3/37 Test  #2: AWT_WSt_StartUp_HighSpShutDown ...........   Passed   30.55 sec
      Start 11: WP_VSP_WTurb_PitchFail
 4/37 Test  #3: AWT_YFree_WSt ............................   Passed   35.85 sec
      Start 12: WP_VSP_ECD
 5/37 Test  #8: AOC_YFix_WSt .............................   Passed   37.15 sec
      Start 13: WP_VSP_WTurb
 6/37 Test  #5: AWT_WSt_StartUpShutDown ..................   Passed   43.96 sec
      Start 14: SWRT_YFree_VS_EDG01
 7/37 Test #11: WP_VSP_WTurb_PitchFail ...................   Passed   28.04 sec
      Start 15: SWRT_YFree_VS_EDC01
 8/37 Test #12: WP_VSP_ECD ...............................   Passed   26.24 sec
      Start 16: SWRT_YFree_VS_WTurb
 9/37 Test #10: UAE_Upwind_Rigid_WRamp_PwrCurve ..........   Passed   59.98 sec
      Start 17: 5MW_Land_DLL_WTurb
10/37 Test  #9: UAE_Dnwind_YRamp_WSt .....................***Failed   97.93 sec
      Start 18: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr
11/37 Test #13: WP_VSP_WTurb .............................   Passed   78.70 sec
      Start 19: 5MW_OC3Trpd_DLL_WSt_WavesReg
12/37 Test  #4: AWT_YFree_WTurb ..........................   Passed  119.06 sec
      Start 20: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth
13/37 Test #19: 5MW_OC3Trpd_DLL_WSt_WavesReg .............***Failed    5.46 sec
      Start 21: 5MW_ITIBarge_DLL_WTurb_WavesIrr
14/37 Test  #7: AOC_YFree_WTurb ..........................   Passed  131.53 sec
      Start 22: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti
15/37 Test #21: 5MW_ITIBarge_DLL_WTurb_WavesIrr ..........   Passed   55.07 sec
      Start 23: 5MW_OC3Spar_DLL_WTurb_WavesIrr
16/37 Test #15: SWRT_YFree_VS_EDC01 ......................   Passed  132.53 sec
      Start 24: 5MW_OC4Semi_WSt_WavesWN
17/37 Test #17: 5MW_Land_DLL_WTurb .......................   Passed  141.64 sec
      Start 25: 5MW_Land_BD_DLL_WTurb
18/37 Test #22: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti ....   Passed  102.83 sec
      Start 26: WP_Stationary_Linear
19/37 Test #26: WP_Stationary_Linear .....................   Passed    1.40 sec
      Start 27: Ideal_Beam_Fixed_Free_Linear
20/37 Test #27: Ideal_Beam_Fixed_Free_Linear .............   Passed    2.20 sec
      Start 28: Ideal_Beam_Free_Free_Linear
21/37 Test #28: Ideal_Beam_Free_Free_Linear ..............   Passed    2.20 sec
      Start 29: 5MW_Land_BD_Linear
22/37 Test #14: SWRT_YFree_VS_EDG01 ......................   Passed  216.11 sec
      Start 30: bd_5MW_dynamic
23/37 Test #23: 5MW_OC3Spar_DLL_WTurb_WavesIrr ...........   Passed   97.00 sec
      Start 31: bd_5MW_dynamic_gravity_Az00
24/37 Test #31: bd_5MW_dynamic_gravity_Az00 ..............   Passed    8.71 sec
      Start 32: bd_5MW_dynamic_gravity_Az90
25/37 Test #32: bd_5MW_dynamic_gravity_Az90 ..............   Passed    8.71 sec
      Start 33: bd_curved_beam
26/37 Test #33: bd_curved_beam ...........................   Passed    0.70 sec
      Start 34: bd_isotropic_rollup
27/37 Test #34: bd_isotropic_rollup ......................   Passed    1.50 sec
      Start 35: bd_static_cantilever_beam
28/37 Test #35: bd_static_cantilever_beam ................   Passed    0.70 sec
      Start 36: bd_static_twisted_with_k1
29/37 Test #36: bd_static_twisted_with_k1 ................   Passed    0.70 sec
      Start 37: beamdyn_utest
30/37 Test #37: beamdyn_utest ............................   Passed    0.70 sec
31/37 Test #30: bd_5MW_dynamic ...........................   Passed   41.92 sec
32/37 Test #29: 5MW_Land_BD_Linear .......................   Passed   68.09 sec
33/37 Test #24: 5MW_OC4Semi_WSt_WavesWN ..................   Passed  182.34 sec
34/37 Test #18: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr ...........   Passed  313.87 sec
35/37 Test #16: SWRT_YFree_VS_WTurb ......................***Failed  396.88 sec
36/37 Test #25: 5MW_Land_BD_DLL_WTurb ....................   Passed  307.02 sec
37/37 Test #20: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth ...***Failed  1472.67 sec

89% tests passed, 4 tests failed out of 37

Label Time Summary:
aerodyn14    = 735.23 sec*proc (7 tests)
aerodyn15    = 3416.82 sec*proc (19 tests)
beamdyn      = 442.47 sec*proc (11 tests)
dynamic      =  59.35 sec*proc (3 tests)
elastodyn    = 3845.03 sec*proc (25 tests)
hydrodyn     = 2229.24 sec*proc (7 tests)
linear       =  73.90 sec*proc (4 tests)
map          = 254.91 sec*proc (3 tests)
moordyn      = 182.34 sec*proc (1 test)
openfast     = 4224.54 sec*proc (29 tests)
servodyn     = 4218.73 sec*proc (26 tests)
static       =   3.61 sec*proc (4 tests)
subdyn       = 1791.99 sec*proc (3 tests)

Total Test time (real) = 1592.43 sec

The following tests FAILED:
	  9 - UAE_Dnwind_YRamp_WSt (Failed)
	 16 - SWRT_YFree_VS_WTurb (Failed)
	 19 - 5MW_OC3Trpd_DLL_WSt_WavesReg (Failed)
	 20 - 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth (Failed)
Errors while running CTest

I'm new to OpenFAST (obviously), what would be the proceedure for checking the 4 failed tests?

Thanks alot for the advice,

Cheers
Callum

**Comment by andrew-platt** [comment]
It is fairly common for those tests cases to appear to fail.  They are more sensitive to numerical roundoff than some of the other cases.  So if you a happen to use a different compiler, or different set of math libraries, or happen to have a different chipset than the baseline was generated on, those particular cases may show enough difference that they get flagged as failing.

Since it will be very difficult to align your system and hardware with the ones used at NREL so that all of your test cases pass. Instead, plot the errors and verify that there's nothing significantly different (you may need to run `ccmake ..` from the build directory and turn on the `CTEST_PLOT_ERRORS` flag).

**Comment by CallumG-Ed** [comment]
That's great, thanks very much for your help Andrew I really appreciate it!

All the best,
Callum
