### ISSUE TITLE
OpenFAST v2.2.0 32-bit version

### ISSUE THREAD

**Issue by RBergua** [OpenFAST/openfast#389]
**Bug description**
It seems that the 32-bit executable released for OpenFAST v2.2.0 is actually a 64-bit version.

**To Reproduce**
By running OpenFAST v2.2.0 in 32-bit (**openfast_Win32.exe**), you can verify:
```
**************************************************************************************************
OpenFAST

Copyright (C)  National Renewable Energy Laboratory
Copyright (C)  Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v2.2.0
Compile Info:
 - Architecture: 64 bit
 - Precision: single
 - Date: Dec 20 2019
 - Time: 15:19:00
```

In addition, OpenFAST will abort if you try to run a controller DLL compiled in 32-bit.

**Additional context**
It can be observed that both files, the 32-bit (openfast_Win32.exe) and the 64-bit single precision (openfast_x64.exe), are the same size (55,838KB). But the 32-bit version is expected to be significantly lighter than the 64-bit version.

**Comment by andrew-platt** [comment]
@rafmudaf can you upload a new one?

**Comment by rafmudaf** [comment]
Yes, I've fixed an issue I had in my script where the 64 bit binary was being copied twice and the new binaries are available in the latest release. Thanks for pointing this out @RBergua!
