### ISSUE TITLE
Blade Node Rotational Velocities Missing in ElastoDyn

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#39]
I thought that we had already included calculations of the rotational velocity of the blade nodes in ElastoDyn, but looking at the code after a user on the forum reported that the terms were missing: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1900, I confirm that the they have not been calculated.  While AeroDyn doesn't need the rotational velocity of the blade nodes, the AeroDyn nodes may be offset from the ElastoDyn nodes, so a rotational velocity of the ElastoDyn nodes should lead to a change in the translational velocity of the AeroDyn nodes through the mesh-mapping routines.  These terms should be included in a future release of ElastoDyn.

The second problem reported in the forum topic linked above only applied to an earlier version of FAST, which has already been fixed.

**Comment by bjonkman** [comment]
@rafmudaf this can be closed now. (fixed in #391 / # 405)
