### ISSUE TITLE
Full-system linearization for FOWTs

### ISSUE THREAD

**Issue by jonmtz** [OpenFAST/openfast#394]
Hi,

I am developing a controller for FOWTs, and I am trying get a full-system linearization in order to be able to adjust the controller parameters.

As far as I have read, currently there exists the possibilty to linearize both HydroDyn and MAP++ modules (apart from the previously linearized modules such as AeroDyn or ElastoDyn).

Nevertheless, using the latest binary from OpenFAST 2.2.0., I receive a message saying that the functionality is not implemented in the current version.

I tried to linearize the FAST Certification Test 24 (setting PCMode and VSContrl to 0 in ServoDyn), and I received the following message:

*******************************************************************************************
OpenFAST-v2.2.0
Compile Info:
 - Architecture: 64 bit
 - Precision: single
 - Date: Dec 20 2019
 - Time: 15:19:00
Execution Info:
 - Date: 02/14/2020
 - Time: 13:08:49+0100

OpenFAST input file heading:
    FAST Certification Test #24: NREL 5.0 MW Baseline Wind Turbine with OC3 Hywind Configuration,
    for use in offshore analysis

FAST_InitializeAll:FAST_Init:ValidateInputData:Linearization is not implemented for the HydroDyn
module.
ValidateInputData:Linearization is not implemented for any of the mooring modules.

 FAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.
*******************************************************************************************
So my questions are:
* Is it possible to perform the linearization for these submodules?
* If so, with which Certification Test (being a FOWT) would it be possible to try it?

Thanks in advance for the help,

Jon

**Comment by jjonkman** [comment]
Dear Jon,

The linearization functionality for floating offshore wind turbines is not included in OpenFAST v2.2.  Instead, it is currently undergoing review and approval before being merged into the dev branch of OpenFAST--see pull request #350.

Best regards,
