### ISSUE TITLE
Compiling OpenFAST in 32bits with Cygwin + CMake

### ISSUE THREAD

**Issue by jonmtz** [OpenFAST/openfast#396]
Dear all,

Until now I have compiled OpenFAST in 64 bit format using Cygwin + CMake, but now I would like to compile the executable for 32 bits.

As I am quite new in compiling, I do not know if this can be managed with the CMakeList.txt file or something similar to that, and I did not find any information in the OpenFAST Documentation.

Any help for doing this with Cygwin + CMake?

Thank you in advance,

Jon

**Comment by andrew-platt** [comment]
I've been following your discussion on #373.  Are you looking to compile in single precision, or double precision with 32 bit?

For single precision, just add the flag `-DDOUBLE_PRECISION=OFF` to the cmake command.

For 32 bit, I believe you will need to point to the 32 bit compiler and associated libraries for BLAS and LAPACK.  @rafmudaf may have more information on how to do this.

**Comment by rafmudaf** [comment]
This is the **one** thing that I know how to do easier on Windows than Linux.
Like @andrew-platt said, I think you'll have to find 32-bit compilers and math libraries for CygWin. If you can get the Intel tools on Windows, it's simply a matter of choosing the right cmd.exe and leaving a few characters out of the CMake command. You could use the 30 day trial for Intel tools.

**Comment by jonmtz** [comment]
Thank you @andrew-platt and @rafmudaf for your answers.

In this case, my intention is to use the 32 bit compiler so I will try to download 32 bit compilers for CygWin, and if I do not find them I will download  the Intel compiler.

Thank you and best regards,

Jon
