### ISSUE TITLE
Wave Excitation model generation in state-space (*.ssexctn input file)

### ISSUE THREAD

**Issue by jonmtz** [OpenFAST/openfast#397]
Hi,

I am using a platform for which I have the .hst, .1 and .3 files. 
My aim is to perform a full-system linearization using #350. As I have seen, for being able to perform the linearization in the HydroDyn Submodule, it is necessary to set both *ExctnMod* and *RdtnMod* to 2 (state-space model).

For the Radiation memory-effect model (*RdtnMod*), I have been able to create the *.ss* file using the SS_Fitting MATLAB Toolbox (https://nwtc.nrel.gov/SS_Fitting), but I was not able to find any toolbox for creating the **.ssexctn* input file.

Between r-tests, I see that the *marin_semi.ssexctn* was created using SS_Excitation_Fitting v1.00.01, but I did not find this toolbox on the net.

Does anyone know how could I get that toolbox, or create the **.ssexctn* file in another way?

Thanks in advance,

Jon

**Comment by andrew-platt** [comment]
@ghaymanNREL do you have any comments?

**Comment by jjonkman** [comment]
Alan Wright of NREL has developed a MATLAB-based preprocessor called SS_Excitation_Fitting--similar to SS_Fitting for fitting state-space wave-radiation models, but for fitting the state-space wave-excitation models.  SS_Excitation_Fitting is not yet ready for general release, but I've asked Alan Wright to respond here as to the status.

**Comment by jonmtz** [comment]
Alright, thank you @andrew-platt and @jjonkman. I will wait for Alan Wright's answer.

On the other hand, @ghaymanNREL, is there any other way to perform linearization of the HydroDyn submodule using a platform without the state-space wave-excitation model?

Thank you and best regards,

Jon

**Comment by jjonkman** [comment]
@jonmtz,

If you don't have a linearized state-space representation of the wave-excitation loads, you can always disable wave excitation loads during the linearization process (ExctnMod = 0), but then the impact of perturbations in wave elevation will not be included in the linearized system (i.e., there will be no B and D matrices associated with a du for perturbations in wave elevation).

Best regards,

**Comment by jonmtz** [comment]
Dear @jjonkman,

I already tried that, but I got the following error when trying to do so.

![Error_linOC4](https://user-images.githubusercontent.com/57631658/75355041-31b94280-58ae-11ea-978e-cc7c0f05ae92.JPG)

That is why in my first message I said that as I have seen, both *ExctnMod* and *RdtnMod* must be 2. Nevertheless, it may happen that the error is due to another cause.

Any ideas?

Thank you in advance,

Jon

**Comment by jjonkman** [comment]
Well, it is hard for me to guess what is causing this problem...and whether it is a problem with your simulation set up or a bug in the source code.  Do you run into the same segmentation fault when you linearize while setting ExctnMod = RdtnMod = 0 with one of the sample models NREL has provided?  I would suggest compiling and running in debug mode to more precisely isolate the problem.

**Comment by alandwright** [comment]
Hi @jonmtz,

We don't have a formal release of the SS_Excitation_Fitting which is why you haven't found it on the github repository. I can work with you one-on-one to send the alpha version to you and help you through it to generate the *.ssexctn files you need for a complete linearization. Please email me at Alan.Wright@nrel.gov. Thanks.

**Comment by jonmtz** [comment]
Thank you @alandwright, I will contact you at your email.

Best regards,

Jon

**Comment by ramisetti** [comment]
I tried to run linearisation test setting ExctnMod = RdtnMod = 0 for IEA 15MW semisubermisble case but openfast fails with segmentation fault. I repeated this with 5MW OC4 semisubmersible case available within the NREL test cases and I found it fails with similar problem. I used both OpenFast v2.4.0 and pull 537 code to run the above two test cases. Can you please let me know if there is any fix to this problem?

**Comment by jjonkman** [comment]
Dear @ramisetti,

Please find attached a sample HydroDyn input file that is compatible with the HydroDyn changes in pull request #537.

[NRELOffshrBsline5MW_OC4DeepCwindSemi_HydroDyn_New4.txt](https://github.com/OpenFAST/openfast/files/5553801/NRELOffshrBsline5MW_OC4DeepCwindSemi_HydroDyn_New4.txt)

Does upgrading from OpenFAST v2.4 to this branch of OpenFAST resolve the segmentation fault you are reporting?

Best regards,

**Comment by ramisetti** [comment]
Dear @jjonkman,

Thanks for sharing the sample HydroDyn input file. I tried to use it with the 5MW OC4 semi case but I still get initialisation error (see below).
I think I don't have any answer yet to your question about the segmentation fault with the pull 537 version until I succeed running openfast with the appropriate HydroDyn.dat file.

-------
FAST_InitializeAll:HydroDyn_Init:HydroDynInput_GetInput:ReadOutputList: Did not find the required
 number of Potfile strings on the input file line: only found 1.

 FAST encountered an error during module initialization.
  Simulation error level: FATAL ERROR
---------

**Comment by jjonkman** [comment]
Dear @ramisetti,

This error sounds like you've specified 3 potential-flow bodies (NBody = 3), but only specified properties of one of them.  You should set NBody = 1 if you only want one potential-flow body.

Best regards,

**Comment by ramisetti** [comment]
Dear @jjonkman,

I have used the sample HydroDyn.dat file that you shared without making any major changes. Yes NBody was already set 3 and I  think the properties are also specified for thrice. Can you explain little more specific about the properties? What properties do I need to specify?

**Comment by jjonkman** [comment]
Dear @ramisetti,

Well, at least you got past the model initialization errors.  It looks like your model has gone numerically unstable, likely due to something improperly set in the updated HydroDyn file.  Have you transferred all of the inputs from the original OC5 semi linearization test (https://github.com/OpenFAST/r-test/blob/master/glue-codes/openfast/5MW_OC4Semi_Linear/NRELOffshrBsline5MW_OC4DeepCwindSemi_HydroDyn.dat) to the new file format?

Regardless, my understanding is the only reason you are using this branch of OpenFAST is to see if the model seg faults when running a linearization with ExctnMod = RdtnMod = 0.  You could try that now by linearizing right away at time zero (LinTimes = 0).

Best regards,

**Comment by ramisetti** [comment]
Dear @jjonkman,

Yes, indeed I got past the model initialisation errors. I did try to transfer all the inputs from the original OC4 semisubmersible case except the AddF0 and AddCLin matrices because of the difference between two formats. The size of AddF0 and AddCLin is different and it's not very clear how to adapt the new format with the values from the original case. could you please explain why this difference between the original case and new hydrodynamics file?

**Comment by jjonkman** [comment]
Dear @ramisetti,

NBody is the number of potential-flow bodies (historically this was always one; in the new branch, HydroDyn supports more than one body).  The additional preload, stiffness, and damping are now just dimensioned by the number of bodies.  When doing this, we also transposed how AddF0 is entered.  Before it was 1 x 6, now it is 6 x NBody.   See the comments after the variable names.

Best regards,

**Comment by ramisetti** [comment]
Thank you @jjonkman for your help. I am now able to run the linearisation with ExctnMod = RdtnMod = 0 for the IEA 15MW semisubmersible case using the pull 537 code.

Just a comment related to representation of the vectors/matrices used in PLATFORM ADDITIONAL STIFFNESS AND DAMPING section. In my opinion, I think the new representation of AddF0 and other Matrices is not really user-friendly. Instead, I prefer to use the vectors/matrices for NBody in new rows as this will also work with previous openfast versions and it is easy to prepare the HydroDyn.dat file. Hope this is clear.

**Comment by jjonkman** [comment]
Dear @ramisetti,

When extending the platform additional stiffness and damping to work with NBody and NBodyMod, we had to change the dimensions of the matrices and vectors.  In this process, we thought it was confusing that AddF0 was input transposed in prior versions of HydroDyn, unlike the other matrices.  We corrected this in the updated version of HydroDyn.

Best regards,

**Comment by mftatfcyclone** [comment]
> Hi @jonmtz,
> 
> We don't have a formal release of the SS_Excitation_Fitting which is why you haven't found it on the github repository. I can work with you one-on-one to send the alpha version to you and help you through it to generate the *.ssexctn files you need for a complete linearization. Please email me at [Alan.Wright@nrel.gov](mailto:Alan.Wright@nrel.gov). Thanks.

Dear @alandwright 
I need to generate the ssexctn file. Could you help me to generate it for NREL 5MW?

**Comment by jjonkman** [comment]
Dear @mftatfcyclone,

For which floating platform do you want the _*.ssexctn_ file for?

Best regards,

**Comment by mftatfcyclone** [comment]
Dear @jjonkman 
Thanks for your prompt response
I need it for spar platform

**Comment by jjonkman** [comment]
Dear @mftatfcyclone,

Alan Wright just sent me the attached _*.ssexctn_ file for the OC3-Hywind spar that supports the NREL 5-MW baseline wind turbine.  I added a .txt file extension to attach it (rename it to _spar.ssexxctn_ for use with OpenFAST).

[spar.ssexctn.txt](https://github.com/OpenFAST/openfast/files/6879107/spar.ssexctn.txt)

I hope that helps.

Best regards,

**Comment by mftatfcyclone** [comment]
Dear @jjonkman

Thank you very much for your considerations.
But I have a question, Is this state space valid for all wave conditions (operating points) of the spar platform of the 5MW wind turbine?

Best regards,

**Comment by jjonkman** [comment]
Dear @mftatfcyclone,

This model should be valid for any sea state (wave height, period) with zero-degree wave heading; it is not valid for other wave propagation directions.

Best regards,

**Comment by Ian-Ammerman** [comment]
> Alan Wright of NREL has developed a MATLAB-based preprocessor called SS_Excitation_Fitting--similar to SS_Fitting for fitting state-space wave-radiation models, but for fitting the state-space wave-excitation models. SS_Excitation_Fitting is not yet ready for general release, but I've asked Alan Wright to respond here as to the status.

Dear @alandwright  ,

Was this pre-processor developed further? Would you be willing to make it available?

Best,
Ian

**Comment by jjonkman** [comment]
Dear @Ian-Ammerman,

See also the discussion on SS_Excitation_Fitting here: https://github.com/OpenFAST/openfast/discussions/1053.  If you provide your e-mail address, I can send you the alpha release of SS_Excitation_Fitting via WeTransfer.

Best regards,

**Comment by Ian-Ammerman** [comment]
> Dear @Ian-Ammerman,
> 
> See also the discussion on SS_Excitation_Fitting here: #1053. If you provide your e-mail address, I can send you the alpha release of SS_Excitation_Fitting via WeTransfer.
> 
> Best regards,

Dear @jjonkman ,

My email is: ian.ammerman@maine.edu

Best,
Ian

**Comment by jjonkman** [comment]
Dear @Ian-Ammerman,

I've sent you the alpha release of SS_Excitation_Fitting via WeTransfer.

Best regards,

**Comment by Hamedfath** [comment]
Dear @jjonkman, 

Could you please send me SS_Excitation_Fitting for the OC4 semisubmersible platform that supports the NREL 5-MW baseline wind turbine, and its manual for me?

My Email is: hfathnejat@bcamath.org

Best regards,
Hamed

**Comment by jjonkman** [comment]
Dear @Hamedfath,

I've sent you the alpha release of SS_Excitation_Fitting via WeTransfer.

Best regards,

**Comment by jiayaomeng** [comment]
> Dear @Ian-Ammerman,
> 
> See also the discussion on SS_Excitation_Fitting here: #1053. If you provide your e-mail address, I can send you the alpha release of SS_Excitation_Fitting via WeTransfer.
> 
> Best regards,

Dear @jjonkman,

Could I please also ask for the alpha release of SS_Excitation_Fitting, so that I can compare my fitting method with it? Thank you so much! My email: jiayao.meng@wolfson.ox.ac.uk

Best wishes,
Jiayao

**Comment by jiayaomeng** [comment]
> Dear @jiayaomeng,
> 
> I've sent you the alpha release of SS_Excitation_Fitting via WeTransfer.
> 
> Best regards,

Thank you very much, @jjonkman, for always being so helpful!

**Comment by MuhammadSharjil** [comment]
hi @alandwright 
I require the SS_Excitation_Fitting for wave disturbance analysis of OC3-Hywind spar-type wind turbine.
It would be a great support if I can get it.
Thanks

Regards,
Muhammad Sharjil

**Comment by jjonkman** [comment]
Dear @MuhammdSharjil,

I've sent you the alpha release of SS_Excitation_Fitting via WeTransfer.

Best regards,

**Comment by pelotonlopezmuro** [comment]
> Dear [@Ian-Ammerman](https://github.com/Ian-Ammerman),
> 
> See also the discussion on SS_Excitation_Fitting here: [#1053](https://github.com/OpenFAST/openfast/discussions/1053). If you provide your e-mail address, I can send you the alpha release of SS_Excitation_Fitting via WeTransfer.
> 
> Best regards,

Dear @jjonkman, could I also get access to the alpha release of SS_Excitation_Fitting?

juan.lopezmuro@rutgers.edu

Thanks in advance!

**Comment by jjonkman** [comment]
Dear @pelotonlopezmuro ,

I've sent you the alpha release of SS_Excitation_Fitting via WeTransfer.

Best regards,

**Comment by juleshd** [comment]
Dear @jjonkman,

Could you please send me the alpha release of SS_Excitation_Fitting too ? Here is my e-mail address : jules.houot@ensta.fr

Have a great day,

Jules

**Comment by jjonkman** [comment]
Dear @juleshd,

I've sent you the alpha release of SS_Excitation_Fitting via WeTransfer.

Best regards,
