### ISSUE TITLE
OpenFOAM interface updates

### ISSUE THREAD

**Issue by sayerhs** [OpenFAST/openfast#4]
Port updates from https://github.com/gantech/fastv8DriverProgram for the OpenFOAM/Nalu interface to OpenFAST repo. 

@gantech

**Comment by ghaymanNREL** [comment]
Shreyas,  the link below isn’t valid.

**Comment by sayerhs** [comment]
@gantech has the repository as a Private repo, so it will be visible once he gives you access to it.

**Comment by michaelasprague** [comment]
It is for me, but you need to be a  collaborator on that project

**Comment by gantech** [comment]
Ok.. so glad this is up. Will do.

**Comment by michaelasprague** [comment]
@gantech Where are we on this issue?

**Comment by gantech** [comment]
With @sayerhs help, I have ported the updates as of early last week here https://github.com/gantech/OpenFAST/tree/cppLibraryGluecode. It passes 5 tests as in here https://github.com/gantech/fastCPPtests. I'm continuing to make updates to my private repo though to account for changes in the ghosting procedure in Nalu. Once we've selected the final version, I'll port those updates over to OpenFAST. All further development will then be in OpenFAST forks and dev branch.

**Comment by mchurchf** [comment]
Can I also make a picky request.  Can we stop calling this interface the "OpenFOAM" interface.  It is misleading because it is really the interface to any other code that is capable of supplying some sort of inflow and taking the loads and positions.

**Comment by gantech** [comment]
I have selected a ghosting approach going forward... I'm working on cleaning up the interface and porting it over to OpenFAST. I hope to be finished with this by the weekend.

**Comment by gantech** [comment]
I have ported over all updates https://github.com/gantech/fastv8DriverProgram for the OpenFOAM/Nalu interface to OpenFAST repo and submitted a pull request.

**Comment by gantech** [comment]
Could we close this. The pull request related to this has already been merged into dev.
