### ISSUE TITLE
HydroDyn Buoyancy Loads Incorrect 

### ISSUE THREAD

**Issue by senu-sirnivas** [OpenFAST/openfast#406]
I am running openFAST V.2.1.0. The HydroDyn summary file reports the external buoyancy loads incorrectly using Structure Volume instead of the Submerged Volume.

Volume Calculations(m^3)
------------------------
  Structure Volume     :    5.84424E+03
  Submerged Volume     :    3.41120E+03
  Marine Growth Volume :    0.00000E+00
  Ballasted Volume     :    0.00000E+00
              NOTE: Structure, Submerged and Marine Growth volumes are based on members not modelled with WAMIT
                      Ballasted volume is computed from all members which are marked as filled in the HydroDyn input file, regardless of PropPot flag

Buoyancy loads summed about ( 0.0, 0.0, 0.0 )
---------------------------------------------
                                BuoyFxi               BuoyFyi               BuoyFzi               BuoyMxi               BuoyMyi               BuoyMzi 
                                  (N)                   (N)                   (N)                  (N-m)                 (N-m)                 (N-m)  
 External:                  0.000000E+00          0.000000E+00          5.874531E+07          1.914501E+01         -5.221367E+01          0.000000E+00
 Internal:                  0.000000E+00          0.000000E+00          0.000000E+00          0.000000E+00          0.000000E+00          0.000000E+00
 Total   :                  0.000000E+00          0.000000E+00          5.874531E+07          1.914501E+01         -5.221367E+01          0.000000E+00
              NOTE: External buoyancy is based on members not modelled with WAMIT
                      Internal buoyancy is computed from all members which are marked as filled in the HydroDyn input file, regardless of PropPot flag
                    Total buoyancy does not include WAMIT-modelled buoyancy contribution

**Comment by jjonkman** [comment]
I thought this issue (reported in https://github.com/OpenFAST/openfast/issues/202) was fixed by https://github.com/OpenFAST/openfast/pull/214?

@ghaymanNREL -- Can you confirm?

**Comment by andrew-platt** [comment]
Is this related to #310?

**Comment by jjonkman** [comment]
I believe this bug was fixed in OpenFAST v2.6 (https://github.com/OpenFAST/openfast/releases/tag/v2.6.0).
