### ISSUE TITLE
Bug report:  Attempt to fetch from allocatable variable FILLEDGROUPS when it is not allocated

### ISSUE THREAD

**Issue by lapadron** [OpenFAST/openfast#409]
**Bug description**
When running test case #19 (5MW_OC3Mnpl_DLL_WTurb_WavesIrr) under gdb, having compiled the whole code with -DCMAKE_BUILD_TYPE=Debug, I am obtaining the following severe error:

forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable FILLEDGROUPS when it is not allocated

Image              PC                Routine            Line        Source             
openfast           000000000518AD99  Unknown               Unknown  Unknown
openfast           0000000003B80D5B  morison_mp_moriso        3822  Morison.f90
openfast           0000000003AE5452  hydrodyn_input_mp        4098  HydroDyn_Input.f90
openfast           0000000003A4C195  hydrodyn_mp_hydro         368  HydroDyn.f90
openfast           000000000043F4FC  fast_subs_mp_fast         812  FAST_Subs.f90
openfast           000000000040716D  fast_subs_mp_fast          61  FAST_Subs.f90
openfast           0000000000405324  MAIN__                     75  FAST_Prog.f90
openfast           0000000000404D82  Unknown               Unknown  Unknown
libc-2.27.so       00007FFFF08BDB97  __libc_start_main     Unknown  Unknown
openfast           0000000000404C6A  Unknown               Unknown  Unknown
[Inferior 1 (process 17086) exited with code 0230]

In seems to come because InitInp%FilledGroups is not allocated yet when invoked from Morison_ProcessMorisonGeometry.
The program seems to run perfectly without debugging options.

**To Reproduce**

1. Compile with Intel Fortran Compiler and  -DCMAKE_BUILD_TYPE=Debug
2. Run 5MW_OC3Mnpl_DLL_WTurb_WavesIrr case with gdb
3. See the error

**OpenFAST Version**

double precision at commit v2.2.0-10-g6d9e2b9f

**System Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Compiler: ifort version 19.0.4.243
 - Compiler settings: Debug

**Comment by rafmudaf** [comment]
I am not able to reproduce this bug with Ubuntu 20.04 at the dev branch of OpenFAST. The HydroDyn and Morison modules were heavily modified in #537 and #615, so this may have been fixed. If you encounter this problem again, please report back here.

**Comment by Junruzhang627** [comment]
Hi @lapadron, have you solved the HydroDyn bug when using openfast linux debug version?
