### ISSUE TITLE
Migrate OutListParameters.xlsx Into OpenFAST

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#413]
As mentioned in https://github.com/OpenFAST/openfast/pull/391, the OutListParameters.xlsx spreadsheet for ElastoDyn, ServoDyn, etc. have not yet been migrated from FAST v8.16 to OpenFAST.  This spreadsheet contains a list of all possible output parameters from ElastoDyn, ServoDyn, etc., including their name(s), description, coordinate system, and units.  Not only is this spreadsheet useful documentation, but it is also used to auto-generate output-processing source code, and so, is important to keep updated when changing the source code.  This spreadsheet should be migrated to OpenFAST.

Also, as mentioned in the following topic on our forum: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=2458&p=14236, the local tower forces from ElastoDyn--TwrHt1FLxt, TwrHt1FLyt, and TwrHt1Flzt etc.--are not described correctly in the OutListParameters.xlsx spreadsheet. They should be described as "Local tower fore-aft shear force of tower gage 1", "Local tower side-to-side shear force of tower gage 1", and "Local tower axial force of tower gage 1" etc., respectively. This description should be fixed.

**Comment by rafmudaf** [comment]
Like @andrew-platt mentioned in https://github.com/OpenFAST/openfast/pull/391#issuecomment-592561500, the spreadsheet does exist in some form in the [openfast-library src](https://github.com/openFAST/openfast/tree/dev/modules/openfast-library/src). A few others are located in the module directories: 

```
>>mbp@~/Development/openfast/modules (dev $)$ find . -name *xlsx
./openfast-library/src/OutListParameters.xlsx
./orcaflex-interface/src/OutListParameters.xlsx
./aerodyn/src/OutListParameters.xlsx
./aerodyn14/src/AD_RegistryEntries.xlsx
./inflowwind/src/OutListParameters.xlsx
./beamdyn/src/OutListParameters.xlsx
```

I'm not sure why there are two versions of some of these. In any case, if there's no functional reason for that, I suggest that they be consolidated into the "main" one in openfast-library.

**Comment by jjonkman** [comment]
Thanks @rafmudaf for clarifying!  I misread @andrew-platt's comment.

Regardless, the OutListParameters.xlsx spreadsheet must still be updated/corrected.

For modularization sake, I would suggest having a separate OutListParameters.xlsx spreadsheet for each module that needs one.  This is already the case for several modules, but I would suggest doing the same for ElastoDyn, ServoDyn, etc.

**Comment by bjonkman** [comment]
I had a chat with @andrew-platt about the `OutListParameters.xlsx` file a few weeks back. As I told him, I *really* hate having multiple spreadsheets with the same name. It is painful to try to copy information between them because Excel can't have them both open at the same time.

**Comment by jjonkman** [comment]
How about appending the module name to each spreadsheet, e.g., OutListParameters_ElastoDyn.xlsx?

**Comment by bjonkman** [comment]
That's better than all with the same name. However, I still prefer to have one spreadsheet with a tab for each module, and then put it in a documentation directory. It makes it easier to compare variable names against those in different modules.

**Comment by rafmudaf** [comment]
Good point - this should be moved to `docs/` and included in a download link in the online documentation.

**Comment by andrew-platt** [comment]
If we move it to `docs/`, then there isn't much need to keep separate files.  I had originally been of the opinion that the `OutListParameters` should be split out by module.  However, after discussing it with @bjonkman, I am of the opinion that we should keep it all in a single file in the `docs/`.  It is used more frequently as documentation reference than for generating code so it makes sense to keep it there.

If we didn't keep all the documentation in one place but rather split it out into each modules source directory, then I would lean towards splitting the `OutListParameters`.

**Comment by andrew-platt** [comment]
Updated in #429
