### ISSUE TITLE
Experiencing compile error on Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by yonghoonlee** [OpenFAST/openfast#415]
I am getting following error while compiling with gcc, g++, gfortran, openblas, and all other dependencies with ubuntu apt packaged libraries.
I turned on with the option BUILD_OPENFAST_CPP_API and BUILD_TESTING options with cmake.
Also, I cloned directly from the master branch of official github repository and recursively cloned with the submodules included in the openfast.
Following is the error message I am getting now:

[ 80%] Building Fortran object modules/openfast-library/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o
gfortran: internal compiler error: Killed (program f951)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
modules/openfast-library/CMakeFiles/openfast_postlib.dir/build.make:110: recipe for target 'modules/openfast-library/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o' failed
make[2]: *** [modules/openfast-library/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o] Error 4
CMakeFiles/Makefile2:2328: recipe for target 'modules/openfast-library/CMakeFiles/openfast_postlib.dir/all' failed
make[1]: *** [modules/openfast-library/CMakeFiles/openfast_postlib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rafmudaf** [comment]
Can you describe your system? Is this a virtual machine?

**Comment by yonghoonlee** [comment]
Yes, this is the VM running on VMWare Fusion on Mac.

**Comment by rafmudaf** [comment]
Try giving it more RAM, like 8GB. Also try switching the build type to `CMAKE_BUILD_TYPE=RelWithDebInfo`. The linking step in Release mode takes a lot of memory.

**Comment by yonghoonlee** [comment]
Thank you @rafmudaf Your advice was helpful in resolving the situation above.
