### ISSUE TITLE
ElastoDyn - Tower Modes

### ISSUE THREAD

**Issue by sr3114** [OpenFAST/openfast#416]
Hello,

Should be a quick question. I'm using an OC3 monopile offshore example as a template for a similar turbine I'm trying to study. In *_ElastoDyn_Tower.dat files, it appears the domain of the polynomial coefficients is 0-1, how does this domain map to physical space? Is 0 at the tower base? In reality, I would have thought there would be some displacement in the mode shape at the tower base because the foundation has a stiffness, so why are there no constant terms (and linear term)? 

I've struggled to use BModes because I think the OC3Hywind.bmi input file I have is out of the date for the version I have installed. Therefore, I've decided to calculate the modal displacements using some other software which I'm more familiar with and I'm resolving everything down to the mudline (-30m) where I'm going to fix it (pinned) for simplicity. The interface is at 20m. Can I just take X as an array between [z_interface, z_towertop] and Y the corresponding displacements and plug them into the polynomial coefficient calculator spreadsheet I saw in the Fast_v8 archive?

I'd appreciate any wisdom you have to help me understand this better!

Many thanks,
Sam

**Comment by jjonkman** [comment]
Hi Sam (@sr3114),

I'm familiar with your question.  Similar questions have been discussed thoroughly on our user forum, e.g., see my post dated Apr 10, 2012 in the following forum topic: https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=607.  NREL has provided the OC3Hywind.bmi input file along with a compatible version of BModes (called "BModes_JJ" on the forum) here: https://wind.nrel.gov/public/jjonkman/BModes/.

Best regards,

**Comment by sr3114** [comment]
Thanks Jason, I'll give this ago.

Best wishes,
Sam

**Comment by sr3114** [comment]
I find that when I use the improved direct method coefficients rather than direct method coefficients, the solution blows up - generally a Mach number error somewhere on the blades. I noticed that in the OC3 Offshore monopile the coefficients are similar to mine when I used direct method coefficients. Is there a reason to use one over the other?

Best wishes,
Sam

**Comment by andrew-platt** [comment]
The slack channel notified me that a comment was posted on this issue, but I don't see it in the issue.  @sr3114 , did you post then remove a comment?

**Comment by sr3114** [comment]
@andrew-platt I posted earlier before realising I had made an input error.

**Comment by lmj19971118** [comment]
> 你好萨姆(@sr 3114)，
> 
> 我很熟悉你的问题。类似的问题已经在我们的用户论坛上进行了彻底的讨论，例如，见我2012年4月10日在以下论坛主题中的帖子：[Https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=607](https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=607)。NREL在论坛上提供了OC3HyWind.bmi输入文件以及兼容版本的BModes(在论坛上称为“BModes_JJ”)：[Https://wind.nrel.gov/public/jjonkman/BModes/](https://wind.nrel.gov/public/jjonkman/BModes/).
> 
> 诚挚的问候,



> 你好萨姆(@sr 3114)，
> 
> 我很熟悉你的问题。类似的问题已经在我们的用户论坛上进行了彻底的讨论，例如，见我2012年4月10日在以下论坛主题中的帖子：[Https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=607](https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=607)。NREL在论坛上提供了OC3HyWind.bmi输入文件以及兼容版本的BModes(在论坛上称为“BModes_JJ”)：[Https://wind.nrel.gov/public/jjonkman/BModes/](https://wind.nrel.gov/public/jjonkman/BModes/).
> 
> 诚挚的问候,
