### ISSUE TITLE
Bug report，cannot run BeamDyn standalone

### ISSUE THREAD

**Issue by iiamdone** [OpenFAST/openfast#419]
**Bug description**
HI, I trying to run BeamDyn standalone and to do some "FSI" thing, but the first step I try to run BeamDyn standalone. Follow the instructions given by the manual, I was unsuccessful to do it. The warning given in the DOS window is showed below.  If it is a very simple or basic question I must apologies for your times to help me.
Thanks for any help given.

P.S. I download the BeamDyn from the nrel website and all the files are exit.

DOS shows:
---------------------------------------------------------------------------------------------------
C:\Users\iammd>D:\Research_data\LUZEHUI\BeamDyn\bin\BeamDyn_Driver_Win32.exe D:\Research_data\LUZEHUI\BeamDyn\bin\Dvr_5MW_Dynamic.inp

**************************************************************************************************
BeamDyn Driver (v1.00.02, 5-Apr-2016)

Copyright (C) 2016 National Renewable Energy Laboratory

This program comes with ABSOLUTELY NO WARRANTY. See the "license.txt" file distributed with this
software for details.
**************************************************************************************************

 Running BeamDyn Driver (v1.00.02, 5-Apr-2016)
 linked with NWTC Subroutine Library (v2.09.00, 23-Jul-2016)

 Running BeamDyn (v1.01.04, 26-Jul-2016).
BD_Init:BD_ReadInput:BD_ReadPrimaryFile:OpenFInpFile:The input file,
"Dynamic_BeamDyn_Input_5MW.inp", was not found.
 BeamDyn Driver encountered simulation error level: FATAL ERROR

 Aborting program.
---------------------------------------------------------------------------------------------------------

**Comment by andrew-platt** [comment]
The BeamDyn driver is not finding your input file.  Do you actually have one located at `D:\Research_data\LUZEHUI\BeamDyn\bin\Dvr_5MW_Dynamic.inp`?

**Comment by iiamdone** [comment]
About:" do you actually have one located at D:\Research_data\LUZEHUI\BeamDyn\bin\Dvr_5MW_Dynamic.inp? "Yes, I do have one. it shows like
![1](https://user-images.githubusercontent.com/58278556/77388159-449a3680-6dca-11ea-9987-4ec898847130.jpg)

About:"did you intend the input file to be on theC:\ drive instead?" No,i think it can run successful no matter the BeamDyn was in C or D disc. The Dos windows show C:\Users\iammd> is what it is, i mean when the dos was opened, the C:\User\iammd> show as well.

And then i try to move the program to C:\ and see if it can run. I install the BeamDyn in C disc and run it in Dos, and the warning shows as before.

-------------------------------------------------------------------------------------
BeamDyn in C disc

![3](https://user-images.githubusercontent.com/58278556/77388563-72cc4600-6dcb-11ea-879b-39bb38335c7f.jpg)


![2](https://user-images.githubusercontent.com/58278556/77388560-6e079200-6dcb-11ea-8411-9a662e4d5784.jpg)



--------------------------------------------------------------------------------------
Dos warning:

![1](https://user-images.githubusercontent.com/58278556/77387124-7a89eb80-6dc7-11ea-88b7-7c1589f71be1.jpg)

**Comment by rafmudaf** [comment]
The driver input file (`Dvr_5MW_Dynamic.inp`) does exist in your directory, but the primary input file you're passing in (`Dynamic_BeamDyn_Input_5MW.inp`) does not.

Just to be clear, the error message from BeamDyn is telling you that it cannot read the primary BeamDyn file. When using the driver, you have a driver input file and then another separate input file that corresponds to BeamDyn library itself. You need to put the path to the primary input file inside the driver input file.

**Comment by iiamdone** [comment]
Thank you rafmudaf and thank you Andrew
Follow your advice.
I have solve this problem by using txt-edit software to change the final line of (Dvr_5MW_Dynamic.inp)
"Dynamic_BeamDyn_Input_5MW.inp"    InputFile - Name of the primary input file
To
"D:\Research_data\LUZEHUI\BeamDyn\bin\Dynamic_BeamDyn_Input_5MW.inp"    InputFile - Name of the primary input file
I mean add the path of (Dynamic_BeamDyn_Input_5MW.inp) in the drive input file. Hope this can help people face this problem.

Thanks again.
