### ISSUE TITLE
Add compatible overloads to the c++ API to use stack allocated variables

### ISSUE THREAD

**Issue by psakievich** [OpenFAST/openfast#422]
**Is your feature request related to a problem? Please describe.**
I am using calls to openfast inside functors for Kokkos that I would ideally like to be thread safe.  Currently the API requires `std::vector<double>&` to pull data out, but inside a thread safe functor this requires multiple heap allocations (min 1 per thread).

**Describe the solution you'd like**
I'd like function overloads that replace `std::vector<double>&` with `double[3]`, `double*` or  `std::array<double,3>` so I can use stack allocated variables. 

**Describe alternatives you've considered**
The standard way of getting around this is to pre allocate `std::vectors` outside a loop. This is fine for most cases, but I'd really like an option to use the stack for such a simple data transport mechanism because it would simplify the api use, and since the vector `size` is always 3 it seems like an array would be more appropriate.

**Comment by psakievich** [comment]
@gantech @sayerhs thoughts?

**Comment by sayerhs** [comment]
@psakievich Can you add some function links that you want to change? That will help make sure we are all on the same page. I do agree that a function that allows pulling data with `(double* buffer, int ndim)` is more versatile than taking a `std::vector` or `std::array`, but I'd like to see the function before I commit to this. :)

**Comment by psakievich** [comment]
@sayerhs no problem. I think this is all of them.  It looks like they are mostly just forwarding to fortran routines anyways so it should be pretty simple.

https://github.com/OpenFAST/openfast/blob/6ec412105a04bc7fac91f7b9c6d7e2e4a4c98223/glue-codes/openfast-cpp/src/OpenFAST.H#L194
https://github.com/OpenFAST/openfast/blob/6ec412105a04bc7fac91f7b9c6d7e2e4a4c98223/glue-codes/openfast-cpp/src/OpenFAST.H#L195
https://github.com/OpenFAST/openfast/blob/6ec412105a04bc7fac91f7b9c6d7e2e4a4c98223/glue-codes/openfast-cpp/src/OpenFAST.H#L198
https://github.com/OpenFAST/openfast/blob/6ec412105a04bc7fac91f7b9c6d7e2e4a4c98223/glue-codes/openfast-cpp/src/OpenFAST.H#L199
https://github.com/OpenFAST/openfast/blob/6ec412105a04bc7fac91f7b9c6d7e2e4a4c98223/glue-codes/openfast-cpp/src/OpenFAST.H#L200
https://github.com/OpenFAST/openfast/blob/6ec412105a04bc7fac91f7b9c6d7e2e4a4c98223/glue-codes/openfast-cpp/src/OpenFAST.H#L203
https://github.com/OpenFAST/openfast/blob/6ec412105a04bc7fac91f7b9c6d7e2e4a4c98223/glue-codes/openfast-cpp/src/OpenFAST.H#L204
https://github.com/OpenFAST/openfast/blob/6ec412105a04bc7fac91f7b9c6d7e2e4a4c98223/glue-codes/openfast-cpp/src/OpenFAST.H#L205
https://github.com/OpenFAST/openfast/blob/6ec412105a04bc7fac91f7b9c6d7e2e4a4c98223/glue-codes/openfast-cpp/src/OpenFAST.H#L206

**Comment by sayerhs** [comment]
@psakievich Yeah, they look like it should be fairly straightforward. Do you want to submit a pull request where the core implementation uses `double*` pointer and the `std::vector<double>&` are just inline implementations that just forward to the pointer functions?

**Comment by psakievich** [comment]
@sayerhs sure thing!

**Comment by psakievich** [comment]
Addressed in #425
