### ISSUE TITLE
question on how to commit a change to the repository

### ISSUE THREAD

**Issue by lapadron** [OpenFAST/openfast#427]
Hello,
I write because I have been working with SubDyn and I believe I found a minor bug in SubDyn_Driver. My question is because I haven't been able to 'upload' the commit (This is possibly a trivial question, but I am new to git or github and haven't been able to do it) and it would be great if somebody could tell me how should I proceed.

After having worked in my local copy, this is what I get when I run 'git status' and then 'git push'. Is this the correct procedure?

~/OpenFAST/OpenFAST_Git_clone/openfast$ git status
On branch dev
Your branch is ahead of 'origin/dev' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean

~/OpenFAST/OpenFAST_Git_clone/openfast$ git push
Username for 'https://github.com': lapadron
Password for 'https://lapadron@github.com': 
remote: Permission to OpenFAST/openfast.git denied to lapadron.
fatal: unable to access 'https://github.com/OpenFAST/openfast.git/': The requested URL returned error: 403

Thank you very much in advance,

**Comment by michaelasprague** [comment]
Hi.  You will need to submit your suggested changes as a pull request.  You can go here for details: https://openfast.readthedocs.io/en/master/source/dev/github_workflow.html#github-workflow

**Comment by lapadron** [comment]
Hi. Thank you. I am going through the steps, but I have a problem at step 4, when I try to create the branch. It tells me "Not a valid object name: 'upstream/dev'.". I have tried starting with 'git clone -b dev https: ...." but I get the same error. I put all the outpus below. Any help will be welcomed.
Thanks in advance, 

:~/OpenFAST/Github$ git clone https://github.com/lapadron/OpenFAST
Cloning into 'OpenFAST'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 30442 (delta 9), reused 11 (delta 3), pack-reused 30420
Receiving objects: 100% (30442/30442), 144.32 MiB | 3.01 MiB/s, done.
Resolving deltas: 100% (17891/17891), done.

:~/OpenFAST/Github$ cd OpenFAST/
:~/OpenFAST/Github/OpenFAST$ git remote add upstream https://github.com/OpenFAST/OpenFAST
:~/OpenFAST/Github/OpenFAST$ git branch feature/minor_bugFix upstream/dev
fatal: Not a valid object name: 'upstream/dev'.
lpadron@lpadron-Precision-3541:~/OpenFAST/Github/OpenFAST$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by rafmudaf** [comment]
@lapadron Have you been able to move past this problem or are you at the same spot?

**Comment by lapadron** [comment]
@rafmudaf Hi, I am still at the same spot ...

**Comment by rafmudaf** [comment]
Do `git fetch --all` and then start back from step 4.

**Comment by lapadron** [comment]
Thank you! That solved it. I already submittted it.
