### ISSUE TITLE
Regression tests in OpenFAST

### ISSUE THREAD

**Issue by ramya-niranjan** [OpenFAST/openfast#432]
Hi all,
I have installed OpenFAST in my MacOS. After running all the regression tests I got the following failures

![image](https://user-images.githubusercontent.com/63047973/78242037-f8a06d80-74fe-11ea-87b2-0c1dbdaffd51.png)

In order to view the plots I ran the command 
**python3 manualRegressionTest.py ../build/glue-codes/openfast/openfast linux gnu 1e-5 -n -p**
Python version installed is 3.7.3 and the matplotlib version is 3.1.0
I am getting the following failures after running the above command in the terminal

![image](https://user-images.githubusercontent.com/63047973/78242058-01913f00-74ff-11ea-90b4-330779e2b631.png)
![image](https://user-images.githubusercontent.com/63047973/78242107-1241b500-74ff-11ea-8b08-6214ff6a6930.png)

I am able to view the .html files and log files but the plots are not getting generated. Please give me some advice on how to resolve this issue.

Thanks and Regards
Ramya

**Comment by rafmudaf** [comment]
This has recently been updated to use Bokeh instead of matplotlib. So its probably failing if you haven't installed that library.

```
pip install Bokeh==1.4
```

This need updating in the documentation.

**Comment by rafmudaf** [comment]
Updated in `dev`.
