### ISSUE TITLE
Numpy cannot be recognized and tests failed

### ISSUE THREAD

**Issue by Seager1989** [OpenFAST/openfast#440]
Hi Guys,
I am working on the compiling on a cluster and errors appeared during the compiling process. I describe them here.

I can cmake the openfast successfully.
I then make it with error : Fatal Error: Cannot read module file 'pfunit_mod.mod' opened at (1), because it was created by a different version of GNU Fortran, compilation terminated.
After that I cannot run the utest and regression test.
However, the openfast and submodules have been compiled and built normally. I can run an example in the regression test successfully by manual. I try to run the regression test manually, but it showed fails with the message of lacking of Numpy.
I actually installed the Numpy as mentioned in the #384 by Andy, but the cluster shell environment can not recognize it even I tried to export it to the shell. The installed Numpy contains bin and lib folders with only three files in the bin. Can someone give me a hand on how to fix this problem? Thank You！

**Comment by rafmudaf** [comment]
The `.mod` problem may be due to changing the compiler. Did you try in one version or type of compiler first and then change to GNU?

It also happens to me when I open the OpenFAST project with an IDE like VS Code and the Fortran extensions try to set up intellisense. To do that, the extension will create these temporary `.mod` files for Fortran modules. If the compiler used for that is different than the one used to compile, you'll get this error.

In any case, try deleting all of these: `cd opencast && find . -name *.mod -delete`.

**Comment by rafmudaf** [comment]
As for Numpy, I suggest verifying that the Python path configured in CMake is the one that has Numpy installed. Also, verify that you can actually import Numpy with the expected Python.

**Comment by Seager1989** [comment]
> The `.mod` problem may be due to changing the compiler. Did you try in one version or type of compiler first and then change to GNU?
> 
> It also happens to me when I open the OpenFAST project with an IDE like VS Code and the Fortran extensions try to set up intellisense. To do that, the extension will create these temporary `.mod` files for Fortran modules. If the compiler used for that is different than the one used to compile, you'll get this error.
> 
> In any case, try deleting all of these: `cd opencast && find . -name *.mod -delete`.

Thank you for you reply.

I tried to remove the *.mod file and compiled Openfast successfully, but the regression test is still incorrect. The glue-codes folder in the built reg-tests contains only several basic cases as below picture.  
![image](https://user-images.githubusercontent.com/38188001/79878539-8b744f80-83bb-11ea-8639-ed510dcb1372.png)
So, I try to recompile it but failed again. Remocing the *.mod does not work now with the following error appeared. It seems related to the utest module.
![image](https://user-images.githubusercontent.com/38188001/79878767-cfffeb00-83bb-11ea-855e-0a74363b991f.png)

In addition, could you please give more detail on, "Did you try in one version or type of compiler first and then change to GNU?"

Thank you!

**Comment by rafmudaf** [comment]
Just to be clear, the trouble compiling pFUnit is for the unit tests not the regression tests. If OpenFAST has compiled, you should be able to run the regression tests just fine. If not, thats a separate issue.

The six folders that have been copied over are not test cases but just the turbine case files. Once you run a case, the case files (a series of `.fst`, `.dats`, and `.inp` files) will be copied over.

As for the `.mod` issues, double check that you've actually been able to delete all of the ones throughout the OpenFAST project. You could also check the Fortran compiler used to compile pFUnit by searching for the `CMAKE_FORTRAN_COMPILER` variable in that sub-project's CMakeCache at `openfast/build/unit_tests/pfunit-build/CMakeCache.txt`. The compiler there should match the once listed in `openfast/build/CMakeCache.txt`.

**Comment by Seager1989** [comment]
> Just to be clear, the trouble compiling pFUnit is for the unit tests not the regression tests. If OpenFAST has compiled, you should be able to run the regression tests just fine. If not, thats a separate issue.
> 
> The six folders that have been copied over are not test cases but just the turbine case files. Once you run a case, the case files (a series of `.fst`, `.dats`, and `.inp` files) will be copied over.
> 
> As for the `.mod` issues, double check that you've actually been able to delete all of the ones throughout the OpenFAST project. You could also check the Fortran compiler used to compile pFUnit by searching for the `CMAKE_FORTRAN_COMPILER` variable in that sub-project's CMakeCache at `openfast/build/unit_tests/pfunit-build/CMakeCache.txt`. The compiler there should match the once listed in `openfast/build/CMakeCache.txt`.

Thank you!
I checked these two files and found different version of Fortran compiler. I unloaded on of them and the solved the .mod problem. **The openfast is compiled normally. The Utest was passed but the regression test is failed.**

I also checked the numpy. There are three python in the system. Only the python 2.7 contained an importable numpy. The openfast needs a python3+. I try to install a user numpy for the python 3.8 and a warning appeared with no module named '_ctypes'. **I run a single regression test with: $ ctest -VV -R AWT_YFix_WSt. It is failed with an error of 'ModuleNotFoundError: No module named '_ctypes''.

So the current problem is do you have any suggestions to fix this problem? Thank you**

**Comment by rafmudaf** [comment]
This is a Python and Numpy problem so your best bet is probably to ask your system administrators about it.
