### ISSUE TITLE
CMake Warning (dev): Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.

### ISSUE THREAD

**Issue by yonghoonlee** [OpenFAST/openfast#441]
On macOS (Intel compilers, Intel MKL), I see the following messages while running cmake with BUILD_SHARED_LIBS=On flag. I think this does not affect for just using the OpenFAST, but I never saw these messages when I run the cmake on the Ubuntu Linux.

It was the dev branch of the OpenFAST; the Intel compilers and MKL are the most recent version (C++ and Fortran, 2020.1.024); other dependencies (such as HDF5, yaml-cpp) are installed using brew.

cmake .. -DBUILD_OPENFAST_CPP_API=On -DBUILD_SHARED_LIBS=On
-- Setting system file as: src/SysIFL.f90
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   aerodyn14lib
   aerodynlib
   beamdynlib
   elastodynlib
   extptfm_mckflib
   feamlib
   foamfastlib
   hydrodynlib
   icedynlib
   icefloelib
   ifwlib
   mapcpplib
   maplib
   moordynlib
   nwtclibs
   openfast_postlib
   openfast_prelib
   openfastcpplib
   openfastlib
   openfoamtypeslib
   orcaflexlib
   scfastlib
   sctypeslib
   servodynlib
   subdynlib
   versioninfolib

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/yonghoonlee/Dropbox/GitRepositories/openfast-env/OpenFAST/build

**Comment by yonghoonlee** [comment]
It was the dev branch of the OpenFAST; the Intel compilers and MKL are the most recent version (C++ and Fortran, 2020.1.024); other dependencies (such as HDF5, yaml-cpp) are installed using brew.

**Comment by andrew-platt** [comment]
I think I had seen this warning a few years ago, but cannot remember what I did to resolve it (or if I simply ignored it).  @rafmudaf have you run into this?

**Comment by yonghoonlee** [comment]
I am not quite sure what those errors mean, but I thought it seems that the compiled *.dylib files are not automatically linked from the executable file, even at the install directories. After I set the environmental variable with
export DYLD_LIBRARY_PATH="~/OpenFAST/install/lib:$DYLD_LIBRARY_PATH"
at least the compiled OpenFAST (with shared library setting) seems working.
