### ISSUE TITLE
Question: specific compilation option for specific file in cmake?

### ISSUE THREAD

**Issue by lapadron** [OpenFAST/openfast#446]
Hello!

I have been trying to include a specific compilation option (flag) only for some source files (not for all files) in cmake. I have tried some tips that I have found on the web but they don't work for me. Do you know how to do it? (for instance, specify -check all only for files in a certain module).
I am working with ubuntu and intel fortran compilers, though I guess it would be the same in all platforms.
Many thanks in advance,
Luis

**Comment by rafmudaf** [comment]
I think you can use [target_compile_options](https://cmake.org/cmake/help/latest/command/target_compile_options.html). I haven't tested this, so you'll want to. After passing your compiler flag, you can inspect the Makefiles in a module directly. I use `grep` for that since the CMake-generated Makefiles aren't very straightforward to follow.

Let me know how it goes!

**Comment by lapadron** [comment]
Hello,

Thanks. I tried it in 'cmake/OpenfastFortranOptions.cmake'. For instance:

  # debug flags
  if(CMAKE_BUILD_TYPE MATCHES Debug)
    set( CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -fpe0 -traceback" )
    target_compile_options(subdynlib.dir PUBLIC -check all -pedantic)  # <- NEW LINE
  endif()

but I always get an error regarding the target. For instance:

CMake Error at cmake/OpenfastFortranOptions.cmake:133 (target_compile_options):
  Cannot specify compile options for target "subdynlib.dir" which is not
  built by this project.

It seems I am not understanding correctly which are the targets. As targets, I have tried SubDyn, subdynlib, subdynlib.dir, but without success.  Do you have a suggestion if I only want it to apply to SubDyn files when building openfast?

**Comment by rafmudaf** [comment]
You need to put the target-specific stuff in the CMakeLists where the target is defined. For `subdynlib`, add those lines in `modules/subdyn/CMakeLists.txt`.

**Comment by lapadron** [comment]
Thank you! Exactly. Solved.
