### ISSUE TITLE
Regression Tests - Ubuntu in Windows 10

### ISSUE THREAD

**Issue by bmazetto** [OpenFAST/openfast#449]
Hello Everyone,

I’m facing some failures during the Regression Tests and problems to get the plots.

**Bug description**
No plots of failed cases.

**To Reproduce**
Basically, I used a similar procedure as the one from #384 to build OpenFAST in Ubuntu and the same steps shown in https://raf-openfast.readthedocs.io/en/docs-general_updates/source/testing/regression_test.html to run the Regression Tests.

I have installed matplotlib using “sudo apt-get python3-matplotlib”. Numpy is installed, as well. 

**Expected behavior**
I tried to generate the plots using the given python routine, so I could compare my results to the baseline. I expected to I go to the directory “openfast\build\reg_tests\glue-codes\openfast” and access the “regression_test_summary.html”, where I could see the plots for the failed cases.

**Screenshots**
These are the results from the Regression Tests executing with CTEST:
![CTEST_1](https://user-images.githubusercontent.com/44245549/82129853-5ed60c80-979c-11ea-8f9a-569068765629.jpg)
![CTEST_2](https://user-images.githubusercontent.com/44245549/82129855-60073980-979c-11ea-9aac-6d518555ee8c.jpg)
![CTEST_3](https://user-images.githubusercontent.com/44245549/82129856-609fd000-979c-11ea-8fda-eec142cddba5.jpg)

These are the results executing the Python routine just to generate the plots, without running the cases again:

![Python_1](https://user-images.githubusercontent.com/44245549/82129858-61386680-979c-11ea-8656-3507e68f6f1a.jpg)
![Python_2](https://user-images.githubusercontent.com/44245549/82129859-61d0fd00-979c-11ea-8d0c-42722d6ed643.jpg)

**OpenFAST Version**
**************************************************************************************************
 OpenFAST

 Copyright (C) 2020 National Renewable Energy Laboratory
 Copyright (C) 2020 Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.3.0-29-gced487c8
 Compile Info:
  - Compiler: GCC version 9.3.0
  - Architecture: 64 bit
  - Precision: double
  - Date: May 15 2020
  - Time: 21:25:06
 Execution Info:
  - Date: 05/16/2020
  - Time: 01:57:45-0300

**System Information (please complete the following information):**
 - OS: Ubuntu 20.04 (inside Windows 10)
 - Compiler: GNU Fortran (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**Additional context**
A little time ago, I manage to build OpenFAST in Windows using Cygwin. Now, I'm running my simulations using it. However, since I have a great number of scenarios to run and they are taking a lot of time, I'd like to run them in parallel. To do so, I've installed Ubuntu for Windows 10 in the same computer and used a similar procedure mentioned in #384 to build OpenFAST in Ubuntu. 

Is there a better way to run OpenFAST simulations in parallel using only one notebook? Could someone give me a suggestion?

Thanks a lot for your time!

**Comment by rafmudaf** [comment]
@bmazetto The documentation link you've included above is my fork's documentation which is just something I use for development. Its is severely out of date. The official OpenFAST documentation is linked at the top of the GitHub page and here's the [link](https://openfast.readthedocs.io/en/master/). That being said, you simply need to install Bokeh at version 1.4 instead of matplotlib.

As for running in parallel, try running with [ctest](https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#ctest-driver) instead of with the Python driver. For what its worth, we are working on improving the custom Python infrastructure so that running in parallel will be supported.

**Comment by bmazetto** [comment]
Hello @rafmudaf , thank you for your help. Now I'm getting the plots. I had to change from Bokeh 2.0.2 to 1.4.0.

I'm not sure how to use the CTEST to run my own simulations. Could you provide an example of how to do it? Maybe point out which files I should customize.

**Comment by rafmudaf** [comment]
Read the CTest section of the documentation [here](https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#executing-with-ctest). Let me know if some part of that is lacking or not clear.
