### ISSUE TITLE
A proplem with the output of AeroDyn

### ISSUE THREAD

**Issue by abdoo0** [OpenFAST/openfast#450]
Hello, 
 I hope this finds you well and safe. 
I have been encountering this problem while running openfast 
![image](https://user-images.githubusercontent.com/62108008/82133421-983a6680-97f4-11ea-873a-ec5e4924e70a.png)
This is the output section of my Aerdyn file 
![image](https://user-images.githubusercontent.com/62108008/82133446-eea7a500-97f4-11ea-93b1-d880642aef3c.png)
Thank you for your help in advance.

**Comment by bp-liu** [comment]
Hello friend, I seem to have encountered a similar problem with you. When I use the command openfast to run the example under Linux, the following problem appears: aerodyn can't read TEST02_ Ad15.ipt file, do you know how to solve it？ @abdoo0 
![0S430$ELEZ1M4`%YBAYE5$1](https://user-images.githubusercontent.com/82130553/113960116-8a4f6300-9856-11eb-97e8-4bba9ee4f4e0.png)
![E3(W4UP7NG16)CG9_%WII9A](https://user-images.githubusercontent.com/82130553/113960121-8c192680-9856-11eb-94de-dd760e7b1973.png)
![W278A5$P@MHKV`EIJB} THB](https://user-images.githubusercontent.com/82130553/113960124-8d4a5380-9856-11eb-9766-7671a3cc4a41.png)

**Comment by bp-liu** [comment]
Hello friend, I seem to have encountered a similar problem with you. When I use the command openfast to run the example under Linux, the following problem appears: aerodyn can't read TEST02_ Ad15.ipt file, do you know how to solve it？ @abdoo0 
![0S430$ELEZ1M4`%YBAYE5$1](https://user-images.githubusercontent.com/82130553/113960412-0c3f8c00-9857-11eb-9436-e3b291dd939e.png)and
![E3(W4UP7NG16)CG9_%WII9A](https://user-images.githubusercontent.com/82130553/113960425-0fd31300-9857-11eb-96a7-5511d5c301cc.png)and
![W278A5$P@MHKV`EIJB} THB](https://user-images.githubusercontent.com/82130553/113960433-12ce0380-9857-11eb-88e9-6dfe917c874a.png)

**Comment by bp-liu** [comment]
Hello friend, I seem to have encountered a similar problem with you. When I use the command openfast to run the example under Linux, the following problem appears: aerodyn can't read TEST02_ Ad15.ipt file, do you know how to solve it?@abdoo0 
![0S430$ELEZ1M4`%YBAYE5$1](https://user-images.githubusercontent.com/82130553/113960465-224d4c80-9857-11eb-9eda-45ca9f2f9c48.png)

**Comment by bp-liu** [comment]
![Uploading E3(W4UP7NG16)CG9_%WII9A.png…]()

**Comment by bp-liu** [comment]
![E3(W4UP7NG16)CG9_%WII9A](https://user-images.githubusercontent.com/82130553/113960716-75bf9a80-9857-11eb-9a54-46073b1207fc.png)
![W278A5$P@MHKV`EIJB} THB](https://user-images.githubusercontent.com/82130553/113960723-78ba8b00-9857-11eb-8367-508081ac45ea.png)
