### ISSUE TITLE
Obtaining Blade geometry inputs BldSwpAC, BldCrvAC

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#451]
Hi openFAST team,

I am trying to obtain information like BldSwpAC, BldCrvAC etc from the blade-geometry from another commercial software to be incorporated in openFAST Aeroydyn blade input files. I realise that if the Aerodynamic center of the blades are known, there must be a formulation to obtain BldSwpAC, BldCrvAC directly. Could someone possibly direct me to such formulation, if there exists one?

Best,
Tanmoy

**Comment by jjonkman** [comment]
Hi @tchatte3,

I'm not sure what type of formulation you are after, but if you know where the aerodynamic center (reference point for the aerodynamic data / pitching moment) is, then it should be just a matter of geometry to identify BldSwpAC and BldCrvAC.  Figure 4.3 from the online AeroDyn documentation (https://openfast.readthedocs.io/en/master/source/user/aerodyn/input.html#aerodyn-primary-input-file) should be useful in this regard.

Best regards,

**Comment by tchatte3** [comment]
@jjonkman Thanks for the input. Infact, I looked at the manual, as well.  BldSwpAC should be the negative local y coordinate value from the blade pitch axis. Additionally, BldCrvAC should be the +ve local blade x coordinate (which is local coordinate and bends with the blade) projected with the absolute x-direction in the paper (with no tilt). The projection angle, as I see should be coming from BldCrvAng, but I do not see an easy way to point-out what the BldCrvAng (measured against the blade-pitch axis) should be.

**Comment by ebranlard** [comment]
This variable has confused me several time,I think you can use this formula
```
BlCrvAng = atan (  ( BlSpn-BlSpan(1) )  / (  BlCrvACx - BlCrvACx(1) )  )  * 180 /  pi
```

**Comment by jjonkman** [comment]
@tchatte3 I'm not sure I understand all of your comments, but BldSwpAC and BldCrvAC are simply the in-plane and out-of-plane offsets normal to the pitch axis, which is not impacted by blade bending.

I think @ebranlard's equation is inverted.  I would use (with small changes to the formula at the root and tip):

`BlCrvAng(n) = atan ( ( BlCrvAC(n+1) - BlCrvAC(n-1) ) / ( BlSpn(n+1) - BlSpn(n-1) )*180/pi`

**Comment by tchatte3** [comment]
@jjonkman , @ebranlard . Thanks a lot for these valuable comments. I think, I  have a much clearer understanding of BlCrvAng, and BlCrvAC, now.
