### ISSUE TITLE
Elastodyn Theory guide

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#459]
Hi,

I am wondering if the latest Elastodyn theory/user manual is available yet? I found some details related to Elastodyn in Fast v6 manual, but was looking for more recent releases.

Thanks,
Tanmoy

**Comment by jjonkman** [comment]
Hi @tchatte3,

Perhaps @rafmudaf is working on something newer in readthedocs, but currently the user documentation of ElastoDyn exists in old FAST v6 User's Manual, with some updates to the input file parameters discussed in the FAST v8 ReadMe file.  For information on the theory basis of ElastoDyn, see the following topic on our forum: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=424.

Best regards,

**Comment by tchatte3** [comment]
@jjonkman Thanks for pointing that out.

Best Regards.
