### ISSUE TITLE
Question about AeroDyn modules?

### ISSUE THREAD

**Issue by ChaoREN1994** [OpenFAST/openfast#468]
Dear,all

I try to run the module ““5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth”. I have a question about the AeroDyn14 and 15. I know, for different wind speed , I need to intialize the rotor speed and pitch angle. I want to know how much rotor speed and pitch angle I should set for a given wind speed? Does that have a rule or an equation? Could you give me some references? In addition, If using AeroDyn15, FAST will abort at the beginning or during the Fast simulation due to high attack angle and tower strike ( I can change the High attack limit in the given file but It also happens). However with AeroDyn14, It will not happen. why? Do you have any idea for that?  Thanks!!!
![5](https://user-images.githubusercontent.com/66703137/84440537-74731080-ac3a-11ea-941c-8bd5cf1d9564.PNG)

**Comment by jjonkman** [comment]
Dear @ChaoREN1994,

To minimize initialization problems and to reduce start-up transients, it is generally recommend to initialize the rotor speed and blade-pitch angles to their expected mean values for a given mean wind speed.  For the NREL 5-MW baseline wind turbine that you are simulating, the expected values for the rotor speed and blade-pitch angle as a function of mean wind speed are given in Figure 9-1 of the NREL 5-MW baseline turbine specifications report: https://www.nrel.gov/docs/fy09osti/38060.pdf.

The high-angle of attack warnings are not causing OpenFAST to abort; they may appear because of improper initial conditions.  OpenFAST is aborting because of the tower strike.  However, this could be triggered because of the large blade deflection warning you are getting.  Perhaps this too is the result of improper initial conditions?  It could also be indicative of a numerical instability, e.g., if you changed model properties (geometry, mass, stiffness) without also changing the time step appropriately.  What have you changed in the r-test model input file(s)?

Best regards,

**Comment by ChaoREN1994** [comment]
Thanks, @jjonkman

1. Thanks for your reply and the reference for initializing the rotor speed and blade-pitch angles.

2. Actually, I did not change any model properties (geometry, mass, stiffness), I just disabled the HydroDyn part and use the wind full-field file generated by TurbSim with large scale (220 m wide, 0.55 m to 180.55 m above ground).  I have done the followings in Fastv8 and now I try to repeat these in Openfast.

When I disable the HydroDyn and use AeroDyn15, I set the rotor speed and blade-pitch angle as the expected values. There is no tower strike errors and but the High attack warning will exist!

Running InflowWind.

   Reading a 32x32 grid (220 m wide, 0.55 m to 180.55 m above ground) with a characteristic wind
   speed of 24.02 m/s. This full-field file was generated by TurbSim (v1.06.00, 21-Sep-2012) on
   31-May-2020 at 23:59:18.

   Processed 7292 time steps of 10-Hz full-field data (729.1 seconds).
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers.
Running SubDyn.
   Calculating Internal Modal Eigenvectors
 Time: 0 of 520 seconds.

FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SrvD_CalcOutput:Running with torque
and pitch control of the NREL offshore 5MW baseline wind turbine from DISCON.dll as written by J.
Jonkman of NREL/NWTC for use in the IEA Annex XXIII OC3 studies.


FAST_Solution:CalcOutputs_And_SolveForInputs:SolveOption2:SrvD_CalcOutput:BladedInterface option
was designed for an explicit-loose coupling scheme. Using last calculated values from DLL on all
subsequent calls until time is advanced. Warning will not be displayed again.
 Time: 420 of 520 seconds. Estimated final completion at 11:39:20.
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.181 deg). BladeNode =
5, Blade = 3
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.181 deg). BladeNode =
5, Blade = 3
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.59 deg). BladeNode =
5, Blade = 1
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.59 deg). BladeNode =
5, Blade = 1
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.273 deg). BladeNode =
5, Blade = 2
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.273 deg). BladeNode =
 Time: 450 of 520 seconds. Estimated final completion at 11:39:13.

FAST_Solution:CalcOutputs_And_SolveForInputs:SolveOption2:AD_CalcOutput:BEMT_CalcOutput(node 18,
blade 1):Compute_UA_AirfoilCoefs:UA_CalcOutput:Mach number exceeds 0.3. Theory is invalid. This
warning will not be repeated though the condition may persist.


FAST_Solution:FAST_AdvanceStates:AD_UpdateStates:BEMT_UpdateStates(node 5, blade
3):BEMT_UnCoupledSolve:There is no valid value of phi for these operating conditions: Vx =
23.259, Vy = -1.658, rlocal = 11.733, theta = 0.64487, geometric phi = 1.642. This warning will
not be repeated though the condition may persist. (See GeomPhi output channel.)

Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.83 deg). BladeNode =
6, Blade = 1
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.83 deg). BladeNode =
6, Blade = 1
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.94 deg). BladeNode =
6, Blade = 2
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.94 deg). BladeNode =
6, Blade = 2
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.254 deg). BladeNode =
7, Blade = 1
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.254 deg). BladeNode =
7, Blade = 1
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.724 deg). BladeNode =
6, Blade = 3
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.724 deg). BladeNode =
 Time: 480 of 520 seconds. Estimated final completion at 11:39:07.
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (48.671 deg). BladeNode =
7, Blade = 3
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (48.671 deg). BladeNode =
7, Blade = 3
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.24 deg). BladeNode =
7, Blade = 2
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (45.24 deg). BladeNode =
7, Blade = 2
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (-46.779 deg). BladeNode =
18, Blade = 2
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (-46.779 deg). BladeNode =
18, Blade = 2
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (-45.882 deg). BladeNode =
18, Blade = 3
Warning: Turning off Unsteady Aerodynamics due to high angle of attack (-45.882 deg). BladeNode =


 Total Real Time:       13.586 minutes
 Total CPU Time:        13.555 minutes
 Simulation CPU Time:   13.052 minutes
 Simulated Time:        8.6667 minutes
 Time Ratio (Sim/CPU):  0.66402

 OpenFAST terminated normally.




When I disable the HydroDyn and use AeroDyn15, I do not set the rotor speed and blade-pitch angle (they are both 0). The tower strike will happen.  So, I thinck you are right about this , it is  due to the improper initial conditions.




Well, When I disable the hydroDyn and use AeroDyn14, I do not set the rotor speed and blade-pitch angle (they are both 0).  it will have start-up transients( I do not these results for my study). But the Fast can terminate normally without tower strike and High attack warning. So, I would like to know the differences between AeroDyn14 and AeroDyn15 are huge or not ?

3. I would like to use the loads(forces and moments) and motions in the platform (Intf) and apply them for OC4 jacket foundation with detailed modeling..  I found that when I use HydroDyn and disable HydroDyn part in Fastv8 with the same wind condition, the loads in the platform are so different. Do you have any ideas about this?
 
Disable the HydroDyn
![1 Fast wind only](https://user-images.githubusercontent.com/66703137/84493268-c8680e80-aca7-11ea-9e58-cdcd5bfd4ff2.png)
With HydroDyn still water condition
![1 Fast wind with still water](https://user-images.githubusercontent.com/66703137/84493336-e2a1ec80-aca7-11ea-8ea2-b3a6ce33009a.png)
Comparison between the two
![4  comparison](https://user-images.githubusercontent.com/66703137/84493386-f4838f80-aca7-11ea-8d71-54af10deb61e.png)

Thanks again for your reply.

**Comment by jjonkman** [comment]
Dear @ChaoREN1994,

Just a couple comments:

- I would not expect to see these "high angle of attack" warnings across most of the blade analysis nodes if you are initializing the rotor speed and blade-pitch angles properly.  It appears you are running  a simulation at a mean wind speed of 24 m/s.  Have you initialized the rotor speed to 12.1 rpm and the blade-pitch angels to approx. 22 degrees (these are expected mean values at 24 m/s) for this simulation?
- There many differences between AeroDyn v14 and AeroDyn v15 and I tend to trust the later more, but it is difficult to comment on any specific set of simulation results due to the many differences.  Please see a summary of the main differences between AeroDyn v14 and AeroDyn v15 in the last two pages of the AeroDyn v15.04 manual found here: https://wind.nrel.gov/public/jjonkman/AeroDyn/AeroDyn_Manual.pdf (many of the AeroDyn v15 limitations mention, e.g., dynamic wake, have now been addressed in newer versions of AeroDyn v15).  We are hoping to deprecate AeroDyn v14 soon.
- I'm not sure why you want to disable HydroDyn for an offshore jacket simulation, but the solution without HydroDyn appears to have numerical problems in the solution.  This could be because you've eliminated a couple sources of damping (hydrodynamic drag, as well as the (3,3) entry of the additional linear damping matrix, AddBLin).

Best regards,

**Comment by ChaoREN1994** [comment]
Thanks @jjonkman 

1. I think it is my problem. When I disable the HydroDyn , the high attack warning will exist. When I enable the HydroDyn, it will not have the high attack warning.  

2. Ok,  thanks for your information

3.As for why I disable the HydroDyn, once I would like to apply identical loads to the OC4 jacket with detailed modeling in FE software Ansys as they were applied in FAST simulations (aerodynamic and hydrodynamic loads). But when I saw the reponse of you in this FAQ(https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1778&p=8606&hilit=test21#p8606)
I was aware that it was not correct to simply takling the the forces and moments in platforms
I have noticed that you proposed:
![1](https://user-images.githubusercontent.com/66703137/84540017-da23d300-acf4-11ea-882a-67c5a9f396af.PNG)

One way coupled approch is not common in offshore wind industry.
The most common approach is sequentially coupled approach. But in the new version Openfast, the user-platform module (ExtPtfm) is still not released?
The third, fully-coupled approach is in Fastv8,  the outputs of the SubDyn (jacket) focus on the individual members of the jacket. But for the behavoir of the whole jacket, how could I do?  Using the Outall option in SubDyn ? Change the source code of Fastv8?

One idea I got is that I only simulate the aeordynamic loads using Fast. For Hydrodynamic loads I will design that by Ansys or Matlab using Morison’s equation. The forces and moments taken from the platfroms in Fast simulations are taken as aerodynamic loads for the jacket model in Ansys and the hydrodynamic loads will be designed in Ansys. I not sure that in this way, can I avoid or decrease the error due to differences in one-way coupled approch?? Looking forward to your opinion or advice!  Thanks a lot!

**Comment by jjonkman** [comment]
Dear @ChaoREN1994,

OK, it sounds like disabling HydroDyn was the cause of the issues you have been reporting.

The sequentially coupled approach has been introduced into OpenFAST per pull request https://github.com/OpenFAST/openfast/pull/344, which was recently merged into OpenFAST-dev.  It is just a matter of time before OpenFAST-dev gets merged into OpenFAST-master for the "official release", but you can use OpenFAST-dev now if you compile yourself.

You are correct that the fully coupled approach was available in FAST v8, and of course, is also available in OpenFAST.  The OutAll option of SubDyn can be used if you want to output the member-level loads at all joints.

Regarding your proposed approach using ANSYS, this sounds like a variation of the one-way coupled approach, which again is not common in offshore wind industry.  It will miss, for example, the effect of aerodynamic damping on the response of the substructure.

Best regards,

**Comment by ChaoREN1994** [comment]
Thanks for your reply.  @jjonkman   Your replys help me a lot.   It is so nice of you!   Thanks again!

**Comment by zz17635** [comment]
> Dear @ChaoREN1994,
> 
> To minimize initialization problems and to reduce start-up transients, it is generally recommend to initialize the rotor speed and blade-pitch angles to their expected mean values for a given mean wind speed. For the NREL 5-MW baseline wind turbine that you are simulating, the expected values for the rotor speed and blade-pitch angle as a function of mean wind speed are given in Figure 9-1 of the NREL 5-MW baseline turbine specifications report: https://www.nrel.gov/docs/fy09osti/38060.pdf.
> 
> The high-angle of attack warnings are not causing OpenFAST to abort; they may appear because of improper initial conditions. OpenFAST is aborting because of the tower strike. However, this could be triggered because of the large blade deflection warning you are getting. Perhaps this too is the result of improper initial conditions? It could also be indicative of a numerical instability, e.g., if you changed model properties (geometry, mass, stiffness) without also changing the time step appropriately. What have you changed in the r-test model input file(s)?
> 
> Best regards,

Dear @jjonkman:
I assume "Tower Strike" means structural failure of the wind turbine tower? How does ElastoDyn determine structural failure and is it possible to locate the failing position (elevation) of a given analysis and to output some stress/strain readouts of the tower?
Thanks very much,

**Comment by jjonkman** [comment]
Dear @zz17635,

It is not ElastoDyn that will indicate a tower strike, but rather it is AeroDyn that will indicate that.  AeroDyn will error out due to a tower strike if an aerodynamic analysis node on the blade passes through the boundary of the tower defined by the tower centerline (in its deflected state) and local tower radius.

Best regards,
