### ISSUE TITLE
Question of Regression test 

### ISSUE THREAD

**Issue by ChaoREN1994** [OpenFAST/openfast#469]
Dear, all

1. I try to run the regression Tests in Openfast. Most of them passed but there  were some tests failed. I did not know why?  
![12](https://user-images.githubusercontent.com/66703137/84571489-b9f72100-ad93-11ea-8272-8748ec9b6ac8.jpg)

Then I tried to use the Openfast.exe run the failed one.  It can terminate normally. I would like to know that I can use Openfast now ? Or should I check the failed ones ? 
![2](https://user-images.githubusercontent.com/66703137/84571550-2f62f180-ad94-11ea-88aa-09ee456bb19b.PNG)
![3](https://user-images.githubusercontent.com/66703137/84571555-34c03c00-ad94-11ea-8f05-2c329e9a6470.PNG)

2. By the way,  could you tell me what is the difference between the two exe files--- Openfast_x64.exe and Openfast_x64_double.exe? I see in Fastv8, there are also two exe  files for x64. Thanks a lot!!!

**Comment by jjonkman** [comment]
Dear @ChaoREN1994,

Here are my answers to your questions:

1. The pass/fail criteria in the OpenFAST r-test is quite sensitive to how the OpenFAST executable was compiled and which platform it is run on.  You can always plot the time series to see how large the differences actually are (considering how many cases passed, my intuition is that the results for the cases that failed are actually quite close).

2. These are executables of OpenFAST with single and double precision.  Normally I'd recommend running OpenFAST in single precision, which runs faster than the double-precision version and is typically accurate enough for engineering applications.  In fact, internal variables that require double precision use double precision even when compiling in single precision; compiling in double precision makes these variables use quad precision, which is typically not required.

Similar questions were discussed here: https://github.com/OpenFAST/openfast/issues/131.

Best regards,

**Comment by ChaoREN1994** [comment]
Thanks, @jjonkman 
1. I have seen the #131.  Thanks!
2.  By using the Openfast single precision or doule precision, I found something weird.
When I used the Openfast single precision, I run the module 5MW_OC4Jckt_ExtPtfm.fst (here I changed the name as OC4ExtPtfm.fst). It will have errors like this! It seems that the Inflow input file is not in  correct format and the same problem for the ExtPtfm.dat
![1](https://user-images.githubusercontent.com/66703137/84602313-b2fd0b00-ae86-11ea-8b0e-010ac97dbaa0.PNG)
![2](https://user-images.githubusercontent.com/66703137/84602314-b5f7fb80-ae86-11ea-9717-93f3f7e443d5.PNG)

While, run with Openfast double precision,  it will no have errors.
![3](https://user-images.githubusercontent.com/66703137/84602317-bee8cd00-ae86-11ea-91f9-8967753a10d3.PNG)
By the way, I replaced the inflow input file with one I used in FASTv8. Try to run with Openfast single precision, the problem of inflow input was settled. Only left the problem of ExtPtfm.dat


3. In addition,  I try to use the module of the 5MW_OC4Jckt_ExtPtfm.fst. I would like to know, is there a template for Guyan file format?  Can I just change the dimonsion in ExtPtfm_SE.dat with Flex 5 format like this? I tried run with this format for Guyan . It worked.
![4](https://user-images.githubusercontent.com/66703137/84602353-07a08600-ae87-11ea-9c1a-c687baf74c88.PNG)

And I saw the your discussions in (https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=2433&p=14023&hilit=ExtPtfm#p14023 ), is that format is still available？That’s for the whole ExtPtfm.dat not for the Guyan input matrices?


4.In the ExtPtfm.dat module, I saw the ouput lists would like to know that the differences between foreces in platform interface and reduced input forces at interface points?
The latter will be exported to feed the substruture model in FE software? Is that correct?
![5](https://user-images.githubusercontent.com/66703137/84602445-c9f02d00-ae87-11ea-87c4-e88da63d2f1c.PNG)


5. Have you any references or technical report about the 5MW_OC4Jckt_ExtPtfm module?

Thanks again for your reply.  Your reply help me a lot.  Looking forward to your reponses!

**Comment by andrew-platt** [comment]
It appears your single precision and double precision are different versions.

1.  single precision version info: OpenFAST-v2.3.0-dirty
2. double precision version info: OpenFAST-v2.3.0-85-g0eec1b42-dirty

The single precision version is from the 2.3.0 release, but your double precision version appears to have been compiled locally using the `/dev` branch.  There were changes in the InfloWind input file on the `/dev` branch that are not compatible with the `/master` branch (v 2.3.0).  Your input files are based on the `/dev` branch since those run.

**Comment by ChaoREN1994** [comment]
Thanks @andrew-platt  

Does that mean that all the input files of my complied Openfast can only run in OpenFAST_x64_Double.exe-v2.3.0-85-g0eec1b42-dirty?  Should I recompile Openfast based on OpenFAST-v2.3.0-dirty?  In addition, in OpenFAST-v2.3.0-dirty , does it not include  the 5MW_OC4Jckt_ExtPtfm module ?

Best regards

**Comment by rafmudaf** [comment]
@ChaoREN1994 If your end goal is to run `5MW_OC4Jckt_ExtPtfm`, then you'll need to recompile from the `dev` branch (or commit `0eec1b42`) as you've already done. Like I mentioned in https://github.com/OpenFAST/openfast/issues/467#issuecomment-642957209, you'll need to get the corresponding r-test for your chosen version of OpenFAST. The simplest way to do this is to checkout the `dev` branch and update the r-test git-submodule:

```bash
cd openfast/

###
git clean -f  # NOTE: this will delete all of your local changes to the source code
###

# Update your local version of OpenFAST and r-test
git fetch
git checkout dev
git pull
git submodule update

# Compile OpenFAST
cd build
make

# Then, go run your test case!
```

The `-dirty` part of your executable's version string means that you've changed something in the source code on your computer. It may be something minor like some additional spaces in a file, so if you want to have a clean version string then remove all local changes.

**Comment by ChaoREN1994** [comment]
Thanks @rafmudaf 

1. And Yes, my end goal is to run the 5MW_OC4Jckt_ExtPtfm. Thanks for your explanation! 

2. By the way, Do you have any references, tuturials or technical report about the 5MW_OC4Jckt_ExtPtfm module?  Or do you have any ideas about the questions (q3,q4)  I mentioned in (https://github.com/OpenFAST/openfast/issues/469#issuecomment-643813240)?Thanks a lot! 

Best regards
Chao REN

**Comment by rafmudaf** [comment]
Thats a question for @ebranlard. You could check out the two documents linked in https://github.com/OpenFAST/openfast/pull/344.

**Comment by ebranlard** [comment]
Hi @ChaoREN1994 

You'll find information about the ExtPtfm input files and outputs here: 
[ExtPtfm-DevelopmentPlan.pdf](https://github.com/OpenFAST/openfast/files/3698656/ExtPtfm-DevelopmentPlan.pdf)

You can indeed provide Guyan inputs by having a dimension of 6. 

The difference of output forces at interfaces correspond to the difference between ""f_C" and "f_r1" in the document. The most relevant output is the coupling force "f_C" (sensors `Intf*)`.  The other one, `f_r1` (sensors `Inp_F*`),  should correspond to the first 6 loads columns of the input file.

I hope that'll help!

**Comment by ChaoREN1994** [comment]
Thanks you!!! @ebranlard  @andrew-platt @rafmudaf 
You are really nice. Your replys really save my life!!!  Thanks again.

**Comment by ChaoREN1994** [comment]
Hello, @ebranlard 

I have another  question for the output lists in the ExtPtfm. For the Craig-Bampton reduction, I see the there are Modal displacement  and  Modal force in the ouput lists.   The modal forces correspond to the last 25 columns of the input file(ExtPtfm_SE).  Well,  for the Modal displacements,  are they also used to feed the FE model ? Or they just correspond to the modal forces?  In the Guyan reduction, only the forces  in Intrf are used to feed the FE model.  I am not familiar with the Craig-Bampton reduction.  How can I use the the modal displacement in Craig-Bampton reduction?   In addition, the selection  of modes in Craig-Bampton reduction,  How do I select?  Thanks in advance!!

Best regards!
Chao REN

**Comment by ebranlard** [comment]
In a Craig-Bampton reduction, you reduce your system into some leader degrees of freedom (also called "Guyan"), and some Craig-Bampton modes. 

ExtPtfm solves for the evolution of Craig-Bampton position and velocities. In the documentation these are noted `x_2` and `\dot{x}_2`, and these can be written as output. These outputs can be used with your FE model to plot the displacements and velocities of each node of the structure. ExtPtfm has no knowledge of the FE model and no knowldege of how the Craig-Bampton modes actually look like in terms of the nodal displacements of the FE model. 

If you only use the Guyan reduction, you don't have any Craig-Bampton modes, and these output are then irrelevant. 
  
You'll find more information about the CB-reduction in the above mentioned references:
[ExtPtm-Publication](https://github.com/OpenFAST/openfast/files/4411768/Branlard_2020_J._Phys.__Conf._Ser._1452_012033.pdf)
[ExtPtfm-DevelopmentPlan.pdf](https://github.com/OpenFAST/openfast/files/3698656/ExtPtfm-DevelopmentPlan.pdf)

**Comment by ChaoREN1994** [comment]
Thanks, @ebranlard 

1. Thanks for your explanation and references.  I would like to know, if i use Craig-Bamptom reduction,  for the 3rd step of reanalysis in the sequential approach (as showed in your figure),   only the intefaces time series of forces are used to feed the FE models. I can get stress distribution of FE model.  Also,  I can obtain the nodal displacement by the reanalysis?   In this case, the outputs of  Craig-Bampton position and velocities are useless to my study?  Is that correct ? 

![1](https://user-images.githubusercontent.com/66703137/84757289-412adb80-afc4-11ea-9aa4-0e9b179c2005.PNG)

2. In addition,  for the selection of modes in Craig-Bampton reduction, I saw there were 25 modes +  leader DOF in ExtPtfm_SE module.  Why ? Is there a rule to follow when selecting the modes of Craig-Bamptom reduction?  I saw that you gived two references paper for selecting modes.  Unfortunately, i can not find the first (DNV GL. Implementing an interface between Bladed and Sesam - Verification report of Sesam’s Bladed interface.)

3. In the discussion part of your paper, you mentioned that Gravity-buoyancy mode is not considered due to the fixed-interface nodes.  Does that means the free-interface nodes will include the Gravity-buoyancy mode?  Does Openfast of this version  support the free-interface  simulation?
Thanks in advance!

Best regards!
Chao REN

**Comment by ebranlard** [comment]
Hi Chao, 

1. You are correct, you won't need the displacements and velocities for the recovery step. Just the interface loads. 

2. I don't think I can answer this question fully. The best would be to perform convergence studies with different number of CB modes for a given structure. The number of modes will also drive your time step. The selection requires a knowledge of the structure, the relevant structural frequencies and excitation frequencies, and what is needed to be (or what can reasonably be) resolved. 25 is a typical round number, but the choice is problem specific. 

3. Some CB implementations take as input an extra mode referred to as the Gravity Buoyancy mode. We do not have this option currently. The alternative for now is to make sure you have sufficient CB modes to capture some of the vertical heaving of the structure. These modes have  usually fairly high frequencies. We unfortunately haven't had time to look into this in details due to time constraint. We hope to setup another project to work on this but that might not occur any time soon. 

Emmanuel

**Comment by ChaoREN1994** [comment]
Thanks @ebranlard 

Your replys help  me a lot to use the  5MW_OC4Jckt_ExtPtfm module.  Openfast of this verison,  i think , is enough for my simualtion and study.  Thanks again!

Best regards!
Chao REN
