### ISSUE TITLE
Elastodyn blade input files

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#470]
Hi openFAST team,

I see as we moved to the newer version of openFAST the second column in the Elastodyn blade input ``Aerocent" is changed to pitch axis. (I can see that as I turn on the echo) While there is robust definition of ``Aerocent" to help it being calculated, I am a bit blurry on the exact definition of ``pitch axis".  Any help regarding this definition?

Best Regards,
Tanmoy

**Comment by jjonkman** [comment]
Hi @tchatte3,

The change from AeroCent to PitchAxis in the ElastoDyn blade input file happened between FAST v7.02 and FAST v8.03.  Here is what is described in the FAST v8 ReadMe file regarding this change:*
> ElastoDyn’s blade input properties table no longer specifies AeroCent. Instead, it specifies the location of the pitch axis, PitchAxis, which is calculated as PitchAxis = 0.5 – AeroCent by the MATLAB conversion script. The PitchAxis input is used only in conjunction with AeroDynv14. The specification of aerodynamic center in AeroDyn v15 replaces the need for PitchAxis.

*Contents from the FAST v8 ReadMe file still need to get ported to OpenFAST readthedocs per issue #177.

I hope that helps.

Best regards,

**Comment by tchatte3** [comment]
Hi @jjonkman,

Thank you for the guidance. So, if I understand that correctly, since I am using Aerodyn v15, we should still be using ``aerocent" in the Elastodyn file, right?

**Comment by jjonkman** [comment]
Hi @tchatte3,

If  you are using AeroDyn v15, then the former AeroCent input, now PitchAxis input, in ElastoDyn is not used.  Instead, the aerodynamic offsets are defined in the AeroDyn v15 blade input file, via inputs BlCrvAC and BlSwpAC.

Best regards,

**Comment by tchatte3** [comment]
@jjonkman Thanks for the clarification. It makes perfect sense now.

Best regards,
Tanmoy
