### ISSUE TITLE
Question of Regression test 

### ISSUE THREAD

**Issue by hohaigx** [OpenFAST/openfast#472]
**Bug description**
Dear all
I try to run the regression Tests in Openfast. When I tested several 5WM offshore wind turbine files, I always encountered the error in the figure below. It seems that the blade mesh mapping of the blades in elastodyn and the blades in aerodyn. Their common feature is that they all use aerodyn 15, but I haven’t changed the content of the test files, I don’t know where is my problem?Could you give me some pointers? Thank you all.
**Screenshots, if applicable**
<Add screenshots to help explain your problem.>
![image](https://user-images.githubusercontent.com/61127382/85307889-102a3980-b4e3-11ea-960e-a273cd6416cf.png)

**Comment by andrew-platt** [comment]
Your executable is for OpenFAST 2.3.0, but based on the error from InflowWind, there is an issue with the test you are running.  Is the regression test from 2.3.0, or from a different version?

`Invalid logical input for file .... _InflowWind_12mps.dat occured while trying to read SumPrint`

This indicates your input file is not compatible with the OpenFAST 2.3.0 executable you are using.

**Comment by hohaigx** [comment]
Thanks for your reply, I am sorry, because of my mistake, the screenshot is wrong, I have edited and attached the correct screenshot, this is the error I encountered.

**Comment by andrew-platt** [comment]
Have you made any code changes?  It is showing the version `v2.3.0-dirty`.

**Comment by hohaigx** [comment]
I did not modify the code, I just compiled openfast 2.3.0 master.

**Comment by andrew-platt** [comment]
Ok. The `-dirty` part is likely because it rebuilt the `_Types.f90` files and changed the line endings to Windows line endings (this often sets `-dirty` from Git for some reason).

Which compiler did you use?

**Comment by hohaigx** [comment]
I used Visual Studio Community 2015 and Intel Fortran 16.0.

**Comment by andrew-platt** [comment]
This is an issue we have seen on rare occasions in the past with certain compiler configurations.  It is due to some numerical roundoff in the mesh mapping routine.  I'm surprised you are seeing this with this compiler combination.

Do you also see this issue if you use the precompiled binary from the release: https://github.com/OpenFAST/openfast/releases/download/v2.3.0/windows_openfast_binaries.zip ?

**Comment by hohaigx** [comment]
Thanks for your timely help, when I use the precompiled binary from the release and ww_ifort_redist_intel64_2017.8.275, the test can run normally. In addition, I followed your suggestion, I made a small edit to the last node location in the AeroDyn blade definition file and move that node inboard 1mm, and the same error still occurs. As far as I know the dev version does not have he precompiled binary, my purpose is to use the dev version of openfast, so I have replaced my compiler and use a higher version compiler to compile the dev version of openfast and it worked well .
