### ISSUE TITLE
Regression Test on Unix fails

### ISSUE THREAD

**Issue by 1fr9** [OpenFAST/openfast#473]
Hello,

we try to compile Openfast on a Unix server, but some regression tests fail (see picture).
It was compiled with Cmake on a GNU/Linux operating system with a AMD Ryzen Threadripper 2990WX 32-Core Processor. 

![image](https://user-images.githubusercontent.com/55579768/85386804-5499f180-b544-11ea-9c60-32e36638ed89.png)

There is no intel paralel studio (ifort, icc) installed on the server, could it be related?

**Comment by rafmudaf** [comment]
@1fr9 It sounds like your system is quite different than the environment where the Linux / GNU baselines are generated (Ubuntu virtual machine on a MacBook Pro host). Did you check the plots?

**Comment by 1fr9** [comment]
I have tried to create the plots with `python3 manualRegressionTest.py ../build/openfast.exe linux gnu 1e-5 -n -p`, but this is the result: 
![image](https://user-images.githubusercontent.com/55579768/85777781-38ec4200-b722-11ea-8c16-c35799cb72dc.png)

**Comment by rafmudaf** [comment]
You can add a `-v` flag to get verbose output that may help you identify what went wrong. The `-case <case_name>` flag will run a single case to keep the output short.

**Comment by 1fr9** [comment]
With the `-v` flag I got the `Error: executable at ../build/openfast does not have proper permissions.`

**Comment by rafmudaf** [comment]
Ah then it sounds like your executable doesnt have the correct permissions. Make sure its set so that your user can run it.
