### ISSUE TITLE
openFAST genertating unphysical Cp, C_t, with generator DOF and drive train DOF ON

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#476]
Hi openFAST team,

I am trying to simulate a rigid blade rigid tower model (all DOF's in blade/tower in Elastodyn = False). Currently I only have Elastodyn, Aerodyn and InflowWind modules active, the rest are switched off. When I set the generator DOF and the drive train DOF  =  false as well, I get constant rotor speed which perfectly makes sense. Additionally, I get physically consistent values of Cp, Ct, power etc. 

![image](https://user-images.githubusercontent.com/14302216/85619452-52ad5c80-b630-11ea-8df5-e5271cf8cf51.png)
![image](https://user-images.githubusercontent.com/14302216/85619798-d23b2b80-b630-11ea-8ab8-647d82d541f7.png)

However, when I turn on generator DOF And the drive train DOF = true, I start getting unphysical results: 

![image](https://user-images.githubusercontent.com/14302216/85619561-7bcded00-b630-11ea-8f79-6a96f9eceac7.png)
Rotor power settling to a negative value (generating is probably motoring?)

Any help as to why this might be occurring?

Best Regards,

**Comment by jjonkman** [comment]
Dear @tchatte3,

When enabling the generator DOF in ElastoDyn, I would guess you are not enabling some sort of generator or control model in ServoDyn.  In that case, I would guess what is happening is that the rotor is accelerating due to the aerodynamic torque until it reaches a (high) speed at which the aerodynamic torque drops to (near) zero.  The solution appears to oscillate in this state (after about 200 s) due to lack of damping.

Whenever you enable the generator DOF in ElastoDyn, you should also enable a generator or control model in ServoDyn.

Best regards,

**Comment by tchatte3** [comment]
@jjonkman  Thanks for the detailed and helpful explanation. Yes, I was not using control model at the point. But, if I switch off generator DOF, that would really mean: The power is being calculated by AerodynamicTorque X omega, where omega is the constant speed I set as initial conditions in Elastodyn, right?

Best Regards,

**Comment by jjonkman** [comment]
@tchatte3 -- Which power output from which module are you referring to?

**Comment by tchatte3** [comment]
@jjonkman  I am referring to rotorAeropower from Aerodynamics

**Comment by jjonkman** [comment]
@tchatte3 -- Yes, AeroDyn output RtAeroPwr is computed as the the aerodynamic torque times the rotational speed.

**Comment by tchatte3** [comment]
@jjonkman Thank you very much.

**Comment by GBA217** [comment]
Hi, 
I'm seeing a similar issue (unrealistically high Cp) in my ramp simulation of a 2MW machine.
![image](https://github.com/user-attachments/assets/3ca2de4f-6501-4fde-9a74-15dc29f28862)

Any leads about what could cause this would be really helpful.

TIA

**Comment by jjonkman** [comment]
Dear @GBA217,

As has been discussed on our forum (https://forums.nrel.gov/), by nature of its calculation within the aero-elastic solution, I would only use the power coefficient output (AeroDyn output `RtAeroCp` or `RtFldCp`) in a time-averaged sense to avoid apparent violations in the Betz limit that may occur instantaneously as a result of the calculation approach. The instantaneous values are effected by rotor acceleration / deceleration, and so, can instantaneously exceed the Betz limit.

Best regards,
