### ISSUE TITLE
Modal analysis and eigenfrequency

### ISSUE THREAD

**Issue by ChaoREN1994** [OpenFAST/openfast#479]
Dear all,

I woud like to know in Openfast 

1. Can I do the Modal analysis of the whole OWT with the foundation and get eigenfrequencies and mode shapes ? For example, I worked in 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth.

2. In addition, Can I just do the Modal analysis of the foundation and get eigenfrequencies and mode shapes ?(Jacket in the 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth case)

Thanks 
Chao REN

**Comment by jjonkman** [comment]
Dear @ChaoREN1994,

The model you are referring to includes a SubDyn model of the jacket foundation.  The full-system linearization functionality of OpenFAST does not yet support linearization with the SubDyn module enabled.  That said, we are currently working on implementing that capability.

SubDyn itself performs an eigenanalysis of the isolated substructure (without the influences of the supported turbine or hydrodynamics) and reports that eigensolution in the SubDyn summary file.

Best regards,

**Comment by ChaoREN1994** [comment]
Thanks, @jjonkman 

1. I have found that the eigenanalysis  of the isolated substructure in SubDyn summary file. Thanks!
2. Well, I have another question about the SubDyn module in 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth. I saw that for the fully-coupled simulation in FASTv8 and Openfast,  Openfast and Fastv8 use SubDyn with CB reduction (8 modes deflaut).  I would like to know why 8 modes and Have you done the convergence study of this?
3. In addition, I tried to use the SubDyn without the CB reduction.  I failed, even through I set the proper inital condition for the given wind speed following the 5MW wind turbine( https://www.nrel.gov/docs/fy09osti/38060.pdf), Also, i tried to set different time steps. But there always errors like this:
![2](https://user-images.githubusercontent.com/66703137/85950173-8bfd0980-b95b-11ea-9929-4bdf541d8c21.PNG)
Could you give me some advises? Thanks in advance!

**Comment by jjonkman** [comment]
Dear @ChaoREN1994,

Yes, there was a convergence study performed when selecting 8 Craig-Bampton modes for the OC4-jacket model.  You typically want to resolve the lowest frequency Craig-Bampton modes in your model (say, up to about 10 Hz) and treat the higher frequency modes statically (SttcSolve = True).

Your model is clearly going physically or numerically unstable, but I would not expect the warnings and errors you are receiving to be caused solely from eliminating Craig-Bampton modes.  The most important warning is the first one--about the small angle assumption violated in SubDyn, which suggests that the substructure is not holding up the supported wind turbine properly.  Did you change the mass, stiffness, or time step of the model?

Best regards,

**Comment by ChaoREN1994** [comment]
Thanks @jjonkman 

1. Thanks for your reply for the convergence study of the CB modes. 
2. Yes, I did change the time step of model from 0.01s to 0.005s. But following you reponses, I resetted the time step as 0.01s , these was still the same warnings and errors as showed in the following:
![2](https://user-images.githubusercontent.com/66703137/86039038-26d01380-ba42-11ea-894c-74833a4e7495.PNG)
![1](https://user-images.githubusercontent.com/66703137/86039050-29cb0400-ba42-11ea-806a-d6dafd7a1040.PNG)

If it is not the problem of time step,  what maybe result in the errors for the SubDyn simualtion without the CB reduction? I did not change the mass and stiffness of the model. Thanks!

3. In addition, SubDyn simulation with or without the CB reduction will result in big differences of the nodes forces and displacments in the jacket foundation?  As you reponsed,  8 Craig-Bampton modes for the OC4-jacket model were selected based on the convergence study.  But in the @ebranlard paper (Superelement reduction of substructures for
sequential load calculations in OpenFAST) for the comparison between fully coupled and sequential coupled simulation,  he used 25 Craig-Bampton modes for both cases.

**Comment by jjonkman** [comment]
Dear @ChaoREN1994,

Does the original jacket test case (I presume you are running the following case in the OpenFAST v2.3 r-test: https://github.com/OpenFAST/r-test/blob/master/glue-codes/openfast/5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth/5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth.fst) run without problems?  What have you changed in the input file(s) between this test and your simulation?  I suspect that you are changing more than just `Nmodes` in SubDyn.

@ebranlard can correct me if I'm wrong, but the paper you are referring did not include a convergence test, did not compare loads within the jacket structure, and did not use the static-improvement method (which is only important for computing loads within the jacket structure, not the loads transmitted back to the turbine).

Best regards,

**Comment by ebranlard** [comment]
I'm guessing that is a time step issue, if you use `CBMod=False`, then you are effectively using all the structure degrees of freedom, which can have very large frequencies, so you'll require a very small time step. 

I'd recommend using `CBMod=True`, and slowly increasing the number of modes, starting from 0 (Guyan), and up. As you increase the number of modes, you'll likely have to decrease the time step. 

When you observe issues like this, there is likely an error in the model (structure, controller, initial conditions or time step) you can try some of the following:
   - Set all turbine DOFs to False
   - Remove the controller `CompServo=0`
   - Remove turbulence `WindType=1`
  - Use Guyan reduction (`CBMod=True, Nmodes=0`)
You can introduce more DOF progressively, noting that the following DOFs are sensitive and should be turned on last:
   - Drive Train torsion DOF can be quite sensitive to the controller and the initial conditions
   - Yaw DOFs, also sensitive to the controller and initial condition (if `YawNeut` and `NacYaw` don't match), but also sensitive to `PtfmYIner` which is typically required to respond to the platform/substructure yaw DOF

**Comment by ChaoREN1994** [comment]
Thanks   @ebranlard @jjonkman 

I will try what you advise @ebranlard. Later, I will give you feedback.

Thanks again!
Chao REN
