### ISSUE TITLE
Errors in using ExtPtfm module

### ISSUE THREAD

**Issue by hohaigx** [OpenFAST/openfast#485]
Dear all
I am trying to use the ExtPtfm module in the developer version. I used OC3Monopile as my test object. I established the same foundation as OC3Monopile in the FEM software. Only the gravity load was applied, and the 4 CB modes was generated. The corresponding mass matrix, stiffness matrix and damping matrix and time load time history are shown in the figure. And only Elastodyn and ExtPtfm modules were opened during the analysis. However, during the calculation, the error prompt shown in the figure appears. The method for solving this error on the forum is usually to reduce the time step, but this does not seem to solve the problem.Can you give me some suggestions? Thank you all.

> 
![image](https://user-images.githubusercontent.com/61127382/86589651-a0c34800-bfc0-11ea-8fa1-e1904307fb5c.png)

![image](https://user-images.githubusercontent.com/61127382/86589429-45915580-bfc0-11ea-9a61-bf5411779657.png)

**Comment by jjonkman** [comment]
Dear @hohaigx,

Which time steps have you tried and how small did you get?

I would suggest simplifying the model further to debug, e.g., eliminate structural DOFs from ElastoDyn.  Does the solution work as expected with only the platform-heave DOF enabled (PtfmHvDOF = True, all other false)?  Which DOF(s), when enabled, cause issues?

Best regards,

**Comment by hohaigx** [comment]
Thank you for your prompt reply. The minimum time step I used was 0.005s. According to your suggestion, I tested and set each one ptfmDOF to be true and the others to be false, but no one could solve the problem. Only when all of them were set to be wrong could they be run.

**Comment by jjonkman** [comment]
Dear @hohaigx,

I see in your ExtPtfm matrices that you use 1 for the diagonal entries of the mass matrix for the Craig-Bampton modes (7-10).  Thus, the corresponding stiffness entries represents the natural frequencies in rad/s squared.  The highest stiffness entry, 130921 (rad/s)^2, represents a natural frequency of 57.6 Hz.  According to the time step rule of thumb discussed on the forum, this would require a time step of 1/(10*57.6) = 0.0017 s.

Best regards,

**Comment by hohaigx** [comment]
Thank you very much for your help. When I reduced the time step to 0.0017s, it worked.
