### ISSUE TITLE
Induction field/ rotor averaged velocity

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#489]
Hello openFAST team,

I am wondering if there is an outputChannel available (I do not see any thing in the .xlsx file) to tap out the average induction factor or rotor averaged velocity at the disc. To summarize, I am wondering if there is a way to read/visualize the induction effects directly when I am using an induction model at openfast. 
When running stand-alone openfast runs with InflowWind (say with uniform velocity), the velocity at hub-height that we tapout is the one prior to applying induction.

Best Regards,

**Comment by ebranlard** [comment]
Hi @tchatte3, 
I'm not aware of such channel, but we can try to include it in a future release. I agree that it can be useful to get both the rotor-averaged quasi-steady induction, and the rotor-averaged dynamic induction (includes dynamic inflow). We have the rotor average wind speed (`RtVAvgxh`),this does not include induction, but include tower shadow, turbulence, shear. 

The integrated thrust coefficient (`RtAeroCt`) is a reasonable measure of induction (low Ct, low induction, high Ct, high induction). 
You can use `a=1/2 (1-sqrt(1-Ct) ` as an approximation to get the average induction, but this will fail for `a>0.5` (and even lower). You can try using the empirical `a-Ct` relationship from Buhl (in the AeroDyn manual) to get induction values at high Ct. This will give you an approximation of the average induction.

**Comment by tchatte3** [comment]
Hi @ebranlard, I was actually using ``a=1/2 (1-sqrt(1-Ct)" to get the estimate, but you have a suggested a very good alternative. I think Buhl's relation will be a better approximation. Thank you for incite.
