### ISSUE TITLE
Blade mass

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#493]
Hi openfast dev. Team,

I have a question related to blade mass. In the Elastodyn file, I specify the BMassDen [kg/m] at different blade stations. When I perform integral of the BMassDen  [kg/m] along BlFract locations, I get the expected value of Blade mass in kg for my particular model blade that I am working on. However I look at the .SUM file from Elastodyn module I see that it reports a different blade-mass, which ~3% off from the expected value. I am currently running openfast with a with precone of -4 dgrees.

Any suggestions, where I am missing something? 

Best Regards,
Tanmoy

**Comment by jjonkman** [comment]
Hi Tanmoy,

My guess is that way you are integrating the distributed blade mass to the total blade mass is a bit different than the way ElastoDyn is doing the integration.  ElastoDyn will interpolate the user-specified mass distribution (BMassDen) to the evenly spaced blade structural analysis nodes (defined by BldNodes), which are located at the centers of the elements.  (The interpolated values and element lengths are reported in the ElastoDyn summary file.)  These interpolated values are then integrated using rectangular integration (i.e., the sum of the mass per unit length at each structural analysis node times its corresponding element length).

Best regards,

**Comment by tchatte3** [comment]
@jjonkman .Thank you for a prompt and quick response. This is really helpful. I see variables RNodes and DRNodes being reported in the interpolated blade sections in .SUM file. Indeed, it seems DRNodes are the element lengths and RNodes are element center locations, so I do see the difference. 

Thank you and Best Regards,
Tanmoy
