### ISSUE TITLE
Using DISCON for a different turbine

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#495]
Hi openfast developers team,

I am trying to see if I an use DISCON.dll for a different turbine other than NREL 5MW. I see in the Servodyn file, the section below the ``Bladed Interface `` has several parameters for pitch and generator that can be tuned for the needs. Is this sufficient or the parameters section in DISCON.f90 also needs to be changed?

Any guidance/help regarding this matter?

Best Regards,
Tanmoy

**Comment by jjonkman** [comment]
Hi @tchatte3,

The "BLADED INTERFACE" section of the ServoDyn input file contains input parameters that are defined in Bladed and sent to the _DISCON.dll_, but it is up to the developers of the _DISCON.dll_ whether these parameters are used or not.  In the case of the baseline controller for the NREL 5-MW turbine, these parameters are not used by the _DISCON.dll_, and so, setting there values would have no influence on the simulation results.  Instead, the parameters of the _DISCON.dll_ for the baseline controller of the NREL 5-MW turbine are set at the top of the corresponding _DISCON.f90_ source file.  You'd have to change these parameters and recompile the DLL for application of the controller to a turbine different from the NREL 5 MW.

That said, the ROSCO Toolbox may provide a more straightforward way to develop a baseline DISCON controller for a new turbine: https://github.com/NREL/ROSCO_toolbox.

Best regards,

**Comment by tchatte3** [comment]
@jjonkman This is very helpful. I would also look at the ROSCO toolbox for this.

Best Regards,
Tanmoy
