### ISSUE TITLE
Power Fluctuations in 5MW NREL wind turbine 

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#500]
Hi openfast dev. Team,

This is question directed towards my better understanding of the aero-power. 
![image](https://user-images.githubusercontent.com/14302216/87813618-4338c200-c830-11ea-9b12-bd745df08991.png)
The plot here shows Aero-power at differnt wind speeds. The Green plot is the one corresponding to wind speed 20mps [supplied via InflowWind module. Velocity ~ 20 mps uniform profile. ].  All the results that I obtain from the simulations, when time-averaged, perfectly falls on the NREL power-curve chart. 

I am actually confused about the oscillations of the Aerodynamic power for 20mps wind (greater than rated wind speed), which is quite high ~ 0.5MW 1MW. The black curve corresponds to 11.4 mps (rated speed), where the oscillations are much smaller. Could somebody provide a physical explanation as to why the power oscillations are increasing as we are reaching the flat aero-power trend in the power curve chart. 

Best Regards,

**Comment by andrew-platt** [comment]
What aerodynamic effects do you have turned on? Tower potential or tower shadow?

Try plotting those as a function of azimuth.  I suspect you will find the dips correspond to where a blade passes the tower.

**Comment by ebranlard** [comment]
Since you are likely operating at uniform wind, the fluctuations of the aerodynamic loads with azimuth are most likely due to: shear, tilt, and tower shadow (and turbine motions).
Most likely what you are seeing is due to the "tower shadow" (TwrPotent and TwrShadow in the AeroDyn file). The tower potential flow model is a function of the mean wind speed, so you might expect larger fluctuations there.

**Comment by tchatte3** [comment]
@andrew-platt : I have both Tower potential and Tower shadow switched on. Yes, I am using RtAeroPwr. Thanks, I will plot it vs. blade azimuth. 

 @ebranlard Thanks, this is a very helpful input. I will try to decouple the tower shadow effects.

**Comment by tchatte3** [comment]
@ebranlard @andrew-platt. This was verified to be a tower model effect. Thanks and closing this issue.
