### ISSUE TITLE
Segmentation fault when attempting to run OpenFAST

### ISSUE THREAD

**Issue by jdinius-dev** [OpenFAST/openfast#501]
**Bug description**
calling openfast from the command line results in a Segmentation fault. 

**To Reproduce**
<Update the following list with your specific information.>
1. Compile openfast as described in the documentation
2. input openfast to the command line
3. Segmentation fault error returned. A screenshot of the output is provided below
![image](https://user-images.githubusercontent.com/66981721/87830795-1049fa80-c83f-11ea-9ccf-51a9505da97e.png)

**OpenFAST Version**
I am using the latest version from the dev branch

**System Information (please complete the following information):**
 - OS:Ubuntu 20.04
 - Compiler: GNU Fortran (Ubuntu 9.3.0-10ubuntu2) 9.3.0
 - Compiler settings: -DCMAKE_BUILD_TYPE=RelWithDebInfo
Any assistance is greatly appreciated.

**Comment by andrew-platt** [comment]
Which branch did you compile?

**Comment by jdinius-dev** [comment]
I compiled the dev branch

**Comment by ebranlard** [comment]
We recently (5hours ago) merged a pull request into dev. The latest commit is  `5aacf65`. Can you pull or confirm that you use this commit,  just to be sure we talk about the same commit?  
Can you try to compile with the debug option: `-DCMAKE_BUILD_TYPE=Debug ` ? This should get a stack trace and reveal which line of code is problematic.
Sometimes, such segmentation fault occur when recompiling and the toolchain picks up some wrong objects. I'd advise to delete the entire build directory before you recompile (it's usually not necessary, but this might be one of these cases..).

**Comment by rafmudaf** [comment]
Also, try this command:
```
openfast -v
```

**Comment by jdinius-dev** [comment]
I am on the most recent dev commit, and rebuilt with the debug option, and used the openfast -v command. The exact same error occurs.

**Comment by ebranlard** [comment]
Thanks. 
Out of curiosity, can you run the following before to extend the stack size: `ulimit -s` unlimited
I'll try to install gfortran 9.3 and give it a try.

**Comment by jdinius-dev** [comment]
Tried it. Still the same error. I should be able to just run `openfast` or `openfast -v` and have something happen right?

**Comment by ebranlard** [comment]
yes, and to test it, you can just run:  ```./glue-codes/openfast/openfast -v ```  from the build directory, it should display some info to screen.  (The reason I'm precising this is on your screenshot you typed "openfast" and not "./openfast" so I'm guessing it's installed somewhere on your system, I'm not sure if that could be an issue too )

**Comment by ebranlard** [comment]
I have now tested it on debian 10.4, 64 bit, with `gcc 9.3.0-15` and didn't have an issue. I haven't tried on Ubuntu.

**Comment by jdinius-dev** [comment]
OK, running that  code actually caused openfast to run properly. I seemed to just be calling it wrong. I did not install openfast, I just compiled it. trying `./openfast` just returns No such file or directory. Now I have another issue. I was given a model to run to get familiar with openfast but I cannot seem to get it to execute. Trying gets the error output in the screenshot below. Pretty sure I'm just doing something wrong Any advice? Also, thanks for all the help. 
![image](https://user-images.githubusercontent.com/66981721/87840583-a856dc80-c85d-11ea-82dd-a4b664215f8f.png)

**Comment by ebranlard** [comment]
The dev version requires some modifications of the input files compared to version 2.3. 
These changes are listed here:
    https://openfast.readthedocs.io/en/dev/source/user/api_change.html
And you'll find examples here:
         https://github.com/OpenFAST/r-test/blob/dev/glue-codes/openfast/5MW_Land_BD_DLL_WTurb/5MW_Land_BD_DLL_WTurb.fst

Note that these are all "dev" repository, and not "master" (which corresponds to version 2.3) 


Regarding your previous issue, try to type `which openfast` to see what kind of executable was run when you just types `openfast`.

**Comment by jdinius-dev** [comment]
Thanks for the help. I tried to edit the .fst file but was unsuccessful in getting it to work (though the error changed slightly) I'll just switch back to the master branch as it should be fine for the work I'm doing and will actually be more in line with my team. Unfortunately, that didn't solve my issue. I'm getting a different error now, but  an error nonetheless. It seems to be related to AreoDyn.dat this time. A screenshot is attached below. Also, it should be noted this came packaged with an executable for Windows. Is it possible that the inputs could be set in such a way that they only work on Windows and not Ubuntu? I doubt it, but I thought I'd mention it just in case so I don't waste everyone's time. 

![image](https://user-images.githubusercontent.com/66981721/87858614-6b85f680-c8ec-11ea-8b25-6a7b588e54e8.png)

Also, the command `which openfast`returns `/usr/loca/bin/openfast`I checked that location and there is indeed an openfast executable there. I don't know if I'm supposed to set something else up for that to work or if I just need to continue using that long call line. If there is a way to get just typing `openfast`to work I'd be happy to hear it.
Once again thanks for all the help.

**Comment by ebranlard** [comment]
It's usually safest to use a full path to the openfast executable, so that you know which version you run. If you want to have the  `openfast` command available in your terminal, you can follow some general procedures depending on your OS (for instance: you can add the parent folder to your `path` environment variable, you can set a bash alias, you can copy the binary to your `/usr/local/bin`). There will be some priorities between the different options, so you'll have to check with the command `which`.

**Comment by jdinius-dev** [comment]
Ok, thanks to everyone for the help. It seems to be working now. I'm going to close the issue.
