### ISSUE TITLE
Build time for FAST_Subs.f90

### ISSUE THREAD

**Issue by sayerhs** [OpenFAST/openfast#503]
Compiling OpenFAST on Linux with GCC 7.4.0 takes a long time. Almost all the time is spent compiling one file `FAST_Subs.f90` with timers indicating almost 25 minutes spent in compiling this file. 

With `RelWithDebInfo` (compilation flags `-O2 -g`) also generates the following warnings

```
[ 96%] Building Fortran object modules/openfast-library/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o
/ccs/proj/cfd142/exawind/exawind-2020-07/source/openfast/modules/openfast-library/src/FAST_Subs.f90:6574:0:

 SUBROUTINE FAST_RestoreFromCheckpoint_Tary(t_initial, n_t_global, Turbine, CheckpointRoot, ErrStat, ErrMsg  )

note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
/ccs/proj/cfd142/exawind/exawind-2020-07/source/openfast/modules/openfast-library/src/FAST_Subs.f90:6782:0:

 SUBROUTINE FAST_RestoreForVTKModeShape_Tary(t_initial, Turbine, InputFileName, ErrStat, ErrMsg  )

note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
```

**Comment by andrew-platt** [comment]
`FAST_Subs.f90` does take a long time to compile.  I honestly don't know if it is something we will attempt to speed up or not given the amount of re-architecture required to address it.

I have noticed the variable tracking message as well on Ubuntu VM compiles, and on Mac compiles.

**Comment by rafmudaf** [comment]
I have an [old branch](https://github.com/rafmudaf/openfast/tree/feature/fast_subs) where I tried to improve the compile time by pulling things out of the huge FAST_Subs module. No such luck. In the end, using `-O2` / `RELWITHDEBINFO` sped it up enough for me. This is also what motivated the use of the version module so that changing the git-commit didnt require recompiling FAST Subs.

I had forgotten that I split out a `FAST_VTK` module. @akey7 may be interested in that.

**Comment by andrew-platt** [comment]
Given how `FAST_Subs` is structured, would we be able to set `-01` for that module without incurring too much run-time penalty?

**Comment by sayerhs** [comment]
@rafmudaf the above timings were from `RELWITHDEBINFO`, and why I am seeing variable tracking assignment warnings.

**Comment by andrew-platt** [comment]
I have noticed the compile times for `FAST_Subs.f90` are significantly improved with gfortran 9.3 compared to gfortran 7.4.

**Comment by bjonkman** [comment]
This may be a long shot, but you might try changing 
```
   TYPE(FAST_TurbineType),   INTENT(  OUT) :: Turbine(:)          !< all data for one instance of a turbine
```
to
```
   TYPE(FAST_TurbineType),   INTENT(INOUT) :: Turbine(:)          !< all data for one instance of a turbine
```
in `FAST_RestoreFromCheckpoint_Tary`.

I recall that change fixed a warning similar to the "note: variable tracking size limit exceeded" one in the `FAST_RestoreFromCheckpoint_T` routine. Not sure that will help the overall compile time, though.

**Comment by sayerhs** [comment]
I can confirm @andrew-platt 's observations regarding GCC 7.4.0 and GCC 9.1.0

| File | GCC 7.4.0 | GCC 9.1.0 |
|--|--|--|
| `FAST_Types.f90` | 5:27 | 4:33 |
| `FAST_Subs.f90` | 33:25 | 13:20 |
| `FAST_Library.f90` | 10:52 | 9:07 |
| `FAST_Prog.f90` | 7:39 | 7:19 |

**Comment by andrew-platt** [comment]
Woah!  That's a dramatic difference in FAST_Subs.f90!

**Comment by rafmudaf** [comment]
Whoa. I'll be upgrading asap.

**Comment by jwpeterson** [comment]
Sorry for commenting on a closed issue, but I just wanted to mention that on my system
```
$ f95 --version
GNU Fortran (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```
for the step
```
[ 96%] Building Fortran object modules/openfast-library/CMakeFiles/openfast_postlib.dir/src/FAST_Subs.f90.o
```
it took about 21.5 minutes and, perhaps more disconcertingly, 22.9% of RAM. Since my laptop has 32 GB of RAM, this corresponds to about 7.3 GB of RAM used by the compiler, which I imagine could start to be an issue for systems with only 8GB of RAM? Has anyone checked whether GCC 9.1.0 is any better on memory usage in addition to being faster?

**Comment by sayerhs** [comment]
@jwpeterson Please see this post https://github.com/OpenFAST/openfast/issues/503#issuecomment-663089975

**Comment by jwpeterson** [comment]
> Please see this post 

@sayerhs yes, I saw your table. It's very helpful, but my question was mainly about whether memory usage on the newer compiler is any lower.

**Comment by crobarcro** [comment]
I have the same issue as @jwpeterson. It actually freezes my laptop with 16GB of ram after a while as it gobbles up all the memory. 

```
$ gfortran --version
GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

**Comment by andrew-platt** [comment]
In addition to faster compile times with later versions of gfortran, the memory usage in gfortran 8, 9, 10 is lower during compile.  Can you upgrade your compiler to one of these versions?
