### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Akheelakk** [OpenFAST/openfast#509]
Hey,
I am a new user of OpenFAST. Installed the code as per the Documentation file and during the 'build' operation, I found some errors as given below.
![image](https://user-images.githubusercontent.com/67406965/88195012-21d73c00-cc5d-11ea-8e7f-420a6898b794.png)
The output window is as follows
1>------ Build started: Project: MAP_dll, Configuration: Release x64 ------
1>freedata.c
1>jacobian.c
1>lineroutines.c
1>mapapi.c
1>maperror.c
1>mapinit.c
1>numeric.c
1>outputstream.c
1>residual.c
1> Creating library ....\build\bin\MAP_x64.lib and object ....\build\bin\MAP_x64.exp
1>Generating code
1>4 of 293 functions ( 1.4%) were compiled, the rest were copied from previous compilation.
1> 0 functions were new in current compilation
1> 4 functions had inline decision re-evaluated but remain unchanged
1>Finished generating code
1>MAP_dll.vcxproj -> C:\openfast-master\vs-build\MAPlib....\build\bin\MAP_x64.dll
C:\openfast-master\modules\nwtc-library\src\SysIVF.f90 : warning: Module 'x64\Release\syssubs.mod' is created by both 'C:\openfast-master\modules\nwtc-library\src\SysIVF.f90' and 'C:\openfast-master\modules\nwtc-library\src\SysMatlabWindows.f90'.
2>------ Build started: Project: FASTlib, Configuration: Release x64 ------
2>Performing Pre-Build Event...
2>fatal: not a git repository (or any of the parent directories): .git
2>fatal: not a git repository (or any of the parent directories): .git
2>Creating library...
2>
2>Build log written to "file://C:\openfast-master\vs-build\FASTlib\x64\Release\BuildLog.htm"
2>FASTlib - 0 error(s), 0 warning(s)
3>------ Skipped Build: Project: OpenFAST-Simulink, Configuration: Release_Matlab x64 ------
3>Project not selected to build for this solution configuration
4>------ Build started: Project: FAST, Configuration: Release x64 ------
4>Performing Pre-Build Event...
4>fatal: not a git repository (or any of the parent directories): .git
4>fatal: not a git repository (or any of the parent directories): .git
4>Linking...
4>ipo: error #11018: Cannot open C:\openfast-master\build\bin\Registry.lib
4>LINK : fatal error LNK1181: cannot open input file 'C:\openfast-master\build\bin\Registry.lib'
4>
4>Build log written to "file://C:\openfast-master\vs-build\FAST\x64\Release\BuildLog.htm"
4>FAST - 2 error(s), 0 warning(s)
========== Build: 2 succeeded, 1 failed, 1 up-to-date, 1 skipped ==========

**Comment by andrew-platt** [comment]
Which branch are you compiling?

It appears that you downloaded the source code as a zip file rather than cloning it as a git repository.  Is that correct?

**Comment by bjonkman** [comment]
Just to explain some of the output you are showing:
1. `fatal: not a git repository (or any of the parent directories): .git` is caused when the code tries to get the version of a git repository somewhere that isn't a git repository. This error tells me you either downloaded an archive from GitHub or copied the code from someplace else. Though it says "fatal", the code should still compile. It just won't have the correct version numbering, and it will be very difficult to determine what version you have and if there have been any changes.
2. `error #11018: Cannot open C:\openfast-master\build\bin\Registry.lib` and the associated `fatal error LNK1181` are the errors that are causing concern. Project FAST should not be attempting to link with Registry.lib at all. You need to figure out why.

Can you look at the **FAST_Registry** project's property page and show what `Configuration Properties->General` looks like? The `Platform Toolset` and `Configuration Type` are probably the 2 fields that matter the most.

The other thing you need to check is what linking properties are set in the **FAST** project's property pages. You should look at `Configuration Properties->Linker->General` and `Configuration Properties->Linker->Input` to see if there are any non-default (shown in bold) settings. If you haven't changed this, it shouldn't be a problem. But without a git repository where you can ask for a difference, you'll have to manually check it.

**Comment by Akheelakk** [comment]
Thank you andrew-platt and bonnie jonkman. 
I guess what you said is correct regarding source code. This is how my FAST_registry property page and FAST property pages look like.
![image](https://user-images.githubusercontent.com/67406965/88200943-7631ea00-cc64-11ea-88a7-ae3bd9325ff1.png)
![image](https://user-images.githubusercontent.com/67406965/88201176-c6a94780-cc64-11ea-85b4-a5477b1f72c8.png)
![image](https://user-images.githubusercontent.com/67406965/88201230-d759bd80-cc64-11ea-8c72-e9a42df33130.png)

**Comment by bjonkman** [comment]
That all looks normal to me. I'm not sure if it's a difference in versions of Intel and/or Visual Studio or what. 

You could try this: Right click on the FAST project in the Solution Explorer window. Then select `Build Dependencies->Project Dependencies`. Uncheck the **FAST_Registry** box (you're telling Visual Studio that the FAST project doesn't depend on the FAST_Registry executable). Then try to build the solution again. (I would **NOT** do "rebuild".)

**Comment by Akheelakk** [comment]
Thank you very much. It worked now without any error or warning. Since there were some fatal commends in the output window, I am pasting it along with this message. I wonder if my results would be wrong as I run the program with input in the future because of this change (unchecking **FAST_Registry**)

C:\openfast-master\modules\nwtc-library\src\SysMatlabWindows.f90 : warning: Module 'x64\Release\syssubs.mod' is created by both 'C:\openfast-master\modules\nwtc-library\src\SysMatlabWindows.f90' and 'C:\openfast-master\modules\nwtc-library\src\SysIVF.f90'.
1>------ Skipped Build: Project: OpenFAST-Simulink, Configuration: Release_Matlab x64 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: FAST, Configuration: Release x64 ------
2>Performing Pre-Build Event...
2>fatal: not a git repository (or any of the parent directories): .git
2>fatal: not a git repository (or any of the parent directories): .git
2>Linking...
2>
2>Build log written to  "file://C:\openfast-master\vs-build\FAST\x64\Release\BuildLog.htm"
2>FAST - 0 error(s), 0 warning(s)
========== Build: 1 succeeded, 0 failed, 3 up-to-date, 1 skipped ==========

**Comment by bjonkman** [comment]
As I mentioned a couple comments above, those fatal comments are there because you don't have a git repository. The version number displayed will be wrong, but it won't affect any simulation results.

Unchecking the FAST_Registry dependency would not have any effect on the simulation results, either. It would only affect the build process--you'd know if it was a problem because it wouldn't rebuild. I think FASTlib still has a dependency on the FAST_Registry, so I don't think this change will have any adverse effects.

**Comment by Akheelakk** [comment]
Thank you very much madam. I really appreciate your patience. If what I remember is correct, I followed the path 
git clone https://github.com/OpenFAST/OpenFAST.git > code (green coloured tab) > Download zip.

**Comment by Xiangheng-Feng** [comment]
Dear friends:
     I met a error when I  tried to build OpenFAST-Simulink_x64;  I will appreciate it very much if anyone can help me to fix this problem.
fatal error LNK1104: can not open file “D:\software\MATLAB2018\extern\lib\win64\microsoft\libmex.lib -qm64 x64\Release_Matlab\FAST_Library.obj E:\OPENFAST\openfast\build\bin\FASTlib_x64_Matlab.lib”
![1602663697(1)](https://user-images.githubusercontent.com/69778937/95962764-62e48400-0e39-11eb-887e-11f5d3dd9730.jpg)
