### ISSUE TITLE
TurbSim and OpenFAST running very slowly on Ubuntu

### ISSUE THREAD

**Issue by jdinius-dev** [OpenFAST/openfast#514]
**Bug description**
I'm attempting to replicate the results of a coworker's simulation in order to learn OpenFAST, but TurbSim and OpenFAST are taking a very long time to run. My estimated completion time on OpenFAST is about 4 hours compared to my coworker who took about 45 minutes to run it on similar hardware (using Windows instead of Ubuntu), and I had to reduce the grid size from 41x41 to 21x21 to get TurbSim to finish. When running OpenFAST I also get the following warning: ` FAST_InitializeAll:HydroDyn_Init:Waves_Init:VariousWaves_Init: The random number generator in use
 differs from the original code provided by NREL. This pRNG uses 8 seeds instead of the 2 in the
 HydroDyn input file.` in case that's relevant to the problem

**OpenFAST Version**
<Please provide as much detail as possible including git commit. The best information is a screenshot of the OpenFAST system description that prints when running OpenFAST:>

```
**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.3.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Jul 24 2020
  - Time: 13:48:16
 Execution Info:
  - Date: 07/24/2020
  - Time:17:38:37-0600
```

**System Information**
 - OS: Ubuntu 20.04
 - Compiler: Gfortran 9.3.0
 - Compiler settings: Build_Type=Release (All flags left as default values)
 - CPU: AMD Ryzen 5 2500-U (Speed 3.0 GHz)
 - Memory: 12 GB

**Additional Context**
I've also checked the API changes since this model was made for version 2.2.0 and ensured all my input files are updated accordingly (double checked with a coworker who was able to run the simulation).

**Comment by andrew-platt** [comment]
Which compiler was used on windows?  The Windows binaries we distribute are built using the Intel Fortran compiler.

We have noticed significant differences in execution time between `gfortran` and the Intel Fortran (`ifort`) on identical hardware. The Intel compilers are much better optimized for performance.

If you have access to an Intel Fortran compiler on Ubuntu, that will help significantly.  One other thing that you can do on Ubuntu is compile in single precision.  We have noticed very large differences in runtime between single and double precision compiles.

**Comment by jdinius-dev** [comment]
Unfortunately I do not have access to the Intel Fortran compiler (I've also heard it doesn't play nice with AMD CPUs). I'll ask my coworker what compiler he used. I'll also try single precision and see where that goes. Thanks for the quick response.

**Comment by jdinius-dev** [comment]
Alright. Switching to single precision seems to have solved the issue and my run times are now reasonable. Thanks for the help.
