### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by KnowNothingButTry** [OpenFAST/openfast#516]
I compiled FAST_SFunc.mexw64 of openfast 2.3.0 version. Examples in the Certest folder could be run in Matlab. I noticed that accelerations output from S-function in FAST V6 can be integrated to get velocities and displacements, and then returned to the S-function block with FAST equations of motions. Does this mean that the S-function in FAST v6 has input interfaces of velocities and displacements? Are there similar input interfaces in the newest openfast 2.3.0? Or is there any other way to get the acceleration information of given displacements and velocities?
FAST v6:
![image](https://user-images.githubusercontent.com/68947524/88801041-a6850580-d1db-11ea-86d6-80175932c1a6.png)

openfast:
![image](https://user-images.githubusercontent.com/68947524/88801124-ccaaa580-d1db-11ea-8397-268738638503.png)

I look forward to your reply and help. Thank you!

**Comment by bjonkman** [comment]
I recommend you read the section `Major Changes Between the FAST v7 and v8 Interfaces to Simulink` in the FAST8 ReadMe, which describes the same differences between the Simulink interface in FAST6 and OpenFAST (that file is now located at https://drive.google.com/drive/folders/10Pw8zzOr_YqIgtLmq10XhYpdAveKAWAJ?ths=true. )

In OpenFAST, the states are not integrated in Simulink, but are instead integrated inside the FAST_SFunc block. If you want to see accelerations, you should select those variables for output in the modules' input files. The accelerations of the internal degrees of freedom that were in FAST6 are available in ElastoDyn, though that may not be exactly what you want. The available output channels are listed in the `OutListParameters.xlsx` file (see for instance https://github.com/OpenFAST/openfast/blob/dev/docs/OtherSupporting/OutListParameters.xlsx)

**Comment by KnowNothingButTry** [comment]
Thank you very much for your help! I have read the docement you gave me, and understand what you mean. 

My goal is to develop a surrogate model of the exact original dynamic model of wind turbine, so I need the value of acceleration (qdotdot) when any initial conditions (q_init, qdot_init) and control inputs are passed to openfast.exe or FAST_SFunc.mexw64.
![image](https://user-images.githubusercontent.com/68947524/88997016-35e80100-d321-11ea-967b-9398a23532e2.png)

could you give me some suggestions? if it useful to modify the source code in the SUBROUTINE Init_ContStates() of ElastoDyn.f90? That is to say, to set a nonzero initial rate for "Initial fore-aft tower top displacement (meters)" and "initial value for the tower fore-aft displacement rate (meters/sec)"?

I found there are AdditionalInputs items in the S-function parameters. If I can set the value of "Initial fore-aft tower top displacement (meters)" and "initial value for the tower fore-aft displacement rate (meters/sec)" through this interface? If so, how can I set the corresponding value here?
![image](https://user-images.githubusercontent.com/68947524/89010974-2e851f80-d342-11ea-8f6d-1af72f6964ea.png)

**Comment by KnowNothingButTry** [comment]
@bjonkman Thank you again!

**Comment by jjonkman** [comment]
@KnowNothingButTry -- In FAST v8 and OpenFAST, the states are internal to the FAST S-Function and cannot be specified as inputs to the block.  Modifying this would likely be a large effort.  Of course, you can specify the initial conditions (at time zero) of many states (e.g., tower deflection) through the input file(s).  It is likely not too difficult to modify the source code so that other states that are currently initialized to zero (e.g., tower velocity) are also initialized to user-specified values, but to specify these through the FAST S-Function block would take much more work.

Another option would be to revert back to FAST v7 where the structural states (but not other states of the model, e.g., aerodynamic states) are inputs into the FAST S-Function.

Best regards,

**Comment by KnowNothingButTry** [comment]
@bjonkman Thanks for your reply! can you  give me a link to download FAST V7 source code?

**Comment by KnowNothingButTry** [comment]
@jjonkman  Thanks for your reply! could you give me a link to download FAST V7 source code?

**Comment by jjonkman** [comment]
@KnowNothingButTry -- As I announced on our forum: https://wind.nrel.gov/forum/wind/viewtopic.php?f=38&t=1001, the NWTC Information Portal crashed before the replacement site is available. I've shared the old FAST v7 archive on Google Drive: https://drive.google.com/drive/folders/12JZQ91qeoi2uIWgp9YGX0FNCY8Ol77SW?usp=sharing.

**Comment by KnowNothingButTry** [comment]
@jjonkman Thank you again!
