### ISSUE TITLE
Power comparison against stand-alone openfast vs openfast + cfd code

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#517]
Hi openfast dev. team,

I am running a wind turbine simulation at on-design operating point condition (pitch angle, rotor rpm and free stream wind speed). I do not have a controller and the genDOF is switched off and I am just computing RtAeroPwr  (as well as Cp, Ct) from the Aerodyn output channel.  The operating point Aero power is 2.2 mW.

I have following observations. 
1) Stand-alone openfast run: uniform velocity at 10.05 m/s, I get power equilibriate at ~ 1.9 mW. I provide 10.05 m/s steady, plug-flow wind @ InflowWind module.  When I channel output from the inFlow wind output channel at hub-height, I get 10.05 m/s

2) openfast + CFD code. uniform steady velocity at 10.05 m/s through CFD inlet condition. (simple laminar model, no turbulence no shear, plug flow profile). This inlet condition is 2.5 km upstream of the turbine. For the same operating condition (blade pitch, rotor rpm), not the output channel from the inflow wind at hub-height is around 7.5 m/s (I understand that is because of blockage effect). The Aero power equilibriate to 1.5 mW.

Note all the openfast inputs corresponding to Elastodyn, Aerodyn are same for 1) and 2).  For 1) I am actually providing free stream velocity at 10.05 m/s through Inflow wind [InflowWind switch 0] but for 2) 10.05 m/s is through Nalu-wind (CFD code) inflow condition  [InflowWind switch 1 -- external from openFOAM or other CFD]. Aditionally,  I use actuator disc model, where I understand that the CFD Code is actually supplying ``induced velocities`` at the actuator nodes at openfast. 

Having said that, I am puzzled to see such a difference in Aero power between 1) and 2). Any suggestions or guidance as to why we observe this?

Sincere Regards,

**Comment by ebranlard** [comment]
Hi @tchatte3, 

The differences are definitely bigger than what I'm used to see. 
Here are some things  that I can think about, to potentially look for: 
   - (maybe it was a typo) I think you might want `CompInflow=1` for BEM and `CompInflow=2` for CFD
   - For the CFD case, you need `WakeMod=0` in the AeroDyn file
   - For the Be sEM case, removhear in InflowWind, `WindType=1`, `PLexp=0.0` (depending on your BC, you might not have shear in the CFD). You do need `WakeMod=1` for the BEM case. 
   - Tower shadow should be removed. 
And in general, the results might be sensitive to the blade discretization and the choice of the "epsilon" values. 

If you still have issue, let us know. 

Emmanuel

**Comment by tchatte3** [comment]
Hi @ebranlard thanks for the detailed guidance. This is really helpful. I was able to fix this issue, for my CFD+openfast case, ``WakeMod = 1 `` which resulted in the induction effects being double counted. Yes, I was using CompInflow = 1 for BEM and CompInflow = 2 for CFD.

This is issue is now resolved. Thank you !
Best Regards,
Tanmoy
