### ISSUE TITLE
AeroDyn14 NewTower TwrCD interpolation

### ISSUE THREAD

**Issue by rwegnerGermany** [OpenFAST/openfast#527]
Hi,
I am using Simpack with AeroDyn v13 but looking at the current code the problem appears to also exist in AeroDyn v14.
I modeled a hybrid lattice tower with the NEWTOWER feature with 50 tower stations (NTwrHt) mapping to 23 different (NTwrCD) drag coefficients.
With a parked rotor at constant 4m/s with no wind shear I got very strange wind speeds at the blade elements:

- Tower dam model can produce highly negative x-direction wind speeds
- Tower dam model affects blade elements far outside of the tower center line and above the tower
- Wind speeds at the blade elements depend on height (for this test the 50 stations had the same diameter and used the same index in TwrCD vector)

This blade element is at the 6 o'clock moving slowly upwards vertically (rotor hangs on a crane). At 950s the elevation is constant.
![WindX](https://user-images.githubusercontent.com/69688683/90271284-d713a300-de5b-11ea-9ad6-2a6642461935.png)

**I think I found the bug:** The variable NTwrCDCol is basically never used after filling it. In AeroSubs.f90 line 2562
`TwrElCD = InterpStp( TwrElHt, p%TwrProps%TwrHtFr, p%TwrProps%TwrCD(1,:), N2, p%TwrProps%NTwrHt )`
the vectors TwrHtFr and TwrCD are of different length. To my understanding the procedure should be:

1. Use the tower station table to get a TwrCD **index** for the height in question
2. Use this index for NTwrCDCol and return the drag coefficient.

It appears to work if NTwrCD = NTwrHt and the TwrCD values are in the order of the tower table. Just like it is in AeroDyn v15.

**Comment by andrew-platt** [comment]
Closing this issue as we won't be able to fix it before deprecating AD14.
