### ISSUE TITLE
Error when building OpenFAST with c++ API enabled

### ISSUE THREAD

**Issue by auraluck** [OpenFAST/openfast#529]
Hello everyone,
I plan to use OpenFAST c++ API to develop a coupling technique between OpenFAST and in-house CFD solver.
I have successfully compiled OpenFAST package using Cygwin64 with default setting (c++ API OFF). However, when I try configuring the main CMakeList file to turn on c++ API or turning the option on via command line, I get the following:

-- A library with LAPACK API found.
-- Setting system file as: src/SysGnuLinux.f90
CMake Warning (dev) at /usr/share/cmake-3.14.5/Modules/FindMPI.cmake:1251 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "CYGWIN" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  glue-codes/openfast-cpp/CMakeLists.txt:20 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.14.5/Modules/FindMPI.cmake:1255 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "CYGWIN" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  glue-codes/openfast-cpp/CMakeLists.txt:20 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find MPI_C (missing: MPI_mpi_LIBRARY MPI_open-rte_LIBRARY MPI_open-pal_LIBRARY MPI_z_LIBRARY MPI_C_HEADER_DIR MPI_C_WORKS)
-- Could NOT find MPI_CXX (missing: MPI_mpi_LIBRARY MPI_open-rte_LIBRARY MPI_open-pal_LIBRARY MPI_z_LIBRARY MPI_CXX_HEADER_DIR MPI_CXX_WORKS)
-- Could NOT find MPI_Fortran (missing: MPI_mpi_usempif08_LIBRARY MPI_mpi_usempi_ignore_tkr_LIBRARY MPI_mpi_mpifh_LIBRARY MPI_mpi_LIBRARY MPI_open-rte_LIBRARY MPI_open-pal_LIBRARY MPI_z_LIBRARY MPI_Fortran_F77_HEADER_DIR MPI_Fortran_MODULE_DIR MPI_Fortran_WORKS)
CMake Error at /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND MPI_Fortran_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.14.5/Modules/FindMPI.cmake:1672 (find_package_handle_standard_args)
  glue-codes/openfast-cpp/CMakeLists.txt:20 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/meow_/code/OpenFAST_sandbox/build/CMakeFiles/CMakeOutput.log".
See also "/home/meow_/code/OpenFAST_sandbox/build/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/OpenFAST/openfast/files/5078207/CMakeError.log)

I believe HDF5 and yaml-cpp are required for OpenFAST C++ API. I installed both of them in Cygwin and still have the issue. I also have OpenMPI for Cygwin.

Any suggestion or help would be highly appreciated!

**Comment by rafmudaf** [comment]
Hi @auraluck Are you still stuck on this compiling problem?
