### ISSUE TITLE
Error in Build The Regression Testing DISCON DLLs			

### ISSUE THREAD

**Issue by jsurabhi501** [OpenFAST/openfast#530]
Hi,

While performing regression tests on windows with the visual studio I am facing the following errors.
I have followed the following steps:
Build The Regression Testing DISCON DLLs

1. Open the Visual Studio Solution (Discon.sln) located in the openfast\vs-build\Discon folder
2. Choose Release and x64 for the Solutions Configuration and Solutions Platform, respectively
3. From the menu bar select Build->Build Solution
4. You should now see the files Discon.dll, Discon_ITIBarge.dll, and Discon_OC3Hywind.dll in your openfast\reg_tests\r-test\glue-codes\fast\5MW_Baseline\ServoData folder.

I am not getting the results mentioned in the 4th step. Please inform me how can I solve this error. I have visual studio 2019 version 16.6.5

![image](https://user-images.githubusercontent.com/68113824/90320741-fede3600-df43-11ea-8221-98474b41862a.png)

**Comment by jjonkman** [comment]
Hi @jsurabhi501,

What is written to the "Output" window in Visual Studio when you receive these errors?

Best regards,

**Comment by jsurabhi501** [comment]
> Hi @jsurabhi501,
> 
> What is written to the "Output" window in Visual Studio when you receive these errors?
> 
> Best regards,

It said that recommended files not found. then I copy-paste Discon.dll, Discon_ITIBarge.dll, and Discon_OC3Hywind.dll files from GitHub and run the command again. After that I got results.

**Comment by Goyan1105** [comment]
Hi @jsurabhi501 @jjonkman  ,
I have the same errors  when building the solution on Visual Studio. But I don't understand how you solved the errors.
From where did you downloaded  Discon.dll, Discon_ITIBarge.dll, and Discon_OC3Hywind.dll on Github? 
And where did you cop-paste those files?
Here are in attachment the errors that I got.
Kind regards

![Screenshot (12)](https://user-images.githubusercontent.com/72247660/94898136-52272c00-0491-11eb-9a3c-bf810b80f22b.png)
![Screenshot (13)](https://user-images.githubusercontent.com/72247660/94898137-52bfc280-0491-11eb-91a2-a55e21dc67b6.png)

**Comment by rafmudaf** [comment]
@Goyan1105 How did you obtain the OpenFAST source code repository? If the DISCON source files are not present, make sure you properly cloned the repo: https://openfast.readthedocs.io/en/master/source/testing/index.html#configuring-the-test-suite.

**Comment by Goyan1105** [comment]
@rafmudaf  I did multiple times the step 1  "Clone the openfast repo and initialize the testing database".  
If I do it now on git bash I will get the following:
![Capture](https://user-images.githubusercontent.com/72247660/95170972-85312e80-07b5-11eb-9779-3c251dc2d5a9.PNG)

**Comment by rafmudaf** [comment]
I'm trying to understand the context for where you are in your process, so bear with me. Is the `~` directory in Git Bash `C:\Users\Bonjour`? I'm asking because the path to the DISCON files in the screen shots may be different than the path you've showed here in Git Bash.

Also, @bjonkman does Visual Studio have any problem with a space in the path? @jsurabhi501 has `Simulation OpenFAST` in the middle of the path.

**Comment by Goyan1105** [comment]
@rafmudaf  I'm at section 3.2.2.4.4.1. Windows with Visual Studio regression test  https://openfast.readthedocs.io/en/master/source/testing/regression_test_windows.html#regression-test-windows
The path to Git Bash is  C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Git.
So I should change the code line : git clone https://github.com/openfast/openfast.git   ?

**Comment by rafmudaf** [comment]
I'm wondering about the path to your OpenFAST repository as you've shown in the Git-Bash terminal and Visual Studio. It looks like they're different. And I'm also wondering if Visual Studio itself has an issue with a space being in the middle of a path.

Your `git` environment is something completely different and is probably just fine.

**Comment by jsurabhi501** [comment]
> Hi @jsurabhi501 @jjonkman ,
> I have the same errors when building the solution on Visual Studio. But I don't understand how you solved the errors.
> From where did you downloaded Discon.dll, Discon_ITIBarge.dll, and Discon_OC3Hywind.dll on Github?
> And where did you cop-paste those files?
> Here are in attachment the errors that I got.
> Kind regards
> 
> ![Screenshot (12)](https://user-images.githubusercontent.com/72247660/94898136-52272c00-0491-11eb-9a3c-bf810b80f22b.png)
> ![Screenshot (13)](https://user-images.githubusercontent.com/72247660/94898137-52bfc280-0491-11eb-91a2-a55e21dc67b6.png)

Dear @Goyan1105 ,

You can simply download those dll files and keep them in the same folder as your test folder. In my case, I kept those newly downloaded files from GitHub and kept in the Cert test folder.

**Comment by rafmudaf** [comment]
Ah good point - @Goyan1105 you can find those DLL's in the [latest release](https://github.com/OpenFAST/openfast/releases/latest) assets: https://github.com/OpenFAST/openfast/releases/download/v2.4.0/openfast_v2.4.0_binaries.zip.

**Comment by bjonkman** [comment]
@rafmudaf: Visual Studio shouldn't have an issue with spaces in the path name. In @Goyan1105 's screen shot, it shows the space in the file name that it is looking for. If the space was a problem, the error message would have stopped printing the file name at the first white space.

@Goyan1105, the errors show that the source files seem to be missing. Can you verify that you do in fact have the submodule files in `C:\Users\Bonjour\Documents\Simulation OpenFAST\openfast-2.4.0\reg_tests\r-test\glue-codes\openfast\5MW_Baseline\ServoData\`, which is where your Visual Studio project file it trying to find them?

As @rafmudaf pointed out, it looks like the `git submodule update --init --recursive` command may have been run in a different location than your Visual Studio screen shots. Your Git Bash file looks like it cloned OpenFAST in `C:\Users\Bonjour\openfast` while the Visual Studio project looks like it is using an OpenFAST clone or download in `C:\Users\Bonjour\Documents\Simulation OpenFAST\openfast-2.4.0`. If you have a Visual Studio file in the clone where you have the submodules initialized, you should run that one: `C:\Users\Bonjour\openfast\vs-build\Discon\Discon.sln`.

**Comment by Goyan1105** [comment]
Thanks for the help, it worked. 
@rafmudaf @bjonkman Now I'm at step 5.c. of section 3.2.2.4.4.1. "Windows with Visual Studio regression test" but, I get the following error on the Anaconda prompt command: 
usage: manualRegressionTest.py [-h] [-p [Plotting-Flag]] [-n [No-Execution]] [-v [Verbose-Flag]] [-case [Case-Name]]
                               OpenFAST System-Name Compiler-Id Test-Tolerance
manualRegressionTest.py: error: argument Test-Tolerance: invalid float value: 'Intel'


Should I change the value of Intel?
![Capture2](https://user-images.githubusercontent.com/72247660/95307847-774cdd80-0889-11eb-91b9-fc9d50543f26.PNG)

**Comment by rafmudaf** [comment]
I think your problem here is the space in the path to your openfast repo. The command line is probably interpreting the first argument as two separate arguments due to that space and so the compiler ID is being read as the test tolerance.
