### ISSUE TITLE
Issue on Compiling the SImulink S-Function on Ubuntu Linux system

### ISSUE THREAD

**Issue by Seager1989** [OpenFAST/openfast#531]
**Bug description**
Error as creating the mex file using the create_FAST_SFunc.m using a different version of gcc (9.3.0).
I am working on compiling the OpenFAST Simulink module at the Linux system. I checked the issue #387, which is a discussion using gcc 4.9 and was using the branch (https://github.com/bjonkman/openfast/tree/f/SimulinkGNUlinux) offered by @bjonkman. This branch compiled correctly. I tried to run the create_FAST_SFunc.m with the built_with_visualStudio = false and 
    installDir = '../../../install';
    outDir = '.';
    libDir = fullfile(installDir, 'lib');
    includeDir = fullfile(installDir, 'include');
    libName = 'openfastlib';
where the install is the installation directory of the compiled OpenFAST. The mex function using the default setup. I also added the 'bin' and 'lib' to the matlab path. Warning was given as follows.

_Warning: You are using gcc version '9.3.0'. The version of gcc is not supported. The version currently supported with MEX is '6.3.x'. For a list of currently supported compilers see: https://www.mathworks.com/support/compilers/current_release._ 

Even warning, the 'FAST_SFunc.mexa64' was still generated, but errors were generated as I tried to run an example as follows.

_Error using Run_Test01_SIG (line 35)
Error due to multiple causes.
Caused by:
    Error using Run_Test01_SIG (line 35)
    Error while obtaining sizes from MEX S-function 'FAST_SFunc' in 'Test01_SIG/FAST Nonlinear Wind Turbine/S-Function'.
        Error using Run_Test01_SIG (line 35)
        Invalid MEX-file '/home/seager/Downloads/openfast/glue-codes/simulink/src/FAST_SFunc.mexa64': libopenfastlib.so:
        cannot open shared object file: No such file or directory
    Error using Run_Test01_SIG (line 35)
    The expression: u(strmatch('LSSGagVxa',OutList))
    in 'Test01_SIG/Fcn'
    has a syntax error_

I also added the libopenfastlib.so to the Matlab path. In the response of @bjonkman in #387 , she was kindly mentioned: "You may be able to get around this by modifying the relevant files in the <MATLAB_ROOT>/bin/<os>/mexopts directory, making sure the paths and libraries are set for the version you are using." I have two additional questions regarding this. 1) is there a suggestion on how to change the mexopts file? 2) did you mean the path the libraries of the new gcc version need to be specified in the Matlab path or something else? 

I do not know if these errors is caused by the different version of gcc9.3 from the 4.9? or I need to make some other modifications?
Thank you for any help.

**Comment by bjonkman** [comment]
I am surprised that it built the mex file after giving the warning about your gcc version being unsupported. It looks like it was able to find the files it needed to build, however, so I'm not sure I would attempt to change the mexopts file(s). (If you did want to go this route, I'd look up some help on the Matlab support page. There are a couple of questions there that deal with trying to get around unsupported gcc versions on Linux.)

My first guess is that it looks like it might just be a path issue in Matlab. I would make sure that the path `libDir` (which is defined in the `create_FAST_SFunc.m` script) is on the MATLAB path. What does it show when you type `which libopenfastlib.so`?

**Comment by Seager1989** [comment]
Hi Bonnie,

Thank you for your reply.

1) By running the `which libopenfastlib.so`, the Matlab shows the file as below. The _install_ is the directory for OpenFAST installation.
_/home/seager/Downloads/openfast/install/lib/libopenfastlib.so_

2) The` libDir` is defined in the Matlab path. The setup of the `create_FAST_SFunc.m` is shown in the below picture with the warning and generated mexa64 presented also.
![image](https://user-images.githubusercontent.com/38188001/90583880-41e81580-e19f-11ea-8d30-8b40f7dccf8c.png)

Do you have any ideas about these?

If it is just a path issue, I prefer to fix the path problem rather than changing the Matlab mexopts files. Thank you

**Comment by bjonkman** [comment]
Okay, it looks like it is finding both the FAST S-Function and openfast library. The next thing would be to check that it can find all the shared libraries that `libopenfastlib.so` depends on. Can you check which libraries these are (e.g. using `ldd`), and then make sure that Matlab can find them? Or try to build `libopenfastlib.so` as a static library so you don't need to worry about getting all the paths to its dependencies set in Matlab? Maybe there are some gcc libraries that Matlab is not finding.

**Comment by Seager1989** [comment]
Thank you for your suggestions. I tried these operations.

1) I checked the dependency of libopenfastlib.so. After exporting the OpenFAST _bin_ and _lib_ to the system path, the libmex.so is the only dependency that the `ldd` can not find. I try to run the OpenFAST model by compiled OpenFAST script. An error also appeared with the information of the missed libmex.so.

2) I also try to compile the OpenFAST with the `-DBUILD_SHARED_LIBS=OFF`. The static library (`libopenfastlib.a`) is compiled. However, the same error is presented as I try to run a regression test model with the OpenFAST script. As I run the create.FAST_SFunc.m, more errors are shown with a part of them listed below.
_Error using mex
/usr/bin/ld: ../../../install2/lib/libopenfastlib.a(FAST_Library.f90.o): in function `FAST_OpFM_Step':
FAST_Library.f90:(.text+0xb0): undefined reference to `__fast_subs_MOD_fast_solution_t'
/usr/bin/ld: FAST_Library.f90:(.text+0x109): undefined reference to `_gfortran_string_len_trim'
/usr/bin/ld: FAST_Library.f90:(.text+0x13e): undefined reference to `_gfortran_concat_string'
/usr/bin/ld: FAST_Library.f90:(.text+0x186): undefined reference to `_gfortran_concat_string'
/usr/bin/ld: FAST_Library.f90:(.text+0x27f): undefined reference to `_gfortran_concat_string'
/usr/bin/ld: FAST_Library.f90:(.text+0x31a): undefined reference to `__supercontroller_MOD_sc_setoutputs'
/usr/bin/ld: FAST_Library.f90:(.text+0x3b5): undefined reference to `__supercontroller_MOD_sc_setinputs'
/usr/bin/ld: ../../../install2/lib/libopenfastlib.a(FAST_Library.f90.o): in function `FAST_OpFM_Restart':
FAST_Library.f90:(.text+0x87f): undefined reference to `__nwtc_library_MOD_nwtc_init'
/usr/bin/ld: FAST_Library.f90:(.text+0x8b0): undefined reference to `_gfortran_string_index'
/usr/bin/ld: FAST_Library.f90:(.text+0x951): undefined reference to `__fast_subs_MOD_fast_restorefromcheckpoint_t'
/usr/bin/ld: FAST_Library.f90:(.text+0x9a5): undefined reference to `__nwtc_library_types_MOD_seterrstat'
/usr/bin/ld: FAST_Library.f90:(.text+0x9c5): undefined reference to `__nwtc_base_MOD_aborterrlev'
/usr/bin/ld: FAST_Library.f90:(.text+0xa2e): undefined reference to `_gfortran_string_len_trim'_

It seems the problem of OpenFAST compilation, but I have no idea how to fix the problem of the missed libmex.so. Do you have any ideas? Thank you and be safe.

**Comment by bjonkman** [comment]
The libmex.so file is a Matlab library that gets linked with the OpenFAST library to enable it to print to the Matlab command window. It is usually found in `<MATLABROOT>/extern/lib/<os>`. I'd be very surprised if Matlab has trouble finding that one.

The errors in your second point make me think that either you have some incompatible compile or linking switches between the mex build and the OpenFAST cmake build, or else the Matlab mex process is finding different libraries than cmake did. Do you have multiple versions of gcc installed?

**Comment by Seager1989** [comment]
Dear Bonnie,

I googled the Libmex.so and find the Matlab page. I checked the Matlab directory based on your suggestions and this page. There is no libmex.so file in both the `<MATLABROOT>/extern/bin` and `lib`. The MATLAB version is 2020a and I checked the MATLAB installed in another Ubuntu Linux machine with also no libmex.so found. Do you have any idea how to fix this problem?

I have only one gcc version: gcc 9.3.0.

In addition, after compiling, the openfast driver in the `build/glue-codes/openfast` can run normally, but after installation, the `install/bin/openfast` can not run with the error of the missing libmex.so as mentioned before. The regression test is also running but all failed.  Thank you

**Comment by bjonkman** [comment]
From [Matlab documentation on building mex files](https://www.mathworks.com/help/matlab/matlab_external/custom-linking-to-required-api-libraries.html):
```
Linux libraries:
    matlabroot/bin/glnxa64/libmex.so
```
If that doesn't exist, check your Matlab installation.

I would not expect that you would generate an OpenFAST driver (executable) that links with the Matlab library. You _might_ be able to run such a code from _inside_ Matlab's command window, but it would not run from the command line. 

You should be generating an OpenFAST _library_ for Simulink (not an executable), which gets called from the S-Function.

**Comment by Seager1989** [comment]
Thank you for caring about this issue. Recently, I compiled the gcc- and gfortran-6.3.0 for MATLAB 2020a. Now, the S-function can be created with no warning and error generated. As I use it in Simulink for a model running, there is an error as below.

`Error using openloopre (line 9)
Error while obtaining sizes from MEX S-function 'FAST_SFunc' in 'OpenLoop/FAST Nonlinear Wind Turbine/S-Function'.
Caused by:
    Error using openloopre (line 9)
    Invalid MEX-file '/home/seager/Downloads/openfast/glue-codes/simulink/src/FAST_SFunc.mexa64': libopenfastlib.so: cannot open shared object file: No such
    file or directory`

The Matlab can find the 'libopenfastlib.so' correctly. I use the `ldd` to find the dependency of it. All openfast libs dependencies can not be found by the `ldd` . I exported the OpenFAST installation directory to the system. The problem is: 
1) Is the error caused by the dependency missing of the `libopenfastlib.so`?
2) If yes, how to help the `libopenfastlib.so` find the dependencies?

Any help is appreciated. Thanks

**Comment by bjonkman** [comment]
Yes, it sounds like the problem is that MATLAB can't find the libopenfastlib.so dependencies. I would probably start by adding the locations of its dependencies to the MATLAB path (e.g., through MATLAB's `addpath` command).

**Comment by Seager1989** [comment]
Thank you. I added the installation path to MATLAB path. The dependencies were found by exporting the `install/lib` to `LD_LIBRARY_PATH`.  However, as I run a Simulink example after created SFunction, the following errors shown . Do you know how to fix this problem? Thanks

`**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST--128-NOTFOUND
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Sep 15 2020
  - Time: 13:53:23
 Execution Info:
  - Date: 09/15/2020
  - Time: 22:05:54-0400

 OpenFAST input file heading:
     FAST Certification Test #18: NREL 5.0 MW Baseline Wind Turbine (Onshore)

 Running ElastoDyn.
 Running AeroDyn.
 Running BEM.
 Running UnsteadyAero.
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 1, Blade = 1
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 2, Blade = 1
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 3, Blade = 1
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 4, Blade = 1
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 1, Blade = 2
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 2, Blade = 2
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 3, Blade = 2
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 4, Blade = 2
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 1, Blade = 3
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 2, Blade = 3
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 3, Blade = 3
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. BladeNode = 4, Blade = 3
 Running InflowWind.

    Reading a 31x31 grid (145 m wide, 17.5 m to 162.5 m above ground) with a characteristic wind
    speed of 12 m/s. This full-field file was generated by TurbSim (v1.06.00, 21-Sep-2012) on
    07-Jan-2014 at 12:50:45.

    Processed 1442 time steps of 20-Hz full-field data (72.05 seconds).
 Running ServoDyn.
 Running ServoDyn Interface for Bladed Controllers.
  Time: 0 of 20 seconds.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGETRF.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGETRF.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGEMM .

  OpenFAST terminated normally.
`

**Comment by Seager1989** [comment]
Hi,
I fixed this problem by export the `install/lib` to `LD_LIBRARY_PATH`. However, a similar problem presented with the matlab crashed. The openfast terminated normally and Segmentation fault (core dumped) are shown at the terminal. `Crash Decoding           : Disabled - No sandbox or build area path` is shown in the MATLAB crash report (as attached) and also, it suggest maybe the mex file need to be checked.

I contacted with the MATLAB support before and they suggest two possible problems: 1) the GCC version and 2) Mex file. Now I compiled the compatible GCC -6.3.0. Can you please help check the mex file quickly? My ubuntu system information is listed as follows:
Ubuntu 18.0.4, 64 bits, MATLAB 2020a, Gcc-6.3.0 and gfortran -6.3.0.

If you need some other information, please let me know. Thanks
[MATLAB crash report.txt](https://github.com/OpenFAST/openfast/files/5232558/MATLAB.crash.report.txt)

**Comment by bjonkman** [comment]
The crash report looks like it is calling the gfortran `EXIT` routine. Which version of the Sys*.f90 library are you building with? (is it this one: https://github.com/bjonkman/openfast/blob/f/SimulinkGNUlinux/modules/nwtc-library/src/SysMatlabLinuxGnu.f90?) The Sys*.f90 files for Simulink/Matlab should have that commented out, so it makes me think you've build the libopenfastlib.so file with the wrong file. Make sure you build with `BUILD_OPENFAST_SIMULINK_API` on.

**Comment by andrew-platt** [comment]
One puzzling thing to me is that while compiled with gfortran, it is linking to the Intel MKL from the Intel Fortran compiler.

**Comment by Seager1989** [comment]
> The crash report looks like it is calling the gfortran `EXIT` routine. Which version of the Sys*.f90 library are you building with? (is it this one: https://github.com/bjonkman/openfast/blob/f/SimulinkGNUlinux/modules/nwtc-library/src/SysMatlabLinuxGnu.f90?) The Sys*.f90 files for Simulink/Matlab should have that commented out, so it makes me think you've build the libopenfastlib.so file with the wrong file. Make sure you build with `BUILD_OPENFAST_SIMULINK_API` on.

1) I use the OpenFast and its Sys*.f90 library from https://github.com/bjonkman/openfast/tree/f/SimulinkGNUlinux.
2) After I add the `-DBUILD_OPENFAST_SIMULINK_API=ON` into the CMAKE, the S-Function **is running** correctly by the Simulink.

However, a problem is in there. As I run the OpenFAST in the terminal, an error occurred as follows.
`openfast: error while loading shared libraries: libmex.so: cannot open shared object file: No such file or directory.` (The `libmex.so` is in the `matlabroot/bin/glnxa64/libmex.so`, but it may not be exported to the PATH or LD_LIBRARY_PATH.)

Also, in the `build` folder, I ran the ctest with most of the cases failed. I checked the folder of reg_test cases in `build` and found that the output files are not named as `*.outb` but `*.sFunc.outb`.  This was recognized as the reason for test failure by running a single Ctest. 

The new problem should be caused by the `-DBUILD_OPENFAST_SIMULINK_API=ON`, but I do not know how to fix this problem so I can run OpenFAST in the terminal correctly also. Thank you!

**Comment by Seager1989** [comment]
> One puzzling thing to me is that while compiled with gfortran, it is linking to the Intel MKL from the Intel Fortran compiler.

Hi Andy,
Thank you for your feedback. The MKL you mentioned is also a confusion form me, but it never appeared again. Now, the main problem (S-Function running) was fixed but with a minor issue still in there as the reply to Bonnie. It is also appreciated if you have some ideas.

**Comment by bjonkman** [comment]
I think there is some confusion here between (1) the stand-alone OpenFAST executable and (2) the OpenFAST-for-Simulink library. Both versions can both be built by cmake, but it should not be building both _at the same time._

I am not sure what you mean by "terminal" here. If it is not the Matlab command prompt window, then you should not be trying to run the OpenFAST-for-Simulink library there. After you build for Simulink, you should **ONLY** use that .so file  _inside_ Matlab. I would not care about ctest in this case at all. (Your file extensions should have the `.SFunc` in them only if they were generated by the OpenFAST-for-Simulink library.)  

So, based on your comments above, it sounds like the OpenFAST-for-Simulink build is running correctly in Simulink. It is not running outside of Simulink, and that is expected behavior.

If you want to run OpenFAST **outside** of Simulink, you should build with `-DBUILD_OPENFAST_SIMULINK_API=OFF`. That should then generate a standalone executable without any connection to Matlab.

**Comment by Seager1989** [comment]
> I think there is some confusion here between (1) the stand-alone OpenFAST executable and (2) the OpenFAST-for-Simulink library. Both versions can both be built by cmake, but it should not be building both _at the same time._
> 
> I am not sure what you mean by "terminal" here. If it is not the Matlab command prompt window, then you should not be trying to run the OpenFAST-for-Simulink library there. After you build for Simulink, you should **ONLY** use that .so file _inside_ Matlab. I would not care about ctest in this case at all. (Your file extensions should have the `.SFunc` in them only if they were generated by the OpenFAST-for-Simulink library.)
> 
> So, based on your comments above, it sounds like the OpenFAST-for-Simulink build is running correctly in Simulink. It is not running outside of Simulink, and that is expected behavior.
> 
> If you want to run OpenFAST **outside** of Simulink, you should build with `-DBUILD_OPENFAST_SIMULINK_API=OFF`. That should then generate a standalone executable without any connection to Matlab.

I totally understand what you mean. Thank you for your help regarding this issue. I think the problem reported in this issue has been fixed, so we can close it. Thank you for all of your help.
