### ISSUE TITLE
Design Load Case error for IEA-15-240-RWT-UMaineSemi

### ISSUE THREAD

**Issue by ramya-niranjan** [OpenFAST/openfast#532]
**Bug description**
Dear All, 
I am interested in running the design load cases for IEA-15-240-RWT-UMaineSemi in OpenFAST using the files shared in https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/master/OpenFAST/IEA-15-240-RWT-UMaineSemi. I am facing the following issue while running the DLCs 3.1 (with steady wind and regular waves).
The simulations were performed for three different time steps (0.05, 0.0125 and 0.001 sec). The error (shown in snapshot 1 below) is happening for the time steps 0.001 and 0.0125 sec and error (shown in snapshot 2 below) is happening for the time step of 0.05 sec. All the above errors are occurring when the Yaw DOF is enabled and the Drivetrain rotational-flexibility DOF is disabled. This issue was posted in the NREL forum 
(https://wind.nrel.gov/forum/wind/viewtopic.php?f=25&t=2534&p=15123#p15123) and I got to know from Dr. Jason Jonkman that receiving an "Unknown ErrID" could be a minor bug in the error handling. Kindly do the needful. For your information, I have used OpenFAST developer branch released in April 2020 to run all the above described simulations. 
![Snapshot1](https://user-images.githubusercontent.com/63047973/90334399-0d335d00-dfeb-11ea-8e38-b5cbe8948d97.png)
![Snapshot2](https://user-images.githubusercontent.com/63047973/90334406-1290a780-dfeb-11ea-9c8b-bb8878f949bc.png)

**OpenFAST Version**
![Screen Shot 2020-08-16 at 6 06 53 PM](https://user-images.githubusercontent.com/63047973/90334450-5e435100-dfeb-11ea-8905-61c5f1115e44.png)

**System Information (please complete the following information):**
 - OS: macOS 10.13.3
 - Compiler: GFortran 9.3.0

**Additional context**
The input files used are the same as shared in https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/master/OpenFAST/IEA-15-240-RWT-UMaineSemi. Few snapshots of the input files where modifications have been made are enclosed below.
**Snapshot from .fst file**
![Screen Shot 2020-08-16 at 6 20 19 PM](https://user-images.githubusercontent.com/63047973/90334716-4967bd00-dfed-11ea-83bc-18554535aac0.png)
**Snapshot from ElastoDyn.dat file**
![Screen Shot 2020-08-16 at 6 22 31 PM](https://user-images.githubusercontent.com/63047973/90334782-a499af80-dfed-11ea-80ed-f988262e6469.png)
**Snapshot from HydroDyn.dat file**
![Screen Shot 2020-08-16 at 6 25 19 PM](https://user-images.githubusercontent.com/63047973/90334814-e75b8780-dfed-11ea-9bac-d797fdeb2f47.png)

Thanks and Regards 
Ramya

**Comment by andrew-platt** [comment]
thanks for the info.  About 4 months ago we discovered some broken error handling in the BEMT module of AeroDyn 15.  There was an update that is now merged into the dev branch that fixes that particular error.  It may be the same error that you are seeing.

The fix for that particular error was merged to dev in pull request #435.  This has not been merged to the master branch for release yet.

If you can compile, could you test the dev branch and see if your error is still there?

**Comment by ramya-niranjan** [comment]
Dear Andrew, 
I ran the simulations with latest OpenFAST dev version as you advised. For the  DLC 3.1 (steady wind and regular waves) and t=0.0125 and 0.001s which was giving an "Unknown ErrID" before are running without any issues now. 

Thanks and Regards
Ramya
