### ISSUE TITLE
Error during "running cmake'

### ISSUE THREAD

**Issue by Akheelakk** [OpenFAST/openfast#533]
Hey all,
I am doing my post graduation in Offshore structures. I am using openfast for my project thesis in OWTs. I followed the 'readthedoc' documentation file. I found some trouble while 'running cmake'. 

C:\Users\Akk>cmake C:\openfast-master -DBUILD_DOCUMENTATION=ON
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_IFACE_LIB MKL_SEQ_LIB MKL_CORE_LIB)
-- A library with LAPACK API found.
-- Setting system file as: src/SysIVF.f90
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS)
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS)
-- Could NOT find MPI_Fortran (missing: MPI_Fortran_LIB_NAMES MPI_Fortran_F77_HEADER_DIR MPI_Fortran_MODULE_DIR MPI_Fortran_WORKS)
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND MPI_Fortran_FOUND)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindMPI.cmake:1717 (find_package_handle_standard_args)
  glue-codes/openfast-cpp/CMakeLists.txt:20 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Akk/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Akk/CMakeFiles/CMakeError.log".

can someone guide me to fix the issue
Thanks in advance

![image](https://user-images.githubusercontent.com/67406965/90729207-d65b9080-e2e3-11ea-961f-49b4feb26ea4.png)

**Comment by andrew-platt** [comment]
Which compiler are you using?

**Comment by Akheelakk** [comment]
cmake

**Comment by andrew-platt** [comment]
CMake is a build system which then sets the compiling scripts based on the compiler you have installed. You will need a Fortran compiler in addition, such as Intel Fortran (https://software.intel.com/content/www/us/en/develop/tools/compilers/fortran-compilers.html), or gfortran (https://gcc.gnu.org/wiki/GFortran).

**Comment by Akheelakk** [comment]
I am using Visual Studio 19. ifort and icc are included in the package
while installing Parallel Studio XE.
Thank you Andy

**Comment by andrew-platt** [comment]
In that case, cmake is not finding the correct paths. You may be able to run cmake from the Visual Studio command window, or call the `CompileVars.bat` file to set the paths from your command window (the location of this depends on your installation).

This post may help you with setting your paths: https://github.com/OpenFAST/openfast/issues/372#issuecomment-674973046

**Comment by Akheelakk** [comment]
Thank you @andrew-platt, I could fix the issue on MKL by following 372. But MPI, MPI_C, MPI_CXX, MPI_Fortran are still missing.

**Comment by rafmudaf** [comment]
There may be another `.bat` file that you'll need to call for the MPI libraries.
