### ISSUE TITLE
Problem in Building OpenFAST on Ubuntu

### ISSUE THREAD

**Issue by auraluck** [OpenFAST/openfast#535]
Hello all,
I have Ubuntu 20.04.1 installed on Oracle virtual machine and try to compile OpenFAST with c++ API ON.
I think I have all packages required for c++ API including HDF5, YAML-cpp, and MPI. 
Following the manual, CMake was run successfully. However, when I try to build the code using Make, the compilation works up to 87% before running into error:

[ 87%] Building Fortran object modules/openfast-library/CMakeFiles/openfast_prelib.dir/src/FAST_Types.f90.o
gfortran: fatal error: Killed signal terminated program f951
compilation terminated.
make[2]: *** [modules/openfast-library/CMakeFiles/openfast_prelib.dir/build.make:82: modules/openfast-library/CMakeFiles/openfast_prelib.dir/src/FAST_Types.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1503: modules/openfast-library/CMakeFiles/openfast_prelib.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

I do not know why this happens. Any help would be appreciated.

**Comment by rafmudaf** [comment]
Its hard to say exactly what the error may be but you could try increasing the memory allocated to the virtual machine. In some cases, the compile has failed because of this when I've tried on virtual systems.
