### ISSUE TITLE
HydroDyn Buoyancy Force Updated based on Dynamic Position of Floating Structure

### ISSUE THREAD

**Issue by cambrown52** [OpenFAST/openfast#540]
When modelling a floating structure in HydroDyn (without potential flow input from WAMIT), the initial buoyancy seems to be calculated in the simulation startup. Then the fluctuations in restoring hydrostatic forces can be calculated with a linear stiffness matrix `AddCLin  - Additional linear stiffness (N/m, N/rad, N-m/m, N-m/rad)`. This stiffness matrix must be generated in a pre-processing step and passed to HydroDyn through the input file.

However, it would be valuable to be able to accurately model situations where the hydrostatic restoring forces are non-linear for example due to partially submerged horizontal or diagonal  members.

I have two questions:
-in situations where the hydrostatic forces are (approximately) linear, is it possible for openFast to generate the hydrostatic stiffness matrix? e.g. inside HydroDyn instead of having to perscribe it in the HydroDyn input file?

-in situations where the non-linear hydrostatic forces are deemed important, is it possible to add a flag to recalculate the buoyancy forces at each time step based on the current position of the floating structure?

**Comment by jjonkman** [comment]
Dear @cambrown52,

Good observations and suggestions.  We're actually wrapping up the development of new functionality in OpenFAST to support floating substructure flexibility and member-level loads (I believe you are already familiar a bit with this project).  As part of this project, HydroDyn was reworked to support the recalculation of hydrostatic (buoyancy) loads in the strip-theory solution based on the displaced position of the substructure (following item two in your list).  The new implementation is nonlinear and supports large motion of the substructure, with the limitation that joints of the member cannot (instantaneously) cross the undisturbed free surface.  So, while angled members are acceptable, horizontal or near horizontal members at the free surface are not.  The pull request for this new functionality has already been issued (https://github.com/OpenFAST/openfast/pull/537), but testing is ongoing before being merged into dev.

Best regards,

**Comment by cambrown52** [comment]
OK great to hear the feature is already on it's way. I look forward the upcoming release.
