### ISSUE TITLE
AeroDyn Driver Input File

### ISSUE THREAD

**Issue by sdwln** [OpenFAST/openfast#543]
Dear all,
I'd like to run alone the AeroDyn which need input file 'AeroDyn Driver Input File'.My question is that how should I adjust the Parameter inclouding NumBlades,HubRad,HubHt,Overhang,ShftTilt,Precone.I don't know where I can find a rule to adjust these parameter.
[ad_driver_example注释.inp.txt](https://github.com/OpenFAST/openfast/files/5213749/ad_driver_example.inp.txt)

**Comment by jjonkman** [comment]
Dear @sdwln,

The AeroDyn driver input file is well documented on the OpenFAST readthedocs site: https://openfast.readthedocs.io/en/master/source/user/aerodyn/input.html#aerodyn-driver-input-file.

Best regards,
