### ISSUE TITLE
Change timestep DT error

### ISSUE THREAD

**Issue by hbasbas** [OpenFAST/openfast#551]
Hello, 

I have a very basic question on changing the time step (variable DT in the input file .fst) : I am using the last version of OpenFAST interfaced with Matlab with the TEST23 (TLP platform). I have some errors and I would like to know if they come from numerical instabilities. Thus, I modify the DT value from 0.0125s to 0.125s. However, when doing this ; I have this error on the Matlab Command Windows

![image](https://user-images.githubusercontent.com/71877229/94906854-7f7ad680-049f-11eb-821a-0be8c3b8eac4.png)

It seems they are two types of DT variables : (1) the one which is define in the input file and (2) 'dt_out'. I check on FAST_Subs.f90 program to identify this variable but I didn't obtain more information ...

**Comment by jjonkman** [comment]
Dear @hbasbas,

The OpenFAST primary (_*.fst_) input file contains both the DT and DT_Out input parameters.

DT is the global, or glue-code, time step; it is essential that a small enough time step is used to ensure solution accuracy (by providing a sufficient sampling rate to characterize all key frequencies of the system), to ensure numerical stability of the selected time-integrators, and to ensure that the coupling between modules of OpenFAST is numerically stable.

DT_Out is the time step of the data in the tabular (time-marching) output files. DT_Out must be an integer multiple of DT.

Best regards,

**Comment by hbasbas** [comment]
Thank you for your reply.
