### ISSUE TITLE
How to add new output parameters to the OutList

### ISSUE THREAD

**Issue by jsurabhi501** [OpenFAST/openfast#557]
Hello,

I am running Test 13 and I get the following output parameters after running it.
![image](https://user-images.githubusercontent.com/68113824/95219472-b16c9f80-07f5-11eb-9d22-024cd4a1ae92.png)

Now I want to add other output parameters to this list similar to the following. 
![image](https://user-images.githubusercontent.com/68113824/95220401-b7af4b80-07f6-11eb-9050-49ab3c7100ad.png)

Can you please guide me on how to do that?

**Comment by jjonkman** [comment]
Dear @jsurabhi501,

You can odd additional outputs from ElastoDyn as shown by your examples.  The full list of ElastoDyn outputs is available in the ElastoDyn tab of the Excel worksheet found here: https://github.com/OpenFAST/openfast/blob/master/docs/OtherSupporting/OutListParameters.xlsx.

Best regards,

**Comment by jsurabhi501** [comment]
Dear @jjonkman,

Do you mean I simply add my expected output parameters to Elastodyn.dat from the ElastoDyn tab of the Excel sheet? Is that right?

**Comment by jjonkman** [comment]
Dear @jsurabhi501,

Yes, that's right.  The two examples you show illustrate how outputs are specified in the OutList.  Simply add the outputs you want (from the Excel sheet), separated by commas (or semicolons, spaces, or tabs), and enclosed by quotes.

Best regards.
