### ISSUE TITLE
Error: FF wind array was exhausted at 43.225 seconds (trying to access data at 47.005 seconds)

### ISSUE THREAD

**Issue by jsurabhi501** [OpenFAST/openfast#563]
Hello,

I am trying to run Test13 for the WP_1.5 MW tower to find out flexural moment at the top and bottom of the tower. 
First I run the test for 40s TMax and get results. Next time, I run the test for 100 s TMax I am getting a fatal error.
![image](https://user-images.githubusercontent.com/68113824/95384521-0808d500-08ed-11eb-8b32-424aea4d736b.png)
Can you please guide me on how to solve this error? Is it related to the Dt-time step? Do they have specific limits to set the value of the DT-time step?

**Comment by andrew-platt** [comment]
You need a larger wind file.  The wind file you have only contains 46.95 seconds of data.  However, when the simulation initializes, the wind box is shifted downwind by a little more than half a wind turbine rotor, which for your turbine running in 12 m/s wind is a shift of ~7 seconds, so the wind box is past the turbine when the simulation ends at ~43 seconds.
