### ISSUE TITLE
OpenFAST Errors occur during regression test

### ISSUE THREAD

**Issue by Sohail-hasan** [OpenFAST/openfast#568]
Hello, I'm new user of OpenFAST. I am Building OpenFAST on Windows with Visual Studio. 
Prerequisites are 
1. Visual Studio 2015 Community Edition
2. parallel_studio_xe_2017_update8_cluster_edition_online_setup
3. Git for windows
4. Anaconda for Python 3.6
I successfully finished installation and openfast compilation. After that I started windows with visual studio regression test but at step 2 Build the regression testing DISCON DLLs as
![Regression 2](https://user-images.githubusercontent.com/72779192/96127948-a0c3d400-0f2f-11eb-9c98-44caf31d48b0.PNG)
**When I opened "Discon.sln" file with visual studio the following error occurs**
![VS error](https://user-images.githubusercontent.com/72779192/96128436-51ca6e80-0f30-11eb-8346-c40eaeea3359.PNG)
the Discon files are incompatible in visual studios....
Please guide me for windows OS.

**Comment by jjonkman** [comment]
Dear @Sohail-hasan,

Your error seems very similar to the one reported and solved in issue #354.

Best regards,

**Comment by Sohail-hasan** [comment]
Dear @jjonkman 
Thank you for prompt reply. Although I already installed parallel_studio_xe_2017_update8_cluster_edition (Student Version). but let me reinstall it.

Best Regards,

**Comment by Sohail-hasan** [comment]
Dear @jjonkman 
Thank you for guidance. Now I am on the last stage of regression test.  
Total PASSING tests - 21
Total FAILING tests - 13
Now i am reading the related issues to pass the regression test
