### ISSUE TITLE
How to run single modified regression test in windows

### ISSUE THREAD

**Issue by Sohail-hasan** [OpenFAST/openfast#571]
I modified the 5MW_OC4Semi_WSt_WavesWN.fst file as follows
![1](https://user-images.githubusercontent.com/72779192/96394611-6abb7400-11fd-11eb-91e3-f0f93c49f4e0.PNG)

Now i **want to run only 5MW_OC4Semi_WSt_WavesWN this test in windows**. can somebody guide me!!!

**Comment by jjonkman** [comment]
Dear @Sohail-hasan,

I'm not sure I understand your question.  What problem are you running into?  Are you asking how to view the animation that is created while running OpenFAST?

Best regards,
