### ISSUE TITLE
HELP RUNNING OPENFAST THROUGH MATLAB

### ISSUE THREAD

**Issue by bartoszstachowicz** [OpenFAST/openfast#572]
HELLO ALL!

I have succesfully compiled fast with VS and compiled FAST_SFunc.mexw64 with no errors.

Could someone explain briefly how to use them? :)
On linux I did it ths way:
'../path/to exec/oe executable case.fst'

I'd like to be able to work on controllers in simulink.

- What is the syntax to run from matlab?
- How ito set up a case to use a controller from Simulink with Open_FAST?
- can I use the same input files I was using before (on Linux)?

BS

**Comment by jjonkman** [comment]
Dear @bartoszstachowicz,

The FAST S-Function (_FAST_SFunc.mexw64_) can be run within Simulink.  I would start with the sample Simulink models (OpenLoop.mdl or Test01_SIG_mdl) available in the OpenFAST repository--see: https://github.com/OpenFAST/openfast/tree/master/glue-codes/simulink/examples.

The documentation on the FAST S-Function has not yet been ported over to the OpenFAST documentation on readthedocs.  But you can find the old documentation from FAST v7 and FAST v8.16 here: https://drive.google.com/file/d/1d_-vRRK3sXlunf1I1tDmtSWUveed91gg/view?usp=sharing (v7) and https://drive.google.com/file/d/17LDwMnCVmLfbRWSaVFxxqphVrtawMwlj/view?usp=sharing (v8.16).

Best regards,

**Comment by bartoszstachowicz** [comment]
Dear @jjonkman 

Thank you v. much!

Regards

BS
