### ISSUE TITLE
How to run R script from python

### ISSUE THREAD

**Issue by jsurabhi501** [OpenFAST/openfast#574]
I am trying to run my Rscript in python but I get the following error.

***"**Traceback (most recent call last):
  File "c:/Users/Surabhi/Desktop/SIM/MODEL/Openfast_py.py", line 486, in <module>
    pr = subprocess.Popen(file_run)
  File "C:\Users\Surabhi\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Surabhi\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified"*****

I am writing the code as follow:

   _**_R_path = 'Rscript.exe --vanilla   '
   file_run = R_path+'   "'+ R_file_text+ '" '
   print(file_run)
   pr = subprocess.Popen(file_run)
   pr.wait()_

Please guide me to resolve this issue._**

**Comment by rafmudaf** [comment]
@jsurabhi501 We support OpenFAST-specific questions here and this is primarily related to Python and R. For support on this, I suggest posting to StackOverflow with a specific description of your problem and use case.
