### ISSUE TITLE
Detecting periodic steady-state using TRIM solution

### ISSUE THREAD

**Issue by yonghoonlee** [OpenFAST/openfast#580]
While solving floating wind turbine and due to floater vibration, torque or pitch values converge to not just a constant but a periodic sinusoidal-shaped signals. In this case, TRIM capability for linearization seems unable to detect steady-state. Do you have recommendation to resolve this issue? Thank you.

**Comment by jjonkman** [comment]
Dear @yonghoonlee,

The steady-state trim solution, and the linearization process in general, requires that you use steady wind and no incident waves.  So, I'm not sure why you say the torque and pitch would be periodic.  I would expect the system to reach some steady state condition, with the only periodicity remaining resulting from the rotor azimuth variation, but these would not result in periodic variations in generator torque or collective blade pitch.

Best regards,
