### ISSUE TITLE
Regression test fails

### ISSUE THREAD

**Issue by hamidMech** [OpenFAST/openfast#587]
Hello,

When I run the "ctest" command I get the below fail message. Could you please help me how to solve it?

Best regards,
Hamid

-------------------------------------------------------------------------------------------------------------------------------------------
7% tests passed, 43 tests failed out of 46

Label Time Summary:
aeroacoustics    =   0.12 sec*proc (1 test)
aerodyn          =   0.13 sec*proc (1 test)
aerodyn14        =   0.96 sec*proc (8 tests)
aerodyn15        =   2.40 sec*proc (20 tests)
beamdyn          =   1.32 sec*proc (11 tests)
bem              =   0.13 sec*proc (1 test)
dynamic          =   0.36 sec*proc (3 tests)
elastodyn        =   3.13 sec*proc (26 tests)
extptfm          =   0.12 sec*proc (1 test)
hydrodyn         =   1.09 sec*proc (9 tests)
linear           =   0.61 sec*proc (5 tests)
map              =   0.36 sec*proc (3 tests)
moordyn          =   0.12 sec*proc (1 test)
offshore         =   0.96 sec*proc (8 tests)
olaf             =   0.24 sec*proc (2 tests)
openfast         =   4.10 sec*proc (34 tests)
servodyn         =   3.25 sec*proc (27 tests)
static           =   0.48 sec*proc (4 tests)
subdyn           =   0.36 sec*proc (3 tests)

Total Test time (real) =   5.24 sec

The following tests FAILED:
	  1 - AWT_YFix_WSt (Failed)
	  2 - AWT_WSt_StartUp_HighSpShutDown (Failed)
	  3 - AWT_YFree_WSt (Failed)
	  4 - AWT_YFree_WTurb (Failed)
	  5 - AWT_WSt_StartUpShutDown (Failed)
	  6 - AOC_WSt (Failed)
	  7 - AOC_YFree_WTurb (Failed)
	  8 - AOC_YFix_WSt (Failed)
	  9 - UAE_Dnwind_YRamp_WSt (Failed)
	 10 - UAE_Upwind_Rigid_WRamp_PwrCurve (Failed)
	 11 - WP_VSP_WTurb_PitchFail (Failed)
	 12 - WP_VSP_ECD (Failed)
	 13 - WP_VSP_WTurb (Failed)
	 14 - SWRT_YFree_VS_EDG01 (Failed)
	 15 - SWRT_YFree_VS_EDC01 (Failed)
	 16 - SWRT_YFree_VS_WTurb (Failed)
	 17 - 5MW_Land_DLL_WTurb (Failed)
	 18 - 5MW_OC3Mnpl_DLL_WTurb_WavesIrr (Failed)
	 19 - 5MW_OC3Trpd_DLL_WSt_WavesReg (Failed)
	 20 - 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth (Failed)
	 21 - 5MW_ITIBarge_DLL_WTurb_WavesIrr (Failed)
	 22 - 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti (Failed)
	 23 - 5MW_OC3Spar_DLL_WTurb_WavesIrr (Failed)
	 24 - 5MW_OC4Semi_WSt_WavesWN (Failed)
	 25 - 5MW_Land_BD_DLL_WTurb (Failed)
	 26 - 5MW_OC4Jckt_ExtPtfm (Failed)
	 27 - HelicalWake_OLAF (Failed)
	 28 - EllipticalWing_OLAF (Failed)
	 29 - IEA_LB_RWT-AeroAcoustics (Failed)
	 30 - WP_Stationary_Linear (Failed)
	 31 - Ideal_Beam_Fixed_Free_Linear (Failed)
	 32 - Ideal_Beam_Free_Free_Linear (Failed)
	 33 - 5MW_Land_BD_Linear (Failed)
	 34 - 5MW_OC4Semi_Linear (Failed)
	 35 - ad_timeseries_shutdown (Failed)
	 36 - bd_5MW_dynamic (Failed)
	 37 - bd_5MW_dynamic_gravity_Az00 (Failed)
	 38 - bd_5MW_dynamic_gravity_Az90 (Failed)
	 39 - bd_curved_beam (Failed)
	 40 - bd_isotropic_rollup (Failed)
	 41 - bd_static_cantilever_beam (Failed)
	 42 - bd_static_twisted_with_k1 (Failed)
	 43 - hd_OC3tripod_offshore_fixedbottom_wavesirr (Failed)
Errors while running CTest
abedih@tfd105:/scratch/NREL/openfast/build$ ctest -VV -R AOC_YFix_WSt
UpdateCTestConfiguration  from :/scratch/NREL/openfast/build/DartConfiguration.tcl
Parse Config file:/scratch/NREL/openfast/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/scratch/NREL/openfast/build/DartConfiguration.tcl
Parse Config file:/scratch/NREL/openfast/build/DartConfiguration.tcl
Test project /scratch/NREL/openfast/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 8
    Start 8: AOC_YFix_WSt

8: Test command: /usr/bin/python3 "/scratch/NREL/openfast/reg_tests/executeOpenfastRegressionCase.py" "AOC_YFix_WSt" "/scratch/NREL/openfast/build/glue-codes/openfast/openfast" "/scratch/NREL/openfast/reg_tests/.." "/scratch/NREL/openfast/build/reg_tests/glue-codes/openfast" "0.00001" "Linux" "GNU"
8: Test timeout computed to be: 5400
8: Error: executable at /scratch/NREL/openfast/build/glue-codes/openfast/openfast does not have proper permissions.
1/1 Test #8: AOC_YFix_WSt .....................***Failed    0.40 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
aerodyn15    =   0.40 sec*proc (1 test)
elastodyn    =   0.40 sec*proc (1 test)
openfast     =   0.40 sec*proc (1 test)
servodyn     =   0.40 sec*proc (1 test)

Total Test time (real) =   0.41 sec

The following tests FAILED:
	  8 - AOC_YFix_WSt (Failed)
Errors while running CTest

**Comment by rafmudaf** [comment]
Hi @hamidMech did you catch this line in the error output?

```
8: Error: executable at /scratch/NREL/openfast/build/glue-codes/openfast/openfast does not have proper permissions.
```

**Comment by hamidMech** [comment]
Yes, I did. I have tried to install openfast on my Linux machine connected to the university's network.

**Comment by rafmudaf** [comment]
Ok can you provide some more specific details or questions? Given the error I mentioned above, you should verify that you can execute the executable manually. Simply run it from a terminal like this:

```bash
cd /scratch/NREL/openfast/build/glue-codes/openfast/
./openfast -v
```

Try that and paste the output here.

**Comment by hamidMech** [comment]
Here is the outcome:
--------------------------------------------------------------------------
abedih@tfd105:~/Desktop/scratch/NREL_2/openfast/build/glue-codes/openfast$ ./openfast -v

 **************************************************************************************************
 OpenFAST

 Copyright (C) 2020 National Renewable Energy Laboratory
 Copyright (C) 2020 Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.4.0-53-g3d170ccc
 Compile Info:
  - Compiler: GCC version 8.3.0
  - Architecture: 64 bit
  - Precision: double
  - Date: Nov 11 2020
  - Time: 12:04:42
 Execution Info:
  - Date: 11/16/2020
  - Time: 08:51:27+0100


  OpenFAST terminated normally.

abedih@tfd105:~/Desktop/scratch/NREL_2/openfast/build/glue-codes/openfast$

**Comment by HYFOAM** [comment]
@hamidMech hi
I also encountered the same problem as you. Have you solved it?
Test project /home/luthuyuan1/OpenFAST/build
      Start  1: AWT_YFix_WSt
 1/43 Test  #1: AWT_YFix_WSt .............................***Failed    0.12 sec
      Start  2: AWT_WSt_StartUp_HighSpShutDown
 2/43 Test  #2: AWT_WSt_StartUp_HighSpShutDown ...........***Failed    0.12 sec
      Start  3: AWT_YFree_WSt
 3/43 Test  #3: AWT_YFree_WSt ............................***Failed    0.12 sec
      Start  4: AWT_YFree_WTurb
 4/43 Test  #4: AWT_YFree_WTurb ..........................***Failed    0.12 sec
      Start  5: AWT_WSt_StartUpShutDown
 5/43 Test  #5: AWT_WSt_StartUpShutDown ..................***Failed    0.12 sec
      Start  6: AOC_WSt
 6/43 Test  #6: AOC_WSt ..................................***Failed    0.12 sec
      Start  7: AOC_YFree_WTurb
 7/43 Test  #7: AOC_YFree_WTurb ..........................***Failed    0.12 sec
      Start  8: AOC_YFix_WSt
 8/43 Test  #8: AOC_YFix_WSt .............................***Failed    0.13 sec
      Start  9: UAE_Dnwind_YRamp_WSt
 9/43 Test  #9: UAE_Dnwind_YRamp_WSt .....................***Failed    0.13 sec
      Start 10: UAE_Upwind_Rigid_WRamp_PwrCurve
10/43 Test #10: UAE_Upwind_Rigid_WRamp_PwrCurve ..........***Failed    0.12 sec
      Start 11: WP_VSP_WTurb_PitchFail
11/43 Test #11: WP_VSP_WTurb_PitchFail ...................***Failed    0.12 sec
      Start 12: WP_VSP_ECD
12/43 Test #12: WP_VSP_ECD ...............................***Failed    0.13 sec
      Start 13: WP_VSP_WTurb
13/43 Test #13: WP_VSP_WTurb .............................***Failed    0.12 sec
      Start 14: SWRT_YFree_VS_EDG01
14/43 Test #14: SWRT_YFree_VS_EDG01 ......................***Failed    0.13 sec
      Start 15: SWRT_YFree_VS_EDC01
15/43 Test #15: SWRT_YFree_VS_EDC01 ......................***Failed    0.13 sec
      Start 16: SWRT_YFree_VS_WTurb
16/43 Test #16: SWRT_YFree_VS_WTurb ......................***Failed    0.12 sec
      Start 17: 5MW_Land_DLL_WTurb
17/43 Test #17: 5MW_Land_DLL_WTurb .......................***Failed    0.14 sec
      Start 18: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr
18/43 Test #18: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr ...........***Failed    0.12 sec
      Start 19: 5MW_OC3Trpd_DLL_WSt_WavesReg
19/43 Test #19: 5MW_OC3Trpd_DLL_WSt_WavesReg .............***Failed    0.13 sec
      Start 20: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth
20/43 Test #20: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth ...***Failed    0.13 sec
      Start 21: 5MW_ITIBarge_DLL_WTurb_WavesIrr
21/43 Test #21: 5MW_ITIBarge_DLL_WTurb_WavesIrr ..........***Failed    0.12 sec
      Start 22: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti
22/43 Test #22: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti ....***Failed    0.12 sec
      Start 23: 5MW_OC3Spar_DLL_WTurb_WavesIrr
23/43 Test #23: 5MW_OC3Spar_DLL_WTurb_WavesIrr ...........***Failed    0.13 sec
      Start 24: 5MW_OC4Semi_WSt_WavesWN
24/43 Test #24: 5MW_OC4Semi_WSt_WavesWN ..................***Failed    0.13 sec
      Start 25: 5MW_Land_BD_DLL_WTurb
25/43 Test #25: 5MW_Land_BD_DLL_WTurb ....................***Failed    0.13 sec
      Start 26: 5MW_OC4Jckt_ExtPtfm
26/43 Test #26: 5MW_OC4Jckt_ExtPtfm ......................***Failed    0.13 sec
      Start 27: HelicalWake_OLAF
27/43 Test #27: HelicalWake_OLAF .........................***Failed    0.13 sec
      Start 28: EllipticalWing_OLAF
28/43 Test #28: EllipticalWing_OLAF ......................***Failed    0.12 sec
      Start 29: WP_Stationary_Linear
29/43 Test #29: WP_Stationary_Linear .....................***Failed    0.13 sec
      Start 30: Ideal_Beam_Fixed_Free_Linear
30/43 Test #30: Ideal_Beam_Fixed_Free_Linear .............***Failed    0.12 sec
      Start 31: Ideal_Beam_Free_Free_Linear
31/43 Test #31: Ideal_Beam_Free_Free_Linear ..............***Failed    0.12 sec
      Start 32: 5MW_Land_BD_Linear
32/43 Test #32: 5MW_Land_BD_Linear .......................***Failed    0.13 sec
      Start 33: 5MW_OC4Semi_Linear
33/43 Test #33: 5MW_OC4Semi_Linear .......................***Failed    0.12 sec
      Start 34: bd_5MW_dynamic
34/43 Test #34: bd_5MW_dynamic ...........................***Failed    0.13 sec
      Start 35: bd_5MW_dynamic_gravity_Az00
35/43 Test #35: bd_5MW_dynamic_gravity_Az00 ..............***Failed    0.13 sec
      Start 36: bd_5MW_dynamic_gravity_Az90
36/43 Test #36: bd_5MW_dynamic_gravity_Az90 ..............***Failed    0.12 sec
      Start 37: bd_curved_beam
37/43 Test #37: bd_curved_beam ...........................***Failed    0.12 sec
      Start 38: bd_isotropic_rollup
38/43 Test #38: bd_isotropic_rollup ......................***Failed    0.12 sec
      Start 39: bd_static_cantilever_beam
39/43 Test #39: bd_static_cantilever_beam ................***Failed    0.12 sec
      Start 40: bd_static_twisted_with_k1
40/43 Test #40: bd_static_twisted_with_k1 ................***Failed    0.13 sec
      Start 41: beamdyn_utest
41/43 Test #41: beamdyn_utest ............................   Passed    0.03 sec
      Start 42: nwtc_library_utest
42/43 Test #42: nwtc_library_utest .......................   Passed    0.03 sec
      Start 43: fvw_utest
43/43 Test #43: fvw_utest ................................   Passed    0.03 sec

7% tests passed, 40 tests failed out of 43

Label Time Summary:
aerodyn14    =   0.99 sec*proc (8 tests)
aerodyn15    =   2.52 sec*proc (20 tests)
beamdyn      =   1.39 sec*proc (11 tests)
dynamic      =   0.38 sec*proc (3 tests)
elastodyn    =   3.26 sec*proc (26 tests)
extptfm      =   0.13 sec*proc (1 test)
hydrodyn     =   1.00 sec*proc (8 tests)
linear       =   0.63 sec*proc (5 tests)
map          =   0.37 sec*proc (3 tests)
moordyn      =   0.13 sec*proc (1 test)
olaf         =   0.25 sec*proc (2 tests)
openfast     =   4.14 sec*proc (33 tests)
servodyn     =   3.39 sec*proc (27 tests)
static       =   0.50 sec*proc (4 tests)
subdyn       =   0.38 sec*proc (3 tests)

Total Test time (real) =   5.19 sec

The following tests FAILED:
          1 - AWT_YFix_WSt (Failed)
          2 - AWT_WSt_StartUp_HighSpShutDown (Failed)
          3 - AWT_YFree_WSt (Failed)
          4 - AWT_YFree_WTurb (Failed)
          5 - AWT_WSt_StartUpShutDown (Failed)
          6 - AOC_WSt (Failed)
          7 - AOC_YFree_WTurb (Failed)
          8 - AOC_YFix_WSt (Failed)
          9 - UAE_Dnwind_YRamp_WSt (Failed)
         10 - UAE_Upwind_Rigid_WRamp_PwrCurve (Failed)
         11 - WP_VSP_WTurb_PitchFail (Failed)
         12 - WP_VSP_ECD (Failed)
         13 - WP_VSP_WTurb (Failed)
         14 - SWRT_YFree_VS_EDG01 (Failed)
         15 - SWRT_YFree_VS_EDC01 (Failed)
         16 - SWRT_YFree_VS_WTurb (Failed)
         17 - 5MW_Land_DLL_WTurb (Failed)
         18 - 5MW_OC3Mnpl_DLL_WTurb_WavesIrr (Failed)
         19 - 5MW_OC3Trpd_DLL_WSt_WavesReg (Failed)
         20 - 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth (Failed)
         21 - 5MW_ITIBarge_DLL_WTurb_WavesIrr (Failed)
         22 - 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti (Failed)
         23 - 5MW_OC3Spar_DLL_WTurb_WavesIrr (Failed)
         24 - 5MW_OC4Semi_WSt_WavesWN (Failed)
         25 - 5MW_Land_BD_DLL_WTurb (Failed)
         26 - 5MW_OC4Jckt_ExtPtfm (Failed)
         27 - HelicalWake_OLAF (Failed)
         28 - EllipticalWing_OLAF (Failed)
         29 - WP_Stationary_Linear (Failed)
         30 - Ideal_Beam_Fixed_Free_Linear (Failed)
         31 - Ideal_Beam_Free_Free_Linear (Failed)
         32 - 5MW_Land_BD_Linear (Failed)
         33 - 5MW_OC4Semi_Linear (Failed)
         34 - bd_5MW_dynamic (Failed)
         35 - bd_5MW_dynamic_gravity_Az00 (Failed)
         36 - bd_5MW_dynamic_gravity_Az90 (Failed)
         37 - bd_curved_beam (Failed)
         38 - bd_isotropic_rollup (Failed)
         39 - bd_static_cantilever_beam (Failed)
         40 - bd_static_twisted_with_k1 (Failed)
Errors while running CTest
Makefile:72: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by hamidMech** [comment]
@HYFOAM 
Not yet. Still waiting.

**Comment by rafmudaf** [comment]
> Here is the outcome:
> 
> abedih@tfd105:~/Desktop/scratch/NREL_2/openfast/build/glue-codes/openfast$ ./openfast -v
> 

@hamidMech This is not the same path that you have set up in the original post. Double check your paths and that you are pointing to the correct executables.

@HYFOAM Like I suggested to @hamidMech, provide more details on your issue. Try to describe the problem by getting more information. Use the CTest command that @hamidMech used in the original post to run a single case with verbose output (its the one beginning with `ctest -VV -R`).

**Comment by hamidMech** [comment]
@rafmudaf 

Here is the outcome:

abedih@tfd105:/scratch/NREL/openfast/build/glue-codes/openfast$ ./openfast -v

 **************************************************************************************************
 OpenFAST

 Copyright (C) 2020 National Renewable Energy Laboratory
 Copyright (C) 2020 Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.4.0-53-g3d170ccc
 Compile Info:
  - Compiler: GCC version 8.3.0
  - Architecture: 64 bit
  - Precision: double
  - Date: Nov 11 2020
  - Time: 11:49:45
 Execution Info:
  - Date: 11/30/2020
  - Time: 17:48:44+0100


  OpenFAST terminated normally.

abedih@tfd105:/scratch/NREL/openfast/build/glue-codes/openfast$

**Comment by rafmudaf** [comment]
Can you describe the system you're using to run this? Is this a compute node?

**Comment by hamidMech** [comment]
@rafmudaf 

It is not a compute node. It is a desktop machine connected to the university's network.

Here is the output of  "uname -a" command:

4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

**Comment by rafmudaf** [comment]
Nothing stands out as a problem here. My suggestion is for you to try to understand why the testing framework may not be able to execute the OpenFAST executable.

You could try moving the project under your home directory rather than `/`. If you do that, you'll have to reconfigure CMake and CTest since all of the paths will be incorrect.
