### ISSUE TITLE
gfortran: fatal error: Killed signal terminated program f951 with 8GB Memory

### ISSUE THREAD

**Issue by jgeisler0303** [OpenFAST/openfast#591]
Hi,
I guess this is not really an issue but rather a FYI. But I want to report it anyway in case it can help others to save some head scratching.

I am compiling OpenFAST on a Raspberry Pi 4 with 4GB of RAM plus 4GB swap space. It runs Ubuntu Mate 20.04 64 bit from a 32GB sd-card.

The compile always fails at ``FAST_Types`` or ``FAST_Subs`` with ``gfortran: fatal error: Killed signal terminated program f951`` which indicates that the compile process ran out of memory. This can be verified by looking into ``journalctl`` where there is an entry stating ``Out of memory: Killed process 7372 (f951) total-vm:7754732kB, anon-rss:3603420kB, ...``. This also shows that the compiler took almost 8GB of memory!

This happens with the latest HEAD and v2.4.0 in ``Release`` and ``RelWithDebInfo`` mode (I didn't test Debug mode). It doesn't happen in v2.3.0. The huge memory demand seems to be caused by the optimization flags (``-O2`` and ``-O3``). Between ``-O2 -g`` and only ``-O2`` there is no big difference. Only with ``-g`` I get the note ``note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without``.

What is really strange though, is that I think I ran the very first compilation totally normal (``git clone ..., cmake .., make -j4`` and evrything went fine. And that was even without any swap. So, there really might be a problem with my system. Or I somehow managed to build in Debug mode the first time without being aware of it. At least I was never able to replicate a successful compilation of HEAD in Release mode.

To Do:
- [ ] Check for memory overhead during compile between versions

**Comment by rafmudaf** [comment]
Thanks for reporting this. I've noticed a significant difference in memory requirements between `-O2` (RelWithDebInfo) and `-O3` (Release) in the past, but I have not checked this across versions. Debug mode (`-O0`) should reduce the memory even further and it also speeds up the compilation significantly. I'm leaving this open for future reference and also so that we can check the memory footprint across versions and report back.

Does your usage of OpenFAST depend on a Raspberry Pi? If so, you should consider compiling in single precision for better performance.

And for what its worth, you can install the latest OpenFAST release with conda through conda-forge without compiling anything.

**Comment by jgeisler0303** [comment]
Thanks for the quick reply.

Now that you mention it, I think I remeber, that ``-O3`` ran out of memory even with v2.3.0.

Compiling without optimization is by far less charging on the CPU and memory. I think the compilation time for ``FAST_Subs`` with and without optimization was 18 minutes vs. 38 seconds.

Since I want to stick to the Pi, I absolutely need any speed optimization I can get. Therefore thanks for the hint about single precision. And I will also try conda-forge. Until now I thought that this is just another build system :-)

**Comment by rafmudaf** [comment]
Cool, conda would be the easiest route to use OpenFAST. Conda contains a build system (`conda-build`) but generally conda is a package manager. Conda-forge is a repository of packages in addition to the main packages hosted by Anaconda. Thats the high level explanation. If you're just wanting to install packages, forget about `conda-build`. All you really need to know is `conda create`, `conda activate`, and `conda install`.

**Comment by jgeisler0303** [comment]
I know, this is starting to get OT, but still...

Just installed ``https://github.com/conda-forge/miniforge`` and tried to install openfast but there doesn't seem to be a linux arm 64 version. Also, looking at these files https://anaconda.org/conda-forge/openfast/files I can't see one. Am i missing something?

**Comment by rafmudaf** [comment]
Ah shoot that's true - I forgot pi's are ARM. I guess conda is a no go for you, at the moment, but I'll see if I can configure a build for that architecture.

**Comment by rafmudaf** [comment]
It looks like there is a path for building with Conda-forge for Arm by configuring Drone CI. If you are interested to help set this up, look at this branch of the OpenFAST Conda-forge feedstock: https://github.com/conda-forge/openfast-feedstock/tree/aarch64. We need to configure the `.drone.yml` file correctly and then integrate Drone to GitHub. A quick look at the documentation makes it seem like this is an involved process.

**Comment by andrew-platt** [comment]
Another option may be be to use a swapfile on the PI during compile:  https://pimylifeup.com/raspberry-pi-swap-file/

**Comment by jgeisler0303** [comment]
@rafmudaf: for now I have v2.3.0 compiled an running and the build time was not so terrible. I might come back to the configuration of conda but for now I don't really have the time for more involved stuff even though I always wanted to learn some more about CI.

@andrew-platt: I already had 4GB of swap active and could probably add another 8GB. But swapping slows things down a lot. And I was really shocked to see a 8000 line source file taking 8GB of memory.

And another OT: the NREL forum is loading really slow and often incomplete or not at all. Do you know about any issues there?

**Comment by jonsowman** [comment]
In case it may help with debugging this issue, I am hitting the same error on Ubuntu 18.04 LTS, x86_64 arch + 8GB RAM.

This happens in both `Release` and `RelWithDebInfo`, but compilation is OK in `Debug` mode.

**Comment by bjonkman** [comment]
@jgeisler0303 , I have also noticed the issue with the NREL forum not loading on Firefox lately. It seems to work better on other browsers, though.

**Comment by jgeisler0303** [comment]
@bjonkman: ah, yes, in Chromium it works perfectly. Thanks.
