### ISSUE TITLE
Usage quesiton about 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth module

### ISSUE THREAD

**Issue by ChaoREN1994** [OpenFAST/openfast#592]
Hello 

I have a question about 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth module .  If i would like to simulate the Design situation "Parked" from IEC-3 standrd as showed following:
![image](https://user-images.githubusercontent.com/66703137/99257386-3dbbaa80-2817-11eb-9c14-b40acfd48409.png)
It is note "parked" with extreme wind model for example with wind velocity 42.37m/s.
How could i simulate that in Openfast ? It will be the same as normal situation like power production cases. if yes, how could i set the intial values like pitch angle, rotor speed , since i did not find the reference in the PDF "Definition of a 5-MW Reference
Wind Turbine for Offshore System Development".   Or, i do not need to set the intial values? 

Regards
Chao REN

**Comment by jjonkman** [comment]
Dear @ChaoREN1994,

I would guess that you'd rather model an idling rotor than a parked rotor, which is more common for this load case.  To model the NREL 5-MW baseline wind turbine as an idling rotor in OpenFAST, specify the following inputs:

In the ElastoDyn's primary input file:

- BlPitch1 = BlPitch2 = BlPitch3 = 90.0 (fully feathered)
- RotSpeed = 0.0

In the InflowWind primary input file:

- Specify the desired turbulent or steady wind.  For turbulent wind, you'd first have to run TurbSim.


In the AeroDyn v15's primary input file:

- WakeMod = 0 (disable aerodynamic induction)
- AFAeroMod = 1 (disable dynamic stall, which isn't valid at large angles of attack)

In the ServoDyn's primary input file:

- PCMode = 0 (disable pitch control)
- GenTiStr = True
- TimGenOn = 9999.9 (a large number > TMax) so as to not start the generator

Best regards,

**Comment by ChaoREN1994** [comment]
Thanks for your reply.  @jjonkman

**Comment by ChaoREN1994** [comment]
Hello, @jjonkman 

Following your advices, I  reset  the parameters in  ElastoDyn, InflowWind, AeroDyn v15 and ServoDyn for the idling rotor.  I tried to simulate with steady and turbulence wind cases in 10 mins. Here are the loads results obtained from the tower base.


Fx in steady and turbulence cases
![Fx](https://user-images.githubusercontent.com/66703137/101483332-5459ab00-3958-11eb-9192-2bafa8196aa0.png)
Fy in steady and turbulence cases
![fy](https://user-images.githubusercontent.com/66703137/101483334-54f24180-3958-11eb-922b-70f3be541d09.png)
Fz in steady and turbulence cases
![Fz](https://user-images.githubusercontent.com/66703137/101483337-558ad800-3958-11eb-9360-bc584a9456cc.png)
Mx in steady and turbulence cases
![mx](https://user-images.githubusercontent.com/66703137/101483352-5b80b900-3958-11eb-900f-98ae7d0a1c38.png)
My in steady and turbulence cases
![my](https://user-images.githubusercontent.com/66703137/101483354-5b80b900-3958-11eb-8b6a-463701885b37.png)
Mz in steady and turbulence cases
![mz](https://user-images.githubusercontent.com/66703137/101483355-5c194f80-3958-11eb-862f-3624ee445133.png)


For steady cases , it seems that the results in loads (Fy,Mx, Mz), they are periodic.  Is that due to the resonance? Is that normal in the the idling rotor case?  But in the loads(Fx,My,Fz) and turbulence case, it seems Ok.

Looking forward to your reply
Best regrads
Chao REN

**Comment by jjonkman** [comment]
Dear @ChaoREN1994,

I'm a bit surprised that the mean Fx and My are not the same between steady and turbulent wind cases.  Is the mean shear profile and mean nacelle-yaw error (nacelle angle / wind direction) the same in both cases?

Regarding the variation in the steady wind case, I would assume that this is correlated with some nonzero rotor rotation; can you confirm?

Best regards,

**Comment by ChaoREN1994** [comment]
Hello, @jjonkman 

Thanks for your reply.

1. First,  the mean Fx and My are not the same in the steady and turbulent wind cases, because the wind speed at reference height are different in these two cases. The mean wind velocity at reference height in  turbulent cases (DLC 6.1a)  equal to 0.95 * Vref and wind velocity at reference height in steady case(DLC 6.1b) equal to  1.3 *Vref.  It is my fault . I did not mention that in the comparison.  If the mean wind velocity of turbulent cases equal to wind velocity in the steady cases at reference height,  the mean Fx is the same like following:
![Fx](https://user-images.githubusercontent.com/66703137/101628857-c3023b80-3a20-11eb-9729-9fd1c565d217.png)

2.  Yes,  you are right.  The rotor rotation are not zero as showed in the following.
Rotor speed
![rotspeed](https://user-images.githubusercontent.com/66703137/101629020-fba21500-3a20-11eb-9466-659760c92bb9.png)
Mz in steady and turbulent cases
![Mz](https://user-images.githubusercontent.com/66703137/101629261-5dfb1580-3a21-11eb-9397-2127cfdf62f0.png)

3.   Could i fix  the rotor speed to zero during the simulation?  

Best regards 
Chao REN

**Comment by jjonkman** [comment]
Hi @ChaoREN1994,

OK, thanks for clarifying.  That makes sense now.

You can fix (park) the rotor by disabling the generator DOF (GenDOF = False) in ElastoDyn.

Best regards,
