### ISSUE TITLE
OpenFAST build does not include src to build DISCON dynamic library

### ISSUE THREAD

**Issue by ghaymanNREL** [OpenFAST/openfast#6]
A DISCON dynamic-linked library (DLL) is needed to run OpenFAST if the ServoDyn input file is using option 5 for the PCMode and VSContrl parameters.

The DISCON DLL is built from a fortran file containing the DISCON subroutine with the following interface:

SUBROUTINE DISCON ( avrSWAP, aviFAIL, accINFILE, avcOUTNAME, avcMSG ) BIND (C, NAME='DISCON')
!DEC$ ATTRIBUTES DLLEXPORT :: DISCON

We should probably include a 'dummy' DLL in a standard build via a DISCON.f90 file, and people can replace the dummy DISCON.f90 file with their own if they need a certain controller behavior.  Perhaps this DISCON.f90 file lives in modules-local/servodyn/src ?

As a side note, various regression tests need different flavors of the DISCON DLL, what process is responsible for building these prior to launching regression tests?  Perhaps this is a separate issue!

**Comment by sayerhs** [comment]
I thought we used the dynamic library loading capability to load the dll instead of compiling openfast with it, so why do we need a dummy `DISCON.f90` file?

**Comment by ghaymanNREL** [comment]
You are correct, but how do I create the DISCON.DLL in the first place.  The code and build of the dll from that code are not in OpenFAST. Where do we send people if they are to use that option.  You have to have it available somewhere, right?

**Comment by gantech** [comment]
So, the DISCON.f90 file was in the CertTest directory in the earlier distributions of FAST. May be we include it in the test repo?

**Comment by sayerhs** [comment]
I see this as part of glue-codes similar to simulink or labview. Most likely the DISCON interface would link to some matlab/simulink codebase (at least based on my experience at Envision).

**Comment by ghaymanNREL** [comment]
While that was true, it seems odd that something needed to use OpenFAST lives outside of the OpenFAST repo.  I’m not sure I like OpenFAST-test as the home for Discon.f90 and it’s build system…

**Comment by rafmudaf** [comment]
This issue has been fixed by pull request #115
