### ISSUE TITLE
Tower frequency decay tests

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#600]
Hi openFAST dev. Team,

I have a question related to tower system ID analysis. We are trying to validate the tower model in openFAST of an offshore turbine against a commercial code BLADED.

For the tower model, we provide the FA1, SS1 modal damping (in terms of % of crit. damping) = 1% and FA2, SS2 modal damping = 2% following the tower model in BLADED. 

The inputs are as follows: 

1.0      TwrFADmp(1) - Tower 1st fore-aft mode structural damping ratio (%)
2.0      TwrFADmp(2) - Tower 2nd fore-aft mode structural damping ratio (%)
1.0      TwrSSDmp(1) - Tower 1st side-to-side mode structural damping ratio (%)
2.0      TwrSSDmp(2) - Tower 2nd side-to-side mode structural damping ratio (%)

When we do a system ID test (decay or ping test) of the tower we have the following observations.

For FA1, SS1 modes
i) Flexible tower + RNA mass + rigid blade = 0.4% damping (percent of critical damping)
ii) Flexible tower + no RNA mass (1e-5 kg of nacelle/hub + generator mass + 1e-5 kg of blade mass) = 1 % damping (percent of critical damping)

Similar observations are seen for FA2 and SS2 modes as well. 

So my question is when I input 1% and 2% of the modal damping of the tower in Elastodyn input file is it only reflecting the tower only damping? Is the only way to 1% FA1, SS1 damping and 2% FA2, SS2 damping achievable by tuning the ``TwrFADmp`` and ``TwrSSDmp`` variables, or am I doing something fundamentally inconsistent here?

Any insights would be valuable.

Best Regards,

**Comment by tchatte3** [comment]
Additionally, we did some system ID test with Tower + nacelle+hub mass but 0 rotor blade mass. 

Here are the results: 

For FA1, SS1 modes
i) Flexible tower + RNA mass + rigid blade = 0.4% damping (percent of critical damping)
ii) Flexible tower +  nacelle hub mass but no blade mass (1e-5 kg of blade mass mass),  = ~ 0.5% damping (percent of critical damping)
ii) Flexible tower + no RNA mass (1e-5 kg of nacelle/hub + generator mass + 1e-5 kg of blade mass) = 1 % damping (percent of critical damping)

Any suggestions/insights? 

Best Regards,

**Comment by ebranlard** [comment]
Dear @tchatte3 

You are correct, the damping you give as input in ElastoDyn is for an "isolated" tower. You can verify it by doing a decay test with a RNA of zero mass. 

One way to access the dampings and frequencies of the full structure, is to perform a linearization analysis with OpenFAST (right now we have postprocessing tools for that in Matlab, though it takes a bit of time to learn and get used to https://github.com/OpenFAST/matlab-toolbox/blob/master/Campbell/example/runCampbell_Trim.m). You probably want to start with only one operating point (e.g. at a 0 wind speed). When I have time, I might add another example script to simply postprocess one linearization file for one operating point. 

Another way to estimate the frequencies and damping would be to integrate the generalized mass and generalized stiffness of the tower (integrating the shape functions of the tower against the tower mass and the stiffness). From this you can get the isolated tower frequency. You can add the RNA inertias to the generalized mass, and use this to get the "full structure" frequency. The ratios of these two frequencies will give you a factor to increase the tower damping to the desired "full structure" damping. 

Linearization would be the more generalized approach.  

I hope that will help you out a bit,

Emmanuel

**Comment by tchatte3** [comment]
Hi Emannuel,

Thanks a lot for your detailed answer. This is really insightful. Yes, I did decay test with 1e-6 (almost 0) RNA mass and was able to get 1% and 2% damping. 

I was able to confirm that when I did the decay test of the full tower + RNA + support structure , I get the same damping ratio as I get from the parked campbell analysis (0 wind speed, 0 rot-speed) with your MATLAB code ~ 0.4%. So, yes, eigenvalue and log-dec indeed gives me similar result which is corroborative. 

Regarding your comment 
"Another way to estimate the frequencies and damping would be to integrate the generalized mass and generalized stiffness of the tower (integrating the shape functions of the tower against the tower mass and the stiffness). From this you can get the isolated tower frequency.". 

I understand what you mean, i.e., to get nat. frequency ~ sqrt (generalized stiffness /generalized mass ). And to calculate that generalized mass and stiffness would we have to take inner product of the tower respective mode shapes with HFract? Could you perhaps give a little bit of extra detail on that?

Thank you for the help,
Tanmoy

**Comment by ebranlard** [comment]
Hi Tanmoy,

That sounds good. 

I think your understanding is correct. For the "direct" calculation approach, I wrote some of the theory in the following [article](https://onlinelibrary.wiley.com/doi/pdf/10.1002/we.2327), where section 5.1 provide some simple examples, in line with the calculations you would need. 

For one shape function (`Phi(z)`), you can compute the generalized mass and stiffness of the tower as follows:
![image](https://user-images.githubusercontent.com/1318316/100003995-166b5d00-2d84-11eb-8cc9-c29fc63cb964.png)
You can add the RNA mass to the generalized tower mass to compute the "full-system" frequency `omega=sqrt(K/(M+M_RNA))`

I do have some scripts to compute all this, but it will probably take me a couple of weeks to find time to sort them out... 

You can use this to get first estimates. 

Cheers,

Emmanuel




The general case would be slightly too complex to detail,

**Comment by tchatte3** [comment]
Hi Emmanuel,

Thanks for giving me the right direction. I think I have the idea to compute omega directly from the tower model which will serve as a triple-check.

Thanks, I am closing this channel now.

**Comment by ebranlard** [comment]
Sounds good, I'll put some links to some scripts when I get to it. It might arrive too late, but hopefully that can be a "quadruple check" :)

**Comment by tchatte3** [comment]
Thanks Emmanuel, I really appreciate it.
