### ISSUE TITLE
ReadFASTbinary Prints Incorrect Times

### ISSUE THREAD

**Issue by brendansndrs** [OpenFAST/openfast#601]
Hi,

I am trying to use the ReadFASTBinary function provided in the matlab-toolbox to read the `.outb` file produced by OpenFAST. However, when I read the file into Matlab, the time column is incorrect. For example, with the following settings from my `.fst` file:
```
     0.0125   DT              - Recommended module time step (s)
     0.0125   DT_Out          - Time step for tabular output (s) (or "default")
          0   TStart          - Time to begin tabular output (s)
          2   OutFileFmt      - Format for tabular (time-marching) output file (switch) {1: text file [<RootName>.out], 2: binary file [<RootName>.outb], 3: both}
```
I expect the output time to be: `0, 0.0125, 0.0250, ...`. However, I get: `0, 0, 0.0298, 0.0298, 0.0595, 0.0595, ...`. It does produce the correct number of data points, I run a 3900 second simulation and get a total of 312,001 lines.

Is there a setting in OpenFAST that I may have missed that would resolve this?

Thanks

**System Information**
**OS:** CentOS 7
**OpenFAST Version:** 2.3.0, compiled in single precision as a .so for use with Matlab/Simulink
**matlab-toolbox Version:** cloned 2020-11-18
**Matlab Version:** 2020b

**Comment by ebranlard** [comment]
Thanks for reporting this. If you are familiar with python, you can try with our python reader (see the Examples in the following [README](https://github.com/OpenFAST/python-toolbox/tree/master/pyFAST/input_output). 

Can you try to reproduce the error with a smaller file, maybe with 5 time steps only? Feel free to enclose this small binary file in that case.

**Comment by brendansndrs** [comment]
Thanks for your response,

I ran a 1 second simulation (80 time steps) and it did output the correct time information, unfortunately the `.outb` file was still ~50 MB, so I won't upload it here.

I am not too familiar with python, but I did try using the reader with the provided example code and it did not appear to fix the problem.

**Comment by ebranlard** [comment]
Thanks for doing the test.  I'm not sure what the issue can be. 
Here's some things to try if you don't mind:
- Can you tell us the values of the variables NT, FileID, NumOutChans read by the matlab reader? (The time is read differently based on the FileID, you can have a look at how `Channels(:,1) ` is set to figure what input is wrong).  What is the total file size? 
- Can you try with OutFileFmt =3 (you'll get a binary and ascii, maybe quite large...), and see if the ascii has any issue. 
- Can you try with less output sensors but the same simulation time? 

Sorry, I'm not quite sure what's happening.. My guess is that some memory might have gotten corrupted somewhere, or some overflow/underflow may have occurred. 

You can also try to send a wetransfer link with the file.

**Comment by brendansndrs** [comment]
I spent some more time trying different time lengths etc.

It turns out that even the 1 second simulation is not correct, just that the errors were small and I didn't see them in Matlab until I actually printed the number.

For a 0.05 second simulation:
```
0.0125000953681592
0.0249998092636815
0.0374999046318408
0.0500000000000000
```

For a 1 second simulation:
```
0.0124970435870635
0.0250017166268664
0.0374987602139299
0.0500034332537327
...
```

In response to bullet 1:

- FileID = 1
- NumOutChans = 79 (the expected number)
- NT = 312,001
- Filesize: `.outb` = ~49 MB; `.out` = ~270 MB (for a 3900 second simulation)

Regarding bullet 2: when written out to the ASCII file the times are correct, the rest of the data also appears to be reasonable. Furthermore, when I look at the Simulink simulation output contained in Matlab the times are correct.

Regarding bullet 3, I haven't tried this yet.

Furthermore, I compared the data from a 100 second simulation with the data from the first 100 seconds of a 500 second simulation and found that there were differences not just in time, but other output channels had differences at the 1e-3 level. I'm not sure if this is expected/relevant but thought it might be worth mentioning.

I'm wondering if this is caused by the scaling that is applied to the data (through TimeScl and TimeOff etc.). Are there any Matlab scripts that exist to write data into the OpenFAST binary format? I have to run a significant number of simulations, and the ASCII files are ~5 times larger than the binary files. Furthermore, I am using MLife for fatigue post-processing, so I need the data in a FAST format, or I need to adjust how MLife reads the data in.

**Comment by ebranlard** [comment]
I'm suspecting that these issues indeed come from the scaling. Data are scaled (removing the mean and dividing by the range), before being stored as unsigned int. The time vector is clearly a difficult input since the data spread further and further from the mean, so there will be a loss of accuracy on Delta t. I haven't done the calculation for your specific case, but that might be what's happening. Some imprecisions are to be expected on delta t, but probably not as strong as the ones you observed in your first post. 
We have other binary formats (as you can see at the top of ReadFASTBinary), but I'm not quite sure how to activate them, I'll have to look at the source code of OpenFAST. 

I believe the type conversions between Matlab (likely in double) and OpenFAST (in single), will affect the results as well. 

If you have the data in Matlab, you could write it as an OpenFAST binary to try, but I'm afraid the results will be the same, and I don't think we have writers for now. If you write one, thank you for sharing it with us. 

It seems like right now a solution would be to save the data as a mat file, and indeed adjust MLife. 

Maybe @bjonkman  and @andrew-platt  have a better guidance?

**Comment by andrew-platt** [comment]
Do you see precision issues in the uncompressed `.outb` format (`OutFileFmt == 0` in the main .fst input file)?  The matlab binary reader [here](https://github.com/OpenFAST/matlab-toolbox/blob/master/Utilities/ReadFASTbinary.m) supports this format.

Unfortunately, when that option is used, it will produce both the .outb and .out format, thereby using more disk space.

**Comment by brendansndrs** [comment]
Using `OutFileFmt = 0` does result in the time being displayed correctly. However, I was trying to avoid writing any ASCII formatted files because (as I understand) it has to be written out at every time step. I am also running a large number of simulations, and while I can delete them after creation to save space, I would prefer not to.

I think I will save the outputs as `.mat` files and then use these to write to the uncompressed file format prior to processing in MLife. This will only require me to replace the `ReadFASTbinary` file in MLife with the one from `matlab-utilities` rather than rewrite any of the source code.

Is there a way to stop OpenFAST from writing any output files so that I can just keep the `.mat` files?

Thanks

**Comment by bjonkman** [comment]
In OpenFAST 2.3.0, the Simulink binary output files store the time channel differently than the binary files generated from the command-line executable code (and the uncompressed .outb file). The original FAST level-1 S-Function could be called multiple times at a give time step, depending on the integration method used in Simulink, so we needed to store the time channel. The OpenFAST S-Function is now a level-2 S-Function, which is supposed to be called just once per time, so in OpenFAST 2.4.0, I modified it to use the same binary format as the command-line executable and uncompressed file: these just store the first output time and the delta-t.

The time-column compression uses 32-bit integers, so it can store only 131,071 unique values (I think we were concerned about file size, but looking back, we probably should not have compressed that channel at all). You have more than twice that number of time steps, so the compression is rounding the values, making it appear as if the time steps are repeated. I would either override the time channel manually, or update to OpenFAST 2.4.0 where this won't be an issue in the compressed binary files. You could also use the uncompressed files or rebuild OpenFAST 2.3.0 after changing some source code:

Change FAST_Subs.f90, lines 2687 and following from:
```
#if defined COMPILE_SIMULINK || defined COMPILE_LABVIEW
   !bjj: 2015-03-03: not sure this is still necessary...
            p%WrBinMod = FileFmtID_WithTime            ! We cannot guarantee the output time step is constant in binary files
#else
            p%WrBinMod = FileFmtID_WithoutTime         ! A format specifier for the binary output file format (1=include time channel as packed 32-bit binary; 2=don't include time channel;3=don't include time channel and do not pack data)
#endif   
```
to
```
            p%WrBinMod = FileFmtID_WithoutTime         ! A format specifier for the binary output file format (1=include time channel 
```

**Comment by bjonkman** [comment]
@rafmudaf , this issue can be closed.
