### ISSUE TITLE
Simulink interface with OpenFAST crashes Matlab

### ISSUE THREAD

**Issue by bjonkman** [OpenFAST/openfast#605]
I am creating a new issue here because there are too many topics going on in issue #548:

From @eletroinf:

I Have the same problem with openFAST 2.4.0-master and dev.
Compilation with Visual studio and mex generated by C compiler installed by means of Matlab Add-on (Matlab 2018b).

The S-function generated using v 2.4.0 source files works fine with openFAST 2.3.0 that I also compiled with Visual Studio. So I think the problem is not with the S-function.

Neither my project nor the examples works - all them result in Matlab crash.

_Originally posted by @eletroinf in https://github.com/OpenFAST/openfast/issues/548#issuecomment-734929035_

**Comment by bjonkman** [comment]
I just tried to generate S-function changing the parameter #define CHANNEL_LENGTH 20 in FAST_library.h file and I got the same problem. Here is my Matlab output:

--------------------------------------------------------------------------------
               abort() detected at sex nov 27 09:49:16 2020 -0300
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : windows-1252
  Deployed                 : false
  Graphics Driver          : Unknown hardware 
  Graphics card 1          : Intel Corporation ( 0x8086 ) Intel(R) UHD Graphics 630 Version 27.20.100.8681 (2020-9-5)
  Java Version             : Java 1.8.0_152-b16 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : win64
  MATLAB Entitlement ID    : 6257193
  MATLAB Root              : C:\Program Files\MATLAB\R2018b
  MATLAB Version           : 9.5.0.944444 (R2018b)
  OpenGL                   : hardware
  Operating System         : Microsoft Windows 10 Pro
  Process ID               : 9896
  Processor ID             : x86 Family 6 Model 158 Stepping 10, GenuineIntel
  Session Key              : 2e3cb4b1-3a3b-46b0-bf51-135d94257c8d
  Window System            : Version 10.0 (Build 18363)

Fault Count: 1


Abnormal termination

Register State (captured):
  RAX = 00000000107aedd8  RBX = 00000000107aedd8
  RCX = 00000000043ed920  RDX = 0000000000000000
  RSP = 00000000043ed890  RBP = 00000000043f0e39
  RSI = 0000000000000000  RDI = 0000000000000000
 
   R8 = 00000000000dc430   R9 = 00007ffc4a14e930
  R10 = 0000000000000014  R11 = 00000000000d5980
  R12 = 00000000043ee558  R13 = 0000000000000000
  R14 = 000000001079ed08  R15 = 00000000043edf90
 
  RIP = 000000001055292a  EFL = 00000206
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (captured):
[  0] 0x000000001054b2c3                              bin\win64\libmwfl.dll+00045763 foundation::core::diag::thread_context::unspecified_bool+00000051
[  1] 0x0000000010549288                              bin\win64\libmwfl.dll+00037512 foundation::core::diag::stacktrace_base::capture+00000024
[  2] 0x000000001054db80                              bin\win64\libmwfl.dll+00056192 foundation::core::diag::symbols::getSymbolAddress+00009632
[  3] 0x000000001055165f                              bin\win64\libmwfl.dll+00071263 foundation::core::diag::is_terminate_message_enabled+00000575
[  4] 0x0000000016dbeb3f                                  bin\win64\mcr.dll+01108799 QueryMLFcnTable_mcr+00047535
[  5] 0x0000000016dbe277                                  bin\win64\mcr.dll+01106551 QueryMLFcnTable_mcr+00045287
[  6] 0x0000000016dba2b0                                  bin\win64\mcr.dll+01090224 QueryMLFcnTable_mcr+00028960
[  7] 0x0000000016dbbec7                                  bin\win64\mcr.dll+01097415 QueryMLFcnTable_mcr+00036151
[  8] 0x00007ffc5307caad                   C:\WINDOWS\System32\ucrtbase.dll+00445101 raise+00000477
[  9] 0x00007ffc5307dab1                   C:\WINDOWS\System32\ucrtbase.dll+00449201 abort+00000049
[ 10] 0x00007ffc5307d20f                   C:\WINDOWS\System32\ucrtbase.dll+00446991 terminate+00000031
[ 11] 0x00007ffc4a142388 C:\Program Files\MATLAB\R2018b\bin\win64\VCRUNTIME140.dll+00009096 is_exception_typeof+00002312
[ 12] 0x00007ffc4a141ec2 C:\Program Files\MATLAB\R2018b\bin\win64\VCRUNTIME140.dll+00007874 is_exception_typeof+00001090
[ 13] 0x00007ffc4a14b950 C:\Program Files\MATLAB\R2018b\bin\win64\VCRUNTIME140.dll+00047440 _CxxFrameHandler3+00000144
[ 14] 0x00007ffc5554184f                      C:\WINDOWS\SYSTEM32\ntdll.dll+00661583 _chkstk+00000287
[ 15] 0x00007ffc5550a889                      C:\WINDOWS\SYSTEM32\ntdll.dll+00436361 RtlRaiseException+00000921
[ 16] 0x00007ffc5550a643                      C:\WINDOWS\SYSTEM32\ntdll.dll+00435779 RtlRaiseException+00000339
[ 17] 0x00007ffc532e3b29                 C:\WINDOWS\System32\KERNELBASE.dll+00277289 RaiseException+00000105
[ 18] 0x00007ffc4a1444f2 C:\Program Files\MATLAB\R2018b\bin\win64\VCRUNTIME140.dll+00017650 CxxThrowException+00000194
[ 19] 0x000000000d89d18a                     bin\win64\libmwsl_services.dll+00512394 slsvStringOrID::untranslatedStr+00073226
[ 20] 0x000000000d8a2746                     bin\win64\libmwsl_services.dll+00534342 slsvThrowIExceptionFromDiagnostic+00000310
[ 21] 0x000000017406c8a2                    bin\win64\codermapping_core.dll+00051362 mds::BlockMapping::setBlock+00000354
[ 22] 0x0000000174094a28                    bin\win64\codermapping_core.dll+00215592 sl::MappingManager::checkValidMappingType+00000168
[ 23] 0x00000001740966df                    bin\win64\codermapping_core.dll+00222943 sl::MappingManager::getActiveModelMapping+00000031
[ 24] 0x0000000174095e8a                    bin\win64\codermapping_core.dll+00220810 sl::MappingManager::detachBdListener+00000762
[ 25] 0x000000001a8a2c08                                  bin\win64\udd.dll+00404488 UDListener::removeListenerContainer+00002392
[ 26] 0x000000001a89ac8c                                  bin\win64\udd.dll+00371852 UDEventInfo::send+00000092
[ 27] 0x000000025e7367d0                  bin\win64\libmwconfigset_base.dll+01075152 mds::postBdEvent+00000144
[ 28] 0x00000000ffeb1035                   bin\win64\simulink_configset.dll+00069685 detachConfigSet+00002597
[ 29] 0x00000000ffeb12d2                   bin\win64\simulink_configset.dll+00070354 restoreOrigConfigSetForBuild+00000322
[ 30] 0x000000000acabbe4                        bin\win64\libmwsimulink.dll+10140644 sldeutils::searchAvailableFunctions+00190052
[ 31] 0x000000000aca73f2                        bin\win64\libmwsimulink.dll+10122226 sldeutils::searchAvailableFunctions+00171634
[ 32] 0x000000000aca8234                        bin\win64\libmwsimulink.dll+10125876 sldeutils::searchAvailableFunctions+00175284
[ 33] 0x000000000b572804                        bin\win64\libmwsimulink.dll+19343364 slstSetOutputPortRateID+00361588
[ 34] 0x000000000b5365e4                        bin\win64\libmwsimulink.dll+19097060 slstSetOutputPortRateID+00115284
[ 35] 0x000000000ae232e7                        bin\win64\libmwsimulink.dll+11678439 M2MIdentifySLClones+00138423
[ 36] 0x000000000bae8e2a                        bin\win64\libmwsimulink.dll+25071146 test::sl_startup+04405434
[ 37] 0x00007ffc53029d26                   C:\WINDOWS\System32\ucrtbase.dll+00105766 execute_onexit_table+00000342
[ 38] 0x00007ffc53029c4b                   C:\WINDOWS\System32\ucrtbase.dll+00105547 execute_onexit_table+00000123
[ 39] 0x00007ffc53029c04                   C:\WINDOWS\System32\ucrtbase.dll+00105476 execute_onexit_table+00000052
[ 40] 0x000000000b6ba73a                        bin\win64\libmwsimulink.dll+20686650 test::sl_startup+00020938
[ 41] 0x000000000b6ba838                        bin\win64\libmwsimulink.dll+20686904 test::sl_startup+00021192
[ 42] 0x00007ffc554c5021                      C:\WINDOWS\SYSTEM32\ntdll.dll+00151585 RtlActivateActivationContextUnsafeFast+00000289
[ 43] 0x00007ffc5550b102                      C:\WINDOWS\SYSTEM32\ntdll.dll+00438530 LdrShutdownProcess+00000306
[ 44] 0x00007ffc5550afad                      C:\WINDOWS\SYSTEM32\ntdll.dll+00438189 RtlExitUserProcess+00000173
[ 45] 0x00007ffc546bcdda                   C:\WINDOWS\System32\KERNEL32.DLL+00118234 ExitProcess+00000010
[ 46] 0x00007ffbec542541 D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\OpenFAST-Simulink_x64.dll+44770625 FAST_OpFM_Init+44675569
[ 47] 0x00007ffbec5424f7 D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\OpenFAST-Simulink_x64.dll+44770551 FAST_OpFM_Init+44675495
[ 48] 0x00007ffbeaeb7b5a D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\OpenFAST-Simulink_x64.dll+21134170 FAST_OpFM_Init+21039114
[ 49] 0x00007ffbe9b7bc82 D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\OpenFAST-Simulink_x64.dll+00965762 FAST_OpFM_Init+00870706
[ 50] 0x00007ffbe9afaa54 D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\OpenFAST-Simulink_x64.dll+00436820 FAST_OpFM_Init+00341764
[ 51] 0x00007ffbe9b4b42b D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\OpenFAST-Simulink_x64.dll+00767019 FAST_OpFM_Init+00671963
[ 52] 0x00007ffbe9b4c4ef D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\OpenFAST-Simulink_x64.dll+00771311 FAST_OpFM_Init+00676255
[ 53] 0x00007ffbe9aa5aba D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\OpenFAST-Simulink_x64.dll+00088762 FAST_End+00000074
[ 54] 0x00000002b2f5155c D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\FAST_SFunc.mexw64+00005468
[ 55] 0x00000002b2f520bf D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\FAST_SFunc.mexw64+00008383
[ 56] 0x00000002b2f524ac D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\FAST_SFunc.mexw64+00009388
[ 57] 0x00000002b2f541bc D:\ricardo\documents\PROGRAMAS\nrel_open_fast\bin\FAST_SFunc.mexw64+00016828 mexFunction+00001596
[ 58] 0x00000000fc635524                               bin\win64\libmex.dll+00349476 MexRetrieveVersion+00003348
[ 59] 0x00000000fc63571c                               bin\win64\libmex.dll+00349980 MexRetrieveVersion+00003852
[ 60] 0x00000000fc635884                               bin\win64\libmex.dll+00350340 MexRetrieveVersion+00004212
[ 61] 0x00000000fc619059                               bin\win64\libmex.dll+00233561 mexUnlock_800+00025273
[ 62] 0x0000000016f0e007                     bin\win64\pgo\m_dispatcher.dll+00057351 Mfh_file::dispatch_fh_impl+00001111
[ 63] 0x0000000016f0da9e                     bin\win64\pgo\m_dispatcher.dll+00055966 Mfh_file::dispatch_fh+00000062
[ 64] 0x0000000016f78622                     bin\win64\pgo\m_dispatcher.dll+00493090 mdDoMatlabFcnCall+00000122
[ 65] 0x000000025d08278a                           bin\win64\sl_utility.dll+00337802 SimpleUserException::~SimpleUserException+00000282
[ 66] 0x000000000da124f8                     bin\win64\libmwsl_services.dll+02041080 CMatlabCommandNoWatermark::execute+00000056
[ 67] 0x000000025d083129                           bin\win64\sl_utility.dll+00340265 slDoMatlabFcnCall+00000089
[ 68] 0x000000000b510fa2                        bin\win64\libmwsimulink.dll+18943906 slSetStateflowChartStateAccessInterface+00252338
[ 69] 0x000000000b50ecb1                        bin\win64\libmwsimulink.dll+18934961 slSetStateflowChartStateAccessInterface+00243393
[ 70] 0x000000000b511501                        bin\win64\libmwsimulink.dll+18945281 slSetStateflowChartStateAccessInterface+00253713
[ 71] 0x000000000b4f1993                        bin\win64\libmwsimulink.dll+18815379 slSetStateflowChartStateAccessInterface+00123811
[ 72] 0x000000000b4f1dca                        bin\win64\libmwsimulink.dll+18816458 slSetStateflowChartStateAccessInterface+00124890
[ 73] 0x000000000b4f3737                        bin\win64\libmwsimulink.dll+18822967 slSetStateflowChartStateAccessInterface+00131399
[ 74] 0x000000000b4b503c                        bin\win64\libmwsimulink.dll+18567228 StateflowAccessStateInterface::~StateflowAccessStateInterface+00037084
[ 75] 0x000000000b301ecb                        bin\win64\libmwsimulink.dll+16785099 closeMaskEditor+00056683
[ 76] 0x000000000b3021c9                        bin\win64\libmwsimulink.dll+16785865 closeMaskEditor+00057449
[ 77] 0x000000000b30f3c4                        bin\win64\libmwsimulink.dll+16839620 BlockSetLocation+00006420
[ 78] 0x000000000b30b424                        bin\win64\libmwsimulink.dll+16823332 closeMaskEditor+00094916
[ 79] 0x000000000fb5a04b                       bin\win64\sl_lang_blocks.dll+07118923 SubsystemBlock::DrawSubsystemVariants+00006491
[ 80] 0x000000000fb59631                       bin\win64\sl_lang_blocks.dll+07116337 SubsystemBlock::DrawSubsystemVariants+00003905
[ 81] 0x000000000fb93d53                       bin\win64\sl_lang_blocks.dll+07355731 SubsystemCopyContext::srcBdIsHighlighting+00007491
[ 82] 0x000000000fb4e013                       bin\win64\sl_lang_blocks.dll+07069715 SubsystemBlock::CheckPrmsAndCreateDlgPrmCache+00001139
[ 83] 0x000000000b301f00                        bin\win64\libmwsimulink.dll+16785152 closeMaskEditor+00056736
[ 84] 0x000000000b3021c9                        bin\win64\libmwsimulink.dll+16785865 closeMaskEditor+00057449
[ 85] 0x000000000b30f3c4                        bin\win64\libmwsimulink.dll+16839620 BlockSetLocation+00006420
[ 86] 0x000000000b30b424                        bin\win64\libmwsimulink.dll+16823332 closeMaskEditor+00094916
[ 87] 0x00000002622387c2                           bin\win64\sl_compile.dll+05539778 EvalAllBlockParamsAndModelArgs+00003586
[ 88] 0x0000000261f544ef                           bin\win64\sl_compile.dll+02508015 SLCompEvalAllBlockParamsAndModelArgs+00001439
[ 89] 0x000000000afd3e2b                        bin\win64\libmwsimulink.dll+13450795 ssSetBlockIsPurelyCombinatorial+00033739
[ 90] 0x000000000afd4014                        bin\win64\libmwsimulink.dll+13451284 ssSetBlockIsPurelyCombinatorial+00034228
[ 91] 0x000000000ae33fd5                        bin\win64\libmwsimulink.dll+11747285 M2MIdentifySLClones+00207269
[ 92] 0x000000000ae26bf7                        bin\win64\libmwsimulink.dll+11693047 M2MIdentifySLClones+00153031
[ 93] 0x000000000ae33929                        bin\win64\libmwsimulink.dll+11745577 M2MIdentifySLClones+00205561
[ 94] 0x000000000ae2ea7c                        bin\win64\libmwsimulink.dll+11725436 M2MIdentifySLClones+00185420
[ 95] 0x000000000b538177                        bin\win64\libmwsimulink.dll+19104119 slstSetOutputPortRateID+00122343
[ 96] 0x000000000b53d10e                        bin\win64\libmwsimulink.dll+19124494 slstSetOutputPortRateID+00142718
[ 97] 0x000000000b5439c1                        bin\win64\libmwsimulink.dll+19151297 slstSetOutputPortRateID+00169521
[ 98] 0x000000000b5431a7                        bin\win64\libmwsimulink.dll+19149223 slstSetOutputPortRateID+00167447
[ 99] 0x000000000b576d05                        bin\win64\libmwsimulink.dll+19361029 slstSetOutputPortRateID+00379253
[100] 0x000000000ad7960a                        bin\win64\libmwsimulink.dll+10982922 slAccPostBlock+00178826
[101] 0x000000000abc8e73                        bin\win64\libmwsimulink.dll+09211507 QueryMLFcnTable_libmwsimulink+00088563
[102] 0x0000000016f0b724                     bin\win64\pgo\m_dispatcher.dll+00046884 Mdispatcher::getDispatcher+00002228
[103] 0x0000000016f0cbe7                     bin\win64\pgo\m_dispatcher.dll+00052199 Mfh_MATLAB_fn_impl::dispatch_fh+00000343
[104] 0x0000000017de4ead                            bin\win64\pgo\m_lxe.dll+00347821
[105] 0x0000000017f7e9b6                            bin\win64\pgo\m_lxe.dll+02025910 MathWorks::lxe::ShutdownLxeEngine+00004034
[106] 0x0000000017edfd3c                            bin\win64\pgo\m_lxe.dll+01375548 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00493568
[107] 0x0000000017ee091c                            bin\win64\pgo\m_lxe.dll+01378588 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00496608
[108] 0x0000000017ee1c92                            bin\win64\pgo\m_lxe.dll+01383570 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00501590
[109] 0x0000000017ee28f8                            bin\win64\pgo\m_lxe.dll+01386744 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00504764
[110] 0x0000000017ee1ddf                            bin\win64\pgo\m_lxe.dll+01383903 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00501923
[111] 0x0000000017ee1ede                            bin\win64\pgo\m_lxe.dll+01384158 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00502178
[112] 0x0000000017de9a7d                            bin\win64\pgo\m_lxe.dll+00367229
[113] 0x0000000017dfb265                            bin\win64\pgo\m_lxe.dll+00438885
[114] 0x0000000017dfa88c                            bin\win64\pgo\m_lxe.dll+00436364
[115] 0x0000000017df8779                            bin\win64\pgo\m_lxe.dll+00427897
[116] 0x0000000017df90eb                            bin\win64\pgo\m_lxe.dll+00430315
[117] 0x0000000017df8a49                            bin\win64\pgo\m_lxe.dll+00428617
[118] 0x0000000016f0e007                     bin\win64\pgo\m_dispatcher.dll+00057351 Mfh_file::dispatch_fh_impl+00001111
[119] 0x0000000016f0da9e                     bin\win64\pgo\m_dispatcher.dll+00055966 Mfh_file::dispatch_fh+00000062
[120] 0x0000000017de4ead                            bin\win64\pgo\m_lxe.dll+00347821
[121] 0x0000000017f7e9b6                            bin\win64\pgo\m_lxe.dll+02025910 MathWorks::lxe::ShutdownLxeEngine+00004034
[122] 0x0000000017edfd3c                            bin\win64\pgo\m_lxe.dll+01375548 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00493568
[123] 0x0000000017ee091c                            bin\win64\pgo\m_lxe.dll+01378588 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00496608
[124] 0x0000000017ee1c92                            bin\win64\pgo\m_lxe.dll+01383570 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00501590
[125] 0x0000000017ee28f8                            bin\win64\pgo\m_lxe.dll+01386744 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00504764
[126] 0x0000000017ee1ddf                            bin\win64\pgo\m_lxe.dll+01383903 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00501923
[127] 0x0000000017ee1ede                            bin\win64\pgo\m_lxe.dll+01384158 mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,MathWorks::lxe::function_descriptor>::load_object_data+00502178


This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

_Originally posted by @eletroinf in https://github.com/OpenFAST/openfast/issues/548#issuecomment-735021064_

**Comment by bjonkman** [comment]
@eletroinf:

Due to the bug in the tagged OpenFAST 2.4.0 release, I would expect the S-Function built with it to run with the OpenFAST DLL built from OpenFAST 2.3.0, but not OpenFAST 2.4.0.

I would also expect that when you changed the header file:
```
#define CHANNEL_LENGTH 20
```
that this S-Function will work with the DLL built from OpenFAST 2.4.0 (or the current dev branch) but not with the DLL from OpenFAST 2.3.0.

Other combinations of the S-Function and DLL versions from 2.3.0 and 2.4.0 will result in Matlab crashing. 

Did you use the correct DLL after you changed the S-Function?

**Comment by eletroinf** [comment]
@bjonkman 

Thank you for the help

I redid the entire compilation process and I build the S-function with #define CHANNEL_LENGTH 20 in FAST_Library.h file.

I obtained the same result: The Matlab crashes and close when I try to run my simulation.

I reviewed my files to make shure that I was using the correct ones.

**Comment by kumaraeedara** [comment]
I have model working perfectly well with the OpenFast V2.2.0 (through simulink). But I have recently compiled and generated s-function from V2.4.0. When I run my model with the latest, matlab crashes. By any chance, are there changes made to the input files (like Aerodyn etc) requiring more inputs compared to the v2.4.0? I mean can the input files created for V2.2.0 be directly used for V2.4.0 as well or do they need to be modified?

Regards,
Kumara

**Comment by jjonkman** [comment]
Dear @kumaraeedara,

The input files must be changed between OpenFAST v2.2 and v2.4. The input file changes associated with each release of OpenFAST are documented here: https://openfast.readthedocs.io/en/master/source/user/api_change.html.

Best regards,

**Comment by kumaraeedara** [comment]
Dear @jjonkman Thanks. I made the relevant changes as pointed in the document and able to run V2.4.0 without issues  using .exe (that I obtained after compilation). 
But the issue in running using Matlab (simulink) still persists. Matlab simply crashes.
@bjonkman , @eletroinf  Any further update on running V2.4.0 using Matlab ? Thanks.

Regards,
Kumara

**Comment by bjonkman** [comment]
@kumaraeedara, If you incorporated the change from https://github.com/OpenFAST/openfast/pull/550 before building the S-Function for v2.4.0, I wouldn't expect Matlab to crash. 

Is Matlab finding and using the correct version of the S-Function that you built? Do you have compatible S-Function `FAST_SFunc.mexw64` and library `OpenFAST-Simulink_x64.dll` files? (i.e., make sure both were built with the same version of OpenFAST.) Are there old copies of any of those files elsewhere on your Matlab path? Does it work if you use the OpenFAST/dev branch?

**Comment by kumaraeedara** [comment]
Dear @bjonkman  I am using the V2.4.0 Latest release (zip file). Just changing the CHANNEL_LENGTH  from 10 to 20 in FAST_Library.h file as suggested in https://github.com/OpenFAST/openfast/issues/548#issuecomment-700780484  and recreating S-function did work for me. Thank you.

Regards,
Kumara

**Comment by eletroinf** [comment]
Only to give a final feedback.
With v.2.4.0 the proposed solution of to change CHANNEL_LENGTH from 10 to 20 in FAST_Library.h did not worked for me.
Now I compiled the OpenFAST 2.5.0 and it is not crashing - it is working. I am working in the changes of my v.2.30 files to make then updated according with  OpenFAST 2.5.0.

Thanks anyway.
