### ISSUE TITLE
Creating mex SFunction : error C2061: syntax error : identifier '_Bool'

### ISSUE THREAD

**Issue by hbasbas** [OpenFAST/openfast#609]
Good morning, 

I am trying to generate a mex file for Matlab/Simulink with the mat file "create_FAST_Sfunc.m". I have the dll OpenFAST_Simulink in the build folder. 

However, when I run the mat file I had a first error : 

_Creating ../../../build/bin\FAST_SFunc.mexw64

cl : Command line warning D9025 : overriding '/MD' with '/MT' 
FAST_SFunc.c 
../../../modules/openfoam/src\OpenFOAM_Types.h(12) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory_

I understood that this error is due to the C language that does not understand boolean variable, thus stdbool.h is a simple header file that create these variables. So I add this file to simulink/src folder and now I get these errors : 

_Creating ../../../build/bin\FAST_SFunc.mexw64

cl : Command line warning D9025 : overriding '/MD' with '/MT' 
FAST_SFunc.c 
../../../modules/supercontroller/src\SuperController_Types.h(34) : error C2061: syntax error : identifier '_Bool' 
../../../modules/supercontroller/src\SuperController_Types.h(35) : error C2059: syntax error : '}' 
../../../modules/supercontroller/src\SuperController_Types.h(47) : error C2061: syntax error : identifier 'SC_ParameterType_t' 
../../../modules/supercontroller/src\SuperController_Types.h(50) : error C2059: syntax error : '}' 
../../../modules/openfast-library/src\FAST_Library.h(8) : error C2054: expected '(' to follow 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(8) : error C2085: 'FAST_AllocateTurbines' : not in formal parameter list 
../../../modules/openfast-library/src\FAST_Library.h(9) : error C2061: syntax error : identifier 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(11) : error C2054: expected '(' to follow 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(12) : error C2085: 'FAST_OpFM_Restart' : not in formal parameter list 
../../../modules/openfast-library/src\FAST_Library.h(13) : error C2061: syntax error : identifier 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(16) : error C2054: expected '(' to follow 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(16) : error C2085: 'FAST_OpFM_Solution0' : not in formal parameter list 
../../../modules/openfast-library/src\FAST_Library.h(17) : error C2061: syntax error : identifier 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(19) : error C2054: expected '(' to follow 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(19) : error C2085: 'FAST_Restart' : not in formal parameter list 
../../../modules/openfast-library/src\FAST_Library.h(20) : error C2061: syntax error : identifier 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(21) : error C2054: expected '(' to follow 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(21) : error C2085: 'FAST_Start' : not in formal parameter list 
../../../modules/openfast-library/src\FAST_Library.h(22) : error C2061: syntax error : identifier 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(23) : error C2054: expected '(' to follow 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(23) : error C2143: syntax error : missing ')' before '*' 
../../../modules/openfast-library/src\FAST_Library.h(23) : error C2081: '_Bool' : name in formal parameter list illegal 
../../../modules/openfast-library/src\FAST_Library.h(23) : error C2085: 'FAST_End' : not in formal parameter list 
../../../modules/openfast-library/src\FAST_Library.h(23) : error C2143: syntax error : missing ';' before '*' 
../../../modules/openfast-library/src\FAST_Library.h(23) : error C2059: syntax error : ')' 
../../../modules/openfast-library/src\FAST_Library.h(24) : error C2054: expected '(' to follow 'EXTERNAL_ROUTINE' 
../../../modules/openfast-library/src\FAST_Library.h(24) : error C2085: 'FAST_CreateCheckpoint' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(24) : warning C4079: unexpected token 'string' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(24) : warning C4081: expected 'newline'; found ')' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(88) : error C2085: '_HUGE' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(106) : error C2082: redefinition of formal parameter 'acos' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(107) : error C2082: redefinition of formal parameter 'asin' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(108) : error C2082: redefinition of formal parameter 'atan' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(109) : error C2082: redefinition of formal parameter 'atan2' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(111) : error C2085: '_copysign' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(112) : error C2085: '_chgsign' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(115) : error C2082: redefinition of formal parameter 'cos' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(116) : error C2082: redefinition of formal parameter 'cosh' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(117) : error C2082: redefinition of formal parameter 'exp' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(118) : error C2082: redefinition of formal parameter 'fabs' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(119) : error C2082: redefinition of formal parameter 'fmod' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(120) : error C2082: redefinition of formal parameter 'log' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(121) : error C2082: redefinition of formal parameter 'log10' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(122) : error C2082: redefinition of formal parameter 'pow' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(123) : error C2082: redefinition of formal parameter 'sin' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(124) : error C2082: redefinition of formal parameter 'sinh' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(125) : error C2082: redefinition of formal parameter 'tan' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(126) : error C2082: redefinition of formal parameter 'tanh' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(127) : error C2082: redefinition of formal parameter 'sqrt' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(134) : error C2085: '_cabs' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(135) : error C2082: redefinition of formal parameter 'ceil' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(136) : error C2082: redefinition of formal parameter 'floor' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(137) : error C2085: 'frexp' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(138) : error C2085: '_hypot' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(139) : error C2085: '_hypotf' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(140) : error C2085: '_j0' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(141) : error C2085: '_j1' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(142) : error C2085: '_jn' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(143) : error C2085: 'ldexp' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(149) : error C2085: '_matherr' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(152) : error C2085: 'modf' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(154) : error C2085: '_y0' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(155) : error C2085: '_y1' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(156) : error C2085: '_yn' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(162) : error C2085: 'hypot' : not in formal parameter list 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(162) : error C2143: syntax error : missing ';' before '{' 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(168) : warning C4013: '_hypotf' undefined; assuming extern returning int 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(168) : warning C4244: 'return' : conversion from 'int' to 'float', possible loss of data 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(599) : warning C4161: #pragma pack(pop...) : more pops than pushes 
FAST_SFunc.c(34) : warning C4005: 'min' : macro redefinition 
        C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\stdlib.h(855) : see previous definition of 'min' 
FAST_SFunc.c(180) : warning C4013: 'fmin' undefined; assuming extern returning int 
FAST_SFunc.c(199) : warning C4013: 'FAST_AllocateTurbines' undefined; assuming extern returning int 
FAST_SFunc.c(200) : warning C4013: 'FAST_Sizes' undefined; assuming extern returning int 
FAST_SFunc.c(346) : warning C4013: 'FAST_Start' undefined; assuming extern returning int 
FAST_SFunc.c(428) : warning C4013: 'FAST_Update' undefined; assuming extern returning int 
FAST_SFunc.c(450) : error C2065: '_Bool' : undeclared identifier 
FAST_SFunc.c(450) : error C2146: syntax error : missing ';' before identifier 'tr' 
FAST_SFunc.c(450) : error C2065: 'tr' : undeclared identifier 
FAST_SFunc.c(451) : warning C4013: 'FAST_End' undefined; assuming extern returning int 
FAST_SFunc.c(451) : error C2065: 'tr' : undeclared identifier 
 
  C:\PROGRA~1\MATLAB\R2012B\BIN\MEX.PL: Error: Compile of 'FAST_SFunc.c' failed. 
 
Error using mex (line 206)
Unable to complete successfully.

Error in create_FAST_SFunc (line 62)
mex('-largeArrayDims', ..._
 
With the first error, it seems that the bool variables are still not recognized by the compiler, right ? How could I fix it ? 

Is it possible that the problem come from that I compiled the OpenFAST_Simulink dll by specifying an additional dependency "C:\Program Files\Matlab\R2012b\extern\lib\win64\microsoft\libmex.lib" and I am using MatlabR2012b ? (The reason is that I have VS2019 installed on one PC (with all administrator rights) and the real time target (dSpace) is installed on another PC which used Matlab R2012b (without administrator rights ...))

Best regards, 

Hedi

**Comment by bjonkman** [comment]
Is this still an issue?

1. yes, it seems that your C/C++ compiler does not recognize the `stdbool.h` file. It sounds like your compiler needs to know to search the src folder to find it (not all compilers look in the source folder to find include/header files). You'll need to add another line with `-I <path-to-header>` to the mex command, or put that header in a different directory.
2. I'm not exactly sure what you are asking, but it sounds like you've built the DLL with VS2019 and are now trying to build the mex function with VS2010. I think this should still be okay.

**Comment by hbasbas** [comment]
Thank you, I fixed the problem by using FASTv8
