### ISSUE TITLE
AeroDyn development and testing process

### ISSUE THREAD

**Issue by Amarelio** [OpenFAST/openfast#611]
Good evening,

I'm a new PhD student and I would like to develop a functionality in AeroDyn which allows harmonic motions to be prescribed to the several degrees of freedom but it is my first interaction with the source code and with its development and I still don't understand exactly how to do it. I have already done all the steps described in section 5.3.1.4 OpenFAST Specific Git Flow (https://raf-openfast.readthedocs.io/en/docs-all/source/dev/github_workflow.html) up to step 5 where I develop the code. As far as my understanding goes, the development process goes like this: 
1 - Make changes to the source code. Make changes to the registry files in order to edit the relevant data types;
2 - Compile the complete OpenFAST in debug mode.
3 - Run OpenFAST with the debugger.
4 - Go back to the first step and iterate.

I have some doubts however in this process:
- Since I only want to develop AeroDyn, is it necessary to compile all of OpenFAST or is it possible to compile AeroDyn only? And if so, how do I do it?
- Is it necessary to recompile each time I make a change in the source code in order to test it? Or is it possible to edit the code at the same time that I'm debugging it? I assume the answer to this question is no because I would say the executable needs to be generated again to be updated with the changes.
- What exactly does the "aerodyn_driver" binary file do and contain? Is it a "translation" to binary of the  "AeroDyn_Driver.f90" file? Does it contain any other source code like the one in "AeroDyn.f90"?

I'm really excited to move forward with this but I still lack some of the basics. I would be really gratefull if you could help me get started.

P.S: Should I change this to a "Discussion" in my OpenFAST fork?

Best regards,
Ricardo Amaral

**Comment by jjonkman** [comment]
Dear @Amarelio,

I agree with your steps except that the debug mode is only necessary if you need to step through an algorithm with the debugger.  Compiling in release mode generates more optimized source code that will execute faster, if you don't need to use the debugger.

The AeroDyn driver currently assumes that the wind turbine structure is rigid, with user-prescribed rotor speed, nacelle-yaw angle, blade-pitch angle, etc.  With some work, it would be possible to modify this driver to also support user-prescribed motion of the entire wind turbine.

Here are my answers to your questions:

- You don't need to compile all of OpenFAST if you only wish to compile the standalone AeroDyn driver.  How will depend on how you currently compile OpenFAST.  You can compile the standalone AeroDyn driver using either CMake (best for Linux/Mac) or Visual Studio (best for Windows).  Do you already compile OpenFAST with one of these methods?

- Yes, it is necessary to recompile each time you change the source code.  You can only run/test compiled source code.

- As with any module in OpenFAST, you can either run AeroDyn coupled to OpenFAST or run AeroDyn in standalone mode through the AeroDyn driver.  In standalone mode, the module-level inputs normally set by OpenFAST are defined explicitly in the standalone driver code.  Compiling the AeroDyn driver program will compile both the driver file (_AeroDyn_Driver.f90_) and the AeroDyn module source code (_AeroDyn.f90_, etc.).

Best regards,

**Comment by Amarelio** [comment]
Dear @jjonkman ,

Thank you for your fast reply, all your answers were clear to me. Answering your question and asking further:

 @jjonkman - "Do you already compile OpenFAST with one these methods?"
R: Yes, I do. I forgot to specify but I have a Linux machine (Ubuntu) so I'm using CMake. My first attempt to compile the code was done in the directory:

ramaral:~/OpenFAST/modules/aerodyn$ ls
CMakeLists.txt  README.md  src  tests    

By running the command "cmake CMakeLists.txt" but I received the following warning and errors:
##### Warning:
 CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as
    project(ProjectName)
  near the top of the file, but after cmake_minimum_required().
  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.
##### Errors:
-- Configuring done
CMake Error: Cannot determine link language for target "afinfolib".
CMake Error: CMake can not determine linker language for target: afinfolib
CMake Error: Cannot determine link language for target "uaaerolib".
CMake Error: CMake can not determine linker language for target: uaaerolib
CMake Error: Cannot determine link language for target "fvwlib".
CMake Error: CMake can not determine linker language for target: fvwlib
CMake Error: Cannot determine link language for target "aeroacoustics".
CMake Error: CMake can not determine linker language for target: aeroacoustics
CMake Error: Cannot determine link language for target "aerodynlib".
CMake Error: CMake can not determine linker language for target: aerodynlib
CMake Error: Cannot determine link language for target "unsteadyaero_driver".
CMake Error: CMake can not determine linker language for target: unsteadyaero_driver
CMake Error: Cannot determine link language for target "aerodyn_driver".
CMake Error: CMake can not determine linker language for target: aerodyn_driver
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

I noticed that these libraries and drivers are present in the directory:

ramaral@TUD259103:~/OpenFAST/build/modules/aerodyn$ ls
CMakeFiles         TestCase             libaeroacoustics.a  libfvwlib.a
ExampleInputFiles  aerodyn_driver       libaerodynlib.a     libuaaerolib.a
Makefile           cmake_install.cmake  libafinfolib.a      unsteadyaero_driver

So should I copy the missing libraries and drivers from "~/OpenFAST/build/modules/aerodyn" to "~/OpenFAST/modules/aerodyn", ignore the warning and run the command "cmake CMakeLists.txt"?

Best regards,
Ricardo Amaral

**Comment by andrew-platt** [comment]
To build the driver, we recommend you create a build directory in the root of your OpenFAST clone (~/OpenFAST/build in your case).  From that directory, run the commands:

```
cmake ..
make aerodyn_driver
```

That will build your aerodyn_driver in `~/OpenFAST/build/modules/aerodyn/aerodyn_driver`.

For further details, see the instructions here: [https://openfast.readthedocs.io/en/dev/source/install/index.html#cmake-with-make-for-linux-macos](https://openfast.readthedocs.io/en/dev/source/install/index.html#cmake-with-make-for-linux-macos)

**Comment by Amarelio** [comment]
Thank you very much @andrew-platt , that was super clear. I'm able to proceed now.

Best regards
