### ISSUE TITLE
Simulation time step

### ISSUE THREAD

**Issue by SudharsanKalidoss** [OpenFAST/openfast#613]
Hi everyone,

   I tried to increase the simulation DT in .fst file. I always ended up with numerical instability errors. I would like to know on what basis the simulation time step is chosen. If I need to increase the time step, what are the parameters I need to consider? 

Thanks

Sudharsan

**Comment by jjonkman** [comment]
Dear Sudharsan,

The required time step is intrinsically related to the rotor speed and structural natural frequencies that you are modeling.  This topic has been discussed many times on our forum, e.g.: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=351&p=1025.

Best regards,
