### ISSUE TITLE
Bug report in inflow wind openfast develop

### ISSUE THREAD

**Issue by ptrbortolotti** [OpenFAST/openfast#618]
**Bug description**
Inflow wind on the develop branch suffers when .wnd files are loaded with a linear vertical shear (DLC 1.5)

**To Reproduce**
<Update the following list with your specific information.>
1. Compile develop with fortran
2. Run inflow wind WindType=2
3. Check outputs RtVavgxh
4. See the error

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots, if applicable**
![image](https://user-images.githubusercontent.com/20641647/102677895-fbf98900-4161-11eb-8384-bf68bfa9c842.png)

**OpenFAST Version**
<Please provide as much detail as possible including git commit. The best information is a screenshot of the OpenFAST system description that prints when running OpenFAST:>

```
**************************************************************************************************
 OpenFAST

 Copyright (C) 2020 National Renewable Energy Laboratory
 Copyright (C) 2020 Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST--128-NOTFOUND
 Compile Info:
  - Compiler: GCC version 9.2.0
  - Architecture: 64 bit
  - Precision: single
  - Date: Dec 15 2020
  - Time: 11:40:53
 Execution Info:
  - Date: 12/18/2020
  - Time: 18:45:01-0700
[outputs.zip](https://github.com/OpenFAST/openfast/files/5718760/outputs.zip)
fast d

**Additional context**
<Add any other context about the problem here.>

**Comment by ptrbortolotti** [comment]
[outputs.zip](https://github.com/OpenFAST/openfast/files/5718770/outputs.zip)

**Comment by bjonkman** [comment]
@ptrbortolotti:  When I tried to download the zip file you attached, my computer tells me it contains a virus or malware, so I can't actually check the model. (Perhaps a controller is included inside the zip file?)

I see only the AeroDyn output channel here, so I am wondering what checks have you done to say that this is caused by the linear vertical shear in InflowWind's uniform wind file and not something in AeroDyn or ServoDyn (or elsewhere).

**Comment by ptrbortolotti** [comment]
Thanks Bonnie for the support here. I'm running some more tests and I will upload new files. I had turned off servodyn, so that's out of the game, but now I do see changes in the outputs varying the aerodyn15 flags. I'll get back to you as soon as I have isolated the problem better. Thank you!

**Comment by ptrbortolotti** [comment]
[outputs.zip](https://github.com/OpenFAST/openfast/files/5725403/outputs.zip)

**Comment by ptrbortolotti** [comment]
Hello OpenFAST team, I've zipped the model again removing anything that is not a .dat file and a .wnd file.
I hope you can now download the folder
I ran some tests myself and everything works fine when WindType=1. When I switch to WindType=2, the blade deflections grow unrealistically and something is up. The problem could clearly be in the number of the .wnd file, but things look fine to me there
I'm happy to run any additional test you might suggest
Thank you!
Pietro

**Comment by andrew-platt** [comment]
I don't see a uniform wind file in that zip.  There is a binary turbsim file (BAR01_3ETM_U4.000000_Seed1.0.bts), but nothing matching the format for the Uniform Wind file (WindType 2).

**Comment by ptrbortolotti** [comment]
that is surprising.. the folder should have two subfolders: "bar0" with the openfast model and "wind" with a .wnd file, which I attach here after changing the extension to .txt
[bar0_EWS_V_P_U15.0.txt](https://github.com/OpenFAST/openfast/files/5726209/bar0_EWS_V_P_U15.0.txt)

**Comment by andrew-platt** [comment]
Thanks for the file.  I'm not sure why it isn't in the zip (3 posts above).

Could you try adding another column of zeros at right side of the table?  I wonder if we have a parsing error when only 8 columns are present instead of the expected 9 (the code in theory should handle this ok, but might have a bug).

**Comment by ptrbortolotti** [comment]
I don't think that has changed anything.

These are the plots when I use WindType=1 at 15 m/s and PLexp=0.2

![WindType1_2](https://user-images.githubusercontent.com/20641647/102817165-7efe2780-438c-11eb-94f0-fb84ac6e74e8.png)
![WindType1](https://user-images.githubusercontent.com/20641647/102817167-802f5480-438c-11eb-8e6b-d8023f18a86d.png)

And this what happens when I set WindType=2 and I load the file above
![WindType2_2](https://user-images.githubusercontent.com/20641647/102817189-8fae9d80-438c-11eb-8941-8cb0101c74ab.png)
![WindType2](https://user-images.githubusercontent.com/20641647/102817194-90dfca80-438c-11eb-84c1-92dafe71b9b8.png)

**Comment by andrew-platt** [comment]
I checked the `bar0_EWS_V_P_U15.0.txt` file with the IfW driver code and a grid of outputs.  At 16.5 seconds, I see the following:

```
    # X               Y                 Z               Vx             Vy            Vz
     0.0000000      -20.0000000      120.0000000     -285.673        0.000        0.000
     0.0000000        0.0000000      120.0000000     -285.673        0.000        0.000
     0.0000000       20.0000000      120.0000000     -285.673        0.000        0.000
     0.0000000      -20.0000000      140.0000000       15.000       -0.000        0.000
     0.0000000        0.0000000      140.0000000       15.000       -0.000        0.000
     0.0000000       20.0000000      140.0000000       15.000       -0.000        0.000
     0.0000000      -20.0000000      160.0000000      315.623       -0.000        0.000
     0.0000000        0.0000000      160.0000000      315.623       -0.000        0.000
     0.0000000       20.0000000      160.0000000      315.623       -0.000        0.000
```


Are the values for linear vertical shear sensible?  It is set to 1.000724 with an additional PL exponent of 0.2.

**Comment by bjonkman** [comment]
Was this a problem in the master branch (or whatever branch you were using)? i.e., is this a new issue?

Or could this be related to something in BEM that is triggered because of the shear you are adding? 

I haven't looked in great detail, but one thing that sticks out to me is the `RefLength` in used for the uniform wind files. It's set to 1 meter in the file you sent, while I would expect this to be closer to the rotor diameter. In your case, when the vertical linear shear is set to 1, you are probably adding hundreds of m/s to the velocity at the top of the rotor. There is probably something weird happening in the aero with those kinds of velocities.

**Comment by ptrbortolotti** [comment]
Thank you Bonnie, it looks like the reference length is not setup correctly in WEIS! I'll keep this issue open for a little longer, but most likely the error is on our side then!

**Comment by ptrbortolotti** [comment]
hello openfast team, thank you for the great support. Bonnie was right, RefLength wasn't initially correctly in WEIS and it was left at a dummy value of 1 meter. This PR is fixing things on our side (together with some other changes)

https://github.com/WISDEM/WEIS/pull/48#partial-pull-merging

thanks again, I'm happy to close this issue now
