### ISSUE TITLE
Getting Documentation in PDF Format

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#62]
The OpenFAST documentation on read-the-docs (http://openfast.readthedocs.io/en/latest/) refers to the ability to get the documentation in PDF format via a “box” in the lower left corner of the browser screen.  However, this functionality is not yet supported.

**Comment by michaelasprague** [comment]
@jjonkman - thanks for the heads up.  I just enabled the PDF builds on RTD (I thought it was already enabled, so I'm a bit confused that they weren't enabled).  However, the section numbers are not appearing as expected in the PDF file, so I am going to leave this issue open until we resolve that.

**Comment by michaelasprague** [comment]
@jjonkman with @rafaelmudafort 's recent commit, we've cleaned up the PDF files.  There are still some more edits that are needed, but the PDF is looking much better.

See: https://github.com/OpenFAST/openfast/commit/e788b9b18bd5ed96ea59d4bc0812d461bc430cfe

and  https://media.readthedocs.org/pdf/openfast/dev/openfast.pdf

**Comment by jjonkman** [comment]
Looks great, thanks!
