### ISSUE TITLE
Using OpenFAST with OpenAI Gym for Reinforcement Learning?

### ISSUE THREAD

**Issue by halvorot** [OpenFAST/openfast#629]
Is there any way to use the OpenFAST simulator to simulate steps in Reinforcement Learning training. I am looking for a solution to integrate with OpenAI Gym and python .

**Comment by rafmudaf** [comment]
Hi @halvorot I'm currently working on an interface with Python drivers for a particular application, but it could be generalized with some additional effort.

See this branch: https://github.com/rafmudaf/openfast/tree/feature/python_integration

**Comment by halvorot** [comment]
> Hi @halvorot I'm currently working on an interface with Python drivers for a particular application, but it could be generalized with some additional effort.
> 
> See this branch: https://github.com/rafmudaf/openfast/tree/feature/python_integration

Thank you @rafmudaf, I will explore this in combination with my work.
