### ISSUE TITLE
Building Documentation Locally on Windows

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#63]
The OpenFAST documentation has instructions to help developers build the documentation locally to aid in producing documentation.  However, the approach to building the documentation locally on Windows is unclear.  Guidance should provided for Windows-based developers (such as myself) on how to build documentation locally on Windows.

**Comment by rafmudaf** [comment]
This issue is fixed by pull request #122. The updated docs page regarding this issue is now live at https://openfast.readthedocs.io/en/dev/source/dev/build_doc.html#pure-python
