### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Bibhanshud** [OpenFAST/openfast#638]
Hello All,

Thank you for troubleshooting previous issues related to the Build error. I finally managed to reach a point with fewer error messages.  I would like your help with the remaining errors please find the details below.

Softwares: Windows 10 , intel Fortran compiler :w_fortran-compiler_p_2021.1.2.62_offline,. and VisualStudio community version vs_community__1142001592.1610718317. I am facing some errors.

Here are the error details.
 
4>Linking...
4>ipo: error #11018: Cannot open C:\Users\dash9\Windturbinesim\openfast\build\bin\FASTlib_x64.lib
4>ipo: error #11018: Cannot open mkl_intel_lp64
4>ipo: error #11018: Cannot open mkl_sequential
4>ipo: error #11018: Cannot open mkl_core
4>ipo: warning #11021: unresolved NWTC_IO_mp_R2LSTR8
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved NWTC_IO_mp_WRSCR
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_SOLUTION_T
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_CREATECHECKPOINT_TARY
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved NWTC_IO_mp_INT2LSTR
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_LINEARIZE_T
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_SOLUTION0_T
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_INITIALIZEALL_T
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved NWTC_IO_mp_NORMSTOP
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved FAST_SUBS_mp_EXITTHISPROGRAM_T
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_RESTOREFORVTKMODESHAPE_TARY
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_RESTOREFROMCHECKPOINT_TARY
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved NWTC_IO_mp_CHECKARGS
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved NWTC_LIBRARY_mp_NWTC_INIT
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved NWTC_IO_mp_PROGNAME
4>        Referenced in ipo_83247obj3.obj
4>ipo: warning #11021: unresolved NWTC_BASE_mp_ABORTERRLEV
4>        Referenced in ipo_83247obj3.obj
4>ipo: error #11023: Not all components required for linking are present on command line
4>LINK : fatal error LNK1181: cannot open input file 'C:\Users\dash9\Windturbinesim\openfast\build\bin\FASTlib_x64.lib'
4>
4>Build log written to  "file://C:\Users\dash9\Windturbinesim\openfast\vs-build\FAST\x64\Release\BuildLog.htm"
4>FAST - 6 error(s), 16 warning(s)
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(40): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(72): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(89): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(167): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(241): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(350): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(363): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(405): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(459): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(541): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(570): warning #7025: This directive is not standard F2003.
5>C:\Users\dash9\Windturbinesim\openfast\modules\openfast-library\src\FAST_Library.f90(675): warning #7025: This directive is not standard F2003.
5>Linking...
5>LINK : fatal error LNK1181: cannot open input file 'C:\Program Files\MATLAB\R2018a\extern\lib\win64\microsoft\libmex.lib'

Awaiting your reply
Thank you

Regards
Bibhanshu

**Comment by bjonkman** [comment]
I think there are a couple of issues here:
1. The Simulink build has to have a link to your Matlab installation path. It is set to `'C:\Program Files\MATLAB\R2018a\extern\lib\win64\microsoft\libmex.lib'`, so if you don't have Matlab R2018a, it will fail. You should change the `R2018a` with the version of Matlab you have installed and then build again. Right-click on the `OpenFAST-Simulink` project in the solution Explorer window:
![image](https://user-images.githubusercontent.com/6108781/104948275-472dd400-597a-11eb-8858-db725114c92b.png)
 
then choose `Properties`, `Configuration Properties -> Linker ->Input` and `Additional Dependencies`:
![image](https://user-images.githubusercontent.com/6108781/104948127-0a61dd00-597a-11eb-9c64-cafe4aae6de5.png)
 
and update the path to your version of Matlab. 

2. You are getting errors about it not finding the Math Kernel Library (MKL) as well as FASTlib_x64.lib. How are you building this? (Are you in the `Release_Matlab | x64` configuration? Did you build the **whole** solution or just an individual project?) Did you make any changes to the Visual Studio project? I think I would need to see your entire build log to have a better idea of what the issue actually is.

**Comment by Bibhanshud** [comment]
@bjonkman  Thank you for replying,
 I am in release mode, I updated the path file of my Matlab version just now.
please find the build log and the related errors below.

Build started...
C:\Users\dash9\Windturbinesim\openfast\modules\nwtc-library\src\SysIVF.f90 : warning: Module 'x64\Release\syssubs.mod' is created by both 'C:\Users\dash9\Windturbinesim\openfast\modules\nwtc-library\src\SysIVF.f90' and 'C:\Users\dash9\Windturbinesim\openfast\modules\nwtc-library\src\SysMatlabWindows.f90'.
1>------ Build started: Project: FASTlib, Configuration: Release x64 ------
1>Performing Pre-Build Event...
1>Creating library...
1>LINK : fatal error LNK1181: cannot open input file '..\..\build\bin\\MAP_x64.lib'
1>
1>Build log written to  "file://C:\Users\dash9\Windturbinesim\openfast\vs-build\FASTlib\x64\Release\BuildLog.htm"
1>FASTlib - 1 error(s), 0 warning(s)
2>------ Build started: Project: FAST, Configuration: Release x64 ------
3>------ Build started: Project: OpenFAST-Simulink, Configuration: Release_Matlab x64 ------
2>Performing Pre-Build Event...
3>Linking...
3>LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj'
3>
3>Build log written to  "file://C:\Users\dash9\Windturbinesim\openfast\vs-build\OpenFAST-Simulink\x64\Release_Matlab\BuildLog.htm"
3>OpenFAST-Simulink - 1 error(s), 0 warning(s)
2>Linking...
2>ipo: error #11018: Cannot open C:\Users\dash9\Windturbinesim\openfast\build\bin\FASTlib_x64.lib
2>ipo: warning #11021: unresolved NWTC_IO_mp_R2LSTR8
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved NWTC_IO_mp_WRSCR
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_SOLUTION_T
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_CREATECHECKPOINT_TARY
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved NWTC_IO_mp_INT2LSTR
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_LINEARIZE_T
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_SOLUTION0_T
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_INITIALIZEALL_T
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved NWTC_IO_mp_NORMSTOP
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved FAST_SUBS_mp_EXITTHISPROGRAM_T
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_RESTOREFORVTKMODESHAPE_TARY
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved FAST_SUBS_mp_FAST_RESTOREFROMCHECKPOINT_TARY
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved NWTC_IO_mp_CHECKARGS
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved NWTC_LIBRARY_mp_NWTC_INIT
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved NWTC_IO_mp_PROGNAME
2>        Referenced in ipo_47967obj3.obj
2>ipo: warning #11021: unresolved NWTC_BASE_mp_ABORTERRLEV
2>        Referenced in ipo_47967obj3.obj
2>ipo: error #11023: Not all components required for linking are present on command line
2>LINK : fatal error LNK1181: cannot open input file 'C:\Users\dash9\Windturbinesim\openfast\build\bin\FASTlib_x64.lib'
2>
2>Build log written to  "file://C:\Users\dash9\Windturbinesim\openfast\vs-build\FAST\x64\Release\BuildLog.htm"
2>FAST - 3 error(s), 16 warning(s)
========== Build: 0 succeeded, 3 failed, 2 up-to-date, 0 skipped ==========
Error and warnings--

Severity	Code	Description	Project	File	Line	Suppression State
Warning		warning #11021: unresolved NWTC_IO_mp_INT2LSTR		ipo		
Warning		warning #11021: unresolved NWTC_LIBRARY_mp_NWTC_INIT		ipo		
Warning		warning #11021: unresolved NWTC_IO_mp_WRSCR		ipo		
Warning		warning #11021: unresolved NWTC_IO_mp_R2LSTR8		ipo		
Warning		warning #11021: unresolved NWTC_IO_mp_PROGNAME		ipo		
Warning		warning #11021: unresolved NWTC_IO_mp_NORMSTOP		ipo		
Warning		warning #11021: unresolved NWTC_IO_mp_CHECKARGS		ipo		
Warning		warning #11021: unresolved NWTC_BASE_mp_ABORTERRLEV		ipo		
Warning		warning #11021: unresolved FAST_SUBS_mp_FAST_SOLUTION_T		ipo		
Warning		warning #11021: unresolved FAST_SUBS_mp_FAST_SOLUTION0_T		ipo		
Warning		warning #11021: unresolved FAST_SUBS_mp_FAST_RESTOREFROMCHECKPOINT_TARY		ipo		
Warning		warning #11021: unresolved FAST_SUBS_mp_FAST_RESTOREFORVTKMODESHAPE_TARY		ipo		
Warning		warning #11021: unresolved FAST_SUBS_mp_FAST_LINEARIZE_T		ipo		
Warning		warning #11021: unresolved FAST_SUBS_mp_FAST_INITIALIZEALL_T		ipo		
Warning		warning #11021: unresolved FAST_SUBS_mp_FAST_CREATECHECKPOINT_TARY		ipo		
Warning		warning #11021: unresolved FAST_SUBS_mp_EXITTHISPROGRAM_T		ipo		
Error		fatal error LNK1181: cannot open input file 'C:\Users\dash9\Windturbinesim\openfast\build\bin\FASTlib_x64.lib'		LINK		
Error		fatal error LNK1181: cannot open input file 'C:\Program.obj'		LINK		
Error		fatal error LNK1181: cannot open input file '..\..\build\bin\\MAP_x64.lib'		LINK		
Error		error #11023: Not all components required for linking are present on command line		ipo		
Error		error #11018: Cannot open C:\Users\dash9\Windturbinesim\openfast\build\bin\FASTlib_x64.lib		ipo

**Comment by bjonkman** [comment]
Are you attempting to build a DLL to use for Simulink or are you trying to build an executable for Matlab? Based on the error you had about linking with the Matlab mex file, I assumed you were trying to make a DLL, but it looks like your build has something mixed up with which projects are being built in `Release` mode.

If you build the solution in `Release_Matlab` mode, it should build the `OpenFAST-Simulink` project + the `FASTlib` + `MAP_dll` projects. However, if you build the solution in `Release` mode, it should build the `FAST` + `FASTlib` + `MAP_dll` projects, and should **not** be attempting to build `OpenFAST-Simulink` at all. Have you changed something in your Visual Studio build files?

If you are attempting to make a DLL for Simulink, make sure you have put quotes around the path name to the Matlab library that you changed in this last step. You now have an error because of the space in that path name.

Also, it looks like the `FASTlib` project is failing because it didn't build the `MAP_dll` project. I'm guessing that you don't have the platform toolset that is specified in the project file (Visual Studio 2015 v140). You can change this in the project properties `Configuration Properties->General->Platform Toolset` box. Just pick a toolset that is listed in that box (it lists which versions you have installed). I think you can also update this when you right-click on the project and select `Retarget projects`.

**Comment by Bibhanshud** [comment]
@bjonkman , I understand now, Thank you very much.
