### ISSUE TITLE
Need a Release Notes Section in the OpenFAST Documentation

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#64]
The OpenFAST documentation has a great section describing the conversion from FAST v8.16 to OpenFAST v0.1 (http://openfast.readthedocs.io/en/latest/source/user/fast_to_openfast.html).  However, the changes between OpenFAST v0.1 and v1.0 are only briefly summarized at a high level in the release comments in the OpenFAST v1.0.0 tag (https://github.com/OpenFAST/openfast/releases).  A release notes section should be added to the OpenFAST documentation summarizing the key details of what is new in each release to aid the general user.  What's important to include in the release notes is a summary of the new features and changes to existing features that will effect the solution (e.g. bug fixes), including changes to the input files that the general user should understand when upgrading.  While anyone can review the commit logs to find all of the details of changes, there is generally far too much detail in the commit logs for the general user to comprehend.  The release notes should be the user-oriented summary of these commit logs.

I'm preparing to change the nwtc.nrel.gov website to link to OpenFAST and to publicly announce the release of OpenFAST, but a release notes section in the OpenFAST documentatoin for the upgrade from OpenFAST v0.1 to OpenFAST v1.0 should be added first.  This release notes section can then be updated as additional OpenFAST tags are added in the future.

**Comment by michaelasprague** [comment]
@jjonkman , thanks for the comment.  However, at this time we are only planning to describe tagged releases at a high level on github (as you described).  The git commit logs are available to those who want a more detailed view.  However, if someone in the community would like to write up a document in the OpenFAST documentation framework describing releases in more detail (and submit a pull request), we would welcome such a contribution.

**Comment by jjonkman** [comment]
I talked to @rafaelmudafort and @ghaymanNREL and we all agree of the need for a release notes section.   I'd be happy to draft this up for the OpenFAST v1.0.0 tag, but I can't check it properly due to issue #63.  In the meantime, I could send the text to @rafaelmudafort for him to commit.
