### ISSUE TITLE
Additional OpenFAST Control Inputs

### ISSUE THREAD

**Issue by DPMarti** [OpenFAST/openfast#646]
I am interested in utilizing the additional control inputs of OpenFAST including the active tendon actuation in MoorDyn and flap control for AeroDyn.  Is there any documentation as to how to feed these control inputs into an OpenFAST executable and/or an SFunction?

**Comment by andrew-platt** [comment]
This functionality is not yet implemented, but will be shortly.  I'll follow up here when the beta version is ready for testing.

**Comment by DPMarti** [comment]
Then the tag notes for v2.3.0 and v2.5.0 are incorrect?

**Comment by andrew-platt** [comment]
The tag notes are correct.  In v2.5.0, MoorDyn was modified to allow control inputs.  However, that functionality is not yet implemented in ServoDyn, and the signal passing has not been added to the glue code.  I expect we will have this step completed in the next week.

**Comment by DPMarti** [comment]
I am interested in utilizing the additional control inputs of OpenFAST including the active tendon actuation in MoorDyn and flap control for AeroDyn. Is there any documentation as to how to feed these control inputs into an OpenFAST executable and/or an SFunction?

**Comment by andrew-platt** [comment]
That functionality is not yet implemented in ServoDyn, and the signal passing has not been added to the glue code.  This is currently under development.

**Comment by DPMarti** [comment]
Has it been integrated into the TCF-Mods2 branch?

**Comment by andrew-platt** [comment]
No.  The TCF-Mods2 branch has been merged into the dev branch.  The controls will be implimented in another pull request from another branch (name to be determined).

**Comment by DPMarti** [comment]
I was under the impression that these updates were being merged last week.  Any time frame on the additional control input updates?

**Comment by andrew-platt** [comment]
The goal was to get them in last week, but we had some delays.  Optimistically I expect early next week I will have a branch to share that contains the ServoDyn updates.

**Comment by DPMarti** [comment]
Hi Andy, just checking in to see if any progress has been made on this front?  Is it possible for you to point me to the files where these additional control inputs would be passed between servodyn.f90 and the glue code?

**Comment by andrew-platt** [comment]
Hi @DPMarti.  The branch I'm currently working on is here: https://github.com/andrew-platt/openfast/tree/f/StrucCtrl_controls.  There are a few minor details I'm wrapping up today/tomorrow:

- passing cable control array out to each module at each timestep
- servodyn input file update (one more line)
- summary file information about what each entry in the extended avrSWAP array is used for (including indicating which module requested which active cable control).
- simulink array matching

The control channels for the active cable tensioning will live in the avrSWAP array at avrSWAP(2601:2800) -- We have greatly increased this swap array for some additional channel groups such as this the cable actuators, lidar channels (not active yet), and tuned mass damper controls (not active yet).

I'll post another update here tomorrow with details on which files to specifically look at for interfacing to Simulink or a DLL controller.

**Comment by andrew-platt** [comment]
A brief update.

In theory the cable controls are now passed correctly from the DLL to subdyn and moordyn when requested, the summary file updates are complete, and the servodyn input files are complete.

We will post a PR shortly with implementation details for the development of a suitable controller.

**Comment by andrew-platt** [comment]
See #664 for status.
