### ISSUE TITLE
Automatic DLC input file generation

### ISSUE THREAD

**Issue by Amarelio** [OpenFAST/openfast#658]
Greetings,

Is there any tool that allows for the automatic generation of the OpenFAST input files for any standard DLC?

Best regards,
Ricardo Amaral

**Comment by jjonkman** [comment]
Dear @Amarelio,

As discussed many times on our forum (https://wind.nrel.gov/forum/wind/), NREL previously supported scripts such as RunIEC and RunNTM to run many of the standard design load cases (DLCs) from the IEC-based design standards in FAST, but these old scripts are no longer supported.

Many users of FAST / OpenFAST who need to run many simulations have written there own scripts for their own purposes. For example, the scripts in the MATLAB Toolbox (https://github.com/OpenFAST/matlab-toolbox) or Python toolbox (https://github.com/OpenFAST/python-toolbox) can be used to read and write FAST input files, so--using these scripts--it would not be difficult to write your own MATLAB- or Python-based scripts to generate OpenFAST input files for a large set of cases based on a master set of OpenFAST input files.  This topic was discussed a bit here: https://github.com/OpenFAST/openfast/issues/573.

The Systems Engineering team at NREL also developed the AeroelasticSE module of WISDEM to automate the running of many of the IEC DLCs.  These scripts are in the process of being overhauled and migrated into the new WEIS framework to support integrated loads analysis, design, and optimization of wind turbines--see: https://github.com/WISDEM/WEIS.

Best regards,

**Comment by Amarelio** [comment]
Dear @jjonkman ,

Thank you for the information. I tried to look for it using the key words "automatic dlc generation" on both forums and also looked into WISDEM because there is mentioning of DLC generation but I didn't find what I was looking for, sorry for that.

Best regards
