### ISSUE TITLE
avrSWAP record 15 (ElecPwr) is not being updated after first iteration

### ISSUE THREAD

**Issue by sebastiaanmuld** [OpenFAST/openfast#66]
We are currently developing our own controller to work with FAST and we want to use the avrSWAP(15) (ElecPwr) for some control loop. However, after the first call of the controller, a value for avrSWAP(15) is set, but is not updated in the subsequent calls. I compared the behavior of avrSWAP(14) (RotPwr), and this value is updated correctly in each iteration.

**Comment by jjonkman** [comment]
@sebastiaanmuld -- Is this different from the bug discussed and resolved by https://github.com/OpenFAST/openfast/issues/40?  This bug has been fixed in the tag release of OpenFAST v1.0.0.

**Comment by sebastiaanmuld** [comment]
OK, never mind, I looked through the open bug list and did not find it, and I am using FAST v8.16 myself currently. Did not notice it is already solved. Thanks.
