### ISSUE TITLE
Issue with OpenFAST/Simulink

### ISSUE THREAD

**Issue by JavierMerino97** [OpenFAST/openfast#660]
Hello, I am working (for the first time) with OpenFAST 2.5, and i had a problem when i tried to link my simulation with Simulink (MATLAB 2018b).

 First I made the Sfunction with no problem, even I reached to simulate de example cases included in the repository. The problem has appeared when I tried to use my own Simulink model, trying to simulate the behaviour of the 5MW_OC4Semi_WSt_WavesWN (TEST25 in other versions). I noticed one error caming from Simulink that says: "Error reported by S-function 'FAST_SFunc' in 'ORPHEO_A_open/FAST Nonlinear Wind Turbine/S-Function". I don't know if the error comes from the fst file because it seems that the problem is only with this model.

**Comment by bjonkman** [comment]
Are there any messages printed to the Matlab command window? If not, can you run that fst file with the stand-alone executable (with appropriate settings in ServoDyn)?

**Comment by JavierMerino97** [comment]
I can run the fst file without problem. Surprisely, I don´t know why but today I'm not getting any Sfunct error. Each error I have is coming from some Simulink variables that I can fix now. I don't know if it has been running the fst file again or restarting the PC but it seems to work fine! Thank you for your help!
