### ISSUE TITLE
Test cases version incompatible

### ISSUE THREAD

**Issue by kasia129** [OpenFAST/openfast#661]
I am trying to run the '_5MW_OC4Semi_WSt_WavesWN_' test case from within the _r-test-main\glue-codes\openfast_  folder, without modifying any input files. I tried using both 2.3 and 2.5 OpenFAST executables, both in single and double precision, as well as replacing the control system .dll files with the ones that worked for me last time I run a case with the same rotor but a different platform.

When running the simulation with the 2.5 version of OpenFAST, I am getting this output:

    status =
      -1.0737e+09
    cmdout =
      0×0 empty char array

and the simulation does not run.

When running this test using the 2.3 version of OpenFAST, the input files seem to be incompatible, with some additional lines, hence giving errors such as this:

     FAST_InitializeAll:FAST_Init:FAST_ReadPrimaryFile:Invalid numerical input for file
     "5MW_OC4Semi_WSt_WavesWN.fst" occurred while trying to read NLinTimes.

Is it possible to get the OpenFAST 2.3-compatible test files? Would that work? What am I missing?

I would be very grateful for any hints.

**Comment by andrew-platt** [comment]
It sounds like you don't have the correct version of the regression tests.  How did you download the regression tests?

If you cloned using git, try `git submodule update` and see if that gets the correct regression tests for the version you have checked out.

**Comment by kasia129** [comment]
I downloaded a .zip of the r-test repository from this location: https://github.com/OpenFAST/r-test/tree/01f51597b8f058d6f08ec67d7b9aeb4a2ffccaad. These seem to be a version later than 2.3, but don't work with 2.5.

**Comment by kasia129** [comment]
I downloaded a .zip of the r-test repository from this location: https://github.com/OpenFAST/r-test/tree/01f51597b8f058d6f08ec67d7b9aeb4a2ffccaad. I did not manage to run any version of openFAST with these files as downloaded (tried 2.3, 2.4 and 2.5).

**Comment by jjonkman** [comment]
Dear @kasia129,

It looks like you are accessing an old branch of the r-test repository.  Downloading the main branch (https://github.com/OpenFAST/r-test/tree/main) should currently be compatible with OpenFAST v2.5.

Best regards,

**Comment by kasia129** [comment]
Thank you very much for your quick response. You are absolutely right, I tried to use an old branch. I have now downloaded the main branch and tried to run openFAST 2.5 with the _'5MW_OC4Semi_WSt_WavesWN'_ test case, but I keep having the same problem:

    [status,cmdout] = system('openfast_x64.exe 5MW_OC4Semi_WSt_WavesWN.fst')
    status =
        -1.0737e+09
    cmdout =
        0×0 empty char array

My process is to copy the executable into the test case folder and run it from MATLAB. I am working in the repository directory so that the path to the rotor folder (_'5MW_Baseline'_) is not missed. Am I missing any steps?

Kind regards,
Kasia

**Comment by rafmudaf** [comment]
Hi @kasia129 - What are you expecting to see in `status` and `cmdout`?

**Comment by kasia129** [comment]
Hi @rafmudaf , thank you so much for your response. Yes, you are right, _status_ should be 0 and _cmdout_ should be whatever openFAST prints out. I have just tried running it from the Command Prompt, and this system error pops out:

    The code execution cannot proceed because libmmd.dll was not found. Reinstalling the program may fix this problem.

I am running different geometries/problems from Matlab and they work fine. I previously run the _'5MW_OC3Spar_DLL_WTurb_WavesIrr'_ case using the files from the repository as well, but to make it work I had to modify the input files by hand, removing some of the lines which were not compatible with the version of the executable I used. Surely there must be a better way.

**Comment by rafmudaf** [comment]
@kasia129 it sounds like you may have the older version of the Intel redistributable libraries installed. Could you verify in your installed applications list in Settings that you have the Intel redistributables version 20, as shown in the image:

![Capture](https://user-images.githubusercontent.com/13797903/110887598-3762aa00-82b0-11eb-906d-96696cee5426.PNG)

**Comment by kasia129** [comment]
Thank you @rafmudaf for this suggestion; it turns out I did not have the Intel redistributables installed at all (only the Microsoft redistributables). After the installation, and adding the _DISCON_OC3Hywind.dll_ files to the ServoData folder, all works fine. Thank you!
