### ISSUE TITLE
Registry mis-interpretation of multi-digit array size without curly braces

### ISSUE THREAD

**Issue by andrew-platt** [OpenFAST/openfast#669]
The registry can misinterpret mult-digit array size specicifations unless wrapped in curly braces.

### Example of issue

For example, the array size specification of `20` will get interpreted as a 2D array with size dimension `(1:2,1:0)`

```
typedef    ^    FAST_ExternInputType    ReKi    CableDeltaL    20    -    -    "Cable control DeltaL"    m
```

and written to the  `_Types.f90` file as:

```
    REAL(ReKi) , DIMENSION(1:2,1:0)  :: CableDeltaL      !< Cable control DeltaL [m]
```

instead of the **expected result** of 

```
    REAL(ReKi) , DIMENSION(1:20)  :: CableDeltaL      !< Cable control DeltaL [m]
```

This can lead to some rather unexpected rank mismatch errors when trying to access the array.
 
### Workaround

If you wrap the array size specification in curly braces  as follows, it is interpreted as expected

```
typedef    ^    FAST_ExternInputType    ReKi    CableDeltaL    {20}    -    -    "Cable control DeltaL"    m
```

 
Single digit values in that column without the curly braces are interpreted without error.

**Comment by andrew-platt** [comment]
For multi-dimensional fixed size arrays, we typically specify them with curly braces:

```
typedef	^	FAST_VTK_SurfaceType	SiKi	NacelleBox	{3}{8}	-	-	"X-Y-Z locations of 8 points that define the nacelle box, relative to the nacelle position"	m
```

**Comment by bjonkman** [comment]
For what it is worth, the original spec was to use brackets to specify/separate each dimension. Then John added some features so we could specify multi-dimensional allocatable arrays without the brackets (and apparently single-digit array sizes).

**Comment by andrew-platt** [comment]
I was a bit suspicious that it was a result of that shorthand notation capability.  We do use `::` on occasion for two dimensional allocatable arrays, so the parser probably doesn't doesn't do any checking for digits.

In 9 years of using the registry, this is the first time I've run into this problem.  Given that history, it probably isn't worth spending the time to modify the registry.
