### ISSUE TITLE
How to couple OpenFAST with Orcaflex 10.2 for coupled aero-hydrodynamic analysis

### ISSUE THREAD

**Issue by AryaThomas** [OpenFAST/openfast#671]
**Is your feature request related to a problem? Please describe.**
<A clear and concise description of the problem.>

**Describe the solution you'd like**
<A clear and concise description of what you want to happen.>

**Describe alternatives you've considered**
<A clear and concise description of any alternative solutions or features youve considered.>

**Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by jjonkman** [comment]
Dear @AryaThomas,

Please see the following related issue: #388.

Best regards,

**Comment by AryaThomas** [comment]
Good day,
 I have seen the #388 issue, but I could only understand a little. Can you elaborate the procedure to couple the two softwares? 
Then I saw the below page in GitHub.
![FAST-OrcaFlex](https://user-images.githubusercontent.com/79747593/110237795-ebd49700-7f63-11eb-9ba7-45d50abad883.png)
But in that its said that I have to download FASTORCA.exe and some other executables. But I could only find the FASTLINK_DLL in Orcina site.  Can you help me with it? Also do I have to model the turbine on top of the orcaflex model of platform?

Thanks in advance

**Comment by jjonkman** [comment]
Dear @AryaThomas,

As mentioned in #388, the OrcaFlex interface to FAST v8 has not changed in OpenFAST.  You can find the FASTlinkDLL for Windows, sample FAST v8.16 models, and the associated documentation from FAST v8 on my Google drive: https://drive.google.com/drive/folders/1HkFPHo4iAtU3hDAlsthBcZf9F1xUcdSZ?usp=sharing.  The sample input files will need to be upgraded to OpenFAST format for use with OpenFAST.

A valid OrcaFlex license is required to run simulations, available from Orcina.

The FAST / OpenFAST interface to OrcaFlex was developed to run coupled floating offshore wind turbine simulations, with the hydrodynamics and moorings solved in OrcaFlex and the turbine, tower, and floating platform structural dynamics; aerodynamics; and control and electrical-drive dynamics computed by FAST / OpenFAST.  If you don't wish to simulate the wind turbine, you shouldn't need this interface.

Best regards,

**Comment by AryaThomas** [comment]
Thanks a lot,

I will do as per the instructions and will let you know the results and issues arising.
