### ISSUE TITLE
Hydrodyn module - OC3 Hywind Spar

### ISSUE THREAD

**Issue by AryaThomas** [OpenFAST/openfast#673]
I am using the same files of OpenFast downloaded from GitHub for simulating the OC3 Hywind-Spar. My doubt is whether I could use the same files from Hydrodata (like .hst, .1, .3) of SPAR from GitHub in order to do my simulation on the same OC3 Hywind-Spar or I have to do a Wamit simulation and then input that data to hydrdyn? (only the wave parameters like wave ht., Time period is changing in my simulation)

**Comment by jjonkman** [comment]
Dear @AryaThomas,

The WAMIT output data used as input to HydroDyn is not sea-state dependent.  You can use the same WAMIT data for different wave heights and wave periods.

Best regards,

**Comment by AryaThomas** [comment]
Thanks a lot.

I have done the simulation for the 0C3 Hywind SPAR platform (same files from GitHub, but with different wave parameters). But in the outfile I am getting  recurring values of exponential type (underlined in blue colour). Do you know the reason?
I am attaching the command prompt file also.
![COMMNAD PROMPT1](https://user-images.githubusercontent.com/79747593/109769617-76de2600-7c20-11eb-9b10-7312b3a4743f.PNG)
![COMMAND PROMPT2](https://user-images.githubusercontent.com/79747593/109769632-7d6c9d80-7c20-11eb-8992-a32d8cc8f4ab.PNG)
![outfile 60s](https://user-images.githubusercontent.com/79747593/109769669-85c4d880-7c20-11eb-86b8-930df40f266e.jpg)

Also, is the simulation correct?

**Comment by jjonkman** [comment]
Dear @AryaThomas,

I don't see any problem with your simulation.  The time-series data in your *.out file is simply wrapped due to the limitation in number of characters per line in the text editor you are using.

Best regards,

**Comment by AryaThomas** [comment]
Really thankful for clarifying my doubts.

**Comment by AryaThomas** [comment]
Hi Jason,

I have some doubts on RAO calculation,

   1) I have simulated the OC3 Hywind SPAR including the turbine with my wave and wind parameters and I have obtained the time series for DOFs, wave elevation. If I do a FFT on them will I get a PSD ? And if I take the ratio between that PSD of DOF and PSD of wave elevation, will I get the RAOs of the entire simulation (which will be affected by wave and wind) ? I have seen calculation of RAO using white noise spectrum in the forum, but nothing is mentioned about aerodyn module.

  2) If I could get the RAOs through the above stated method, is it possible to use the RAO code by Amy Robertson mentioned in the forum?

 3) Is the time series obtained for all the output parameters are due to coupled motion of platform and turbine together?

**Comment by jjonkman** [comment]
Hi @AryaThomas,

Here are my answers to your questions:

1. An FFT and PSD are not the same thing, although you can calculate a PSD via FFT.  See the following topic on our forum for more information, including a simple MATLAB script (_Jason_PSD.m_) that performs the calculations: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=2219.  An RAO cannot be calculated by taking the ratio between two PSDs; instead, the RAO is equal to the output-wave cross-spectral density divided by the wave auto-spectral density, where "output" is any motion and/or load output from the simulation. For example, the heave RAO is the heave-wave cross-spectral density divided by the wave auto-spectral density.  The auto-spectral density is equivalent to a PSD.  I'm not sure I understand your point about AeroDyn, but we have computed RAOs of various floating offshore wind turbines both with and without aerodynamic loading/damping.  The following topics on our forum and our ISOPE 2013 paper are likely of interest to you:
https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1173
https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=1976
https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=2219
https://www.nrel.gov/docs/fy13osti/58098.pdf
2. The MATLAB script provided on our forum (_RAO.m_)--see: https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=1976 --can be used to compute the RAO by post-processing the time series via the cross-spectral density and auto-spectral density, as discussed above.
3. Yes.

Best regards,

**Comment by AryaThomas** [comment]
Hi,

Regarding my 1st doubt, I wanted to present my results in the form of PSD. So I am doing a FFT in time series of DOFs for the whole simulation (combined wave-wind). If I do that, I wanted to compare my results with the equation, S(w) = RAO * A(w), where S(w) = spectral density of DOF of platform (which is the PSD I had obtained like stated above), A(w) = wave spectrum. I wanted to know if I could do this or my theory is correct.
But from your explanation, I could understand that cross spectral density is not same as PSD of DOF. Can you help me to solve this confusion.

Also I have done a FFT for surge time series(=Data) using Jason.m,but what I get is making no sense to me. My x-y axis labels are same as what indicated in your code.

![jason plot](https://user-images.githubusercontent.com/79747593/110955024-26c53900-836f-11eb-9b42-8877a5b5adb3.PNG)
 
![jason code](https://user-images.githubusercontent.com/79747593/110954996-1f9e2b00-836f-11eb-901a-56000fd09f5b.PNG)

**Comment by jjonkman** [comment]
Dear @AryaThomas,

I don't agree with your equation, but you can write:

`S(w) = A(w)*ABS(RAO(w))^2`

If I understand correctly, you are plotting _Sf1_ versus _f1_ derived from Jason_PSD.m (you are plotting the one-sided spectrum rather than the FFT).   The spike at zero frequency is the mean value of the signal.  If you zoom in over the low frequencies, my guess is you'll see other nonzero values of the spectrum (_Sf1_) at positive frequencies.

Best regards,

**Comment by AryaThomas** [comment]
Hi Jason,

1) Now the confusion on RAO is somewhat settled, but if can you state the difference between abs (RAO) and RAO calculated using ratio of cross-spectral density and auto spectral density, it will be more clear for me.

2) Also, I have done the simulation on OC3 Hywind SPAR platform, but the time series show some complications.

I have simulated SPAR for turbine operational case with Hs = 1.5m, Tp = 6.88s and wind speed =11.4m/s, and I have got large surge motion, why is it so? 

![surge](https://user-images.githubusercontent.com/79747593/111040997-07f0a080-845c-11eb-9fdc-66fa72a9b73e.PNG)
![heave](https://user-images.githubusercontent.com/79747593/111041000-0aeb9100-845c-11eb-9ace-1a4f8007f943.PNG)
![pitch](https://user-images.githubusercontent.com/79747593/111041001-0b842780-845c-11eb-9118-04c7ad4d0a69.PNG)
![wave](https://user-images.githubusercontent.com/79747593/111041181-1be8d200-845d-11eb-9f2f-2eaf1f42d4d6.PNG)

I am also attaching the pictures of modules.

![SPAR_OP_INP](https://user-images.githubusercontent.com/79747593/111041284-800b9600-845d-11eb-8778-fc323bd6a258.PNG)
![doubt_hy_op](https://user-images.githubusercontent.com/79747593/111041289-869a0d80-845d-11eb-89fd-58a970597e9d.PNG)

 a) Also the wamit file I refer to in hydrodyn file, is it in correct format? I have saved the wamit files like this:

![doubt_wamit](https://user-images.githubusercontent.com/79747593/111041322-b9440600-845d-11eb-8703-2f56ebf58035.PNG)

b) What is the difference between moordyn and MAP for mooring analysis, which one has to be used?

 3) I also did an extreme case (turbine idling) Hs = 5m Tp =771s wind speed = 9.34m/s (its a wave created during a tsunami event) but compared to event 2), this simulation shows smaller values. Is it because of the chosen data or anything with my simulation?

![ex_aero](https://user-images.githubusercontent.com/79747593/111041553-b3025980-845e-11eb-91db-e8badbb8c86d.PNG)
![ex_elast](https://user-images.githubusercontent.com/79747593/111041560-bd245800-845e-11eb-86ab-be710cf48099.PNG)
![ex_hydro](https://user-images.githubusercontent.com/79747593/111041568-c44b6600-845e-11eb-94e7-7e88ae18cc67.PNG)
![ex_servo](https://user-images.githubusercontent.com/79747593/111041578-ce6d6480-845e-11eb-99d1-b649bef2fbf0.PNG)

![heave](https://user-images.githubusercontent.com/79747593/111041959-d9c18f80-8460-11eb-8fda-48f0d55891ae.PNG)
![pitch](https://user-images.githubusercontent.com/79747593/111041962-db8b5300-8460-11eb-9bcf-ba5a244559c2.PNG)
![surge](https://user-images.githubusercontent.com/79747593/111041963-dc23e980-8460-11eb-936e-cecaee527b1e.PNG)
![wave](https://user-images.githubusercontent.com/79747593/111041964-dcbc8000-8460-11eb-99f5-a67bba1c77cc.PNG)
 
It will be really helpful if my questions are answered . 
Thanks in advance.

**Comment by jjonkman** [comment]
Hi @AryaThomas,

Here are my answers to your questions:

1. The RAO is a complex value, so ABS(RAO) is its magnitude.  Dividing the cross spectral density with the auto-spectral density is a common way in system identification to calculate frequency-response functions from time series.

2. The thrust from the wind turbine causes a large surge offset in the OC3-Hywind spar system.
a) These WAMIT files look fine with me.
b) Their input files are similar, but the underlying theory bases of MAP++ and MoorDyn are quite different.  MAP++ is a quasi-static model based on the analytical formulation of cables.  MoorDyn is a dynamic model based on the lumped mass approach.  Both should give similar results under static conditions or for low-frequency oscillations, and in most cases, both will result in similar global motions of a floating wind turbine.  When mooring dynamics are important (i.e., when calculating mooring line ultimate or fatigue loads), MoorDyn would be more accurate than MAP++.

3. Tp = 771 s is very long for a wave period, which will be far removed from all system natural frequencies, and so, cause little dynamic excitation of the structure.  You'd also have to run a much longer simulation to calculate the response at this period.  Also, with rotor idling, the aerodynamic loads on the rotor will be small, and the aerodynamic loads on the tower (tower drag force) will dominate.

Best regards,

**Comment by AryaThomas** [comment]
Thanks a lot.

**Comment by AryaThomas** [comment]
Hi Jason, 
Really thankful for your early answers and kindness. Now I am having some problem with 10MW turbine. Please do help me as always.

I have simulated upscaled OC3-Hywind-SPAR with 10MW wind turbine in OpenFast.
I got 10MW turbine files from https://github.com/IEAWindTask37/IEA-10.0-198-RWT.
I am using Turbsim (v2.00.08a-bjj, 18-Jul-2017).
a). But I have encountered an error, is that because of the version incompatibility or any missing files?
![cp](https://user-images.githubusercontent.com/79747593/111330074-a61b7b00-8695-11eb-8228-95e13066d68d.PNG)

![file](https://user-images.githubusercontent.com/79747593/111330248-c6e3d080-8695-11eb-8429-3bb9098c9108.PNG)

Inflow file:
![inflow](https://user-images.githubusercontent.com/79747593/111330285-cf3c0b80-8695-11eb-8dcf-dd645af26109.PNG)

Input file for OpenFast: 
![input](https://user-images.githubusercontent.com/79747593/111330385-e3800880-8695-11eb-9671-46f2de2a0262.PNG)

Turbsim file:
![turbsim1](https://user-images.githubusercontent.com/79747593/111330404-e8dd5300-8695-11eb-9248-2d1d8022b3a4.PNG)


b). Also in input file for Openfast, a beamdyn file is needed, but I haven't got that from GitHub. So what should I use instead?
c). I have obtained wamit file for the upscaled SPAR, but it is not aligned like that of wamit file for the baseline  OC3 SPAR from GitHub. Will that cause a simulation error later?

**Comment by jjonkman** [comment]
Dear @AryaThomas,

Here are my answers to your questions:
a) It looks like you are running OpenFAST v2.4, but your InflowWind input file is formatted for a newer version.  See the API documentation found here for differences in formatting between versions: https://openfast.readthedocs.io/en/main/source/user/api_change.html.
b) The OpenFAST model of the DTU 10-MW reference wind turbine model that you are using uses a simplified ElastoDyn representation of the blade structural dynamics.  I'm sure the higher-fidelity BeamDyn representation could be developed with effort, based on the published blade structural data, but I don't believe this is something someone at NREL has developed.
c) I'm not sure what you mean be "not aligned".  Perhaps you mean the formatting is different?  Regardless, HydroDyn expects the hydrodynamic data of the various WAMIT-generated output files (*.1, *.3, and *.hst for first order, etc.) to follow the WAMIT format documented in Chapter 4 of the WAMIT User’s Manual, available online: http://www.wamit.com/manual6.4/Chap4.pdf.

Best regards,

**Comment by AryaThomas** [comment]
Thanks Jason.

b). So I could use the elastodyn_blade.dat to set the individual blade property right? Is this respiratory for 10MW turbine ok to be used or any-other latest version is there?
c) By meaning 'not aligned' is that, the converted files of wamit (.1,.3,.hst) is not opening as the same sequence like that I had obtained in GitHub, it is disarranged. Here is an example for .hst file

[upscaled_spar_21.txt](https://github.com/OpenFAST/openfast/files/6155731/upscaled_spar_21.txt)
Will it can cause error?

**Comment by jjonkman** [comment]
Dear @AryaThomas,

b) I'm not aware of another repository for this version of the DTU 10-MW reference wind turbine (updated within IEA Wind Task 37).
c) I'm still not understanding.  Other than the extension, which should be _hst_, the file you attached is consistent in sequence with the _*.hst_ files provided in the OpenFAST r-test.  Please note, though, that the roll (4,4) and pitch (5,5) elements do not look correct to me.  I would expect these to be negative valued because they should only include the effect of external buoyancy, not including the restoring from body weight / center of mass, which are intrinsically included within ElastoDyn and should not be double counted.

Best regards,

**Comment by AryaThomas** [comment]
Ok, I will look at the comment you have made on roll and pitch.

Thanks a lot.

**Comment by AryaThomas** [comment]
Hi,
I have simulated the above 10MW turbine for an upscaled OC3-Hywind SPAR. Hs = 1.5m,Tp= 6.88s, wind velocity = 11m/s (rated), rotor speed = 9rpm (rated), initial blade pitch = 0deg. I haven't disabled any DOFs in elastodyn, AFAeromod =2 Skewmod =2. But I am getting error :
![1](https://user-images.githubusercontent.com/79747593/111596068-c6ad1780-87f2-11eb-888d-63179c871bc6.PNG)
![2](https://user-images.githubusercontent.com/79747593/111596092-cf9de900-87f2-11eb-8d0d-c5e26872a595.PNG)
![3](https://user-images.githubusercontent.com/79747593/111596133-d62c6080-87f2-11eb-97c3-a573bfe51434.PNG)

But when I had changed AFaeromod=1 Skewmod =1 another error is coming regarding grid height. I have changed the grid ht. from 230m ( z=21350m above grid) to grid ht =237m (z= -8870m below grid). Can you please help me to find out why z is having such a large value? And what value I have to give for grid ht.?
![11](https://user-images.githubusercontent.com/79747593/111622239-efdba100-880e-11eb-95c6-af4564df95d8.PNG)
![111](https://user-images.githubusercontent.com/79747593/111622258-f4a05500-880e-11eb-8235-38541c56e5f2.PNG)
[InflowFile1.txt](https://github.com/OpenFAST/openfast/files/6163806/InflowFile1.txt)

**Comment by andrew-platt** [comment]
Hi @AryaThomas,
What timestep are you using for the simulation?  It looks like your simulation went unstable and ElastoDyn is unable to solve its system of equations.  This often results in AeroDyn errors of velocities above mach 1 or InflowWind giving errors about wind requested at unrealistic positions (below ground or at locations where turbine blades should never be).

I suggest first reducing your timestep by a factor of 2 or more and seeing if ElastoDyn can converge properly.  If that doesn't help, there may be an error in the setup someplace (unrealistically stiff or soft blades, tower, or missing inertia terms someplace).  Turning off degrees of freedom in ElastoDyn can further help narrow down what is causing the simulation to fail.

Andy

**Comment by AryaThomas** [comment]
Hi 
Thanks for the suggestions.

I am carrying out simulation for 700s (TDmax) with time step of 0.0125s (DT) in openfast and for turbsim 700s with 0.05s time step.

**Comment by AryaThomas** [comment]
Hi Andrew, 
 I have done as per your suggestion, tried different time steps but its not converging. One sample simulation is here (700s for 0.0349275s time step):
![3](https://user-images.githubusercontent.com/79747593/111790115-e07c5680-88e7-11eb-9792-c19f6d4e3141.PNG)
![4](https://user-images.githubusercontent.com/79747593/111790134-e40fdd80-88e7-11eb-9914-240717b310f1.PNG)

And when I turned off all the ptfm DOFs, value of z is so high. 

When I used a time step of 0.5s I am getting an error, which is different:


![2](https://user-images.githubusercontent.com/79747593/111790786-947de180-88e8-11eb-8c39-f9dd9a8f9ee3.PNG)

![1](https://user-images.githubusercontent.com/79747593/111790458-39e48580-88e8-11eb-81f8-7971268c23bc.PNG)

I am  attaching the  hydrodyn file. Please do suggest some solution.I have used the same elastodyn file from https://github.com/IEAWindTask37/IEA-10.0-198-RWT.
[IEA-10.0-198-RWT_HydroDyn1.txt](https://github.com/OpenFAST/openfast/files/6171597/IEA-10.0-198-RWT_HydroDyn1.txt)

**Comment by andrew-platt** [comment]
Could you try a small timestep of 0.005 or 0.001 seconds?

We typically cannot run such models with timesteps larger than 0.01 seconds (this is usually the hard coded controller timestep).

**Comment by AryaThomas** [comment]
Hi,

 I have tried both the time step that you have mentioned. But the simulation is crashing after 6s.
Here are the related files that I have used for simulation:

[IEA-10.0-198-RWT_HydroDyn1.txt](https://github.com/OpenFAST/openfast/files/6176273/IEA-10.0-198-RWT_HydroDyn1.txt)
[Results1.xlsx](https://github.com/OpenFAST/openfast/files/6176274/Results1.xlsx)
[IEA-10.0-198-RWT_InflowFile1.txt](https://github.com/OpenFAST/openfast/files/6176282/IEA-10.0-198-RWT_InflowFile1.txt)
[TurbSim1.txt](https://github.com/OpenFAST/openfast/files/6176284/TurbSim1.txt)
[IEA-10.0-198-RWT_ServoDyn1.txt](https://github.com/OpenFAST/openfast/files/6176288/IEA-10.0-198-RWT_ServoDyn1.txt)
[IEA-10.0-198-RWT_ElastoDyn1.txt](https://github.com/OpenFAST/openfast/files/6176289/IEA-10.0-198-RWT_ElastoDyn1.txt)

![1](https://user-images.githubusercontent.com/79747593/111883336-a642b000-89e0-11eb-8697-5862372a44e1.PNG)
![2](https://user-images.githubusercontent.com/79747593/111883337-a80c7380-89e0-11eb-85e3-51d51219eaa5.PNG)


Can you please help me to sort this out?
Is it because of any problem with my upscaled platform? 
Thanks  in advance.

**Comment by AryaThomas** [comment]
Is this problem can be solved by eliminating tower aerodynamic analysis nodes? If yes, could you specify the method to do that?

**Comment by andrew-platt** [comment]
You can either turn off the tower aerodynamics (AeroDyn input file), or generate the tower wind file (`WrADTWR` in TS input file, `TowerFile` in InflowWind.

**Comment by AryaThomas** [comment]
Hi 
I have simulated the platform for 0.005s by adding additional damping, stiffness matrices, changed values in elastodyn file by setting ptfmRefzt = -cog, yawDOF =false, ptfmydof=ptfmhvdof=false. In servodyn, PCmode=5, vscntrl=5
Now the simulation is completed without any error.
But when I change any one of the DOF-flags mentioned above in elastodyn, the simulation gets aborted due small grid in z-axis.
Is excessive heave causing my platform unstable?

**Comment by jjonkman** [comment]
Hi @AryaThomas.

Does your model run as expected if you enable the ElastoDyn DOFs that you've disabled, while disabling aerodynamics and control (CompAero = CompServo = 0)?

Best regards,

**Comment by AryaThomas** [comment]
Hi Jason,

I am really sorry for the late reply.

Yes my model ran when I have enabled all the above mentioned elastodyn DOFs while disabling aerodynamics and control in .fst file.

Thanking you,

**Comment by AryaThomas** [comment]
Hi Jason

So is the controller causing the simulation to abort? By disabling the above flags in.fst, I won't get the coupled simulation right?

**Comment by jjonkman** [comment]
Dear @AryaThomas,

Can you back up and explain what you've changed in the OpenFAST input files and what problem you are seeing?

Best regards,

**Comment by AryaThomas** [comment]
Hi Jason

I am simulating an upscaled OC3 Hywind SPAR platform to accommodate 10 MW IEA turbine. I have obtained the 10MW turbine files from https://github.com/IEAWindTask37/IEA-10.0-198-RWT. From this I have only changed the inflow input file such that it will be compatible for my openfast v_2.4.0.

When I disable the mentioned DOFs in elastodyn, the simulation runs. But when the DOFs are enabled, the simulation gets aborted by saying small grid size in z-direction. But when the aerodynamic and controller in .fst files are disabled, the simulation runs with all the DOFs true. 

This is what I get when I simulated for no wave and wind condition (when YawDOF =true, all other DOF =T) :
![YAWDOF=T](https://user-images.githubusercontent.com/79747593/113828612-3aaf5f80-97a2-11eb-956f-bb25d5e15901.PNG)



When running coupled analysis (with wind and wave, YawDOF =T, all other DOF = T):
![Capture](https://user-images.githubusercontent.com/79747593/113828147-b230bf00-97a1-11eb-8106-a6be6191e29d.PNG)


[Upscaled_SPARElastoDyn.txt](https://github.com/OpenFAST/openfast/files/6269836/Upscaled_SPARElastoDyn.txt)
[Upscaled_SPARServoDyn.txt](https://github.com/OpenFAST/openfast/files/6269837/Upscaled_SPARServoDyn.txt)
[Upscaled_SPAR_AeroDyn15.txt](https://github.com/OpenFAST/openfast/files/6269839/Upscaled_SPAR_AeroDyn15.txt)
[Upscaled_spaR_hydrodyn_file.txt](https://github.com/OpenFAST/openfast/files/6269840/Upscaled_spaR_hydrodyn_file.txt)
[InflowFile1.txt](https://github.com/OpenFAST/openfast/files/6269841/InflowFile1.txt)
 These are my input files.

The problem I face in coupled analysis is gone as i disable the YawDOF, PltfmHvDOF, PltfmYDOF.

Thanking you in advance,

**Comment by jjonkman** [comment]
Dear @AryaThomas,

From my quick skim of your files, I see a few things that are questionable:

- You have PtfmRefzt = -121.38 m, which will create large offset between the platform DOFs in ElastoDyn and the WAMIT reference point in HydroDyn at (0,0,0).  I suggest setting PtfmRefzt = 0 in ElastoDyn so that the reference points are located at the same place in ElastoDyn and HydroDyn.
- The values of the YawSpr and YawDamp in ServoDyn appear to be set to unphysical values (9999999999.0), which is probably why the YawDOF is disabled in the ElastoDyn model provided for the IEA-10.0-198-RWT.  So, my guess is your model will go unstable when YawDOF = True with ServoDyn enabled.  I suggest either setting physical values for YawSpr and YawDamp in ServoDyn, or keeping the YawDOF disabled.
- You haven't explained, and I haven't checked, how you scaled up the structural and hydrodynamic properties of the OC3-Hywind spar floater to support the IEA-10.0-198-RWT, but is the response stable with all platform DOFs enabled when simulating without aerodynamics (CompAero = False) and without incident waves (WaveMod = 0 in HydroDyn)?
- I'm not sure what turbulent wind conditions you are simulating, but I'm suspicious that the initial conditions you've set for the rotor speed (RotSpeed) and blade-pitch angles (BlPitch) in ElastoDyn are equal to the expected (mean) values for the mean wind speed simulated, which is generally recommend, and if not, could cause problems with the controller when ServoDyn is enabled.

Best regards,

**Comment by AryaThomas** [comment]
Hi Jason,

- I have changed to PtfmRefzt = 0 and disabled YawDOF (what are the appropriate values for YawSpr and YawDamp, if any?) I am creating a turbulent wind for 10.75m/s (which is seen as the rated speed from https://github.com/IEAWindTask37/IEA-10.0-198-RWT. documentation) and RotSpeed = 8.68rpm, BlPitch = 0 (from https://github.com/IEAWindTask37/IEA-10.0-198-RWT. ) I am attaching the tursim file and MAP file:

[turbsim.txt](https://github.com/OpenFAST/openfast/files/6273417/turbsim.txt)
[MAP.txt](https://github.com/OpenFAST/openfast/files/6273519/MAP.txt)

And done the usual coupled  simulation (all DOFs are enabled), but it got aborted:
![1](https://user-images.githubusercontent.com/79747593/113908434-285e1180-97f4-11eb-9c2e-1ec61bebdba2.PNG)
![2](https://user-images.githubusercontent.com/79747593/113908455-2eec8900-97f4-11eb-8630-3e9fd899abfd.PNG)


- Yes the response is stable (simulation terminated normally) for my upscaled platform in no wind no wave condition when YawDOF =False and enabling all other DOF s. I have upscaled the platform by a scale factor. 

- I have done the hydrodynamic analysis of upscaled platform in Ansys-AQWA (which has reference point at COG) and converted this file to WAMIT format in BEMRosetta. Due to this reason, I have put PtfmRefzt = -cog earlier. 

I hope these answers are sufficient for you to understand my issues.

Thanking you,

**Comment by jjonkman** [comment]
Dear @AryaThomas,

Just a few comments:

- If you want to enable the YawDOF in ElastoDyn, YawSpr and YawDamp in ServoDyn should be set to give an appropriate yaw actuator response. This is discussed a bit in my post dated May 11, 2010 in the following forum topic: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=356.
- Your error seems to indicate that an aerodynamic analysis node has passed below the lowest edge of the wind domain, which is just above SWL.  Given that the lowest aerodynamic analysis nodes in the blades and tower of your AeroDyn model starts off over 10-m above SWL, this suggests that the platform is heaving downward a lot or that there are large deflections somewhere in the system.  What do the blade, tower, and platform deflections/displacements look like before receiving this error?
- You say that the response is stable when simulating without aerodynamics (CompAero = False) and without incident waves (WaveMod = 0 in HydroDyn), but is the system in vertical equilibrium--i.e., does the combined weight of the rotor + drivetrain + nacelle + tower + floating substructure balance with the hydrostatic buoyancy and mooring (tether) pretension in the vertical direction such that the heave is close to zero?  This vertical equilibrium condition is the recommend way to set up a FOWT model in OpenFAST.
- Are the hydrodynamic data from ANSYS-AQWA and converted with BEMRosetta expressed relative to (0,0,0) or relative to the COG?  The HydroDyn version you are using expects the hydrodynamic data to be relative to (0,0,0).

Best regards,

**Comment by AryaThomas** [comment]
Hi Jason,

- Ok, I will look into the YawDOF from the forum.
- Do you want the outfile upto where the simulation aborts? Is that what you meant by "....before error looks like"?
- I will check the vertical direction of DOF from time series (outfile) after the no wave-wind simulation and will let you know.
- Hydrodynamic data from Aqwa and BEMRosetta is relative to COG. Do I need to transform those values with the help of matrices? Or by PtfmRefzt = -cog cannot provide the required reference point?

Regards,

**Comment by jjonkman** [comment]
Dear @AryaThomas,

Yes, it is helpful to review the simulation results (blade, tower, and platform deflections/displacements) for the portion of the simulation that ran before aborting.

The location of the platform DOF in ElastoDyn does not change the reference point for the potential-flow solution in HydroDyn, which is still (0,0,0) in the version of OpenFAST you are using.  So, you must transform the AQWA output from the COG to (0,0,0).  This has also been discussed on our forum, e.g., see: https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=2198&p=14814 and https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1257.

Best regards,

**Comment by AryaThomas** [comment]
Hi Jason

After transforming the AQWA output from COG to  SWL  and adding additional platform additional damping and stiffness in hydrodyn, the simulation has ran without errors.

Thank you for your time.

**Comment by AryaThomas** [comment]
Hi Jason

1. I have a question regarding Jason.m PSD script. I have asked this same question, but I did not get the solution even after your reply. 
![jason code](https://user-images.githubusercontent.com/79747593/114862079-b4cb8e00-9e0b-11eb-951e-e8e5bd4300a4.PNG)
![jason plot](https://user-images.githubusercontent.com/79747593/114862087-b7c67e80-9e0b-11eb-9262-26699ea4950c.PNG)

Can you please explain how to check the low frequency values to get non-zero psd values?

2. Also how to use the RAO.m script, what is the command line ? For this, I need to create time series of DOF with a white noise wave spectrum with all input files of FAST  for operational load case right?

**Comment by jjonkman** [comment]
Dear @AryaThomas,

Regarding _Jason_PSD.m_, the spike at zero frequency represents the mean (zero frequency) value of the signal.  This value is likely far larger than the values at other frequencies.  If you don't plot the results for f<= 0, or zoom in over the low frequencies, my guess is you'll see other nonzero values of the spectrum (Sf1) at positive frequencies (unless the Data is constant over time).

The use of the _RAO.m_ script is documented in its header.  The MATLAT syntax is:

`[FRF,fi] = ComputeFRFs(time,U,Y,nens,plotting);`

The RAO script does not require that the input wave elevation (U time series) be generated from a white noise spectrum (or perhaps I should say that that condition is not checked), but the RAO script would function best if U was based on a white noise spectrum.  Otherwise, the calculation may be ill-conditioned if the auto-spectral density of the input wave elevation tends to zero at certain frequencies.

Best regards,

**Comment by AryaThomas** [comment]
Ok Jason, I will use the scripts and come back to you.
Thanks a lot.

**Comment by AryaThomas** [comment]
Hi Jason,

1. I have got the same plot when I used the Jason.m, but when I zoom in over the lower positive frequencies, I have got values for spectrum. 
 I have used the code like this :
                 Data=xlsread('surge_series.xlsx','sheet1')
                 df=1/700
                 N=700/0.0125
                 [f1,Sf1]=Jason_PSD(Data,df,N)
![psd_Surge](https://user-images.githubusercontent.com/79747593/115053094-5e8a4800-9efc-11eb-8709-5f695d40a008.PNG)

[surge_series.xlsx](https://github.com/OpenFAST/openfast/files/6326546/surge_series.xlsx)
Is my inputs correct? How to avoid the mean value (at zero frequency) of the signal?

2. In RAO.m, I getting a plot like this
![frf](https://user-images.githubusercontent.com/79747593/115054915-6fd45400-9efe-11eb-9ff7-ea42deae77a8.PNG)
![frf1](https://user-images.githubusercontent.com/79747593/115054920-7236ae00-9efe-11eb-8d90-fab6bdf9f97a.PNG)

Second picture is the zoomed one of first pic.
I have a few doubts:    time= the total simulation time series (0 to 700)
                                   U = input wave elevation series (I have not used the white noise spectrum)
                                   Y = time series of the DOF (in my case surge time series)
          nens=4
Is these right? I am  not able to attachthese files , but screenshots are here. I have done a coupled simulation with all input files of OpenFAST.
time: 
![time](https://user-images.githubusercontent.com/79747593/115057026-289b9280-9f01-11eb-8713-053d81178730.PNG)
U:
 ![U](https://user-images.githubusercontent.com/79747593/115057036-2e917380-9f01-11eb-9fd5-87b61a2f22b2.PNG)
Y: 
![Y](https://user-images.githubusercontent.com/79747593/115057054-33562780-9f01-11eb-965c-5f4e8e7f2da3.PNG)

![matlab](https://user-images.githubusercontent.com/79747593/115056674-c2af0b00-9f00-11eb-876b-fe5d91da2fbf.PNG)



If they are right, then is my RAO plot correct?
In the RAO.m it is written that "This function calculates RAOs based on averaging multiple output files
 generated with white noise excitation.  Averaging four files appears to give decent
 results.  Six files gives good results." what does this actually mean?

**Comment by jjonkman** [comment]
Dear @AryaThomas,

Yes, your PSD looks correct to me.  Looking at your time series, the dominant frequency is at about 0.007 Hz, which is what the dominant peak is in your PSD.  You can remove the mean from the time series before processing the PSD if you don't want a spike at zero frequency showing up in the PSD.

Regarding _RAO.m_, yes, that sounds correct.  But again, the RAO results will only make sense over the frequency range where there is wave energy (which is why the use of white noise waves is the best).  If you are not using white noise waves, I would first calculate the PSD of the wave elevation.  And I would only review the RAO results over the frequency range where a decent amount of wave energy exists.  in RAO.m, `nens` is the number of time series the signals will be separated into in order to ensemble-average (smooth) the RAO.

Best regards,

**Comment by QAlexande** [comment]
Dear @jjonkman 
Hello, I am a newcomer to fast, and recently I encountered some problems :
My goal is to obtain the attenuation response of a spar-type wind turbine with a pitch and fore-aft degree of freedom when the platform inclination is 5° under static water and no wind conditions. I set up my openfast3.0 program through the following steps , 
setp1：
![image](https://user-images.githubusercontent.com/92294430/143243280-f4f302ae-3c83-46aa-a35f-e8fd85ab4572.png)
step2：
![image](https://user-images.githubusercontent.com/92294430/143243394-bddac3cd-1a37-48c5-a8de-844cf1bc602b.png)
step3：
![image](https://user-images.githubusercontent.com/92294430/143244241-ec4ecdc0-20d2-4b5a-b8ae-3d1768aae634.png)

Finally I got the following picture ：
![image](https://user-images.githubusercontent.com/92294430/143244390-18ab8fd3-16d7-4622-be32-7954d672d1ba.png)
But there seems to be some gaps compared with the figure in the paper ：
![image](https://user-images.githubusercontent.com/92294430/143244586-8f1e6e2d-7a01-4b6c-b5a5-ee4a4730cc92.png)

Can you give me some advice on this 

Best regards,

**Comment by andrew-platt** [comment]
@QAlexande, what is the time scale on the second plot?

**Comment by QAlexande** [comment]
dear @andrew-platt 
 The time scale on the second plot is 
![image](https://user-images.githubusercontent.com/92294430/143365872-c493dbb7-472c-4eb2-bf5b-2282a5364378.png)
Best regards,

**Comment by jjonkman** [comment]
Dear @QAlexande,

I'm not sure what paper you are referencing, but one problem could be that pitch and surge motions are coupled in the OC3-Hywind spar, so, if you enable pitch while disabling surge DOFs, then I would not expect that you'd get a representative response.

Best regards,

**Comment by QAlexande** [comment]
dear @jjonkman 
Thank you very much for your reply, with your help, I have reached the goal, thank you very much。
Best regards,
