### ISSUE TITLE
Binary not launching

### ISSUE THREAD

**Issue by Seinacio** [OpenFAST/openfast#675]
Hi

I want to install OpenFAST v2.5.0 from binaries on Windows but the installer is not launching.

I downloaded OpenFAST v2.5.0 binaries zip. I experienced Issue #649, so I downloaded and installed the Intel® Fortran Compiler 19.1 for Windows. In this regard, I suggest updating the link in the [documentation](https://openfast.readthedocs.io/en/master/source/install/index.html), as it currently directs to 2017 version.

However, if I now try to run the openfast_x64_double.exe (the same happens with openfast_x64.exe), even as administrator, it does not launch. For less than a second the mouse shows the system is busy but then nothing happens. Tried to restart the computer but didn't work.

I am using Windows 10 Home.

Thanks in advance

**Comment by jjonkman** [comment]
Hi @Seinacio,

When you say that you tried to run OpenFAST but "nothing happens," what do you mean? Are you running OpenFAST from a command prompt or by double clicking on it? See, e.g., https://github.com/OpenFAST/openfast/issues/463.

Best regards,

**Comment by Seinacio** [comment]
Hi @jjonkman, that solved my problem, thank you.
