### ISSUE TITLE
Compling OpenFAST with Simulink in VS error #11023 and LNK2019

### ISSUE THREAD

**Issue by klitz06** [OpenFAST/openfast#676]
Hi ,
I am trying to build OpenFAST with simulink by choosing Release_Matlab mode with x64. I think errors that I am having is due to simulink linking as you can see from the errors. I am not sure about the warnings if they are problem for compiling or not.

![1](https://user-images.githubusercontent.com/79355394/110036614-57ddb200-7d4e-11eb-9f95-5d15dbcffb2f.JPG)
![2](https://user-images.githubusercontent.com/79355394/110036620-59a77580-7d4e-11eb-9bd9-15d04e48d845.JPG)
![3](https://user-images.githubusercontent.com/79355394/110036628-5c09cf80-7d4e-11eb-867d-84d033265a71.JPG)

I have changed the MATLAB libmex.lib location in simulink properties as written https://github.com/OpenFAST/openfast/issues/638#issuecomment-762409007 in another post. It doesnt solve the problem unfortunately. Below you can see what i have installed in VS and Intel Fortran

![4](https://user-images.githubusercontent.com/79355394/110037874-10f0bc00-7d50-11eb-89a4-a303ccdef3d2.JPG)
![5](https://user-images.githubusercontent.com/79355394/110038010-409fc400-7d50-11eb-8539-8266f8481d8f.JPG)
![6](https://user-images.githubusercontent.com/79355394/110038019-42698780-7d50-11eb-9c4a-3fe93dcc94fa.JPG)

**Comment by andrew-platt** [comment]
Visual studio is not finding the Matlab library that contains `MEXPRINTF`.  You may need to tell visual studio where that is located.

**Comment by klitz06** [comment]
> Visual studio is not finding the Matlab library that contains `MEXPRINTF`. You may need to tell visual studio where that is located.

If you are talking about MATLAB path inside the properties I have changed it to my MATLAB path as I mentioned.
![7](https://user-images.githubusercontent.com/79355394/110039214-f7e90a80-7d51-11eb-9273-172810819592.JPG)

**Comment by andrew-platt** [comment]
Looking at your first output screenshot, it didn't find the `MEXPRINTF` during the compilation of `openfast_x64.exe`.   I'm not sure VS should be building that one during the Release_Matlab build. @bjonkman , do we normally build `openfsat_x64.exe` with this?  I would have thought all the preprocessor defs would render that executable useless.

It does look like it found the appropriate library for the `OpenFAST-Simulink_x64.lib` build.  So I expect that one should work with simulink.

**Comment by andrew-platt** [comment]
@klitz06, which branch are you building?

**Comment by klitz06** [comment]
I used " git clone https://github.com/openfast/openfast.git " to clone the repository. I dont know which one is it. How do I check it?

**Comment by andrew-platt** [comment]
`git branch` will show the available branches.  It will show `main` and `dev` as the two options, and the one you built will be highlighted (or have a star next to it).  I think `main` is the default one.

**Comment by klitz06** [comment]
Yes it is `main` one.

**Comment by andrew-platt** [comment]
What happens if you try the `create_FAST_SFunc.m` script (after setting any paths necessary as mentioned in the script)?  It should only be needing that `OpenFAST-Simulink_x64.lib` for linking to Simulink, and not the `openfast_x64.exe`.

The other warnings can be safely ignored (we mostly follow the Fortran 2008 standard, but only set VS to enforce the Fortran 2003 standard, so it flags stuff that isn't actually an issue).

**Comment by klitz06** [comment]
I think it is succesfully created. I will try the examples and get back.

![image](https://user-images.githubusercontent.com/79355394/110041701-962a9f80-7d55-11eb-85d4-0ee9386d014b.png)

**Comment by klitz06** [comment]
OK I tried to run Ren_Test01_SIG.m and this is the result:
![image](https://user-images.githubusercontent.com/79355394/110042038-31bc1000-7d56-11eb-9be7-50351c541432.png)

I changed VSContrl = 4 and to see if it helps added LSSGagVxa to the ElastoDyn outputs. It didnt help.

**Comment by andrew-platt** [comment]
you may have to add the location of the SFunc to the matlab path.  `addpath(genpath(('../../../install'))` from the examples directory.

**Comment by klitz06** [comment]
I am sorry I couldn't understand what you want me to do. Do I just run it through command window?

**Comment by andrew-platt** [comment]
yes.  I was thinking in the command window. but the error might be indicating a problem with the test itself.

Did you initialize the r-test submodule after cloning from github?  `git submodule update --init --recursive` as outlined here: https://openfast.readthedocs.io/en/dev/source/testing/index.html

**Comment by klitz06** [comment]
Yes I actually ran `git clone --recursive  https://github.com/openfast/openfast.git` at the beginning of the process could it be the problem? Should I use the command you give?

**Comment by andrew-platt** [comment]
does `<openfast git rootdir>/reg_tests/r-test/glue-codes/openfast/AWT_YFix_WSt/` exist?

**Comment by klitz06** [comment]
Yes it exists.

**Comment by andrew-platt** [comment]
I'm not sure then. I'm at a loss for ideas.  Maybe someone else can comment on with what they ran into with this.

**Comment by klitz06** [comment]
Thank you for your help. Could be from my MATLAB installation? Because I did not install everything that comes with MATLAB.

**Comment by andrew-platt** [comment]
so after some testing, I can reproduce the error you are seeing using MATLAB 2020b with simulink on a windows 10 VM.  This was using the `main` branch of OpenFAST.

![Screen Shot 2021-03-04 at 6 04 32 PM](https://user-images.githubusercontent.com/2745453/110052018-14fee880-7d14-11eb-86f3-bd8d422f1384.png)


I had forgotten to mention that there was a bugfix #641 for this problem.  The bug description was given in #632.  This fix has been merged to the `dev` branch, but has not made it into the main branch yet.  My apologies for not remembering this earlier.

So could you try `git checkout dev` then `git submodule update`, then rebuild and try again?

**Comment by klitz06** [comment]
Now OpenFAST runs through MATLAB but now I have this error:

![image](https://user-images.githubusercontent.com/79355394/110053761-055ebe80-7d6b-11eb-961c-18db7bd392a9.png)

**Comment by klitz06** [comment]
After downloading dev branch from scratch compilation completed without error. Same warnings are present and MATLAB example Test01 works. Other one didnt work due to not having DISCON.dll.

**Comment by klitz06** [comment]
Im using NREL 5MW as my base(tower and nacelle is same) and it works well with conda in WSL. When I want to  try running my own designed WT through MATLAB with `Run_OpenLoop.m` I face some problems first:
![image](https://user-images.githubusercontent.com/79355394/110185455-72ce2600-7e23-11eb-82a8-2c6ba081fa4b.png)
Then I changed `TwrShadow` from `True` to `1`, I passed this error although this will probably cause problems in next steps. After this I get the below error:
![image](https://user-images.githubusercontent.com/79355394/110185558-b9238500-7e23-11eb-88c4-1de000dba0b6.png)

And I am stuck here. Is this related to my input files? Because I was able to run `AWT_YFix_WSt` through `Run_OpenLoop.m`. The reason I want to use MATLAB is because I will design a pitch controller otherwise I would use OpenFAST with conda in WSL.

**Comment by andrew-platt** [comment]
Yes.  There was an input file change between v2.5.0 and the `dev` branch.   The conda + WSL is using v2.5.0, but your compiled version is on the `dev` branch.  You can do a `git checkout main; get submodule update` and recompile your local copy to get the v2.5.0 version.

This input file change is noted in the second table **Modified in OpenFAST dev** found here https://openfast.readthedocs.io/en/dev/source/user/api_change.html

**Comment by klitz06** [comment]
I have two more question. Are any test cases where pitch angle is controlled through simulink? And description of cases?

**Comment by jjonkman** [comment]
Dear @klitz06,

There are no Simulink examples like that in the OpenFAST repo, but you may find the Simulink version of the ROSCO controller of interest: https://github.com/NREL/ROSCO_toolbox.

Best regards,

**Comment by klitz06** [comment]
Thank you.

**Comment by LaurenceWETI** [comment]
Hello everyone,

I’ve got an error as AeroDyn trying to read TwrShadow, although the tower shadow switch is set to 0. 

![TwrShadow](https://user-images.githubusercontent.com/47774400/110948238-6412d200-8341-11eb-9c41-d8af568446b3.JPG)


Anyone familiar with such error? 
Best regards.

**Comment by jjonkman** [comment]
Dear @LaurenceWETI,

As with any input file processing issue, I recommend enabling the Echo option to debug.  Do you see any problems in your input file when comparing it with the corresponding Echo file?

Does setting TwrShadow = FALSE solve the problem?

Best regards,

**Comment by andrew-platt** [comment]
@LaurenceWETI 

Version 2.5.0 that you are running uses a boolean flag for the `TwrShadow` input.  As @jjonkman suggested, this should be either `True` or `False`

The version `dev` uses a switch with values of `0,1,2` with the addition of a second tower shadow model.

**Comment by LaurenceWETI** [comment]
Dear @jjonkman and @andrew-platt,

Thank you for your quick reply.
Setting TwrShadow to True or Flase solved the Problem in AeroDyn, but now ServoDyn has a problem with reading `CompNTMD`. I could not find this parameter in the input file of ErvoDyn. 

![ServoDyn](https://user-images.githubusercontent.com/47774400/111164070-f9aa9d80-859d-11eb-874b-bc0060edb7fa.JPG)

Do you have any idea how to solve this error? 
Is there any instructions how to switch to the `dev` version, in order to use the tower shadow switch again?  

Best regards,

**Comment by klitz06** [comment]
Yes, they changed that part in the servodyn files in dev branch. Here take a look at master branch of NREL 5mw [link](https://github.com/OpenFAST/r-test/blob/01f51597b8f058d6f08ec67d7b9aeb4a2ffccaad/glue-codes/openfast/5MW_Land_BD_DLL_WTurb/NRELOffshrBsline5MW_Onshore_ServoDyn.dat) in the TUNED MASS DAMPER section of the file.
