### ISSUE TITLE
I have 19 errors when building a solution 

### ISSUE THREAD

**Issue by Noureddine611** [OpenFAST/openfast#679]
Build started...
1>------ Build started: Project: FAST_Registry, Configuration: Release x64 ------
1>data.c
1>C:\openfast\modules\openfast-registry\src\data.c(1,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>gen_c_types.c
1>C:\openfast\modules\openfast-registry\src\gen_c_types.c(1,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>gen_module_files.c
1>C:\openfast\modules\openfast-registry\src\gen_module_files.c(1,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>misc.c
1>C:\openfast\modules\openfast-registry\src\misc.c(1,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>my_strtok.c
1>C:\openfast\modules\openfast-registry\src\my_strtok.c(1,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>registry.c
1>C:\openfast\modules\openfast-registry\src\registry.c(1,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>reg_parse.c
1>C:\openfast\modules\openfast-registry\src\reg_parse.c(1,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>sym.c
1>C:\openfast\modules\openfast-registry\src\sym.c(63,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>symtab_gen.c
1>C:\openfast\modules\openfast-registry\src\symtab_gen.c(34,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>type.c
1>C:\openfast\modules\openfast-registry\src\type.c(1,10): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
1>Done building project "FAST_Registry.vcxproj" -- FAILED.
2>------ Build started: Project: MAP_dll, Configuration: Release x64 ------
2>Performing Custom Build Tools
2>======================================================================
2>'..\..\build\bin\Registry.exe' is not recognized as an internal or external command,
2>operable program or batch file.
2>'..\..\build\bin\Registry.exe' is not recognized as an internal or external command,
2>operable program or batch file.
2>
2>Error running FAST Registry for MAP.
2> 
2>======================================================================
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): warning MSB8065: Custom build for item "..\..\modules\map\src\MAP_Registry.txt" succeeded, but specified output "c:\openfast\modules\map\src\map_types.h" has not been created. This may cause incremental build to work incorrectly.
2>bstraux.c
2>C:\openfast\modules\map\src\bstring\bstraux.c(1004,26): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
2>C:\openfast\modules\map\src\bstring\bstraux.c(1017,13): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
2>bstrlib.c
2>C:\openfast\modules\map\src\bstring\bstrlib.c(367,32): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
2>dpmpar.c
2>enorm.c
2>enorm_u.c
2>lmder.c
2>lmpar.c
2>qrfac.c
2>qrsolv.c
2>freedata.c
2>C:\openfast\modules\map\src\map.h(38,10): fatal error C1083: Cannot open include file: 'MAP_Types.h': No such file or directory
2>jacobian.c
2>C:\openfast\modules\map\src\map.h(38,10): fatal error C1083: Cannot open include file: 'MAP_Types.h': No such file or directory
2>lineroutines.c
2>C:\openfast\modules\map\src\map.h(38,10): fatal error C1083: Cannot open include file: 'MAP_Types.h': No such file or directory
2>mapapi.c
2>C:\openfast\modules\map\src\map.h(38,10): fatal error C1083: Cannot open include file: 'MAP_Types.h': No such file or directory
2>maperror.c
2>C:\openfast\modules\map\src\map.h(38,10): fatal error C1083: Cannot open include file: 'MAP_Types.h': No such file or directory
2>mapinit.c
2>C:\openfast\modules\map\src\map.h(38,10): fatal error C1083: Cannot open include file: 'MAP_Types.h': No such file or directory
2>numeric.c
2>C:\openfast\modules\map\src\map.h(38,10): fatal error C1083: Cannot open include file: 'MAP_Types.h': No such file or directory
2>outputstream.c
2>C:\openfast\modules\map\src\map.h(38,10): fatal error C1083: Cannot open include file: 'MAP_Types.h': No such file or directory
2>residual.c
2>C:\openfast\modules\map\src\map.h(38,10): fatal error C1083: Cannot open include file: 'MAP_Types.h': No such file or directory
2>simclist.c
2>Done building project "MAP_dll.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by bjonkman** [comment]
The errors come because Visual Studio is not finding the "stdio.h" file in your C projects. This may be because you are using an old version of Visual Studio / Window SDK or because you have something set incorrectly in the Visual Studio settings. What version of Visual Studio are you using? Also, what platform are you building for? You can see this by opening the properties for the `FAST_Registry` project in your Visual Studio solution and looking at the `Target Platform Version` and `Platform Toolset` values:

![image](https://user-images.githubusercontent.com/6108781/110350415-ed986c00-7ff0-11eb-9da3-0a7fafb3c8d9.png)

![image](https://user-images.githubusercontent.com/6108781/110350122-a5794980-7ff0-11eb-8b96-9c0b0a3edf0c.png)

**Comment by Noureddine611** [comment]
Dear Ms. Bonnie Jonkman, 
I am using VS2019 v142, I could not find any other version. 
Best regards, 
Noureddine Alawawdeh 
![Github1](https://user-images.githubusercontent.com/80156110/110357530-0da54b00-8044-11eb-9b5a-61e568e1c40b.png)
![github2](https://user-images.githubusercontent.com/80156110/110357729-46452480-8044-11eb-9bfe-474ca0c38409.png)

**Comment by bjonkman** [comment]
Visual Studio 2019 should be able to find `stdio.h`. I would try changing the Windows SDK Version to 10.0 (or whatever version of 10 you have installed). It's possible the 8.1 SDK didn't get installed with your version of Visual Studio (I don't think it's a default option).

The screenshot of your Solution Explorer window shows an issue with the Fortran projects: they are all listed as "incompatible". That is a separate issue, but one that you should figure out. Do you have Intel Fortran installed, too?

**Comment by Noureddine611** [comment]
Dear Ms. Bonnie Jonkman,

I reinstall VS2019 and Fortran, I think that I solved "incompatible" issue, and "stdio.h" too, but still doesn't work. I have 3977 errors as follow:
 "========== Build: 2 succeeded, 2 failed, 0 up-to-date, 1 skipped ==========" 
"5>FAST - 31 error(s), 14 warning(s)"
"3>FASTlib - 3946 error(s), 174 warning(s)"
"4>------ Skipped Build: Project: OpenFAST-Simulink, Configuration: Release_Matlab x64 ------" 

are the following configurations Right as depicted for the following: "OpenFast Simulink" and "FAST_Registry" and "MAP_dll"
Best Regards, 

![github3](https://user-images.githubusercontent.com/80156110/110388405-b7e49900-806b-11eb-8f4f-8a659f486647.png)
![github4](https://user-images.githubusercontent.com/80156110/110388913-786a7c80-806c-11eb-822d-53ce03b282db.png)
![github5](https://user-images.githubusercontent.com/80156110/110388924-7d2f3080-806c-11eb-86cb-935b5a81e3ec.png)

**Comment by bjonkman** [comment]
I think it's building the C/C++ stuff correctly, it's just the Fortran code that is failing. Can you show the build output from the "output" tab (next to the error list)? Seeing the first few errors from that window will make it easier to interpret what the problem is.

**Comment by Noureddine611** [comment]
Dear Ms. Bonnie Jonkman, 

The first errors as follow: 
 
Build started...
1>------ Build started: Project: FAST_Registry, Configuration: Release x64 ------
1>data.c
1>gen_c_types.c
1>gen_module_files.c
1>C:\openfast\modules\openfast-registry\src\gen_module_files.c(2346,19): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:\openfast\modules\openfast-registry\src\gen_module_files.c(2358,24): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>misc.c
1>my_strtok.c
1>registry.c
1>reg_parse.c
1>sym.c
1>symtab_gen.c
1>type.c
1>C:\openfast\modules\openfast-registry\src\type.c(187,1): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>Generating code
1>Previous IPDB not found, fall back to full compilation.
1>All 75 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>FAST_Registry.vcxproj -> C:\openfast\build\bin\Registry.exe
1>Done building project "FAST_Registry.vcxproj".
2>------ Build started: Project: MAP_dll, Configuration: Release x64 ------
2>Performing Custom Build Tools
2>======================================================================
2>
2>----- FAST Registry --------------
2>----------------------------------------------------------
2>input file: ..\..\modules\map\src\MAP_Registry.txt
2>opening ..\..\modules\nwtc-library\src/Registry_NWTC_Library.txt
2>opening ..\..\modules\map\src/MAP_Fortran_Registry.txt in usefrom mode
2>opening ..\..\modules\nwtc-library\src/Registry_NWTC_Library.txt in usefrom mode
2>generating ..\..\modules\map\src/MAP_Types.f90
2>CUSTOMBUILD : Registry warning : derived data type LinInitInp of type lin_initinputtype is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type LinInitInp of type lin_initinputtype is not passed through F-C interface
2>CUSTOMBUILD : Registry warning : derived data type Ver of type progdesc is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type LinInitOut of type lin_initoutputtype is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type Ver of type progdesc is not passed through F-C interface
2>CUSTOMBUILD : Registry warning : derived data type LinInitOut of type lin_initoutputtype is not passed through F-C interface
2>CUSTOMBUILD : Registry warning : derived data type LinParams of type lin_paramtype is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type LinParams of type lin_paramtype is not passed through F-C interface
2>CUSTOMBUILD : Registry warning : derived data type PtFairDisplacement of type meshtype is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type PtFairDisplacement of type meshtype is not passed through F-C interface
2>CUSTOMBUILD : Registry warning : derived data type ptFairleadLoad of type meshtype is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type ptFairleadLoad of type meshtype is not passed through F-C interface
2>
2>----- FAST Registry --------------
2>----------------------------------------------------------
2>input file: ..\..\modules\map\src\MAP_Fortran_Registry.txt
2>opening ..\..\modules\nwtc-library\src/Registry_NWTC_Library.txt
2>generating ..\..\modules\map\src/MAP_Fortran_Types.f90
2>
2>Registry for MAP completed.
2> 
2>======================================================================
2>bstraux.c
2>C:\openfast\modules\map\src\bstring\bstraux.c(1004,26): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
2>C:\openfast\modules\map\src\bstring\bstraux.c(1017,13): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
2>bstrlib.c
2>C:\openfast\modules\map\src\bstring\bstrlib.c(367,32): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
2>dpmpar.c
2>enorm.c
2>enorm_u.c
2>lmder.c
2>lmpar.c
2>qrfac.c
2>qrsolv.c
2>freedata.c
2>jacobian.c
2>lineroutines.c
2>mapapi.c
2>maperror.c
2>mapinit.c
2>numeric.c
2>outputstream.c
2>residual.c
2>simclist.c
2>lmroutines.cc
2>   Creating library ..\..\build\bin\MAP_x64.lib and object ..\..\build\bin\MAP_x64.exp
2>Generating code
2>Previous IPDB not found, fall back to full compilation.
2>All 293 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
2>Finished generating code
2>MAP_dll.vcxproj -> C:\openfast\build\bin\MAP_x64.dll
2>Done building project "MAP_dll.vcxproj".
C:\openfast\modules\nwtc-library\src\SysIVF.f90 : warning: Module 'x64\Release\syssubs.mod' is created by both 'C:\openfast\modules\nwtc-library\src\SysIVF.f90' and 'C:\openfast\modules\nwtc-library\src\SysMatlabWindows.f90'.
3>------ Build started: Project: FASTlib, Configuration: Release x64 ------
3>Performing Pre-Build Event...
3>Compiling with Intel® Fortran Compiler Classic 2021.1.1 [Intel(R) 64]...
3>qk61.f
3>i1mach.f
3>xermsg.f
3>xerhlt.f
3>slasrt2.f
3>xercnt.f
3>j4save.f
3>xgetua.f
3>fdump.f
3>d1mach.f
3>xersve.f
3>dqk61.f
3>xerprn.f
3>r1mach.f
3>dlasrt2.f
3>fftpack4.1.f
3>VersionInfo.f90
3>qsort_c_module.f90
3>SingPrec.f90
3>RANLUX.f90
3>ED_UserSubs.f90
3>NWTC_Base.f90
3>NWTC_SLATEC.f90
3>UserSubs.f90
3>NWTC_LAPACK.f90
3>NWTC_ScaLAPACK.f90
3>SysIVF.f90
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(126): warning #7416: Fortran 2003 does not allow this intrinsic procedure.   [ERF]
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(136): warning #7416: Fortran 2003 does not allow this intrinsic procedure.   [ERF]
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(149): warning #7416: Fortran 2003 does not allow this intrinsic procedure.   [ERF]
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(166): warning #7416: Fortran 2003 does not allow this intrinsic procedure.   [GAMMA]
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(176): warning #7416: Fortran 2003 does not allow this intrinsic procedure.   [GAMMA]
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(186): warning #7416: Fortran 2003 does not allow this intrinsic procedure.   [GAMMA]
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(228): warning #7410: Fortran 2003 does not allow this keyword.   [DIRECTORY]
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(242): warning #7410: Fortran 2003 does not allow this keyword.   [CARRIAGECONTROL]
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(267): warning #7410: Fortran 2003 does not allow this keyword.   [CONVERT]
3>C:\openfast\modules\nwtc-library\src\SysIVF.f90(284): warning #7416: Fortran 2003 does not allow this intrinsic procedure.   [EXIT]

**Comment by bjonkman** [comment]
You haven't actually gotten any errors yet in this text. These are just some warnings and informational messages. Perhaps you can just output the whole build log?

**Comment by Noureddine611** [comment]
I think it's work
 Thank you 
========== Build: 4 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========
