### ISSUE TITLE
Fast Forum unavailable and TurbSim question

### ISSUE THREAD

**Issue by Amarelio** [OpenFAST/openfast#680]
Greetings,

The Fast Forum seems to be down. Is it indeed down or was the website migrated somewhere else?

Also, I have a simple question that I couldn't look up. Does the Analysis Time on the TurbSim input file need to match the simulation time provided in the .fst file?

Best regards

**Comment by jjonkman** [comment]
Dear @Amarelio,

The server that was hosting the forum and many other sites has gone down.  I’m expecting it to be fixed soon.  I would check back in a few hours.

The AnalysisTime in TurbSim should generally be at least as long as the output time from the corresponding FAST / OpenFAST simulation, but not less than 600 s to avoid coarse discretization of the wind spectrum within TurbSim.

Best regards,
