### ISSUE TITLE
Entries nodal output list ignored Bug report

### ISSUE THREAD

**Issue by JelmerPolman** [OpenFAST/openfast#684]
I couldn't find it as an open issue so I'm posting it here.

**Bug description**
In the BeamDyn primary input file, the first entry in the nodal output list is ignored. That is, the channel at the first entry of the list does not appear in the BeamDyn echo file and the results are not written to the output file (text file). This applies only to the first entry. The second and onward entries are echoed and written to the output files.

**To Reproduce**
For BeamDyn, in the list

`3    BldNd_BlOutNd     - Blades to output`
`"TDxr"`
`"TDyr"`
`"TDzr"`

the channel `TDxr` is not echoed and written, the others are. If the list consists out of one entry, nothing is written.

**Temporary fix**
Replace the ignored entries with a dummy sensor. for BeamDyn for example the list:

`3    BldNd_BlOutNd     - Blades to output`
`"Dummy"`
`"TDxr"`
`"TDyr"`
`"TDzr"`

writes all three channels.

**OpenFAST Version**
OpenFAST-v2.5.0
Compile Info:
 - Compiler: Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R)
 64, Version 2021.1 Build 20201112_000000
 - Architecture: 64 bit
 - Precision: single
 - Date: Jan 14 2021
 - Time: 12:12:37
Execution Info:
 - Date: 03/11/2021
 - Time: 09:29:17+0100

**Comment by JelmerPolman** [comment]
In ElastoDyn, the second entry in the nodal output list is ignored. Furthermore, the channel `TDx` is not written at all to the output file.

**To Reproduce**
For example, in the list

`3   BldNd_BladesOut  - Blades to output`
`"TDx"`
`"TDy"`
`"TDz"`

The channel `TDy` is not echoed and written. Furthermore, the channel `TDx` is echoed, but **not** written.

In the list

`3   BldNd_BladesOut  - Blades to output`
`"TDx"`
`"Dummy"`
`"TDy"`
`"TDz"`

All three channels are echoed, but again, the channel `TDx `not written.

**Comment by JelmerPolman** [comment]
In AeroDyn, all entries are echoed and written.

**Comment by rafmudaf** [comment]
I've tested this in the latest `dev` branch and it seems to work well. @andrew-platt was this addressed in a recent pull request?

**Comment by bjonkman** [comment]
@JelmerPolman, I think you have an incorrect format for these nodal outputs. The lines you say are ignored are supposed to be comment lines.

For **BeamDyn**, you can see examples here: 
- https://openfast.readthedocs.io/en/dev/source/user/beamdyn/appendix.html 
- https://github.com/OpenFAST/openfast/blob/main/docs/source/user/beamdyn/examples/NodalOutputs.txt

```
END of input file (the word "END" must appear in the first 3 columns of the last OutList line)
====== BeamDyn Outputs for all blade stations (same ending as above for B1N1.... ========== 
   "All"          BldNd_BlOutNd       - Future feature will allow selecting a portion of the nodes to output.  Not implemented yet. (-)
                  OutList             - The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels, (-)
TDxr
TDyr
TDzr
```

BeamDyn doesn't have a "blades to output" line since there is one file per blade. 


For **ElastoDyn**, there is one additional line for the nodal outputs (the number of blades for output). Here is the documentation on the format:
- https://github.com/OpenFAST/openfast/blob/main/docs/source/user/elastodyn/exampleInput/NodalOutpus.txt
```
END of input file (the word "END" must appear in the first 3 columns of this last OutList line)
---------------------- ELASTODYN NODE OUTPUTS --------------------------------------------
          3   BldNd_BladesOut  - Blades to output
         99   BldNd_BlOutNd   - Blade nodes on each blade (currently unused)
              OutList     - The next line(s) contains a list of output parameters.  See OutListParameters.xlsx, ElastoDyn_Nodes tab for a listing of available output channels, (-)
"ALx"    -  local flapwise acceleration (absolute) of node
"ALy"    - local flapwise acceleration (absolute) of node
"ALz"    - local flapwise acceleration (absolute) of node
```

**Comment by JelmerPolman** [comment]
Thank you for the replies.

I was always looking for examples after a version release, but could never find them. Thank you for the reference. it all works as expected now.
