### ISSUE TITLE
Simulink Inputs to S-Function

### ISSUE THREAD

**Issue by klitz06** [OpenFAST/openfast#685]
Hi, I cannot login, reset or send an email in NREL forum telling me to contact admin so I will write my problem here. I am trying to get to know simulink integration of OpenFAST and right now trying to create simple-variable torque control through simulink. I am however having some issues. I used calculations for Region 2 and Region 2 1/2 for constants and equations and diagram(pg. 41) given in [here](https://www.nrel.gov/docs/fy08osti/42437.pdf). I can start simulations using calculated values in OpenFAST through conda and they look realistic to me. 
Here is control diagram:
![simple_diagram](https://user-images.githubusercontent.com/79355394/110793806-17b68c00-8286-11eb-95ef-6fc94bf0600c.JPG)

And here is all the simulink project:
![image](https://user-images.githubusercontent.com/79355394/110793905-33ba2d80-8286-11eb-9091-7d7b41634cb9.png)

And the error that I get:

![image](https://user-images.githubusercontent.com/79355394/110794060-6106db80-8286-11eb-9c93-7525e8770f6c.png)

**Comment by jjonkman** [comment]
Dear @klitz06,

Regarding the forum; what is your user name? If you forgot your password, you should be able to reset it by entering your user name and clicking “forgot my password” here: https://wind.nrel.gov/forum/wind/ucp.php?mode=login.

Port 1 into the S-Function must contain both the generator torque and power.  See the simple Simulink model _Test01_SIG.mdl_ (with the corresponding MATLAB script _Run_Test01_SIG.m_) provided in the _Simulink/Samples_ directory of the FAST v8 archive for a simple example, which should also work with OpenFAST: https://drive.google.com/file/d/1dZXlrORZG5c6T30fCAML7VDcdRmLE73_/view?usp=sharing.

Best regards,

**Comment by klitz06** [comment]
Even if I try to reset my password I get an error saying contact admin. The support ID is : 10420325272844506744 and my username is Deniz.Kepez .
Regarding Simulink model, I need to provide both power and torque I understand.

**Comment by jjonkman** [comment]
Dear @klitz06,

Regarding the forum, I suggest trying a different web browser to see if that solves the problem.

Best regards,

**Comment by klitz06** [comment]
Thank you different browser solve the problem. Regarding the `Test01_SIG.mdl`, inside the Simulink model the output from FAST to the input of simple generator is sorted through block `Fcn`. However, atleast in MATLAB R2020a it does not work. I had to change that block to Ìnterpreted MATLAB Function` with the same function name to get it started.
