### ISSUE TITLE
MoorDyn input file change for release v2.5.0 not documented

### ISSUE THREAD

**Issue by pschuenemann** [OpenFAST/openfast#694]
Hi all,

In release v2.5.0 active tensioning capabilities were added to MoorDyn.
This requires a change of the MoorDyn input file, see #565.

This input file change is missing in the documentation of API changes between OpenFAST v2.4.0 and OpenFAST v2.5.0 on https://openfast.readthedocs.io/en/main/source/user/api_change.html#openfast-v2-4-0-to-openfast-v2-5-0.

It would be nice if it could be added there. 
Unfortunately, right now I don't have time to do it. Thus, I just want to mention it here, so it won't be forgotten.

Best regards,
Paul

**Comment by andrew-platt** [comment]
Hi Paul.  Thanks for the note.  I'll get that into the docs.

**Comment by pschuenemann** [comment]
Great. Thanks!
