### ISSUE TITLE
Openfast Linux binary can't reproduce results

### ISSUE THREAD

**Issue by sinolonghai** [OpenFAST/OpenFAST#7]
I have compiled two versions of openfast in Linux/CMake using Intel and gcc respectively. And I compared their results for Test21 with the results in https://github.com/NWTC/FAST. The three results are just different with each other. Any one has an idea? I need a standard way to compile openfast so that I can use this as the benchmark.
Thanks!

**Comment by sayerhs** [comment]
@sinolonghai Are you running this on Peregrine? can you share the location of the results, or upload them to this issue?

**Comment by sinolonghai** [comment]
Yes, on Peregrine: /scratch/hlong/ipcc/intel/OpenFAST

**Comment by gantech** [comment]
Dr. Jason Jonkman told me that Tests 19-25 use random number generators to generate the input conditions for off shore wind turbines. Hence these tests might yield similar results when using the same compiler with different settings or on different systems; but different results across compilers.

**Comment by sayerhs** [comment]
@gantech Thanks for that tip. I had not realized that. 

@sinolonghai Have you tried other tests and do they also produce different results?  @ghaymanNREL and I compared Test 1 and were able to ascertain that they produce the same results. Can  you rerun that case and let us know if you find issues? If you still have issues, please point to the run directory where you have run the case.

**Comment by sinolonghai** [comment]
Thanks. Will try and let you know the results.

**Comment by michaelasprague** [comment]
@sinolonghai any news on this?

**Comment by michaelasprague** [comment]
@sinolonghai , please comment on this issue -- can it be closed?

**Comment by sinolonghai** [comment]
Successfully reproduced results for test1. Close the issue.
