### ISSUE TITLE
Standalone Modules

### ISSUE THREAD

**Issue by SudharsanKalidoss** [OpenFAST/openfast#701]
Hi everyone,

I need to run the OpenFAST modules separately. I checked in the manual for all the modules for the standalone simulation procedure. All module manuals refers to this site https://www.nrel.gov/wind/nwtc/aerodyn.html. I'm able to find the executables on that website. Is there any other repository available to download the executables? Or do I need the compile the modules from source code like OpenFAST? If so, how do I need to do it? I need AeroDyn, BeamDyn, ElastoDyn, HydroDyn and SubDyn modules.

Thanks

Sudharsan

**Comment by rafmudaf** [comment]
Are you able to use macOS or Linux? If so, conda is your easiest path to install the module drivers: https://openfast.readthedocs.io/en/dev/source/install/index.html#conda-installation

**Comment by SudharsanKalidoss** [comment]
Hi Rafael,

  I'm using Windows OS. Is it possible to use anaconda command prompt to install the drivers? Also can I run modules in standalone mode in anaconda command prompt?

**Comment by rafmudaf** [comment]
No, the OpenFAST conda-forge project is not yet configured to build for Windows, unfortunately. You could use the Windows Linux Subsystem. Otherwise, you'll have to compile the binaries as described here: https://openfast.readthedocs.io/en/dev/source/install/index.html#compile-from-source.

**Comment by rafmudaf** [comment]
Before you compile, do you really need the standalone modules or are you intending to run a coupled simulation?

**Comment by SudharsanKalidoss** [comment]
I already have executable for OpenFAST which is compiled using visual studio. I want to run the modules separately.

**Comment by rafmudaf** [comment]
Oh great! Configuring a system to compile OpenFAST can be challenging, so I try to ensure that people go down that path only when it's required. In any case, you should be set to compile the driver codes you need.

**Comment by SudharsanKalidoss** [comment]
Can you guide me in that process? I'm not familiar with visual studio. I just followed the instructions given in the OpenFAST documents.

**Comment by rafmudaf** [comment]
Each module driver has its own Visual Studio project. For example, BeamDyn's is here: https://github.com/OpenFAST/openfast/tree/main/vs-build/BeamDyn. You can double click on the `vfproj` file and it will open Visual Studio. Then, it should be a very similar sequence as building OpenFAST.

I don't use these myself, so my knowledge is limited. @bjonkman is there any nuance for the module drivers?

**Comment by bjonkman** [comment]
I have a list of the solution files that are available for Visual Studio here: https://github.com/OpenFAST/openfast/blob/main/vs-build/ReadMe.md. In general, you'd open the solution files that are linked on that page and then select 'build' (typically using the `Release` configuration). They write the executables they generate to the `<openfast>\build\bin` directory.

**Comment by rdamiani** [comment]
I am getting this error trying to build the AeroDyn driver from the VSbuild solution:

Error		fatal error LNK1181: cannot open input file 'D:\Program Files\Microsoft Visual Studio\2019\Community\build\bin\Registry.lib'		LINK		

Could you please help me figure this out?

**Comment by bjonkman** [comment]
@rdamiani ,

Which build configuration are you running? The error message you've printed sounds like it could be attempting to link the Registry into AeroDyn_Driver. Can you verify that the AeroDyn_Driver project file is set to NOT link the library dependencies? 
![image](https://user-images.githubusercontent.com/6108781/123523617-ec637b80-d681-11eb-9c28-9de149e93618.png)

**Comment by rdamiani** [comment]
Thank you @bjonkman! it is Release x64, and also Win32, and It indeed shows a Yes at 'Link Library Dependencies';
And of course with your magic, it now works, you are the BEST!
