### ISSUE TITLE
Simulation error

### ISSUE THREAD

**Issue by Noureddine611** [OpenFAST/openfast#704]
Dear All, 
This is my first time on openfast, I am try to make simulation using one of r-test examples , but I always have this, and I don't know what to do. 
Thanks in advance.
![1](https://user-images.githubusercontent.com/80156110/113443992-af2d7b80-93fb-11eb-8ebb-1b92b1c2a87a.png)
![2](https://user-images.githubusercontent.com/80156110/113444004-b3f22f80-93fb-11eb-92f1-db341e908f92.png)

**Comment by jjonkman** [comment]
Dear @Noureddine611,

The problem is that the path to your ElastoDyn blade input file (_NRELOffshrBsline5MW_Blade.dat_) is not set correctly in your ElastoDyn primary input file (_NRELOffshrBsline5MW_OC3Hywind_ElastoDyn_).

Best regards,

**Comment by Noureddine611** [comment]
Dear @jjonkman, 
I corrected the path, but unfortunately I have another problem. I could not find "DISCON_OC3Hywind.dll" file. 
kindly please check the screen shot. 
Best regards, 
![3](https://user-images.githubusercontent.com/80156110/113492483-423fe180-94e0-11eb-8174-1711fb6285bc.jpg)

**Comment by Noureddine611** [comment]
Dear @jjonkman,

I am trying to compile "Discon", but it always fail.  And I have another question because this is my first time on "openfast". Do I need to build solutions for all folders in "vs-build" ? 
Kindly please check the screen shot.

Best regards,
![6](https://user-images.githubusercontent.com/80156110/113630681-f3758180-9670-11eb-8655-47f4c818a3b3.jpg)
![7](https://user-images.githubusercontent.com/80156110/113630775-17d15e00-9671-11eb-9ece-70c7ba778358.jpg)

**Comment by Noureddine611** [comment]
Thank you Mr. @jjonkman
