### ISSUE TITLE
Build issues from filesystem header include in C++ API

### ISSUE THREAD

**Issue by psakievich** [OpenFAST/openfast#708]
I'm unable to compile the `dev` branch due to the include of `filesystem` that was added in #670. I'm using GCC 7.2 and Intel 19.  Is the include of `filesystem` necessary?  This header is [not supported in GCC 7](https://stackoverflow.com/questions/45867379/why-does-gcc-not-seem-to-have-the-filesystem-standard-library).

If necessary I can move my build systems up to a GCC 8 if we decide we don't need to support GCC 7 for Exawind/HFM.
@sayerhs or @jrood-nrel would you care to weigh in on this?

 I guess some macro magic could be employed to switch the include to `experimental/filesystem` too.

**Comment by rafmudaf** [comment]
Do you need to compile the C++ based driver or just the C++ API? If just the API, you shouldn't need to deal with FAST_Prog.cpp and its included `filesystem`. That make-target for the API library is `openfastcpplib` whereas `openfastcpp` compiled both the API and the driver code.

**Comment by sayerhs** [comment]
@rafmudaf Sorry I commented on #670. I'll reproduce that here. 

- Is C++17 the minimum standard required for OpenFAST? 
- `openfastcpp` executable is part of the `install` targets (https://github.com/OpenFAST/openfast/blob/718d46f707d78e85edf1b49d3b1a63e8e23e1aae/glue-codes/openfast-cpp/CMakeLists.txt#L85-L86). So it is not sufficient that we can build `openfastcpplib` we need to be able to execute `make install`. So it seems like a breaking change.

**Comment by sayerhs** [comment]
Also to @psakievich 's point, why is this header included? I don't see any invocations of `std::filesystem` anywhere.

**Comment by rafmudaf** [comment]
These are all good points.

As I understand it (from @gantech), the C++ driver is only used for testing purposes and as a tool to develop the C++ API. So, if anything needs to change there, I don't see a problem with it. I'll take out this unused import of filesystem.

It's also worth considering removing it from the `install` target.

**Comment by rafmudaf** [comment]
@psakievich I've updated this in `dev`. Please let me know if you're able to compile now.

**Comment by psakievich** [comment]
@rafmudaf thanks. I just tested and it builds fine now.  This resolves the issue for me.
