### ISSUE TITLE
The Renolds number not calculated correctly in BEMTUncoupled.f90

### ISSUE THREAD

**Issue by gerwangcy** [OpenFAST/openfast#71]
Dear developers,

I find an error regarding the Renolds number calculation in the file:
modules-local/aerodyn/src/BEMTUncoupled.f90,  line 96, which is: 
`Re = airDens * W * chord / mu`
It seems to be problematic, because the variable 'mu' here is actually the kinematic viscosity, rather than the dynamic viscosity. This line is within the subroutine:
`subroutine BEMTU_Wind( axInduction, tanInduction, Vx, Vy,  chord, airDens, mu, W, Re )`
which is called by many other functions, an example is in the file:
modules-local/aerodyn/src/BEMT.f90,  line 977, which is:
`call BEMTU_Wind( 0.0_ReKi, 0.0_ReKi, u1%Vx(i,j), u1%Vy(i,j), p%chord(i,j), p%airDens, p%kinVisc, Vrel, Re )`
The seventh argument is kinematic viscosity instead of dynamic viscosity! It is true for other calls of the function. The easiest way to correct may be just to replace the line 96 of BEMTUncoupled.f90 with:
`Re =  W * chord / mu`

It is also the case for fastv8 repository. I hope this could help. Thanks.

Best,
Chengyu Wang

**Comment by rafmudaf** [comment]
Fixed by #195
