### ISSUE TITLE
How does AeroDyn use the wind file generated by TurbSim?

### ISSUE THREAD

**Issue by Domotopeng** [OpenFAST/openfast#710]
Hello, 
I want to learn how to use the wind file generated by TurbSim to run AeroDyn independently, but after reading the user guides of TurbSim and AeroDyn, I still don't know how to do it. The main doubt at the moment is, do I need to modify the "ad_TimeseriesInput.inp" file in the driver? Is there a way to use wind files generated by TurbSim directly? Is this related to Inflowwind?
Special note, the modules I compiled are the latest version.

Best wishes!

**Comment by jjonkman** [comment]
Dear @Domotopeng,

What do you mean when you say, "wind file generated by TurbSim to run AeroDyn independently"?  Are you referring to the standalone AeroDyn driver or are you running AeroDyn coupled to OpenFAST (aeroelastically)?

TurbSim can be used to generate full-field turbulent wind data files that can be read directly by the InflowWind module within coupled OpenFAST simulations.  InflowWind can make use of any TurbSim output.  The name of the TurbSim output file is an input in the InflowWind module input file.

Best regards,

**Comment by Domotopeng** [comment]
> Dear @Domotopeng,
> 
> What do you mean when you say, "wind file generated by TurbSim to run AeroDyn independently"? Are you referring to the standalone AeroDyn driver or are you running AeroDyn coupled to OpenFAST (aeroelastically)?
> 
> TurbSim can be used to generate full-field turbulent wind data files that can be read directly by the InflowWind module within coupled OpenFAST simulations. InflowWind can make use of any TurbSim output. The name of the TurbSim output file is an input in the InflowWind module input file.
> 
> Best regards,

Dear @jjonkman ,
First of all sorry for my  poor English! I referring to the standalone AeroDyn driver .I want to run the standalone AeroDyn driver and the wind file in it is generated by Turbsim, but I don't know how to operate it. I tried to change the “ad_driver.inp”, but I don’t know how to apply the wind file generated by Turbsim to the standalone AeroDyn driver.

Best whishes!

**Comment by jjonkman** [comment]
Dear @Domotopeng,

The current standalone driver for AeroDyn only supports steady wind.  A new AeroDyn driver under development does support TurbSim-generated wind data files because the driver also calls the InflowWind module, but this new driver has not yet been merged into the dev or main branches of OpenFAST.  See: https://github.com/OpenFAST/openfast/pull/688.

Best regards,

**Comment by Domotopeng** [comment]
Dear@jjonkman 
Thanks for your reply! I will try to use these test cases. Besides, if I use Simulink to run Open
fast, are the variables in the output file selected from the output variables of the ElastoDyn module? When I increase the output variable in AeroDyn, such as "RtAeroCp", Matlab reports an error. Can I export the output variables in AeroDyn?
![error](https://user-images.githubusercontent.com/46665739/114265638-8b35ef80-9a24-11eb-923a-48fc0e99929c.JPG)

**Comment by Domotopeng** [comment]
Dear @jjonkman 
I tried to run the test case in #688 with the standalone AeroDyn driver, but an error occurred. Does the current AeroDyn driver not match the test case?
![error3](https://user-images.githubusercontent.com/46665739/114291457-2927c980-9aba-11eb-9470-5bfa4944fcd3.JPG)

Best wishes!

**Comment by bjonkman** [comment]
It looks like your AeroDyn input file is not in the correct format for the version of AeroDyn (i.e., OpenFAST) that you are using.

**Comment by jjonkman** [comment]
Dear @Domotopeng,

Regarding your first question, "yes," you should have access to the OpenFAST output from any module (including RtAeroCp in AeroDyn) within Simulink.

To add to what Bonnie said regarding your second question, the new AeroDyn driver that is still under development that I linked to requires an updated driver input file format.  This is documented in the new AeroDyn driver documentation, also under development: https://ebranlard-openfast.readthedocs.io/en/f-driver/source/user/aerodyn/driver.html.

Best regards,
