### ISSUE TITLE
OpenFAST Error while linking to simulink

### ISSUE THREAD

**Issue by AbdElhamidNabeel** [OpenFAST/openfast#715]
I have followed every step in the following documentation [OpenFAST](https://github.com/OpenFAST/openfast/files/4363742/OpenFAST_Simulink.pdf) and every thing goes well, but when running the openloop.m file i receive the following error

I'm using MATLAB R2019b, Visual Studio 2019 for building the libraries.

i have created the FAST_SFunc.mexw64 as following

Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.

When running the openloop.m file, the following error occurred.

 **************************************************************************************************
 OpenFAST

 Copyright (C) 2021 National Renewable Energy Laboratory
 Copyright (C) 2021 Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.5.0-dirty
 Compile Info:
  - Compiler: Intel(R) Fortran Compiler 2021
  - Architecture: 64 bit
  - Precision: single
  - Date: Apr 10 2021
  - Time: 19:51:17
 Execution Info:
  - Date: 04/10/2021
  - Time: 20:47:44+0200

 OpenFAST input file heading:
     FAST Certification Test #18: NREL 5.0 MW Baseline Wind Turbine (Onshore)

 Running ElastoDyn.
 Nodal outputs section of ElastoDyn input file not found or improperly formatted.
 Running AeroDyn.
 Nodal output section of AeroDyn input file not found or improperly formatted.
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 1, blade 1)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 1)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 3, blade 1)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 1)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 1, blade 2)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 2)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 3, blade 2)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 2)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 1, blade 3)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 3)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 3, blade 3)
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 3)
 Running InflowWind.

    Reading a 31x31 grid (145 m wide, 17.5 m to 162.5 m above ground) with a characteristic wind
    speed of 12 m/s. This full-field file was generated by TurbSim (v1.06.00, 21-Sep-2012) on
    07-Jan-2014 at 12:50:45.

    Processed 1442 time steps of 20-Hz full-field data (72.05 seconds).
 Running ServoDyn.
 Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows/Matlab,
 ).

  OpenFAST completed.

Error using Run_OpenLoop (line 12)
Error reported by S-function 'FAST_SFunc' in 'OpenLoop/FAST Nonlinear Wind Turbine/S-Function':

**Comment by bjonkman** [comment]
You might try using the OpenFAST `dev` branch, or seeing if the changes from this pull request fixes the issue: https://github.com/OpenFAST/openfast/pull/641.

I would guess that the simulation stopped because of an error, but the error message didn't get printed to the Matlab command window. Given where the simulation stopped, I'd check that it can find the 64-bit controller DLL that it is looking to open in the Interface for Bladed Controllers.

**Comment by madhuri-seeram** [comment]
> Thank you very much [@bjonkman](https://github.com/bjonkman) , i figured out the error, and i like to share it with those who can see this post I had to change the PCMode, VSContrl, HSSBrMode, YCMode values to 4 in the NRELOffshrBsline5MW_Onshore_ServoDyn.dat file. Now it run successfully

I did the same thing with similar error. But its not running for me. I used OpenFAST v 5.0.0

**Comment by jjonkman** [comment]
@madhuri-seeram -- Let's continue the discussion in your related OpenFAST issue: https://github.com/OpenFAST/openfast/issues/3404.
