### ISSUE TITLE
A tiny error in ElastoDyn_IO.f90

### ISSUE THREAD

**Issue by gerwangcy** [OpenFAST/openfast#72]
Dear developers,

there is a tiny error in ElastoDyn_IO.f90, line 3620:
`CALL ReadVar( UnIn, InputFile, InputFileData%NacYaw, "RotSpeed", "Initial nacelle-yaw angle (deg)", ErrStat2, ErrMsg2, UnEc)`

I think the fourth argument should be "NacYaw".

Best,
Chengyu Wang

**Comment by bjonkman** [comment]
This issue can be closed. The fix has already been merged into openfast/dev.

**Comment by rafmudaf** [comment]
It is indeed. Thanks for pointing this out, @bjonkman.
