### ISSUE TITLE
Segmentation fault for SIMULINK version in linux

### ISSUE THREAD

**Issue by abhineet-gupta** [OpenFAST/openfast#730]
**Bug description**
Cannot run the simulink version of OpenFAST due to segmentation fault. The s-function compiles without any issues.
This behavior exists in both main(718d46f7) and dev(216bccbf) branches.
I am showing the results from the dev brach as the main branch has an bug where simulink errors are not reported.

**System Details**
Linux Mint 20.1, MATLAB 2020b, openblas, gcc and gfortran

**To Reproduce**
Following options were used ()
1. cmake .. -DBUILD_OPENFAST_SIMULINK_API=ON -DBUILD_SHARED_LIBS=ON
2. make
3. make install

**Screenshots, if applicable**
The crash report is attached

**OpenFAST Version**
dev(216bccbf)

[matlab_crash_dump.txt](https://github.com/OpenFAST/openfast/files/6373711/matlab_crash_dump.txt)

**Comment by andrew-platt** [comment]
Which model are you testing with?

**Comment by abhineet-gupta** [comment]
I modified the "Run_OpenLoop.m" to run the 5MW_Land_BD_Linear turbine.

**Comment by andrew-platt** [comment]
Did the original "Run_OpenLoop.m" also experience a segmentation fault?

**Comment by abhineet-gupta** [comment]
With the AOC_Wst turbine, I get a weird error shown below.

%%%%%%%%%%%%%%%%%%%
Error reported by S-function 'FAST_SFunc' in 'OpenLoop/FAST Nonlinear Wind Turbine/S-Function':
FAST_InitializeAll: IfW_Init:IfW_UniformWind_Init: Could not read upflow column in uniform wind files. Assuming
upflow is 0.
FAST_InitializeAll:SrvD_Init:SrvD_ReadInput:ReadPrimaryFile:Invalid logical input for file
"/home/abhineet/Documents/MyOpenFAST/openfast/reg_tests/r-test/glue-codes/openfast/AOC_WSt/AOC_WSt_ServoDyn.dat"
occurred while trying to read CompNTMD.
%%%%%%%%%%%%%%%%%%%%%

**Comment by andrew-platt** [comment]
the format of the ServoDyn input file has changed between v2.5.0 and what is currently in the dev branch.  The `CompNTMD` keyword was used v2.5.0 branch, but not in the current `dev` branch.  So it looks like you are running the input files from the dev branch with the v2.5.0 compiled version of OpenFAST.

**Comment by abhineet-gupta** [comment]
I had also tried running the simulations for 'main' branches and got errors as well. 
I can rerun those and share the errors if that helps in debugging. 
(The main branch had a bug that simulink errors were not displayed (fixed in the dev branch) so I thought that might be less useful for bug reporting. )

**Comment by andrew-platt** [comment]
Since your error message states `occurred while trying to read CompNTMD`, the OpenFAST version that simulink is running is not the dev version.  What version does OpenFAST report in the first few output lines?

**Comment by abhineet-gupta** [comment]
The OpenFAST output says:

%%%%%%%%%%%%%%%%%%%%%%%
 OpenFAST-v2.4.0-133-gb913c945-dirty
 Compile Info:
  - Compiler: GCC version 9.3.0
  - Architecture: 64 bit
  - Precision: double
  - Date: Jan  5 2021
  - Time: 21:12:45
 Execution Info:
  - Date: 04/26/2021
  - Time: 09:48:55-0500
%%%%%%%%%%%%%%%%%%%%%%%

Also, heres a screenshot of my git log
![image](https://user-images.githubusercontent.com/49625841/116104132-d2072480-a675-11eb-85ec-c57b217578f8.png)

**Comment by andrew-platt** [comment]
commit b913c945 is on the main branch from 4 months ago.  Can you recompile your currently checked out version and rerun the create_FAST_SFunc.m script?  I would expect to see the git hash ending in `-g216bccbf` in the OpenFAST output if you actually are using the dev version that is checked out.

![Screen Shot 2021-04-26 at 9 04 32 AM](https://user-images.githubusercontent.com/2745453/116105303-6bcad380-a66e-11eb-9ef3-eaea8679affe.png)

**Comment by abhineet-gupta** [comment]
Just to make sure, when you say recompile, you mean I should run the following commands (with the current checked out version)

1) cmake .. -DBUILD_OPENFAST_SIMULINK_API=ON -DBUILD_SHARED_LIBS=ON
2) make
3) make install

**Comment by andrew-platt** [comment]
Yes.  First though, delete everything in the build directory (`rm -rf *` inside the build directory).  This will make absolutely certain that there are no leftover modules from a prior build.

You may also want to get the recent tags (git doesn't grab them by default for some reason): `get fetch --all --tags`

**Comment by abhineet-gupta** [comment]
Alright, will do.

**Comment by andrew-platt** [comment]
One other thought that @rafmudaf brought up is to check the install path.

In the `CMakeCache.txt` file within the build directory, what does the entry for the `CMAKE_INSTALL_PREFIX` variable show?  Is that the same as the location specified in the `create_FAST_SFunc.m`?  If not, it is possible that an older version at the location specified in the `create_FAST_SFunc.m` script is getting linked in the mex-function.

**Comment by abhineet-gupta** [comment]
> One other thought that @rafmudaf brought up is to check the install path.
> 
> In the `CMakeCache.txt` file within the build directory, what does the entry for the `CMAKE_INSTALL_PREFIX` variable show? Is that the same as the location specified in the `create_FAST_SFunc.m`? If not, it is possible that an older version at the location specified in the `create_FAST_SFunc.m` script is getting linked in the mex-function.

The ``CMakeCache.txt`` has the following like
CMAKE_INSTALL_PREFIX:PATH=/home/abhineet/Documents/MyOpenFAST/openfast/install

which is same as what I am using in ``create_FAST_SFUNC.m``
```
if ( ispc ) % Windows PC
        installDir = '../../../install';
        outDir = fullfile(installDir, 'lib');
        % If there are shared libraries does it work for outDir to be the local directory?
    else
        installDir = '../../../install';  %%%%%%% <<<<<<<<< **Here**
        outDir = '.';
    end
```

**Comment by abhineet-gupta** [comment]
> Yes. First though, delete everything in the build directory (`rm -rf *` inside the build directory). This will make absolutely certain that there are no leftover modules from a prior build.
> 
> You may also want to get the recent tags (git doesn't grab them by default for some reason): `get fetch --all --tags`

@andrew-platt 
I tried the following based on your comments
1) cd openfast
2) rm -rf ./build
3) rm -rf ./install
4) mkdir ./build
5) cd ./build
6) cmake .. -DBUILD_OPENFAST_SIMULINK_API=ON -DBUILD_SHARED_LIBS=ON
7) make -j12
8) make install
9) cd glue-codes/simulink/src/
10) rm ./FAST_SFunc.mexa64
11) rm ../examples/FAST_SFunc.mexa64
12) edit ``create_FAST_SFunc.m`` (to ensure correct options for ``linux built_with_visualStudio = false`` and ``installDir = '../../../install;`` )
13) cp ./FAST_SFunc.mexa64 ../examples/
14) run ``Run_OpenLoop.m`` with AOC_WSt turbine

I get the following output in matlab
```
OpenFAST-v2.4.0-133-gb913c945-dirty
 Compile Info:
  - Compiler: GCC version 9.3.0
  - Architecture: 64 bit
  - Precision: double
  - Date: Jan  5 2021
  - Time: 21:12:45
 Execution Info:
  - Date: 04/26/2021
  - Time: 11:16:55-0500
```

and the same error
%%%%%%%%%%%%%%%%%%%
Error using Run_OpenLoop (line 12)
Error reported by S-function 'FAST_SFunc' in 'OpenLoop/FAST Nonlinear Wind Turbine/S-Function':
FAST_InitializeAll: IfW_Init:IfW_UniformWind_Init: Could not read upflow column in uniform wind files. Assuming
upflow is 0.
FAST_InitializeAll:SrvD_Init:SrvD_ReadInput:ReadPrimaryFile:Invalid logical input for file
"../../../reg_tests/r-test/glue-codes/openfast/AOC_WSt/AOC_WSt_ServoDyn.dat" occurred while trying to read
CompNTMD.
%%%%%%%%%%%%%%%%%%%

**Comment by andrew-platt** [comment]
I'm surprised the version info didn't change.  What does `git describe --tags` return?  I'm expecting to see something like `v2.5.0-1017-g216bccbf8`

**Comment by rafmudaf** [comment]
Also, can you do `find /usr -name *openfast*`?

**Comment by bjonkman** [comment]
Also, note that the compile date says `Jan 5 2021`. It is definitely not using the openfast library file that you just built.

**Comment by abhineet-gupta** [comment]
> Also, can you do `find /usr -name *openfast*`?

Ah, Nice catch. The output is 

```
/usr/local/include/openfast
/usr/local/lib/libopenfast_prelib.so
/usr/local/lib/libopenfast_postlib.so
/usr/local/lib/libopenfastlib.so
/usr/local/bin/openfast
```

I guess it is prioritizing older version of OpenFAST which have on my system with higher priority path.
My bad, and sorry for the oversight.

Is there an easy way to remove the OpenFAST in /usr/local? or should I just remove all the OpenFAST files from /usr folder?

I will try to run the correct version of OpenFAST meanwhile to ensure that no segmentation fault occurs.

**Comment by rafmudaf** [comment]
There's no catch-all, but you can do these things:

```
find /usr/local -name *openfast* -delete
find /usr/local -name *dyn*
# If there's something related to OpenFAST (aerodynlib, beamdynlib, etc), delete those
ls /usr/local/include
# Remove anything here related to OpenFAST
```

**Comment by abhineet-gupta** [comment]
Thank you all for the help. I got the simulation working although I had some more trouble with LAPACK libraries.

My understanding after some reading on the issue is that OpenBLAS includes 'LAPACK' library but not 'LAPACKE' which is needed for OpenFAST. This can be fixed with 

``sudo apt install liblapacke liblapacke-dev``

and then running the following (in a new terminal to avoid any mixup)

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path to openfast/install/lib>
export BLAS_VERSION=libopenblas.so
export LAPACK_VERSION=liblapacke.so
matlab
```

Hope this helps someone.

**Comment by rafmudaf** [comment]
For our reference, what was the LAPACK error you found and fixed by installing LAPACKE?

**Comment by abhineet-gupta** [comment]
If I use the following options 
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path to openfast/install/lib>
export BLAS_VERSION=libopenblas.so
export LAPACK_VERSION=libopenblas.so
matlab
```
I get the following error (which was fixed by using LAPACKE)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Error using Run_OpenLoop (line 12)
Error in 'OpenLoop/FAST Nonlinear Wind Turbine/S-Function' while executing C MEX S-function 'FAST_SFunc', (mdlStart),
at time 0.0.
Caused by:
    Error using Run_OpenLoop (line 12)
    LAPACK loading error:
    /usr/lib/x86_64-linux-gnu/libopenblas.so.0: undefined symbol: LAPACKE_sbdsdc
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by rafmudaf** [comment]
Got it, thanks.
