### ISSUE TITLE
Running OLAF

### ISSUE THREAD

**Issue by KatrijnChys** [OpenFAST/openfast#737]
Hello

When I try to run OLAF I get following error:

`FAST_Solution:FAST_AdvanceStates:B1:BD_GA2:BD_BoundaryGA2:ExtractRelativeRotation:BD_CrvExtractCrv
:BD_CheckRotMat:Passed invalid rotation matrix
FAST_AdvanceStates:B2:BD_GA2:BD_BoundaryGA2:ExtractRelativeRotation:BD_CrvExtractCrv:BD_CheckRotMa
t:Passed invalid rotation matrix
FAST_AdvanceStates:B3:BD_GA2:BD_BoundaryGA2:ExtractRelativeRotation:BD_CrvExtractCrv:BD_CheckRotMa
t:Passed invalid rotation matrix`

Everything works fine when I run BEM. I changed WakeMod to 3, AFAeroMod to 1 and I added the OLAF input file. 
Do I need to add another file or change another parameter?

Kind regards
Katrijn Chys

**Comment by andrew-platt** [comment]
The errors you are seeing are from the structural code BeamDyn that is used in your model.  I'm really puzzled why BeamDyn would run fine with BEM but fail badly with OLAF.  One possible thought is that the loads coming from OLAF are dramatically different at some point.  @ebranlard, do you have any thoughts on differences in startup transient loads from OLAF?

A few other questions:

- Which version of OpenFAST?
- How far into the simulation do you get this error?
- Which turbine model is this?  Is it one of the regression test models, or a different one?

**Comment by KatrijnChys** [comment]
Version 2.5.0
5MW onshore model from reg_test

I get the error before the simulation starts.
`**************************************************************************************************
OpenFAST

Copyright (C) 2021 National Renewable Energy Laboratory
Copyright (C) 2021 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v2.5.0-dirty
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 2021
 - Architecture: 64 bit
 - Precision: double
 - Date: Mar 21 2021
 - Time: 11:29:35
Execution Info:
 - Date: 04/28/2021
 - Time: 16:46:28+0200

OpenFAST input file heading:
    FAST Certification Test #26: NREL 5.0 MW Baseline Wind Turbine (Onshore)

Running ElastoDyn.
Nodal outputs section of ElastoDyn input file not found or improperly formatted.
Running BeamDyn.
Nodal outputs section of BeamDyn input file not found or improperly formatted.
Running BeamDyn.
Nodal outputs section of BeamDyn input file not found or improperly formatted.
Running BeamDyn.
Nodal outputs section of BeamDyn input file not found or improperly formatted.
Running AeroDyn.
Nodal output section of AeroDyn input file not found or improperly formatted.
Running FVW.
 - Directory:         C:\Users\Katrijn Chys\openFASTclone\openfast\build\bin\5MW
 - RootName:          OLAF\INFLOW_5ms\5MW_Land_BD_DLL_WTurb\5MW_Land_BD_DLL_WTurb.
 - No OpenMP support
Running InflowWind.
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows, ).
Using legacy Bladed DLL interface.
 Time: 0 of 100 seconds.

FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:SrvD_CalcOutput:DLL_controller_call:Run
ning with torque and pitch control of the NREL offshore 5MW baseline wind turbine from DISCON.dll
as written by J. Jonkman of NREL/NWTC for use in the IEA Annex XXIII OC3 studies.


FAST_Solution:FAST_AdvanceStates:B1:BD_GA2:BD_BoundaryGA2:ExtractRelativeRotation:BD_CrvExtractCrv
:BD_CheckRotMat:Passed invalid rotation matrix
FAST_AdvanceStates:B2:BD_GA2:BD_BoundaryGA2:ExtractRelativeRotation:BD_CrvExtractCrv:BD_CheckRotMa
t:Passed invalid rotation matrix
FAST_AdvanceStates:B3:BD_GA2:BD_BoundaryGA2:ExtractRelativeRotation:BD_CrvExtractCrv:BD_CheckRotMa
t:Passed invalid rotation matrix

 FAST encountered an error at simulation time 0 of 100 seconds.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.`

**Comment by jjonkman** [comment]
Dear @KatrijnChys,

If you switch from modeling the blades with BeamDyn (`CompElast` = 2) to modeling the blades with ElastoDyn (`CompElast` = 1), how does the simulation perform?

Best regards,

**Comment by KatrijnChys** [comment]
Olaf runs when I change CompElast to 1 but everything in the output file is indicated as NaN.

![image](https://user-images.githubusercontent.com/64846405/116431929-835db400-a848-11eb-9268-2cccfc3140d5.png)

**Comment by andrew-platt** [comment]
That seems like a pretty clear indication that either there is a setup error (possibly with the OLAF input files), or OLAF is not initializing something correctly.

Can you attach the OLAF input files you are using?

**Comment by jjonkman** [comment]
I would also add that it is difficult to know what has happened because the output does not begin until 50-s into the simulation.  I would suggest setting `TStart` = 0 s to debug.

**Comment by KatrijnChys** [comment]
This is the input file
[Elliptic_OLAF.txt](https://github.com/OpenFAST/openfast/files/6393272/Elliptic_OLAF.txt)

I changed the TStart to 0s and ran again. Now I only get the values for 0s.

**Comment by ebranlard** [comment]
It's probably related to the regularization. I think your OLAF file is based on the elliptic wing case, which attempts to match a theoretical result and does not use regularization (values of 0).  As a first try, you can set `RegDeterMethod=1`. It will try to setup the parameters for you, but this is still in beta. You'll still need to update the size of the near wake and far wake. 

You can find some guidelines on how to setup the important parameters of OLAF here: https://ebranlard-openfast.readthedocs.io/en/f-weis_olaf/source/user/aerodyn-olaf/RunningOLAF.html#guidelines
(this will soon be part of the dev documentation of OpenFAST). 

I hope this will solve your issues.  Keep us in touch!

**Comment by ebranlard** [comment]
I should also add, that when using OLAF with BeamDyn, you might want to change the time step of OLAF to a multiple of the glue code time step, so that it's something more manageable like 0.1 or 0.01 depending on your RPM (see the guidelines above). 

OLAF will then overcycle. This is a beta feature as well, but it should work.

**Comment by KatrijnChys** [comment]
Using the guidelines, I calculated that I needed a time step of 0,08 sec. This gave an error. I adjusted the time step to 0,03 sec and recalculated the other values.
When I run it with a time step of 0,03 sec for 80 sec it takes 14 hours, but the output values are OK.

Thank you for your help, kind regards
Katrijn Chys
