### ISSUE TITLE
Bug report: OpenFAST v2.6, array bounds in Morison module

### ISSUE THREAD

**Issue by jacket-max** [OpenFAST/openfast#757]
Hello, everyone

I use the source program and input file downloaded from Github, but the following error occurred in the hydrodyn module during simulation:
 **************************************************************************************************
OpenFAST v2.6
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 1600
 - Architecture: 32 bit
 - Precision: single
 - Date: May 17 2021
 - Time: 11:08:28
Execution Info:
 - Date: 05/17/2021
 - Time: 20:51:37+0800

OpenFAST input file heading:
    FAST model of the NREL 5MW Reference Wind Turbine, onshore version 1.00

Running ElastoDyn.
Nodal outputs section of ElastoDyn input file not found or improperly formatted.
Running AeroDyn14.
Running InflowWind.
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows, ).
Using legacy Bladed DLL interface.
Running HydroDyn.
forrtl: severe (408): fort: (2): Subscript #1 of the array NODEINDX has value 4 which is greater than the upper bound of 3

Image              PC        Routine            Line        Source
openfast_Win32_De  04172D71  Unknown               Unknown  Unknown
openfast_Win32_De  03631CD1  _MORISON_mp_FLIPM        1364  Morison.f90
openfast_Win32_De  03646394  _MORISON_mp_SETUP        1789  Morison.f90
openfast_Win32_De  036513ED  _MORISON_mp_MORIS        1895  Morison.f90
openfast_Win32_De  0122E1A9  _HYDRODYN_mp_HYDR        1365  HydroDyn.f90
openfast_Win32_De  0088B700  _FAST_SUBS_mp_FAS         789  FAST_Subs.f90
openfast_Win32_De  00872F6B  _FAST_SUBS_mp_FAS          60  FAST_Subs.f90
openfast_Win32_De  0081163E  _MAIN__                    91  FAST_Prog.f90
openfast_Win32_De  046150FF  Unknown               Unknown  Unknown
openfast_Win32_De  04905FDE  Unknown               Unknown  Unknown
openfast_Win32_De  04905EC0  Unknown               Unknown  Unknown
openfast_Win32_De  04905D6D  Unknown               Unknown  Unknown
openfast_Win32_De  04905FF8  Unknown               Unknown  Unknown
KERNEL32.DLL       7764FA29  Unknown               Unknown  Unknown
ntdll.dll          77797A7E  Unknown               Unknown  Unknown
ntdll.dll          77797A4E  Unknown               Unknown  Unknown

**Comment by andrew-platt** [comment]
Are you running one of the regression tests, or a different hydodynamic model?

**Comment by jacket-max** [comment]
I am using the same input file of HydroDyn and SubDyn downloaded from GitHub for simulating the OC3 monopile and OC4 JACKET. When I disable the HydroDyn module, other modules can be used normally.
