### ISSUE TITLE
Regression test cannot generate plots

### ISSUE THREAD

**Issue by Miamilan** [OpenFAST/openfast#758]
Hi all,

I have installed OpenFAST on VMware virtual machine of Ubuntu 18.04. After running the regression tests, I got some failures as follows

![image](https://user-images.githubusercontent.com/18329134/118644991-f25b7680-b810-11eb-9eca-775e402d5ed2.png)

Then I ran the command in the terminal
python manualRegressionTest.py ../build/reg_tests/glue-codes/openfast linux gnu 1e-5 -p -n -v -case UAE_Dnwind_YRamp_WSt
to check the plots, 

![image](https://user-images.githubusercontent.com/18329134/118646144-62b6c780-b812-11eb-9575-0d6909461154.png)

All the test files exist in /build/reg_tests/glue-codes/openfast

![image](https://user-images.githubusercontent.com/18329134/118646422-c4773180-b812-11eb-9589-9ac01d79eb99.png)

It only generated a html. file without plots:

![image](https://user-images.githubusercontent.com/18329134/118646601-fab4b100-b812-11eb-9dac-636ead82025d.png)

I have installed the Bokeh in Python, so how can l generate the plots and then solve the failure cases? 

Thank you.

Haoran.

**Comment by rafmudaf** [comment]
In the second image, you are getting an error regarding the OpenFAST executable not being found when you are running the command to generate plots.

Try replacing this command:
```
python manualRegressionTest.py ../build/reg_tests/glue-codes/openfast linux gnu 1e-5 -p -n -v -case UAE_Dnwind_YRamp_WSt
```

With this:
```
python manualRegressionTest.py ../build/glue-codes/openfast linux gnu 1e-5 -p -n -v -case UAE_Dnwind_YRamp_WSt
```

The difference is the path to your OpenFAST executable: `../build/reg_tests/glue-codes/openfast` vs `../build/glue-codes/openfast`.

**Comment by Miamilan** [comment]
Hi @rafmudaf 

Thank you for your reply. It still does not work by changing the command:

![image](https://user-images.githubusercontent.com/18329134/118657206-da3e2400-b81d-11eb-87ba-ac8635baef24.png)

There are only some CMake-related files in the ../build/glue-codes/openfast:

![image](https://user-images.githubusercontent.com/18329134/118657754-52a4e500-b81e-11eb-90f6-f2fee5939b25.png)

**Comment by rafmudaf** [comment]
Ah sorry, one more try:
```
python manualRegressionTest.py ../build/glue-codes/openfast/openfast linux gnu 1e-5 -p -n -v -case UAE_Dnwind_YRamp_WSt
```

**Comment by Miamilan** [comment]
Thank you @rafmudaf ,

It also failed to generate plots, but the execution results show 'Using gold standard files with machine-compiler type linux-gnu':

![image](https://user-images.githubusercontent.com/18329134/118666885-19707300-b826-11eb-944b-b761185a2ac7.png)

**Comment by rafmudaf** [comment]
Can you show the contents of the log for that case? It's in `openfast/build/reg_tests/glue-codes/openfast/UAE_Dnwind_YRamp_WSt/UAE_Dnwind_YRamp_WSt.log`.

**Comment by Miamilan** [comment]
OK, @rafmudaf 

[UAE_Dnwind_YRamp_WSt.log](https://github.com/OpenFAST/openfast/files/6506206/UAE_Dnwind_YRamp_WSt.log)

**Comment by LuckyYubo** [comment]
> Can you show the contents of the log for that case? It's in `openfast/build/reg_tests/glue-codes/openfast/UAE_Dnwind_YRamp_WSt/UAE_Dnwind_YRamp_WSt.log`.

Hi @rafmudaf, I also try it on the macOS but it also failed to generate plots.
