### ISSUE TITLE
Add the control TMD to Simulink with S-function

### ISSUE THREAD

**Issue by salicto** [OpenFAST/openfast#761]
Hello everyone,
I am looking to connect the TMD module with Simulink in order to develop a complete instrumentation and control system. I contacted Professor Lackner (he developed this module) but unfortunately he did not have the solution. So I ask the openfast user community if they have worked on this part. 

Thank you in advance for any help you could give me,

Best Regards

Tom

**Comment by andrew-platt** [comment]
Hi Tom,

We have completed the passing of control signals from the Bladed controller interface to the StC module (formerly TMD) in the following pull request: https://github.com/OpenFAST/openfast/pull/664. 

If you need to pass the StC signals in from Simulink, you can follow the example for how the cable controls are passed to Simulink.  You will need to expand the arrays on the C library (FAST_Library.h) and set the appropriate data handling in the FAST_Library.f90.  Within ServoDyn, you will need to complete the passing of those signals through in the `StCControl_CalcOutput` routine in the ServoDyn.f90.

Regards

**Comment by salicto** [comment]
Hi Andrew,

Thank you for your comment, I will take a closer look at this module.

Regards,

**Comment by ALpadisa** [comment]
Dear  @Andrew,

I am going to use "openfast-f-StrucCtrl_controls" to complete the TMD simulation in simulink, when I used VS2017 to compile your file before, the following problems occurred when generating s-Func. I don't know why?
![image](https://user-images.githubusercontent.com/41632071/135413130-eb6a2d22-222a-4c38-b889-921f93d18766.png)
Or describe as
`
4>FASTlib_x64_Matlab.lib(mapapi.obj): found MSIL .netmodule or a module compiled with /GL; is using /LTCG to restart the link; add /LTCG to the link command line to improve linker performance
4>FASTlib_x64_Matlab.lib(SysMatlabWindows.obj): error LNK2001: Unresolved external symbol MEXPRINTF
4>..\..\build\bin\\openfast_x64.exe: fatal error LNK1120: 1 unresolved external command

`
Looking forward to your reply

Regards

**Comment by ALpadisa** [comment]
dear Andrew
Today, when I used matlab to run the file'openLoop.mdl' in'...\openfast-f-StrucCtrl_controls\glue-codes\simulink\examples', the following situation occurred, and I still can’t answer after consulting a lot of information , Here to ask you for advice

![image](https://user-images.githubusercontent.com/41632071/135451558-e5e1f3d3-6389-462e-bd49-84d8e4c694dc.png)

The file I run is "...\StC_test_OC4Semi\StC_test_OC4Semi.fst" 
Regards,

**Comment by jjonkman** [comment]
Dear @ALpadisa,

From the error, it sounds like the version of your input file is incompatible with the version of OpenFAST you are running.  Can you clarify from which branch of OpenFAST you compiled the source code and from which branch you obtained the input file(s)?  Providing the full links to your files would help.

Best regards,

**Comment by ALpadisa** [comment]
Dear @jjonkman 
I am very glad that you can reply to my news. The Openfast file I compiled comes from
`
https://github.com/andrew-platt/openfast/tree/f/StrucCtrl_controls
`
The input file comes from
`
https://github.com/openfast/r-test
`
My goal is to add TMD module in Simulink
Best regards,

**Comment by jjonkman** [comment]
Dear @ALpadisa,

The input file format has changed between the version of OpenFAST you have compiled and the input files from the OpenFAST v3.0 r-test.  I'll let @andrew-platt respond regarding where an input file compatible with the version of OpenFAST you are compiling can be found.  Alternatively, you can modify the input files based on the errors you are receiving; reviewing the Echo files may help.

Best regards,

**Comment by andrew-platt** [comment]
Dear @ALpadisa,

There are some input file differences between the OpenFAST v3.0 and the `f/StrucCtrl_controls` branches.  For the latter, the corresponding input files can be found in this branch for r-test: https://github.com/OpenFAST/r-test/tree/f/StrucCtrl_controls

Regards

**Comment by ALpadisa** [comment]
Dear Andrew,

Thank you very much for your reply, I will check it carefully！

Regards,

**Comment by QAlexande** [comment]
dear @andrew-platt 
Sorry to bother you again. How do I input an external force in simulink for this version of [openFAST](https://github.com/andrew-platt/openfast/tree/f/StrucCtrl_controls)? Just like the picture below 
![image](https://user-images.githubusercontent.com/41632071/136747124-78f5a862-5e87-454c-9991-efffb930ae33.png)
Regards,

**Comment by QAlexande** [comment]
dear @andrew-platt 
Sorry to bother you ！ How do I input an external force in simulink for this version of [openFAST](https://github.com/andrew-platt/openfast/tree/f/StrucCtrl_controls)? Just like the picture below 
![image](https://user-images.githubusercontent.com/41632071/136747124-78f5a862-5e87-454c-9991-efffb930ae33.png)
Regards,

**Comment by QAlexande** [comment]
Dear @jjonkman 
Thank you very much for replying to my email. If I want to modify the source code of Openfast, what information should I refer to? Can you give me some details?
Best regards,
