### ISSUE TITLE
Error compiling in Windows Ubuntu WSL 2: "recompile with -fPIE"

### ISSUE THREAD

**Issue by hgropelli** [OpenFAST/openfast#765]
I tried to compile openfast in Windows wsl 2 - Ubuntu 20.04. But after the make command the shell asks to recompile with -fpie, i tried the command make -j6 -fpie, but is not a recognizable command according to make.
**Bug description**
```
[ 99%] Linking Fortran executable openfast
/usr/bin/ld: ../../modules/map/libmapcpplib.a(mapapi.c.o): relocation R_X86_64_32 against symbol `cable_library_meter' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../modules/map/libmapcpplib.a(maperror.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../modules/map/libmapcpplib.a(mapinit.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../modules/map/libmapcpplib.a(outputstream.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../modules/map/libmapcpplib.a(bstrlib.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../modules/map/libmapcpplib.a(jacobian.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../modules/map/libmapcpplib.a(lineroutines.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../modules/map/libmapcpplib.a(numeric.c.o): relocation R_X86_64_32 against symbol `inner_function_evals' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make[2]: *** [glue-codes/openfast/CMakeFiles/openfast.dir/build.make:126: glue-codes/openfast/openfast] Error 1
make[1]: *** [CMakeFiles/Makefile2:1843: glue-codes/openfast/CMakeFiles/openfast.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX static library libopenfastlib.a
[100%] Built target openfastlib
make: *** [Makefile:136: all] Error 2"
```
[CMakeCache.txt](https://github.com/OpenFAST/openfast/files/6526695/CMakeCache.txt)
[log.txt](https://github.com/OpenFAST/openfast/files/6526697/log.txt)

**To Reproduce**

git clone https://github.com/OpenFAST/OpenFAST.git
cd OpenFAST
mkdir build
cd build
cmake ../
make -j6

**OpenFAST Version**
I tried the releases v2.5.0 and v2.6.0, but i got the same behaviour.

**System Information (please complete the following information):**
Windows 10 Pro; 21H1; 19043.985; Windows Feature Experience Pack 120.2212.2020.0
"wsl -l -v
NAME            STATE           VERSION
Ubuntu-20.04    Running         2"

**Comment by rafmudaf** [comment]
I don't have a good guess on this, but one thing that stands out from the CMakeCache is that you're C++ and C compilers are those distributed with OpenFOAM. Can you try installing GCC (`apt-get install gcc`) and reconfiguring CMake? You'll have to delete your existing CMakeCache.txt since you are changing the compiler.

**Comment by hgropelli** [comment]
Thank you!
@rafmudaf Your guess is correct.
I don't know why cmake linked to c++ and c of openfoam, i had already installed gcc and other requirements.
