### ISSUE TITLE
SC_InputType now SC_DX_InputType

### ISSUE THREAD

**Issue by psakievich** [OpenFAST/openfast#766]
**Bug description**
When compiling AMR-Wind with OpenFAST the autogenerated types have now changed from `SC_[type]` to `SC_DX_[type]`.  This causes the build of AMR-Wind to fail since we use the generated types in our code. These types look like they are autogenerated from `SuperController_Registry.txt`. It's not clear to me what caused this change by looking through the commits. @rafmudaf it seems like it might be related to your commit [here ](https://github.com/OpenFAST/openfast/commit/8fabb647332548fa682644f473a342cafc1c9c55)?

Anyways, I mainly want to understand what caused this change and if there is any platform specific things I need to be aware of.  If the types now just have `_DX_` in them then I will update our code accordingly.

**To Reproduce**
Compile openfast with c++ support on Mac OS Catalina.
Check the types in the `SCDataEx_Types.h` header.

**Expected behavior**
Types will all have `DX` in them now.

**OpenFAST Version**
dev commit `479683ed0859f306a79690a91d5df3c02cbdb761`

**Comment by bjonkman** [comment]
The structure of the super controller was changed in FAST.Farm: https://github.com/OpenFAST/openfast/pull/584/. @gantech can probably tell you about the reasoning behind these changes.

**Comment by psakievich** [comment]
@bjonkman okay thanks. I probably don't need to know the details of why FAST.Farm was changed.  Pretty overwhelming PR there.  So I'll assume `_DX_` is now just inserted into all the type names and resolve the API changes for the function calls.  If that is correct feel free to close the issue.
