### ISSUE TITLE
Drive train dynamics

### ISSUE THREAD

**Issue by alvart-98** [OpenFAST/openfast#772]
Hello,

Which is the difference between the variables 'RotTorq' and 'RtAeroMxh'? Aren't they supposed to provide the torque on the rotor due to the wind and its own dynamics?

Also, how would you introduce the term due to the losses of the gearbox in the state-space system of the drive train dynamics?

[Jr + Jg N^2, -Jg N^2 ][theta_r]_dd + [0, 0][theta_r] + [0, 0][theta_r]_d =  Q_r - Q_g N
[  -Jg N^2  ,   Jg N^2][ nu    ]_dd + [0, K][ nu    ] + [0, B][ nu    ]_d =  Q_g N

Thank you for your time.

**OpenFAST Version**
OpenFAST-v2.0.0

**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.0.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Nov 27 2018
  - Time: 17:19:38
 Execution Info:
  - Date: 08/06/2021
  - Time: 10:00:00-11:00:00

**System Information (please complete the following information):**
 - OS: Windows 10
 - Compiler: Intel Fortran oneAPI HPC Toolkit

**Additional context**
Matlab & Simulink: 2018b & 2020b

**Comment by jjonkman** [comment]
Dear @alvart-98,

AeroDyn output RtAeroMxh is the aerodynamic applied torque, Q_r in your state-space model.

ElastoDyn output RotTorq is the reaction torque within the drivtrain, K*nu + B*nu_d in your state-space model.

The gearbox friction in OpenFAST is modeled as a torque opposing the motion that is proportional to RotTorq and the gearbox efficiency (GBoxEff).

The following topic on our forum is likely useful for you: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=525.

Best regards,

**Comment by alvart-98** [comment]
Dear @jjonkman,

Thank you very much for this explanation. Now, I fully understand the concepts mentioned in my question.

Kind regards
