### ISSUE TITLE
FAST.Farm - Invalid logical input for file

### ISSUE THREAD

**Issue by ealmquist** [OpenFAST/openfast#785]
Hello,

I am working to run FAST.Farm with the [sample primary input file](https://openfast.readthedocs.io/en/main/source/user/fast.farm/AppendixA.html#fast-farm-primary-input-file) provided (and other openFAST files from previous simulations), but am running into the following issue: 
![image](https://user-images.githubusercontent.com/86681519/124804205-075aa900-df28-11eb-890b-98ed8ea4aa6f.png)

It appears that my value of "False" for "ChkWndFiles" is not being read correctly, and I'm not sure why.  As seen in the text file, I'm also using "1" for "Mod_AmbWind", so shouldn't ChkWndFiles be ignored anyways?
![image](https://user-images.githubusercontent.com/86681519/124804422-45f06380-df28-11eb-9a14-82757228c48f.png)

Thanks in advance!

**Comment by jjonkman** [comment]
Dear @ealmquist,

As with any input file processing error, you can always enable the Echo option to debug.

But from what I can tell, it looks like line 14 (WindFilePath) has accidentally been moved to the end of line 13 in your FAST.Farm input file, which is causing FAST.Farm to complain about line 15 (ChkWndFiles).

Best regards,

**Comment by ealmquist** [comment]
Hi @jjonkman,

Thank you for the quick response!  I'll be sure to use Echo next time - I'm still relatively unfamiliar with openFAST and didn't realize that was an option.  

Thanks again,

**Comment by ArnoldTUB** [comment]
Hello @jjonkman,

This issue is closed but the problem regarding [sample primary input file](https://github.com/OpenFAST/openfast/blob/main/docs/source/user/fast.farm/examples/FAST.Farm--input.dat) (line 18 and 19) perseveres.
Thus, I ran into the same error and tumbled across this issue.  

Best regards
Arnold

**Comment by bjonkman** [comment]
@ArnoldTUB, this error often occurs when the input files that you are using are a different version from the version of the code you are using. Make sure that the code you compiled is for the version of input files you have and make adjustments if they are not.
