### ISSUE TITLE
Error while building OpenFAST with visual studio 2019 and intel fortran

### ISSUE THREAD

**Issue by saksiwi** [OpenFAST/openfast#787]
Hi, I'm new to openfast and try to build it with Visual Studio 2019 and intel fortran. I've also installed the Math Kernell.

But the output shows errors like in the picture below...

<img width="668" alt="1" src="https://user-images.githubusercontent.com/80746849/125253757-a51bf280-e2f1-11eb-9279-f24f1ddfacbb.png">

In the solution explorer, besides the FAST_registry and Map_dll, there is a written (Visual studio 2015). Should I use Visual Studio 2015 instead to build it? Thank you.

**Comment by saksiwi** [comment]
Hi, I changed the toolset and it solved the previous problem, but another error appears. 

![image](https://user-images.githubusercontent.com/80746849/125256083-ffb64e00-e2f3-11eb-8f97-0aaaaa359bb0.png)
 
What should I change or is there any thing that I have to change in the configuration? Thanks.

**Comment by bjonkman** [comment]
It looks like the MAP_dll project file may not be building properly. Did you change the toolset for the entire solution? Or just the FAST_Registry project? 

Can you show me your build log or the contents of the "output" window in Visual Studio (starting from the top)?

Also, what version of Intel Fortran are you using?

**Comment by saksiwi** [comment]
I change the toolset for FAST_Registry and also MAP_dll. I change the platform toolset to visual studio 2019 for both. 

[output.txt](https://github.com/OpenFAST/openfast/files/6802610/output.txt)
![image](https://user-images.githubusercontent.com/80746849/125315654-3e1d2e80-e32f-11eb-9ca0-cdd8cd550e5e.png)

I use Intel Fortran Compiler Classic and Fortran Beta for Windows version 2021.3

**Comment by bjonkman** [comment]
The first error in your output.txt file is helpful:
```
1>error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
1>Done building project "MAP_dll.vcxproj" -- FAILED.
```
From the `Project menu` in Visual Studio, select `Retarget solution`, and pick the Windows SDK version that you have installed. Then build again.

**Comment by saksiwi** [comment]
Hi, thank you for the solution. I got it done successfully. 
Next, I want to try modeling the 5MW Turbine to see how OpenFAST works, can I try it directly or should I do the "testing OpenFAST" and the regression first? 
What I did right now is only build solutions in the Visual Studio, what do you recommend for the next step on learning the OpenFAST?

**Comment by jjonkman** [comment]
Dear @saksiwi,

I would always recommend running the OpenFAST r-test to compare your results with the established baselines after compiling OpenFAST yourself.  This way you can be assured the software is functioning a expected.

Best regards,
