### ISSUE TITLE
Hydrodyn and WAMIT

### ISSUE THREAD

**Issue by robytian** [OpenFAST/openfast#792]
Dear all,

1. I set the WaveHS (Significant Wave Height of Incident Waves) of the Hydrodyn module to whatever size, B1HEAVE (Displacement of the 1st Wamit Body Along the Global Z-Axis) and PTFMHEAVE (Platform Vertical Heave (Translational) Displacement) always keeps the same trend and size, I wonder is this right? These problems also manifest in SURGE and SWAY.

2.For the three degrees of freedom of rotational motion, although the trend is the same, but the magnitude is different.

3.Also, is there any correlation between changing the WaveHS in Hydrodyn and the wave height used in WaMit, and then what parameters need to be consistent between the potential flow solution and the parameters set in Hydro?

Best regards，
Tian

**Comment by jjonkman** [comment]
Dear @robytian,

I'm not sure I understand your first two questions; please clarify.  For (1), are you saying that the significant wave height set in HydroDyn is not affecting the platform-heave motion you are seeing output from HydroDyn and ElastoDyn?  Are you using a model NREL has provided or one you have developed yourself?

Regarding (3), the significant wave height is not specified as an input to WAMIT.  The output from WAMIT is independent of sea state.

Best regards,

**Comment by robytian** [comment]
> Dear @robytian,
> 
> I'm not sure I understand your first two questions; please clarify. For (1), are you saying that the significant wave height set in HydroDyn is not affecting the platform-heave motion you are seeing output from HydroDyn and ElastoDyn? Are you using a model NREL has provided or one you have developed yourself?
> 
> Regarding (3), the significant wave height is not specified as an input to WAMIT. The output from WAMIT is independent of sea state.
> 
> Best regards,

Yeah, the point I'm trying to make is that the wave heights used for the solutions calculated in WAMIT don't affect the significant wave height that I set in the Hydrodyn module, right? And if i modify the significant wave height in Hydrodyn, is the platform motion different from the Body1 motion that WAMIT outputs?

**Comment by jjonkman** [comment]
Dear @robytian,

As I said earlier, the significant wave height is not an input to WAMIT.  WAMIT does not output motions for specific irregular sea states.  Instead, WAMIT computes the hydrodynamic properties of the floater (added mass, radiation damping, wave excitation loads, etc.) as a function of frequency.

Best regards,

**Comment by robytian** [comment]
> Dear @robytian,
> 
> As I said earlier, the significant wave height is not an input to WAMIT. WAMIT does not output motions for specific irregular sea states. Instead, WAMIT computes the hydrodynamic properties of the floater (added mass, radiation damping, wave excitation loads, etc.) as a function of frequency.
> 
> Best regards,

Thank you for your answer. I have one more question, why is it true that Platform and B1 have the same displacement but not the same rotation? What causes this?
Best regards,
<img width="804" alt="1" src="https://user-images.githubusercontent.com/86820784/126576959-7abd1b08-e957-45c5-af08-cb4423a31d30.png">

**Comment by jjonkman** [comment]
Dear @robytian,

It looks like the ElastoDyn outputs match the HydroDyn outputs (as expected), but for the rotational outputs, ElastoDyn outputs the rotations in degrees and HydroDyn outputs the rotations in radians.

Best regards,

**Comment by robytian** [comment]
> Dear @robytian,
> 
> It looks like the ElastoDyn outputs match the HydroDyn outputs (as expected), but for the rotational outputs, ElastoDyn outputs the rotations in degrees and HydroDyn outputs the rotations in radians.
> 
> Best regards,

Thank you for your reply!
Best regards,
