### ISSUE TITLE
Line2-to-Point Mapping Search Bug

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/OpenFAST#8]
The Line2-to-Point mesh-mapping algorithm for loads documented in our [AIAA paper](http://www.nrel.gov/docs/fy16osti/63203.pdf) is correct.  However, there is a bug in the implementation of the mapping search part of the algorithm that leads to the problems--basically, while the total integrated loads are correct, the local loads distributed along the Point elements are incorrect when the number of points elements is greater than the number of Line2 nodes.

FAST users have reported this problem in the following forum posts:
https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1767
https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=1701

**Comment by jjonkman** [comment]
Bonnie Jonkman of Envision fixed the bug!  See the commit here: https://github.com/NWTC/NWTC_Library/commit/ba1bed6015efa34c8ca4ba5b4db7c2e5b2b7de80.  The fix can be easily merged into the OpenFAST repo.

**Comment by michaelasprague** [comment]
@ghaymanNREL , would you please merge this fix?  Thanks!
