### ISSUE TITLE
generate load cases

### ISSUE THREAD

**Issue by Unique-Wang** [OpenFAST/openfast#802]
Hi everyone,
     I'm pretty new on here,and these days I wanna use openfast to generate load cases but I really do not know where to start,like how to run them one by one or run them in batch,by the way I have all the data needed,I'm sorry I don‘t even know if I am describing  my questions  in an understandable way,anyways it would be so great if any of you can offer me some help like giving me some instructions or tell me where I can find related information I can refer to，thank u so much!

**Comment by jjonkman** [comment]
Dear @Unique-Wang,

A similar question was asked and answered here: https://github.com/OpenFAST/openfast/issues/658.

Best regards,

**Comment by Unique-Wang** [comment]
Dear @jjonkman ,

I cant thank you enough for your reply,I'm gonna try it right away.

Best regards,
