### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by robeche** [OpenFAST/openfast#809]
**Is your feature request related to a problem? Please describe.**
I would like to define the initial azimuth in the input file

**Describe the solution you'd like**
An additional parameter in the aerodyn driver input file

**Describe alternatives you've considered**
I can't find where to place the initial azimuth in the aerodyn driver code. I could make it in the original openfast code but not in yours, can you help me?

**Comment by jjonkman** [comment]
Dear @robeche,

It is not possible to specify the initial azimuth angle in the current version of the standalone AeroDyn driver input file (where the initial azimuth angle is always assumed to be zero), but this would probably not be too much work to add by modifying the source code. There is also a much more capable standalone AeroDyn driver under development--see: https://github.com/OpenFAST/openfast/pull/688.  I believe the functionality to specify an initial azimuth angle is available in that driver, which will replace the current one, so, I'm closing this issue.

Best regards,

**Comment by robeche** [comment]
Hello Jason,

sorry for my message as I already ask for this at the nrel forum and you replied with the #688 pull request... When i opened this issue i thought i was directly asking at the E.Branlard repository. I downloaded his aerodyn driver but could not find the option to set the initial azimuth.

Kind regards

Robert

**Comment by jjonkman** [comment]
Hi @robeche,

It wont be as simple as giving the azimuth angle, but by setting `BasicHAWTFormat` = False in the new standalone AeroDyn driver, you can specify the orientation of each blade via `BldOrientation_h()`.

Best regards,
