### ISSUE TITLE
Introduce Preconditioning in BeamDyn to Reduce Start-Up Transients and Allow for Large Time Steps

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#81]
BeamDyn often requires small time steps that could be increased if BeamDyn is given better initial conditions that reduce start-up transients.  Addressing this problem may be aided by the currently BeamDyn linearization effort currently under development.

**Comment by rafmudaf** [comment]
@bjonkman I heard you may be currently working on this. Is that true?

**Comment by bjonkman** [comment]
Yes, @rafmudf, this is already included in the set of changes currently in my f/Envision branch.

**Comment by rafmudaf** [comment]
resolved by [OpenFAST#157](https://github.com/openfast/openfast/pull/157)
