### ISSUE TITLE
Python-toolbox

### ISSUE THREAD

**Issue by Unique-Wang** [OpenFAST/openfast#811]
Dear @ebranlard ,

I downloaded your code from https://github.com/OpenFAST/python-toolbox/blob/dev/pyFAST    and tried to run it on Pycharm,but a  problem occurred ,it’s shown in the screenshot below
![1629181782(1)](https://user-images.githubusercontent.com/87693817/129675021-6ad0db3d-2d75-433e-a9f4-5c27c85b126f.png)
![1629181493(1)](https://user-images.githubusercontent.com/87693817/129674470-74d98a00-8c71-4629-bab1-e9d85421baa9.png)
I don't know much about Python,so could you please tell what should I do? Thank you.

Best regards,

**Comment by ebranlard** [comment]
Dear @Unique-Wang , please post this issue on the python-toolbox repository. This is actually a general issue which is independent of the python-toolbox. You problem is "how to install a downloaded python package in pyCharm". Hopefully you can find resources on the internet for that. There are some instructions to install pyFAST in the README of the python-toolbox repository, but I'm not sure how it would work for pyCharm. Keep in touch.
