### ISSUE TITLE
OpenFAST

### ISSUE THREAD

**Issue by AryaThomas** [OpenFAST/openfast#813]
Hello,

Can I use openFAST to analyse a barge with moonpool (mass is not uniformly distributed due to operational machines placed over it) that is not meant to carry a wind turbine by only using hydrodyn, elastodyn for barge propeties and moordyn?
If so, in which module do I have to include the wind effects acting on the barge and how to incorporate the non-uniform mass?

Regards,

**Comment by jjonkman** [comment]
Hi @AryaThomas,

Yes, you could.  To "remove" the wind turbine from ElastoDyn, set the appropriate geometry and mass terms to zero (or close to zero) and disable all but the platform DOFs.  You can place the entire mass, center of mass, and inertias of the barge in the ElastoDyn platform.

However, OpenFAST does not currently support direct wind loading on the substructure.  AeroDyn currently only considers wind loading on the rotor and tower.

Best regards,

**Comment by AryaThomas** [comment]
Thanks Jason.

Is there any way to externally add (couple) the direct wind loading on the substructure  into OpenFAST?

**Comment by jjonkman** [comment]
@AryaThomas,

If you have your own way of calculating wind loading time series (not including relative motion effects), the new Structural Control (StC) submodel of ServoDyn, released in OpenFAST v3.0 (https://github.com/OpenFAST/openfast/pull/607), allows the user to prescribe their own applied loads (forces, moments) at user-specified locations in the blades, nacelle, tower, and substructure.

Best regards,

**Comment by AryaThomas** [comment]
Ok.
Thanks for the information.
