### ISSUE TITLE
r-test and pfunit 

### ISSUE THREAD

**Issue by saksiwi** [OpenFAST/openfast#814]
Hi, I got some confusion while trying to test OpenFAST
I've done the installing and build the OpenFAST with visual studio 2019 and intel fortran. I'm trying to test OpenFast with r-test. I'm reading the documentation and it is said that I have to run pFunit first with cmake. I've cloned the openfast from the github, then r-test and pfunit in openfast folder that I've cloned are empty. Should I clone it separately out of OpenFAST folder or where should I put the r-test and pfunit?

if it is download separately from openfast folder, I tried to download the pfunit folder put it outside openfast folder from github and run it with cmake, then this error below appear:

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
The Fortran compiler identification is Intel 2021.3.0.20210609
The C compiler identification is MSVC 19.29.30038.1
Detecting Fortran compiler ABI info
Detecting Fortran compiler ABI info - done
Determine Intel Fortran Compiler Implicit Link Path
Determine Intel Fortran Compiler Implicit Link Path - done
Check for working Fortran compiler: C:/Program Files (x86)/Intel/oneAPI/compiler/2021.3.0/windows/bin/intel64/ifort.exe - skipped
Checking whether C:/Program Files (x86)/Intel/oneAPI/compiler/2021.3.0/windows/bin/intel64/ifort.exe supports Fortran 90
Checking whether C:/Program Files (x86)/Intel/oneAPI/compiler/2021.3.0/windows/bin/intel64/ifort.exe supports Fortran 90 - yes
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
*** Setting default install prefix to C:/Users/dwino/pFUnit/installed.
*** Override with -DCMAKE_INSTALL_PREFIX=<path>.
Performing Test _LOGICAL_DEFAULT_KIND: SUCCESS (value=4)
Performing Test _INT_DEFAULT_KIND: SUCCESS (value=4)
Performing Test _ISO_INT8: SUCCESS (value=1)
Performing Test _ISO_INT16: SUCCESS (value=2)
Performing Test _ISO_INT32: SUCCESS (value=4)
Performing Test _ISO_INT64: SUCCESS (value=8)
Performing Test _REAL_DEFAULT_KIND: SUCCESS (value=4)
Performing Test _DOUBLE_DEFAULT_KIND: SUCCESS (value=8)
Performing Test _ISO_REAL32: SUCCESS (value=4)
Performing Test _REAL32_IEEE_SUPPORT: FAILURE
Performing Test _ISO_REAL64: SUCCESS (value=8)
Performing Test _REAL64_IEEE_SUPPORT: FAILURE
Performing Test _ISO_REAL128: SUCCESS (value=16)
Performing Test _REAL128_IEEE_SUPPORT: FAILURE

what should I do? Thank you before.

**Comment by rafmudaf** [comment]
Hi @saksiwi 

The r-test and pfunit folders should exist inside of the OpenFAST folder and they should not be empty. These two repositories are included in the OpenFAST project as git-submodules. So, you should use git to clone the submodules directly. From your current OpenFAST directory, use this command: `git submodule update --init --recursive`. For reference, this portion of the documentation is [here](https://openfast.readthedocs.io/en/main/source/testing/index.html#configuring-the-test-suite).

Keep in mind that the testing is only required for new software development. If you will not be making changes to the source code, I recommend that you download the executables from the [GitHub Releases](https://github.com/openFAST/openfast/releases) page or, for linux and Mac, use conda (`conda install -c conda-forge openfast`).

**Comment by saksiwi** [comment]
Hi @rafmudaf , thank you for replying.

I have to use the OpenFAST for modeling 2 MW wind turbine later, now I want to learn modeling 5MW wind turbine that have already been built inside the OpenFAST. If that the case should I do the testing? 

If not, what do you recommend I do to start trying to model the wind turbine? I want to ask to execute the model is it only using command prompt or should I execute it from visual studio or using matlab? Sorry for asking such unimportant question, but hope you can help me.

**Comment by rafmudaf** [comment]
Ok, in this case you do not need to compile the software. Compiling is a process that converts the code written in Fortran into an executable that you can run in the command line (`cmd.exe`). The OpenFAST software contains many input files to describe a turbine model and operating conditions, so you can change the input files as needed without modifying the code. You may know this, but I'm describing the process just in case.

I recommend that you download the files attached to the latest GitHub Release (linked above) in the "Assets" dropdown. Then, from the command prompt try to execute the file `openfast_x64.exe` with no additional arguments. The expected response is for the command prompt to display the syntax of the OpenFAST command line interface. The unexpected response is a pop-up saying something about a missing library.

After validating that the executable runs on your machine, you can move to establishing your turbine model. Please report back after verifying the executable will run.

**Comment by saksiwi** [comment]
Hi @rafmudaf thank you for the explanation!

I've tried to execute the openfast_x64.exe file, and this is the result:

Microsoft Windows [Version 10.0.19042.1165]
(c) Microsoft Corporation. All rights reserved.

C:\Users\dwino>openfast_x64.exe

**************************************************************************************************
OpenFAST

Copyright (C) 2021 National Renewable Energy Laboratory
Copyright (C) 2021 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v3.0.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 1900
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: Jun 23 2021
 - Time: 21:25:05
Execution Info:
 - Date: 08/23/2021
 - Time: 20:53:53+0100


 Syntax is:

    OpenFAST [/h] <InputFile>

 where:

    /h generates this help message.
    <InputFile> is the name of the required primary input file.

 Note: values enclosed in square brackets [] are optional. Do not enter the brackets.

  Invalid syntax: no command-line arguments given.

 Aborting OpenFAST.


Is it the expected result?
I'm sorry for asking this, but the primary input file (for example I want to try to model the 5MW turbine), can you tell me advice me which file to try to model first to see the wind field data from the turbine? I'm a bit lost with all the modules.

Thank you so much in advance!

**Comment by saksiwi** [comment]
Or maybe can you recommend any documentation for starting modeling the 5MW wind turbine?

**Comment by jjonkman** [comment]
Dear @saksiwi,

Yes, this is the expected result if no input file name is specified.  You'll have to add the name of the OpenFAST primary input file as indicated to execute a specific OpenFAST model.  The OpenFAST primary input file typically has a _*.fst_ extension and in this file it lists which OpenFAST modules are enabled and what there input file names / paths are.  The OpenFAST primary input file the land-based version of the NREL 5-MW baseline wind turbine is available in the r-test repository here: https://github.com/OpenFAST/r-test/blob/main/glue-codes/openfast/5MW_Land_DLL_WTurb/5MW_Land_DLL_WTurb.fst.

I hope that helps.

Best regards,

**Comment by saksiwi** [comment]
Dear @jjonkman ,
Hi thank you for your answer. I tried to put the input file, I have 2 question:
1. I have 5MW turbine fst file in the openfast folder that I have cloned before, should I put the openfast_x64.exe file in all the folder that I want to try to run? Sorry if it is a silly question.
2. I have error while running the .fst file. The output is like this:

C:\Users\dwino\OpenFAST\reg_tests\r-test\glue-codes\openfast\5MW_Land_DLL_WTurb>openfast_x64.exe 5MW_Land_DLL_WTurb.fst

**************************************************************************************************
OpenFAST

Copyright (C) 2021 National Renewable Energy Laboratory
Copyright (C) 2021 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v3.0.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 1900
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: Jun 23 2021
 - Time: 21:25:05
Execution Info:
 - Date: 08/23/2021
 - Time: 22:14:21+0100

OpenFAST input file heading:
    FAST Certification Test #18: NREL 5.0 MW Baseline Wind Turbine (Onshore)

Running ElastoDyn.
Nodal outputs section of ElastoDyn input file not found or improperly formatted.
Running AeroDyn.
AD15 Nodal Outputs: Nodal output section of AeroDyn input file not found or improperly formatted.
Skipping nodal outputs.
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 1, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 3, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 1)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 1, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 3, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 2)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 1, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 2, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 3, blade 3)
Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0. (node 4, blade 3)
Running InflowWind.

   Reading a 31x31 grid (145 m wide, 17.5 m to 162.5 m above ground) with a characteristic wind
   speed of 12 m/s. This full-field file was generated by TurbSim (v1.06.00, 21-Sep-2012) on
   07-Jan-2014 at 12:50:45.

   Processed 1442 time steps of 20-Hz full-field data (72.05 seconds).
Running ServoDyn.
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows, ).

FAST_InitializeAll:SrvD_Init:BladedInterface_Init:The dynamic library
.\../5MW_Baseline/ServoData/DISCON.dll could not be loaded. Check that the file exists in the
specified location and that it is compiled for 64-bit applications.

 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.

Do you have any idea, why this is happening? Thank you.

**Comment by jjonkman** [comment]
Dear @saksiwi,

Regarding (1), that would work, but you can also set up an environment variable in Windows so that the OpenFAST executable can be called from any directory without having to duplicate copies of, or move, the executable.

Regarding (2), there are typically one of two reasons you'd git this error:
(a) The name or path to the dynamic library is specified incorrectly in input DLL_FileName in the ServoDyn input file.
(b) The dynamic library you have is compiled for 32 bits while you are using a 64-bit compiled executable of FAST / OpenFAST.

Best regards,

**Comment by rafmudaf** [comment]
@saksiwi On your second question, verify that the DISCON.dll file exists at the path given in the error message. Note that the path is relative to the ServoDyn input file, so it would be 
```
C:\Users\dwino\OpenFAST\reg_tests\r-test\glue-codes\openfast\5MW_Land_DLL_WTurb\.\../5MW_Baseline/ServoData/DISCON.dll
```
If it's not there, you should copy the 64 bit DISCON controller you downloaded from the GitHub Releases page to that location.

**Comment by saksiwi** [comment]
Dear @jjonkman and @rafmudaf ,

Thank you so much for your help! I've executed it successfully and get the output. Now will read the 5MW wind turbine technical report more for the detail. Hope I can understand more. Let me know if you have other suggestions or documents to read for modeling wind turbine.
