### ISSUE TITLE
Choice of axis in BeamDyn

### ISSUE THREAD

**Issue by ptrbortolotti** [OpenFAST/openfast#818]
**Bug description**
The aeroelastic results from BeamDyn are influenced by the choice of the axis. In other words, results differ when I compute the cross sectional properties at the sectional twist centers vs other points, such as the mid-chord.

**To Reproduce**
I have prepared a public repository that we can use https://github.com/ptrbortolotti/debug_BD_AD15_axes during debugging
The repo currently contains three subfolders with the IEA15MW OpenFAST model (v3.0.0)
1) The subfolder debug_BDaxis_BDstandalone contains an example for BeamDyn standalone
2) The subfolder debug_BDaxis_ED contains the files to run the model within OpenFAST, no aerodynamics
3) The subfolder debug_BDaxis_AD contains the example when AD15 is activated

Each subfolder has the BeamDyn input files defined w.r.t. the twist centers and the mid-chord centers. A simple python script (https://github.com/ptrbortolotti/debug_BD_AD15_axes/blob/main/Case0/debug_BDaxis_BDstandalone/compute_c2_axis.py) shows how I computed the 3D axis. Note that I removed the blade prebend from the original model to simplify things.
To get the matrices, I ran ANBA4 at the two points. If necessary, I can prepare a python script that translates the matrices given the offset between the two axes

**Expected behavior**
The two models should return identical results.

**Screenshots, if applicable**
These plots show the blade tip deflections in x/y/z from the BD driver for a constant rpm of 10 and gravity on 
![B1TipTDzr_BD](https://user-images.githubusercontent.com/20641647/131185932-a41fef11-c078-4dd5-b63e-01dbc4236e24.png)
![B1TipTDyr_BD](https://user-images.githubusercontent.com/20641647/131185934-e2f1f6fb-4452-41fd-baaa-19b833fb8171.png)
![B1TipTDxr_BD](https://user-images.githubusercontent.com/20641647/131185935-fa2ec398-8af1-4073-984a-e2a2ebb7c487.png)

The lines are close in x and y, but aren't identical in z (but the delta is tiny and can be justified by some minor discrepancies in the input K and I matrices?)

Differences are still somewhat tiny when OF calls BD.
![ED](https://user-images.githubusercontent.com/20641647/131186195-b514b914-8f00-491a-b09b-b7ba2f7fe7a1.png)

But when aerodynamics are on, the offsets grow visibly
![B2TipTDzr](https://user-images.githubusercontent.com/20641647/131186925-a74e8998-bd5d-40dd-b11a-93fa09adae07.png)
![B2TipTDyr](https://user-images.githubusercontent.com/20641647/131186928-fed42d4e-090e-4a85-8e90-7b0420ea0ff0.png)
![B2TipTDxr](https://user-images.githubusercontent.com/20641647/131186930-a4118e00-963d-42cb-af51-9a7b69782948.png)
![B1TipTDzr](https://user-images.githubusercontent.com/20641647/131186932-fc0dd1ba-656c-4c75-b37f-30b6d3365fa6.png)
![B1TipTDyr](https://user-images.githubusercontent.com/20641647/131186934-eeb5e878-fb55-4262-9bab-fced67832079.png)
![B1TipTDxr](https://user-images.githubusercontent.com/20641647/131186938-35b59a58-eaad-4929-b8a4-f16b9b56a269.png)

**OpenFAST Version**
 OpenFAST-v3.0.0
 Compile Info:
  - Compiler: GCC version 9.2.0
  - Architecture: 64 bit
  - Precision: double
  - OpenMP: No
  - Date: Aug 23 2021
  - Time: 12:04:42
 Execution Info:
  - Date: 08/27/2021
  - Time: 14:22:27-0600

**System Information (please complete the following information):**
 - OS: macOS
 - Compiler: GCC version 9.2.0
 - Compiler settings: standard make

**Comment by pelljam** [comment]
This sounds similar, or possible the same, as an issue cornering the BeamDyn reference origin that I reported in issue #759

**Comment by ptrbortolotti** [comment]
The issue is finally resolved in this fork/branch https://github.com/ptrbortolotti/openfast/tree/stability, especially thanks to this one-line commit https://github.com/ptrbortolotti/openfast/commit/c8011439416925a871cf8d94c10c7abda9397a0a
We are working to update openfast dev, thank you for your patience

**Comment by ptrbortolotti** [comment]
Here a couple plots showing overlapping rotations at blade tip between beamdyn models defined along the twist center and along the mid-chord points for the IEA15 reference wind turbine
![IEA15_RDy_BDst_OF3p0qfit6](https://user-images.githubusercontent.com/20641647/149561998-9cfbc167-100b-4d0d-a4c4-37310063f8f2.png)
![IEA15_RDx_BDst_OF3p0qfit6](https://user-images.githubusercontent.com/20641647/149562004-42bd6fa5-3705-4a28-8beb-bdeb80305a7a.png)
