### ISSUE TITLE
Bug report (FAST.Farm): Fortran runtime error: Cannot write to file opened for READ

### ISSUE THREAD

**Issue by Helloczm** [OpenFAST/openfast#822]
**Bug description**
When I ran <LESinflow. fstf> of the FAST.Farm example in r-test, I wanted to get a animation of the wind turbine, but just when I thought I had everything set up and started running, the problem occurred.

**To Reproduce**
1. Compile with 'gnu gcc-6.1.0' on CentOS 7
2. Set WrVTK in LESinflow.fst to 2
![image](https://user-images.githubusercontent.com/89171153/132334775-cd832c4a-07c9-4d05-8d83-20ab785d86f6.png)
3. Run 'LESinflow.fstf' case with 'FAST.Farm' command
4. When it was running, the bug occurred
5. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/89171153/132334916-e71ff987-148f-4a76-a725-b15203f59ed4.png)

Thank you very much!

**Comment by Helloczm** [comment]
@jjonkman @NRELAdmin

**Comment by jjonkman** [comment]
Dear @Helloczm,

I don't understand how that error could be associated with the switch from WrVTK from 0 to 2 in the OpenFAST model.  Can you clarify--does FAST.Farm run as expected (to completion) when you run the LESinflow test case without modification of the input parameters or source code?

Best regards,

**Comment by andrew-platt** [comment]
It could be a hard coded unit number somewhere that ends up accessing the wrong file. Might take some digging into the code to find the culprit.

**Comment by Helloczm** [comment]
It was done quite successfully when I used source code or did not make any changes to the input file, the same is true in the TSinflow example. But when I want to get a visual animation of the turbine, I need to set WrVTK to 2.
I tried to set WrVTK to 2 in TSinflow. fst in the TSinflow example and the program still ran successfully and got the output I wanted. However, when I changed the same Settings in LESinflow, I got the bug I mentioned earlier:Fortran runtime error
I recompiled the source code, but the problem persisted after changing the Settings in LES.Compared to the TSinflow runtime, this bug felt like my Fortran couldn't recognize this high-resolution VTK wind file.
My classmates did not encounter this bug at runtime, probably because their version of GCC was different from mine. She uses gcc-7.1.0.
My next step is to try to upgrade GCC to 7.1.0, recompile the source code, and hopefully I can fix this bug.
Thank you very much for your reply, please leave a comment if you want me to provide more information.

**Comment by Helloczm** [comment]
> It could be a hard coded unit number somewhere that ends up accessing the wrong file. Might take some digging into the code to find the culprit.

Ok, I will try to further explore, thank you for your reply！

**Comment by Helloczm** [comment]
The problem is almost solved. The bug was caused by whether OpenMP was enabled in the CMakeLists.txt. Bug will appear if OpenMP is enabled, see the following figure
![image](https://user-images.githubusercontent.com/89171153/132676797-5433e664-bd28-410c-8f6f-85cfd60285fe.png)
Bug can be debugged by turning off the OpenMP option. In other words, there is no parallel computation for the wind turbine visualization file in the LES example.

**Comment by andrew-platt** [comment]
@Helloczm, Thanks for the follow up!

This indicates to me that there are issues with the `GetNewUnit` function when openmp is used.  I'm suspicious two openmp threads are attempting to open files in rapid succession and either the `GetNewUnit` calls in each thread are unaware of each others handing out unit numbers, or both hit the code at the same time and hand out the same unit. @bjonkman, do you have any thoughts on how we can make that thread safe?

@bjonkman, is the openmp parallelization done at the turbine level in FAST.Farm?  If so, maybe a quick hack is to add a `TurbineNumber * 100` to the unit number.

**Comment by Helloczm** [comment]
> @Helloczm, Thanks for the follow up!
> 
> This indicates to me that there are issues with the `GetNewUnit` function when openmp is used. I'm suspicious two openmp threads are attempting to open files in rapid succession and either the `GetNewUnit` calls in each thread are unaware of each others handing out unit numbers, or both hit the code at the same time and hand out the same unit. @bjonkman, do you have any thoughts on how we can make that thread safe?
> 
> @bjonkman, is the openmp parallelization done at the turbine level in FAST.Farm? If so, maybe a quick hack is to add a `TurbineNumber * 100` to the unit number (edit: maybe multiply by a smaller number -- not sure what the limit is on unit numbers).

Dear @andrew-platt 
Thank you for your reply! Expect better performance from FAST. Farm in the future!

**Comment by Helloczm** [comment]
> Following up on this: I can reproduce this issue with full VTK outputs with openMP. I expect to propose a solution for this soon as it is hampering my workflow.

Hello！
I recently found a solution to this problem, and the program works even when OpenMP is open：
![image](https://user-images.githubusercontent.com/89171153/137885347-6d6651e3-bf34-47fd-908e-3a386b7fd9af.png)
The image👆 above shows the VISUALIZATION portion of the .fst primary input file in the LES example. If you change the VTK_fps to the appropriate value, the program will run until the end.
I chose to change the value from 15 to 0.3333, I got 30 frames of turbine visualization.👇
![image](https://user-images.githubusercontent.com/89171153/137886491-1e9b1739-ca20-4eec-b271-e8c346878d60.png)
It matches the number of visual files of the wind farm(in 'vtk_ff')

**Comment by bjonkman** [comment]
This is still an issue. See https://forums.nrel.gov/t/fast-farm/1887/399

I also suspect there is an issue with getting appropriate unit numbers in `GetNewUnit`. @andrew-platt, in one of my earliest Fortran90 training sessions, there was a concern about using any unit numbers > 100. I don't think that is an issue with present day compilers and/or architectures;[ Intel says](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/data-transfer-i-o-statements/components-of-data-transfer-statements/i-o-control-list/unit-specifier-unit.html#unit-specifier-unit) it should be a positive number less than `2^31 - 1`. 

I wonder if using the [`NEWUNIT` specifier](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/file-operation-i-o-statements/open-statement-specifiers/open-newunit-specifier.html) in open statements would be better; not sure if that is thread-safe or not. For a "pseudo-fix", we could use that in `WrVTK_header`, which should at least reduce the time between calling `INQUIRE()` and `OPEN()`.

Otherwise, having another argument to `GetNewUnit` might be a good option (a lower bound for units associated with that turbine instance, like your suggestion of 100*TurbineNumber).
