### ISSUE TITLE
Linearization with BeamDyn

### ISSUE THREAD

**Issue by ptrbortolotti** [OpenFAST/openfast#823]
**Bug description**
The linearization with OF+BeamDyn does not return reliable results in terms of frequency and damping plots. 

@ebranlard and I have been digging and we have isolated a few problems. I report here the current status of things by running the NM80 model between OF 2.3 and OF 2.5.
In OF 2.3, the frequency and damping plots looked like this and the match with ED was satisfactory.
![Campbell](https://user-images.githubusercontent.com/20641647/132407882-fc687f52-a114-4041-95b0-55fb273b8c22.png)

In OF 2.4, the Campbell broke
![Campbell](https://user-images.githubusercontent.com/20641647/132408073-6958c077-340c-4ad1-8aae-72bd02b0390b.png)
but @ebranlard found a patch to BeamDyn_IO.f90 (see here https://github.com/ptrbortolotti/openfast/commit/004de857bb987d0b72383eb2a7bcbc5b66ea52c7) and results now make sense, except at 5 m/s, where @ebranlard is further looking into the code to get to the cause of the spike
![Campbell](https://user-images.githubusercontent.com/20641647/132408155-3f839158-1f8f-4168-826e-7530ad6f8a18.png)

Unfortunately the same patch does not work for OF 2.5, where negative damping is marked at high wind speeds
![Campbell](https://user-images.githubusercontent.com/20641647/132408232-d7e9a1d3-dc24-4d79-80d9-a574410bd7c2.png)
We worked through the commits and we have identified a couple of problematic ones. 

Until commit https://github.com/OpenFAST/openfast/commit/6b5b8660325a706f6172cadf43315683c8a6ddf9, things look the same as OF 2.4 with the patch.
Next, commit https://github.com/OpenFAST/openfast/commit/001b9c00d66f72eadd540289140e8a364c05873e does not compile due to an error in BeamDyn.
Two commits later, https://github.com/OpenFAST/openfast/commit/6abb5cc224cba0658dd74346d9ec95c29e3359a8, the code returns unphysical frequency and damping plots
![Campbell](https://user-images.githubusercontent.com/20641647/132408869-4ac39fec-a7bc-4e7c-a47c-dd98249fb957.png)

I looked at the time histories, and the blade deflections also looked markedly different between commit https://github.com/OpenFAST/openfast/commit/6b5b8660325a706f6172cadf43315683c8a6ddf9 from October 20th and commit https://github.com/OpenFAST/openfast/commit/6abb5cc224cba0658dd74346d9ec95c29e3359a8 from October 21st.

![of2p4](https://user-images.githubusercontent.com/20641647/132409360-a5819f0c-6e93-43d5-8a8b-52565380486c.png)

Something must have happened in between these two commits that is worth revisiting.

**To Reproduce**
The NM80 model is not public, but I can add NREL people to this repo https://github.nrel.gov/pbortolo/debugOF2p4, where the files for 15 different commits and 3 different tags are ready to run. One then needs to compile the corresponding openfast version with the appropriate commit id and possibly add the patch of BeamDyn_IO.f90.

**Expected behavior**
Smoother lines in both the frequency and damping plots would help build confidence in the results. The jump in the time domain response is also worrying.

**OpenFAST Version**
I have run simulations on Eagle compiling OF at the different commits and tags with the patch (https://github.com/ptrbortolotti/openfast/commit/004de857bb987d0b72383eb2a7bcbc5b66ea52c7) with Intel

**Comment by ptrbortolotti** [comment]
The results above included AD15. I ran https://github.com/OpenFAST/openfast/commit/6b5b8660325a706f6172cadf43315683c8a6ddf9 and https://github.com/OpenFAST/openfast/commit/6abb5cc224cba0658dd74346d9ec95c29e3359a8 without AD15 and the resulting Campbell are reported below

![Campbell](https://user-images.githubusercontent.com/20641647/132542662-44e0662c-3963-4880-abda-121cd5528dc1.png)
 
![Campbell](https://user-images.githubusercontent.com/20641647/132542730-d22e4542-aed5-47ef-848b-0c0de203c9ab.png)

The time histories are also different

![tipdx](https://user-images.githubusercontent.com/20641647/132543180-b4e328be-4d30-4add-bb1f-717a6ca0e664.png)
![tipdx2](https://user-images.githubusercontent.com/20641647/132543193-028e15c2-9984-4dc9-a653-fb3ae445a046.png)
![tipdx3](https://user-images.githubusercontent.com/20641647/132543206-ddfc34fc-eb42-4445-aa65-45df7e3ee921.png)

**Comment by ptrbortolotti** [comment]
Quick update. The time histories from the two commits for the BD driver are also fairly different, especially in the RDy rotation

![BDonly](https://user-images.githubusercontent.com/20641647/132597902-a38cd64a-912d-49b8-9f4b-e38eac110b74.png)

My next step is to go back to out simpler tests and check them out for the two commits. I'm afraid we mostly focused on deflections more than rotations, but we'll see if that helps

**Comment by rafmudaf** [comment]
@ptrbortolotti could you verify and document that #1050 fixes this issue?

**Comment by ptrbortolotti** [comment]
I confirm that the issue is resolved in OF 3.2, thank you all
