### ISSUE TITLE
Some questions about FAST.Farm

### ISSUE THREAD

**Issue by Helloczm** [OpenFAST/openfast#829]
Q1: In the wake dynamics module of the FAST.Farm primary input file, the value of NumRadii is 40, and value of dr is 5.0. This means 2(NumRadii-1)dr=2×39×5=390m, but it is out of the low-resolution domain in LES example, I don't understand how it works.

Q2: In the wake dynamics module of the FAST.Farm primary input file, the value of NumPlanes is 140. So what's the distance between the plane and the plane?

See the picture👇(I have not changed the parameter values)
![image](https://user-images.githubusercontent.com/89171153/133459681-90d6c655-cdd8-4fda-a598-0c52875c565a.png)

Q3: In the visualization file generated by FAST.Farm, how can I add the visualization file of turbulence intensity and mean wind speed?

Q4: Is there a separate manual for Super Controller?  Can you send me a copy if you have one?

Those are all my questions about FAST.Farm, and I would appreciate your answers!

**Comment by Helloczm** [comment]
@jjonkman @NRELAdmin

**Comment by jjonkman** [comment]
Dear @Helloczm,

Here are my answers to your questions:

1) I agree with your math.  FAST.Farm permits the wake planes to extend beyond the boundaries of the low-resolution domain, or even leave the domain entirely.  But it is important for the spatial averaging to cover a wide area beyond the wake boundary (especially for larger values of `Mod_Meander`), so, even if portions of a given wake plane extend beyond the boundaries of the low-resolution, this is better then having the wake planes too small.

2) The distance between each wake plane will differ between each pair of planes, but will equal V_plane_norm*`DT_Low`, where V_plane_norm is the convection speed of the wake plane normal to the wake plane, calculated by spatially averaging the disturbed wind velocity field (ambient wind + wake deficits) and projecting along the unit vector normal to the plane.

3) I'm not sure I understand your question.

4) There is not a separate manual, but the super controller available in FAST.Farm is documented [here](https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#super-controller) and [here](https://openfast.readthedocs.io/en/main/source/user/fast.farm/FFarmTheory.html#fast-farm-theory-basis).

Moreover, the [Modeling Guidance](https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#) chapter of the FAST.Farm documentation provides guidance on setting many of the FAST.Farm input parameters.

Best regards,

**Comment by Helloczm** [comment]
> Dear @Helloczm,
> 
> Here are my answers to your questions:
> 
> 1. I agree with your math.  FAST.Farm permits the wake planes to extend beyond the boundaries of the low-resolution domain, or even leave the domain entirely.  But it is important for the spatial averaging to cover a wide area beyond the wake boundary (especially for larger values of `Mod_Meander`), so, even if portions of a given wake plane extend beyond the boundaries of the low-resolution, this is better then having the wake planes too small.
> 2. The distance between each wake plane will differ between each pair of planes, but will equal V_plane_norm*`DT_Low`, where V_plane_norm is the convection speed of the wake plane normal to the wake plane, calculated by spatially averaging the disturbed wind velocity field (ambient wind + wake deficits) and projecting along the unit vector normal to the plane.
> 3. I'm not sure I understand your question.
> 4. There is not a separate manual, but the super controller available in FAST.Farm is documented [here](https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#super-controller) and [here](https://openfast.readthedocs.io/en/main/source/user/fast.farm/FFarmTheory.html#fast-farm-theory-basis).
> 
> Moreover, the [Modeling Guidance](https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#) chapter of the FAST.Farm documentation provides guidance on setting many of the FAST.Farm input parameters.
> 
> Best regards,

**Comment by Helloczm** [comment]
Dear @jjonkman ,
Thank you very much for your answers to my questions, which are very helpful to me!
Now I want to improve on my third question:
Q3: The FAST.Farm wind visualization file I have so far only shows the wind speed, but I also want to get the average wind speed and turbulence intensity visualization file, what should I do?

Best regards,

**Comment by jjonkman** [comment]
Dear @Helloczm,

The visualization output from FAST.Farm contains the instantaneous wind velocity at each output time step.  You can derive the average wind speed, wind speed standard deviation, turbulence intensity, etc. from this via customized post-processing, but that functionality is not built into FAST.Farm.

Best regards,

**Comment by Helloczm** [comment]
> Dear @Helloczm,
> 
> The visualization output from FAST.Farm contains the instantaneous wind velocity at each output time step. You can derive the average wind speed, wind speed standard deviation, turbulence intensity, etc. from this via customized post-processing, but that functionality is not built into FAST.Farm.
> 
> Best regards,

OK, thanks you very much!
