### ISSUE TITLE
Increase time-step

### ISSUE THREAD

**Issue by saksiwi** [OpenFAST/openfast#832]
Hi all, 

I have question-related to Tmax and DT while I am trying to execute the input file. I run 5MW_Land DLL_WTurb.fst. Initially from the glue code, the TMax is 60s. I tried to increase it, for 65s it is a success, but for 70s it makes an error that said that FF wind array was exhausted at 65.31s. 

I tried to look at previous issues and I have several question: 
1. There is solution that asked me to take a look at variable speed control. I take a look at the settings and it is "user-defined from Bladed-style DLL". I have no idea how can I edit the Discon.dll? Or what should I do with that one?

2. Another solution that I read is that I have to increase the wind file (src: https://github.com/OpenFAST/openfast/issues/563). The wind filed that is used as far as I understand is NRELOffshrBsline5MW_InflowWind_12mps.dat. The settings mentioned that the wind file type is from binary turbsim. May I know how can I edit the 90m_12mps_twr.bts file? Does the content of the bts file is same with 90m_12mps_twr.inp file? If it is the same, is it the usable time that I have to change to increase the wind file so I can increase the time step?

Thank you!

**Comment by saksiwi** [comment]
Hi @jjonkman, 

Sorry for just replying now. Thank you so much for your help, now it's working for me. 

I have an additional question but sorry if it is unnecessary to ask. What I did is that I copy the 90m_12mps_twr.inp file in turbsim folder to regenerate the .bts file then copy the file again in openfast folder (the wind baseline folder). It's a bit redundant to do that back and forth. Should I put turbsim folder inside openfast folder or the other way around? 

Thank you before.

**Comment by jjonkman** [comment]
@saksiwi,

I'm not really understanding your question, but you shouldn't need to copy files back and forth between directories.  You can specify the path to the actual TurbSim output file you want to use within the OpenFAST's InflowWind input file.

Best regards,

**Comment by saksiwi** [comment]
Hi @jjonkman 

I have another question regarding the time step. I've increased the increased the usable time to 630s so it's worked properly like I talked before. Now I want to increase the module time-step (DT) to 0.04s but it got the error (I attached the error below). Is there any maximum DT that I can use? Or is there any way that I can increase DT? Because I want to run around 10 minutes for the simulation, but I want to have time step bigger than 0.04s. 

Hope you can help, thank you.
