### ISSUE TITLE
Run IEA15MW Test

### ISSUE THREAD

**Issue by robytian** [OpenFAST/openfast#840]
I modified the file in test （IEA-15-240-RWT-UMaineSemi） by referring to the Openfast3.0 format. When I run it, I get the following problem
![6SJ5HQ8KA_6U LX (T28`65](https://user-images.githubusercontent.com/86820784/134680880-9b7bfec7-3094-4b8a-811a-9ef29fca403d.png)
:Please help to answer, thank you.

Best regards,

**Comment by jjonkman** [comment]
Dear @robytian,

Given the Mach error appearing just after model initialization, would guess there is something incorrect in your conversion to OpenFAST v3.0 or in your model setup.  But it is difficult to guess what the problem is.  I would double check your conversion steps.

Best regards,

**Comment by robytian** [comment]
I downloaded the example of IEA15MW-SEMI for OPENFAST3.0 on the [](https://github.com/NREL/ROSCO_toolbox)
It can be run after just downloading, but when I generated the BTS wind file, the following error occurred.
![image](https://user-images.githubusercontent.com/86820784/134765189-e143367a-93a5-4989-b630-5811675dba7e.png)
wind file parameters:
![TUKK5J5P}JL_P3_9TX{H3$O](https://user-images.githubusercontent.com/86820784/134765229-2e942229-0406-4051-8c9c-bc3165e5a200.png)

**Comment by jjonkman** [comment]
Dear @robytian,

Can you clarify where you obtained the model you are running and what you changed in the input file(s)?  You say you are running an OpenFAST v3.0 model of the IEA Wind 15-MW reference wind turbine, but the message you are reporting references the baseline controller for the NREL 5-MW wind turbine.  Could you be using the wrong controller?

Best regards,

**Comment by robytian** [comment]
On the Windows system I use, I downloaded the DISCON,dll of version 2.4 through your link and copied it to the corresponding location of version 3.0. The following error occurred. I suspect that the 2.4 and 3.0 controllers are not shared and need to be recompiled. How do I find the controller source code for IEA15MW-UMainSemi model? How do i compile it?
![123](https://user-images.githubusercontent.com/86820784/135240876-0c90c1c8-40ae-44aa-9f80-6f5bf0bd7a4b.png)
Best regards,

**Comment by nikhar-abbas** [comment]
Hi @robytian,
ROSCO is used as the de-facto controller for the IEA 15MW wind turbine. You can download the .dll for the most recent tagged release here:
https://github.com/NREL/ROSCO/releases/tag/v2.3.0

You can also follow the following instruction to compile the source code directly:
https://rosco-toolbox.readthedocs.io/en/latest/source/install.html#rosco-controller

Either way, please make sure that ServoDyn properly points to your compiled .dll. Using full file paths can help reduce any sources of confusion.

Best,
Nikhar

**Comment by robytian** [comment]
> Hi @robytian, ROSCO is used as the de-facto controller for the IEA 15MW wind turbine. You can download the .dll for the most recent tagged release here: https://github.com/NREL/ROSCO/releases/tag/v2.3.0
> 
> You can also follow the following instruction to compile the source code directly: https://rosco-toolbox.readthedocs.io/en/latest/source/install.html#rosco-controller
> 
> Either way, please make sure that ServoDyn properly points to your compiled .dll. Using full file paths can help reduce any sources of confusion.
> 
> Best, Nikhar

Thank you very much！
