### ISSUE TITLE
floating overflow&floating divide by zero

### ISSUE THREAD

**Issue by shuilifjfj** [OpenFAST/openfast#862]
I compiled the Aerodyn_Driver program under this address (https://github.com/ebranlard/openfast/tree/f/driver), but when I run different input files, I get a floating overflow&floating divide by zero error. What is this? The cause? How to solve it.
[The content of the main input file.docx](https://github.com/OpenFAST/openfast/files/7326243/The.content.of.the.main.input.file.docx)

**Comment by jjonkman** [comment]
Dear @shuilifjfj,

Can you share the exact error as written to the command prompt?

Best regards,
