### ISSUE TITLE
Implement the RanLux Pseudo-Random Number in HydroDyn For Wave Generation

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#89]
HydroDyn invokes an intrinsic pseudo-random number generator (pRNG) to derive the internal wave kinematics time series from the wave frequency and direction spectra.  However, the intrinsic pRNG is different across different compilers and operating systems, making cross comparisons of time-domain response difficult.

TurbSim also uses a pRNG to derive wind time series from the wind spectrum (among other uses).  In addition to an intrinsic pRNG, TurbSim also has a built-in pRNG named RanLux (implemented in Fortran source code).  If RanLux where moved to the NWTC_Library, it could be used by FAST modules.  It is recommended to add the RanLux pRNG to the NWTC_Library and use it as an optional pRNG within HydroDyn.  (The intrinsic pRNG is initialized with 2 seeds; the RanLux pRNG is initialized with 1 seed and is selected by setting the second random seed to the RanLux keyword.)  Once implemented, when the RanLux pRNG is selected in HydroDyn, it will then be possible to have identical wave kimenatics time series to enable cross comparisons of time-domain responses across different compilers and operating systems.

**Comment by rafmudaf** [comment]
Using a HydroDyn standalone test case with irregular waves (WaveMod 2), I've found that the wave elevation calculation differs between GNU and Intel compilers, as shown in the plot below.

![compiler_diff](https://user-images.githubusercontent.com/13797903/87964988-ac167900-ca80-11ea-9b36-3f38f260aa97.png)
