### ISSUE TITLE
Bug report：why there are so many "This directive is not standard F2003." when I complier openfast

### ISSUE THREAD

**Issue by YIR11** [OpenFAST/openfast#910]
1>FAST_Library.f90
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(40): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(72): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(89): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(167): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(241): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(350): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(363): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(405): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(459): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(591): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(616): warning #7025: This directive is not standard F2003.
1>D:\wind_farm_control\openfast_code\openfast\modules\openfast-library\src\FAST_Library.f90(729): warning #7025: This directive is not standard F2003.
1>Linking...
 **************************************************************************************************

 OpenFAST-v3.0.0
```

**System Information (please complete the following information):**
 - OS: <e.g.Windows10>
 - Compiler: <VS15>


**Additional context**
<Add any other context about the problem here.>

**Comment by bjonkman** [comment]
`FAST_Library.f90` is used to build OpenFAST as a dynamic library (for example, to be used with Simulink). The way dynamic libraries are built--particularly on Windows--requires some capabilities that aren't built into the Fortran 2003 standard language definition, so it must use extensions to the language definition. The VS build files check for non-standard Fortran 2003, so on `FAST_Library.f90` you'll get a warning about the `ATTRIBUTES DLLEXPORT` statement on each subroutine that can be accessed by a program calling the DLL. Those warnings are expected and can be ignored.

**Comment by YIR11** [comment]
Thanks!
Same warning will also appear, when some other files are used to compiled, such as: OrcaFlexInterface.f90; FVW_Subs.f90; SysIVF.f90; etc. Can they also be ignored?

**Comment by bjonkman** [comment]
Yes. Generally the Sys*.f90 files (e.g., SysIVF.f90) will contain the system-specific (non-standard) Fortran code, so most of the warnings will be there. OrcaFlexInterface is another one that calls a DLL, so that has some non-standard code, too. FVW_Subs has a routine that should probably be moved to the Sys*.f90 files. I wouldn't worry about any of those warnings. If you are developing code and see new warnings, you should pay attention to them, though, to make sure they are expected (and that your code will work with different compilers and/or different systems).
