### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by halayoy** [OpenFAST/openfast#913]
**Dear all,  whether openfast has the ability to receive dynamic input information（not .hh files） and execute real-time simulation?**

**Comment by jjonkman** [comment]
Dear @halayoy,

Can you clarify your question?  What type of "dynamic input" are you referring to; are you referring to full-field turbulent wind, e.g., as generated from TurbSim?

Whether OpenFAST can run at real time or not depends on the functionality (modules/features) enabled and time step.  This is generally easier for larger wind turbines that spin slower and have low natural frequencies and more difficult for offshore wind turbines and for rotors with highly flexible blades that require BeamDyn.

Best regards,

**Comment by halayoy** [comment]
Dear @jjonkman,

Thanks for your answer，I didn't clarify my question clearly.  

My "dynamic input" means the input information（wind speed and direction）can feed to Openfast model in the form of data streams(from the Network Communications or other ways)，not the .hh or .bts input files. 

So whether OpenFAST can run at  real-time mode with dynamic input data streams in Linux platform？I think that would be a interesting feature.

**Comment by halayoy** [comment]
Dear @jjonkman ,

Thanks for your suggestions!
