### ISSUE TITLE
Unexpected results when PtfmRefztRot <>0

### ISSUE THREAD

**Issue by rdamiani** [OpenFAST/openfast#914]
**Bug description**
When the BEM hydrodynamic solution is attained with a reference frame not aligned with the expected global inertial frame in OpenFAST, the parameter PtfmRefztRot could be used to rotate results from BEM to the OpenFAST coordinate system. Yet, simple decay simulations associated with a floater and PtfmRefztRot=180-deg do not appear to reproduce the correct response.  This might have implications for regular simulations results as well, and it appears to be a bug. 

**To Reproduce**
1. Run two simple test cases with any floater and potential flow mode, e.g., OC4 Semi Test Case from r-test directory, with no wind or wave enabled, and with an initial PtfmPitch of 5 deg, and with PtfmRefztRot=0-deg and 180-deg, respectively.
2. Examine PtfmPitch output by the simulations and check associated frequency
3. Examine differences

**Expected behavior**
In a potential flow solution, a still water pitch-decay case should return the same frequency response when the floater is rotated 180 deg. 

**Screenshots, if applicable**
<Add screenshots to help explain your problem.>
 
 Results for a barge
![image](https://user-images.githubusercontent.com/8195507/141185066-fed97a5e-0242-4212-8c17-4cae093d317b.png)

Results for the OC4 Semi
![image](https://user-images.githubusercontent.com/8195507/141193088-c423d681-a3fd-4732-9934-d6e3f49c6e35.png)

**OpenFAST Version**
**************************************************************************************************
OpenFAST

Copyright (C) 2021 National Renewable Energy Laboratory
Copyright (C) 2021 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v3.0.0-4-g8c054308-dirty
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 1910
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: Jul 01 2021
 - Time: 20:11:24
Execution Info:
 - Date: 11/10/2021
 - Time: 12:32:23-0700

**System Information (please complete the following information):**
 - OS: Windows 10
 - Compiler: Intel

**Additional context**
<Add any other context about the problem here.>

**Comment by andrew-platt** [comment]
The ITI barge case doesn't even stay upright in this test -- probably because it is only potential flow and doesn't contain any hydrostatic buoyancy from Morison elements.  This is definitely a bug.  Thanks for reporting it @rdamiani!

**Comment by jjonkman** [comment]
Closed by PR #915.
