### ISSUE TITLE
about dynamic wake model

### ISSUE THREAD

**Issue by HEUMK** [OpenFAST/openfast#927]
Hello,everybody.
I have some questions about DWM theory.

Question 1: after using the DWM model of fast. Farm, I want to deduce the Wake-Deficit model. According to the user guide, I know that the momentum equation used is eq. (1), but I get eq. (2) by deriving the thin shear layer (TL) approximation. I find that the Wake-Deficit model ignores the influence of the second term on the right. Why?

Question 2: we know the eddy visibility formulation expressions the influence of the ambient vapor (first term on the right-hand side) and wake shear layer (second term) on the vapor stresses in the wake, formula 3. According to the mixed length theory, I know that the eddy visibility is equal to the second term, but what theory is the first term on the right hand side based on? I have read all the articles on DWM development and quoted the three articles of Ainslie [1-3], but there are no resources on the Internet. Does anyone know how this is derived? Or have anyone share these three articles?

[1] Ainslie, J. F., 1986, “Wake Modelling and the Prediction of Turbulence Properties,” Proceedings of the Eighth British Wind energy Association Conference, Cambridge, Mar. 19–21, pp. 115–120.
[2] Ainslie, J. F., 1988, “Calculating the Flow Field in the Wake of Wind Turbines,” J. Wind. Eng. Ind. Aerodyn., 27, pp. 213–224.
[3] Ainslie, J. F., 1985, “Development of an Eddy Viscosity Model for Wind Turbine Wakes,” Proceedings of the BWEA Conference, pp. 61–66.

Best regards,
Yuan.
![p1](https://user-images.githubusercontent.com/55135456/143550485-b6d30eb0-7380-4e38-a205-de908bf66ac3.JPG)

**Comment by jjonkman** [comment]
Dear @HEUMK,

It looks like you asked the same question on our forum.  I've now responded there: https://wind.nrel.gov/forum/wind/viewtopic.php?f=39&t=2847&p=18461.

Best regards,
