### ISSUE TITLE
Deprecating AeroDyn 14

### ISSUE THREAD

**Issue by rafmudaf** [OpenFAST/openfast#93]
It has been mentioned recently that AeroDyn 14 may be phased out in favor of AeroDyn 15. This issue is intended to start that conversation.

@jjonkman Is there anything that is in AeroDyn 14 but not in AeroDyn 15?

**Comment by jjonkman** [comment]
The big things missing from AeroDyn v15 that are in AeroDyn v14 are (1) Generalized Dynamic Wake (GDW) and (2) support for Yujia's Dynamic Wake Meandering (DWM) code.

Regarding (1), we collaborated with Envision Energy to implement and test Dynamic Blade Element/Momentum Theory (DBEMT).  It was intended that DBEMT in AeroDyn v15 will replace the need for GDW.  My understanding is the Envision Energy has given NREL a branch of AeroDyn v15 with DBEMT that NREL needs to review and merge into OpenFAST.

Regarding (2), Yujia's DWM code will be replaced with FAST.Farm, which has been developed as a branch of OpenFAST.  We are currently validating FAST.Farm against SOWFA in preparation for the initial public release.

So, to me, once DBEMT and FAST.Farm have been included in OpenFAST, we can eliminate AeroDyn v14 from OpenFAST.

**Comment by rafmudaf** [comment]
This is resolved by https://github.com/OpenFAST/openfast/pull/754/commits/7c35b9493b2929ed0d666d9d6e903ba155a767d3 in v3.0.0.

**Comment by rafmudaf** [comment]
To clarify, https://github.com/OpenFAST/openfast/commit/7c35b9493b2929ed0d666d9d6e903ba155a767d3 adds a deprecation warning and notes that AD14 will be removed in a future release. Therefore, let's leave this issue open until AD14 is removed from OpenFAST.

**Comment by andrew-platt** [comment]
Completed in 4.0.0 (#2586)
