### ISSUE TITLE
Each parameter of "Full_frequencies" for eigenfrequencies in the SubDyn summary file

### ISSUE THREAD

**Issue by DaraeShin** [OpenFAST/openfast#937]
Dear all,

I woud like to know in Openfast.
I can only see the number values of "Full_frequencies" in #eigenfrequencies.

May I know the parameter corresponding to the number values in #eigenfrequencies?

**Comment by jjonkman** [comment]
@DaraeShin,

I'm not sure I really understand what you are asking.  What do you mean by "the parameter corresponding to the number of values"?  Please clarify.

Best regards,

**Comment by DaraeShin** [comment]
@jjonkman,

![image](https://user-images.githubusercontent.com/95604833/144936452-9db4247d-8981-4e6e-9f1f-e705272a09c0.png)

I want to know the definition of a number corresponding to #1X54 (metrix).

Thanks, @jjonkman

**Comment by jjonkman** [comment]
@DaraeShin,

This just means that there are 54 full-system eigenfrequencies, so, the row vector has 54 elements.

Best regards,

**Comment by DaraeShin** [comment]
@jjonkman,
Thank you for your answer.

How can I get the natural frequency[Hz] below in Full-system Eigenanalysis?
- 1st Tower Fore-Atf
- 1st Tower Side-to-Side
- 1st Drivetrain Torsion
- 1st Blade Collective Flap
- 1st Blade Asymmetric Flapwise Pitch
- 1st Blade Asymmetric Flapwise Yaw
- 1st Blade Asymmetric Edgewise Pitch
- 1st Blade Asymmetric Edgewise Yaw
- 2nd Tower Fore-Atf
- 2nd Tower Side-to-Side
- 2nd Blade Collective Flap
- 2nd Blade Asymmetric Flapwise Pitch
- 2nd Blade Asymmetric Flapwise Yaw

**Comment by jjonkman** [comment]
Dear @DaraeShin,

SubDyn is just a model of the substructure.  So, the "full-system eigenfrequencies" reported in the SubDyn summary file are just for the substructure.  It looks like you are after the natural frequencies of the full wind turbine system (blades + drivetrain + nacelle+ tower + substructure).  These cannot be output from SubDyn.  Calculating these requires the use of the full-system linearization functionality of OpenFAST, as has been discussed before on this issues page (e.g., here: https://github.com/OpenFAST/openfast/issues/480), as well as many times on our forum: https://wind.nrel.gov/forum/wind/.

Best regards,
