### ISSUE TITLE
Possible bug in AFAeroMod

### ISSUE THREAD

**Issue by alessandrazappulla** [OpenFAST/openfast#945]
Hi everyone,
I wrote here mounths ago and I solved successfully the problem, so I try again with another issue. 

I'm analyzing the behavior of a 5MW off-shore wind turbine in steady condition ( no tilt angle, no motion added), with the OpenFast 2.6 version. If I compute the problem using AFAeroMod=1, the result is coherent with my expectations. If I use AFAeroMod=2, even though the problem is still in steady condition, the result is not the same as before in terms of power and thrust. 
I've checked Lift and Drag coefficients and they are quite different between the two cases.

Why the two cases don't give the same results? 
Is it possible that there is a sort of bug in AFAeromod when the case is steady? 

Hoping to be clear enough, thank you in advance.

**Comment by jjonkman** [comment]
Dear @alessandrazappulla,

I think you are referring to the same issue discussed in the following OpenFAST r-test issue: https://github.com/OpenFAST/r-test/issues/20 and the associated forum topic: https://wind.nrel.gov/forum/wind/viewtopic.php?f=2&t=2492.  Hopefully you can further understand the issue and its solutions in these posts.

Best regards,

**Comment by alessandrazappulla** [comment]
Dear Jason,

This is the problem I was talking about! 
Thank you so much, I've just solved the problem downloading the latest version of OpenFast, updating each input file and using UAMod=4. Now everything seems coherent with my expectations.

Best regards,
Alessandra
