### ISSUE TITLE
Unable to generate DISCON.so file in linux

### ISSUE THREAD

**Issue by abhineet-gupta** [OpenFAST/openfast#964]
**Bug description**
The openfast repository contains a visual studio .sln file to generate the DISCON.DLL in "./openfast/vs-build/Discon/" but I can not find a way to generate the similar DISCON.so file in linux.

I tried the following steps
1. cd ./openfast/reg_tests/r-test/glue-codes/openfast/5MW_Baseline/ServoData/DISCON
2. mkdir buildtry
3. cd buildtry
4. cmake ..
      -- The C compiler identification is GNU 11.1.0
      -- The CXX compiler identification is IntelLLVM 2022.0.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /home/abhineet/intel/oneapi/compiler/2022.0.1/linux/bin/dpcpp - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- The Fortran compiler identification is GNU 11.1.0
      -- Detecting Fortran compiler ABI info
      -- Detecting Fortran compiler ABI info - done
      -- Check for working Fortran compiler: /usr/bin/gfortran - skipped
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /home/abhineet/Documents/OpenFAST/openfast/reg_tests/r-test/glue-codes/openfast/5MW_Baseline/ServoData/DISCON/buildtry

5. make
        Scanning dependencies of target DISCON
        [ 50%] Building Fortran object CMakeFiles/DISCON.dir/DISCON.F90.o
        [100%] Linking Fortran shared library DISCON.dll
        [100%] Built target DISCON
6. make install
        [100%] Built target DISCON
        Install the project...
        -- Install configuration: "Release"
        -- Installing: /home/abhineet/Documents/OpenFAST/openfast/reg_tests/r-test/glue-codes/openfast/5MW_Baseline/ServoData/DISCON/../DISCON.dll

But this produced a DISCON.dll file again.
What is the correct procedure to generate the DISCON.so file, and is there documented somewhere (that I might have overlooked)?

**OpenFAST Version**
OpenFAST (tag: v3.0.0) is used.

**Comment by rafmudaf** [comment]
Hi @abhineet-gupta

This is actually producing a valid linux .so file but its renaming it to have the .dll suffix. This is used for the regression tests so that we don't have to maintain three different file sets for the operating systems we support. You can just rename the file to discon.so or change your ServoDyn input file to point to the .dll.

Rafael
