### ISSUE TITLE
Valid Yaw values for OpenFAST

### ISSUE THREAD

**Issue by pablozl92** [OpenFAST/openfast#969]
Hi everyone,

I have asked this in the forum also (https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=2880).

I am studying the behaviour of the OC4 model when wind has high absolute values for PropagationDir, or when wind is aligned with X-axis (hence 0º dir) but the platform is Yawed. In this second case, I have found inestabilities in the simulations (i.e. almost all the variables take values). Moreover, the simulations even abort when checking initial values if PtfmYaw is set to 20 degrees in ElastoDyn (see attached image).

In this conext: could someone confirm me that the theory behind OpenFAST (or FASTv8) lose validity outside the Yaw range of [-15, 15] degrees? I think I have read that in some document, but I cannot find the quote.

Provided that's true: what would be a work-around to simulate the OC4 with high yaw values? Should I set the PtfmYawDOF to False and carry out different simulations with fixed PtfmYaw?

Thank you in advance.

 ![Yaw_Range_Errors_OC4_OpenFAST](https://user-images.githubusercontent.com/92505841/150109643-c662c3f0-df50-4de1-bc28-f31ebac93bdc.PNG)

**Comment by jjonkman** [comment]
Dear Pablo,

I've now responded to your questions on the forum (https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=2880).

Best regards,
