### ISSUE TITLE
How to couple only the AeroDyn and BeamDyn modules?

### ISSUE THREAD

**Issue by ZL6462** [OpenFAST/openfast#974]
Dear all,
I want the calculate only the aero-elastic performance of the wind turbine's rotor, namely don't consider other parts of the wind turbine (e.g. the tower and necelle...). So my question is how to realize the coupling of the AeroDyn and BeamDyn modules, which doesn't include ElastoDyn module, because this part is temporarily not necessary for me.

**Comment by jjonkman** [comment]
Dear @ZL6462,

OpenFAST requires that you always have ElastoDyn enabled, but you can model the drivetrain, nacelle, and support structure rigidly (resulting in the effect you desire) by disabling all structural degrees of freedom in ElastoDyn.  In this case, ElastoDyn is simply used to define basic fixed geometry such as the number of blades, hub height/location, hub radius, shaft tilt, blade precone, and blade pitch.

Please note that you would also need to enable the InflowWind module to specify the wind inflow.

Best regards,

**Comment by ZL6462** [comment]
> Dear @ZL6462,
> 
> OpenFAST requires that you always have ElastoDyn enabled, but you can model the drivetrain, nacelle, and support structure rigidly (resulting in the effect you desire) by disabling all structural degrees of freedom in ElastoDyn. In this case, ElastoDyn is simply used to define basic fixed geometry such as the number of blades, hub height/location, hub radius, shaft tilt, blade precone, and blade pitch.
> 
> Please note that you would also need to enable the InflowWind module to specify the wind inflow.
> 
> Best regards,

**Comment by ZL6462** [comment]
Dear @jjonkman 

Thank for you quick reply, and this is useful for solving my issues.

Best regards,

**Comment by LaurenceWETI** [comment]
Hello [@jjonkman](https://github.com/jjonkman),

Do I understand that correctly, that BD doesn’t have blades to output, and therefore BD uses ED to define parameters such as number of blades?
If a loop through the blades needs to be generated in BD, can a parameter such as `p%NumBl` be used? For example, is such loop in BD feasible?
   ```
   !.... now compute changes in mass matrices based on this
   DO BN=1,p%NumBl   
       DO i=1,p%elem_total
         DO idx_qp=1,p%nqp
            temp_id = (i-1)*p%nqp+idx_qp

            DO k=1,InputFileData%InpBl%station_total

             
                   p%Mass0_QP(1:6,1:6,temp_id) = p%Mass0_QP(1:6,1:6,temp_id) + FluidMass
						   
						   
            ENDDO ! k=InputFileData%InpBl%station_total

         ENDDO ! idx_qp=quadrature point
       ENDDO ! i=element
	ENDDO ! BN=number of blades   

```

Best regards,
Laurence

**Comment by jjonkman** [comment]
Dear @LaurenceWETI,

The data structures of BeamDyn do not store data on a per blade basis.  Instead all BeamDyn knows about is the properties and response of a a single beam.  We get around this in OpenFAST by allocating multiple instances of BeamDyn within the OpenFAST glue code; i.e., essentially the loop through the number of blades that you are proposing takes place in the OpenFAST glue code, not within BeamDyn itself.

Best regards,
