### ISSUE TITLE
Compile OpenFAST using IntelFortran in Linux

### ISSUE THREAD

**Issue by HCKimDaniel** [OpenFAST/openfast#975]
**Is your feature request related to a problem? Please describe.**
The linux system used the gfortan automatically instead of intel Fortran when compiled

**Describe the solution you'd like**
I want to compile OpenFAST with IntelFortran in the Linux system 

**Describe alternatives you've considered**
No Alternatives are considered

**Additional context**
I am using TACC Frontera System for compiling OpenFAST. I want to compile OpenFAST with IntelFortran in the Linux system, but it used the gfortran automatically. Can you help me for me to compile OpenFAST using Intel Fortran in the Linux. 

```
login1.frontera(1015)$ git clone https://github.com/OpenFAST/OpenFAST.git
Cloning into 'OpenFAST'...
remote: Enumerating objects: 49013, done.
remote: Counting objects: 100% (298/298), done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 49013 (delta 176), reused 198 (delta 140), pack-reused 48715
Receiving objects: 100% (49013/49013), 202.92 MiB | 33.46 MiB/s, done.
Resolving deltas: 100% (32219/32219), done.
login1.frontera(1016)$ cd OpenFAST
login1.frontera(1017)$ mkdir build
login1.frontera(1018)$ cd build
login1.frontera(1019)$ cmake ../
-- The CXX compiler identification is GNU 8.3.0
-- The C compiler identification is GNU 8.3.0
-- The Fortran compiler identification is GNU 8.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/apps/gcc/8.3.0/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/apps/gcc/8.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/apps/gcc/8.3.0/bin/gfortran - skipped
-- Checking whether /opt/apps/gcc/8.3.0/bin/gfortran supports Fortran 90
-- Checking whether /opt/apps/gcc/8.3.0/bin/gfortran supports Fortran 90 - yes
-- Performing Test HAS_FORTRAN2008
-- Performing Test HAS_FORTRAN2008 - Success
-- Enabling Fortran 2008 features
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so;/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_gnu_thread.so;/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_core.so;/opt/apps/gcc/8.3.0/lib64/libgomp.so;-lpthread;-lm;-ldl
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so;/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_gnu_thread.so;/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin/libmkl_core.so;/opt/apps/gcc/8.3.0/lib64/libgomp.so;-lpthread;-lm;-ldl;-lpthread;-lm;-ldl
-- Setting system file as: src/SysGnuLinux.f90
-- Configuring done
-- Generating done
-- Build files have been written to: /home1/08330/hckim81/OpenFAST/build
>
```

**Comment by HCKimDaniel** [comment]
Hi!! @rafmudaf As far as I know, intel compiler can be assessed because I used ifort to compile an in-house code in Frontera. Also, I paste and copy the answer for  `which ifort` below. 

`login3.frontera(1001)$ which ifort
/opt/intel/compilers_and_libraries_2020.1.217/linux/bin/intel64/ifort`

`login3.frontera(1004)$ which cmake
/opt/apps/cmake/3.20.3/bin/cmake`

The difference from the previous compiling experience is that cmake is used for the openfast. If I follow the compile process from the website "https://openfast.readthedocs.io/en/main/source/install/index.html#cmake-with-make-for-linux-macos", the frontera system uses the gfortran automatically. Do I need to change the cmake option in the related cmake input file to compile openfast using ifort?

**Comment by rafmudaf** [comment]
Yes, you could try that. Change the value for `CMAKE_FORTRAN_COMPILER` in `openfast/build/CMakeCache.txt` to contain the path from the `which ifort` command. Be sure to run `cmake ..` after saving this change.

However, I think this will not change the math libraries that would have been found by CMake. A safer method might be to set the `FC` environment variable to the path to ifort and start the configuration and compile from scratch. Something like this:
```bash
cd openfast/
rm -rf build
mkdir build && cd build
export FC=/opt/intel/compilers_and_libraries_2020.1.217/linux/bin/intel64/ifort
cmake ..
```

**Comment by HCKimDaniel** [comment]
> 

There is no value for `CMAKE_FORTRAN_COMPILER` in `openfast/build/CMakeCache.txt`
I copy and paste all the passages in CMakeCache.txt below


`# This is the CMakeCache file.
# For build in directory: /home1/08330/hckim81/OpenFAST/build
# It was generated by CMake: /opt/apps/cmake/3.20.3/bin/cmake
# You can edit this file to change values found and used by cmake.
# If you do not want to change any of the values, simply exit the editor.
# If you do want to change a value, simply edit, save, and exit the editor.
# The syntax for the file is as follows:
# KEY:TYPE=VALUE
# KEY is the name of a variable in the cache.
# TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
# VALUE is the current value for the KEY.

########################
# EXTERNAL cache entries
########################

//Path to a program.
CMAKE_ADDR2LINE:FILEPATH=/opt/apps/gcc/8.3.0/bin/addr2line

//Path to a program.
CMAKE_AR:FILEPATH=/opt/apps/gcc/8.3.0/bin/ar

//CXX compiler
CMAKE_CXX_COMPILER:FILEPATH=/opt/apps/gcc/8.3.0/bin/c++

//A wrapper around 'ar' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_CXX_COMPILER_AR:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc-ar

//A wrapper around 'ranlib' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc-ranlib

//C compiler
CMAKE_C_COMPILER:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc

//A wrapper around 'ar' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_AR:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc-ar

//A wrapper around 'ranlib' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_RANLIB:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc-ranlib

//Path to a program.
CMAKE_DLLTOOL:FILEPATH=CMAKE_DLLTOOL-NOTFOUND

CMAKE_FORTRAN_COMPILER:FILEPATH=/opt/intel/compilers_and_libraries_2020.1.217/linux/bin/intel64/ifort

//Path to a program.
CMAKE_LINKER:FILEPATH=/opt/apps/gcc/8.3.0/bin/ld

//Path to a program.
CMAKE_MAKE_PROGRAM:FILEPATH=/bin/gmake

//Path to a program.
CMAKE_NM:FILEPATH=/opt/apps/gcc/8.3.0/bin/nm

//Path to a program.
CMAKE_OBJCOPY:FILEPATH=/opt/apps/gcc/8.3.0/bin/objcopy

//Path to a program.
CMAKE_OBJDUMP:FILEPATH=/opt/apps/gcc/8.3.0/bin/objdump

//Value Computed by CMake
CMAKE_PROJECT_DESCRIPTION:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_HOMEPAGE_URL:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_NAME:STATIC=OpenFAST

//Path to a program.
CMAKE_RANLIB:FILEPATH=/opt/apps/gcc/8.3.0/bin/ranlib

//Path to a program.
CMAKE_READELF:FILEPATH=/opt/apps/gcc/8.3.0/bin/readelf

//Path to a program.
CMAKE_STRIP:FILEPATH=/opt/apps/gcc/8.3.0/bin/strip

//Value Computed by CMake
OpenFAST_BINARY_DIR:STATIC=/home1/08330/hckim81/OpenFAST/build

//Value Computed by CMake
OpenFAST_SOURCE_DIR:STATIC=/home1/08330/hckim81/OpenFAST


########################
# INTERNAL cache entries
########################

//ADVANCED property for variable: CMAKE_ADDR2LINE
CMAKE_ADDR2LINE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_AR
CMAKE_AR-ADVANCED:INTERNAL=1
//This is the directory where this CMakeCache.txt was created
CMAKE_CACHEFILE_DIR:INTERNAL=/home1/08330/hckim81/OpenFAST/build
//Major version of cmake used to create the current loaded cache
CMAKE_CACHE_MAJOR_VERSION:INTERNAL=3
//Minor version of cmake used to create the current loaded cache
CMAKE_CACHE_MINOR_VERSION:INTERNAL=20
//Patch version of cmake used to create the current loaded cache
CMAKE_CACHE_PATCH_VERSION:INTERNAL=3
//Path to CMake executable.
CMAKE_COMMAND:INTERNAL=/opt/apps/cmake/3.20.3/bin/cmake
//Path to cpack program executable.
CMAKE_CPACK_COMMAND:INTERNAL=/opt/apps/cmake/3.20.3/bin/cpack
//Path to ctest program executable.
CMAKE_CTEST_COMMAND:INTERNAL=/opt/apps/cmake/3.20.3/bin/ctest
//ADVANCED property for variable: CMAKE_CXX_COMPILER
CMAKE_CXX_COMPILER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_COMPILER_AR
CMAKE_CXX_COMPILER_AR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_COMPILER_RANLIB
CMAKE_CXX_COMPILER_RANLIB-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_COMPILER
CMAKE_C_COMPILER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_COMPILER_AR
CMAKE_C_COMPILER_AR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_COMPILER_RANLIB
CMAKE_C_COMPILER_RANLIB-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_DLLTOOL
CMAKE_DLLTOOL-ADVANCED:INTERNAL=1
//Path to cache edit program executable.
CMAKE_EDIT_COMMAND:INTERNAL=/opt/apps/cmake/3.20.3/bin/ccmake
//Executable file format
CMAKE_EXECUTABLE_FORMAT:INTERNAL=ELF
//Name of external makefile project generator.
CMAKE_EXTRA_GENERATOR:INTERNAL=
//Name of generator.
CMAKE_GENERATOR:INTERNAL=Unix Makefiles
//Generator instance identifier.
CMAKE_GENERATOR_INSTANCE:INTERNAL=
//Name of generator platform.
CMAKE_GENERATOR_PLATFORM:INTERNAL=
//Name of generator toolset.
CMAKE_GENERATOR_TOOLSET:INTERNAL=
//Source directory with the top level CMakeLists.txt file for this
// project
CMAKE_HOME_DIRECTORY:INTERNAL=/home1/08330/hckim81/OpenFAST
//ADVANCED property for variable: CMAKE_LINKER
CMAKE_LINKER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MAKE_PROGRAM
CMAKE_MAKE_PROGRAM-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_NM
CMAKE_NM-ADVANCED:INTERNAL=1
//number of local generators
CMAKE_NUMBER_OF_MAKEFILES:INTERNAL=1
//ADVANCED property for variable: CMAKE_OBJCOPY
CMAKE_OBJCOPY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_OBJDUMP
CMAKE_OBJDUMP-ADVANCED:INTERNAL=1
//Platform information initialized
CMAKE_PLATFORM_INFO_INITIALIZED:INTERNAL=1
//ADVANCED property for variable: CMAKE_RANLIB
CMAKE_RANLIB-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_READELF
CMAKE_READELF-ADVANCED:INTERNAL=1
//Path to CMake installation.
CMAKE_ROOT:INTERNAL=/opt/apps/cmake/3.20.3/share/cmake-3.20
//ADVANCED property for variable: CMAKE_STRIP
CMAKE_STRIP-ADVANCED:INTERNAL=1
//uname command
CMAKE_UNAME:INTERNAL=/bin/uname`

**Comment by HCKimDaniel** [comment]
There is no value for `CMAKE_FORTRAN_COMPILER` in `openfast/build/CMakeCache.txt`. Do you mean that I need to add the value in `openfast/build/CMakeCache.txt`?

**Comment by rafmudaf** [comment]
Could you post the CMakeCache file here? You can just attach it to a comment rather than copy-paste the contents.

**Comment by HCKimDaniel** [comment]
I posted CMakeCache.txt below


>#This is the CMakeCache file.
#For build in directory: /home1/08330/hckim81/OpenFAST/build
#It was generated by CMake: /opt/apps/cmake/3.20.3/bin/cmake
#You can edit this file to change values found and used by cmake.
#If you do not want to change any of the values, simply exit the editor.
#If you do want to change a value, simply edit, save, and exit the editor.
#The syntax for the file is as follows:
#KEY:TYPE=VALUE
#KEY is the name of a variable in the cache.
#TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
#VALUE is the current value for the KEY.
########################
#EXTERNAL cache entries
########################
//Path to a program.
CMAKE_ADDR2LINE:FILEPATH=/opt/apps/gcc/8.3.0/bin/addr2line
//Path to a program.
CMAKE_AR:FILEPATH=/opt/apps/gcc/8.3.0/bin/ar
//CXX compiler
CMAKE_CXX_COMPILER:FILEPATH=/opt/apps/gcc/8.3.0/bin/c++
//A wrapper around 'ar' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_CXX_COMPILER_AR:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc-ar
//A wrapper around 'ranlib' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc-ranlib
//C compiler
CMAKE_C_COMPILER:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc
//A wrapper around 'ar' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_AR:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc-ar
//A wrapper around 'ranlib' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_RANLIB:FILEPATH=/opt/apps/gcc/8.3.0/bin/gcc-ranlib
//Path to a program.
CMAKE_DLLTOOL:FILEPATH=CMAKE_DLLTOOL-NOTFOUND
//Path to a program.
CMAKE_LINKER:FILEPATH=/opt/apps/gcc/8.3.0/bin/ld
//Path to a program.
CMAKE_MAKE_PROGRAM:FILEPATH=/bin/gmake
//Path to a program.
CMAKE_NM:FILEPATH=/opt/apps/gcc/8.3.0/bin/nm
//Path to a program.
CMAKE_OBJCOPY:FILEPATH=/opt/apps/gcc/8.3.0/bin/objcopy
//Path to a program.
CMAKE_OBJDUMP:FILEPATH=/opt/apps/gcc/8.3.0/bin/objdump
//Value Computed by CMake
CMAKE_PROJECT_DESCRIPTION:STATIC=
//Value Computed by CMake
CMAKE_PROJECT_HOMEPAGE_URL:STATIC=
//Value Computed by CMake
CMAKE_PROJECT_NAME:STATIC=OpenFAST
//Path to a program.
CMAKE_RANLIB:FILEPATH=/opt/apps/gcc/8.3.0/bin/ranlib
//Path to a program.
CMAKE_READELF:FILEPATH=/opt/apps/gcc/8.3.0/bin/readelf
//Path to a program.
CMAKE_STRIP:FILEPATH=/opt/apps/gcc/8.3.0/bin/strip
//Value Computed by CMake
OpenFAST_BINARY_DIR:STATIC=/home1/08330/hckim81/OpenFAST/build
//Value Computed by CMake
OpenFAST_SOURCE_DIR:STATIC=/home1/08330/hckim81/OpenFAST
########################
#INTERNAL cache entries
########################
//ADVANCED property for variable: CMAKE_ADDR2LINE
CMAKE_ADDR2LINE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_AR
CMAKE_AR-ADVANCED:INTERNAL=1
//This is the directory where this CMakeCache.txt was created
CMAKE_CACHEFILE_DIR:INTERNAL=/home1/08330/hckim81/OpenFAST/build
//Major version of cmake used to create the current loaded cache
CMAKE_CACHE_MAJOR_VERSION:INTERNAL=3
//Minor version of cmake used to create the current loaded cache
CMAKE_CACHE_MINOR_VERSION:INTERNAL=20
//Patch version of cmake used to create the current loaded cache
CMAKE_CACHE_PATCH_VERSION:INTERNAL=3
//Path to CMake executable.
CMAKE_COMMAND:INTERNAL=/opt/apps/cmake/3.20.3/bin/cmake
//Path to cpack program executable.
CMAKE_CPACK_COMMAND:INTERNAL=/opt/apps/cmake/3.20.3/bin/cpack
//Path to ctest program executable.
CMAKE_CTEST_COMMAND:INTERNAL=/opt/apps/cmake/3.20.3/bin/ctest
//ADVANCED property for variable: CMAKE_CXX_COMPILER
CMAKE_CXX_COMPILER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_COMPILER_AR
CMAKE_CXX_COMPILER_AR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_COMPILER_RANLIB
CMAKE_CXX_COMPILER_RANLIB-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_COMPILER
CMAKE_C_COMPILER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_COMPILER_AR
CMAKE_C_COMPILER_AR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_COMPILER_RANLIB
CMAKE_C_COMPILER_RANLIB-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_DLLTOOL
CMAKE_DLLTOOL-ADVANCED:INTERNAL=1
//Path to cache edit program executable.
CMAKE_EDIT_COMMAND:INTERNAL=/opt/apps/cmake/3.20.3/bin/ccmake
//Executable file format
CMAKE_EXECUTABLE_FORMAT:INTERNAL=ELF
//Name of external makefile project generator.
CMAKE_EXTRA_GENERATOR:INTERNAL=
//Name of generator.
CMAKE_GENERATOR:INTERNAL=Unix Makefiles
//Generator instance identifier.
CMAKE_GENERATOR_INSTANCE:INTERNAL=
//Name of generator platform.
CMAKE_GENERATOR_PLATFORM:INTERNAL=
//Name of generator toolset.
CMAKE_GENERATOR_TOOLSET:INTERNAL=
//Source directory with the top level CMakeLists.txt file for this
// project
CMAKE_HOME_DIRECTORY:INTERNAL=/home1/08330/hckim81/OpenFAST
//ADVANCED property for variable: CMAKE_LINKER
CMAKE_LINKER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MAKE_PROGRAM
CMAKE_MAKE_PROGRAM-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_NM
CMAKE_NM-ADVANCED:INTERNAL=1
//number of local generators
CMAKE_NUMBER_OF_MAKEFILES:INTERNAL=1
//ADVANCED property for variable: CMAKE_OBJCOPY
CMAKE_OBJCOPY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_OBJDUMP
CMAKE_OBJDUMP-ADVANCED:INTERNAL=1
//Platform information initialized
CMAKE_PLATFORM_INFO_INITIALIZED:INTERNAL=1
//ADVANCED property for variable: CMAKE_RANLIB
CMAKE_RANLIB-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_READELF
CMAKE_READELF-ADVANCED:INTERNAL=1
//Path to CMake installation.
CMAKE_ROOT:INTERNAL=/opt/apps/cmake/3.20.3/share/cmake-3.20
//ADVANCED property for variable: CMAKE_STRIP
CMAKE_STRIP-ADVANCED:INTERNAL=1
//uname command
CMAKE_UNAME:INTERNAL=/bin/uname

**Comment by rafmudaf** [comment]
Did the cmake configuration command (`cmake ..`) end successfully? As in, did it state

```
-- Configuring done
-- Generating done
-- Build files have been written to: <path>/openfast/build
```

If CMake finished correctly, the CMakeCache must contain a variable for the Fortran compiler in the same way that it contains paths to the C++ and C compilers.

**Comment by HCKimDaniel** [comment]
After cmake .., I got the error below 


login3.frontera(1066)$ cmake ..
-- The CXX compiler identification is GNU 8.3.0
-- The C compiler identification is GNU 8.3.0
CMake Error at /opt/apps/cmake/3.20.3/share/cmake-3.20/Modules/CMakeDetermineFortranCompiler.cmake:33 (message):
  Could not find compiler set in environment variable FC:

  /opt/intel/compilers_andlibraries_2020.1.217/linux/bin/intel64/ifort.
Call Stack (most recent call first):
  CMakeLists.txt:18 (project)


CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home1/08330/hckim81/OpenFAST/build/CMakeFiles/CMakeOutput.log".
login3.frontera(1067)$

**Comment by HCKimDaniel** [comment]
OK. I cloned the repository from GitHub again and tried as you commented 

```
cd openfast/
rm -rf build
mkdir build && cd build
export FC=/opt/intel/compilers_and_libraries_2020.1.217/linux/bin/intel64/ifort
cmake ..
```

The message is changed like below after `cmake ..`. I think taht the fortran compiler is successfully changed to ifort based on the message. I will compile openfast again. And let you know the update. Thank you. 

```
login3.frontera(1074)$ cmake ..
-- Enabling Fortran 2008 features
-- Setting system file as: src/SysIFL.f90
-- Configuring done
-- Generating done
-- Build files have been written to: /home1/08330/hckim81/OpenFAST/build
login3.frontera(1075)$ ls
CMakeCache.txt  cmake_install.cmake  glue-codes  modules
CMakeFiles      ftnmods              Makefile    OpenFASTConfig.cmake
login3.frontera(1076)$ cd ..
login3.frontera(1077)$ ls
build  CMakeLists.txt  glue-codes  modules     reg_tests  unit_tests
cmake  docs            LICENSE     README.rst  share      vs-build
login3.frontera(1078)$ rm -rf build
login3.frontera(1079)$ mkdir build && cd build
login3.frontera(1080)$ export FC=/opt/intel/compilers_and_libraries_2020.1.217/l                                                                                                                                                             inux/bin/intel64/ifort
login3.frontera(1081)$ cmake ..
-- The CXX compiler identification is GNU 8.3.0
-- The C compiler identification is GNU 8.3.0
-- The Fortran compiler identification is Intel 19.1.0.20200306
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/apps/gcc/8.3.0/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/apps/gcc/8.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/intel/compilers_and_libraries_2020.1                                                                                                                                                             .217/linux/bin/intel64/ifort - skipped
-- Checking whether /opt/intel/compilers_and_libraries_2020.1.217/linux/bin/inte                                                                                                                                                             l64/ifort supports Fortran 90
-- Checking whether /opt/intel/compilers_and_libraries_2020.1.217/linux/bin/inte                                                                                                                                                             l64/ifort supports Fortran 90 - yes
-- Performing Test HAS_FORTRAN2008
-- Performing Test HAS_FORTRAN2008 - Success
-- Enabling Fortran 2008 features
-- Found MKL: /opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel6                                                                                                                                                             4/libmkl_intel_lp64.so;/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/l                                                                                                                                                             ib/intel64/libmkl_sequential.so;/opt/intel/compilers_and_libraries_2020.1.217/li                                                                                                                                                             nux/mkl/lib/intel64/libmkl_core.so
-- Setting system file as: src/SysIFL.f90
-- Configuring done
-- Generating done
-- Build files have been written to: /home1/08330/hckim81/OpenFAST/build
```

**Comment by rafmudaf** [comment]
Yes, this looks good. At least CMake is able to find your Intel compiler and the Intel MKL library. Please let me know if you're able to compile.

**Comment by HCKimDaniel** [comment]
@rafmudaf Thank you so much!!! It fully works well.
