### ISSUE TITLE
First time: Moving from pre-compiled FASTv8.exe in Windows to OpenFAST compiled on Linux

### ISSUE THREAD

**Issue by victormendoza1983** [OpenFAST/openfast#977]
Dear all,
* I moved from pre-compiled FASTv8.exe in Windows to OpenFAST compiled on Linux
* I am newbie trying to run one of the cases r-test (ex CertTests)
* It seems I have compiled everything correct, but I have NO IDEA how to run the cases
* In Windows it was as simple as writing in the command promt: FASTv.EXE casetotest.fst
* When I try to do the same the same in a Unix terminal it does not work.

Your help is highly appreciated in advance!

![image](https://user-images.githubusercontent.com/97036019/150785165-89b3c823-0cc2-4f94-8d7b-e5bdd55672ec.png)

**Comment by victormendoza1983** [comment]
@jjonkman !
Thanks so much for your kind and fast reply. I will take a look into your comment and come back if needed.
Have a nice week.
Best regards,

**Comment by victormendoza1983** [comment]
Hello @jjonkman ,
Still I can not fix anything :/ . Summarizing, I managed to run cases (for example AOC_YFix_WSt) through ctest option but not directly from the terminal as before.

With ctest
![openfast_ctest](https://user-images.githubusercontent.com/97036019/150966300-b6285ab2-946a-491e-8f5f-43a316ac2094.png)

From terminal
![openfast_terminal](https://user-images.githubusercontent.com/97036019/150966310-eb75898d-1dad-4bf4-aaec-d0095f0fe0f1.png)

I would like to be able to copy a case in another folder and just run through the terminal: openfast test_case.fst but still don't understand how?
Is there any tutorial about how to? 

Thanks in advance for your support and reply!

**Comment by rafmudaf** [comment]
Hi @victormendoza1983 Please rerun the ctest command above with the added `-vv` (these are two "v") flag to get more output and share the results. The command should be

```bash
ctest -R AOC_YFix_WSt -vv
```

**Comment by victormendoza1983** [comment]
Hello guys, 
One update... I managed to install the version OpenFAST -v3.0.0-1, but however it does not run the case directly from the terminal.

![OF1](https://user-images.githubusercontent.com/97036019/151069823-0e619dd7-af07-41de-a65a-6b3fcdf3e1ef.png)


@rafmudaf I ran the ctest as you asked me
![OF2](https://user-images.githubusercontent.com/97036019/151069976-5767486f-765c-4254-84dc-0c1ca1f3ab35.png)

I share you the results ech, log and out (I changed to txt format in order to be able to attach them).
[AOC_YFix_WSt.ech.txt](https://github.com/OpenFAST/openfast/files/7937617/AOC_YFix_WSt.ech.txt)
[AOC_YFix_WSt.log.txt](https://github.com/OpenFAST/openfast/files/7937618/AOC_YFix_WSt.log.txt)
[AOC_YFix_WSt.out.txt](https://github.com/OpenFAST/openfast/files/7937619/AOC_YFix_WSt.out.txt)

Please, let me know whatever additional you need and thanks a lot one more time!

**Comment by rafmudaf** [comment]
That's correct, v3.0 requires files with a slightly different format than those for v2.5. The r-test repository is tricky and nuanced as it was developed for automated testing but we ended up using it as a set of examples.

Try cloning the r-test repository directly (in a different location than your OpenFAST repository) and run the case there.
```bash
cd ~/NRELtools   # For example, move into your NREL tools directory
git clone https://github.com/openfast/r-test -b v3.0.0
cd r-test/glue-codes/openfast/AOC_YFix_WSt
~/NRELtools/openfast/build/glue-codes/openfast -v
# Make sure this shows v3.0.0
~/NRELtools/openfast/build/glue-codes/openfast AOC_YFix_WSt.fst
```

As a side note, the version print in the first screen shot above shows `v3.0.0-1-gebff1b46` whereas the one in the log.txt file attached has `v3.0.0-446-g5e25d5d1`. This first one here is from the `main` branch in the repo and the second one is from the `dev` branch.

**Do you need to compile the code?** On Linux, you can simply install from conda and a precompiled binary will be in your path. See the [docs](https://openfast.readthedocs.io/en/dev/source/install/index.html#conda-installation) for instructions.

**Comment by victormendoza1983** [comment]
Hello @jjonkman  and @rafmudaf !
The last comment @rafmudaf gave me it was the solution.
It seems I was not consistent with the OpenFAST version I installed and the r-test cases I downloaded.
Now with having both for the version 3.0.0 I can run them either through the command ctest and/or directly from terminal.
Thanks a lot for all your support!
