### ISSUE TITLE
About "PotMod=2" (fluid-impulse theory) in HydroDyn

### ISSUE THREAD

**Issue by jiayaomeng** [OpenFAST/openfast#989]
Dear Development Team,

I noticed that there is a publication [(Chan, GKY, Sclavounos, PD, Jonkman, J, & Hayman, G, 2015)](https://asmedigitalcollection.asme.org/OMAE/proceedings-abstract/OMAE2015/V009T09A038/280026) that couples the fluid-impulse theory with FAST to determine the nonlinear hydrodynamic forces on a floating wind turbine. I'm very interested in this method as it takes into account the time-varying wetted body surface with more realistic computational efforts compared to CFD analysis. It would be great if I could benchmark my nonlinear wave-platform interaction model against this one in the future. However, the option "PotMod=2" does not work in HydroDyn and the source code is missing. I completely understand if the codes cannot be made public for the moment. I was wondering if the OpenFast or HydroDyn executable file compiled from the fluid-impulse theory code could by any chance be shared. 

Thank you so much!
Jiayao

**Comment by jjonkman** [comment]
Dear Jiayao,

Unfortunately, fluid-impulse theory (FIT) was never fully implemented, and so, PotMod = 2 is not supported in FAST v8 or OpenFAST.  (FIT was being developed by Godine Kok Yan Chan, a PhD student at MIT, but he graduated before the coupled FIT-FAST code was fully functional.)

Best regards,

**Comment by jiayaomeng** [comment]
Dear Dr. Jonkman,

Many thanks for your reply! It seems from the paper that the difference in the hydrodynamic forces between FIT and HydroDyn is not negligible. May I ask would that be a concern to you as the developer of OpenFAST? Would you consider enhancing HydroDyn to be able to handle the nonlinearities induced by the large platform rotation in the future?

Best wishes,
Jiayao

**Comment by jjonkman** [comment]
Dear Jiayao,

To be honest, I was a bit surprised by some of the differences shown between FIT and HydroDyn.  Based on the validation work we have done comparing OpenFAST/HydroDyn to experimental (wave tank) data, the biggest issues we've seen in the hydrodynamic modeling of floating offshore wind turbines are the difficulty in estimating the drag coefficients and the underprediction of second-order hydrodynamic loads (for excitation of the floating substructure at rigid-body natural frequencies).  We have recently addressed both of these issues for the OC4-DeepCwind semisubmersible--see our recently published paper here: https://www.sciencedirect.com/science/article/pii/S0960148122000635?dgcid=author.  (The asssociated improvements to HydroDyn discussed in the paper will be included in this repository through a new pull request soon.)

While not specific to large floater rotation, we are working on other improvements to HydroDyn that will support the calculation of wave loads at the displaced position of the floating substructure--see: https://github.com/OpenFAST/openfast/pull/970.  (This functionality will better support large translation motion of the floater than large rotational motion.)  To address large floater rotation will require not only hydrodynamic changes, but changes to the structural modules of OpenFAST (ElastoDyn and SubDyn) that assume small floater rotations.

Best regards,

**Comment by jiayaomeng** [comment]
Dear Dr. Jonkman,

Thank you so much for the links! The modifications to the drag coefficients appear to be very effective in reducing the discrepancy between the simulation and experimental measurements in the low-frequency region. The physical interpretation with respect to the viscous effects also makes perfect sense to me. However, I read from Dr. Godine Kok Yan Chan's PhD thesis that the inappropriate neglection of nonlinear effects under the framework of potential flow theory (inviscid flow) could also result in the underprediction of wave forces at both the sum- and difference- frequencies. 
![Screen Shot 2022-02-04 at 5 41 59 PM](https://user-images.githubusercontent.com/79981762/152583248-92893fc5-121b-4ea0-82ca-06c95cc582f7.png)

The paper you shared doesn't mention the sum-frequency region, but I found from your earlier paper https://www.nrel.gov/docs/fy20osti/76210.pdf that the forces in this region predicted by different codes show large discrepancies compared to the experimental results. Though this relatively high-frequency region has limited influence on compliant floating wind turbines, I am very curious whether your modifications could also improve the force prediction in this region.
![Screen Shot 2022-02-04 at 5 57 30 PM](https://user-images.githubusercontent.com/79981762/152583407-2f5e8a0f-6948-4c7f-8457-23ead96d4453.png)

Regarding the new pull request 970, I'm not sure if I understand it correctly, may I confirm with you that only the horizontal displacements (in the O-X-Y plane) of the platform are taken into account to interpolate the instantaneous wave elevation when calculating the wave excitation force? May I ask how big the difference is with and without the inclusion of the platform displacements? Thank you very much!

Best wishes,
Jiayao

**Comment by jjonkman** [comment]
Dear Jiayao,

I agree that sum-frequency effects are not very important for compliant floaters, such as the OC4-DeepCwind semisubmersible or OC3-Hywind spar.  Sum-frequency effects would be much more important to floaters with taut stationkeeping systems, such as tension-leg platforms or taut-line buoys because they can have natural frequencies in the sum-frequency range.

Regarding PR #970, the interpolation of the wave kinematics in the strip-theory solution and wave excitation in the potential-flow solution makes use of the displaced horizontal (X,Y) position of each hydrodynamic analysis node, but uses the undisplaced vertical (Z) position of the each hydrodynamic analysis node.  The big effect that is captured with this is the change in phasing of the wave loads associated with large horizontal displacements.

Best regards,

**Comment by jiayaomeng** [comment]
Thank you Dr. Jonkman. The information is very helpful!

Best wishes,
Jiayao
